- app/controllers/api/v1/billable_metrics_controller.rb
- app/graphql/types/billable_metric_filters/input.rb
- app/graphql/types/billable_metric_filters/object.rb
- app/graphql/types/billable_metrics/create_input.rb
- app/graphql/types/billable_metrics/object.rb
- app/graphql/types/billable_metrics/update_input.rb
- app/serializers/v1/billable_metric_filter_serializer.rb
- app/serializers/v1/billable_metric_serializer.rb
- app/services/billable_metric_filters/create_or_update_batch_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/billable_metric_filters/input_spec.rb
- spec/graphql/types/billable_metric_filters/object_spec.rb
- spec/graphql/types/billable_metrics/create_input_spec.rb
- spec/graphql/types/billable_metrics/object_spec.rb
- spec/graphql/types/billable_metrics/update_input_spec.rb
- spec/requests/api/v1/billable_metrics_spec.rb
- spec/serializers/v1/billable_metric_filter_serializer_spec.rb
- spec/serializers/v1/billable_metric_serializer_spec.rb
- spec/services/billable_metric_filters/create_or_update_batch_service_spec.rb
This PR exposes billable metric filters in both API and GraphQL API
> feat(filter): Handle billable metric filters in GraphQL and API

- .gitignore
- app/services/billable_metrics/aggregations/base_service.rb
- app/services/billable_metrics/aggregations/unique_count_service.rb
- app/services/billable_metrics/aggregations/weighted_sum_service.rb
- app/services/billable_metrics/breakdown/sum_service.rb
- app/services/billable_metrics/prorated_aggregations/sum_service.rb
- app/services/events/stores/base_store.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
This PR refactors the filtering arguments in the events store services:
- Remove the unused `event` argument
- Move the `group` argument as a sub value of a new `filters` one
- Add `grouped_by` and `grouped_by_value` argument in the `filters`
- Add logic to handle `grouped_by_value` when present
> feat(group-by): add grouped_by_value logic to event stores

- app/graphql/types/charges/properties.rb
- app/graphql/types/charges/properties_input.rb
- app/graphql/types/customers/usage/charge.rb
- app/graphql/types/fees/object.rb
- app/serializers/v1/customers/charge_usage_serializer.rb
- app/serializers/v1/fee_serializer.rb
- db/migrate/20240118140703_add_grouped_by_to_cached_aggregations.rb
- db/migrate/20240118141022_add_grouped_by_to_fees.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/graphql/types/charges/properties_input_spec.rb
- spec/graphql/types/charges/properties_spec.rb
- spec/graphql/types/customers/usage/charge_spec.rb
- spec/graphql/types/fees/object_spec.rb
- spec/serializers/v1/customers/charge_usage_serializer_spec.rb
- spec/serializers/v1/fee_serializer_spec.rb
This PR adds:
- A `grouped_by` attribute to the fees table
- A `grouped_by` attribute to the cached_aggregation
- Exposes this attributes in API and GraphQL
- Allow and expose the same attribute to the standard charge model properties in GraphQL
> feat(group-by): Expose grouped_by for fees in GraphQL API

- app/services/billable_metric_filters/create_or_update_batch_service.rb
- app/services/billable_metrics/create_service.rb
- app/services/billable_metrics/update_service.rb
- spec/services/billable_metric_filters/create_or_update_batch_service_spec.rb
- spec/services/billable_metrics/create_service_spec.rb
- spec/services/billable_metrics/update_service_spec.rb
This PR adds a new `BillableMetricFilters::CreateOrUpdateBatchService` to manage billable metric filters
> feat(filter): Create or update service for billable metric filters

- app/graphql/types/adjusted_fees/adjusted_fee_type_enum.rb
- app/graphql/types/adjusted_fees/create_input.rb
- app/graphql/types/fees/object.rb
- app/models/adjusted_fee.rb
- schema.graphql
- schema.json
- spec/graphql/types/fees/object_spec.rb
Currently it is not possible to manually edit the draft invoice through the UI. With this feature it will be possible to adjust fee, remove adjusted values and recalculate draft invoice based on those values.
This PR adds `adjusted_fee` bool attribute to the `fee` graphql object. It will allow FE to recognise if adjusted fee is attached and if `reset` option should be available
> feat (edit-draft-invoice): add adjusted fee bool field in fee graphql object

- Dockerfile
Healthcheck in https://github.com/getlago/lago/blob/main/docker-compose.yml for lago-api relies on curl binary existing in lago-api docker image (it wasn't included). Docker currently floods log files with a failure message:
`Health check for container x error: OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"`
> Update Dockerfile to fix health check reliant on curl binary

- app/models/invoice.rb
- app/services/billable_metrics/aggregations/base_service.rb
- app/services/billable_metrics/aggregations/unique_count_service.rb
- app/services/billable_metrics/aggregations/weighted_sum_service.rb
- app/services/billable_metrics/breakdown/sum_service.rb
- app/services/billable_metrics/prorated_aggregations/sum_service.rb
- app/services/charges/pay_in_advance_aggregation_service.rb
- app/services/events/stores/base_store.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- app/services/fees/charge_service.rb
- app/services/fees/create_pay_in_advance_service.rb
- spec/services/billable_metrics/aggregations/count_service_spec.rb
- spec/services/billable_metrics/aggregations/latest_service_spec.rb
- spec/services/billable_metrics/aggregations/max_service_spec.rb
- spec/services/billable_metrics/aggregations/sum_service_spec.rb
- spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
- spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
- spec/services/billable_metrics/breakdown/sum_service_spec.rb
- spec/services/billable_metrics/breakdown/unique_count_service_spec.rb
- spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
- spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
- spec/services/charges/pay_in_advance_aggregation_service_spec.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
- spec/services/fees/create_pay_in_advance_service_spec.rb
This PR refactors the filtering arguments in the aggregation services:
- Move the `group` argument as a sub value of a new `filters` one
- Add `grouped_by` and `grouped_by_value` argument in the `filters`
- Adapt logic for pay in advance charges
> feat(group-by): handle group for in pay in advance charges

- app/services/events/stores/base_store.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
This PR updates the event stores to add support for grouped aggregation on:
- `count`
- `max`
- `sum`
- `last`
> feat(filter): Add grouped_by logic on events aggregation

- app/graphql/types/fees/object.rb
- app/services/fees/create_pay_in_advance_service.rb
- db/migrate/20240123104811_change_fees_grouped_by_type.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/graphql/types/fees/object_spec.rb
- spec/services/fees/create_pay_in_advance_service_spec.rb
This PR changes the type of `fees#grouped_by` and `cached_aggregations#grouped_by` from an array of `string` to a `JSON`
>  feat(group-by): Change grouped_by type for fees and cached_aggregation

- app/services/payment_provider_customers/adyen_service.rb
70 days is the maximum available expiration time for adyen checkout url. Probably due to timezone or daylight saving time there could be validation issues with setting it to 70 days.
In this PR expiration at field for checkout url is decreased by one day and set to 69 days.
> fix: decrease adyen chekout url expiration time

- app/controllers/api/v1/plans_controller.rb
- app/serializers/v1/plan_serializer.rb
- app/services/commitments/apply_taxes_service.rb
- app/services/plans/create_service.rb
- app/services/plans/update_service.rb
- spec/factories/commitments.rb
- spec/requests/api/v1/plans_spec.rb
- spec/serializers/v1/plan_serializer_spec.rb
- spec/services/commitments/apply_taxes_service_spec.rb
- spec/services/plans/create_service_spec.rb
- spec/services/plans/update_service_spec.rb
In this PR we're updating plan create/update services for creating and updating plan's minimum commitment. Also the controllers are updated to support it.
> feat(minimum-spending): Add controllers for plan commitments

- app/graphql/types/customers/usage/charge.rb
- app/services/adjusted_fees/create_service.rb
- app/services/charges/charge_model_factory.rb
- app/services/fees/charge_service.rb
- app/services/fees/init_from_adjusted_charge_fee_service.rb
- db/migrate/20240125080718_add_grouped_by_to_adjusted_fees.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/graphql/types/customers/usage/charge_spec.rb
- spec/services/charges/charge_model_factory_spec.rb
- spec/services/fees/init_from_adjusted_charge_fee_service_spec.rb
This PR changes adds a new `grouped_by` json field to the `AdjustedFee` model and moves the creation of fees from an adjusted fee into a proper service to ease the next steps of the feature and make it easier to tests and maintain.
> feat(grouped-by) Refact AdjustedFees for grouped by

- app/graphql/types/customers/usage/charge.rb
- app/services/billable_metrics/aggregations/base_service.rb
- app/services/billable_metrics/aggregations/sum_service.rb
- app/services/charges/charge_model_factory.rb
- app/services/charges/charge_models/grouped_standard_service.rb
- app/services/fees/charge_service.rb
- app/services/fees/init_from_adjusted_charge_fee_service.rb
- spec/services/billable_metrics/aggregations/sum_service_spec.rb
- spec/services/charges/charge_model_factory_spec.rb
- spec/services/charges/charge_models/grouped_standard_service_spec.rb
- spec/services/fees/charge_service_spec.rb
This PR applies the grouped_by logic to in arrears charges with sum aggregation. It creates a fee per aggregated group.
> feat(grouped-by) Adapt sum aggregation to return grouped aggregation

- app/services/billable_metrics/aggregations/base_service.rb
- app/services/billable_metrics/aggregations/sum_service.rb
- app/services/billable_metrics/aggregations/unique_count_service.rb
- spec/services/billable_metrics/aggregations/sum_service_spec.rb
This PR adds the logic for current usage on in advance sum aggregation with `grouped_by` attribute defined at the charge level.
> feat(grouped-by): Current usage for in advance aggregation

- app/services/billable_metrics/aggregations/count_service.rb
- spec/services/billable_metrics/aggregations/count_service_spec.rb
This PR adapt the grouped logic to the count aggregation
> feat(grouped-by): Add grouped count aggregation

- app/services/billable_metrics/aggregations/base_service.rb
- app/services/billable_metrics/aggregations/sum_service.rb
- app/services/billable_metrics/aggregations/unique_count_service.rb
- app/services/billable_metrics/prorated_aggregations/base_service.rb
- app/services/billable_metrics/prorated_aggregations/sum_service.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
This PR adds the prorated grouped sum computation logic in the event stores
> feat(grouped-by): Add grouped prorated sum logic

- app/services/billable_metrics/aggregations/latest_service.rb
- spec/services/billable_metrics/aggregations/latest_service_spec.rb
This PR applies the grouped_by logic to the latest aggregation
> feat(grouped-by): Adapt latest aggregation to return grouped aggregation

- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/services/billable_metrics/aggregations/count_service_spec.rb
- spec/services/billable_metrics/aggregations/latest_service_spec.rb
- spec/services/billable_metrics/aggregations/max_service_spec.rb
- spec/services/billable_metrics/aggregations/sum_service_spec.rb
- spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
- spec/services/billable_metrics/breakdown/sum_service_spec.rb
- spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
Both `Events::Stores::Clickhouse` and `Events::Stores::Postgres` are missing a filter to the `organization_id`, leading to a risk of aggregating events from other organizations if the same subscription_id and billable metric code exsits in multiple organizations.
This PR mitigate this risk by ensuring we always filter events on the organization_id
> fix(event): Add missing organization scope to event stores

- app/services/billable_metrics/aggregations/weighted_sum_service.rb
- app/services/events/stores/base_store.rb
- app/services/events/stores/clickhouse/weighted_sum_query.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres/weighted_sum_query.rb
- app/services/events/stores/postgres_store.rb
- app/services/fees/charge_service.rb
- db/migrate/20240129155938_add_grouped_by_to_quantified_events.rb
- db/schema.rb
- spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
- spec/services/fees/charge_service_spec.rb
This PR adds the weighted sum computation logic in the event stores and billable metric aggregations
> feat(grouped-by): Add full logic on weighted sum aggregation

- spec/factories/subscriptions.rb
- spec/graphql/mutations/applied_coupons/create_spec.rb
- spec/graphql/resolvers/subscription_resolver_spec.rb
- spec/jobs/clock/subscriptions_to_be_terminated_job_spec.rb
- spec/jobs/clock/terminate_ended_subscriptions_job_spec.rb
- spec/models/subscription_spec.rb
- spec/requests/api/v1/applied_coupons_spec.rb
- spec/requests/api/v1/events_spec.rb
- spec/scenarios/create_event_spec.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/services/applied_coupons/create_service_spec.rb
- spec/services/customers/terminate_relations_service_spec.rb
- spec/services/events/validate_creation_service_spec.rb
- spec/services/fees/create_pay_in_advance_service_spec.rb
- spec/services/fees/estimate_pay_in_advance_service_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
- spec/services/plans/destroy_service_spec.rb
- spec/services/quantified_events/create_or_update_service_spec.rb
- spec/services/subscriptions/activate_service_spec.rb
Before, each time we were creating a `subscription` via FactoryBot, `started_at` was null but `status` active.
> misc: Add started_at value to the default subscription factory

- app/models/fee.rb
- app/views/helpers/fee_display_helper.rb
- app/views/templates/credit_note.slim
- app/views/templates/invoices/v4/_default_fee.slim
- app/views/templates/invoices/v4/_default_fee_with_groups.slim
- app/views/templates/invoices/v4/_fee_with_groups.slim
- app/views/templates/invoices/v4/_fees_without_groups.slim
- app/views/templates/invoices/v4/_subscription_details.slim
- spec/models/fee_spec.rb
- spec/views/helpers/fee_display_helper_spec.rb
Existing PDF templates miss support for `grouped_by` feature. Also, currently, we always display pay in arrear fees first and after that pay in advance fees. However, we need to change it in a way that subscription fee is always on the top, no matter if pay in arrear or pay in advance. Basically, fees ordering should use logic that was implemented before so this part has been reverted.
This PR covers:
- support for grouped_by feature
- reorder fees
> feat (document-template): Adjust credit note and invoice templates

- app/services/commitments/calculate_amount_service.rb
- app/services/utils/datetime_service.rb
- spec/services/commitments/calculate_amount_service_spec.rb
- spec/services/utils/datetime_service_spec.rb
This PR adds `Commitments::CalculateAmountService` that calculates the amount for a commitment.
> feat(minimum-spending): Calculate minimum commitment amount cents

- app/services/events/create_batch_service.rb
Added the ability to modify the value of MAX_LENGTH for events batching
I've added support for configuring the maximum length of events batching by introducing the `LAGO_EVENTS_BATCH_MAX_LENGTH` env variable.
Now, users can easily customize the batch length according to their specific requirements without modifying the codebase directly.
> feat(events) Modify events batch length limit

- app/models/fee.rb
- app/views/templates/invoices/v4/_subscription_details.slim
In PDF invoice, template fees with zero unit value need to be removed
> fix: remove zero units fees from PDF template

- app/jobs/clock/activate_subscriptions_job.rb
We recently add some invoice duplication related to the subscription activation process when the workers are on heavy load on a billing day (first day of a month).
Many multiple activation jobs were enqueued but not processed during a period of time because no worker were available to process them. Since the clock jobs have priority over the billing ones, they were all executed immediately in parallel when some worker get free.
In the  `Clock::ActivateSubscriptionsJob`, subscriptions are filtered to only take the pending one, but since the job were executed in parallel, the status was not updated yet.
This PR adds the `activejob-uniqueness` protection to ensure that only one instance of the  `Clock::ActivateSubscriptionsJob` can be executed at a time.
> fix: Ensure subscription activation clock job cannot be enqueued twice

- app/services/invoices/payments/adyen_service.rb
- app/services/invoices/payments/stripe_service.rb
- app/services/payment_providers/adyen_service.rb
- spec/fixtures/adyen/webhook_authorisation_payment_response.json
- spec/services/invoices/payments/adyen_service_spec.rb
- spec/services/invoices/payments/stripe_service_spec.rb
- spec/services/payment_providers/adyen_service_spec.rb
Currently we are not able to generate one-time payment url
This PR handles incoming webhooks where invoice status is changed according to the checkout status
> feat(payment-url): handle incoming webhooks

- app/controllers/api/v1/invoices_controller.rb
- app/serializers/v1/payment_providers/invoice_payment_serializer.rb
- app/services/invoices/payments/adyen_service.rb
- app/services/invoices/payments/generate_payment_url_service.rb
- app/services/invoices/payments/payment_providers/factory.rb
- app/services/invoices/payments/stripe_service.rb
- app/services/payment_providers/adyen_service.rb
- config/routes.rb
- spec/fixtures/adyen/webhook_authorisation_payment_response.json
- spec/requests/api/v1/invoices_spec.rb
- spec/serializers/v1/payment_providers/invoice_payment_serializer_spec.rb
- spec/services/invoices/payments/adyen_service_spec.rb
- spec/services/invoices/payments/generate_payment_url_service_spec.rb
- spec/services/invoices/payments/payment_providers/factory_spec.rb
- spec/services/invoices/payments/stripe_service_spec.rb
- spec/services/payment_providers/adyen_service_spec.rb
Some customers don’t have payment methods that accept recurring payments (ie: card payments in India) and currently it is not possible to fetch one-time payment link when invoice payment status is failed.
This PR adds base setup for creating one-time payment link. Actual integration logic was already implemented in another PR.
> feat(invoice-payment-url): Add setup for invoice payment url

- app/controllers/api/v1/invoices_controller.rb
- app/serializers/v1/payment_providers/invoice_payment_serializer.rb
- app/services/invoices/payments/adyen_service.rb
- app/services/invoices/payments/generate_payment_url_service.rb
- app/services/invoices/payments/payment_providers/factory.rb
- app/services/invoices/payments/stripe_service.rb
- app/services/payment_providers/adyen_service.rb
- config/routes.rb
- spec/fixtures/adyen/webhook_authorisation_payment_response.json
- spec/requests/api/v1/invoices_spec.rb
- spec/serializers/v1/payment_providers/invoice_payment_serializer_spec.rb
- spec/services/invoices/payments/adyen_service_spec.rb
- spec/services/invoices/payments/generate_payment_url_service_spec.rb
- spec/services/invoices/payments/payment_providers/factory_spec.rb
- spec/services/invoices/payments/stripe_service_spec.rb
- spec/services/payment_providers/adyen_service_spec.rb
Some customers don’t have payment methods that accept recurring payments (ie: card payments in India) and currently it is not possible to fetch one-time payment link when invoice payment status is failed.
This PR adds a logic for stripe and adyen in order to generate one time payment link
> feat(payment-url): generate payment url for stripe and adyen

- app/services/billable_metrics/aggregations/unique_count_service.rb
- spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
This PR adds the new grouping logic for the unique count aggregation (without pro-ration)
> feat(grouped_by): Add support for unique count

- app/models/invoice.rb
- db/migrate/20240205160647_remove_organization_sequential_id_index_from_invoices.rb
- db/schema.rb
- spec/scenarios/invoices/invoice_numbering_spec.rb
When generating invoice number in `per_organization` mode, we should use organization timezone.
`organization_sequential_id` usually have following pattern: `prefix-202402-001`. Middle part and sequential id should be generated in the organization scope and based on existing month. However, month scope should take organization timezone into account.
> fix (invoice-number): use organization timezone in per org numbering

- app/views/templates/invoices/v4.slim
- app/views/templates/invoices/v4/_subscription_details.slim
- app/views/templates/invoices/v4/_subscriptions_summary.slim
There are few smaller issues in PDF invoice template
This PR fixes:
- customer email list -> This list is actually string with elements separated by comma. HTML by default break string on multiple lines (when needed) upon empty space detection, so we need to ensure that email list string is correctly formatted.
- removes unnecessary word in multiple subscriptions breakdown page
- displays adjusted subscription fee display name
> fix(invoice-pdf): handle invoice pdf template issues

- app/services/billable_metrics/aggregations/base_service.rb
- app/services/billable_metrics/aggregations/count_service.rb
- app/services/billable_metrics/aggregations/latest_service.rb
- app/services/billable_metrics/aggregations/max_service.rb
- app/services/billable_metrics/aggregations/sum_service.rb
- app/services/billable_metrics/aggregations/unique_count_service.rb
- app/services/billable_metrics/aggregations/weighted_sum_service.rb
- app/services/billable_metrics/prorated_aggregations/base_service.rb
- app/services/billable_metrics/prorated_aggregations/sum_service.rb
- app/services/billable_metrics/prorated_aggregations/unique_count_service.rb
- spec/scenarios/billable_metrics/unique_count_spec.rb
- spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
This PR adds the new grouping logic for the prorated unique count aggregation
> feat(grouped-by): Prorated unique count aggregation

- app/services/quantified_events/create_or_update_service.rb
- spec/scenarios/billable_metrics/unique_count_spec.rb
- spec/services/quantified_events/create_or_update_service_spec.rb
This PR is the last of the epic, it simply ensure that `QuantifiedEvent` are created for events related to a standard charge with `grouped_by` attribute properties when if it's related to a unique count aggregation.
> feat(grouped-by): Quantified event processing after event creation

- app/services/payment_provider_customers/adyen_service.rb
- app/services/payment_provider_customers/gocardless_service.rb
- app/services/payment_provider_customers/stripe_service.rb
When using a list of emails for customer, it creates error on providers side.
- Split the email and take the first one in the list.
> fix(customers): Fix provider emails

- app/models/invoice.rb
- app/views/templates/invoices/v4.slim
- app/views/templates/invoices/v4/_subscription_details.slim
- spec/models/invoice_spec.rb
This PR fixes:
- remove fees table header if there are no positive fees inside
- setting margins
- prevent error when there is no email since we call `gsub` method on it
> fix(invoice-pdf): add new PDF template updates

- app/models/concerns/currencies.rb
- schema.graphql
- schema.json
A user reported that the `KWD` currency is missing in the accepted currency list
This PR adds the missing currency and expose it in the GraphQL api
> fix(currency): Add missing KWD currency

- app/services/events/create_service.rb
- db/clickhouse_migrate/20231026124912_create_events_raw_queue.rb
- db/clickhouse_schema.rb
An issue have been identified with the event timestamp conversion from float to datetime in Clickhouse events_raw.
`1706745600` (2024-02-01T00:00:00.000Z) is stored as `Thu, 01 Feb 2024 00:00:59.392000000 UTC +00:00`
To fix the issue, we decided to turn the float into a string and to send timestamp as an iso8601 datetime
> fix(weighted-sum): Turn kafka timestamp into a string

- app/services/events/stores/base_store.rb
- app/services/invoices/customer_usage_service.rb
This PR adds:
- The missing method signatures in the `Events::Stores::BaseStore`
- Takes advantage of the `Subscriptions::ChargeCacheService` to generate the cache key in the current usage service
> misc: small refactoring regarding caching and event stores

- app/services/invoices/payments/adyen_service.rb
- app/services/payment_provider_customers/adyen_service.rb
- lib/lago/adyen/error_handlable.rb
Fix adyen payment failing jobs
> fix(payment): Fix Adyen invoice payment

- app/services/events/stores/postgres/unique_count_query.rb
- app/services/events/stores/postgres_store.rb
- spec/services/events/stores/postgres_store_spec.rb
The goal of this PR is to add the method `Events::Stores::PostgresStore#unique_count`.
The SQL logic has been extracted into `Events::Stores::Postgres::UniqueCountQuery`.
We've added the method `Events::Stores::PostgresStore#unique_count_breakdown' to facilitate the debugging.
> feat(unique-count): Implement basic unique count for PostgresStore

- app/services/events/stores/postgres/unique_count_query.rb
- app/services/events/stores/postgres_store.rb
- spec/services/events/stores/postgres_store_spec.rb
The goal of this PR is to add the method `Events::Stores::PostgresStore#prorated_unique_count`.
The SQL logic has been extracted into `Events::Stores::Postgres::UniqueCountQuery`.
> feat(unique-count): Add prorated unique count method

- app/services/events/stores/clickhouse/unique_count_query.rb
- app/services/events/stores/clickhouse_store.rb
- spec/services/events/stores/clickhouse_store_spec.rb
The goal of this PR is to add the method `Events::Stores::ClickhouseStore#unique_count`.
> feat(unique-count): Add unique count to ClickhouseStore

- app/services/events/stores/postgres/unique_count_query.rb
- app/services/events/stores/postgres_store.rb
- spec/services/events/stores/postgres_store_spec.rb
The goal of this PR is to add the method `Events::Stores::PostgresStore#grouped_unique_count`.
The SQL logic has been extracted into `Events::Stores::Postgres::UniqueCountQuery`.
> feat(unique-count): Add grouped unique count to PostgresStore

- app/services/events/stores/postgres/unique_count_query.rb
- app/services/events/stores/postgres_store.rb
- spec/services/events/stores/postgres_store_spec.rb
The goal of this PR is to add the method `Events::Stores::PostgresStore#grouped_prorated_unique_count`.
The SQL logic has been extracted into `Events::Stores::Postgres::UniqueCountQuery`.
> feat(unique-count): Add grouped prorated unique count to PostgresStore

- app/services/events/stores/clickhouse/unique_count_query.rb
- app/services/events/stores/clickhouse_store.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
The goal of this PR is to add the method `Events::Stores::ClickhouseStore#prorated_unique_count`.
> feat(unique-count): Add prorated unique count to ClickhouseStore

- app/services/events/stores/clickhouse/unique_count_query.rb
- app/services/events/stores/clickhouse_store.rb
- spec/services/events/stores/clickhouse_store_spec.rb
The goal of this PR is to add the method `Events::Stores::ClickhouseStore#grouped_unique_count`.
> feat(unique-count): Add grouped_unique_count to ClickhouseStore

- app/services/charges/charge_models/volume_service.rb
- spec/services/charges/charge_models/volume_service_spec.rb
If aggregation amount is the number between two tiers, currently the error is thrown.
Tiers:
0 -> 5
6 -> 10
11 -> nil
If aggregation result is 5.5, we should apply second tier values.
> fix (charge models): adjust volume charge model logic

- app/services/events/stores/clickhouse/unique_count_query.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres/unique_count_query.rb
- app/services/events/stores/postgres_store.rb
The goal of this PR is to add the handle prorated recurring logic for unique count aggregation
> feat(unique-count): Prorated unique count queries

- Gemfile
- Gemfile.lock
- app/services/base_service.rb
- app/services/customers/eu_auto_taxes_service.rb
Common scenario in Lago is that we have to trigger active job inside DB transaction. SInce job tries to fetch and use record that is saved inside transaction, we often end up with `ActiveJob::DeserializationError` if job is processed before transaction commit command.
We usually handle this issue by setting wait parameter to 3 seconds upon calling active job. 
This PR sets up `ActiveCommitEverywhere` gem so that we can handle this issue without a 3 seconds hack.
Also, as part of this PR new library is used to correctly call `customer.vies_check` webhook.
> fix (jobs-inside-transaction): add setup for after commit everywhere and fix customer.vies_check webhook

- app/models/subscription.rb
- app/services/billable_metrics/prorated_aggregations/base_service.rb
- app/services/billable_metrics/prorated_aggregations/sum_service.rb
- app/services/credit_notes/create_from_termination.rb
- app/services/fees/create_true_up_service.rb
- app/services/fees/subscription_service.rb
- app/services/subscriptions/create_service.rb
- app/services/subscriptions/terminate_service.rb
- spec/models/subscription_spec.rb
- spec/scenarios/charge_models/prorated_graduated_spec.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/scenarios/subscriptions/upgrade_spec.rb
- spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
- spec/services/credit_notes/create_from_termination_spec.rb
- spec/services/fees/subscription_service_spec.rb
When performing upgrade in some scenarios, date of the upgrade has been included in both termination invoice and first invoice for the new plan.
In all scenarios date of the upgrade will be included in calculation in the first invoice of the new plan.
This PR includes following changes:
Upgrade:
- adjust credit note for plan pay in advance so that date of the upgrade is also included in credit note
- prorated subscription fee should not include date of the upgrade
- charges should not include date of the upgrade (recurring ones)
Termination:
- subscription fee should include date of upgrade
- charges should include date of the upgrade (recurring ones)
> feat (plan-changes): Adjust boundaries upon subscription upgrade

- app/services/invoices/calculate_fees_service.rb
- spec/scenarios/invoices/invoices_spec.rb
After terminating a subscription for a yearly plan with a subscription fee paid in arrears, the invoice does not include any fees.
This PR fixes a bug in `Invoices::CalculateFeesService::should_create_yearly_subscription_fee?` method that now handles terminated subscriptions for plans paid in arrears.
> fix(fees): Fix creating yearly in-arrears subscription fee

- app/services/events/stores/clickhouse/unique_count_query.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres/unique_count_query.rb
- app/services/events/stores/postgres_store.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
The goal of this PR is to add the method `Events::Stores::ClickhouseStore#prorated_unique_count_breakdown` and  `Events::Stores::PostgresStore#prorated_unique_count_breakdown`.
> feat(unique_count): Reafact queries and add prorated breakdown

- app/controllers/api/v1/subscriptions_controller.rb
- db/schema.rb
- spec/services/plans/update_service_spec.rb
Updating a plan by passing `charge_model` was not possible when a new charge is given.
> fix: Updating plan with new charge

- app/services/billable_metrics/prorated_aggregations/sum_service.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- app/services/utils/timezone_service.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
The goal of this PR is to add the method `Events::Stores::ClickhouseStore#active_unique_property?` and  `Events::Stores::PostgresStore#active_unique_property?`.
The PR also adds small fixes and refact
> feat(unique_count): Add active_unique_property to event stores

- app/services/subscriptions/update_service.rb
- spec/services/subscriptions/update_service_spec.rb
Subscription edition works in a way that it changes plan's values. It works fine if subscription is attached to overridden plan.
However, if subscription is attached to parent plan it will change also values on all other subscriptions.
> fix(subscriptions): fix edit subscription attached to parent plan

- app/services/subscriptions/create_service.rb
- app/services/subscriptions/terminate_service.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/scenarios/subscriptions/downgrade_spec.rb
- spec/scenarios/subscriptions/upgrade_spec.rb
- spec/services/subscriptions/terminate_service_spec.rb
If new plan is pay in advance, upon upgrade and downgrade we issue two invoices, closing one for the old subscription and one for new subscription
This PR groups those two invoices
> fix (invoices): group invoices upon downgrade and upgrade

- app/services/utils/datetime_service.rb
- spec/scenarios/charge_models/prorated_graduated_spec.rb
- spec/services/utils/datetime_service_spec.rb
An issue has been identified in the `Utils::DatetimeService.date_diff_with_timezone` method when the provided to_date is a the beginning of the day.
```
to
=> Thu, 07 Dec 2023 00:00:00.000000000 UTC +00:00
from
=> Fri, 01 Dec 2023 00:00:00.000000000 UTC +00:00
Utils::DatetimeService.date_diff_with_timezone(from, to, 'UTC')
=> 6
```
The expected result is 7
The PR adds a second to the `to` value when it is the beginning of the day
> fix: Fix a small edge case with datetime diff computation

- app/services/webhooks/base_service.rb
Some webhook deliveries are ending in the sidekiq deadjob queue because the response from the service was a `Net::HTTPBadResponse`
This error should be captured and the webhook should be handled by the retry mechanism
> fix: Add Net::HTTPBadResponse in the webhook error retry list

- db/schema.rb
It's just the order of two columns
This will prevent changes from appearing when there is no change to the database
I was running `rake db:migrate` and got a different `db/schema.rb`
Only two columns are in the wrong position
> Syncronize with db/schema.rb generated by rails db:migrate

- Gemfile.lock
It's added when doing `bundle` on a recent macOS
When doing `bundle` or `bundle install` on a recent Macbook (Air in my case) with a recent version of macOS, bundler will add a platform.
I just add the platform
> Add arm64-darwin-23 platform to Gemfile.lock

- app/graphql/mutations/plans/create.rb
- app/graphql/mutations/plans/update.rb
- app/graphql/types/commitments/commitment_type_enum.rb
- app/graphql/types/commitments/input.rb
- app/graphql/types/commitments/object.rb
- app/graphql/types/plans/object.rb
- app/graphql/types/subscriptions/plan_overrides_input.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/plans/create_spec.rb
- spec/graphql/mutations/plans/update_spec.rb
- spec/graphql/resolvers/plan_resolver_spec.rb
- spec/graphql/types/commitments/input_spec.rb
- spec/graphql/types/commitments/object_spec.rb
- spec/graphql/types/plans/object_spec.rb
- spec/graphql/types/subscriptions/plan_overrides_input_spec.rb
In this PR we're adding GraphQL resources for minimum commitment.
> feat(minimum-spending): Add graphql commitment type

- Gemfile
- Gemfile.lock
This PR adds [ruby-lsp-rails](https://github.com/Shopify/ruby-lsp-rails)  gem into the Gemfile as a development dependency to better integrate into code editors
> misc: Add ruby-lsp-rails in the gemfile

- spec/services/invoices/finalize_service_spec.rb
When run early in the day, the test would fail because of a wrong date.
This is because the customer is in New York timezone and the default time zone is UTC
```
1) Invoices::FinalizeService#call updates the issuing date
Failure/Error:
expect { finalize_service.call }
.to change { invoice.reload.issuing_date }.to(Time.current.to_date)
.and change { invoice.reload.payment_due_date }.to(Time.current.to_date)
expected `invoice.reload.issuing_date` to have changed to Fri, 23 Feb 2024, but is now Thu, 22 Feb 2024
...and:
expected `invoice.reload.payment_due_date` to have changed to Fri, 23 Feb 2024, but is now Thu, 22 Feb 2024
```
> Fix flaky test for invoice finalize service

- config/initializers/analytics_ruby.rb
Otherwise the app doesn't start with:
Failure/Error: require_relative '../config/environment'
ArgumentError:
Write key must be initialized
When doing `rspec` I would get an error.
Solution was to have:
```
SEGMENT_WRITE_KEY=1
```
or
```
LAGO_DISABLE_SEGMENT=true
```
> require a SEGMENT_WRITE_KEY

- app/views/templates/invoices/v4/_default_fee.slim
- app/views/templates/invoices/v4/_fees_without_groups.slim
- app/views/templates/invoices/v4/_subscription_details.slim
Invoice pdf do not display the correct fee when grouped_by
1. I created a plan.charge with grouped_by attribute
2. I created a subscription on customer
3. Sends events to this subscription with grouped_by.key values
4. Current usage is displayed correctly ✅
5. I terminate the subscription
6. Invoice on user interface is displayed correctly ✅
7. Invoice on PDF display only 1 fees (looks like it aggregates all fees into one) ❌
The fix is to ensure that we loop over all fees when rendering the invoice
> fix(groupe-by): Ensure all groups appears on invoice

- app/services/billable_metric_filters/create_or_update_batch_service.rb
- spec/services/billable_metric_filters/create_or_update_batch_service_spec.rb
This PR adds the logic to discard  billable metric filters when updating a billable metric
> feat(filter): Discard filter and its values

- app/services/credit_notes/apply_taxes_service.rb
- spec/scenarios/invoices/invoices_spec.rb
When we refresh draft invoice, credit note taxes got recalculated.
We need to ensure to add guard clause before dividing with zero
> fix (credit-notes): handle NaN issue in draft invoice refresh part

- app/services/plans/update_service.rb
- spec/services/plans/update_service_spec.rb
Currently it is not possible to edit plan amount cents on edit plan page and on edit subscription page.
We want to allow users to edit plan/subscription amount cents so that they don't need to create new plan with each change.
Also, if downgraded plan's amount cents is updated to the value that is less than the one in downgraded plan, pending subscription should be destroyed.
> feat(edit-plan-amount-cents): Allow editing plan amount cents

- app/models/charge.rb
- app/services/charge_filters/create_or_update_batch_service.rb
- app/services/plans/create_service.rb
- app/services/plans/update_service.rb
- db/migrate/20240227161430_add_invoice_display_name_to_charge_filters.rb
- db/schema.rb
- spec/services/charge_filters/create_or_update_batch_service_spec.rb
- spec/services/plans/create_service_spec.rb
- spec/services/plans/update_service_spec.rb
This PR adds the logic to create, update or remove a `ChargeFilter` and its associated `ChargeFilterValues` in a dedicated `ChargeFilters::CreateOrUpdateBatchService`
> feat(filter): Add creation and update logic for charge filters

- app/services/credit_notes/refresh_draft_service.rb
- app/services/invoices/refresh_draft_service.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/services/credit_notes/refresh_draft_service_spec.rb
When draft invoice fee got changed, we do not recalculate attached credit note item value. It has to change because end-user could end up with invalid credit note amount that would be later applied.
This PR handles credit note recalculation upon fee change.
In prior PR - https://github.com/getlago/lago-api/pull/1733 scenario tests for this case were added. The goal of this change is to cover credit note item recalculation so that scenario tests passes with expected values.
> fix(credit-notes): recalculate credit note item upon draft invoice refresh

- app/jobs/send_email_job.rb
- app/mailers/application_mailer.rb
- app/services/payment_providers/stripe_service.rb
- config/sidekiq.yml
- spec/services/credit_notes/create_service_spec.rb
- spec/services/fees/charge_service_spec.rb
- spec/services/invoices/add_on_service_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
- spec/services/invoices/create_service_spec.rb
- spec/services/invoices/finalize_service_spec.rb
- spec/services/invoices/paid_credit_service_spec.rb
- spec/services/invoices/subscription_service_spec.rb
- spec/services/password_resets/create_service_spec.rb
This PR is an attempt to handle retry and errors with email deliveries.
The PR changes the jobs used to deliver email from the default `ActionMailer::MailDeliveryJob` to an app specific `SendEmailJob`. The new job simply inherit from the first one to keep the delivery behavior
The goal is to allow us:
- To use a custom sidekiq queue rather than the `default` one
- To handle error catching and retry (`ActiveJob::DeserializationError` and `LagoHttpClient::HttpError` for now)
> fix: Deliver email with SendEmailJob

- spec/services/fees/charge_service_spec.rb
Timestamp needs to be included in boundaries in fees/charge_service_spec. Timestamp from boundaries is used for calculating true-up. If not present, current time is used which can result in invalid test results
> misc: fix flaky test

- app/graphql/types/charge_filters/input.rb
- app/graphql/types/charge_filters/object.rb
- app/graphql/types/charge_filters/values.rb
- app/graphql/types/charges/input.rb
- app/graphql/types/charges/object.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/plans/create_spec.rb
- spec/graphql/types/charge_filters/input_spec.rb
- spec/graphql/types/charge_filters/object_spec.rb
- spec/graphql/types/charges/input_spec.rb
- spec/graphql/types/charges/object_spec.rb
This PR adds exposes the charge filters and the charge filter values into the GraphQL API
> feat(filter): Expose charge filters into GraphQL API

- app/models/cached_aggregation.rb
- db/migrate/20240301133006_add_charge_filter_id_to_cached_aggregations.rb
- db/schema.rb
This PR adds a new relation between `ChargeFilter` and `CachedAggregation`
> feat(filter): Add relation between charge filter and cached aggregation

- app/services/subscriptions/billing_service.rb
This PR removes the random wait time when enqueuing the recurring subscription billing, in order to let Sidekiq responsible for balancing the load over the workers. This should help to reduce the number of dead jobs that occurs during the billing day
> misc: Remove wait time for subscription billing

- app/graphql/types/customers/usage/charge.rb
- app/graphql/types/customers/usage/charge_filter.rb
- app/graphql/types/customers/usage/grouped_usage.rb
- app/graphql/types/fees/object.rb
- app/models/charge_filter.rb
- schema.graphql
- schema.json
- spec/graphql/types/customers/usage/charge_filter_spec.rb
- spec/graphql/types/customers/usage/charge_spec.rb
- spec/graphql/types/fees/object_spec.rb
- spec/models/charge_filter_spec.rb
This PR exposes the charge filters details in Fee and Usage types for GraphQL API
> feat(filter): Expose filter with fees and usage in GraphQL

- app/models/payment_provider_customers/stripe_customer.rb
- schema.graphql
- schema.json
Currently BACS and ACH payment method schemas cannot be used in Lago
This PR enables customers to use both BACS and ACH
> feat(stripe-payment-methods): update stripe payment provider method list

- app/graphql/types/billable_metric_filters/object.rb
- app/graphql/types/customers/usage/charge.rb
- app/graphql/types/customers/usage/charge_filter.rb
- app/graphql/types/customers/usage/grouped_usage.rb
- app/models/billable_metric.rb
- app/serializers/v1/billable_metric_filter_serializer.rb
- app/serializers/v1/charge_filter_serializer.rb
- app/serializers/v1/charge_serializer.rb
- app/serializers/v1/customers/charge_usage_serializer.rb
- app/serializers/v1/fee_serializer.rb
- spec/graphql/resolvers/customers/usage_resolver_spec.rb
- spec/serializers/v1/billable_metric_filter_serializer_spec.rb
- spec/serializers/v1/charge_filter_serializer_spec.rb
- spec/serializers/v1/charge_serializer_spec.rb
- spec/serializers/v1/customers/charge_usage_serializer_spec.rb
- spec/serializers/v1/fee_serializer_spec.rb
This PR exposes the bm filter details sorted alphabetically
> feat(filter): Sort bm filters and values

- app/graphql/types/customers/usage/charge.rb
- app/graphql/types/customers/usage/charge_filter.rb
- app/graphql/types/customers/usage/grouped_usage.rb
- app/serializers/v1/charge_filter_serializer.rb
- app/serializers/v1/charge_serializer.rb
- app/serializers/v1/customers/charge_usage_serializer.rb
- app/serializers/v1/fee_serializer.rb
- spec/graphql/resolvers/customers/usage_resolver_spec.rb
- spec/serializers/v1/charge_filter_serializer_spec.rb
- spec/serializers/v1/charge_serializer_spec.rb
- spec/serializers/v1/customers/charge_usage_serializer_spec.rb
- spec/serializers/v1/fee_serializer_spec.rb
This PR exposes the charge filters details in the REST API
> feat(filter): Expose charge filters in API

- app/models/charge_filter.rb
- app/serializers/v1/charge_serializer.rb
The goal of this feature is to allow more flexibility in event grouping by allowing an unlimited level of grouping and making it easier to define default charge properties for events based on their properties.
This PR adds relation between charge_filter and billable metric filters
> feat(filter): Add relation between charge_filter and bm filters

- app/controllers/api/v1/plans_controller.rb
- app/controllers/api/v1/subscriptions_controller.rb
- app/graphql/types/subscriptions/charge_overrides_input.rb
- app/services/charges/override_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/subscriptions/charge_overrides_input_spec.rb
- spec/services/charges/override_service_spec.rb
This PR adds the override logic for charge filters
> feat(filter): Add support for filter in plan override

- db/migrate/20240305164449_add_missing_charge_filter_id_relations.rb
- db/schema.rb
This PR adds:
- `charge_filter_id` to `quantified_events`
- `charge_filter_id` to `adjusted_fees`
> feat(filter): Add missing charge filter id relations

- app/queries/past_usage_query.rb
This PR ensure that charge_filters (and groups) are preloaded along with the fees when computing the past usage for a customer
> feat(filter): Preload charge filter and groups in past usage fees

- app/serializers/v1/events_validation_errors_serializer.rb
- app/services/events/post_validation_service.rb
- db/migrate/20240305093058_update_last_hour_events_mv_to_version3.rb
- db/schema.rb
- db/views/last_hour_events_mv_v03.sql
- spec/serializers/v1/events_validation_errors_serializer_spec.rb
- spec/services/events/post_validation_service_spec.rb
This PR adds the post validation logic for the events when they belongs to a billable metric with filters
> feat(filter): Add post validation logic for events

- app/serializers/v1/billable_metric_filter_serializer.rb
- app/serializers/v1/charge_filter_serializer.rb
- app/serializers/v1/customers/charge_usage_serializer.rb
- app/services/payment_providers/stripe_service.rb
- spec/serializers/v1/billable_metric_filter_serializer_spec.rb
- spec/serializers/v1/charge_filter_serializer_spec.rb
- spec/serializers/v1/customers/charge_usage_serializer_spec.rb
This PR removes all reference to `"*_lago_id` in REST API as they are not usable to retrieve values
> feat(filter): Remove *_filters#lago_id in API

- app/models/invoice_subscription.rb
- app/services/invoices/create_invoice_subscription_service.rb
- app/services/subscriptions/terminate_service.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/scenarios/spending_minimum_spec.rb
- spec/scenarios/subscriptions/terminate_ended_spec.rb
- spec/services/subscriptions/create_service_spec.rb
- spec/services/subscriptions/terminate_service_spec.rb
When subscription auto-termination feature is used by setting `ending_at`, there is a chance that unnecessary credit note can be created. Described scenario can happen if `ending_at` is set on billing day and if termination job is processed before billing job on that day. In that case, since invoice has not been created, we should not issue a credit note.
This PR handles described case. New logic that checks the case is added and also specs have been updated and added.
> fix(sub-termination): update automatic credit note creation logic

- app/services/credit_notes/create_from_termination.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/services/credit_notes/create_from_termination_spec.rb
When a credit note is created with a free trial, we were computing the amount based on a wrong period (1 day was missing).
> fix: Credit note calculation with trial period

- .github/workflows/migrations-test.yml
- config/database.yml
- lib/tasks/db.rake
- spec/services/fees/charge_service_spec.rb
Few issues were reported in the past with database migrations on a fresh lago install.
Since the migration are not performed from the start when deploying on the cloud instance or on the local instances, some edge case could prevent some migration to perform correctly.
This PR adds a github CI action to perform the migration from scratch making sure they all perform correctly
> misc: Add github action to test DB migrations

- app/services/billable_metrics/aggregations/weighted_sum_service.rb
- spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
This PR fixes the following error:
```
TypeError
no implicit conversion of BigDecimal into String (TypeError)
```
It happens because the quantified events stores the cached aggregation values as string, but it has to be converted into BigInt.
> fix(weighted-sum): Fix TypeError with grouped weighted sum

- app/models/charge_filter_value.rb
- spec/models/charge_filter_value_spec.rb
This PR adds a validation rule on `ChargeFilterValue` to accept `__LAGO_MATCH_ALL_FILTER_VALUES__` as a "match all" value
> feat(filter): Add match all value for charge_filters

- app/services/plans/update_service.rb
- spec/services/plans/update_service_spec.rb
This edge case is originally part of update-plan-subscription-fee feature. If plan that got updated has pending subscription whose new subscription fee is greater that the one from original plan, pending subscription needs to be canceled..
This PR covers the described edge case and adds related specs
> fix: cover edge case when pending subscriptions need to be canceled

- app/services/billable_metrics/aggregations/weighted_sum_service.rb
- spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
The goal of this PR is to be able to process aggregation for a `weighted sum` billable metric linked to a `percentage` charge model.
> fix: Aggregation of weighted sum bm linked to a percentage charge model

- app/services/credit_notes/create_from_termination.rb
- app/services/fees/subscription_service.rb
- app/services/subscriptions/dates_service.rb
- spec/services/credit_notes/create_from_termination_spec.rb
- spec/services/fees/subscription_service_spec.rb
- spec/services/subscriptions/dates/monthly_service_spec.rb
Credit note creation for payed in advance plan termination is failing when the plan#amount_cents is updated between the previous subscription fee creation and the termination.
This happen because the proration is computed with the updated plan amount rather than with the one used to initially create the fee 
This PR stores the plan amount cents in the `fee#amount_details[plan_amount_cents]` to make sure that the right value is used to create the credit note.
> fix(credit-note): Store plan amount on fees to compute termination credit note

- app/services/events/post_validation_service.rb
- db/migrate/20240308150801_update_last_hour_events_mv.rb
- db/migrate/20240311091817_add_index_on_last_hour_events_mv.rb
- db/migrate/20240312141641_add_new_index_to_groups.rb
- db/schema.rb
- db/views/last_hour_events_mv_v03.sql
- spec/services/events/post_validation_service_spec.rb
This PR adds back the post validation logic for filters on events
> feat(filter): Add post event validation (again)

- app/services/credit_notes/create_from_termination.rb
- spec/scenarios/subscriptions/multiple_upgrade_spec.rb
In some cases of multiple subscription upgrade, a subscription fee could be already prorated when computing the prorated credit note amount . The result of the proration could then be greater than the last subscription fee amount.
In that case, we have to use this last subscription fee amount
In that case, we have to use this last subscription fee amount as base for the credit note creation
> fix(credit_note): Handle consecutive subscription upgrade

- app/models/invoice.rb
- app/services/users_service.rb
- spec/models/invoice_spec.rb
- spec/scenarios/invoices/invoice_numbering_spec.rb
- spec/services/users_service_spec.rb
Due to the accounting regulations, we should not reset our `per_organisation` numbering sequence each month.
Current logic for November 2023:
COM-202311-001
COM-202311-002
Current logic for December 2023:
COM-202312-001
COM-202312-002
Expected Behaviour:
**Feb**
PRO-377A-202402-001
PRO-377A-202402-002
PRO-377A-202402-003
PRO-377A-202402-004
**March**
PRO-377A-202403-001
PRO-377A-202403-002
**//RELEASE FEATURE**
PRO-377A-202403-003
PRO-377A-202403-004
**April**
PRO-377A-202404-005
PRO-377A-202404-006
PRO-377A-202404-007
This PR covers described `per_organisation` logic change.
There are two main constraints that we had to satisfy and which affected the logic:
1. After releasing the feature we should take the last `organisation_sequence_id` and continue from there (accounting regulations …
> feat(invoice-numbering): add new per_organisation numbering logic

- config/locales/de/commitment.yml
- config/locales/en/commitment.yml
- config/locales/es/commitment.yml
- config/locales/fr/commitment.yml
- config/locales/it/commitment.yml
- config/locales/nb/commitment.yml
- config/locales/sv/commitment.yml
This PR adds locales for minimum commitment.
> feat(min-spend): Add minimum commitment locales

- app/models/commitment.rb
- app/models/fee.rb
- app/models/invoice_subscription.rb
- app/services/fees/apply_taxes_service.rb
- spec/factories/fees.rb
- spec/models/commitment_spec.rb
- spec/models/invoice_subscription_spec.rb
- spec/services/fees/apply_taxes_service_spec.rb
This PR adds minimum commitment-related mothod to various models.
> feat(min-spend): Add commitment-related methods to models

- app/services/invoices/payments/create_service.rb
Today, when a payment attempt failed to enqueue because of a `ActiveJob::Uniqueness::JobNotUnique` the complete process is stopped, leading to a lot of dead jobs and unpredictable inconsistent states for invoices or customers (and their attached objects).
This PR makes sure that the `ActiveJob::Uniqueness::JobNotUnique` remains captured but that the execution is not stopped for the rest of the process
> fix(payment): Stop failing all the process when failing to enqueue a payment

- app/services/subscriptions/dates/yearly_service.rb
- spec/services/subscriptions/dates/yearly_service_spec.rb
For current usage, when interval is `anniversary` and plan is `yearly`, we haven't calculated boundaries correctly.
This fix handles logic for finding starting boundary for yearly plan when interval is anniversary.
> fix (date-boundaries): yearly plan boundaries for anniversary interval were incorrect

- app/services/payment_provider_customers/create_service.rb
- spec/services/payment_provider_customers/create_service_spec.rb
Stripe payment methods were automatically overridden by Lago.
**Steps to reproduce:**
Create a customer via API with stripe as the payment provider and "provider_payment_methods": ["card","sepa_debit"];
Update the customer account via API by sending only external_id and a random field, such as city (do not send anything related to billing_configuration);
In the API response, you can see that Lago automatically removed "sepa_debit" from the list of available payment methods.
Expected behaviour: when updating a customer, only the attributes included in the request payload should be modified.
This PR fixes updating provider customer specifically the payment methods when no payment method is sent.
> fix(payment-methods): Fix provider payment methods

- spec/scenarios/commitments/minimum/in_advance/anniversary/monthly_spec.rb
- spec/scenarios/commitments/minimum/in_advance/anniversary/quarterly_spec.rb
- spec/scenarios/commitments/minimum/in_advance/anniversary/weekly_spec.rb
- spec/scenarios/commitments/minimum/in_advance/anniversary/yearly_spec.rb
- spec/scenarios/commitments/minimum/in_advance/calendar/monthly_spec.rb
- spec/scenarios/commitments/minimum/in_advance/calendar/quarterly_spec.rb
- spec/scenarios/commitments/minimum/in_advance/calendar/weekly_spec.rb
- spec/scenarios/commitments/minimum/in_advance/calendar/yearly_spec.rb
- spec/scenarios/commitments/minimum/in_advance_spec.rb
- spec/scenarios/commitments/minimum/in_arrears/anniversary/monthly_spec.rb
- spec/scenarios/commitments/minimum/in_arrears/anniversary/quarterly_spec.rb
- spec/scenarios/commitments/minimum/in_arrears/anniversary/weekly_spec.rb
- spec/scenarios/commitments/minimum/in_arrears/anniversary/yearly_spec.rb
- spec/scenarios/commitments/minimum/in_arrears/calendar/monthly_spec.rb
- spec/scenarios/commitments/minimum/in_arrears/calendar/quarterly_spec.rb
- spec/scenarios/commitments/minimum/in_arrears/calendar/weekly_spec.rb
- spec/scenarios/commitments/minimum/in_arrears/calendar/yearly_spec.rb
- spec/scenarios/commitments/minimum/in_arrears_spec.rb
> feat(min-spending): Add scenario specs

- app/services/coupons/destroy_service.rb
- app/services/customers/terminate_relations_service.rb
- app/services/plans/destroy_service.rb
This PR intends to replace some calls to `each` with `find_each` when looping over DB resources in Plans and Customers deletion services, in order to reduce the memory usage when dealing with a lot of resources.
> misc: Replace each with find_each in plan and customer delete services

- app/graphql/types/charge_filters/values.rb
- app/models/charge_filter.rb
- app/models/charge_filter_value.rb
- app/services/billable_metric_filters/create_or_update_batch_service.rb
- app/services/charge_filters/create_or_update_batch_service.rb
- db/migrate/20240314163426_add_multiple_values_to_charge_filter_values.rb
- db/schema.rb
- spec/factories/charge_filter_values.rb
- spec/graphql/mutations/plans/create_spec.rb
- spec/models/charge_filter_spec.rb
- spec/models/charge_filter_value_spec.rb
- spec/serializers/v1/charge_filter_serializer_spec.rb
- spec/services/billable_metric_filters/create_or_update_batch_service_spec.rb
- spec/services/charge_filters/create_or_update_batch_service_spec.rb
- spec/services/charges/override_service_spec.rb
- spec/services/plans/create_service_spec.rb
- spec/services/plans/update_service_spec.rb
This PR turns `change_filter_values#value` into `change_filter_values#values` to accept multiple values for a single filter.
> feat(filter): Accept multiple values on a charge_filter_value

- app/services/charge_filters/matching_and_ignored_service.rb
- app/services/events/stores/base_store.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- app/services/fees/charge_service.rb
- spec/services/charge_filters/matching_and_ignored_service_spec.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
- spec/services/fees/charge_service_spec.rb
This PR adds back the aggregation logic for filters
> feat(filter): Create fee for each charge filter

- app/services/invoices/create_generating_service.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- spec/services/invoices/create_generating_service_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
When generating charge pay in advance invoice, grace period should be ignored when calculating `issuing_date`.
This PR fixes described problem and adds related automation tests.
> fix(invoices): assign correct issuing_date for charge pay in advance invoice

- app/models/billable_metric_filter.rb
- app/models/charge_filter.rb
- app/models/charge_filter_value.rb
- app/services/charge_filters/matching_and_ignored_service.rb
- spec/models/charge_filter_spec.rb
This PR adds the logic for the `MATCH_ALL_FILTER_VALUES` in the aggregation process
> feat(filter): Take match_all into account for aggregation

- app/graphql/types/customers/usage/charge_filter.rb
- spec/graphql/resolvers/customers/usage_resolver_spec.rb
This PR ensure that the customer usage with charge filter is correctly rendered in the GraphQL api
> feat(filter): current usage charge with applied filters

- app/services/billable_metrics/prorated_aggregations/base_service.rb
- app/services/subscriptions/dates_service.rb
- spec/scenarios/charge_models/prorated_graduated_spec.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/scenarios/subscriptions/upgrade_spec.rb
- spec/services/subscriptions/dates/monthly_service_spec.rb
When performing upgrade, we want the boundary for charges to be `terminated_at`.
Last month we implemented the new logic where the upgrade day is billed with the next subscription. However, we found few other edge cases that does not work with the new logic so we decided to have the old logic for calculating boundaries upon the upgrade.
> fix(subscription-boundaries): adapt charges boundaries for upgrade case

- app/models/charge_filter.rb
- app/models/charge_filter_value.rb
- spec/models/charge_filter_spec.rb
- spec/models/charge_filter_value_spec.rb
This PR changes the ALL_FILTER_VALUES constant value from `__MATCH_ALL_FILTER_VALUES__` to `__ALL_FILTER_VALUE__`
> feat(filter): Update ALL_FILTER_VALUES constant

- app/services/plans/update_service.rb
- spec/scenarios/charge_models/edit_with_filter_spec.rb
- spec/support/scenarios_helper.rb
The update of the charge model of an existing charge with filter is failing, due to a validation error on the filter properties. The validation is performed with the previous charge model condition.
This PR ensures that the validation is performed using the right charge model
> fix(filters): Allow update of charge model

- app/services/fees/charge_service.rb
Invoice is not generating when filters are attached to a charge.
The issue is related to the fee creation with default properties, created for events that does not match any filter. The fee generation uses a non persisted charge filter with default properties, but it tries to attach it to the generated fee, leading to a validation error.
This fix makes sure that the charge filter is not attached to the fee
> fix(filter): Invoice should be created when default prices is set

- .rubocop.yml
When running `rubocop` from the command line, there is a warning about all the new cops available, which I think is annoying.
(Yes, my terminal is light mode)
Disabling NewCops is how it works now, all new cops are printed in the console but they are not enabled. I'm not against enabling more cops but first, I'd love to be able to run rubocop on the entire codebase with no error.
If we want to enable all the new cops by default, the number for issue almost 10x 🙈 I'm in favor of: 
1. disabling new cops to get rid of the warning
2. fixing the 173 offences
3. enabling whatever new cops we want
Even if a lot of offenses are autocorrectable, it will make the codebase "change a lot", making `git blame` harder to follow, creating conflict with open PRs..
```diff
- 1843 files inspected, 173 …
```
> chore(rubocop): disable new cops by default

- app/models/organization.rb
- app/services/organizations/update_service.rb
- spec/services/organizations/update_service_spec.rb
Organization within the EU must charge the VAT of the country of their customers, not their country. This feature should only be available to country within the EU.
This feature is enabled in the **Integrations** tab.
If your org is outside you get an error message. So far it's a generic error, maybe we can display a better error in the frontend.
If your org is outside the EU but the feature was already enabled, you can still disable it.
If your org is within the EU, you're all good.
**We could do more here, like disabling the _Connect_ button if you select a country outside the EU but for now, we think it's enough effort for the issue.**
> fix(tax): Block Eu Tax Management if org is not in EU country

- app/services/billable_metrics/aggregations/base_service.rb
- app/services/billable_metrics/aggregations/sum_service.rb
- app/services/billable_metrics/aggregations/unique_count_service.rb
- app/services/billable_metrics/aggregations/weighted_sum_service.rb
- app/services/charge_filters/event_matching_service.rb
- app/services/charges/pay_in_advance_aggregation_service.rb
- app/services/events/stores/base_store.rb
- app/services/fees/charge_service.rb
- app/services/fees/create_pay_in_advance_service.rb
- spec/services/billable_metrics/aggregations/sum_service_spec.rb
- spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
- spec/services/charge_filters/event_matching_service_spec.rb
- spec/services/charges/pay_in_advance_aggregation_service_spec.rb
- spec/services/fees/create_pay_in_advance_service_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
This PR adds the logic to apply filters for the pay in advance aggregation
> feat(filter): Pay in advance aggregation support

- app/graphql/types/customers/usage/charge.rb
- app/graphql/types/customers/usage/charge_filter.rb
- app/graphql/types/customers/usage/grouped_usage.rb
- app/graphql/types/fees/object.rb
- app/serializers/v1/customers/charge_usage_serializer.rb
- schema.graphql
- schema.json
- spec/graphql/types/fees/object_spec.rb
- spec/serializers/v1/customers/charge_usage_serializer_spec.rb
This PR ensure that the default filter is exposed in the current usage in both GraphQL and REST API, with both grouped_by or no
> fix(filter): Return default filter in usage

- app/models/concerns/sequenced.rb
- app/models/invoice.rb
- spec/models/invoice_spec.rb
- spec/scenarios/invoices/invoice_numbering_spec.rb
- spec/scenarios/spending_minimum_spec.rb
Currently invoice number is generated upon invoice generation. We should change this behaviour to generate invoice number upon changing invoice status to `finalized`.
This PR handles described case. New logic also ensures that all invoices that are in `draft` status before releasing the feature, keep already generated number and sequential ids.
> feat (invoice-numbering): generate invoice number upon invoice finalization

- app/services/wallets/balance/decrease_ongoing_service.rb
- spec/services/wallets/balance/decrease_ongoing_service_spec.rb
The goal of this PR is to be able to handle automatic topup when usage is empty.
> fix(prepaid-credit): Automatic topup without any usage

- app/models/subscription.rb
- spec/models/subscription_spec.rb
We're working on some change with how the trial is billed. This is a very small function needed for these change. More PR are coming.
The `in_trial_period?` method will help us determine if a subscription is currently in trial (to know if they should be billed or not).
> feat(model): Introduce Subscription.in_trial_period?

- app/models/invoice.rb
- app/serializers/v1/invoice_serializer.rb
- db/migrate/20240327071539_add_payment_disputed_to_invoices.rb
- db/schema.rb
- spec/models/invoice_spec.rb
- spec/serializers/v1/invoice_serializer_spec.rb
PSP integration should listen to disputes and chargebacks to update payment status.
This PR adds a migration that adds `payment_dispute_lost_at` column to `invoices` table.
It also handles validations in `Invoice` model with and model specs as well.
It adds this field to `InvoiceSerializer`.
> feat(disputes): Add dispute columns to invoices

- app/models/analytics/gross_revenue.rb
- app/models/analytics/invoice_collection.rb
- app/models/analytics/invoiced_usage.rb
- app/models/analytics/mrr.rb
PSP integration should listen to disputes and chargebacks to update payment_dispute_lost_at after a dispute is lost.
This PR adds `payment_dispute_lost_at IS NULL` to analytics queries to exclude the invoices with lost payment dispute.
> feat(disputes): Add payment_dispute_lost_at to analytics queries

- app/controllers/api/v1/invoices_controller.rb
- app/services/invoices/lose_dispute_service.rb
- config/routes.rb
- spec/requests/api/v1/invoices_controller_spec.rb
- spec/services/invoices/lose_dispute_service_spec.rb
PSP integration should listen to disputes and chargebacks to update payment_dispute_lost_at after a dispute is lost.
This PR adds route, controller action and `Invoices::LoseDisputeService` so that it's possible to mark invoice payment dispute as lost via the API:
`POST /api/v1/invoices/:id/lose_dispute`
> feat(disputes): Add route, controller action and service for lost disputes

- app/jobs/clock/terminate_ended_subscriptions_job.rb
- app/models/invoice.rb
- app/models/subscription.rb
- app/services/base_service.rb
- app/services/billable_metrics/prorated_aggregations/base_service.rb
- app/services/commitments/calculate_prorated_coefficient_service.rb
- app/services/events/stores/postgres_store.rb
- app/services/fees/subscription_service.rb
- app/services/subscriptions/activate_service.rb
- app/services/subscriptions/billing_service.rb
- app/services/subscriptions/validate_service.rb
- app/services/utils/datetime.rb
- app/services/utils/timezone.rb
- app/services/wallets/create_interval_wallet_transactions_service.rb
- app/services/wallets/update_service.rb
- app/services/wallets/validate_service.rb
- spec/services/utils/datetime_spec.rb
- avoid duplications of `at_time_zone` methods 
- rename `Utils::DatetimeService` to `Utils::Datetime`
- rename `Utils::TimezoneService` to `Utils::Timezone`
> misc: Prevent duplications of at_time_zone methods

- app/models/subscription.rb
- app/services/subscriptions/free_trial_billing_service.rb
- db/migrate/20240328075919_add_trial_ended_at_to_subscriptions.rb
- db/schema.rb
- spec/services/subscriptions/free_trial_billing_service_spec.rb
Following https://github.com/getlago/lago-api/pull/1820, we need a job find all subscriptions which has a trial which just ended.
This introduce a new service to find all subscription with a trial period ending today. The job will run every hour to follow customer timezones. 
We introduce a new timestamp in subscriptions to know if the trial has ended. This ensure we only run the job once. Without this flag, we would retrieve the same subscription 24 times and dispatch the webhook 24 times. The invoice can't be used to know if the job was run because we only change plans with `pay_in_advance = true`.
This adds the fourth definition of the `at_time_zone` method. I'm hoping to refactor this later.
**Note that the job doesn't run yet**. The following PR will add it to the scheduler and …
> feat(trial): Introduce Subscriptions::FreeTrialBillingService

- spec/factories/subscriptions.rb
- spec/graphql/resolvers/customer_resolver_spec.rb
- spec/models/subscription_spec.rb
- spec/queries/subscriptions_query_spec.rb
- spec/requests/api/v1/subscriptions_controller_spec.rb
- spec/scenarios/create_event_spec.rb
- spec/services/customers/terminate_relations_service_spec.rb
- spec/services/plans/destroy_service_spec.rb
- spec/services/subscriptions/activate_service_spec.rb
- spec/services/subscriptions/terminate_service_spec.rb
- spec/services/subscriptions/update_service_spec.rb
The goal of this PR is to extract the `pending_subscription` factory into a trait, to be consistent with the other traits (ie. terminated).
> misc: Extract pending subscription factory into a trait

- app/graphql/types/customers/usage/charge.rb
- app/graphql/types/customers/usage/grouped_usage.rb
- app/models/adjusted_fee.rb
- app/models/fee.rb
- app/serializers/v1/customers/charge_usage_serializer.rb
- app/services/charge_filters/matching_and_ignored_service.rb
- app/services/charges/charge_model_factory.rb
- app/services/charges/pay_in_advance_aggregation_service.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- app/services/fees/charge_service.rb
- spec/models/fee_spec.rb
- spec/scenarios/invoices/filters_and_grouped_by_spec.rb
- spec/serializers/v1/customers/charge_usage_serializer_spec.rb
- spec/services/charge_filters/matching_and_ignored_service_spec.rb
This PR:
- Adds the logic to handle `AdjustedFee` with filters
- Fixes the behavior with filters and `grouped_by`
- Improve the handling of `ignored_filters` with `ALL_VALUES`
> feat(filter): Handle adjusted fees and improve ignored filters

- app/jobs/send_webhook_job.rb
- app/serializers/v1/invoices/payment_dispute_lost_serializer.rb
- app/services/invoices/lose_dispute_service.rb
- app/services/webhooks/invoices/payment_dispute_lost_service.rb
- spec/factories/invoices.rb
- spec/serializers/v1/invoices/payment_dispute_lost_serializer_spec.rb
- spec/services/invoices/lose_dispute_service_spec.rb
- spec/services/webhooks/invoices/payment_dispute_lost_service_spec.rb
PSP integration should listen to disputes and chargebacks to update payment_dispute_lost_at after a dispute is lost.
This PR adds PaymentDisputeLostService webhook.
> feat(disputes): Add payment_dispute_lost webhook

- app/graphql/types/charges/object.rb
- app/graphql/types/customers/usage/charge_filter.rb
- app/models/charge_filter.rb
- app/models/fee.rb
- app/services/adjusted_fees/create_service.rb
- app/services/charge_filters/create_or_update_batch_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/customers/usage/charge_filter_spec.rb
- spec/models/charge_filter_spec.rb
- spec/models/fee_spec.rb
- spec/scenarios/plans/create_and_update_filters_spec.rb
This PR:
- Improve the GraphQl API for billable metric and charge filter
- Makes sure that the edited ChargeFilter and ChargeFilterValue keeps their order after edition
> feat(filter): GraphQL and BillableMetricFilter improvements

- app/services/adjusted_fees/create_service.rb
- spec/services/adjusted_fees/create_service_spec.rb
When editing draft invoice, we should raise validation failure for percentage and graduated prorated charge model only if user wants to edit units. In that case, having number of units as input is not sufficient for performing calculation.
If user wants to have amount adjustment or display name adjustment, we should allow it regardless of the charge model.
> fix: allow display name edition for all types of fees in draft invoice

- .github/workflows/spec.yml
- config/environments/test.rb
Defining configuration here rather than in env vars makes it easier to run tests outside Docker.
When running tests, do we need actual encryption value? We could put the values from `.github/workflows/spec.yml` inside the config if they matter but I don't think they do.
> chore(env): define ActiveRecord encryption config

- app/services/invoices/calculate_fees_service.rb
- spec/services/invoices/calculate_fees_service_spec.rb
When creating an invoice, the fees are determined by `Invoices::CalculateFeesService`. 
If the subscription is set to `pay_in_advance`, the first invoice should not include the usage-based charges because they are billed in arrears and you just got started.
Before, we used to only check if there was a previous invoice to guess of the charge fees should be added. It's worked because pay in advance plan were always billed on day one.
We're changing how the trial works and we're now **charging the subscription fee only at then end of trial**. Now, we cannot assume there was an invoice created on day 1.
Let's look at a subscription with a plan billed monthly, on the first day of the month, with **a trial period of 20 days**.
- 2023-03-20 
- subscription started
- one invoice created, …
> poc(billing): Refactor first invoice when pay plan.in_advance

- app/services/subscriptions/dates/monthly_service.rb
- app/services/subscriptions/dates/quarterly_service.rb
- spec/scenarios/subscriptions/billing_boundaries_spec.rb
- spec/support/matchers/datetime_matcher.rb
An issue have been identified when a subscription is billed in advance on a monthly basis if the subscription starts on a 30 and the billing month is shorter than the subscription month
Subscription_at = 30th of January, billed on an anniversary basis
Plan: Monthly, billed in advance
On the billing day of February 29th, the following boundaries were returned: 
- From datetime: 2024-01-30 00:00:00.000000000
- To datetime: 2024-02-28T59:59.999999000 UTC +00:00
The expected boundaries are:
- From datetime: 2024-02-29 00:00:00.000000000
- To datetime: 2024-03-29T59:59.999999000 UTC +00:00
This PR ensure that the boundaries are correct
> fix(invoices): Fix boundaries when in advance anniversary

- app/services/customers/update_invoice_grace_period_service.rb
- app/services/organizations/update_invoice_grace_period_service.rb
- spec/services/customers/update_invoice_grace_period_service_spec.rb
- spec/services/organizations/update_invoice_grace_period_service_spec.rb
- Some users update the grace period to 0 to finalize all draft invoices. Sometimes this call is done twice and it finalize each invoice twice. No major bug linked to this but we send the email twice to customers.
- Do not trigger invoice finalization if the grace period is the same, on both `organizations` and `customers`
> fix(grace-period): Avoid multiple finalize call when grace period is the same

- app/models/customer.rb
- spec/models/customer_spec.rb
It should not be possible to change customer's currency when addons have been applied thus invoices are generated.
This PR disables the possibility to change customer's currency by fixing the `Customer#editable?` method.
Once an invoice is created you can no longer change customer's currency.
> fix(customer-editable): Fix Customer#editable?

- app/graphql/types/customers/usage/charge_filter.rb
- app/models/charge_filter.rb
- app/models/fee.rb
- app/services/charge_filters/matching_and_ignored_service.rb
- app/services/fees/init_from_adjusted_charge_fee_service.rb
- spec/models/charge_filter_spec.rb
- spec/services/charge_filters/matching_and_ignored_service_spec.rb
This PR adds all remaining parts than can be merged without impacting the production.
> feat(filter): last mergeable changes before release

- app/graphql/resolvers/integration_resolver.rb
- app/graphql/resolvers/integrations_resolver.rb
- app/graphql/types/integrations/integration_type_enum.rb
- app/graphql/types/integrations/netsuite.rb
- app/graphql/types/integrations/object.rb
- app/graphql/types/organization_type.rb
- app/graphql/types/query_type.rb
- app/models/organization.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/integration_resolver_spec.rb
- spec/graphql/resolvers/integrations_resolver_spec.rb
This PR adds support for graphql queries related to integrations models
> feat(accounting-integrations): add support for integrations graphql queries

- .github/workflows/manual-release.yml
- .github/workflows/pronto.yml
- .github/workflows/release.yml
I'm seeing deprecation notices in the pronto actions. Updating to latest `actions/checkout@v4` should fix them.
https://github.com/getlago/lago-api/actions/runs/8599754635
> chore(ci): Update pronto actions/checkout to v4

- .github/workflows/pronto.yml
Yesterday, all our `pronto` actions started [failing like this](https://github.com/getlago/lago-api/actions/runs/8600901566/job/23566843917?pr=1854).
It turned out that there was a bug introduced in rubocop, which made it incompatible with `rubocop-rails`. A [fix](https://github.com/rubocop/rubocop/pull/12826) seems on the way.
https://github.com/rubocop/rubocop/issues/12823
One way to mitigate this is to use `bundle exec rubocop` instead of global `rubocop`. We don't have pronto in our Gemfile so let's move to regular rubocop for now.
Ideally, we'd like to move to checks like this: https://github.com/getlago/lago-api/pull/1856
Note: It's necessary to exit if there is no files to run because you can run rubocop on the entire codebase today.
> chore(ci): tentative fix pronto

- app/views/helpers/line_break_helper.rb
- spec/views/helpers/line_break_helper_spec.rb
An organisation can choose to display a custom text block on invoices.
With this change, we'll ensure the all the blank line before and after the last lines are removed. We'll also remove extra blank lines.
> fix(pdf): Remove extra blank link in custom footer

- config/initializers/sidekiq.rb
- config/routes.rb
Very small improvements:
* Move sidekiq session config to initializer rather than `routes.rb`.
* Only `require 'sidekiq/web'` if we're going to mount it
See https://github.com/getlago/lago-api/pull/1071/
> chore(config): Move Sidekiq config to initializer

- app/controllers/api/v1/invoices_controller.rb
- app/graphql/mutations/invoices/lose_dispute.rb
- app/graphql/resolvers/invoices_resolver.rb
- app/queries/invoices_query.rb
- app/services/credit_notes/refunds/adyen_service.rb
- app/services/credit_notes/refunds/gocardless_service.rb
- app/services/credit_notes/refunds/stripe_service.rb
- app/services/invoices/lose_dispute_service.rb
- app/services/payment_providers/adyen_service.rb
- app/services/payment_providers/stripe_service.rb
- app/services/payment_providers/webhooks/adyen/chargeback_service.rb
- app/services/payment_providers/webhooks/base_service.rb
- app/services/payment_providers/webhooks/stripe/charge_dispute_closed_service.rb
- schema.graphql
- schema.json
- spec/fixtures/adyen/chargeback_lost_event.json
- spec/fixtures/adyen/chargeback_won_event.json
- spec/fixtures/stripe/charge_dispute_lost_event.json
- spec/fixtures/stripe/charge_dispute_won_event.json
- spec/graphql/resolvers/invoices_resolver_spec.rb
- spec/queries/invoices_query_spec.rb
- spec/services/credit_notes/refunds/adyen_service_spec.rb
- spec/services/credit_notes/refunds/gocardless_service_spec.rb
- spec/services/credit_notes/refunds/stripe_service_spec.rb
- spec/services/invoices/lose_dispute_service_spec.rb
- spec/services/payment_providers/webhooks/adyen/chargeback_service_spec.rb
- spec/services/payment_providers/webhooks/stripe/charge_dispute_closed_service_spec.rb
PSP integration should listen to disputes and chargebacks to update payment_dispute_lost_at after a dispute is lost.
This PR adds `PaymentProviders::Webhooks::Stripe::ChargeDisputeClosedService` and `PaymentProviders::Webhooks::Adyen::ChargebackService`
> feat(disputes): Add payment dispute stripe and adyen service

- app/services/invoices/calculate_fees_service.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/services/invoices/calculate_fees_service_spec.rb
Broken by this PR https://github.com/getlago/lago-api/pull/1836
On the same day
* Create a pay_in_advance subscription
* The invoice is generated for the subscription fee
* Send events
* Terminate subscription
* A credit note is created to refund all subscription fee by one day
* A charge is created to bill you the usage-based charges ⬅️ This part was broken
> fix(invoice): Bill usage-based charges if subscription is terminated on day one

- app/models/integrations/netsuite_integration.rb
- spec/models/integrations/netsuite_integration_spec.rb
This PR fixes storing account id. We need to store it with necessary string transformations
> fix (integrations): add account id setter with needed transformations

- config/environments/production.rb
- Oauth Google SDK needs sessions
> feat(sso): Production environment support sessions

- .github/workflows/pronto.yml
- app/jobs/bill_subscription_job.rb
- app/jobs/clock/free_trial_subscriptions_biller_job.rb
- app/jobs/send_webhook_job.rb
- app/models/subscription.rb
- app/serializers/v1/subscription_serializer.rb
- app/services/invoices/calculate_fees_service.rb
- app/services/invoices/create_generating_service.rb
- app/services/invoices/refresh_draft_service.rb
- app/services/invoices/subscription_service.rb
- app/services/subscriptions/activate_service.rb
- app/services/subscriptions/create_service.rb
- app/services/subscriptions/free_trial_billing_service.rb
- app/services/utils/transactional_jobs.rb
- app/services/webhooks/subscriptions/trial_ended_service.rb
- clock.rb
- db/migrate/20240329112415_fill_subscriptions_trial_ended_at.rb
- db/migrate/20240404123257_add_skip_charges_bool_in_invoices.rb
- db/schema.rb
- spec/jobs/bill_subscription_job_spec.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/scenarios/subscriptions/free_trial_billing_spec.rb
- spec/serializers/v1/subscription_serializer_spec.rb
- spec/services/invoices/calculate_fees_service_spec.rb
- spec/services/subscriptions/activate_service_spec.rb
- spec/services/subscriptions/create_service_spec.rb
- spec/services/subscriptions/free_trial_billing_service_spec.rb
- spec/services/webhooks/subscriptions/trial_ended_service_spec.rb
- spec/support/matchers/have_empty_charge_fees.rb
- spec/support/scenarios_helper.rb
When a subscription has a trial period, we want to invoice the customer at the end of the trial, not at the beginning.
Following #1820 and #1821
* Disable billing when creating a new subscription if there is a trial
* Disable billing when activating a pending subscription if there is a trial
* Run the `Subscriptions::FreeTrialBillingService` introduced in #1821 every hour
* Migrate data for existing subscription with trial already ended
* Ensure we don't bill customers if an invoice was created when the subscription started (for sub created before this feature)
Keep in mind that if you're trial ends on day X, this day is *NOT FREE*.
If the 10 days free trial start on the 10th at 14:00, it will end on the 20th at 14:00. You get the 10th to the 19th for free. Day 20 is your first pay day …
> feat(trial): Invoice subscription fee at the end of the trial period

- app/jobs/integrations/aggregator/perform_sync_job.rb
- app/services/integrations/aggregator/base_service.rb
- app/services/integrations/aggregator/sync_service.rb
- app/services/integrations/netsuite/create_service.rb
- spec/jobs/integrations/aggregator/perform_sync_job_spec.rb
- spec/services/integrations/aggregator/sync_service_spec.rb
- spec/services/integrations/netsuite/create_service_spec.rb
This PR adds base service for communicating with Lago's accounting integrations aggregator - Nango.
Also, the sync job is added. Lago needs to call Nango sync endpoint upon integration object creation. Sync is needed for Nango so that they can pull data from accounting provider.
Nango's enpoint structure will be the same for all other providers.
> feat (accounting-integrations): add logic for calling nango sync endpoint

- spec/services/subscriptions/free_trial_billing_service_spec.rb
Test was [failing on main](https://github.com/getlago/lago-api/actions/runs/8702243995/job/23865887566).
```
Failures:
1) Subscriptions::FreeTrialBillingService#call with trial ended due to previous subscription with the same external_id sets trial_ended_at
Failure/Error: expect { service.call }.to change { sub.reload.trial_ended_at }.from(nil).to(sub.trial_end_datetime)
expected `sub.reload.trial_ended_at` to have changed from nil to 2024-04-16 07:21:40.129012000 +0000, but did not change
Finished in 5 minutes 2 seconds (files took 9.89 seconds to load)
4546 examples, 1 failure
```
> fix(tests): Better date definition for flacky test

- app/controllers/api/v1/credit_notes_controller.rb
- app/controllers/api/v1/wallets_controller.rb
- spec/requests/api/v1/credit_notes_controller_spec.rb
- spec/requests/api/v1/wallets_controller_spec.rb
The goal of this PR is to add:
- `items` to `CreditNotesController#index`
- `recurring_transaction_rules` to `WalletsController#index`
> feat: Add missing fields in Wallet and CreditNote responses

- app/models/billable_metric.rb
- app/models/charge.rb
- db/migrate/20240415122310_add_custom_aggregator_to_billable_metrics.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/factories/billable_metrics.rb
- spec/models/billable_metric_spec.rb
- spec/models/charge_spec.rb
- spec/services/fees/charge_service_spec.rb
This PR updates 
- The billable metric model to add:
- The `custom_agg` aggregation type
- A new `custom_aggregator` database column
- The charge model to add
- The `custom` charge model
> feat(metric): Add custom_agg type and custom_aggregator to BM

- app/graphql/resolvers/integration_collection_mappings/netsuite_collection_mapping_resolver.rb
- app/graphql/resolvers/integration_collection_mappings/netsuite_collection_mappings_resolver.rb
- app/graphql/resolvers/integration_mappings/netsuite_mapping_resolver.rb
- app/graphql/resolvers/integration_mappings/netsuite_mappings_resolver.rb
- app/graphql/types/query_type.rb
- app/queries/integration_collection_mappings/netsuite_collection_mappings_query.rb
- app/queries/integration_mappings/netsuite_mappings_query.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/integration_collection_mappings/netsuite_collection_mapping_resolver_spec.rb
- spec/graphql/resolvers/integration_collection_mappings/netsuite_collection_mappings_resolver_spec.rb
- spec/graphql/resolvers/integration_mappings/netsuite_mapping_resolver_spec.rb
- spec/graphql/resolvers/integration_mappings/netsuite_mappings_resolver_spec.rb
- spec/queries/integration_collection_mappings/netsuite_collection_mappings_query_spec.rb
- spec/queries/integration_mappings/netsuite_mappings_query_spec.rb
Currently Lago does not support accounting integrations.
This Pull request adds queries and GraphQL resolvers needed for Netsuite integration mappings.
> feat(integrations-resolvers): Add resolvers and queries

- app/graphql/types/integrations/netsuite.rb
- app/models/integrations/base_integration.rb
- schema.graphql
- schema.json
- spec/graphql/types/integrations/netsuite_spec.rb
This PR adds new graphql field which is needed on UI to display (or not) mapping alert
> feat (accounting-integrations): add has_mappings_configured graphql field

- app/jobs/integrations/aggregator/send_restlet_endpoint_job.rb
- app/services/integrations/aggregator/send_restlet_endpoint_service.rb
- app/services/integrations/netsuite/create_service.rb
- app/services/integrations/netsuite/update_service.rb
- spec/jobs/integrations/aggregator/send_restlet_endpoint_job_spec.rb
- spec/services/integrations/aggregator/send_restlet_endpoint_service_spec.rb
- spec/services/integrations/netsuite/create_service_spec.rb
- spec/services/integrations/netsuite/update_service_spec.rb
This PR handles following cases:
- When connection is created or updated Lago needs to send restlet endpoint URL to aggregator (Nango)
- Also, this PR removes job that triggers Nango sync upon connection creation. We realised that it can be done automatically by providing extra configuration in Nango. However, until the whole integration is done, we will leave related code in the codebase, just in case.
> feat(accounting-integrations): Send restlet endpoint to nango

- app/services/invoices/calculate_fees_service.rb
- spec/support/matchers/have_empty_charge_fees.rb
https://linear.app/getlago/issue/DLVRY-262
Subscriptions fees are now invoiced at the end of the trial instead of at the beginning of the subscription. We made a change were we don't always skip charge fees if it's the first invoice anymore. See https://github.com/getlago/lago-api/pull/1836
In some cases, the system might create invalid charge boundaries. This is not new but those cases always happened on the first invoice, and previously, we were skipping charges in this case so it was never visible.
With this PR, we'll ensure a charge is only created if the boundaries are valid. Next, we'll need to look into *why* the boundaries are invalid in the first place but it's important to merge this fix in the meantime.
> fix(invoice): Remove charges if charge boundaries are invalid

- Gemfile
- Gemfile.lock
- Guardfile
Guard::RSpec allows to automatically & intelligently launch specs when files are modified.
This PR adds `guard-rspec` gem.
> misc(guard): Add guard-rspec gem

- app/models/payment_provider_customers/adyen_customer.rb
- app/models/payment_provider_customers/base_customer.rb
- app/models/payment_provider_customers/stripe_customer.rb
- app/models/payment_providers/adyen_provider.rb
- app/models/payment_providers/base_provider.rb
- app/models/payment_providers/gocardless_provider.rb
- app/models/payment_providers/stripe_provider.rb
Since we have `SecretsStorable` and `SettingsStorable` we can call methods like `settings_accessors :webhook_secret, :success_redirect_url` in the models so that we don't have to implement each getter and setter.
This PR includes `SecretsStorable` and `SettingsStorable` to payment providers and payment provider customers base models and then calls `settings_accessors` and `secret_accessors` when needed.
> misc(settings-and-secrets): Add settings and secrets accessors to payment providers and customers

- db/migrate/20240314165306_migrate_groups_to_filters.rb
- db/migrate/20240314170211_add_charge_filter_id_to_quantified_events.rb
- db/migrate/20240314172008_link_filters_to_cached_aggregation.rb
Disable database transaction for migration from groups into filters as the migration are fully re-playable and should be visible for the customer as fast as possible
> misc: Make group migrations non transactional

- db/migrate/20240314170211_add_charge_filter_id_to_quantified_events.rb
Add missing `to_h` to migrate quantified events
> fix: Quantified event migration

- app/jobs/integrations/aggregator/fetch_items_job.rb
- app/models/integration_item.rb
- app/services/integrations/aggregator/base_service.rb
- app/services/integrations/aggregator/items_service.rb
- app/services/integrations/aggregator/sync_service.rb
- db/migrate/20240419085012_create_integration_items.rb
- db/schema.rb
- lib/lago_http_client/lago_http_client/client.rb
- spec/factories/integration_items.rb
- spec/fixtures/integration_aggregator/items_response.json
- spec/jobs/integrations/aggregator/fetch_items_job_spec.rb
- spec/models/integration_item_spec.rb
- spec/services/integrations/aggregator/items_service_spec.rb
- spec/services/integrations/aggregator/sync_service_spec.rb
This PR adds logic for fetching items from Nango (Lago's integration aggregator).
These items are basically objects that are used for mapping. We decided to store it on our side in order to make it searchable and more efficient since the same list need to be returned to the UI for various mappable objects.
> feat (accounting-integrations): add logic for fetching items from integration aggregator

- spec/services/subscriptions/free_trial_billing_service_spec.rb
When writing the tests, I have set `timestamp` to a specific time and I acted as if it was a time `Timecop.freeze` call.
No need to set the timestamp to a specific time is most tests, it's already overridden for test that need it.
> fix(tests): Fix free trial tests where time wasn't frozen

- app/services/billable_metrics/aggregation_factory.rb
- app/services/billable_metrics/aggregations/custom_service.rb
- app/services/charges/charge_model_factory.rb
- app/services/charges/charge_models/custom_service.rb
- spec/factories/billable_metrics.rb
- spec/factories/charges.rb
- spec/services/billable_metrics/aggregation_factory_spec.rb
- spec/services/billable_metrics/aggregations/custom_service_spec.rb
- spec/services/charges/charge_model_factory_spec.rb
- spec/services/charges/charge_models/custom_service_spec.rb
- spec/services/fees/charge_service_spec.rb
This PR adds the base logic for `BillableMetrics::Aggregations::CustomService` and `Charges::ChargeModels::CustomService`
Note: the aggregation logic itself will come in a next PR(s)
> feat(custom_agg): Base structure for custom aggregation

- app/graphql/types/charges/properties.rb
- app/graphql/types/charges/properties_input.rb
- app/services/charges/filter_charge_model_properties_service.rb
- app/services/plans/create_service.rb
- app/services/plans/update_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/charges/properties_input_spec.rb
- spec/graphql/types/charges/properties_spec.rb
- spec/services/charges/filter_charge_model_properties_service_spec.rb
This PR adds the whitelisting logic for `custom_properties` in the `charge#properties` object and updates the GraphQL type to expose this field
> feat(custom_agg): Whitelist custom_properties in charge properties

- app/controllers/api/v1/plans_controller.rb
- app/graphql/types/charges/object.rb
- app/graphql/types/plans/object.rb
- app/models/charge_filter.rb
- app/models/charge_filter_value.rb
Some performance issues were reported after the recent introduction of the `filters` feature.
This PR tries to speed-up the plans/charges rendering by pre-loading charge filters and filter values to avoid N+1 queries
> feat(custom_agg): Retrieve event properties from event stores

- app/controllers/api/v1/wallet_transactions_controller.rb
- app/graphql/mutations/wallet_transactions/create.rb
- app/graphql/types/wallet_transactions/object.rb
- app/graphql/types/wallet_transactions/transaction_status_enum.rb
- app/jobs/wallet_transactions/create_job.rb
- app/models/wallet_transaction.rb
- app/serializers/v1/wallet_transaction_serializer.rb
- app/services/credits/applied_prepaid_credit_service.rb
- app/services/wallet_transactions/create_service.rb
- app/services/wallet_transactions/recredit_service.rb
- db/migrate/20240419071607_add_transaction_status_to_wallet_transactions.rb
- db/schema.rb
- db/seeds/base.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/wallet_transactions/create_spec.rb
- spec/graphql/types/wallet_transactions/object_spec.rb
- spec/jobs/wallet_transactions/create_job_spec.rb
- spec/serializers/v1/wallet_transaction_serializer_spec.rb
- spec/services/credits/applied_prepaid_credit_service_spec.rb
- spec/services/wallet_transactions/create_service_spec.rb
This PR aims to add a `transaction_status` field for wallet transactions.
This field can be set to `paid`, `offered`, or `voided` (not used yet).
> feat(wallet): Set transaction status to wallet transaction

- app/services/subscriptions/free_trial_billing_service.rb
- spec/services/subscriptions/free_trial_billing_service_spec.rb
When a plan free trial has ended, we invoice the subscription, set `subscription.trial_ended_at` attribute and send the `subscription.trial_ended` webhook.
This fix will ensure we do this work *only* if the plan attached to the subscriptions has a free trial configured.
Note that in ruby, the `subscription.trial_ended_datetime` method already returns nil if there is no trial_period configured.
> fix(trial): Ignore subscription if there is no free trial set

- app/views/templates/invoices/v4/charge.slim
This PR is a fix for the following error in InvoiceMailer:
```
undefined method `charge?' for #<Invoice id: "<GUID>", created_at: "<DATETIME>", updated_at: "<DATETIME>", issuing_date: "<DATE>", taxes_amount_cents: 0, total_amount_cents: 0, invoice_type: "subscription", payment_status: "succeeded", number: "SOR-D491-348-140", sequential_id: 140, file: nil, customer_id: "<GUID>", taxes_rate: 0.0, status: "finalized", timezone: "UTC", payment_attempts: 0, ready_for_payment_processing: true, organization_id: "<GUID>", version_number: 4, currency: "USD", fees_amount_cents: 0, coupons_amount_cents: 0, credit_notes_amount_cents: 0, prepaid_credit_amount_cents: 0, sub_total_excluding_taxes_amount_cents: 0, sub_total_including_taxes_amount_cents: 0, payment_due_date: "<DATE>", net_payment_term: 0, …
```
> fix(filter): Fix email template with fee display name

- app/controllers/api/v1/wallet_transactions_controller.rb
- app/graphql/mutations/wallet_transactions/create.rb
- app/jobs/wallet_transactions/create_job.rb
- app/services/base_validator.rb
- app/services/wallet_transactions/create_service.rb
- app/services/wallet_transactions/recredit_service.rb
- app/services/wallets/balance/decrease_ongoing_service.rb
- app/services/wallets/create_interval_wallet_transactions_service.rb
- app/services/wallets/create_service.rb
- spec/jobs/wallet_transactions/create_job_spec.rb
- spec/requests/api/v1/wallet_transactions_controller_spec.rb
- spec/services/wallet_transactions/create_service_spec.rb
- spec/services/wallets/create_interval_wallet_transactions_service_spec.rb
This PR aims to refactor `WalletTransactions::CreateService` to use the common `call` method.
> misc(wallet): Refactor WalletTransaction create service

- app/models/charge_filter.rb
- app/models/charge_filter_value.rb
- app/services/plans/create_service.rb
- app/services/plans/update_service.rb
- spec/graphql/resolvers/invoice_resolver_spec.rb
- spec/requests/api/v1/invoices_controller_spec.rb
- spec/services/invoices/generate_pdf_service_spec.rb
This PR follow the recent release of the filter feature.
It makes discarded charge filters attached to fees are returned:
- In the GraphQL API
- In the Rest API
- On the invoice  PDF
> fix(filter): Render discarded charge filters when attached to fees

- .github/workflows/migrations-test.yml
Reverts getlago/lago-api#1888
For some reasons `AddNewIndexToGroups` stays stuck for a very long time and running specs takes forever. Let's revert back.
https://github.com/getlago/lago-api/actions/runs/8801237466/job/24154104088?pr=1912
> Revert "chore(ci): Migrate DB before test instead of running a dedicated job"

- config/sidekiq.yml
This PR adds `integrations` queue in sidekiq definition
> add new integrations queue

- app/services/integrations/netsuite/create_service.rb
- app/services/integrations/netsuite/update_service.rb
- spec/services/integrations/netsuite/create_service_spec.rb
- spec/services/integrations/netsuite/update_service_spec.rb
This PR triggers Nango (accounting aggregator) sync when we create or update connection. Sync is needed only when restlet url is set because without restlet url sync will fail.
> feat (accounting-integrations): start sync upon connection create and update

- app/graphql/resolvers/memberships_resolver.rb
- app/graphql/types/membership_type.rb
- app/graphql/types/memberships/role_enum.rb
- app/graphql/types/user_type.rb
- app/models/membership.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/current_user_resolver_spec.rb
Role-based permissions are coming to Lago.
This PR introduces an proper RoleEnum for `membership.role` attribute. Today there is only admin but more roles are coming.
This is preliminary work to help the frontend retrieve permissions and role for the current user for each organization through memberships. The `organizations` relation is still available for backward compatibility reasons.
```gql
fragment CurrentUserInfos on User {
id
email
premium
organizations {
id
name
logoUrl
}
}
```
```gql
fragment CurrentUserInfos on User {
id
email
premium
memberships {
id
role
permissions.  <--- upcoming
organization {
id
name
logoUrl
}
}
}
```
> feat(gql): expose Memberships to UserType (to retrieve upcoming permissions)

- app/services/charges/pay_in_advance_aggregation_service.rb
- app/services/fees/create_pay_in_advance_service.rb
- spec/services/charges/pay_in_advance_aggregation_service_spec.rb
- spec/services/fees/create_pay_in_advance_service_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
This PR follow the recent release of the filter feature.
This PR is cleaning up the groups from pay in advance logic for fees and invoices
> feat(filter): Remove groups from in advance aggregations

- app/config/permissions/definition.yml
- app/config/permissions/role-finance.yml
- app/config/permissions/role-manager.yml
- app/controllers/graphql_controller.rb
- app/graphql/concerns/authenticable_api_user.rb
- app/graphql/extensions/field_authorization_extension.rb
- app/graphql/mutations/base_mutation.rb
- app/graphql/types/base_argument.rb
- app/graphql/types/base_field.rb
- app/graphql/types/base_input_object.rb
- app/graphql/types/membership_type.rb
- app/graphql/types/permissions_type.rb
- app/models/membership.rb
- app/models/permission.rb
- app/models/user.rb
- app/support/dotted_hash.rb
- config/application.rb
- schema.graphql
- schema.json
- spec/graphql/types/permissions_type_spec.rb
- spec/models/permission_spec.rb
- spec/support/graphql_helper.rb
- spec/support/matchers/graphql_field_permissions_matcher.rb
Currently, all Lago users are admin. They can perform all actions and access every piece of data.
This PR introduces the base needed to add permissions all over the codebase.
- **users** have roles per **organization**, hence **membership** have `roles`
- **roles** have `permissions`
- app always checks for `permissions` (as much as possible), not `roles`
Lago defines 3 roles by default
* Admin
* Account Manager
* Finance & Analyst
These roles exist for every organization. It's not possible to create custom roles. It's not possible to customize the permissions of these roles.
```ruby
user.has_role? :admin, organization
user.admin? organization
user.manager? organization
user.has_permission? "organization:info:edit", organization
user.can? "organization:info:edit", organization
```
* The …
> feat(rbac): Introduce permission system

- Gemfile
- Gemfile.lock
Since the update to ruby 3.3.0, to new warning appeared when starting the API containers:
```
/usr/local/bundle/gems/crack-0.4.5/lib/crack/xml.rb:9: warning: bigdecimal was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec. Also contact author of crack-0.4.5 to add bigdecimal into its gemspec.
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/auth.rb:11: warning: mutex_m was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of httpclient-2.8.3 to add mutex_m into its gemspec.
```
This PR add `bigdecimal` and `mutex_m` in the Gemfile to fix the deprecation warning
> misc(gems): Fix warning with missing gems

- lib/lago_utils/lago_utils/ruby_sandbox.rb
- lib/lago_utils/lago_utils/ruby_sandbox/runner.rb
- lib/lago_utils/lago_utils/ruby_sandbox/safe_environment.rb
- lib/lago_utils/lago_utils/ruby_sandbox/sandbox_error.rb
- lib/lago_utils/lago_utils/ruby_sandbox/sanitizer.rb
- spec/lib/lago_utils/ruby_sandbox_spec.rb
This PR adds the Ruby Sandbox that will be used to execute the custom aggregation method in a next PR
> feat(custom_agg): Add Ruby Sandbox to allow ruby execution in a safe environment

- lib/lago_utils/lago_utils/ruby_sandbox/safe_environment.rb
This PR fixes the RubySandbox issue with Ruby 3.3.0
```
`undef_method': undefined method `new' for class `String' (NameError)
```
> fix: Ruby sandbox support for ruby 3.3.0

- app/models/customer.rb
- app/models/integration_customers/base_customer.rb
- app/models/integration_customers/netsuite_customer.rb
- db/migrate/20240425082113_create_integration_customers.rb
- db/schema.rb
- spec/factories/integration_customers.rb
- spec/models/customer_spec.rb
- spec/models/integration_customers/base_customer_spec.rb
- spec/models/integration_customers/netsuite_customer_spec.rb
This PR adds models for integration customers.
> feat(integrations): Add models for integrations customers

- app/graphql/resolvers/integrations/subsidiaries_resolver.rb
- app/graphql/types/integrations/subsidiaries/object.rb
- app/graphql/types/query_type.rb
- app/services/integrations/aggregator/subsidiaries_service.rb
- schema.graphql
- schema.json
- spec/fixtures/integration_aggregator/subsidiaries_response.json
- spec/graphql/resolvers/integrations/subsidiaries_resolver_spec.rb
- spec/services/integrations/aggregator/subsidiaries_service_spec.rb
This PR covers fetching subsidiaries from Lago's integration aggregator.
List of subsidiaries is needed on the UI in order to allow user to select customer's subsidiary. Subsidiary is required field in customer create and update actions.
There is small amount of subsidiaries (and it is used only on one place in the UI) so we will return it to the UI on the fly from accounting aggregator.
> feat (accounting-integrations): add logic and graphql support for fetching subsidiaries list

- app/models/wallet_transaction.rb
- app/services/credits/applied_prepaid_credit_service.rb
- app/services/wallet_transactions/create_service.rb
- db/migrate/20240419071607_add_transaction_status_to_wallet_transactions.rb
- db/seeds/base.rb
- schema.graphql
- schema.json
- spec/services/credits/applied_prepaid_credit_service_spec.rb
- spec/services/wallet_transactions/create_service_spec.rb
This PR aims to rename:
- `paid` to `purchased`
- `offered` to `granted`
for the `transaction_status` field for Wallet.
> feat(wallet): Rename transaction statuses for wallet

- app/services/wallet_transactions/create_service.rb
The goal of this PR is to send a webhook with up-to-date values for the wallet transaction, because sometimes, it can be outdated
> feat(wallet): Reload wallet transaction before sending webhook

- app/controllers/webhooks_controller.rb
We're getting as error in webhooks controller when `params['notificationItems']` is `nil`.
This PR fixes `adyen_params` method by adding a safe navigation operator.
> fix(webhook): Fix webhook controller adyen params

- app/jobs/send_webhook_job.rb
- app/services/wallets/balance/update_ongoing_service.rb
- app/services/webhooks/wallets/depleted_ongoing_balance_service.rb
- db/migrate/20240424124802_add_depleted_ongoing_balance_to_wallets.rb
- db/schema.rb
- spec/services/wallets/balance/update_ongoing_service_spec.rb
- spec/services/webhooks/wallets/depleted_ongoing_balance_service_spec.rb
This PR aims to add a new webhook when the ongoing balance is < or = 0.00.
> feat(wallet): Send wallet.depleted_ongoing_balance webhook

- app/services/billable_metrics/aggregations/custom_service.rb
- app/services/charges/charge_models/custom_service.rb
- spec/factories/billable_metrics.rb
- spec/scenarios/billable_metrics/custom_aggregation_spec.rb
- spec/services/billable_metrics/aggregations/custom_service_spec.rb
- spec/services/charges/charge_models/custom_service_spec.rb
- spec/services/fees/charge_service_spec.rb
This PR implements the custom aggregation logic using the ruby Sandbox
> feat(custom_agg): Implement custom aggregator

- app/jobs/bill_subscription_job.rb
- app/models/invoice_subscription.rb
- app/services/invoices/create_invoice_subscription_service.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- app/services/invoices/refresh_draft_service.rb
- app/services/invoices/subscription_service.rb
- app/services/subscriptions/activate_service.rb
- app/services/subscriptions/billing_service.rb
- app/services/subscriptions/create_service.rb
- app/services/subscriptions/free_trial_billing_service.rb
- app/services/subscriptions/terminate_service.rb
- app/services/subscriptions/update_service.rb
- db/migrate/20240412133335_add_invoice_type_to_invoice_subscriptions.rb
- db/schema.rb
- spec/jobs/bill_subscription_job_spec.rb
- spec/scenarios/subscriptions/free_trial_billing_spec.rb
- spec/services/customers/terminate_relations_service_spec.rb
- spec/services/invoices/create_invoice_subscription_service_spec.rb
- spec/services/invoices/subscription_service_spec.rb
- spec/services/plans/destroy_service_spec.rb
- spec/services/subscriptions/billing_service_spec.rb
- spec/services/subscriptions/terminate_service_spec.rb
In some cases, due to race conditions, duplicated non-recurring invoices are created by the system, (for example when the clock job stars a subscription)
Today, only recurring invoices are protected against the duplication via a unique index on `recurring`, `charges_from_datetime` and `charges_to_datetime` columns of the `invoice_subscriptions` table
This PR tries to address the problem by
- Adding a new `invoicing_reason` on the `invoice_subscriptions` table as an enum accepting `subscription_started`, `subscription_terminated`, `in_advance_charge` and `subscription_periodic` values
- It will replace the `recurring` column in the future
- Adding two new unique indexes on the `invoice_subscriptions` table
- subscription_id, invoice_type where invoice_type = 'started'
- subscription_id, …
> fix(invoice): Prevent duplicated non-recurring invoices

- app/services/wallets/balance/update_ongoing_service.rb
- spec/services/wallets/balance/update_ongoing_service_spec.rb
The goal of this PR is to fix an issue we recently introduced by accepting negative values for the ongoing balance of a wallet.
For the recurring topup, we want to take into consideration pending transactions, to avoid pending topup every 5 minutes.
> fix(wallet): Prevent creation of several recurring topup

- spec/services/subscriptions/terminate_service_spec.rb
On the last day of the month, we don't create credit note because there is no days to refund.
> chore(tests): Fix flacky test

- app/services/billable_metrics/create_service.rb
- app/services/billable_metrics/update_service.rb
- db/migrate/20240429141108_add_custom_aggregation_to_organizations.rb
- db/schema.rb
- spec/services/billable_metrics/create_service_spec.rb
- spec/services/billable_metrics/update_service_spec.rb
This PR adds a new flag to the `organizations` table, name `custom_aggregation`, to enable the custom aggregation feature.
This flag is then used to enforce both billable metric creation and update permissions with `custom_agg` aggregation type
**NOTE: A flag feature might soon replace the current logic**.
See https://github.com/getlago/lago-api/pull/1872
> feat(custom_agg): Add flag to enable the feature

- app/models/cached_aggregation.rb
- app/services/billable_metrics/aggregations/custom_service.rb
- app/services/charges/apply_pay_in_advance_charge_model_service.rb
- app/services/events/post_process_service.rb
- app/services/fees/charge_service.rb
- app/services/fees/create_pay_in_advance_service.rb
- spec/scenarios/billable_metrics/custom_aggregation_spec.rb
- spec/services/billable_metrics/aggregations/custom_service_spec.rb
- spec/services/fees/charge_service_spec.rb
- spec/services/fees/create_pay_in_advance_service_spec.rb
This PR adds the aggregation logic for recurring, current usage and pay in advance flows
> feat(custom_agg): Finalize aggregregation logic

- spec/scenarios/plans/create_and_update_filters_spec.rb
This PR is re-enabling a spec that was ignored due to a flaky behavior that has been fixed
> misc(filter): re-enable an ignored test case

- app/graphql/mutations/integration_items/fetch_items.rb
- app/graphql/mutations/integration_items/fetch_tax_items.rb
- app/jobs/integrations/aggregator/perform_sync_job.rb
- app/services/integrations/aggregator/base_service.rb
- app/services/integrations/aggregator/sync_service.rb
- app/services/integrations/netsuite/create_service.rb
- spec/jobs/integrations/aggregator/perform_sync_job_spec.rb
- spec/services/integrations/aggregator/sync_service_spec.rb
- spec/services/integrations/netsuite/create_service_spec.rb
This PR handles following issues:
1. When connection is created or updated we are triggering sync of all resources between our aggregator and Netsuite. After we receive the success response we want to start the services for importing items and tax items from aggregator. That being said, from now on, the jobs for importing items should be part of sync service since it can take a lot of time to be handled in the service.
2. When Re-fetch button is pressed in items dropdown (GRAPHQL MUTATION) , following actions should be performed: sync should be started between aggregator and Netsuite, we should import items / tax items. For this case it does not make sense to trigger sync of all resources. Instead, we should just trigger sync for the …
> feat (accounting-integrations): refactor logic for syncing resources

- app/services/billable_metrics/aggregations/custom_service.rb
- spec/factories/billable_metrics.rb
- spec/scenarios/billable_metrics/custom_aggregation_spec.rb
This PR add a new scenario for a complex custom aggregation involving filters.
It also makes sure that the applied aggregation properties are the one from the filter
> feat(custom_agg): Add a new scenario and fix aggregation properties

- app/controllers/api/v1/wallet_transactions_controller.rb
- app/graphql/mutations/wallet_transactions/create.rb
- app/jobs/send_webhook_job.rb
- app/models/wallet_transaction.rb
- app/services/credits/applied_prepaid_credit_service.rb
- app/services/wallet_transactions/create_service.rb
- app/services/wallet_transactions/settle_service.rb
- app/services/wallet_transactions/validate_service.rb
- app/services/wallet_transactions/void_service.rb
- app/services/webhooks/invoices/payment_status_updated_service.rb
- app/services/webhooks/wallet_transactions/updated_service.rb
- db/migrate/20240430133150_add_invoiced_to_transaction_status.rb
- db/schema.rb
- db/seeds/base.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/wallet_transactions/create_spec.rb
- spec/requests/api/v1/wallet_transactions_controller_spec.rb
- spec/services/credits/applied_prepaid_credit_service_spec.rb
- spec/services/wallet_transactions/create_service_spec.rb
- spec/services/wallet_transactions/settle_service_spec.rb
- spec/services/wallet_transactions/validate_service_spec.rb
- spec/services/wallet_transactions/void_service_spec.rb
- spec/services/webhooks/wallet_transactions/updated_service_spec.rb
This PR aims to create a voided wallet transaction.
> feat(wallet): Ability to create a voided wallet transaction

- app/services/events/stores/postgres_store.rb
We're getting SQL syntax errors when some of the conditions are blank: 
```
aggregation_failure: PG::SyntaxError: ERROR:  syntax error at or near ")" (BaseService::ServiceFailure)
LINE 1: ...ies->>'core_hours' ~ '^-?\d+(\.\d+)?$') AND NOT (() OR () OR...
^
```
In this PR we're adding `conditions.compact_blank` to remove the blank ones.
> fix(postgres-store): Fix empty conditions sql error

- app/graphql/types/add_ons/object.rb
- app/graphql/types/billable_metrics/object.rb
- app/models/integrations/base_integration.rb
- schema.graphql
- schema.json
- spec/graphql/types/add_ons/object_spec.rb
- spec/graphql/types/billable_metrics/object_spec.rb
- spec/models/integrations/base_integration_spec.rb
This PR adds `netsuite_mappable` to addons and billable metrics.
> feat(integrations): Add netsuite_mappable to addons and billable metrics

- app/services/invoices/calculate_fees_service.rb
- db/migrate/20240502075803_add_filters_missing_indexes.rb
- db/schema.rb
- db/seeds/invoices.rb
Lago is facing some performance issues when it has to generate a lot of invoices on a single day.
This PR:
- Add 3 indexes
- charge_filters#charge_id where deleted_at is null
- charge_filter_values#charge_filter_id where deleted_at is null
- billable_metric_filters#billable_metric_id where deleted_at is null
- Preload every `ChargeFilter`, `ChargeFilterValue` and `BillableMetricFilter` in the `Invoices#CalculateFeesService`
> misc: Preload filters allong with charges in billing process

- app/graphql/mutations/invites/create.rb
- app/graphql/types/invites/object.rb
- app/models/invite.rb
- app/services/invites/accept_service.rb
- app/services/invites/create_service.rb
- app/services/invites/validate_service.rb
- app/services/users_service.rb
- db/migrate/20240430100120_add_role_to_invite.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/invites/create_spec.rb
- spec/services/invites/accept_service_spec.rb
- spec/services/invites/create_service_spec.rb
- spec/services/invites/validate_service_spec.rb
- spec/services/users_service_spec.rb
Granular permissions are being added to Lago.
When inviting a user to an app, you must assign them a role. This PR adds role to user invitation endpoints (create and accept) and related services.
`Invite.role` attribute is added and on par with `Membership.role`.
I removed the email param when possible, instead of using the email passed to graphql, we use the email from the invite we retrive via the token.
> feat(rbac): Add role to user invitation GQL endpoints and services

- db/migrate/20240502095122_add_indexes_to_subscriptions.rb
- db/schema.rb
Lago is facing some performance issues when it has to generate a lot of invoices on a single day.
This PR:
- Add 2 indexes
- `subscriptions#started_at` and `subscriptions#ending_at`
- `invoice_subscriptions#subscription_id`, `invoice_subscriptions#from_datetime`, `invoice_subscriptions#to_datetime`
> misc(subscription): Add indexes to speedup billing

- app/models/invoice.rb
- spec/models/invoice_spec.rb
This PR fixes the following issue happening when generating an invoice with a fee attached to a charge filter and requiring a breakdown (Unique count aggregation)
```
undefined local variable or method `charge_filter' for an instance of Invoice
```
> fix(charge_filter): Fix fee breakdown with filter

- app/services/billable_metric_filters/create_or_update_batch_service.rb
- spec/services/billable_metric_filters/create_or_update_batch_service_spec.rb
Updating multiple values of a billable metric filter, does not discard the associated charge filter values, leading to future validation errors on plan update as the validation will fail with a `value_is_invalid` error
This PR fixes the issue by ensuring that all removed billable metric values are effectively removed from the charge filters
> fix(filter): Fix multiple update of billable metric values

- app/services/adjusted_fees/create_service.rb
- app/services/billable_metrics/aggregations/base_service.rb
- app/services/billable_metrics/aggregations/weighted_sum_service.rb
- app/services/billable_metrics/prorated_aggregations/base_service.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- spec/services/billable_metrics/aggregations/count_service_spec.rb
- spec/services/billable_metrics/aggregations/latest_service_spec.rb
- spec/services/billable_metrics/aggregations/max_service_spec.rb
- spec/services/billable_metrics/aggregations/sum_service_spec.rb
- spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
- spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
- spec/services/billable_metrics/breakdown/sum_service_spec.rb
- spec/services/billable_metrics/breakdown/unique_count_service_spec.rb
- spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
- spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
This PR follow the recent release of the filter feature.
This PR removes reference to groups in Billable Metric Aggregators and Event Stores
> feat(filter): Remove legacy group logic

- app/graphql/types/membership_type.rb
- spec/graphql/resolvers/current_user_resolver_spec.rb
- spec/graphql/types/membership_type_spec.rb
I realized the `permissions` field was never implemented (nor tested). 🤦‍♂️
> fix: missing permissions attribute in MembershipType

- app/serializers/v1/integrations/customer_error_serializer.rb
- app/services/integrations/aggregator/contacts/base_service.rb
- app/services/webhooks/integrations/customer_error_service.rb
- spec/serializers/v1/integrations/customer_error_serializer_spec.rb
- spec/services/integrations/aggregator/contacts/create_service_spec.rb
- spec/services/integrations/aggregator/contacts/update_service_spec.rb
Integration customer error webhook now contains also `accounting_provider_code`
> feat(integrations): Add provider code to integration customer error webhook

- app/graphql/types/base_argument.rb
- app/graphql/types/base_input_object.rb
- app/graphql/types/current_organization_type.rb
- app/graphql/types/organizations/update_organization_input.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/organizations/update_spec.rb
- spec/graphql/resolvers/organization_resolver_spec.rb
- spec/graphql/types/current_organization_type_spec.rb
- spec/graphql/types/organizations/update_organization_input_spec.rb
- spec/support/matchers/graphql_field_permissions_matcher.rb
Granular permissions are being added to Lago.
Following #1926,  #1941, #1952 and #1969, this PR add permissions restriction to Organization-related endpoints.
For organization, both mutations and resolvers are accessible without permissions but many fields/arguments are restricted. 
**Line length: Remember that soon, with StandardRb, there is no line length restrictions** 😬
> feat(rbac): Add premissions on Organization (resolver and mutation)

- app/services/payment_provider_customers/stripe_service.rb
- spec/services/payment_provider_customers/stripe_service_spec.rb
This PR is an attempt to handle `Stripe::IdempotencyError` happening when a customer creation via API failed and does not properly save the `provider_customer_id` on the `PayementProviderCustoner::StripCustomer` instance.
The issue appears in some rare case of race conditions, but it puts the customer in an instable state, as it cannot be synced again on Stripe due to idempotency protection.
In case of `Stripe::IdempotencyError`, the service not tries to fetch the StripeCustomer from the API using the customer email. If only one matches the email, it is returned by the service and its ID is saved in the `provider_customer_id` field.
> fix(stripe): Handle IdempotencyError when creating customer

- app/services/invoices/subscription_service.rb
- spec/services/invoices/subscription_service_spec.rb
On days when a lot of invoices have to be generated, it's not uncommon that a `BillSubscriptionJob` job enqueued for processing stays in the queue for more than 1 hour. Since the clock job is running every hour, a new job to bill the same subscription might be enqueued twice (or more).
A logic to prevent double billing of the invoices was added (an index at DB level and a condition in the service creating the invoice subscription). Today this logic is simply raising an error leading to a lot of dead jobs. Since the invoice already exists, the dead job is generating a lot of useless noise and have to been manually removed.
This PR silents the  `BaseService::ServiceFailure` error with code `duplicated_invoices` in `Invoices::SubscriptionSerivces` when the `invoicing_reason` is …
> fix(invoice): Ignore duplicated_invoices error for recurring billing

- app/graphql/types/customers/create_customer_input.rb
- app/graphql/types/customers/update_customer_input.rb
- app/graphql/types/integration_customers/input.rb
- schema.graphql
- schema.json
- spec/graphql/types/integration_customers/input_spec.rb
This PR adds `integration` and `integration_code` to integration customer input and adds this input to customer inputs.
> feat(integrations): Add integration and integration_code to customer input

- app/graphql/lago_api_schema.rb
Currently, the overview of an invoice has a complexity of 305, that's why we decided to increase the value from 300 to 350.
> misc: Increase graphql max-complexity

- app/graphql/lago_api_schema.rb
Currently, we have one query with a depth of 15, that's why we decided to increase the value from 13 to 15.
> misc: Increase graphql max-depth

- lib/tasks/custom_aggregation.rake
- spec/scenarios/billable_metrics/custom_aggregation_spec.rb
This PR adds a `custom_aggregation:debug` rake task to make it easier to debug custom aggregators
> misc(custom_agg): Add a rake task to debug custom aggregation

- ci/clickhouse/config.xml
- db/clickhouse_migrate/20231024084411_create_events_raw.rb
- db/clickhouse_schema.rb
This PR is part of the high usage event ingestion epic.
It refacts the migration to create `events_raw` table to remove the hot/cold storage approach as Clickhouse cloud does not provide this feature.
> feat(clickhouse): Update schema for events_raw

- config/initializers/enable_yjit.rb
Following the recent update of Ruby to version 3.3.0, we can now enable Ruby YJIT
This PR simply adds an initializer to enable YJIT.
For more details, see:
- https://github.com/Shopify/yjit?tab=readme-ov-file
- https://github.com/ruby/ruby/blob/master/doc/yjit/yjit.md
- https://github.com/rails/rails/pull/49947
> misc: Enable YJIT

- app/jobs/payment_providers/stripe/register_webhook_job.rb
- app/jobs/send_webhook_job.rb
- app/models/payment_providers/stripe_provider.rb
- app/serializers/v1/payment_providers/error_serializer.rb
- app/services/payment_providers/stripe/base_service.rb
- app/services/payment_providers/stripe/register_webhook_service.rb
- app/services/payment_providers/stripe_service.rb
- app/services/webhooks/payment_providers/error_service.rb
- spec/jobs/payment_providers/stripe/register_webhook_job_spec.rb
- spec/serializers/v1/payment_providers/error_serializer_spec.rb
- spec/services/payment_providers/stripe/register_webhook_service_spec.rb
- spec/services/payment_providers/stripe_service_spec.rb
- spec/services/webhooks/payment_providers/error_service_spec.rb
Some `PaymentProviders::Stripe::RegisterWebhookJob` are failing with a `Stripe::AuthenticationError` error.
The error message is:
```
This API call cannot be made with a publishable API key. Please use a secret API key. You can find a list of your API keys at https://dashboard.stripe.com/account/apikeys.
```
Since this error cannot be handled by Lago, but must be addressed by the Lago organization admin, we need to inform the admin about it by sending a webhook and silent the error.
The PR refactors the stripe webhook endpoint creation by:
- Moving the registration logic from the generic `PaymentProviders::StripeService` into a dedicated `PaymentProviders::Stripe::RegisterWebhookService`
- Handling `Stripe::AuthenticationError`
- Delivering a `payment_provider.error`
- Returning an empty …
> misc(stripe): Handle Stripe::AuthenticationError when registering stripe webhook URL

- app/services/validators/decimal_amount_service.rb
- app/services/wallets/validate_recurring_transaction_rules_service.rb
- app/services/wallets/validate_service.rb
- spec/services/wallets/validate_service_spec.rb
When users create or edit a wallet they can define a recurring top-up rule.
If the rule is based on a threshold, the user can define this specific threshold.
Today the value set can be 0 or positive - we should be able to define a negative value also.
The goal of this PR is to accept negative values for `threshold_credits` by only validating the presence of a decimal instead of a positive amount.
> feat(wallet): Accept negative values for threshold_credits

- app/models/event.rb
- spec/models/event_spec.rb
Sometimes we receive `Error: NoMethodError: undefined method 'plan' for nil` error in `Fees::CreatePayInAdvanceJob`
We need to update `subscription` method in `event` model.
If the precision of `terminated_at` is higher than seconds which are used in condition (e.g., milliseconds), it could result in a discrepancy where the truncated timestamp used in the condition might not match exactly with the provided timestamp.
Based on investigation and various tests, it seems that using `millisecond` precision solves the issue
> fix(events): update event subscription method

- app/graphql/types/customers/create_customer_input.rb
- app/graphql/types/customers/update_customer_input.rb
- app/graphql/types/integration_customers/netsuite.rb
- app/services/customers/create_service.rb
- app/services/customers/update_service.rb
- app/services/integration_customers/create_or_update_service.rb
- schema.graphql
- schema.json
This PR fixes create service for integration customers when the params are empty.
> fix(integration-customer): Fix create service

- app/services/events/create_batch_service.rb
- app/services/events/create_service.rb
- add `ingested_at` field on kafka payload
- it permit a better tracking on when an event is ingested
> chore(kafka): add ingested_at field

- app/graphql/types/integration_customers/input.rb
- schema.graphql
- schema.json
- spec/graphql/types/integration_customers/input_spec.rb
This PR updates Input integration customer object for graphql side
> fix(integration-customers): update integration customers graphql input

- app/services/integration_customers/base_service.rb
- app/services/integrations/aggregator/contacts/create_service.rb
- spec/services/integration_customers/create_service_spec.rb
- spec/services/integration_customers/update_service_spec.rb
- spec/services/integrations/aggregator/contacts/create_service_spec.rb
This PR fixes `Integrations::Aggregator::Contacts::CreateService` because a new param `custentity_lago_sf_id` is mandatory now.
> fix(integration-customers): Fix integration customer create service

- app/services/integrations/aggregator/contacts/update_service.rb
- spec/services/integrations/aggregator/contacts/update_service_spec.rb
This PR fixes `Integrations::Aggregator::Contacts::UpdateService` because a new param `custentity_lago_sf_id` is present.
> fix(integration-customers): Fix integration customer update service

- app/models/integrations/base_integration.rb
- spec/models/integrations/base_integration_spec.rb
This PR handles destroying dependent integration customers after an integration is deleted.
> misc(integration-customers): Delete integration customers when integration is deleted

- app/models/integration_collection_mappings/base_collection_mapping.rb
- schema.graphql
- schema.json
- spec/models/integration_collection_mappings/netsuite_collection_mapping_spec.rb
Currently Lago does not support accounting integration
This PR adds new type `credit_note` which also needs to be mapped
> feat(accounting-integrations): add credit note type in collection mapping

- lib/tasks/custom_aggregation.rake
As we move toward Standard.rb, we might have some code merged that wasn't fixed with the latest rules. In PRs, rubocop only runs on modified files.
```
Offenses:
lib/tasks/custom_aggregation.rake:9:8: C: [Corrected] Layout/SpaceInsideHashLiteralBraces: Space inside { detected. (https://rubystyle.guide#spaces-braces)
{ total_units: BigDecimal('0'), amount: BigDecimal('0') }
^
lib/tasks/custom_aggregation.rake:9:62: C: [Corrected] Layout/SpaceInsideHashLiteralBraces: Space inside } detected. (https://rubystyle.guide#spaces-braces)
{ total_units: BigDecimal('0'), amount: BigDecimal('0') }
^
lib/tasks/custom_aggregation.rake:15:23: C: [Corrected] Layout/SpaceInsideHashLiteralBraces: Space inside { detected. (https://rubystyle.guide#spaces-braces)
previous_state = { total_units: …
```
> chore: rubocop

- app/graphql/types/base_organization_type.rb
- app/graphql/types/current_organization_type.rb
- app/graphql/types/organization_type.rb
- spec/graphql/resolvers/customer_portal/organization_resolver_spec.rb
I recently refactored GraphQL `OrganizationType` https://github.com/getlago/lago-api/pull/1919
`billing_configuration` is exposed in both Types but I forgot the resolution method in on type.
> fix(gql): Missing billing_configuration solution for OrganizationType

- app/graphql/types/membership_type.rb
- schema.graphql
- schema.json
- spec/graphql/types/membership_type_spec.rb
Role attribute is always present on membership model so it's type definition should reflect this
> misc: membership role cannot be null

- app/controllers/api/v1/customers_controller.rb
- app/graphql/types/integrations/netsuite.rb
- app/graphql/types/integrations/netsuite/create_input.rb
- app/models/integrations/netsuite_integration.rb
- app/services/integration_customers/update_service.rb
- app/services/integrations/netsuite/create_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/integrations/netsuite_spec.rb
- spec/services/integration_customers/update_service_spec.rb
This PR fixes multiple issue we found during the QA:
- Missing `integration_customers` in the customer serializer
- Integration customer update was not called
- `script_endpoint_url` should be mandatory
> fix(integrations): Address customer QA returns

- app/models/integration_item.rb
- app/models/integration_resource.rb
- app/models/integrations/base_integration.rb
- app/models/invoice.rb
- db/migrate/20240520115450_add_integration_id_to_integration_resources.rb
- db/schema.rb
- spec/factories/integration_resources.rb
- spec/models/integration_item_spec.rb
- spec/models/integration_resource_spec.rb
- spec/models/integrations/base_integration_spec.rb
This PR handles the following:
- Add `integration_id` foreign key in `integration_resources` DB table
- Remove `status_updated_to_finalized?` method in invoice model - not needed anymore
- Change uniqueness validation in `IntegrationItem` `external_id`: the scope should be `validates :external_id, uniqueness: {scope: [:integration_id, :item_type]}`
> fix(integrations): Add an association and indices

- .git-blame-ignore-revs
The goal of this PR is to put the appropriate commit SHA for ignoring TrailingCommaInHashLiteral changes on the blame.
> misc: Ignore TrailingCommaInHashLiteral commit for blame

- app/graphql/resolvers/memberships_resolver.rb
- app/graphql/types/memberships/metadata.rb
- app/services/memberships/revoke_service.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/memberships/revoke_spec.rb
- spec/graphql/resolvers/memberships_resolver_spec.rb
- spec/services/memberships/revoke_service_spec.rb
Granular permissions are being added to Lago.
In the frontend, we need to know how many admins there are currently on the app. We're adding a new custom attribute to the pagination metadata 😎
https://github.com/RenoFi/graphql-pagination?tab=readme-ov-file#custom-metadata
The backend is also updated so it won't let you delete the last admin anyway.
> feat(gql): Add admin_count custom metadata for organization members

- app/services/integration_customers/update_service.rb
- spec/services/integration_customers/update_service_spec.rb
This PR fixes a bug when the integration customer was not synced to Nango/Netsuite after an update.
> fix(integrations): Fix integration customer update service

- clock.rb
We don't want to process customer usage every 5 minutes if the caching sytem is not set.
> feat(wallet): Do not refresh wallets balance without cache

- app/graphql/types/webhooks/object.rb
UI is expecting webhooks's paylaod to be parsable as JSON.
This PR fixes this issue on the graphql type side.
> fix(webhooks): change webhook payload format

- app/models/integration_resource.rb
- app/models/sales_order.rb
- app/services/integrations/aggregator/invoices/base_service.rb
- app/services/integrations/aggregator/invoices/create_service.rb
- app/services/integrations/aggregator/sales_orders/create_service.rb
- db/migrate/20240522105942_add_resource_type_to_integration_resources.rb
- db/schema.rb
- spec/models/integration_resource_spec.rb
- spec/services/integrations/aggregator/invoices/create_service_spec.rb
- spec/services/integrations/aggregator/sales_orders/create_service_spec.rb
This PR adds logic for creating sales order in accounting provider.
The base for sales order is Lago's invoice. Payload is pretty much similar to the payload for creating invoice in accounting provider.
> feat (accounting-integrations): add logic for creating integration sales order

- spec/graphql/mutations/auth/okta/accept_invite_spec.rb
- spec/graphql/mutations/auth/okta/login_spec.rb
- spec/graphql/mutations/memberships/revoke_spec.rb
- spec/services/auth/okta/accept_invite_service_spec.rb
- spec/services/auth/okta/login_service_spec.rb
- spec/services/invoices/customer_usage_service_spec.rb
- spec/spec_helper.rb
I was writing tests with redis cache driver and realized we didn't have an easy way to set the drivers in tests.
This first PR introduce a simple way to pass metadata to your test and rspec will ensure that the correct cache driver is set.
It avoids mocking `Rails.cache`. 
In a following PR, I'll add the Redis driver (because I need it).
Note that it can be set on `describe` or `example`.
```rb
RSpec.describe Invites::AcceptService cache: :memory do
context 'with cache' do
it do
end
end
context 'without cache', cache: :null do
it do
end
end
end
```
> chore(tests): Add cache metadata to configure Rails.cache driver

- app/graphql/types/memberships/metadata.rb
- spec/graphql/resolvers/memberships_resolver_spec.rb
This metadata have been added recently
This value should only operate on active memberships of the current organization
> bug: admin_count should count active memberships

- app/controllers/api/v1/wallets_controller.rb
- app/graphql/types/wallets/recurring_transaction_rules/create_input.rb
- app/graphql/types/wallets/recurring_transaction_rules/method_enum.rb
- app/graphql/types/wallets/recurring_transaction_rules/object.rb
- app/graphql/types/wallets/recurring_transaction_rules/update_input.rb
- app/models/recurring_transaction_rule.rb
- app/serializers/v1/wallets/recurring_transaction_rule_serializer.rb
- app/services/wallets/create_service.rb
- db/migrate/20240521143531_add_target_ongoing_balance_to_recurring_transaction_rules.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/factories/recurring_transaction_rules.rb
- spec/graphql/mutations/wallets/create_spec.rb
- spec/graphql/mutations/wallets/update_spec.rb
- spec/graphql/types/wallets/recurring_transaction_rules/create_input_spec.rb
- spec/graphql/types/wallets/recurring_transaction_rules/object_spec.rb
- spec/graphql/types/wallets/recurring_transaction_rules/update_input_spec.rb
- spec/requests/api/v1/wallets_controller_spec.rb
- spec/serializers/v1/wallets/recurring_transaction_rule_serializer_spec.rb
- spec/services/wallets/create_service_spec.rb
- spec/services/wallets/recurring_transaction_rules/update_service_spec.rb
- spec/services/wallets/update_service_spec.rb
- add `target_ongoing_balance` to `recurring_transaction_rules` table
- accept `method` and `target_ongoing_balance` on wallet creation (API & GraphQL)
- accept `method` and `target_ongoing_balance` on wallet update (API & GraphQL)
> feat(wallet): Handle method and target_ongoing_balance for recurring transaction rule

- app/graphql/types/invoices/object.rb
- schema.graphql
- schema.json
This PR adds `external_id` to the invoice object so that proper URL on integration provider can be displayed in the UI
> feat(integrations): return external_id in invoice graphql object

- app/jobs/invoices/generate_pdf_job.rb
From time to time some `Invoices::GeneratePdfJob` are failing with the following error:
```
HTTP 503 - URI: http://pdf-web.default.svc.cluster.local/forms/chromium/convert/html. Error: Service Unavailable
```
Since to fix the issue we usually just have to retry the job, the retry could be automated.
This PR adds a `retry_on` attribute for `LagoHttpClient::HttpError` for 6 attemps with exponnential wait time between each retry.
> misc: Auto retry PDF generate jobs in case of HTTP errors

- app/services/invoices/calculate_fees_service.rb
This add taxes preloading for charge in the `Invoices::CalculateFeesService` used to create charge fees on invoice and for current usage
> misc: Preload taxes for charge fees creation

- .rubocop.yml
No offenses are currently present on the codebase.
> misc: Enable TrailingCommaInBlockArgs rubocop rule

- app/services/integrations/aggregator/base_service.rb
- app/services/integrations/aggregator/contacts/base_service.rb
- app/services/integrations/aggregator/invoices/create_service.rb
- app/services/integrations/aggregator/sales_orders/create_service.rb
- spec/services/integrations/aggregator/invoices/create_service_spec.rb
- spec/services/integrations/aggregator/sales_orders/create_service_spec.rb
This PR adds a webhook that is sent after creating an invoice fails in Nango.
> fix(integrations): Send webhook after create invoice fails

- app/graphql/types/add_ons/object.rb
- app/graphql/types/billable_metrics/object.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/add_ons_resolver_spec.rb
This PR adds possibility to filter (by integration id) all mappings that belong to certain add-on or billable metric.
> fix (integrations): add possibility to filter bm and add-ons in graphql resolvers

- app/services/wallets/recurring_transaction_rules/validate_service.rb
- app/services/wallets/validate_service.rb
- spec/graphql/mutations/wallets/create_spec.rb
- spec/services/wallets/recurring_transaction_rules/validate_service_spec.rb
- spec/services/wallets/validate_service_spec.rb
The goal of this PR is to extract how we're validating recurring transaction rule parameters into a separate class.
Indeed, we'll add other validations in the next PRs, and doing this prerequisite will help.
> feat(wallet): Extract validation of RecurringTransactionRule

- clock.rb
Some users don't need wallet refresh background job
This PR provides a way to disable refresh wallet job which can lead to performace issues
> misc: add disable wallet refresh env var

- app/services/wallets/recurring_transaction_rules/validate_service.rb
- app/services/wallets/validate_recurring_transaction_rules_service.rb
- spec/requests/api/v1/wallets_controller_spec.rb
- spec/services/wallets/recurring_transaction_rules/validate_service_spec.rb
- spec/services/wallets/validate_recurring_transaction_rules_service_spec.rb
- Add validation on credits for recurring transaction rules
- Remove duplication on wallet rules validation
> feat(wallet): Remove duplication on wallet rules validation

- app/services/invoices/customer_usage_service.rb
This PR follows https://github.com/getlago/lago-api/pull/2076
It tries to fix an issue with the connection pool:
```
could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use (ActiveRecord::ConnectionTimeoutError)
```
> fix(current-usage): Manage connection pools with parallel threads

- app/services/integrations/aggregator/invoices/base_service.rb
- app/services/integrations/aggregator/invoices/create_service.rb
- app/services/integrations/aggregator/sales_orders/create_service.rb
Allow to sync invoice even if no item is mapped.
> feat(integrations): Allow to sync invoice even if no item is mapped

- app/services/wallets/create_service.rb
- app/services/wallets/recurring_transaction_rules/create_service.rb
- spec/services/wallets/create_service_spec.rb
- spec/services/wallets/recurring_transaction_rules/create_service_spec.rb
The goal of this PR is to extract logic for the creation of wallet transaction rule into his own class.
> feat(wallet): Extract creation of wallet transaction rule

- app/services/subscriptions/terminate_service.rb
- spec/services/subscriptions/terminate_service_spec.rb
This pull request addresses the issue where pending subscriptions are incorrectly marked as terminated when canceled. The goal is to ensure that pending subscriptions are marked as canceled, without incorrectly triggering termination-related webhooks.
When an active subscription is terminated, it should be marked as terminated, but when a pending subscription is deleted, it should be marked as canceled
> fix(subscription): Pending subscription cancel status

- app/models/credit_note.rb
- spec/models/credit_note_spec.rb
This PR adds `should_sync_credit_note?` method to `CreditNote` model.
> fix(integrations): Sync credit notes add should_sync_credit_note?

- app/services/subscriptions/charge_cache_service.rb
- lib/tasks/cache.rake
This PR adds a new rake task to allow the removal of the cache of a given subscription:
```bash
rails cache:expire_subscription_cache subscription_id=XXX
```
> misc: Add a rake task to expire the cache of a given subscription

- app/models/integrations/anrok_integration.rb
- app/models/integrations/base_integration.rb
- spec/factories/integrations.rb
- spec/models/integrations/anrok_integration_spec.rb
Lago does not support tax tool integrations, but support for it is being implemented.
This PR adds required model changes. We are using existing `integrations` table.
> feat(tax-integration): add anrok model changes

- app/graphql/types/webhooks/object.rb
- app/models/webhook.rb
- spec/factories/webhooks.rb
- spec/graphql/resolvers/webhooks_resolver_spec.rb
- spec/models/webhook_spec.rb
I recently [refactored the webhook](https://github.com/getlago/lago-api/pull/1993) model to split the SendWebhookJob into 2 jobs.
The payload was previously stored as a string (json serialized hash) inside a JSON column. 
It's now a hash stored in a JSON column.
I introduced a bug where the webhook sent to the GraphQL API wasn't in the format expected.
@lovrocolic fixed in https://github.com/getlago/lago-api/pull/2053
Currently, if you open an old webhook, `w.payload` will return a string. Newer payload would return a hash.
This PR ensures you always get a hash.
Note that there was no release since #1993.
Webhooks are deleted after 90 days, so "one day", all webhooks will be stored in hash.
> fix(webhook): Deserialize payload for older webhooks

- app/services/utils/datetime.rb
- spec/services/utils/datetime_spec.rb
Some issues have been reported on the go client with the handling of `started_at` and `ending_at`.
The go client is sending the values with milliseconds, leading to a bug with the validation on Lago side since the validator relies on `DateTime`, which is deprecated in favor of `Time`
This PR makes sure that Time with microseconds are correctly handled and validated
> fix(subscription): fix handling of started_at/ended_at

- app/controllers/api/v1/wallets_controller.rb
- app/graphql/mutations/wallets/update.rb
- app/services/wallets/update_service.rb
- spec/services/wallets/update_service_spec.rb
- Refactor `Wallets::UpdateService#update` to `Wallets::UpdateService#call`
- Refresh wallet balance on update
> feat(wallet): Refresh wallet balance on update

- app/jobs/integrations/aggregator/credit_notes/create_job.rb
- app/services/integrations/aggregator/credit_notes/create_service.rb
- spec/jobs/integrations/aggregator/credit_notes/create_job_spec.rb
- spec/services/integrations/aggregator/credit_notes/create_service_spec.rb
This PR adds `Integrations::Aggregator::CreditNotes::CreateJob`
> fix(integrations): Sync credit notes - create job

- app/views/helpers/fee_display_helper.rb
- app/views/templates/invoices/v4/_subscription_details.slim
👉  https://getlago.canny.io/feature-requests/p/hide-fees-at-zero
Users do not want to display subscription fee on invoice when the amount is 0.
This PR ensures that the subscription fee is hidden on the invoice except when no other charge fees are visible as well
> feat(invoice): Hide subscription fee when 0

- app/controllers/api/v1/wallets_controller.rb
- app/graphql/types/wallets/recurring_transaction_rules/create_input.rb
- app/graphql/types/wallets/recurring_transaction_rules/object.rb
- app/graphql/types/wallets/recurring_transaction_rules/update_input.rb
- app/serializers/v1/wallets/recurring_transaction_rule_serializer.rb
- app/services/wallets/recurring_transaction_rules/create_service.rb
- db/migrate/20240530123427_add_started_at_to_recurring_transaction_rules.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/graphql/types/wallets/recurring_transaction_rules/create_input_spec.rb
- spec/graphql/types/wallets/recurring_transaction_rules/object_spec.rb
- spec/graphql/types/wallets/recurring_transaction_rules/update_input_spec.rb
- spec/serializers/v1/wallets/recurring_transaction_rule_serializer_spec.rb
- spec/services/wallets/recurring_transaction_rules/create_service_spec.rb
- spec/services/wallets/recurring_transaction_rules/update_service_spec.rb
The goal of this PR is to add `started_at` to `recurring_transaction_rules`.
> feat(wallet): Add started_at to recurring_transaction_rules

- app/graphql/resolvers/integrations_resolver.rb
- app/graphql/types/integrations/anrok.rb
- app/graphql/types/integrations/object.rb
- schema.graphql
- schema.json
- spec/graphql/types/integrations/anrok_spec.rb
Lago does not support tax tool integrations, but support for it is currently being implemented.
This PR adds required graphql type for Anrok integration
> feat (tax-integrations): add anrok graphql type

- app/graphql/types/integrations/netsuite.rb
This PR fixes `has_mappings_configured` in netsuite GraphQL type
> fix(integrations): Fix has_mappings_configured in netsuite GraphQL type

- app/graphql/types/credit_notes/object.rb
- schema.graphql
- schema.json
- spec/graphql/types/credit_notes/object_spec.rb
- spec/graphql/types/invoices/object_spec.rb
This PR adds external_integration_id to CreditNote GraphQL type
> fix(integrations): Add external_integration_id to CreditNote GraphQL type

- lib/tasks/filters.rake
In some cases, the migration from groups to charge filters introduces some duplicated filters, leading to a risk of double billing of some events on some production accounts.
This PR introduces a new `filters:deduplicate` rake task to remove duplicated filters and only keep one for each group of keys/values
> misc: Add a task to soft remove duplicated filters

- app/services/utils/pdf_generator.rb
- lib/lago_http_client/lago_http_client/client.rb
- PDF service is configured to have a 300s timeout
- Add support for HttpClient to support higher read timeout
> fix(pdf): Add read timeout for PDF service calls

- db/migrate/20240603080144_fix_quantified_event_migration.rb
- db/schema.rb
A migration task to migrate `QuantifedEvent` into `CachedAggregation` was invalid and did not migrate the values in a proper way, leading to inssue with the computation of recurring weighted  sum aggregation  
This PR adds the same migration with a fix for `started_at`/`terminated_at` boundaries
> fix: Rerun QuantifiedEvent migration into CachedAggregation

- app/jobs/fees/create_pay_in_advance_job.rb
- app/services/fees/create_pay_in_advance_service.rb
- spec/jobs/fees/create_pay_in_advance_job_spec.rb
- spec/services/fees/create_pay_in_advance_service_spec.rb
When a charge is `invoiceable: true, pay_in_advance: true` an invoice is created every time an event is received. If the  Billable Metrics attached is `recurring: true`, each month this charge will be added to the subscription invoice.
If the charge is `invoiceable: false, pay_in_advance: true` a fee is created every time an even is received (but no invoice). If the  Billable Metrics attached is `recurring: true`, nothing happens each months.
We want to change this behavior and create a new Fee each month.
Each time a new fee is created for the new period, we'll continue to attach it to the same event that triggered it in the first place.
In this PR, we extract the "timestamp" into an arg so on following months, we can use the correct billing date instead of relying on the time of the …
> feat(fees): Add billing_at arg to CreatePayInAdvance flow

- app/controllers/api/v1/wallets_controller.rb
- app/graphql/mutations/wallets/create.rb
- app/graphql/types/wallets/recurring_transaction_rules/create_input.rb
- app/services/wallets/balance/update_ongoing_service.rb
- app/services/wallets/create_service.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/services/wallets/create_service_spec.rb
The goal of this PR is to be able to create recurring transaction rule by passing `granted_credits` and `paid_credits` fields (without taking the ones defined on the wallet object).
> feat(wallet): Add granted and paid credits on recurring transaction rule

- db/migrate/20240603095841_refresh_cached_aggregations.rb
- db/schema.rb
This PR follows: https://github.com/getlago/lago-api/pull/2114
The goal of this PR is to recompute the cached aggregation for the subscription that were impacted by the migration issue.
It will ensure that next invoice will use the right initial values for recurring weighted sum aggregation
> fix: Add migration to recompute weighted sum cached aggregation

- app/queries/credit_notes_query.rb
- spec/graphql/resolvers/credit_notes_resolver_spec.rb
- spec/queries/credit_notes_query_spec.rb
We'll be adding a new view to list all credit notes for all customers
This PR adapts the query to scope to the organization instead of the customers.
> fix(gql): Add credit note filter on query

- app/config/permissions/definition.yml
- app/config/permissions/role-finance.yml
- app/config/permissions/role-manager.yml
- app/graphql/concerns/can_require_permissions.rb
- app/graphql/mutations/customers/update.rb
- app/graphql/mutations/customers/update_invoice_grace_period.rb
- app/graphql/resolvers/payment_providers_resolver.rb
- app/graphql/types/base_argument.rb
- app/graphql/types/customers/billing_configuration_input.rb
- app/graphql/types/customers/update_customer_input.rb
- app/graphql/types/payment_providers/adyen.rb
- app/graphql/types/payment_providers/gocardless.rb
- app/graphql/types/payment_providers/stripe.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/customers/update_invoice_grace_period_spec.rb
- spec/graphql/mutations/customers/update_spec.rb
- spec/graphql/mutations/integrations/anrok/update_spec.rb
- spec/graphql/mutations/payment_providers/adyen/create_spec.rb
- spec/graphql/mutations/payment_providers/adyen/update_spec.rb
- spec/graphql/mutations/payment_providers/gocardless/create_spec.rb
- spec/graphql/mutations/payment_providers/gocardless/update_spec.rb
- spec/graphql/mutations/payment_providers/stripe/create_spec.rb
- spec/graphql/mutations/payment_providers/stripe/update_spec.rb
- spec/graphql/resolvers/payment_providers_resolver_spec.rb
- spec/graphql/types/payment_providers/adyen_spec.rb
- spec/graphql/types/payment_providers/gocardless_spec.rb
- spec/graphql/types/payment_providers/stripe_spec.rb
- spec/support/shared_examples/graphql_requirements.rb
Granular permissions are coming to Lago.
After some testing we realized a few things weren't working as expected. 
The diff is  long but this PR basically adjust mutations and resolver permissions. Some mutations need to be access with multiple permission, then the Input will control what field can be updated depending on your permissions.
I also removed `subscriptions:delete` because it wasn't used. We use `subscriptions:update` to terminate a subscriptions, it can't be "deleted".
> fix(rbac): Adjust permissions

- app/models/payment.rb
- spec/models/payment_spec.rb
This PR adds `should_sync_payment?` method to `Payment` model.
> feat(integrations): Add should_sync_payment? to Payment

- app/services/wallets/balance/update_ongoing_service.rb
- app/services/wallets/create_interval_wallet_transactions_service.rb
- app/services/wallets/create_service.rb
- app/services/wallets/threshold_top_up_service.rb
- app/services/wallets/validate_service.rb
- spec/services/wallets/balance/update_ongoing_service_spec.rb
- spec/services/wallets/create_interval_wallet_transactions_service_spec.rb
- spec/services/wallets/threshold_top_up_service_spec.rb
- extract wallet top up into his own class
- handle target top up
> feat(wallet): Extract wallet threshold top up

- app/services/invoices/payments/stripe_service.rb
- app/services/payment_providers/stripe_service.rb
- spec/services/invoices/payments/stripe_service_spec.rb
Some dead jobs were received lately for `PaymentProviders::Stripe::HandleEventJob` with an `ActiveRecord::RecordNotFound (Couldn't find Invoice with 'id'=XXXX)`  error.
The event type of the webhook was a `charge.succeeded` and it was related to an `one_off` invoice.
After investigation it appears that the webhook was comming from Lago stripe account in test mode. Most certainly configured in a staging, and so was not related to production invoices.
This PR changes the invoice lookup behavior, to bubble-up a Not Found error if the invoice is not found in the DB. The webhook handler catches the error and ignore it if the event is comming from an account with tthe flag `"livemode": false`
> fix(stripe): Ignore invoice not found error when in test mode

- app/jobs/integrations/aggregator/payments/create_job.rb
- app/services/integrations/aggregator/payments/create_service.rb
This PR fixes the problem when the invoice for a payment is not synced yet. In that case we let the payment sync job fail so that when it retries the invoice is already synced.
> fix(integrations): Fix payments sync when the invoice is not synced yet

- app/jobs/send_email_job.rb
This PR enable the auto-retry mechanism for email delivery in case of `Net::ReadTimeout` network error
> misc: Retry email jobs on Net::ReadTimeout error

- app/services/invoices/add_on_service.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- app/services/invoices/create_service.rb
- app/services/invoices/finalize_service.rb
- app/services/invoices/paid_credit_service.rb
- app/services/invoices/subscription_service.rb
- spec/services/invoices/add_on_service_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
- spec/services/invoices/create_service_spec.rb
- spec/services/invoices/finalize_service_spec.rb
- spec/services/invoices/paid_credit_service_spec.rb
- spec/services/invoices/subscription_service_spec.rb
- spec/support/shared_examples/integrations.rb
This PR modifies some of the invoice services to enqueue sync jobs for invoices and sales orders when needed.
> feat(integrations): Trigger invoices and sales orders syncs

- app/services/credit_notes/create_service.rb
- spec/services/credit_notes/create_service_spec.rb
- spec/support/shared_examples/integrations.rb
This PR modifies credit notes service to enqueue sync jobs for credit notes.
> feat(integrations): Trigger credit notes sync

- db/migrate/20240314172008_link_filters_to_cached_aggregation.rb
Some customers using Lago on a self hosted mode have faced issue with the migration converting `Group` into `ChargeFilter`.
The main point is that the part trying to migrate group attached to fees into charges is very very slow on system counting a lot off fees. 
This PR tries to remediate this situation by preloading as much records as possible to reduce the number of calls to the database.
It also fixes some edge case that could lead to duplicated filters on some charges
> misc: Try to speed up group to filter migration

- Gemfile
- Gemfile.lock
- app/jobs/clock/activate_subscriptions_job.rb
- app/jobs/clock/create_interval_wallet_transactions_job.rb
- app/jobs/clock/events_validation_job.rb
- app/jobs/clock/finalize_invoices_job.rb
- app/jobs/clock/free_trial_subscriptions_biller_job.rb
- app/jobs/clock/refresh_draft_invoices_job.rb
- app/jobs/clock/refresh_wallets_ongoing_balance_job.rb
- app/jobs/clock/subscriptions_biller_job.rb
- app/jobs/clock/subscriptions_to_be_terminated_job.rb
- app/jobs/clock/terminate_coupons_job.rb
- app/jobs/clock/terminate_ended_subscriptions_job.rb
- app/jobs/clock/terminate_wallets_job.rb
- app/jobs/clock/webhooks_cleanup_job.rb
- app/jobs/concerns/sentry_cron_concern.rb
- clock.rb
- config/application.rb
- config/initializers/sentry.rb
Reapply changes from https://github.com/getlago/lago-api/pull/2109 that were reverted in https://github.com/getlago/lago-api/pull/2112 due to errors with the clock job processing
> Reapply "misc: Add scheduler monitoring for sentry if enabled" (#2112)

- app/services/payment_providers/stripe_service.rb
Similar to https://github.com/getlago/lago-api/pull/2124
Some dead jobs were received lately for `PaymentProviders::Stripe::HandleEventJob` with an `BaseService::NotFoundFailure (invoice_not_found)`  error.
The event type of the webhook was a `payment_intent.succeeded` and it was related to an `one_off` invoice.
After investigation it appears that the webhook was coming from Lago stripe account in test mode. Most certainly configured in a staging, and so was not related to production invoices.
This PR changes the invoice lookup behavior, to bubble-up a Not Found error if the invoice is not found in the DB. The webhook handler catches the error and ignore it if the event is coming from an account with the flag `"livemode": false`
> fix(stripe): Add more ignore invoice not found error when in test mode

- app/services/base_service.rb
- spec/services/base_service_spec.rb
All services inherit from `BaseService`. Many services override the `initialize` constructor method and call `super`.
The BaseService constructor only accepts one argument: the current user. When we call `super` without parenthesis, the argument are forwarded to the parent. Most of the time, we call the parent constructor without the parenthesis.
It means that in many many case, the result returned by the service has a `result.user` which old something else, not a user.
We heavily use the named parameters so most of the time, it's a hash with the argument of the descendant service.
One way to fix this is to go and modify all calls to `super` and replace them with `super(nil)`. I think a better way is to ignore the current_user if it's not an instance of `User`.
```ruby
module AddOns
class …
```
> fix(service): Ignore current_user if it's not an instance of User

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
I use `pp` a lot to print variables or messages when I'm debugging with tests. Unfortunately, it's printing only one line without colors in my tests. It's all pretty in the console. I must be missing something but one solution I like is to use the `awesome_print` gem.
Am I the only one with this problem?
You can go and uncomment one line to easily see where you left your `pp`. 
Especially useful when you started editing gems 😬
> chore(spec): Use `awesome_print` to debug tests

- app/services/integration_customers/anrok_service.rb
- app/services/integration_customers/create_service.rb
- app/services/integration_customers/factory.rb
- app/services/integration_customers/netsuite_service.rb
- spec/services/integration_customers/anrok_service_spec.rb
- spec/services/integration_customers/create_service_spec.rb
- spec/services/integration_customers/netsuite_service_spec.rb
Lago does not support tax tool integrations, but support for it is currently being implemented.
This PR adds needed changes in create integration service.
Anrok does not sync customer right away. Instead, customer is synced when the first document is sent to the anrok.
Based on requirements from above, we changed a bit generic create service so that it works based on specific integration needs.
> feat(anrok-integration): refactor create integration customer service

- app/graphql/types/customers/object.rb
- app/graphql/types/integration_customers/anrok.rb
- app/models/customer.rb
- app/models/integration_collection_mappings/anrok_collection_mapping.rb
- app/models/integration_customers/anrok_customer.rb
- app/models/integration_customers/base_customer.rb
- app/models/integration_mappings/anrok_mapping.rb
- app/models/organization.rb
- app/services/integration_collection_mappings/factory.rb
- app/services/integration_customers/anrok_service.rb
- app/services/integration_customers/create_service.rb
- app/services/integration_customers/factory.rb
- app/services/integration_customers/netsuite_service.rb
- app/services/integration_customers/update_service.rb
- app/services/integration_mappings/factory.rb
- db/migrate/20240604141208_change_integration_customer_external_id_nullable_option.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/graphql/types/customers/object_spec.rb
- spec/graphql/types/integration_customers/anrok_spec.rb
- spec/services/integration_customers/anrok_service_spec.rb
- spec/services/integration_customers/create_service_spec.rb
- spec/services/integration_customers/netsuite_service_spec.rb
Lago does not support tax tool integrations, but support for it is currently being implemented.
This PR adds required graphql type for Anrok integration
> feat(tax-integration): Add base logic for anrok customer and mapping

- app/services/billable_metric_filters/create_or_update_batch_service.rb
There was a bug in filters.
After removing a value from billable metric filter the whole charge filter was discarded - not just the value.
This PR fixes this bug in `BillableMetricFilters::CreateOrUpdateBatchService`
> fix(filters): Fix deleting filters

- app/models/billable_metric.rb
- app/models/charge.rb
- app/services/events/post_process_service.rb
- spec/models/billable_metric_spec.rb
- spec/services/events/post_process_service_spec.rb
Whenever a event associated with PayInAdvance charge is recieved, we create a Fee for this event.
The validation was performed only after we create the Fee for `invoiceable: false` charges creating some disparities if the charge is invoiceable or not.
I realized that there is already a validation on the aggregation in the Charge model, which I refactored.
~I have removed all the validation in the PostProcess events because, you're not supposed to be able to create invalid charge (see Charge model validation) and if you send events without the `properties[bm.field_name]`, I'm not sure it should fail silently.~ It creates a fee even without valid properties so I'm keeping the condition as-is, but earlier in the function.
> feat(events): Refactor PayInAdvance Billable Metric validation

- app/models/events/common.rb
- app/services/events/common_factory.rb
- spec/factories/clickhouse_events.rb
- spec/factories/common_events.rb
- spec/models/events/common_spec.rb
- spec/services/events/common_factory_spec.rb
Today Clickhouse integration does not support pay in advance aggregation.
To do so, we need to refactor some logic that relies on the `events` table located in Postgres database to move to a DB agnostic approach. It will allow us to handle events coming from the API and from Kafka (via Sidekiq)
This PR, introduces a new model `Events::Common` and a `Events::CommonFactory` to create an instance from any source.
This model will later be used in place of `Event` model in all location related to `pay_in_advance` aggregation
> feat(clickhouse): Introduce Events::Common for in advance aggregation

- app/jobs/invoices/payments/stripe_create_job.rb
This pull request enables the auto retry for `Stripe::APIConnectionError` on `Invoices::Payments::StripeCreateJob` to avoid dead jobs that should just be retried
> fix(stripe): Enable auto retry for APIConnectionError on payment job

- app/services/payment_providers/stripe/register_webhook_service.rb
- spec/services/payment_providers/stripe/register_webhook_service_spec.rb
The `PaymentProviders::Stripe::RegisterWebhookJob`  job sometimes failed to register the webhook on Stripe and raises a
`Stripe::InvalidRequestError (You have reached the maximum of 16 test webhook endpoints)`.
Since this error cannot be fixed by Lago and requires a manual action on the customer side and since most of the time the it is related to a test API key, it should not end in the dead queue.
This PR changes the current behavior to avoid generating a dead job but to emit a `payment_provider.error` error webhook instead
> misc(stripe): Avoid dead jobs for register webhook errors

- app/services/base_service.rb
- app/services/payment_providers/adyen_service.rb
- app/services/payment_providers/stripe_service.rb
This PR improves the `Result#raise_if_error!` method  in order to return the result if it is a success, allowing use to write thing like `return result.raise_if_error!` instead of `return result.raise_if_error! || result`
This new approach is then used in some refactors in `PaymentProviders::AdyenService` and `PaymentProviders::StripeService`
Finally a new `raise_if_error!` is added to the result of the `PaymentProviders::Webhooks::Stripe::ChargeDisputeClosedService#call` to ignore missing payment error when stripe has flag `livemode` set to `false`
> misc(payment_webhook): Improve result management

- app/controllers/api/v1/billable_metrics_controller.rb
- app/models/billable_metric.rb
The billable metric index route appears to be slow in API in some cases.
This PR tries to speed it up a bit by preloading attached `filters` and `groups` . 
NOTE: Billable metric serializer is also exposing three counters: (`active_subscriptions_count`, `draft_invoices_count` and `        plans_count`), that are slowing down this route. A discussion will be opened about it soon.
> misc(billable_metric): preload filters and groups in index route

- app/graphql/types/integration_mappings/create_input.rb
- app/graphql/types/integration_mappings/object.rb
- schema.graphql
- schema.json
- spec/graphql/types/integration_mappings/create_input_spec.rb
- spec/graphql/types/integration_mappings/object_spec.rb
Currently Lago does not support tax integrations
When creating Anrok mapping object `code` is not required so we need to change our generic gql mapping definitions
> fix (integrations): enable optional code when creating mapping object

- app/jobs/invoices/payments/adyen_create_job.rb
Some `Invoices::Payments::AdyenCreateJob ` failed with a `Faraday::ConnectionFailed`
Since it is a temporary error with the Adyen API, these jobs should be reprocessed automatically instead of ending in the dead queue.
This PR adds the retry system for the `Faraday::ConnectionFailed`
> fix(adyen): Retry payment creation on Faraday::ConnectionFailed

- app/jobs/payment_provider_customers/stripe_create_job.rb
This PR ensures that the `PaymentProviderCustomers::StripeCreateJob` does not end in the dead job queue if the stripe api secret is invalid. 
It will only deliver an error webhook to the account owner.
> misc(stripe): Avoid dead job for invalid key when creating customers

- app/graphql/types/invoices/object.rb
- app/jobs/clock/mark_invoices_as_payment_overdue_job.rb
- app/jobs/send_webhook_job.rb
- app/models/invoice.rb
- app/serializers/v1/invoice_serializer.rb
- app/services/customers/create_service.rb
- app/services/customers/update_service.rb
- app/services/invoices/update_service.rb
- app/services/webhooks/invoices/payment_overdue_service.rb
- clock.rb
- db/migrate/20240611074215_add_payment_overdue_to_invoices.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/graphql/types/invoices/object_spec.rb
- spec/jobs/clock/mark_invoices_as_payment_overdue_job_spec.rb
- spec/models/invoice_spec.rb
- spec/serializers/v1/invoice_serializer_spec.rb
- spec/services/invoices/update_service_spec.rb
- spec/services/webhooks/invoices/payment_overdue_service_spec.rb
The goal of this PR is to add:
- `payment_overdue`
to `invoice`
> feat(dunning): Add payment_overdue to invoice

- app/services/invoices/subscription_service.rb
In case of `Sequenced::SequenceError` in the `Invoices::SubscriptionService`, called by the `BillSubscriptionJob`, the generating invoice is not reattached to the renqueued job, leading to a dead job caused by a `ActiveRecord::RecordNotUnique` error.
This behavior leads to a lot of dead jobs that cannot be reprocessed automatically and that leave invoices stuck in the `generating` status
This PR makes sure that every error happening in the `Invoices::SubscriptionService` are converted into an error result, allowing the  `BillSubscriptionJob` to attached the generating `invoice` to the new generation attempt.
It should fix most of the `ActiveRecord::RecordNotUnique` errors happening in this job
> fix(invoice): make sure generating invoices are re-attached to the billing jobs

- app/services/subscriptions/create_service.rb
- spec/requests/api/v1/subscriptions_controller_spec.rb
- spec/services/subscriptions/create_service_spec.rb
When a user tries to create a subscription via API without providing external_customer_id, the API returns a 422 error.
This is the expected behaviour, but the reason is incorrect: it says "external_id": ["value is mandatory"] instead of "external_customer_id": ["value is mandatory"].
Add guard clause to `Subscriptions::CreateService` to ensure `external_customer_id` is provider or return a validation error with the right details as result.
> fix(subscriptions): Fix incorrect `error_details` when creating a subscription without `external_customer_id`

- app/jobs/invoices/generate_pdf_and_notify_job.rb
- app/jobs/invoices/generate_pdf_job.rb
We recently introduced a new queue to generate PDF https://github.com/getlago/lago-api/pull/2121
This PR moves the existing `GeneratePdfJob` to this queue.
> fix(pdf): Move GeneratePdfJob to new pdfs queue

- app/services/invoices/create_invoice_subscription_service.rb
- spec/services/invoices/create_invoice_subscription_service_spec.rb
In some cases, when retrying to bill a subscription for a subscription start (after a dead job), it could end into an error if the subscription has been terminated in between the initial invoice and the retry.
This PR ensures that the `subscription_terminating` is assigned to the `invoice_subscription` only when it should
> fix(subscription): check terminated_at for invoicing_reason

- app/controllers/api/v1/customers_controller.rb
- app/graphql/types/customers/create_customer_input.rb
- app/graphql/types/customers/update_customer_input.rb
- app/serializers/v1/integration_customer_serializer.rb
- app/services/customers/create_service.rb
- app/services/customers/update_service.rb
- app/services/integration_customers/create_or_update_service.rb
- app/services/integration_customers/create_service.rb
- schema.graphql
- schema.json
- spec/services/customers/create_service_spec.rb
- spec/services/integration_customers/create_or_update_service_spec.rb
Currently Lago app is being extended with accounting and tax integrations
For accounting integrations, we could have only **one** integration customer per customer create/update request.
However, with tax integrations, Lago should support multiple integration customers per request. That being said, Lago should be able to create integration customer object related to tax provider and integration customer object for accounting provider.
This PR handles described scenario and supports array of integration customers from both GQL and API.
This update is NOT a breaking change since released accounting integration is premium add-on and is not being used in production yet.
> feat(integrations): support array of integration customers

- app/graphql/types/integrations/anrok/create_input.rb
- app/models/integrations/anrok_integration.rb
- app/services/integrations/anrok/create_service.rb
- schema.graphql
- schema.json
- spec/factories/integrations.rb
- spec/graphql/mutations/integrations/anrok/create_spec.rb
- spec/models/integrations/anrok_integration_spec.rb
- spec/services/integrations/anrok/create_service_spec.rb
Currently Lago does not support tax integrations
When Lago create integration object, `connection_id` also needs to be stored. This is identifier in Nango (integrations aggregator) and it will be used in all requests from Lago's BE.
> feat (anrok-integration): add support for connection_id

- app/models/customer.rb
- app/models/integration_customers/base_customer.rb
- app/models/integration_customers/xero_customer.rb
- app/serializers/v1/integration_customer_serializer.rb
- spec/factories/integration_customers.rb
- spec/models/customer_spec.rb
- spec/models/integration_customers/base_customer_spec.rb
- spec/serializers/v1/integration_customer_serializer_spec.rb
This PR adds and modifies integration customer models and a serializer for Xero integration.
> feat(xero): Add customer models and serializer

- app/graphql/mutations/invoices/retry_all_payments.rb
- app/jobs/invoices/payments/retry_all_job.rb
- app/services/invoices/payments/retry_batch_service.rb
- spec/services/invoices/payments/retry_batch_service_spec.rb
Insignificant but `result.throw_error` doesn't exist.
@ivannovosad and @vincent-pochet recently introduced `call_async` in services so why not use it instead of `call_later`.
> fix(service): Use call_later for RetryAllJob and raise if error

- app/controllers/api/v1/invoices_controller.rb
- app/graphql/resolvers/invoices_resolver.rb
- app/queries/invoices_query.rb
- app/services/invoices/void_service.rb
- schema.graphql
- schema.json
- spec/queries/invoices_query_spec.rb
- spec/requests/api/v1/invoices_controller_spec.rb
- spec/services/invoices/void_service_spec.rb
The goal of this PR is to add `payment_overdue` filter when fetching invoices.
> feat(dunning): Add payment_overdue filter on invoices

- app/jobs/events/pay_in_advance_job.rb
- app/jobs/events/pay_in_advance_kafka_job.rb
- app/jobs/fees/create_pay_in_advance_job.rb
- app/jobs/invoices/create_pay_in_advance_charge_job.rb
- app/services/billable_metrics/aggregations/base_service.rb
- app/services/events/common_factory.rb
- app/services/events/pay_in_advance_service.rb
- app/services/events/post_process_service.rb
- app/services/fees/create_pay_in_advance_service.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- spec/factories/cached_aggregations.rb
- spec/jobs/events/pay_in_advance_job_spec.rb
- spec/jobs/fees/create_pay_in_advance_job_spec.rb
- spec/services/events/pay_in_advance_service_spec.rb
- spec/services/events/post_process_service_spec.rb
- spec/services/fees/create_pay_in_advance_service_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
Today Clickhouse integration does not support pay in advance aggregation.
To do so, we need to refactor some logic that relies on the `events` table located in Postgres database to move to a DB agnostic approach. It will allow us to handle events coming from the API and from Kafka (via Sidekiq)
This PR refactors the `pay_in_advance` handling by extracting the logic into a new `Events::PayInAdvanceJob` that will also be called by the comming `pay_in_advance` ingest service
The service takes advantage of the new `Events::Common` model
> feat(clickhouse): Refact in advance logic to handle non-PG events

- app/services/events/pay_in_advance_service.rb
This PR is a fix for some error related to the last changes on the `Events::PayInAdvanceService`. It makes sure that the service is always returning a result to avoid `NoMethodError: undefined method `raise_if_error!' for nil` error in sidekiq
> fix(event): Return result in pay in advance service

- app/jobs/clock/refresh_draft_invoices_job.rb
- app/models/invoice.rb
- spec/jobs/clock/refresh_draft_invoices_jobs_spec.rb
Prevent refreshing draft invoices which don't have at least one active subscription
If invoice is in draft status but subscriptions related to it are terminated, we don't want to refresh such an invoice each 5 minutes
> fix (draft- invoices): refresh draft invoice only if there is active subscription

- config/initializers/active_job_uniqueness.rb
Few days ago I tried to deploy `api-clock` service but got stuck with the following error:
"[ActiveJob] Failed enqueuing Clock::ActivateSubscriptionsJob to Sidekiq(clock): Redis::CannotConnectError (Waited 0.1 seconds)"
The problem turned out to be that my Redis instance doesn't allow connecting without the proper URL Schema (which is `rediss://` in my case) and with the unnecessary `?` which is always added between the host and the port that is currently generated.
Currently with the following environment variables:
- `REDIS_URL=rediss://:example-token@redis-host.com:6379`
- `REDIS_PASSWORD=example-token`
The generated Redlock server host is: `redis://:example-token@redis-host.com?:6379` instead of `rediss://:example-token@redis-host.com:6379` (notice the URL schema and the extra …
> misc: improve active job uniqueness's redlock server host generation

- app/services/invoices/refresh_draft_service.rb
- spec/services/invoices/refresh_draft_service_spec.rb
When refreshing invoice, that is result of the upgrade operation, we didn't calculate correctly invoice reason. If there are multiple subscriptions, old logic could lead to fetching invalid reason and consequently to the DB index uniqueness error.
This PR handles described scenario and adds related tests.
> fix(draft-invoice): fix invoice reason logic for draft invoices

- app/graphql/types/invoice_subscription/object.rb
- app/models/invoice.rb
- app/serializers/v1/fee_serializer.rb
- app/services/subscriptions/dates_service.rb
- app/views/templates/invoices/v3/_subscription_details.slim
- app/views/templates/invoices/v4/_subscription_details.slim
For Pay in Advance charges, the date boundaries are sometimes incorrectly computed. This was patch recently to ensure the dates show in the invoice, in the frontend and in the API are correct but the database is still not-so-correct.
Ideally, we would want to fix the boundaries and store the dates in each fees but it's a significant effort and I cannot do it now. This PR extract the previous patch from `Invoice` model to `DatesService` so I can reuse it for [Non Invoiceable fees](https://github.com/getlago/lago-api/pull/2185).
See these two PRs for more context: https://github.com/getlago/lago-api/pull/1188 and https://github.com/getlago/lago-api/pull/1540
> feat(boundaries): Move charge_pay_in_advance_interval from Invoice to DatesService

- app/services/integration_customers/create_or_update_service.rb
- spec/services/integration_customers/create_or_update_service_spec.rb
Lago is currently adding more integrations; accounting and tax ones
Integration customer logic was originally written for one `integration_customer` object per `customer`. Recently the logic changed so that we support array in the input side.
However, we haven't changed memoization logic. The issue was that only the first object got cached and all subsequent params hashes got linked to the invalid `@integration` and `@integration_customer` instance variables.
This PR fixes described problem.
> fix(integration-customers): fix incorrectly cached variables

- config/initializers/sidekiq.rb
Lago uses Redis for storing sidekiq jobs and its operational data.
In order to avoid `RedisClient::ReadTimeoutError` we can increase `redis` timeout property. By default our redis version sets this property to `1s`.
> misc: extend redis timeout property

- app/services/integrations/aggregator/sync_service.rb
This PR adds `full_resync: true` to the sync service, the incremental sync is not working currently for Netsuite integration.
> fix(integrations): Trigger full resync

- app/controllers/api/v1/analytics/overdue_balances_controller.rb
- app/models/analytics/overdue_balance.rb
- app/serializers/v1/analytics/overdue_balance_serializer.rb
- app/services/analytics/overdue_balances_service.rb
- config/routes.rb
- spec/models/analytics/overdue_balance_spec.rb
- spec/requests/api/v1/analytics/overdue_balances_controller_spec.rb
- spec/serializers/v1/analytics/overdue_balance_serializer_spec.rb
- spec/services/analytics/overdue_balances_service_spec.rb
The goal of this PR is to add an analytics endpoint for fetching overdue balances per month and per currency.
> feat(dunning): Add overdue balance analytics endpoint

- app/services/fees/update_service.rb
- spec/services/fees/update_service_spec.rb
When [non-invoiceable fees were introduced](https://github.com/getlago/lago-api/pull/1069), we only allowed change of `payment_status` if the fee was attached to a non-invoiceable charge.
What we really meant is _"the fee is standalone, not attached to an invoice"_. Now we're working on attaching the non-invoiceable fees to an invoice at the end of the period. See https://github.com/getlago/lago-api/pull/2171
I'm changing the condition so the fee can be updated, only if it's not attached to any invoice yet.
> feat(fees): Only allow payment status to be changed if not attached to invoice yet

- app/graphql/resolvers/analytics/overdue_balances_resolver.rb
- app/graphql/types/analytics/overdue_balances/object.rb
- app/graphql/types/query_type.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/analytics/overdue_balances_resolver_spec.rb
- spec/graphql/types/analytics/overdue_balances/object_spec.rb
The goal of this PR is to add an analytics graphql endpoint for fetching overdue balances per month and per currency.
> feat(dunning): Add Resolvers::Analytics::OverdueBalancesResolver

- app/serializers/v1/fee_serializer.rb
- app/services/fees/charge_service.rb
- app/services/invoices/calculate_fees_service.rb
- app/services/invoices/subscription_service.rb
- spec/factories/fees.rb
- spec/scenarios/fees/recurring_fee_downgrade_spec.rb
- spec/scenarios/fees/recurring_fee_upgrade_spec.rb
- spec/scenarios/fees/recurring_fees_spec.rb
- spec/services/invoices/calculate_fees_service_spec.rb
- spec/support/scenarios_helper.rb
This pull request addresses the issue where recurring fees for non-invoiceable charges in advance are not re-generated at each billing period. 
- **Generate Fee at Subscription Renewal**: Ensure that a fee is generated at the time of subscription renewal when the recurring charge is set to pay-in-advance and is non-invoiceable. This guarantees that the billing system accurately reflects the charges for each period, even for non-invoiceable fees.
1. **Serializer Update**
- **File**: `app/serializers/v1/fee_serializer.rb`
- **Description**: Updated the serializer to handle the conditions where a charge is non-invoiceable and pay-in-advance. This includes parsing the timestamp and calculating the interval for fee generation.
2. **Charge Service Update**
- **File**: …
> feat(fees): Create Recurring non invoiceable fees on billing day

- app/jobs/clock/refresh_draft_invoices_job.rb
- app/jobs/clock/refresh_wallets_ongoing_balance_job.rb
- app/jobs/invoices/refresh_draft_job.rb
- app/jobs/wallets/refresh_ongoing_balance_job.rb
The goal of this PR is to ensure that only one refresh job can be processed at a time.
The lock is released automatically when the job finishes its execution
> misc: Add unique lock on refresh jobs

- app/jobs/clock/refresh_draft_invoices_job.rb
- app/jobs/clock/refresh_wallets_ongoing_balance_job.rb
- app/jobs/invoices/payments/stripe_create_job.rb
- app/jobs/invoices/refresh_draft_job.rb
- app/jobs/wallets/refresh_ongoing_balance_job.rb
We don't want to raise `ActiveJob::Uniqueness::JobNotUnique` when refreshing wallets and invoices.
The goal of this PR is to log them instead.
> misc: Do not raise ActiveJob::Uniqueness::JobNotUnique

- Gemfile
- Gemfile.lock
- config/initializers/sentry.rb
This PR: 
- Upgrades Sentry gems to 5.18.0
- Enhance the details sent to Sentry by adding the version and by using the `SENTRY_TRACES_SAMPLE_RATE` to configure the sample rate sent to Sentry
> misc: Upgrade Sentry gem and enable version tracking

- app/graphql/resolvers/invoices_resolver.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/invoices_resolver_spec.rb
👉  https://getlago.canny.io/feature-requests/p/ability-to-export-data-from-the-user-interface
In order to effortlessly download export of invoices by non-technical users, it is required to extend the invoices filtering capabilities.
This change includes new filters to the GraphQL invoices resolver to query invoices by:
* invoice_type
* currency
* issuing_date (from and to range)
* customer external_id
Also drops support for filtering by ids as this filter is not in use.
> feat(export invoices): Add GraphQL invoices filters

- app/graphql/types/integrations/anrok.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/integrations/anrok/create_spec.rb
- spec/graphql/types/integrations/anrok_spec.rb
Currently multiple tax and accounting integration are being added to the Lago app
This PR adds `externalAccountId` to the GQL response of the integration object.
This field is is needed for the UI to build the URL link for anrok customer. We can extract this data from api key but we don't want to expose whole api key object so new field in the response is added.
> feat (integration-customers): add external account id to the anrok GQL response

- spec/factories/add_ons.rb
- spec/factories/events.rb
Many have models have `code` attribute which is typically a few letter long.
Some factories relied on `Faker::Name.first_name` to generate code, unfortunately it's more likely to create collition than a random suite of letters. It actually happened today!
* Used `Faker::Alphanumeric.alphanumeric(number: 10)` to generate code attribute (all others already work this way)
* Changed `transaction_id` to a random string so it creates less confusion when debugging. I'd expect UUID to be linked to another model ID but here it's something "random" from the customer sending event.
> chore(factories): Don't use Faker names for random codes

- app/controllers/api/v1/customers_controller.rb
- app/graphql/types/customers/address.rb
- app/graphql/types/customers/address_input.rb
- app/graphql/types/customers/create_customer_input.rb
- app/graphql/types/customers/object.rb
- app/graphql/types/customers/update_customer_input.rb
- app/models/customer.rb
- app/serializers/v1/customer_serializer.rb
- app/services/customers/create_service.rb
- app/services/customers/update_service.rb
- db/migrate/20240626094521_add_shipping_address_to_customers.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/customers/create_spec.rb
- spec/graphql/types/customers/object_spec.rb
- spec/serializers/v1/customer_serializer_spec.rb
- spec/services/customers/create_service_spec.rb
- spec/services/customers/update_service_spec.rb
Currently Lago is adding integration with Tax provider - Anrok.
In some countries taxes can differ based on where the product is used and not based on customer's main location.
That's why shipping address is introduced and this PR adds support for it on the API side.
> feat(anrok-integration): add support for customer shipping address on the API side

- app/jobs/clock/activate_subscriptions_job.rb
- app/jobs/clock/create_interval_wallet_transactions_job.rb
- app/jobs/clock/events_validation_job.rb
- app/jobs/clock/finalize_invoices_job.rb
- app/jobs/clock/free_trial_subscriptions_biller_job.rb
- app/jobs/clock/mark_invoices_as_payment_overdue_job.rb
- app/jobs/clock/refresh_draft_invoices_job.rb
- app/jobs/clock/refresh_wallets_ongoing_balance_job.rb
- app/jobs/clock/subscriptions_biller_job.rb
- app/jobs/clock/subscriptions_to_be_terminated_job.rb
- app/jobs/clock/terminate_coupons_job.rb
- app/jobs/clock/terminate_ended_subscriptions_job.rb
- app/jobs/clock/terminate_wallets_job.rb
- app/jobs/clock/webhooks_cleanup_job.rb
- app/jobs/concerns/sentry_cron_concern.rb
- clock.rb
This PR is a new approach to try to finally add cron monitoring on Sidekiq.
The logic was first introduced in https://github.com/getlago/lago-api/pull/2109 and https://github.com/getlago/lago-api/pull/1780
The new approach uses `ActiveJob.set` to pass cron arguments to the job, in order to avoid the issues we faced lately with the initial approach
> misc(sidekiq): New approach for cron monitoring

- app/services/events/stores/base_store.rb
- app/services/events/stores/clickhouse/weighted_sum_query.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
This PR is a fix for https://github.com/getlago/lago/issues/345
It makes sure that `:` symbol is correctly escaped when present in a billable metric code.
This change was made possible by the recent update of rails to 7.1.3
See https://github.com/rails/rails/pull/48852/files for reference
> fix(bm): Handle colon in billable metric code

- app/jobs/invoices/prepaid_credit_job.rb
We've recently seen an issue where we receive the `succeeded` webhook from Stripe several times at the same moment (some milliseconds interval) on some wallet transactions.
The goal of this PR is to add a unique lock on the `Invoices::PrepaidCreditJob` job to not impact the balance twice.
> fix(wallet): Prevent from having duplicate Invoices::PrepaidCreditJob

- app/services/integrations/aggregator/invoices/payloads/netsuite.rb
- spec/services/integrations/aggregator/invoices/create_service_spec.rb
Netsuite only support decimals of to 14 digits if there is decimal point. This PR adapts this use-case
> fix(netsuite-integration): limit netsuite payload rate

- app/controllers/api/v1/plans_controller.rb
- app/graphql/types/charges/object.rb
- app/graphql/types/charges/regroup_paid_fees_enum.rb
- app/models/charge.rb
- app/serializers/v1/charge_serializer.rb
- app/services/invoices/advance_charges_service.rb
- app/services/plans/create_service.rb
- app/services/plans/update_service.rb
- config/locales/en.yml
- db/migrate/20220816120137_update_properties_on_percentage_charges.rb
- db/migrate/20231218170631_add_rate_to_percentage_amount_details.rb
- db/migrate/20240429141108_add_custom_aggregation_to_organizations.rb
- db/migrate/20240702081109_add_regroup_paid_fees_to_charges.rb
- db/schema.rb
- lib/tasks/charges.rake
- schema.graphql
- schema.json
- spec/factories/charges.rb
- spec/graphql/types/charges/object_spec.rb
- spec/models/charge_spec.rb
- spec/requests/api/v1/plans_controller_spec.rb
- spec/services/invoices/advance_charges_service_spec.rb
- spec/services/plans/create_service_spec.rb
When your charge is pay in advance but not invoiceable, the fees are created but not attached to any invoice.
This adds an options so at the end of the period, you get a new invoice showing all PAID fees. unpaid fees are ignored.
See also https://github.com/getlago/lago-api/pull/2171
We're dropping the idea of `invoice_strategy` because it turned out to be a bad idea. Instead we're adding `regroup_paid_fees` attribute that takes only one value today `invoice`.
> feat(charges): Add `regroup_paid_fees` to Charge

- app/jobs/invoices/payments/stripe_create_job.rb
- app/services/invoices/payments/stripe_service.rb
In this pull request, we change the error handling within the StripeCreateJob by discarding jobs that encounter Stripe::AuthenticationError. This change ensures that we prevent creating noise 
- When a `Stripe::AuthenticationError` is raised, it indicates an issue with the authentication credentials. Since this is a non-recoverable error in the job context, retries are unnecessary.
- Customers are already notified of such errors through a webhook, making additional retries redundant and potentially confusing for the customer.
- The `update_payment_method_id` method in the related service sends a webhook notification when any `Stripe::StripeError` is raised, ensuring customers are informed of issues promptly.
> feat: Add Discard Handling for AuthenticationError

- .rubocop.yml
- app/jobs/data_exports/export_resources_job.rb
- app/mailers/data_export_mailer.rb
- app/models/data_export.rb
- app/models/integration_resource.rb
- app/services/data_exports/create_service.rb
- app/services/data_exports/export_resources_service.rb
- db/clickhouse_migrate/20231024084411_create_events_raw.rb
- db/migrate/20230720204311_add_signature_to_webhook_endpoints.rb
- db/migrate/20240514081110_create_integration_resources.rb
- db/migrate/20240520115450_add_integration_id_to_integration_resources.rb
- db/migrate/20240522105942_add_resource_type_to_integration_resources.rb
- db/migrate/20240619082054_add_in_advance_charge_periodic_invoicing_reason.rb
- db/migrate/20240625090742_create_data_exports.rb
- db/migrate/20240628083654_add_membership_id_and_organization_id_to_data_exports.rb
- db/migrate/20240628083830_remove_user_id_from_data_exports.rb
- db/migrate/20240702081109_add_regroup_paid_fees_to_charges.rb
- spec/factories/data_exports.rb
- spec/factories/integration_resources.rb
- spec/jobs/data_exports/export_resources_job_spec.rb
- spec/mailers/data_export_mailer_spec.rb
- spec/mailers/previews/base_preview_mailer.rb
- spec/mailers/previews/data_export_mailer_preview.rb
- spec/models/data_export_spec.rb
- spec/models/integration_resource_spec.rb
- spec/services/data_exports/create_service_spec.rb
- spec/services/data_exports/export_resources_service_spec.rb
When reviewing PR I realized that many new files don't have the `# frozen_string_literal: true` comment.
I believe the rule was removed when we updated the code style recently.
> chore(perf): Add missing frozen_string_literal comment

- app/models/concerns/paper_trail_traceable.rb
- db/migrate/20240703061352_add_lago_version_to_versions.rb
- db/schema.rb
- spec/support/shared_examples/paper_trail_traceable.rb
Every time a change is made to a model, we store the changes in a `versions` table managed by the [papertrail gem](https://github.com/paper-trail-gem/paper_trail).
This PR adds the version of Lago to help debugging, especially self hosted versions.
Only possible because of [this PR](https://github.com/getlago/lago-api/pull/2204).
> feat(papertrail): Add Lago Version to papertrail metadata

- config/database.yml
- scripts/start.sh
This PR is a fix for https://github.com/getlago/lago-api/issues/1945#issuecomment-2206942237
Lago startup script is relying on the `rails db:migrate:primary` to perform the migration at startup.
Since in some situation, only one database is configured in the `database.yml` file, the command is failing with the following error:
```
Unrecognized command "db:migrate:primary" (Rails::Command::UnrecognizedCommandError)
Did you mean?  db:migrate:up
```
This PR fixes this by using `rails db:migrate` instead when only one database is present.
> fix: Startup script does not always perform migrations

- app/services/subscriptions/billing_service.rb
- app/services/subscriptions/create_service.rb
- app/services/subscriptions/terminate_service.rb
- spec/scenarios/invoices/advance_charges_spec.rb
- spec/services/subscriptions/billing_service_spec.rb
- spec/services/subscriptions/terminate_service_spec.rb
This PR aims to enable the code implemented in [PR #2171](https://github.com/getlago/lago-api/pull/2171) for the Regroup Fees feature. The previous implementation added the foundational code for this feature but left it commented out to await the completion of a subsequent PR that introduces the setting to toggle this feature.
The required setting functionality was added in [PR #2232](https://github.com/getlago/lago-api/pull/2232). With the merging of that PR, this feature can now be conditionally enabled based on the newly introduced setting.
> feat: Enable Regroup Fees Feature

- app/models/payment_provider_customers/stripe_customer.rb
- schema.graphql
- schema.json
- spec/models/payment_provider_customers/stripe_customer_spec.rb
This PR was previously opened at: https://github.com/getlago/lago-api/pull/2228
My customers prefer the Link payment method (https://link.com/) not to be confused with stripe payment links (https://docs.stripe.com/payments/link) when checking out with stripe. In order to reasonably migrate existing customers with Link payment methods, I'll need this as an option. This payment method is compatible with Payment Intents.
Slack conversation: https://lago-community.slack.com/archives/C03MCH55EL8/p1719509722047739
References https://github.com/getlago/lago-api/pull/1738
Adds the link payment method to the stripe customer
> feat: add link to payment methods

- config/initializers/console.rb
On support, I often found myself using `GlobalID::Locator.locate` because this is how the job arguments are displayed in Sidekiq UI.
I'm proposing this helper that loads only in the Rails console to easily retrieve things. What else would you like to see there?
I'm thinking for UUID we could try to resolve `Organization` and `Invoice` to see if one matches
> feat(dx): Add `find` helper in Rails console

- app/models/deprecation.rb
- spec/models/deprecation_spec.rb
`Deprecation` model helps track some usage in Redis.
Before removing some features, like sending Events without `external_subscription_id`, we want to ensure that no hosted customer still rely on them.
I'm adding a simple way to reset the reports.
```ruby
Deprecation.reset_all :feature_name
```
I'm also improving the CSV export.
> feat(deprecation): Add reset methods

- app/services/invoices/payments/stripe_service.rb
This PR addresses an issue where the `create` method in the `Invoices::Payments::StripeService` class could return `nil` in case of certain Stripe exceptions. This inconsistency in the return type could lead to unexpected behaviors in the calling code.
> fix: Ensure Consistent Return of `result` Object on Stripe Exceptions

- app/controllers/api/v1/fees_controller.rb
- app/models/fee.rb
- app/services/fees/destroy_service.rb
- config/routes.rb
- db/migrate/20240701184757_add_deleted_at_to_fees.rb
- db/schema.rb
- spec/requests/api/v1/fees_controller_spec.rb
**Context**
We already utilize the `discard` gem for soft deletion in other models within our application. However, the fees model currently lacks this functionality. Additionally, there is a need to ensure that fees associated with invoices are protected from deletion to maintain data integrity.
This PR extends the use of the `discard` gem to the fees model, enabling the soft deletion of fees. Furthermore, a validation is added to ensure that only fees not attached to any invoice can be deleted. If a deletion attempt is made on a fee associated with an invoice, the system will respond with a `405 Method Not Allowed` status and an error code `invoiced_fee`. This ensures that while fees can be logically removed from active use, those associated with invoices remain intact, …
> feat: Add ability to soft delete fees

- app/graphql/types/data_exports/invoices/filters_input.rb
- spec/graphql/types/data_exports/object_spec.rb
- spec/models/deprecation_spec.rb
This PR addresses an issue with the `.get_all_as_csv` test in the `Deprecation` model where the presence of quotes around `organization.name` caused the test to fail. The test has been updated to normalize both the expected and actual CSV strings by removing quotes before comparison, ensuring the comparison focuses on the data content rather than the format.
> fix: Normalize CSV Comparison in Tests to Ignore Quotes

- clock.rb
This is a very bad feature, we should think about disable it, and remove it very soon.
Scalability = 0
- Give the option to disable the events validation
> misc(events): Add option to remove event validations job

- app/services/commitments/dates_service.rb
- app/services/subscriptions/terminated_dates_service.rb
Minimum commitment calculation was using incorrect dates service in when refreshing draft invoices for terminated subscriptions.
Fix terminated dates service to be able to skip calling `matching_invoice_subscription?` when creating the dates service.
> fix(dates-service): Fix terminated dates service for min commitment calculations

- app/services/integration_customers/create_or_update_service.rb
- spec/services/integration_customers/create_or_update_service_spec.rb
We were getting a lot of dead jobs when trying to sync a deleted customer to nango (netsuite).
This PR fixes the issue by not trying to sync a non-existent (deleted) customer.
> fix(integrations): Fix creating a deleted customer

- app/graphql/types/credit_notes/object.rb
- app/graphql/types/invoices/object.rb
- app/models/credit_note.rb
- app/models/integration_customers/base_customer.rb
- app/models/invoice.rb
- app/models/payment.rb
- app/services/integrations/aggregator/invoices/base_service.rb
- db/schema.rb
Improve integration customer queries
Currently Accounting integrations, Netsuite and Xero, are supported in Lago but tax integration Anrok is currently being implemented.
This PR improves existing integration customers queries. Customer can have attached ONLY one accounting integration and ONLY one tax integration, but we want to avoid case that tax integration customer is returned in accounting context.
> fix (integration-customers): adapt integration customer queries

- app/controllers/api/v1/events_controller.rb
- spec/requests/api/v1/events_controller_spec.rb
All events sent to Lago must include `external_subscription_id`.
Track event sent to `/api/v1/events/estimate_fees` without the `external_subscription_id`
See https://github.com/getlago/lago-api/pull/2056
> feat(events): Track event sent without external_subscription_id for /estimate_fees

- db/migrate/20240701184757_add_deleted_at_to_fees.rb
Uses disable_ddl_transaction! to execute the migration outside of a transaction, allowing for concurrent index creation.
> fix: disable transaction on migration

- db/migrate/20240611074215_add_payment_overdue_to_invoices.rb
- db/migrate/20240619082054_add_in_advance_charge_periodic_invoicing_reason.rb
Uses disable_ddl_transaction! to execute the migration outside of a transaction, allowing for concurrent index creation.
> fix: add disable_ddl_transaction

- app/mailers/data_export_mailer.rb
- app/services/data_exports/csv/invoice_fees.rb
- app/services/data_exports/export_resources_service.rb
- app/views/data_export_mailer/completed.slim
- config/locales/en/email.yml
- spec/mailers/data_export_mailer_spec.rb
- spec/services/data_exports/csv/invoice_fees_spec.rb
- spec/services/data_exports/export_resources_service_spec.rb
👉  https://getlago.canny.io/feature-requests/p/ability-to-export-data-from-the-user-interface
In order to effortlessly download export of invoice fees by non-technical users, it is required to add a new CSV exporter and extend the export resource service and mailer.
This change adds a new CSV exporter for invoice fees;
also extends the `ExportResourcesService` to handle unknown resource types and invoice_fees.
and improve the mailer and its specs to support different kind of exported resources like invoice_fees.
> feat(export-invoice-fees): Export invoice fees to CSV

- app/graphql/types/data_exports/format_type_enum.rb
- app/graphql/types/data_exports/status_enum.rb
- schema.graphql
- schema.json
- spec/graphql/types/data_exports/object_spec.rb
👉 https://getlago.canny.io/feature-requests/p/ability-to-export-data-from-the-user-interface
namespace graphQL data export types
> fix(export-invoices): Namespace DataExports graphQL enum types

- app/graphql/resolvers/customer_portal/analytics/invoice_collections_resolver.rb
- app/graphql/resolvers/customer_portal/analytics/overdue_balances_resolver.rb
- app/graphql/types/analytics/gross_revenues/object.rb
- app/graphql/types/analytics/overdue_balances/object.rb
- app/graphql/types/query_type.rb
- app/models/analytics/gross_revenue.rb
- app/models/analytics/invoice_collection.rb
- app/models/analytics/overdue_balance.rb
- app/serializers/v1/analytics/gross_revenue_serializer.rb
- app/serializers/v1/analytics/overdue_balance_serializer.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/analytics/gross_revenues_resolver_spec.rb
- spec/graphql/resolvers/customer_portal/analytics/invoice_collections_resolver_spec.rb
- spec/graphql/resolvers/customer_portal/analytics/overdue_balances_resolver_spec.rb
- spec/models/analytics/invoice_collection_spec.rb
- spec/serializers/v1/analytics/gross_revenue_serializer_spec.rb
- spec/serializers/v1/analytics/overdue_balance_serializer_spec.rb
The goal of this PR is to add an analytics graphql endpoint for fetching overdue balances per month and per currency at the customer portal level.
> feat(dunning): Add customer portal analytics resources

- .github/workflows/migrations-test.yml
- .github/workflows/spec.yml
- config/database.yml
- lib/tasks/lago.rake
- scripts/start.sh
This PR introduce a new  `LAGO_CLICKHOUSE_MIGRATIONS_ENABLED` environment variable to enable or disable the Clickhouse migration. This variable completes the existing `LAGO_CLICKHOUSE_ENABLED` that enable the Clickhouse event stores in API
It should fix some issue we had recently in deploy on US/EU clusters with migration performed at startup
> misc: Add LAGO_CLICKHOUSE_MIGRATIONS_ENABLED env

- app/services/invoices/payments/stripe_service.rb
- spec/services/invoices/payments/stripe_service_spec.rb
Payment description not provided when after complting the payment via payment URL.
Stripe payment does not include the standard description (shows payment intent ID instead).
This PR fixes the issue by adding description to the payload.
> fix(stripe): Add invoice description to payment url payload

- spec/scenarios/commitments/minimum/in_advance_spec.rb
This PR addresses a flaky test related to the sorting of commitment fees amounts.
> fix: Fix flaky test for commitment fees amount sort

- app/models/analytics/gross_revenue.rb
- app/models/analytics/invoice_collection.rb
- app/models/analytics/overdue_balance.rb
On the customer page, we don't want to include analytics of deleted customers having the same `external_id`.
> fix(analytics): Prevent fetching deleted customer analytics

- Gemfile.lock
- app/models/clickhouse/events_count_agg.rb
- app/models/clickhouse/events_enriched.rb
- app/models/clickhouse/events_max_agg.rb
- app/models/clickhouse/events_sum_agg.rb
- db/clickhouse_migrate/20240705080709_create_events_enriched.rb
- db/clickhouse_migrate/20240705084952_create_events_enriched_queue.rb
- db/clickhouse_migrate/20240705085501_create_events_enriched_mv.rb
- db/clickhouse_migrate/20240705090006_create_events_sum_agg.rb
- db/clickhouse_migrate/20240705090310_create_events_sum_agg_mv.rb
- db/clickhouse_migrate/20240709095907_create_events_count_agg.rb
- db/clickhouse_migrate/20240709100047_create_events_count_agg_mv.rb
- db/clickhouse_migrate/20240709135506_create_events_max_agg.rb
- db/clickhouse_migrate/20240709135535_create_events_max_agg_mv.rb
- db/clickhouse_schema.rb
This PR is part of the real-time aggregation epic
This PR adds new tables, queues and materlialized views in Clickhouse to allow pre-aggregation of events, based on all the work done on the ingest and post-process services
> feat(event): Add clickhouse pre-aggregation config

- app/models/fee/applied_tax.rb
- app/models/invoice/applied_tax.rb
- app/services/fees/apply_provider_taxes_service.rb
- app/services/invoices/apply_provider_taxes_service.rb
- db/migrate/20240708195226_remove_null_constraint_on_applied_taxes.rb
- db/schema.rb
- spec/services/fees/apply_provider_taxes_service_spec.rb
- spec/services/invoices/apply_provider_taxes_service_spec.rb
Currently Anrok - tax tool integration is being added
This PR created applied taxes objects in Lago based on fetched Anrok taxes.
Two new services are added: `Fees::ApplyProviderTaxesService` and `Invoices::ApplyProviderTaxesService`.
This logic follows existing behaviour in `Fees::ApplyTaxesService` and `Invoices::ApplyTaxesService` services. The only difference is that source of taxes is not Lago app anymore but external provider.
New services are not used yet.
> feat(applied-taxes): add logic for creating applied taxes based on external provider

- app/graphql/types/charges/input.rb
- schema.graphql
- schema.json
- spec/graphql/types/charges/input_spec.rb
`regroup_paid_fees` was missing from ChargeInput. You can read the data but not edit it. This makes it editable.
> feat(gql): Add regroup_paid_fees to ChargeInput

- config/initializers/active_job_uniqueness.rb
- We often have an error message about redis timeout (0.1 seconds)
- After investigation, its coming from the uniqueness job configuration
- Update the `redis_timeout` value to the same as redis, `5 second` . It's a lot but it will cover cases where redis can be slower (self hosted).
https://github.com/getlago/lago/issues/188#issuecomment-2229508006
> fix(redis): Timeout error on unique jobs

- app/jobs/clock/mark_invoices_as_payment_overdue_job.rb
- app/models/invoice.rb
- app/services/credit_notes/create_service.rb
- app/services/credit_notes/validate_service.rb
- app/services/invoices/payments/adyen_service.rb
- app/services/invoices/payments/generate_payment_url_service.rb
- app/services/invoices/payments/gocardless_service.rb
- app/services/invoices/payments/retry_service.rb
- app/services/invoices/payments/stripe_service.rb
- app/services/invoices/update_service.rb
- app/services/payment_provider_customers/stripe_service.rb
- spec/jobs/clock/mark_invoices_as_payment_overdue_job_spec.rb
- spec/jobs/invoices/update_fees_payment_status_job_spec.rb
- spec/models/invoice_spec.rb
- spec/services/credit_notes/validate_service_spec.rb
- spec/services/invoices/calculate_fees_service_spec.rb
- spec/services/invoices/create_one_off_service_spec.rb
- spec/services/invoices/payments/adyen_service_spec.rb
- spec/services/invoices/payments/generate_payment_url_service_spec.rb
- spec/services/invoices/payments/gocardless_service_spec.rb
- spec/services/invoices/payments/stripe_service_spec.rb
As part of implementation error status for invoices, we got conflict between current `failed?` method on invoice that comes from payment_status and new `failed?` method that comes from invoice status itself, so it makes sense to make payment statuses explicitly payment's  statuses, introducing this prefix to payment_status enum, so it will be
`paymen_failed` instead (and other methods from the enum)
Also it will make it clearer that `invoice.pending?` does not mean that the invoice is pending because of something, instead we'll have now `invoice.payment_pending?` which is again more explicit
> Feat(invoice.payment_status): add prefix to invoice payment status enum

- db/migrate/20240718080929_update_billable_metrics_grouped_charges_to_version_3.rb
- db/schema.rb
- db/views/billable_metrics_grouped_charges_v03.sql
This PR update the `billable_metrics_grouped_charges` view introduced in https://github.com/getlago/lago-api/pull/2231 to allow a better filtering of events related to in advance charges.
Today all event having the code of a billable metric related to an in advance charge is sent to the event_worker even if no subscription is attached to it leading to a lot of load on the worker for jobs that will in the end not be charged
This PR will allow us to the update the ingest service so that only event related to an in advance charge on a active subscription are sent to the event worker
> feat(event): Add pay_in_advance flag in grouped charges view

- app/graphql/resolvers/analytics/gross_revenues_resolver.rb
- app/graphql/resolvers/analytics/overdue_balances_resolver.rb
- app/graphql/resolvers/customer_portal/analytics/invoice_collections_resolver.rb
- app/graphql/resolvers/customer_portal/analytics/overdue_balances_resolver.rb
- app/models/analytics/base.rb
- app/models/analytics/gross_revenue.rb
- app/models/analytics/invoice_collection.rb
- app/models/analytics/overdue_balance.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/analytics/gross_revenues_resolver_spec.rb
- spec/graphql/resolvers/analytics/overdue_balances_resolver_spec.rb
We want to be able to refresh analytics on the customer section:
And the customer portal:
> feat(analytics): Ability to expire cache when fetching customer analytics

- app/services/events/stores/clickhouse/pre_aggregated/base.rb
- app/services/events/stores/clickhouse/pre_aggregated/count_query.rb
- app/services/events/stores/clickhouse/pre_aggregated/latest_query.rb
- app/services/events/stores/clickhouse/pre_aggregated/max_query.rb
- app/services/events/stores/clickhouse/pre_aggregated/sum_query.rb
- app/services/invoices/customer_usage_service.rb
- spec/factories/clickhouse/events_count_aggs.rb
- spec/factories/clickhouse/events_enriched.rb
- spec/factories/clickhouse/events_max_aggs.rb
- spec/factories/clickhouse/events_sum_aggs.rb
- spec/services/events/stores/clickhouse/pre_aggregated/count_query_spec.rb
- spec/services/events/stores/clickhouse/pre_aggregated/latest_query_spec.rb
- spec/services/events/stores/clickhouse/pre_aggregated/max_query_spec.rb
- spec/services/events/stores/clickhouse/pre_aggregated/sum_query_spec.rb
- spec/spec_helper.rb
This PR is part of the real-time aggregation epic
This PRs uses previously added Clickhouse tables and materialized views for pre-aggregation of Max, Sum and Count billable metrics, to compute the number of units for a billing period.
It takes into account the `::Clickhouse::Events*Agg` as well as the `::Clickhouse::EventsEnriched` at the beginning and the end of the period
> feat(event): Compute aggregation using Clickhouse pre-aggregation

- app/models/invoice.rb
- schema.graphql
- schema.json
https://www.notion.so/getlago/Dive-in-Calculate-taxes-info-for-finalized-invoices-subscription-58481b4c8a5c40b18cf86b8a800cf49d?pvs=4#255f83ec5c6a47b283ee5afda6d13df1
As part of processing errors from tax_provider, we want to be able to indicate that invoice failed to be generated
Added new status for invoices: `failed`
Added prefix to payment_statuses enum methods: `payment`
> feat(anrok): Add failed status to invoice

- app/services/fees/apply_provider_taxes_service.rb
- app/services/integrations/aggregator/taxes/invoices/base_service.rb
- app/services/integrations/aggregator/taxes/invoices/payload.rb
- app/services/invoices/apply_provider_taxes_service.rb
- app/services/invoices/compute_amounts_from_fees.rb
- spec/fixtures/integration_aggregator/taxes/invoices/success_response.json
- spec/graphql/mutations/integrations/anrok/fetch_draft_invoice_taxes_spec.rb
- spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb
- spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb
- spec/services/invoices/compute_amounts_from_fees_spec.rb
Lago is currently implementing integration with Anrok, the tax provider.
As part of the tax provider integration, Lago is building new action for retrying invoice that failed due to unsuccessful tax fetch.
Pre-requirement for this action is having some updates in core logic that works with provider taxes. Few small changes are added in this PR:
1. In the API response it changed a bit how tax exempts are returned -> small fix added - NOT USED YET
2. `Invoices::ApplyProviderTaxesService` is extended so that it can also take provider taxes as parameter, not only fetch it internally - NOT USED YET
3. `Invoices::ComputeAmountsFromFees` is extended so that it can call `Fees::ApplyProviderTaxesService` and `Invoices::ApplyProviderTaxesService` if customer has configured Anrok -> THIS SERVICE IS …
> feat(tax-integrations): update provider tax core logic

- app/models/fee.rb
as second part of improvements introduced in this PR:
https://github.com/getlago/lago-api/pull/2299
we want to be more explicit when payment_status on a model actually relates to the payment, so following invoices we want to add `payment_` prefix to payment statuses on fees
> misc: add prefix to payment status enum on fee

- app/graphql/resolvers/invoices_resolver.rb
- app/graphql/types/data_exports/invoices/filters_input.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/data_exports/invoices/create_spec.rb
- spec/graphql/resolvers/invoices_resolver_spec.rb
- spec/graphql/types/data_exports/invoices/filters_input_spec.rb
- spec/queries/invoices_query_spec.rb
👉 https://getlago.canny.io/feature-requests/p/ability-to-export-data-from-the-user-interface
Accept a list of values for invoices type and status filters on invoices resolver and create data export mutation.
also;
assigns a meaningful name to data exports invoices filter input type
> fix(export invoices): multi value invoices filters and improve graphql type name

- app/controllers/api/v1/applied_coupons_controller.rb
- app/controllers/api/v1/customers/usage_controller.rb
- app/controllers/api/v1/fees_controller.rb
- app/controllers/api/v1/invoices_controller.rb
- app/controllers/api/v1/subscriptions_controller.rb
- app/graphql/resolvers/customer_portal/invoices_resolver.rb
- app/graphql/resolvers/customers/invoices_resolver.rb
- app/graphql/resolvers/integration_collection_mappings_resolver.rb
- app/graphql/resolvers/integration_mappings_resolver.rb
- app/graphql/resolvers/invoices_resolver.rb
- app/graphql/resolvers/subscriptions_resolver.rb
- app/queries/base_query.rb
- app/queries/invoices_query.rb
- app/queries/past_usage_query.rb
- app/services/data_exports/csv/invoices.rb
- spec/queries/applied_coupons_query_spec.rb
- spec/queries/fees_query_spec.rb
- spec/queries/integration_collection_mappings_query_spec.rb
- spec/queries/integration_mappings_query_spec.rb
- spec/queries/invoices_query_spec.rb
- spec/queries/past_usage_query_spec.rb
- spec/queries/subscriptions_query_spec.rb
- spec/services/data_exports/csv/invoice_fees_spec.rb
- spec/services/data_exports/csv/invoices_spec.rb
👉 https://getlago.canny.io/feature-requests/p/ability-to-export-data-from-the-user-interface
When exporting data (eg: invoices) we use query objects to fetch the records to export. However, the current implementation of query objects paginates to first page and limit results to 25 or 100 (depends on implementation) when no pagination information is provided.
We need the query object to allow no pagination and fetch all resources matching the search / filter criteria when no pagination is provided.
This change allows client code to call Query object with no pagination information to avoid pagination defaults (page: 1, limit: 25).
Also, it makes `BaseQuery::Pagination` internal knowledge of the query objects. As query objects expect pagination as a hash `{page: 1, limit: 50}`. The same will …
> fix(export-invoices): allow no pagination for Query objects

- app/models/invoice.rb
- app/services/invoices/retry_service.rb
- spec/factories/invoices.rb
- spec/fixtures/integration_aggregator/taxes/invoices/success_response_multiple_fees.json
- spec/services/invoices/retry_service_spec.rb
Currently Lago is adding Anrok tax integration
This PR adds new service for retrying failed invoice due to the tax integration errors.
Main goals of the service are:
1. Keep existing fees
2. Fetch tax based on the existing fees
3. Apply taxes on fees and invoice
4. Calculate totals
5. Generate invoice number and finalize invoice
6. Call all async actions: accounting integration syncs, trigger webhooks, payment...
> feat (tax-integrations): Add invoice retry service

- Gemfile.lock
This is meant to fix the exception 
`super: no superclass method `broadcast' for class ActiveSupport::Logger` when running lago worker.
More details on the sidekiq issue can be found here https://github.com/sidekiq/sidekiq/issues/6063
> deps: bump sidekiq from 7.1.4 to 7.1.5

- app/controllers/api/v1/credit_notes_controller.rb
- app/controllers/api/v1/invoices_controller.rb
- app/graphql/mutations/credit_notes/create.rb
- app/graphql/mutations/customer_portal/download_invoice.rb
- app/graphql/mutations/invoices/download.rb
- app/graphql/mutations/invoices/lose_dispute.rb
- app/graphql/mutations/invoices/refresh.rb
- app/graphql/mutations/invoices/retry.rb
- app/graphql/mutations/invoices/retry_payment.rb
- app/graphql/mutations/invoices/update.rb
- app/graphql/mutations/invoices/void.rb
- app/graphql/resolvers/credit_notes/estimate_resolver.rb
- app/graphql/resolvers/invoice_resolver.rb
- app/graphql/types/customers/object.rb
- app/graphql/types/invoices/status_type_enum.rb
- app/models/invoice.rb
- app/queries/invoices_query.rb
- spec/models/invoice_spec.rb
We're splitting invoices statuses into 2 categories:
* **Visible:** show up in the UI (via graphQL) and available via the rest API
* **Invisible:** cannot be retrieved via API or UI, never trigger webhook. They are purely technical, waiting to move to a visible status
> feat(invoice): Introduce visible/invisible invoice status

- config/initializers/console.rb
Sometimes you created an invoice by mistake or there was a bug and it should be recreated. It's a rare operation that doesn't happen in the normal flow. The deletion must be done via the Rails console.
This helper allows you to delete it with a helper instead of trying to figure it out every time.
The helper will load the invoice, print the ID and the organization name, then wait for confirmation before deleting it.
```
irb(main):001:0> id = Invoice.first.id
=> "0df671da-c89b-4259-a822-1446bff8e570"
irb(main):002:0> hard_delete_invoice id
Going to hard delete invoice from org `Hooli` (id: 0df671da-c89b-4259-a822-1446bff8e570)
Press any key to confirm deletion or CTRL+C to cancel.
Deletion cancelled.
=>
#<Invoice:0x0000ffff99c74248
...
```
```
hard_delete_invoice id
Invoice Load (2.3ms) …
```
> feat(console): Hard delete invoice in console

- app/services/charges/apply_taxes_service.rb
- app/services/plans/apply_taxes_service.rb
- app/services/plans/update_service.rb
- spec/services/charges/apply_taxes_service_spec.rb
- spec/services/plans/apply_taxes_service_spec.rb
- spec/services/plans/update_service_spec.rb
Currently, we're setting `ready_to_be_refreshed` on invoices when applying taxes to the plan or a charge.
As it's only used when updating a plan, we want to change this behavior and only set `ready_to_be_refreshed: true` once at this moment.
> fix: Set ready_to_be_refreshed only when updating a plan

- app/controllers/api/v1/invoices_controller.rb
- app/graphql/mutations/invoices/finalize.rb
- app/jobs/invoices/finalize_job.rb
- app/services/customers/terminate_relations_service.rb
- app/services/customers/update_invoice_grace_period_service.rb
- app/services/invoices/finalize_service.rb
- app/services/invoices/refresh_draft_and_finalize_service.rb
- app/services/organizations/update_invoice_grace_period_service.rb
- app/services/plans/destroy_service.rb
- spec/jobs/clock/finalize_invoices_job_spec.rb
- spec/jobs/invoices/finalize_job_spec.rb
- spec/services/customers/update_invoice_grace_period_service_spec.rb
- spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
- spec/services/organizations/update_invoice_grace_period_service_spec.rb
- spec/services/organizations/update_service_spec.rb
- spec/services/subscriptions/dates/monthly_service_spec.rb
As we're considering adding more Invoice state, we should specify what the current `FinalizeService` does. It not only finalize it, it takes a draft invoice, refresh it and finalize it.
We're also changing a little bit how invoice is set in result and reloaded, hoping to make it a little bit clearer.
> chore(services): Rename FinalizeService to RefreshDraftAndFinalizeService

- app/models/invoice.rb
- spec/models/invoice_spec.rb
The open status is a technical status just like `generating`. It's used in different upcoming feature.
`open` invoices means:
* invoice cannot be edited (unlike `draft`)
* invoice is not visible (not via API nor GQL)
* invoice is payable
> feat(invoices): Add open status

- app/queries/base_query.rb
- app/queries/invoices_query.rb
- app/services/data_exports/csv/invoices.rb
- spec/queries/invoices_query_spec.rb
- spec/services/data_exports/csv/invoice_fees_spec.rb
- spec/services/data_exports/csv/invoices_spec.rb
👉 https://getlago.canny.io/feature-requests/p/ability-to-export-data-from-the-user-interface
This change include a number of fixes related to query objects in general, the InvoicesQuery objects filters and how the invoices CSV export service uses the InvoicesQuery;
* Fixes query objects date parsing capabilities as original implementation was able to parse datetimes and failed with dates.
* Fix InvoicesQuery filters to ensure it works when keys are strings or symbols using the Filters object.
* Fix DataExports::CSV::Invoices service to use properly the current InvoicesQuery interface as it was missing some filters that are currently outside of the filters hash (will be fixed in https://github.com/getlago/lago-api/pull/2313)
> Fix export invoices query object filters

- app/graphql/types/error_details/object.rb
- schema.graphql
- schema.json
- spec/services/error_details/create_service_spec.rb
When adding error_details to the invoices [PR](https://github.com/getlago/lago-api/pull/2329), we added details of the errors as a jsonb object, while for now we'll be only storing there the error_code / error clarification and FE doesn't need the whole object for this
Updated error_detail type to send only first value of it's detils
> misc: change format of error_details description we send to FE

- app/services/invoices/payments/gocardless_service.rb
- spec/services/invoices/payments/gocardless_service_spec.rb
GoCardless payment creation does not raise error when no mandate available
Instead of raising an error when a mandate is not available at GoCardless to create a new payment,
We notify the client with a meaningful error message, flag the invoice as payment failed and return a failure result.
Given a customer does not have a GoCardless mandate available to process an invoice payment, `Invoices::Payments::GocardlessCreateJob` was raising an exception, moving the job to sidekiq dead jobs queue and notifying the client with not helpful information `"One of your parameters was incorrectly typed"`.
```
job_name: "Invoices::Payments::GocardlessCreateJob"
error_class: "GoCardlessPro::InvalidApiUsageError"
error_message: "One of your parameters was incorrectly typed"
```
This change fixes this …
> fix: GoCardless payment creation exception when no mandate available

- app/jobs/invoices/prepaid_credit_job.rb
- app/services/wallets/apply_paid_credits_service.rb
- spec/services/wallets/apply_paid_credits_service_spec.rb
As we're working on some wallet improvements, I was looking at this service. I'd like to make some modification:
* `*Service.call` methods should return a result as much as possible to avoid calling `raise_if_error!` on nil
* The Service is under `Wallets` namespace and only need a wallet transaction so I change the params. The invoice was not needed. I think this makes the test more straight forward too.
> refactor(wallet): change ApplyPaidCreditsService argument

- app/queries/invoices_query.rb
- spec/queries/invoices_query_spec.rb
Whenever `payment_dispute_lost` filter had a value other than `nil` it was returing only inovoices with `payment_dispute_lost`,
hence, when the filter had a `false` value, it still returns only invoices with a payment dispute lost.
This change fixes the filter by providing the proper scoping base on the value of the filter.
> fix: invoices query payment_dispute_lost filter

- app/queries/invoices_query.rb
- spec/queries/invoices_query_spec.rb
Given `payment_overdue` filter is false, `InvoicesQuery` ignores the filter and return all invoices without consider their `payment_overdue` value, while it should only return `payment_overdue` == false invoices.
This change fixes the filter by providing the proper scoping base on the value of the filter.
> fix: invoices query payment_overdue filter

- app/serializers/collection_serializer.rb
Before, all item attributes are serialized with symbol keys but nested collections with strings. This incosistency caused bugs when using the serializer to export resources in CSV format.
Ensure the provided key is symbolized.
> fix: Serialize nested collections with a symbol key

- db/migrate/20240729154334_add_index_on_events_external_subscription_id_with_included.rb
- db/schema.rb
- We have pretty bad performances on the `events` table when we want to retreive events for aggregations and before computing it.
- Add the missing optimized index on `external_subscription_id`, `code`  and `timestamp` and including `organization_id` and `properties`
> misc(events): Add new optimized index

- .github/workflows/migrations-test.yml
Make sure schema.rb is up to date with latest migrations.
> misc(migrations) - Add extra check to make sure schema.rb is up to date.

- app/graphql/types/invoices/object.rb
- app/serializers/v1/invoice_serializer.rb
- app/services/invoices/retry_service.rb
- spec/factories/invoices.rb
- spec/services/invoices/retry_service_spec.rb
When retrying an invoice we want to mark all previous errors as discarded, so if the invoice succeeded these errors will not be shown
- Update deleted_at for existing tax_error error_details  when retrying fetch taxes for the invoice
- Create new errors when retrying invoice fetching taxes failed
- Serialize only error_details that are not discarded
> Feat(anrok): add handling discarded errors when retrying invoice

- app/services/integrations/aggregator/contacts/payloads/netsuite.rb
- spec/services/integrations/aggregator/contacts/create_service_spec.rb
- spec/services/integrations/aggregator/contacts/payloads/netsuite_spec.rb
- spec/services/integrations/aggregator/contacts/update_service_spec.rb
By creating or updating a customer from Lago to NetSuite, a client needs us to send a custom field with the hyperlink of our Lago customer.
Add `custentity_lago_customer_link` to payload body when saving a netsuite customer.
> feat(netsuite): Add lago customer link to netsuite

- app/services/integrations/aggregator/invoices/payloads/netsuite.rb
- spec/services/integrations/aggregator/invoices/create_service_spec.rb
- spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
- spec/services/integrations/aggregator/sales_orders/create_service_spec.rb
By syncing an invoice from Lago to NetSuite, a client needs us to send a custom field with the hyperlink of our Lago invoice.
Add `custbody_lago_invoice_link` to netsuite invoice payload body.
> feat(netsuite): Add lago invoice link to netsuite

- config/database.yml
Currently the database configuration for production looks like so:
```
production:
primary:
<<: *default
url: <%= ENV['DATABASE_URL'] %>
pool: <%= ENV.fetch('DATABASE_POOL', 10) %>
prepared_statements: <%= ENV.fetch('DATABASE_PREPARED_STATEMENTS', true) %>
schema_search_path: <%= ENV.fetch('POSTGRES_SCHEMA', 'public') %>
events:
<<: *default
url: <%= ENV['DATABASE_URL'] %>
pool: <%= ENV.fetch('DATABASE_POOL', 10) %>
prepared_statements: <%= ENV.fetch('DATABASE_PREPARED_STATEMENTS', true) %>
database_tasks: false
```
As you can see, schema_search_path is configured for `primary` but missing for `events`. This means that migrations and all the main logic will run on POSTGRES_SCHEMA if configured, but events will still look for the tables in the `public` schema, which will not exist, causing …
> Fix: Event ingestions when using a non default schema

- app/services/data_exports/csv/invoices.rb
- spec/services/data_exports/csv/invoices_spec.rb
👉  https://getlago.canny.io/feature-requests/p/ability-to-export-data-from-the-user-interface
Customers need some extra data in the invoices export we did not anticipate.
- Add the `fees_amount_cents` column in the CSV export
- Fix the invoice header typo (invoice instead of `invoince`)
- Add a `customer_name` column, after the `customer_external_id` name
- Invoices list must be sorted by `issuing_date DESC` (newest invoice at the top)
- Adapt the order of columns (in the exact order). This list of columns must start after the file_url one:
1. `fees_amount_cents`
2. `coupons_amount_cents`
3. `taxes_amount_cents`
4. `credit_notes_amount_cents`
5. `prepaid_credit_amount_cents`
6. `total_amount_cents`
In order to achieve the CSV row order by `issuing_date DESC` we can not use rails …
> fix(export invoices): Re arrange CSV column order, add new columns and fix row order by issuing date

- app/services/integrations/aggregator/invoices/payloads/netsuite.rb
- spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
Customers do not want Lago to sync 0 amount line item to NetSuite.
Do not sync line items in NetSuite if Lago's `fees.amount_cents` is equal to `0`.
> feat(netsuite): Do not send line items with 0 amount cents

- db/migrate/20240801142242_alter_events_vacuum_settings.rb
- db/schema.rb
Default postgres autovacuum settings are a bit too defensive for our use-cases. We require frequent vacuuming of the events table, mostly to keep the visibility map of the events table up to date.
> misc(events) - Setup more aggressive autovacuum_vacuum_scale_factor setting for events

- Gemfile.lock
Forgotten `Gemfile.lock` update after ruby 3.3.4 upgrade
> misc - Missing gemfile.lock update after ruby upgrade

- config/initializers/active_job_uniqueness.rb
We only passed in the `redlock_options` when we provided the `REDIS_PASSWORD` env var. We should set it in all cases.
> fix(redis) - set redlock_options even if REDIS_PASSWORD is not provided

- app/jobs/send_webhook_job.rb
- app/serializers/v1/integrations/taxes/fee_error_serializer.rb
- app/services/webhooks/integrations/taxes/fee_error_service.rb
- spec/serializers/v1/integrations/taxes/fee_error_serializer_spec.rb
- spec/services/webhooks/integrations/taxes/fee_error_service_spec.rb
Currently Lago is adding Anrok tax integration.
If there is error while fetching taxes for fees pay in advance, we want to have dedicated webhook.
This PR creates new webhook type for described case and adds related tests.
> feat (tax-integration): add new webhook type for fee tax failure

- app/jobs/invoices/finalize_job.rb
When finalizing an invoice, we need to assign an invoice number, following a sequence. This requires a lock on the database which can fail. Other similar jobs already retry on this error.
Maybe we should even retry any jobs with this error. 🤔
> feat(billing): Retry finalize jobs on Sequence error

- app/services/integrations/aggregator/base_payload.rb
- app/services/integrations/aggregator/invoices/payloads/netsuite.rb
- spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
In our NetSuite integration, if the tax_item mapping is not set, do not block the invoice from being synced to NetSuite. In that case, simply remove the taxitem and the taxamountoverride from the POST invoice request.
Remove`taxitem` and `taxamountoverride` columns from invoice payload if tax item is not mapped.
> fix(netsuite): Do not send taxes columns if tax not mapped

- config/initializers/lograge.rb
Make sure we can correlate logs with traces by including the OpenTelemetry trace_id and span_id in the logs.
> misc(tracing) - add trace_id and span_id to lograge custom_options

- app/services/invoices/customer_usage_service.rb
Given that spans and traces are thread-local, we need to capture the context and set it explicitly in the blocks executing in other threads. 
Inspired by https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/concurrent_ruby/lib/opentelemetry/instrumentation/concurrent_ruby/patches/thread_pool_executor.rb#L15
> misc(tracing) - Capture and pass context inside Parallel execution blocks 

- config/locales/de.yml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
- config/locales/it.yml
- config/locales/nb.yml
- config/locales/sv.yml
Invoices and emails have been sent with dates with month abbreviated,
however the abbreviation was wrong for some months and languages, also
the format was off in some cases.
related: https://github.com/getlago/lago/issues/386
This change fixes this issue changing the date format with month full
name.
Also, correct the month name abbreviations
> fix(wrong-month-abbreviation): use month full names instead

- app/serializers/v1/plan_serializer.rb
- app/serializers/v1/progressive_billing_treshold_serializer.rb
- spec/serializers/v1/plan_serializer_spec.rb
- spec/serializers/v1/progressive_billing_treshold_serializer_spec.rb
👉  https://getlago.canny.io/feature-requests/p/progressive-billing
- Add `ProgressiveBillingTresholdSerializer`
- Update PlanSerializer wtih `progressive_billing_tresholds`
> feat(tresholds): Add serializers

- config/locales/de.yml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
- config/locales/it.yml
- config/locales/nb.yml
- config/locales/sv.yml
The goal of this PR is to change how we're aggregating months by default for all available locales.
> fix(wrong-month-abbreviation): Change abbreviation month names

- config/locales/es.yml
- config/locales/fr.yml
We don't want to prepend the month name by `0` if less than `10` for `es` and `fr` locales.
---
Example before:
Example after:
> fix(wrong-month-abbreviation): Do not prepend day number by 0 for fr and es locales

- app/graphql/types/integrations/anrok.rb
- schema.graphql
- schema.json
- spec/graphql/types/integrations/anrok_spec.rb
Currently integration with tax provider Anrok is being added.
This PR adds total number of failed invoices to the Anrok Integration GQL response. It will allow FE to display this information.
> feat(tax-integration): add failed invoices count

- app/controllers/api/v1/invoices_controller.rb
- app/serializers/v1/invoices/error_detail_serializer.rb
- spec/serializers/v1/invoice_serializer_spec.rb
when serializing invoice we want to include error_details
add error_details to include into invoice payload
> fix(anrok): add error_details include to invoice serialization

- app/controllers/api/v1/plans_controller.rb
- app/controllers/api/v1/subscriptions_controller.rb
- app/serializers/v1/subscription_serializer.rb
- spec/requests/api/v1/plans_controller_spec.rb
- spec/requests/api/v1/subscriptions_controller_spec.rb
👉  https://getlago.canny.io/feature-requests/p/progressive-billing
This PR adds and modifies controllers that handle creating, updating and overriding plans/subscriptions with usage tresholds.
> feat(tresholds): Add usage tresholds params to controllers

- app/services/integrations/aggregator/taxes/invoices/base_service.rb
- app/services/integrations/aggregator/taxes/invoices/void_service.rb
- spec/fixtures/integration_aggregator/taxes/invoices/success_response_void.json
- spec/services/integrations/aggregator/taxes/invoices/void_service_spec.rb
Currently integration with tax provider Anrok is being added
This service adds logic for sending new request to Nango. This action notifies Anrok that invoice has been voided in Lago.
> feat (tax-integrations): add new service for syncing void invoice with anrok

- app/services/integrations/aggregator/taxes/invoices/base_service.rb
- app/services/integrations/aggregator/taxes/invoices/negate_service.rb
- spec/fixtures/integration_aggregator/taxes/invoices/success_response_negate.json
- spec/services/integrations/aggregator/taxes/invoices/negate_service_spec.rb
Currently integration with tax provider Anrok is being added
This service adds logic for sending new request to Nango.
New action triggers `negate` action in Anrok.
This action should be called if voided operation cannot be perform (in case invoice is already reported to the tax authority)
> feat (tax-integrations): add support for negate action

- app/models/lifetime_usage.rb
- app/models/subscription.rb
- db/migrate/20240808132042_create_lifetime_usage.rb
- db/schema.rb
- spec/factories/lifetime_usage.rb
- spec/factories/subscriptions.rb
- spec/models/lifetime_usage_spec.rb
- spec/models/subscription_spec.rb
- spec/rails_helper.rb
- spec/services/subscriptions/create_service_spec.rb
Adds a LifetimeUsage model. sets up links between Subscription and LifetimeUsage.
> feature(ProgressiveBilling) - Add lifetime usage model

- db/migrate/20240812130655_re_add_unique_index_on_record_id.rb
- db/schema.rb
the `record_id` column was removed and re-added as a UUID (https://github.com/getlago/lago-api/commit/c36ce47a7ddf7c53eecfb9211c38c2bbe0ab6fe8) . This inadvertently removed the index that ActiveStorage adds when setting up the table. 
This MR adds that index again.
> perf(active_storage) - add index that went missing when the record_id column changed type

- app/services/invoices/calculate_fees_service.rb
- app/services/subscriptions/dates/yearly_service.rb
- app/services/subscriptions/dates_service.rb
- spec/services/invoices/calculate_fees_service_spec.rb
Currently, we are not creating any subscription fee if the subscription is started in the past.
For yearly plan with monthly charges, that's not the case, the subscription is created on the next charges billing period.
The goal of this PR is to change that by not creating any subscription fee even if the plan is yearly with monthly charges.
> fix: Prevent creating subscription fee in advance for yearly plan started in the past

- app/views/templates/credit_note.slim
Wrong country is displayed on organization section of the credit note template. It always display the customer country instead of the organization one 
This PR makes sure that the organization country is rendered.
> fix: incorrect country on credit note template

- app/services/billable_metrics/aggregations/base_service.rb
- app/services/billable_metrics/aggregations/count_service.rb
- app/services/billable_metrics/aggregations/custom_service.rb
- app/services/billable_metrics/aggregations/max_service.rb
- app/services/billable_metrics/aggregations/sum_service.rb
- app/services/billable_metrics/aggregations/unique_count_service.rb
- app/services/billable_metrics/prorated_aggregations/sum_service.rb
- app/services/charges/apply_pay_in_advance_charge_model_service.rb
- app/services/charges/charge_models/percentage_service.rb
- app/services/events/stores/base_store.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres_store.rb
- spec/services/charges/apply_pay_in_advance_charge_model_service_spec.rb
- spec/services/events/stores/clickhouse_store_spec.rb
- spec/services/events/stores/postgres_store_spec.rb
When an event is created for a paid-in-advance charge, by regrouping all fees in a single invoice at the end of the period, we were excluding the last event for computing the amount.
In the case an event was created in the future, we should not remove the last event.
The goal of this PR is to fix this issue by excluding the appropriate event before doing the aggregation.
Example before:
Example after:
> fix: Correct computation for paid in advance events

- app/models/plan.rb
- spec/models/plan_spec.rb
- spec/requests/api/v1/plans_controller_spec.rb
We were getting 500's when trying to create a plan without an interval via the API.
This PR adds presence validation for plan's interval.
> fix(plan): Add presence validation for plan interval

- app/controllers/api/v1/add_ons_controller.rb
- app/controllers/api/v1/applied_coupons_controller.rb
- app/controllers/api/v1/credit_notes_controller.rb
- app/controllers/api/v1/customers_controller.rb
- app/controllers/api/v1/fees_controller.rb
- app/controllers/api/v1/invoices_controller.rb
- app/controllers/api/v1/plans_controller.rb
Many #index actions include extra relations when serializing. If we don't include the associations we'll have N+1 queries in overview pages making them unnecessarily slow.
> perf - fix N+1 queries on #index actions

- app/services/data_exports/csv/invoice_fees.rb
- app/services/data_exports/csv/invoices.rb
- app/services/data_exports/export_resources_service.rb
- spec/services/data_exports/csv/invoice_fees_spec.rb
- spec/services/data_exports/csv/invoices_spec.rb
- spec/services/data_exports/export_resources_service_spec.rb
CSV content was generated in memory and then upload to file storage. This implies high memory requirements when the export contains a high number of records.
This change modifies the exporters to write the CSV content to disk (tempfile), then upload the file.
This should reduce the memory requirements of the worker processing the data exports and avoid sidekiq workers being restarted/killed.
> fix(data-exports): Improve CSV export memory usage

- app/models/event.rb
These scopes prevent optimal index usage. Specifically any index that includes the `timestamp` cannot be used when we use this cast.
> Remove casting in Event.{from|to}_datetime scopes

- .rubocop.yml
- app/controllers/api/v1/customers/usage_controller.rb
- app/graphql/resolvers/customers/usage_resolver.rb
- app/services/invoices/customer_usage_service.rb
- app/services/lifetime_usages/calculate_service.rb
- app/services/wallets/balance/refresh_ongoing_service.rb
- spec/services/invoices/customer_usage_service_spec.rb
- spec/services/lifetime_usages/calculate_service_spec.rb
This PR add the `LifetimeUsages::CalculateService`. This service is responsible for correctly calculating the `invoiced_usage` and `current_usage` amounts. 
Secondly a small refactor to the `CustomerUsageService` to differentiate between the 2 use-cases and streamline usage in the newly added `CalculateService`
> feat(ProgressiveBilling) -  add `LifetimeUsages::CalculateService`

- config/locales/en/email.yml
- spec/mailers/data_export_mailer_spec.rb
When a data export (invoices or fees) is completed an email is sent to the user... this email has a typo in the subject.
fix the typo.
> fix(export-invoices): fix finalized data export email subject typo

- app/graphql/mutations/integrations/anrok/fetch_draft_invoice_taxes.rb
Currently integration with tax provider Anrok is being implemented
This PR fixes mutation that fetched taxes for one-off invoice form, so that taxes can be displayed there
> fix (tax-integrations): fix mutation for fetching one-off invoice taxes

- app/controllers/api/v1/payment_requests_controller.rb
- app/models/organization.rb
- app/models/payable_group.rb
- app/models/payment_request.rb
- app/queries/payment_requests_query.rb
- config/routes.rb
- db/migrate/20240814144137_add_organization_id_to_payment_requests_and_payable_groups.rb
- db/schema.rb
- spec/factories/payable_groups.rb
- spec/factories/payment_requests.rb
- spec/models/payment_request_spec.rb
- spec/queries/payment_requests_query_spec.rb
- spec/requests/api/v1/payment_requests_controller_spec.rb
The goal of this PR is to add an endpoint for fetching payment requests from the API.
> feat(dunning): Ability to fetch payment requests from API

- app/jobs/send_webhook_job.rb
- app/serializers/v1/subscription_serializer.rb
- app/services/webhooks/subscriptions/usage_thresholds_reached_service.rb
- spec/jobs/send_webhook_job_spec.rb
- spec/serializers/v1/subscription_serializer_spec.rb
- spec/services/webhooks/subscriptions/usage_thresholds_reached_service_spec.rb
This PR add a new `subscription.usage_threshold_reached` webhook to notify that a subscription reached a new  lifetime usage threshold
> feat(ProgressiveBilling): Add new threshold reached webhook

- app/models/usage_threshold.rb
- app/services/lifetime_usages/usage_thresholds/check_service.rb
- spec/services/lifetime_usages/usage_thresholds/check_service_spec.rb
This PR adds the service responsible for checking if a threshold has been reached. It will return return all passed_thresholds as the result.
> feat(ProgressiveBilling) add `LifetimeUsages::UsageThresholds::CheckService`

- app/models/fee.rb
- app/models/invoice.rb
- app/models/invoice_subscription.rb
- app/services/fees/apply_taxes_service.rb
- app/services/fees/create_from_usage_threshold_service.rb
- app/services/invoices/create_invoice_subscription_service.rb
- app/services/invoices/progressive_billing_service.rb
- db/migrate/20240813095718_add_usage_threshold_id_to_fees.rb
- db/migrate/20240813121307_add_progressive_billing_to_invoicing_reason.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/factories/fees.rb
- spec/models/fee_spec.rb
- spec/services/fees/apply_taxes_service_spec.rb
- spec/services/fees/create_from_usage_threshold_service_spec.rb
- spec/services/invoices/create_invoice_subscription_service_spec.rb
- spec/services/invoices/progressive_billing_service_spec.rb
This PR adds the services to create an invoice with a fee when a specific `usage_threshold` is reach by a subscription.
It creates:
- A `progressive_billing` invoice
- An `invoice_subscription` with the right period boundaries
- A `progressive_billing` fee
It also handles:
- PDF generation
- Tax computation
- Email delivery
- Tracking on Segment
- Payment
- Sync with integrations
> feat(ProgressiveBilling): create an invoice for a threshold

- app/services/integrations/aggregator/taxes/invoices/base_service.rb
- spec/graphql/mutations/integrations/anrok/fetch_draft_invoice_taxes_spec.rb
- spec/services/fees/apply_provider_taxes_service_spec.rb
- spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb
- spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb
- spec/services/invoices/apply_provider_taxes_service_spec.rb
Tax provider might send us taxes with explanation of specific rules that were applied on these taxes. We want to save this information in AppliedTaxes on fees and invoices
when parsing response from tax provider, if the tax_type is included in SPECIAL_TAXATION_TYPES constant, we want to save it's name from received tax reason or tax type
> Feat(anrok): allow to save special provider tax types

- app/models/usage_threshold.rb
- app/services/plans/update_service.rb
- db/migrate/20240819092354_add_deleted_at_to_usage_thresholds.rb
- db/schema.rb
- spec/models/usage_threshold_spec.rb
This PR updates the `usage_threshold` model to allow soft deletion.
> feat(ProgressiveBilling): Usage threshold should be soft deleted

- app/graphql/types/error_details/object.rb
Fix serialization of error_details in graphql after error_details field on error_details model was renamed to details
> fix(anrok): renamed field error_details to details on error_details object

- app/services/integrations/aggregator/taxes/invoices/base_service.rb
- app/services/integrations/aggregator/taxes/invoices/payload.rb
- spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb
Now if user doesn't have a fallback item set up and tries to fetch taxes for item without product_mapping provided, we'd fail with `undefined method 'external_id' for nil (NoMethodError)` and will return server error. Instead we should process it as any other tax_integration error, because it's an incomplete integration set up
in case when no mapped_item is found for the fee, we provide an empty open_struct, so calling any method on it returns nil. It allows us to send request to anrok with empty external_product_id, and then anrok can return us validation error with message `"Request body: \"lineItems\": 0: \"productExternalId\": String must contain at least 1 character(s)."` which indicates, that product_external_id to fetch taxes is missing
> Fix(anrok): no fallback_item mapping is found

- spec/services/customers/eu_auto_taxes_service_spec.rb
As customer is created with Factorybot and for zipcode we generate `zipcode: Faker::Address.zip_code `, we can accidentally generate a zipcode in france for a customer with special rules. This introduces a flaky test, as happened here:
https://github.com/getlago/lago-api/actions/runs/10451847578/job/28939063361
as in the tests we're assuming that customer's zipcode is empty unless actively set (https://github.com/getlago/lago-api/blob/bc8193366e63c1dadbbfaaffcc5d6ee9258eafc7/spec/services/customers/eu_auto_taxes_service_spec.rb#L63), the fix is to explicitly create customer with empty zipcode
> Fix: fix flaky test for eu_auto_taxes_service_spec

- app/services/customers/create_service.rb
- spec/services/customers/create_service_spec.rb
This pull request changes Customers::CreateService adding email validation to ensure only valid email addresses are accepted when creating or updating customer records.
This is particularly important because we sync these emails with Stripe, which enforces strict email validation. Without this check, invalid emails could cause the Stripe synchronization process to fail
> feat: add email validation

- app/graphql/mutations/plans/create.rb
- app/graphql/mutations/plans/update.rb
- app/graphql/types/plans/object.rb
- app/graphql/types/subscriptions/plan_overrides_input.rb
- app/graphql/types/subscriptions/usage_threshold_overrides_input.rb
- app/graphql/types/usage_thresholds/input.rb
- app/graphql/types/usage_thresholds/object.rb
- app/services/plans/override_service.rb
- app/services/usage_thresholds/override_service.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/plans/create_spec.rb
- spec/graphql/mutations/plans/update_spec.rb
- spec/graphql/mutations/subscriptions/create_spec.rb
- spec/graphql/types/plans/object_spec.rb
- spec/graphql/types/subscriptions/plan_overrides_input_spec.rb
- spec/graphql/types/subscriptions/usage_threshold_overrides_input_spec.rb
- spec/graphql/types/usage_thresholds/input_spec.rb
- spec/graphql/types/usage_thresholds/object_spec.rb
- spec/requests/api/v1/subscriptions_controller_spec.rb
- spec/services/usage_thresholds/override_service_spec.rb
👉  https://getlago.canny.io/feature-requests/p/progressive-billing
Add GraphQL for usage thresholds.
> feat(tresholds): Add GraphQL for usage thresholds

- app/models/fee.rb
- app/models/usage_threshold.rb
- app/services/invoices/progressive_billing_service.rb
- app/views/helpers/fee_display_helper.rb
- app/views/templates/invoices/v4/_subscription_details.slim
- config/locales/de/invoice.yml
- config/locales/en/invoice.yml
- config/locales/es/invoice.yml
- config/locales/fr/invoice.yml
- config/locales/it/invoice.yml
- config/locales/nb/invoice.yml
- config/locales/sv/invoice.yml
- spec/factories/fees.rb
- spec/models/fee_spec.rb
- spec/models/usage_threshold_spec.rb
- spec/services/invoices/progressive_billing_service_spec.rb
This PR allows generating the PDF for progressive billing invoices
> feat(ProgressiveBilling): Update PDF template

- db/migrate/20240816075711_add_negative_amount_cents_to_invoice.rb
- db/schema.rb
With the addition of progressive billing we might have negative invoices when subtracting already progressively billed invoices. This MR sets up the DB to store that field. 
The logic will be added later on top of the invoicing code.
> feat(ProgressiveBilling) - add negative_amount_cents to invoices

- app/services/credits/credit_note_service.rb
- app/services/invoices/calculate_fees_service.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- app/services/invoices/progressive_billing_service.rb
- app/services/invoices/retry_service.rb
- spec/services/credits/credit_note_service_spec.rb
- spec/services/invoices/progressive_billing_service_spec.rb
This PR makes sure that coupons, prepaid credits and credit notes are applied to progressive billing invoices
> feat(ProgressiveBilling): Apply credit notes, coupons and prepaid credits to invoice

- app/models/credit.rb
- app/models/invoice.rb
- db/migrate/20240820090312_attach_progressive_billing_invoices_to_credits.rb
- db/schema.rb
- spec/factories/credits.rb
- spec/models/credit_spec.rb
- spec/models/invoice_spec.rb
This PR adds the `progressive_billing_invoice_id` foreign key column to the `credits` table. It will allow us to take a progressive billing invoice into account when generating a subscription invoice
> feat(ProgressiveBilling): Add progressive billing invoice relation to credit

- app/jobs/send_webhook_job.rb
- app/services/payment_requests/create_service.rb
- app/services/webhooks/payment_requests/created_service.rb
- spec/jobs/send_webhook_job_spec.rb
- spec/services/payment_requests/create_service_spec.rb
- spec/services/webhooks/payment_requests/created_service_spec.rb
- create the payable group for the overdue invoices
- create the payment request for the payable group
- send the payment_request.created webhook
on the payment request creation service
> feat(dunning): Create payment request

- app/models/subscription.rb
- spec/services/subscriptions/create_service_spec.rb
as we activate a subscription, we assumed we'd have to flag the life-time usage for recalculation. This is incorrect, and causes unneeded calculations. These flags should be set when an invoice is generated or an event is processed.
> 🐛 bug(ProgressiveBilling) Don't set recalculation flags to true when creating LifetimeUsage

- app/services/payment_requests/create_service.rb
- spec/requests/api/v1/payment_requests_controller_spec.rb
- spec/services/payment_requests/create_service_spec.rb
The goal of this PR is to prevent the creation of a payment request:
- when not premium
- when not having `dunning` add-on feature
- when invoices are not overdue
> feat(dunning): Prevent creating payment request when not overdue

- app/graphql/types/wallets/recurring_transaction_rules/object.rb
The goal of this PR is to remove the following warning:
```
RecurringTransactionRule's `field :method` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_method` and `def resolve_method`). Or use `method_conflict_warning: false` to suppress this warning.
```
> fix: Remove conflict with a built-in method on graphql

- app/models/invoice/applied_tax.rb
- app/views/templates/invoices/v4/_subscription_details.slim
- config/locales/de/invoice.yml
- config/locales/en/invoice.yml
- config/locales/es/invoice.yml
- config/locales/fr/invoice.yml
- config/locales/it/invoice.yml
- config/locales/nb/invoice.yml
- config/locales/sv/invoice.yml
- spec/models/invoice/applied_tax_spec.rb
When saving applied taxes with received from Anrok special tax provider rules (types) we want to display them in invoice
added `applied_on_whole_invoice?` method to Invoice::AppliedTax
depending on if displayed tax is applicable on the whole invoice or no, show different name format for the tax name
> Feat (anrok): display special provider rules in pdf

- app/models/lifetime_usage.rb
- app/services/lifetime_usages/usage_thresholds/check_service.rb
- db/migrate/20240822080031_add_historical_usage_to_lifetime_usage.rb
- db/schema.rb
- spec/models/lifetime_usage_spec.rb
- spec/services/lifetime_usages/usage_thresholds/check_service_spec.rb
Add a `historical_usage_amount_cents` column to `LifetimeUsage`, this column can be filled in with usage coming from an external system. 
We take the historical usage into account when checking if thresholds have been passed.
> feat(ProgressiveBilling) - Add historical_usage_amount_cents to LifetimeUsage

- Gemfile
- Gemfile.lock
- app/models/clickhouse/events_count_agg.rb
- app/models/clickhouse/events_enriched.rb
- app/models/clickhouse/events_max_agg.rb
- app/models/clickhouse/events_raw.rb
- app/models/clickhouse/events_sum_agg.rb
- db/clickhouse_migrate/20231024084411_create_events_raw.rb
- db/clickhouse_migrate/20240705080709_create_events_enriched.rb
- db/clickhouse_migrate/20240705090006_create_events_sum_agg.rb
- db/clickhouse_migrate/20240709095907_create_events_count_agg.rb
- db/clickhouse_migrate/20240709135506_create_events_max_agg.rb
See https://github.com/getlago/clickhouse-activerecord/pull/10 description for full context
> chore: Upgrade our `clickhouse-activerecord` fork

- clock.rb
- spec/clockwork_spec.rb
Allows configuring the refresh interval via an ENV variable.
> feat(ProgressiveBilling) - Add support for LAGO_LIFETIME_USAGE_REFRESH_INTERVAL_SECONDS 

- app/models/customer.rb
- app/services/customers/create_service.rb
- lib/tasks/auto_annotate_models.rake
- spec/services/customers/create_service_spec.rb
This pull request unifies the email validation logic across the application, use the same validation in customer that we already had for the organization
> feat: Unify Email Validation Across the Application

- app/services/credits/progressive_billing_service.rb
- app/services/invoices/compute_amounts_from_fees.rb
- app/services/invoices/progressive_billing_service.rb
- spec/services/credits/progressive_billing_service_spec.rb
- spec/services/invoices/progressive_billing_service_spec.rb
This PR applies credits from the progressive_billing invoices to every new progressive billing invoice in the same period. It also makes sure that credits are well applied to fees and taken into account when computing taxes
> feat(ProgressiveBilling): Apply credit to progressive billing invoices

- app/services/payment_requests/create_service.rb
- spec/services/payment_requests/create_service_spec.rb
The goal of this PR is to return an error when trying to create a payment request with:
- invoices having different currencies
- invoices not ready for payment processing
> feat(dunning): Prevent creation of payment request

- app/services/integrations/aggregator/contacts/payloads/base_payload.rb
- app/services/integrations/aggregator/contacts/payloads/netsuite.rb
- spec/services/integrations/aggregator/contacts/create_service_spec.rb
- spec/services/integrations/aggregator/contacts/payloads/netsuite_spec.rb
- spec/services/integrations/aggregator/contacts/update_service_spec.rb
Netsuite doesn't support comma-separated contacts emails, so we'll send only the first one.
Similar aplies for the phone number(s).
This PR adds methods for transforming email and phone in contact create and update payloads.
It also removes obsolete `custentity_form_activeprospect_customer` attribute.
> feat(netsuite): Cleanup email and phone in contact payloads

- app/graphql/types/invoices/object.rb
- app/jobs/clock/refresh_lifetime_usages_job.rb
- app/models/invoice.rb
- app/serializers/v1/invoice_serializer.rb
- app/views/templates/invoices/v4/_progressive_billing_details.slim
- app/views/templates/invoices/v4/_subscription_details.slim
- app/views/templates/invoices/v4/_subscriptions_summary.slim
- config/locales/de/invoice.yml
- config/locales/en/invoice.yml
- config/locales/es/invoice.yml
- config/locales/fr/invoice.yml
- config/locales/it/invoice.yml
- config/locales/nb/invoice.yml
- config/locales/sv/invoice.yml
- schema.graphql
- schema.json
- spec/graphql/types/invoices/object_spec.rb
- spec/jobs/clock/refresh_lifetime_usages_job_spec.rb
- spec/models/invoice_spec.rb
- spec/serializers/v1/invoice_serializer_spec.rb
This PR:
- Improves the PDF templates to render the previously billed progressive billing amount
- Exposes the `progressive_billing_credit_amount_cents` in REST and GraphQL APIs as well as in invoice related webhooks.
- Ensures that the `Clock::RefreshLifetimeUsagesJob` job is performed only in premium mode
> feat(ProgressiveBilling): Improvements on PDF and APIs

- app/models/payment_request.rb
- app/services/payment_requests/payments/deliver_error_webhook_service.rb
- app/services/payment_requests/payments/payment_providers/factory.rb
- app/services/payment_requests/payments/stripe_service.rb
- db/migrate/20240822142524_add_payment_retry_columns_to_payment_requests.rb
- db/schema.rb
- spec/factories/payment_requests.rb
- spec/models/payment_request_spec.rb
- spec/services/payment_requests/payments/deliver_error_webhook_service_spec.rb
- spec/services/payment_requests/payments/payment_providers/factory_spec.rb
- spec/services/payment_requests/payments/stripe_service_spec.rb
- spec/support/matchers/negated_matchers.rb
The goal of this PR is to create a stripe payment for customers this payment provider.
> feat(dunning): Create stripe payment

- app/graphql/types/invoices/applied_taxes/object.rb
- schema.graphql
- schema.json
On FE to be able to show differently taxes applied on all line items vs on few only within the invoice, we need to specify on the applied_tax if it's applicable on the whole invoice
and to be able to show different translation for the taxes depending on their code, we want to send tax_cod with applied tax as well
- added tax_code
- and applied_on_whole_invoice
to Invoice::AppliedTax graphql type
> Feat(anrok): add fields to graphql response on applied taxes

- app/models/applied_usage_threshold.rb
- app/models/invoice.rb
- app/models/lifetime_usage.rb
- app/models/usage_threshold.rb
- app/services/invoices/progressive_billing_service.rb
- app/views/templates/invoices/v4.slim
- config/locales/de/invoice.yml
- config/locales/en/invoice.yml
- config/locales/es/invoice.yml
- config/locales/fr/invoice.yml
- config/locales/it/invoice.yml
- config/locales/nb/invoice.yml
- config/locales/sv/invoice.yml
- db/migrate/20240823092643_create_applied_usage_thresholds.rb
- db/schema.rb
- spec/factories/applied_usage_thresholds.rb
- spec/models/applied_usage_threshold_spec.rb
- spec/models/invoice_spec.rb
- spec/models/lifetime_usage_spec.rb
- spec/models/usage_threshold_spec.rb
- spec/services/invoices/progressive_billing_service_spec.rb
This PR updates the logic to render a usage threshold description on the progressive invoice PDF. It does so by creating a relation between the invoice and the usage threshold
> feat(ProgressiveBilling): Add invocing reason on the progressive billing invoice template

- app/services/payment_requests/payments/gocardless_service.rb
- spec/services/payment_requests/payments/gocardless_service_spec.rb
The goal of this PR is to create a GoCardLess payment mandate for customers with this payment provider.
> feat(dunning): Create GoCardLess payment

- app/services/invoices/refresh_draft_and_finalize_service.rb
- app/services/invoices/refresh_draft_service.rb
- app/services/lifetime_usages/flag_refresh_from_invoice_service.rb
- spec/services/invoices/refresh_draft_service_spec.rb
Also flag draft invoices for LifetimeUsage recalculation.
> feat(ProgressiveBilling) - take draft invoices into account for LifetimeUsage refreshing

- app/services/credits/progressive_billing_service.rb
- app/services/lifetime_usages/calculate_service.rb
- app/views/templates/invoices/v4.slim
- app/views/templates/invoices/v4/_progressive_billing_details.slim
- app/views/templates/invoices/v4/_subscription_details.slim
- app/views/templates/invoices/v4/_subscriptions_summary.slim
- spec/services/credits/progressive_billing_service_spec.rb
- spec/services/invoices/calculate_fees_service_spec.rb
- spec/services/lifetime_usages/calculate_service_spec.rb
This PR
- Includes draft invoices in the computation of `lifetime_usage#invoiced_usage_amount_cents` amount
- Makes sure that previous subscriptions are also taken into account
> feat(ProgressiveBilling): Use draft invoices and previous subscriptions

- app/services/invoices/refresh_draft_and_finalize_service.rb
- app/services/invoices/refresh_draft_service.rb
fail with validation failure when fail to refresh invoice
> return validation_error when failing to refresh invoice

- config/database.yml
Our staging workers are run with a concurrency of 10 but the connection pools are the default size of 5. In order to increase reliability when running high amount of jobs, we bump the limit to 10.
> Increase default pool size to 10 for staging databases

- app/jobs/payment_requests/payments/adyen_create_job.rb
- app/jobs/payment_requests/payments/gocardless_create_job.rb
- app/jobs/payment_requests/payments/stripe_create_job.rb
- app/services/payment_requests/create_service.rb
- app/services/payment_requests/payments/create_service.rb
- app/services/payment_requests/payments/payment_providers/factory.rb
- spec/jobs/payment_requests/payments/adyen_create_job_spec.rb
- spec/jobs/payment_requests/payments/gocardless_create_job_spec.rb
- spec/jobs/payment_requests/payments/stripe_create_job_spec.rb
- spec/services/payment_requests/create_service_spec.rb
- spec/services/payment_requests/payments/create_service_spec.rb
- spec/services/payment_requests/payments/payment_providers/factory_spec.rb
👉
The goal of this PR is to kick off the payment creation for payment requests when customer has a payment provider.
> feat(dunning): Create payment on payment request creation

- app/services/integrations/aggregator/base_service.rb
- spec/fixtures/integration_aggregator/error_payload_response.json
- spec/services/integrations/aggregator/contacts/create_service_spec.rb
- spec/services/integrations/aggregator/contacts/update_service_spec.rb
Return Nango's error as a webhook message. Some error payloads have different json format as we expected.
Catch all the error formats that Netsuite/Nango returns and send a webhook.
> misc(netsuite): Process payload errors

- app/graphql/types/integrations/anrok.rb
When returning amount of failed invoices for the anrok integration, filter invoices with only status 'failed'
> Fix(anrok): return only number of failed invoices

- app/controllers/api/v1/payment_requests_controller.rb
- app/mailers/payment_request_mailer.rb
- app/models/invoice.rb
- app/models/payment_request.rb
- app/services/payment_requests/create_service.rb
- app/services/payment_requests/payments/create_service.rb
- app/views/payment_request_mailer/requested.slim
- config/locales/de/email.yml
- config/locales/en/email.yml
- config/locales/es/email.yml
- config/locales/fr/email.yml
- config/locales/it/email.yml
- config/locales/nb/email.yml
- config/locales/sv/email.yml
- spec/mailers/payment_request_mailer_spec.rb
- spec/mailers/previews/payment_request_mailer_preview.rb
- spec/services/payment_requests/create_service_spec.rb
The goal of this PR is to send an email reminder when creating a payment request without payment provider.
> feat(dunning): Send email reminder when creating a payment request

- app/graphql/types/integration_customers/anrok.rb
- schema.graphql
- schema.json
- spec/graphql/types/integration_customers/anrok_spec.rb
Anrok integration is currently being implemented
This PR adds additional field on anrok customer GQL object so that UI can easier present links
> fix (tax-integrations): expose external account id on anrok customer

- app/services/payment_requests/payments/adyen_service.rb
- app/services/payment_requests/payments/generate_payment_url_service.rb
- app/services/payment_requests/payments/stripe_service.rb
- spec/services/payment_requests/payments/adyen_service_spec.rb
- spec/services/payment_requests/payments/generate_payment_url_service_spec.rb
- spec/services/payment_requests/payments/stripe_service_spec.rb
The goal of this change is to allow payment requests for stripe and adyen payment providers to generate payment urls
> feat(dunning): Generate Payment url for stripe and adyen

- app/serializers/v1/integrations/taxes/customer_error_serializer.rb
- app/services/webhooks/integrations/taxes/error_service.rb
- spec/serializers/v1/integrations/taxes/customer_error_serializer_spec.rb
Integration with tax provider Anrok is being implemented
This PR fixes error webhook that is being dispatched
> fix(tax-integrations): update anrok error webhook attributes

- app/jobs/send_webhook_job.rb
- app/serializers/v1/payment_providers/payment_request_payment_error_serializer.rb
- app/services/payment_requests/payments/deliver_error_webhook_service.rb
- app/services/webhooks/payment_providers/payment_request_payment_failure_service.rb
- spec/jobs/send_webhook_job_spec.rb
- spec/serializers/v1/payment_providers/payment_request_payment_error_serializer_spec.rb
- spec/services/webhooks/payment_providers/payment_request_payment_failure_service_spec.rb
The goal of this change is to add the missing payment request payment failure webhook.
> feat(dunning): Add payment_request.payment_failure webhook

- app/mailers/payment_request_mailer.rb
The goal of this change is to ensure invoices pdf are generated before sending the payment request email.
> feat(dunning): Generate PDF files for payment request invoices

- app/graphql/mutations/integrations/anrok/fetch_draft_invoice_taxes.rb
- app/services/fees/one_off_service.rb
- app/services/invoices/create_one_off_service.rb
- spec/graphql/mutations/integrations/anrok/fetch_draft_invoice_taxes_spec.rb
- spec/services/fees/one_off_service_spec.rb
- spec/services/invoices/create_one_off_service_spec.rb
Currently integration with tax provider Anrok is being implemented.
This PR uses all existing Anrok logic on one-off invoices. 
If customer is connected to Anrok, its taxes should be used. All services and Anrok core logic is already implemented and merged on main. This is just logic that consumes it for one-off invoices
> feat (tax-integrations): Use Anrok taxes for one off invoices

- app/jobs/bill_subscription_job.rb
- app/jobs/invoices/finalize_all_job.rb
- app/services/fees/commitments/minimum/create_service.rb
- app/services/invoices/apply_provider_taxes_service.rb
- app/services/invoices/calculate_fees_service.rb
- app/services/invoices/refresh_draft_and_finalize_service.rb
- app/services/invoices/refresh_draft_service.rb
- app/services/invoices/subscription_service.rb
- spec/jobs/bill_subscription_job_spec.rb
- spec/jobs/invoices/finalize_all_job_spec.rb
- spec/jobs/invoices/finalize_job_spec.rb
- spec/jobs/invoices/refresh_draft_job_spec.rb
- spec/services/fees/commitments/minimum/create_service_spec.rb
- spec/services/invoices/apply_provider_taxes_service_spec.rb
- spec/services/invoices/calculate_fees_service_spec.rb
- spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
- spec/services/invoices/refresh_draft_service_spec.rb
- spec/services/invoices/subscription_service_spec.rb
Currently integration with tax provider Anrok is being implemented.
This PR uses all existing Anrok logic on subscription and draft invoices. 
If customer is connected to Anrok, its taxes should be used. All services and Anrok core logic is already implemented and merged on main. This is just logic that consumes it for subscription and draft invoices
> feat (tax-integrations): Use Anrok taxes in subscription invoices flow

- app/graphql/types/taxes/applied_tax.rb
- schema.graphql
- schema.json
Since applied taxes received from Anrok does not have relation to taxes saved in the DB, tax is no longer required on the Applied Tax
> Fix(anrok): make tax object on applied tax optional

- app/jobs/fees/create_pay_in_advance_job.rb
- app/jobs/invoices/create_pay_in_advance_charge_job.rb
- app/services/fees/create_pay_in_advance_service.rb
- app/services/invoices/apply_provider_taxes_service.rb
- app/services/invoices/compute_amounts_from_fees.rb
- app/services/invoices/create_generating_service.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- spec/services/fees/create_pay_in_advance_service_spec.rb
- spec/services/invoices/advance_charges_service_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
Currently integration with tax provider Anrok is being implemented.
This PR uses all existing Anrok logic on pay in advance invoices
If customer is connected to Anrok, its taxes should be used. All services and Anrok core logic is already implemented and merged on main. This is just logic that consumes it for pay in advance invoices
> feat (tax-integrations): Use Anrok taxes in pay in advance flow

- app/services/payment_requests/payments/adyen_service.rb
- app/services/payment_requests/payments/stripe_service.rb
- spec/services/payment_requests/payments/adyen_service_spec.rb
- spec/services/payment_requests/payments/stripe_service_spec.rb
👉
The goal of this change is to define description/reference/product name for stripe and adyen payloads as agreed.
Also, sets adyen payment link TTL to the maximum allowed (70 days).
> feat(dunning): define right description/reference/product name within stripe and adyen payloads

- app/graphql/types/plans/object.rb
- app/graphql/types/subscriptions/charge_overrides_input.rb
- app/graphql/types/subscriptions/usage_threshold_overrides_input.rb
- app/models/usage_threshold.rb
- app/services/plans/update_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/subscriptions/charge_overrides_input_spec.rb
- spec/graphql/types/subscriptions/usage_threshold_overrides_input_spec.rb
We were getting validation erros when updating a plan via the UI.
The problem was a specific combination of: removing and re-adding thresholds with the same amount because of a constraint. First we were creating a new threshold while the old one (with the same amount was still in the DB). Also there might have been the same threshold wtih that amount existing but soft deleted.
Refactor the validations, and saving logic of thresholds.
> fix(thresholds): Fix updating plan with deleted thresholds

- app/serializers/v1/applied_usage_threshold_serializer.rb
- app/serializers/v1/invoice_serializer.rb
- spec/serializers/v1/applied_usage_threshold_serializer_spec.rb
- spec/serializers/v1/invoice_serializer_spec.rb
This PR adds adds the new `applied_usage_thresholds` in `V1::InvoiceSerializer`
> feat(ProgressiveBilling): Expose Invoice#AppliedUsageThresholds in REST API

- app/services/integration_customers/update_service.rb
- spec/services/integration_customers/update_service_spec.rb
For Anrok, we should not call the service that updates integration customer data in external service
> fix (tax-integrations): do not call update integration customer external service for anrok

- app/services/integrations/aggregator/taxes/invoices/payload.rb
- spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb
- spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb
If there is no shipping address, we should fallback to billing address
> fix (tax-integrations): use billing address if there is no shipping address

- app/models/invoice/applied_tax.rb
- app/services/integrations/aggregator/taxes/invoices/base_service.rb
- config/locales/de/invoice.yml
- config/locales/en/invoice.yml
- config/locales/es/invoice.yml
- config/locales/fr/invoice.yml
- config/locales/it/invoice.yml
- config/locales/nb/invoice.yml
- config/locales/sv/invoice.yml
- schema.graphql
- schema.json
- spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb
Apply zero tax for unknown tax exemption
> fix (tax-integrations): apply zero tax for unknown tax exemption

- config/routes.rb
when fetching plans, sending a request to {{baseUrl}}/plans/:code, if code contains dots, the plan can't be found
allowed code parameter for plans_controller contain dots
> Fix: allow code for plans_controller#show to contain dots

- app/jobs/send_webhook_job.rb
- app/services/payment_requests/payments/gocardless_service.rb
- app/services/payment_requests/update_service.rb
- app/services/webhooks/payment_requests/payment_status_updated_service.rb
- spec/services/payment_requests/payments/gocardless_service_spec.rb
- spec/services/payment_requests/update_service_spec.rb
- spec/services/webhooks/payment_requests/payment_status_updated_service_spec.rb
The goal of this change is to update the status of gocardless payments.
With this change we introduce a service to update payment requests, this will trigger a webhook when the payment status is updated.
> feat(dunning): Add update_payment_status for gocardless payments

- app/graphql/resolvers/invoices_resolver.rb
- schema.graphql
- schema.json
When fetching invoices, we can filter by `external_id` but it's not currently possible to filter by `id`. 
In the case of deleted customers with the same external id, it will return all the related invoices as well.
We want to be able to only return invoices for the active customer.
> feat(dunning): Add customerId to invoices graphql resolver

- app/graphql/types/integrations/anrok_objects/breakdown_object.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/integrations/anrok/fetch_draft_invoice_taxes_spec.rb
to display addon taxes the same way when creating a one-off invoice as when we show fee taxes in all the other invoices, FE needs enumed_tax_code to be sent in the same format as for Invoice::AppliedTax (which is usually created when creating an invoice)
> Feat(anrok): add enumed_tax_code to tax breakdown serialization

- app/jobs/clock/refresh_lifetime_usages_job.rb
- app/models/organization.rb
- app/services/credits/progressive_billing_service.rb
- spec/jobs/clock/refresh_lifetime_usages_job_spec.rb
- spec/models/organization_spec.rb
Instead of refreshing all LifetimeUsage objects, we'll only check those that belong to an organization that has `progressive_billing` enabled.
> feat(ProgressiveBilling) - Only refresh LifeTimeUsage for premium integrations with progressive_billing enabled

- app/services/payment_requests/payments/stripe_service.rb
- spec/services/payment_requests/payments/gocardless_service_spec.rb
- spec/services/payment_requests/payments/stripe_service_spec.rb
👉
The goal of this change is to update the status of stripe payments for payment requests.
> feat(dunning): Add update_payment_status for stripe payments

- app/config/permissions/role-finance.yml
- app/graphql/types/organizations/current_organization_type.rb
- app/graphql/types/organizations/update_organization_input.rb
- spec/graphql/mutations/organizations/update_spec.rb
- spec/graphql/types/organizations/current_organization_type_spec.rb
- spec/graphql/types/organizations/update_organization_input_spec.rb
This PR addresses an issue where users with the “Finance” role were unable to view or update the organization.tax_identification_number despite the role having permissions to manage organization information according to the roles and permissions documentation.
> Fix(permissions): Allow Finance Role to View and Update Organization’s Tax ID

- app/services/payment_providers/adyen_service.rb
- app/services/payment_providers/gocardless_service.rb
- app/services/payment_providers/stripe_service.rb
- spec/fixtures/adyen/webhook_authorisation_payment_response_invalid_payable.json
- spec/fixtures/adyen/webhook_authorisation_payment_response_payment_request.json
- spec/fixtures/gocardless/events_invalid_payable_type.json
- spec/fixtures/gocardless/events_payment_request.json
- spec/fixtures/stripe/charge_event_invalid_payable_type.json
- spec/fixtures/stripe/charge_event_payment_request.json
- spec/fixtures/stripe/payment_intent_event_invalid_payable_type.json
- spec/fixtures/stripe/payment_intent_event_payment_request.json
- spec/services/payment_providers/adyen_service_spec.rb
- spec/services/payment_providers/gocardless_service_spec.rb
- spec/services/payment_providers/stripe_service_spec.rb
The goal of this change is to route payment events to the right service to update the payment status when the payable is a payment request.
> feat(dunning): Process PSPs event for payment requests payment status update

- app/graphql/types/subscriptions/lifetime_usage_object.rb
- app/graphql/types/subscriptions/object.rb
- app/services/lifetime_usages/find_last_and_next_thresholds_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/subscriptions/lifetime_usage_object_spec.rb
- spec/graphql/types/subscriptions/object_spec.rb
- spec/services/lifetime_usages/find_last_and_next_thresholds_service_spec.rb
This PR exposes a new `SubscriptionLifetimeUsage` GraphQL type attached to the `Subscription` type.
> feat(ProgressiveBilling): expose SubscriptionLifetimeUsage in GraphQL

- app/graphql/resolvers/customers/usage_resolver.rb
- app/services/invoices/customer_usage_service.rb
- app/services/lifetime_usages/calculate_service.rb
- spec/graphql/resolvers/customers/usage_resolver_spec.rb
- spec/services/invoices/customer_usage_service_spec.rb
In current usage, taxes are relevant only in API context and in Ongoing Wallet Balance Job. In other cases, tax computation should be skipped.
> misc: prevent applying taxes for current usage where it is not necessary

- app/mailers/payment_request_mailer.rb
- app/views/payment_request_mailer/requested.slim
- spec/mailers/payment_request_mailer_spec.rb
- spec/mailers/previews/payment_request_mailer_preview.rb
The goal of this change is to include the payment link within the payment request requested email to customers when the PSP is Stripe or Adyen and the link is available
> feat(dunning): Include payment link to payment request email when available

- app/services/payment_providers/adyen_service.rb
- app/services/payment_requests/payments/adyen_service.rb
- app/services/payment_requests/payments/gocardless_service.rb
- app/services/payment_requests/payments/stripe_service.rb
- spec/fixtures/adyen/webhook_authorisation_payment_response_invalid_payable.json
- spec/fixtures/adyen/webhook_authorisation_payment_response_payment_request.json
- spec/fixtures/stripe/charge_event_invalid_payable_type.json
- spec/fixtures/stripe/charge_event_payment_request.json
- spec/fixtures/stripe/payment_intent_event_invalid_payable_type.json
- spec/fixtures/stripe/payment_intent_event_payment_request.json
- spec/services/payment_providers/stripe_service_spec.rb
- spec/services/payment_requests/payments/adyen_service_spec.rb
- spec/services/payment_requests/payments/gocardless_service_spec.rb
- spec/services/payment_requests/payments/stripe_service_spec.rb
The goal of this change is to fix a QA return dropping the `Lago_invoices_id` attribute from PSPs payload as it is not needed for us and some PSPs like Stripe only supports string values, hence, a list of ids can not be passed within the metadata payload.
> feat(dunning): Drop lago_invoice_ids from PSPs metadata payloads

- app/controllers/api/v1/lifetime_usages_controller.rb
- app/graphql/types/subscriptions/lifetime_usage_object.rb
- app/serializers/v1/lifetime_usage_serializer.rb
- app/services/lifetime_usages/find_last_and_next_thresholds_service.rb
- app/services/lifetime_usages/update_service.rb
- app/services/lifetime_usages/usage_thresholds_completion_service.rb
- config/routes.rb
- schema.graphql
- schema.json
- spec/graphql/types/subscriptions/lifetime_usage_object_spec.rb
- spec/requests/api/v1/lifetime_usages_controller_spec.rb
- spec/serializers/v1/lifetime_usage_serializer_spec.rb
- spec/services/lifetime_usages/find_last_and_next_thresholds_service_spec.rb
- spec/services/lifetime_usages/update_service_spec.rb
- spec/services/lifetime_usages/usage_thresholds_completion_service_spec.rb
This PR introduces a new `LifetimeUsages::UsageThresholdsCompletionService` which calculates the completion ratios of thresholds. 
Also we add a `LifetimeUsagesController` combined with new serializer to facilitate fetching and updating lifetime usages through the api.
> feat(ProgressiveBilling) - Add LifetimeUsages::UsageThresholdsCompletionService

- app/models/subscription.rb
- app/services/invoices/create_invoice_subscription_service.rb
- app/services/subscriptions/dates_service.rb
- spec/models/subscription_spec.rb
- spec/services/invoices/calculate_fees_service_spec.rb
- spec/services/subscriptions/dates/monthly_service_spec.rb
- spec/services/subscriptions/dates/quarterly_service_spec.rb
- spec/services/subscriptions/dates/weekly_service_spec.rb
- spec/services/subscriptions/dates/yearly_service_spec.rb
After terminating a subscription, when there are several draft invoices linked to the same subscription (i.e. several invoice subscriptions) and we refresh the oldest one, the corresponding invoice subscription is updated with the boundaries of the most recent invoice subscription.
The goal of this PR is to check the termination date of the subscription and compare it with the given timestamp, in addition of checking if the subscription is terminated.
> fix: Compare terminated_at to timestamp for terminated subscription

- spec/services/invoices/finalize_open_credit_service_spec.rb
This PR fixes the following warning messages when running the specs:
```
WARNING: An expectation of `:should_sync_invoice?` was set on `nil`. To allow expectations on `nil` and suppress this message, set `RSpec::Mocks.configuration.allow_message_expectations_on_nil` to `true`. To disallow expectations on `nil`, set `RSpec::Mocks.configuration.allow_message_expectations_on_nil` to `false`. Called from /home/runner/work/lago-api/lago-api/spec/services/invoices/finalize_open_credit_service_spec.rb:12:in `block (2 levels) in <top (required)>'.
WARNING: An expectation of `:should_sync_sales_order?` was set on `nil`. To allow expectations on `nil` and suppress this message, set `RSpec::Mocks.configuration.allow_message_expectations_on_nil` to `true`. To disallow expectations on `nil`, set …
```
> misc: Fix some warning in specs

- app/services/wallets/balance/refresh_ongoing_service.rb
- app/services/wallets/balance/update_ongoing_service.rb
- spec/services/wallets/balance/update_ongoing_service_spec.rb
Currently, invoiceable charges paid in advance are deducted twice from the ongoing balance of the active wallet.
The goal of this PR is to exclude these fees from the ongoing balance.
> fix(wallet): Exclude pay in advance fees from the ongoing balance

- app/views/payment_request_mailer/requested.slim
- config/locales/en/email.yml
- config/locales/es/email.yml
The goal of this change is to fix QA returns related to the Spanish translation for payment requested email.
> feat(dunning): Fix Spanish translation for payment requested email

- app/models/wallet.rb
- spec/models/wallet_spec.rb
This PR adds a validation rule to `wallet#rate_amount` to make sure it will always be a positive value.
It will fixes the following dead job related to wallets with rate_amount = 0 
```
ActiveRecord::RecordInvalid
Validation failed: Ongoing balance is not a number, Ongoing usage balance is not a number (ActiveRecord::RecordInvalid)
```
> fix(wallet): Add validation rule on rate_amount

- app/jobs/bill_subscription_job.rb
- app/jobs/fees/create_pay_in_advance_job.rb
- app/jobs/invoices/create_pay_in_advance_charge_job.rb
- app/jobs/invoices/finalize_all_job.rb
This PR fixes the following error in `BillSubscriptionJob`
```
NoMethodError
undefined method `messages' for an instance of ActiveRecord::RecordNotUnique
```
The issue is related to the recent handling of `tax_error` that is checking for a `tax_error` error in the `error.messages`. `error.messages` only exists if the error is a `BaseService::ValidationFailure`
> fix(taxes): tax_error handling must target ValidationFailure

- app/services/customers/create_service.rb
- app/services/customers/update_service.rb
- spec/services/customers/create_service_spec.rb
- spec/services/customers/update_service_spec.rb
In this PR we're adding the new model fields `lastname`, `firstname` and `customer_type` to  create and update customer services
> feat: Add customer type to services

- app/models/customer.rb
- app/queries/customers_query.rb
- app/queries/invoices_query.rb
- spec/queries/customers_query_spec.rb
- spec/queries/invoices_query_spec.rb
We have enhanced the search functionality for both Customers and Invoices to allow searches by `firstname` and `lastname` fields, in addition to the existing name field.
> feat: Add firstname and last name to queries

- app/config/permissions/definition.yml
- app/config/permissions/role-finance.yml
- app/config/permissions/role-manager.yml
- app/graphql/resolvers/analytics/overdue_balances_resolver.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/analytics/overdue_balances_resolver_spec.rb
The goal of this change is to fix QA returns related to the overdue balances permission.
> feat(dunning): Add permission to analytics overdue balances

- app/controllers/api/v1/customers_controller.rb
- spec/requests/api/v1/customers_controller_spec.rb
In this PR we're white-listing the new fields `lastname`, `firstname` and `customer_type` in `CustomersController`.
> feat(customer-type): Whitelist new params in customer controller

- app/views/templates/credit_note.slim
- app/views/templates/invoices/v1.slim
- app/views/templates/invoices/v2.slim
- app/views/templates/invoices/v3.slim
- app/views/templates/invoices/v3/charge.slim
- app/views/templates/invoices/v3/one_off.slim
- app/views/templates/invoices/v4.slim
- app/views/templates/invoices/v4/charge.slim
- app/views/templates/invoices/v4/one_off.slim
This PR modifies all the invoice/credit note templates so that they call `customer.display_name` method that handles the logic of what's displayed.
> feat(customer-type): Replace customer name with display_name in templates

- app/services/payment_provider_customers/gocardless_service.rb
- spec/services/payment_provider_customers/gocardless_service_spec.rb
We currently only create GoCardless customers with a limited set of details. However, there is a need to ensure that **company name**, **first name**, and **last name** are included when available. 
the additional customer attributes to GoCardless, specifically:
- `given_name`: If the customer's first name is present, it will be sent.
- `family_name`: If the customer's last name is present, it will be sent.
> feat(customer_type): Gocardless add firstname and lastname

- app/services/integrations/aggregator/contacts/payloads/netsuite.rb
- spec/services/integrations/aggregator/contacts/create_service_spec.rb
- spec/services/integrations/aggregator/contacts/payloads/netsuite_spec.rb
- spec/services/integrations/aggregator/contacts/update_service_spec.rb
In this PR we're adding the new fields: `lastname`, `firstname` and `isperson` to both create and update netsuite payloads.
> feat(customer-type): Update netsuite payload with new fields

- app/models/invoice.rb
- app/models/subscription.rb
- app/services/fees/create_true_up_service.rb
- app/services/invoices/create_invoice_subscription_service.rb
- spec/scenarios/invoices/invoices_spec.rb
- spec/services/billable_metrics/breakdown/sum_service_spec.rb
- spec/services/invoices/calculate_fees_service_spec.rb
- spec/services/subscriptions/dates/monthly_service_spec.rb
- spec/services/subscriptions/dates/quarterly_service_spec.rb
- spec/services/subscriptions/dates/weekly_service_spec.rb
- spec/services/subscriptions/dates/yearly_service_spec.rb
Some termination invoices failed to refresh or are generated with the wrong boundaries.
This is related to a small mismatch with the time comparison when looking if the subscription was terminated before the invoice timestamp.
This PR fixes the `subscription#terminated_at?` comparison so that it always compare time with the second precision, to avoid side effects related to rounding when persisting `ActiveRecord` objects.
A lot of `DateTime` objects are also converted into proper `Time.zone` to fix potential issues around time management as DateTime should not be used in Lago's context (see https://docs.datadoghq.com/code_analysis/static_analysis_rules/ruby-best-practices/no-datetime/)
> fix(subscription): Make sure terminated invoice always comes with the right boundaries

- app/models/customer.rb
- app/services/integrations/aggregator/contacts/payloads/anrok.rb
- app/services/integrations/aggregator/contacts/payloads/base_payload.rb
- spec/models/customer_spec.rb
- spec/services/integrations/aggregator/contacts/create_service_spec.rb
- spec/services/integrations/aggregator/contacts/payloads/anrok_spec.rb
- spec/services/integrations/aggregator/contacts/payloads/factory_spec.rb
- spec/services/integrations/aggregator/contacts/payloads/xero_spec.rb
- spec/services/integrations/aggregator/contacts/update_service_spec.rb
In this PR we're adding the new fields: to both create and update anrok and xero payloads.
> feat(customer-type): Update anrok and xero payloads with new fields

- app/graphql/types/customers/create_customer_input.rb
- app/graphql/types/customers/finalize_zero_amount_invoice_enum.rb
- app/graphql/types/customers/object.rb
- app/graphql/types/customers/update_customer_input.rb
- app/graphql/types/invoices/status_type_enum.rb
- app/graphql/types/organizations/current_organization_type.rb
- app/graphql/types/organizations/update_organization_input.rb
- app/services/customers/update_service.rb
- app/services/invoices/advance_charges_service.rb
- app/services/invoices/create_one_off_service.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- app/services/invoices/refresh_draft_and_finalize_service.rb
- app/services/invoices/subscription_service.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/customers/create_spec.rb
- spec/graphql/mutations/customers/update_spec.rb
- spec/graphql/mutations/organizations/update_spec.rb
- spec/graphql/types/customers/create_customer_input_spec.rb
- spec/graphql/types/customers/object_spec.rb
- spec/graphql/types/organizations/current_organization_type_spec.rb
- spec/graphql/types/organizations/update_organization_input_spec.rb
This PR introduces a new field, finalize_zero_amount_invoice, to the Customer-related GraphQL types and input objects, as well as to the organization settings. This field is an enum type that provides options for handling invoices with a zero total amount. The enhancement allows users to specify how zero-amount invoices should be managed at both the organization and customer levels
its to enable what we did on this pr but on the frontend https://github.com/getlago/lago-api/pull/2462
> Feat(invoice): Add finalize zero invoice to GraphQL

- app/graphql/resolvers/analytics/gross_revenues_resolver.rb
- schema.graphql
- schema.json
The goal of this change is to not setting `months: 12` each time we're fetching gross revenues from graphql.
> misc: Remove months restriction from gross revenues

- app/services/payment_provider_customers/stripe_service.rb
- spec/services/payment_provider_customers/stripe_service_spec.rb
In this PR we're adding the new fields: `lastname`, `firstname` to both create and update stripe payloads when the name on the customer is not defined.
> feat(customer-type):  Update stripe customer name with new fields

- app/models/credit_note.rb
- app/models/credit_note/applied_tax.rb
- db/migrate/20240910093646_change_tax_id_null_on_credit_note_applied_taxes.rb
- db/migrate/20240910111203_update_indexes_for_credit_notes_taxes.rb
- db/schema.rb
- spec/models/credit_note/applied_tax_spec.rb
- spec/models/credit_note_spec.rb
- spec/models/credit_spec.rb
We need to adjust credit_note and credit_note::applied_tax to reflect the changes in processing taxes:
- applied_tax might not belong to a stored in lago tax, so tax_id becomes optional,
- during reporting we might receive some errors, so credit_note can have many :error_details
> Feat: anrok <> credit_notes model changes

- app/jobs/integrations/aggregator/credit_notes/create_job.rb
- app/jobs/integrations/aggregator/fetch_items_job.rb
- app/jobs/integrations/aggregator/fetch_tax_items_job.rb
- app/jobs/integrations/aggregator/invoices/create_job.rb
- app/jobs/integrations/aggregator/payments/create_job.rb
- app/jobs/integrations/aggregator/perform_sync_job.rb
- app/jobs/integrations/aggregator/sales_orders/create_job.rb
- app/jobs/integrations/aggregator/send_restlet_endpoint_job.rb
- app/services/integrations/aggregator/base_service.rb
- app/services/integrations/aggregator/contacts/create_service.rb
- app/services/integrations/aggregator/contacts/update_service.rb
- app/services/integrations/aggregator/credit_notes/create_service.rb
- app/services/integrations/aggregator/invoices/create_service.rb
- app/services/integrations/aggregator/payments/create_service.rb
- app/services/integrations/aggregator/request_limit_error.rb
- app/services/integrations/aggregator/sales_orders/create_service.rb
- app/services/integrations/aggregator/taxes/invoices/create_draft_service.rb
- app/services/integrations/aggregator/taxes/invoices/create_service.rb
- app/services/integrations/aggregator/taxes/invoices/negate_service.rb
- app/services/integrations/aggregator/taxes/invoices/void_service.rb
Many dead jobs are raised by integration with an `SSS_REQUEST_LIMIT_EXCEEDED` error code.
Theses jobs should be automatically retried without ending up in the dead queue. 
This PR adds the logic to dig in the error message of integration response looking for the error code. When this error code is `SSS_REQUEST_LIMIT_EXCEEDED` it now raises a new `RequestLimitError` and related jobs are now able to reprocess up to 10 times
> fix(integration): Add more auto retries for reuqest limit errors

- app/services/invoices/advance_charges_service.rb
- spec/services/invoices/advance_charges_service_spec.rb
This check returns true if the invoice is nil, this is not intended.
> bug - Fix check for invoice.closed? in `Invoices::AdvanceChargesService`

- app/services/integrations/aggregator/taxes/credit_notes/create_service.rb
- app/services/integrations/aggregator/taxes/credit_notes/payload.rb
- app/services/integrations/aggregator/taxes/invoices/base_service.rb
- app/services/integrations/aggregator/taxes/invoices/create_service.rb
- spec/services/integrations/aggregator/taxes/credit_notes/create_service_spec.rb
- spec/services/integrations/aggregator/taxes/credit_notes/payload_spec.rb
Currently Lago is implementing integration with tax provider Anrok
This PR adds base service which sends credit note to the Anrok and creates transaction there.
> feat (tax-integrations): support endpoint for reporting credit notes in tax provider

- app/services/invoices/subscription_service.rb
This PR is fixing a regression recently introduced by the external tax management feature. A test was added to handle `tax_error` and was testing a specific error code on a service failure, but not all `BaseService::FailedResult` are responding to the `error` method
> fix(invoice): avoid failure on error not related to taxes

- app/services/customer_portal/generate_url_service.rb
- spec/requests/api/v1/customers_controller_spec.rb
- spec/services/customer_portal/generate_url_service_spec.rb
👉  [https://getlago.canny.io/feature-requests/p/{{FEATURE_SLUG}}](https://getlago.canny.io/feature-requests/p/add-features-to-the-customer-portal)
The goal of this PR is to make accessible to all our users (free and premium) the customer portal URL.
> feat(customer_portal): Remove premium restriction

- app/services/fees/one_off_service.rb
- spec/services/fees/one_off_service_spec.rb
- spec/services/invoices/create_one_off_service_spec.rb
When creating one off invoice and applying taxes on fee, we need to save fee, otherwise calculated values on fees are set, but not saved
> Fix: save fees with taxes_rate when creating one off invoice

- app/services/integrations/aggregator/contacts/payloads/base_payload.rb
- spec/services/integrations/aggregator/contacts/payloads/xero_spec.rb
We should not send empty firstnme and lastname to Xero, because in that case a contact (instead of a customer) is created.
If we don't send those empty attributes at all a customer is created which is the expected behaviour.
> fix(customer-type): Do not add empty firstname and lastname to xero payload

- app/jobs/credit_notes/provider_taxes/report_job.rb
- app/services/credit_notes/provider_taxes/report_service.rb
- spec/factories/credit_notes.rb
- spec/jobs/credit_notes/provider_taxes/report_job_spec.rb
- spec/services/credit_notes/provider_taxes/report_service_spec.rb
Currently Lago is working on integration with tax provider Anrok.
This PR covers sending credit notes to the tax provider and handling tax provider errors
> feat(tax-integration): add logic for reporting credit note to the tax provider

- app/models/credit_note_item.rb
- app/services/credit_notes/apply_taxes_service.rb
- spec/factories/fee_applied_taxes.rb
- spec/factories/invoice_applied_taxes.rb
- spec/mailers/payment_request_mailer_spec.rb
- spec/models/credit_spec.rb
- spec/services/credit_notes/apply_taxes_service_spec.rb
- spec/services/credit_notes/create_from_progressive_billing_invoice_spec.rb
- spec/services/credit_notes/create_from_termination_spec.rb
- spec/services/credit_notes/create_service_spec.rb
- spec/services/credit_notes/estimate_service_spec.rb
- spec/services/credit_notes/refresh_draft_service_spec.rb
**Context**
When we apply taxes on credit_notes, we're applying taxes that are stored for invoice - Invoice::AppliedTax. (and then we select taxes applied on fees, related to the credit_note_items)
Previous taxes implementation suggested that we should have a tax, saved in the db, so when iterating through taxes we were using tax.id, but currently taxes received from tax provider don't have a corresponding tax in the db, but we have tax_code, identifying the tax. the same is with stored in the db taxes: within the organization the tax_code will not be repeated, so if we start looking for taxes by tax_code instead of tax.id, we won't break existing logic and will adapt it to the new applied taxes that do not have taxes, stored in the db.
**What was done:**
Updated algorythm of searching …
> Feat(anrok<>credit_notes) refactor CreditNotes::AppliedTax to search taxes by tax_code

- app/jobs/bill_subscription_job.rb
- app/jobs/fees/create_pay_in_advance_job.rb
- app/jobs/invoices/create_pay_in_advance_charge_job.rb
- app/jobs/invoices/finalize_all_job.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- app/services/invoices/refresh_draft_and_finalize_service.rb
- app/services/invoices/refresh_draft_service.rb
- app/services/lifetime_usages/recalculate_and_check_service.rb
Error when not raised anymore by the `BillSubscrpitionJob`
The error happens because `[]` is `true`
> fix(subscription): fix tax error digging in all the places

- app/services/subscriptions/dates_service.rb
- spec/models/invoice_spec.rb
- spec/scenarios/subscriptions/terminate_ended_spec.rb
- spec/services/subscriptions/dates/monthly_service_spec.rb
- spec/services/subscriptions/dates/quarterly_service_spec.rb
- spec/services/subscriptions/dates/weekly_service_spec.rb
- spec/services/subscriptions/dates/yearly_service_spec.rb
Invoice for subscription termination are stuck in a `generating` status  when the subscription is attached to a next subscription with `pending` status.
NOTE: A `terminated` subscription should never be attached to a pending subscription, as next possible status should be either, `active` or `canceled`. The initial issue seems to be related to a race condition with multiple simultaneous upgrades and downgrades.
This PR does not fixes the initial issue but it makes sure that the `Subscriptions::DatesService#to_datetime` cannot returns a date before the start date of the subscription
> fix(subscription): Fix generating invoice with pending downgrade

- app/models/integrations/base_integration.rb
- app/models/integrations/hubspot_integration.rb
- app/models/organization.rb
- schema.graphql
- schema.json
- spec/factories/integrations.rb
- spec/models/integrations/base_integration_spec.rb
- spec/models/integrations/hubspot_integration_spec.rb
- spec/models/organization_spec.rb
Integration with HubSpot to import customers, subscriptions and invoices.
Add `HubspotIntegration` model and modify existing models where necessary to support hubspot.
> feat(hubspot): Add hubspot integration models

- .rubocop.yml
- Gemfile
- app/services/subscriptions/billing_service.rb
- lib/cops/service_call_cop.rb
- spec/cop_helper.rb
- spec/lib/cops/service_call_cop_spec.rb
We've built several subclasses of BaseService that don't adhere to the common pattern of having an `initialize` method with arguments and a `call` method without arguments. In an effort to standardize this pattern, a rubocop is added that validates that the call method definition on subclasses of BaseService does not have any arguments.
> misc(cleanup) Fix billing service call & introduce rubocop ensuring code consistency

- app/models/organization.rb
- app/services/payment_requests/create_service.rb
- schema.graphql
- schema.json
- spec/models/organization_spec.rb
- spec/services/payment_requests/create_service_spec.rb
The goal of this PR is to remove the dunning feature from the premium addon features.
> feat(dunning): Remove dunning feature from premium addon

- app/jobs/integrations/aggregator/send_private_app_token_job.rb
- app/services/integrations/aggregator/base_service.rb
- app/services/integrations/aggregator/send_private_app_token_service.rb
- app/services/integrations/hubspot/create_service.rb
- app/services/integrations/hubspot/update_service.rb
- spec/jobs/integrations/aggregator/send_private_app_token_job_spec.rb
- spec/services/integrations/aggregator/send_private_app_token_service_spec.rb
- spec/services/integrations/hubspot/create_service_spec.rb
- spec/services/integrations/hubspot/update_service_spec.rb
Integration with HubSpot to import customers, subscriptions and invoices.
Add `Hubspot::CreateService` and `Hubspot::UpdateService`  services and modify existing ones where necessary to support hubspot.
> feat: add hubspot connection services

- app/models/event.rb
- db/migrate/20240917144243_add_precise_total_amount_cents_to_event.rb
- db/migrate/20240917145042_add_index_on_precise_total_amount_cents.rb
- db/schema.rb
AI, CPaaS and Fintech customers can apply a price to a unit that fluctuates over time. Currently Lago does not support this usecase.
Adds `precise_total_amount_cents` to Event. Includes an index similar to the one added recently for quick calculations
> feat(DynamicPricing) - Add precise_total_amount_cents to Event

- app/models/charge.rb
Some conditions related to group properties remain in the `Charge` model validation.
Since `group_properties` are not used in production anymore, we should remove the related logic from the code base 
This PR updates the `Charge` model to remove the relation with the `group_properties` and the related charge model validation rules
> misc(group): Remove legacy group_properties validation in charge

- app/services/integrations/aggregator/base_payload.rb
- app/services/integrations/aggregator/credit_notes/create_service.rb
- app/services/integrations/aggregator/credit_notes/payloads/base_payload.rb
- app/services/integrations/aggregator/credit_notes/payloads/netsuite.rb
- app/services/integrations/aggregator/invoices/create_service.rb
- app/services/integrations/aggregator/invoices/payloads/base_payload.rb
- app/services/integrations/aggregator/invoices/payloads/netsuite.rb
- spec/services/integrations/aggregator/credit_notes/create_service_spec.rb
- spec/services/integrations/aggregator/invoices/create_service_spec.rb
For invalid payload due to incomplete configuration, we raise error (500) instead of silently notifying users via webhooks.
This PR covers described scenario
> fix (accounting-integrations): send webhook for incomplete payload

- app/models/invoice.rb
- app/views/templates/invoices/v1.slim
- app/views/templates/invoices/v2.slim
- app/views/templates/invoices/v3.slim
- app/views/templates/invoices/v3/charge.slim
- app/views/templates/invoices/v3/one_off.slim
- app/views/templates/invoices/v4.slim
- app/views/templates/invoices/v4/charge.slim
- app/views/templates/invoices/v4/one_off.slim
- config/locales/de/invoice.yml
- config/locales/en/invoice.yml
- config/locales/es/invoice.yml
- config/locales/fr/invoice.yml
- config/locales/it/invoice.yml
- config/locales/nb/invoice.yml
- config/locales/sv/invoice.yml
- spec/models/invoice_spec.rb
In some countries, invoices must include specific information when taxes are included. One of these obligations is to display `Tax invoice` in the header of the document, instead of `Invoice`.
This PR handles described use-case. Currently we are handling only following country codes: `AU`, `AE`, `NZ` and `ID`.
> feat(tax-invoices): add required invoice title for some countries

- db/migrate/20240920084727_change_wallet_transactions_metadata_default.rb
- db/migrate/20240920091133_change_recurring_transaction_rules_transaction_metadata_default.rb
- db/schema.rb
- spec/services/wallets/create_interval_wallet_transactions_service_spec.rb
- spec/services/wallets/threshold_top_up_service_spec.rb
All api clients expect metadata to be returned as array (and when records are created, it's also an array), but if we create WalletTransaction without metadata, it takes default value of `{}` which then breaks api-clients
> Fix: change default value for WalletTransaction metadata

- app/models/integration_collection_mappings/netsuite_collection_mapping.rb
- spec/factories/integration_collection_mappings.rb
- spec/models/integration_collection_mappings/netsuite_collection_mapping_spec.rb
When Anrok is connected to NetSuite, it’s impossible for Lago to override the tax details. Thus, Lago always sends the amount excluding tax to NetSuite, creating some discrepancies.
Add new tax-related attributes to `NetsuiteCollectionMapping` model.
> feat(netsuite-taxes): Add new model attributes

- app/services/invoices/subscription_service.rb
- spec/services/invoices/subscription_service_spec.rb
**context**
when assigning status before calculating fees, the total of the invoice is always 0, so the `TransitionToFinalStatusService` was always returning `:closed`
> Fix invoice status when choosing final status for the invoice

- app/graphql/mutations/integration_collection_mappings/create.rb
- app/graphql/mutations/integrations/hubspot/create.rb
- app/services/integration_collection_mappings/create_service.rb
- app/services/integration_collection_mappings/update_service.rb
- spec/services/integration_collection_mappings/create_service_spec.rb
- spec/services/integration_collection_mappings/update_service_spec.rb
When Anrok is connected to NetSuite, it’s impossible for Lago to override the tax details. Thus, Lago always sends the amount excluding tax to NetSuite, creating some discrepancies.
Add new tax-related attributes to collection mapping services.
> feat(netsuite-taxes): Add new tax attributes to collection mapping services

- app/controllers/api/v1/events_controller.rb
- app/serializers/v1/event_serializer.rb
- app/services/events/create_batch_service.rb
- app/services/events/create_service.rb
- spec/requests/api/v1/events_controller_spec.rb
- spec/serializers/v1/event_serializer_spec.rb
- spec/services/events/create_batch_service_spec.rb
- spec/services/events/create_service_spec.rb
AI, CPaaS and Fintech customers can apply a price to a unit that fluctuates over time. Currently Lago does not support this usecase.
This PR updates `POST /api/v1/events` and `POST /api/v1/batch_events` to accept the new `precise_total_amount_cents` field on event model.
> feat(DynamicPricing): Accept precise_total_amount_cents when creating an event

- config/application.rb
This PR is related to https://github.com/getlago/lago-doc/pull/210
A mismatch was reported by a user between the environment variable defined on https://doc.getlago.com/guide/self-hosted/docker and the one used in the API application.
This PR makes sure that the API application is using the environment variables defined in the documentation without breaking the setup for users using the docker-compose.yml file from the main Lago repository
> misc: Allign env variables with documentation

- app/models/credit_note_item.rb
- app/services/credit_notes/create_service.rb
- app/services/integrations/aggregator/taxes/credit_notes/payload.rb
- spec/factories/customers.rb
- spec/models/credit_note_item_spec.rb
- spec/services/credit_notes/create_service_spec.rb
- spec/services/integrations/aggregator/taxes/credit_notes/payload_spec.rb
When creating a credit note we should schedule a job to report credit note creation to tax provider is customer has tax_provider set up;
When reporting credit note, the reported amount should be taken from the items amounts
> Feat(anrok): call report credit note job when creating a credit note

- app/services/billable_metrics/aggregations/custom_service.rb
- app/services/events/stores/clickhouse/unique_count_query.rb
- app/services/events/stores/clickhouse/weighted_sum_query.rb
- app/services/events/stores/clickhouse_store.rb
- app/services/events/stores/postgres/unique_count_query.rb
- app/services/events/stores/postgres/weighted_sum_query.rb
- app/services/events/stores/postgres_store.rb
When running aggregation for billable metrics we are (almost) always ordering events by the `timestamp` property.
In most cases this order is not necessary since the end-result will not be dependent of the event order (sum, count, max...) and the order clause might slow down the queries.
This PR updates all events-related aggregation queries to get rid of the order and keep it only when required. This should allow for a small gain in aggregation performances.
> misc(event): Remove ordering of event queries when not required

- app/graphql/types/integration_collection_mappings/create_input.rb
- app/graphql/types/integration_collection_mappings/object.rb
- app/graphql/types/integration_collection_mappings/update_input.rb
- schema.graphql
- schema.json
- spec/graphql/types/integration_collection_mappings/create_input_spec.rb
- spec/graphql/types/integration_collection_mappings/object_spec.rb
- spec/graphql/types/integration_collection_mappings/update_input_spec.rb
When Anrok is connected to NetSuite, it’s impossible for Lago to override the tax details. Thus, Lago always sends the amount excluding tax to NetSuite, creating some discrepancies.
Add new tax-related attributes to GraphQL types and inputs.
> feat(netsuite-taxes): Add new tax attributes to GraphQL types and inputs

- app/graphql/resolvers/customer_portal/subscriptions_resolver.rb
- app/graphql/types/query_type.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/customer_portal/subscriptions_resolver_spec.rb
The goal of this PR is to return subscriptions from the customer portal.
> feat(dunning): Add subscriptions resolver to customer portal

- app/graphql/types/subscriptions/object.rb
- app/serializers/v1/subscription_serializer.rb
- app/services/subscriptions/dates_service.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/customer_portal/subscriptions_resolver_spec.rb
- spec/graphql/types/subscriptions/object_spec.rb
- spec/serializers/v1/subscription_serializer_spec.rb
- spec/services/subscriptions/dates/monthly_service_spec.rb
- spec/services/subscriptions/dates/quarterly_service_spec.rb
- spec/services/subscriptions/dates/weekly_service_spec.rb
- spec/services/subscriptions/dates/yearly_service_spec.rb
The goal of this PR is to add current billing dates to subscription object.
> feat(customer-portal): Add current billing dates to subscription object

- app/controllers/api/v1/events_controller.rb
- app/queries/events_query.rb
- config/routes.rb
- spec/queries/events_query_spec.rb
- spec/requests/api/v1/events_controller_spec.rb
Hi, Ruby newbie here. This is my first Ruby and Lago contribution so, if there is any suggestion, I'd be much appreciated!
👉  https://getlago.canny.io/feature-requests/p/retrieve-and-filter-events
Currently, REST API does not provide the endpoint to list all events (as in the Developer -> Events page). This pull request aim to expose the event list to the REST API to let the user retrieve and filter events.
This pull request add supports for:  
- Adding `GET /api/v1/events` endpoint
- Filtering events by `code`, `external_subscription_id`, `timestamp_from`, and `timestamp_to`
I'm also planning to checkout the front-end side to add these kinds of filter into the UI later as well.
> feat(event): Add event list API

- app/queries/credit_notes_query.rb
we show credit notes on invoice page and on all credit notes page
at invoice page we sort them by `created_at` of type `date_time`
at the all credit notes page we sort them by `issuing_date` of type `date`
As result they are sorted slightly differently and they are not sorted accurately on the all credit notes page
Unified ways we sort credit notes, using `:created_at` for sorting
> Fix: credit notes sorting

- app/models/invoice.rb
- app/views/templates/invoices/v3/charge.slim
- app/views/templates/invoices/v4/charge.slim
- config/locales/de/invoice.yml
- config/locales/en/invoice.yml
- config/locales/es/invoice.yml
- config/locales/fr/invoice.yml
- config/locales/it/invoice.yml
- config/locales/nb/invoice.yml
- config/locales/sv/invoice.yml
When an invoice is generated for **paid_in_advance fees** (invoice_type: `advance_charges`), the title of the invoice currently displays "Invoice" and the last line of the PDF shows "Total due." However, since this invoice is already paid, this is misleading for the users.
The goal is to provide more accurate labeling in the invoice title and the total section.
- For invoices of type `advance_charges`, the title should now display "Paid invoice" instead of "Invoice."   
- For these invoices, instead of displaying "Total due," we now show "Already paid."
- on the due date -> now appears already paid without date 
- Conditional logic has been added to check if the invoice type is `advance_charges` and select the correct label
> feat: added translations

- app/graphql/resolvers/customer_portal/customers/usage_resolver.rb
- app/graphql/resolvers/customers/usage_resolver.rb
- app/graphql/types/query_type.rb
- app/services/invoices/customer_usage_service.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/customer_portal/customers/usage_resolver_spec.rb
- spec/services/invoices/customer_usage_service_spec.rb
The goal of this PR is to return customer usage from the customer portal.
> feat(customer_portal): Add usage resolver to customer portal

- app/graphql/types/invoices/applied_taxes/object.rb
- app/models/fee.rb
- app/models/invoice/applied_tax.rb
- app/services/credit_notes/apply_taxes_service.rb
- app/services/fees/apply_provider_taxes_service.rb
- app/services/invoices/apply_provider_taxes_service.rb
- app/views/templates/invoices/v4/_progressive_billing_details.slim
- app/views/templates/invoices/v4/_subscription_details.slim
- app/views/templates/invoices/v4/_subscriptions_summary.slim
- app/views/templates/invoices/v4/charge.slim
- app/views/templates/invoices/v4/one_off.slim
- db/migrate/20240924114730_add_taxes_deduction_rate_fields_to_fees_and_applied_taxes.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/models/invoice/applied_tax_spec.rb
- spec/services/fees/apply_provider_taxes_service_spec.rb
- spec/services/fees/one_off_service_spec.rb
- spec/services/invoices/apply_provider_taxes_service_spec.rb
- spec/services/invoices/create_one_off_service_spec.rb
- spec/services/invoices/retry_service_spec.rb
Lago recently launched integration with tax provider Anrok.
In some scenarios tax is not applied on the sum of all fees (with coupon applied).
Instead, there are scenarios where tax base is less than the sum of the fees (with coupon applied) and it depends mostly on the country (e.g. Texas in the USA).
This PR is covering described case. `tax_base_rate` is included in tax logic and also used to display correct base in the UI/PDF.
> feat(tax-integrations): Cover tax deduction case for tax integrations

- lib/lago_eu_vat/lago_eu_vat/eu_vat_rates.json
Update Finnish VAT to the most recent 25.5%
> fix(vat-rates): Update Finnish VAT

- app/controllers/api/v1/add_ons_controller.rb
- app/controllers/api/v1/billable_metrics_controller.rb
- app/controllers/api/v1/coupons_controller.rb
- app/graphql/mutations/add_ons/create.rb
- app/graphql/mutations/billable_metrics/create.rb
- app/graphql/mutations/coupons/create.rb
- app/graphql/mutations/coupons/terminate.rb
- app/jobs/clock/terminate_coupons_job.rb
- app/services/add_ons/create_service.rb
- app/services/base_service.rb
- app/services/billable_metrics/create_service.rb
- app/services/coupons/create_service.rb
- app/services/coupons/terminate_service.rb
- spec/services/add_ons/create_service_spec.rb
- spec/services/billable_metrics/create_service_spec.rb
- spec/services/coupons/create_service_spec.rb
- spec/services/coupons/terminate_service_spec.rb
Some services inherinting from the `BaseService` are not using the `SERVCE_CLASS.call` pattern. They are mostly old services that were created before the introduction of the pattern in the project.
To increase consistency in the code base, this PR turns some old services to the pattern.
The impacted services are:
- `AddOns::CreateService`
- `BillableMetrics::CreateService`
- `Coupons::CreateService`
- `AddOns::CreateService`
More refactor will follow as other services have still to be converted.
> misc: Refact some services to the call pattern

- app/graphql/resolvers/customer_portal/subscription_resolver.rb
- app/graphql/types/query_type.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/customer_portal/subscription_resolver_spec.rb
The goal of this PR is to return a specific subscription from the customer portal.
> feat(customer-portal): Add Subscription graphql resolver

- app/graphql/resolvers/customer_portal/organization_resolver.rb
- app/graphql/types/customer_portal/organizations/object.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/customer_portal/organization_resolver_spec.rb
- spec/graphql/types/customer_portal/organizations/object_spec.rb
The goal of this PR is to add premium integrations to the organization's customer portal graphql type.
> feat(customer-portal): Extract organization type and add premium integrations

- app/models/invoice.rb
- app/services/invoices/calculate_fees_service.rb
- app/services/invoices/subscription_service.rb
- spec/services/invoices/subscription_service_spec.rb
**context** 
Before we were setting invoice status to `finalized` or `draft` before calculating fees (because before calculating fees we don't know if it will be 0-invoice or no, and as result we don't know if it will be `:finalized` or `:closed`)
but inside calculate_fees_service we save the invoice, so if it's in `finalized` status we would generate number for this invoice, which is not needed for `closed` invoices
as result we should set invoice to `finalized` or to `closed` after we calculated fees.
so the definition if the process is finalization or  drafting of the invoice should be done not only by status, but also by the context.
**what was done** 
- instead of setting invoice status before calculating fees, set up context
- define if the process is finalization for applying …
> Fix: closed invoices with generated number

- app/jobs/invoices/create_pay_in_advance_charge_job.rb
- app/models/charge.rb
- app/services/charges/apply_pay_in_advance_charge_model_service.rb
- app/services/charges/charge_models/percentage_service.rb
- app/services/fees/create_pay_in_advance_service.rb
- app/views/templates/invoices/v4/_charge_percentage.slim
- app/views/templates/invoices/v4/charge.slim
- spec/models/charge_spec.rb
- spec/scenarios/pay_in_advance_charges_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
We needed to enhance representation of price for percentage pay in advance charge. Initial request was to simply show only percentage if only percentage is set, but then the request grew up to show the whole amount breakdown as we have in subscription invoices
- added amount_details calculation for fee as we have for fee aggregation (subscription invoices)
- amount_detail is calculated only for percentage invoices
- added fix for free_events calculation: before if we had a plan that allows 3 free events, we received two and generate the invoice, in the invoice it will say that there are 0 free events. Now it will say 2 free_events
> Feat: Add price breakdown for pay in advance percentage charge

- app/models/payment_provider_customers/adyen_customer.rb
- app/models/payment_provider_customers/base_customer.rb
- app/models/payment_provider_customers/gocardless_customer.rb
- app/models/payment_provider_customers/stripe_customer.rb
- app/models/payment_providers/adyen_provider.rb
- app/models/payment_providers/base_provider.rb
- app/models/payment_providers/gocardless_provider.rb
- app/models/payment_providers/stripe_provider.rb
- app/services/customers/update_service.rb
- app/services/payment_provider_customers/stripe_service.rb
- app/services/payment_providers/adyen_service.rb
- app/services/payment_providers/base_service.rb
- app/services/payment_providers/destroy_service.rb
- app/services/payment_providers/gocardless_service.rb
- app/services/payment_providers/stripe_service.rb
- db/migrate/20230202110407_add_index_to_payment_provider_customers.rb
- db/migrate/20241001105523_add_deleted_at_to_payment_providers.rb
- db/migrate/20241001112117_add_deleted_at_to_payment_provider_customers.rb
- db/schema.rb
- lib/tasks/stripe.rake
- spec/models/payment_providers/base_provider_spec.rb
- spec/services/payment_provider_customers/stripe_service_spec.rb
- spec/services/payment_providers/adyen_service_spec.rb
- spec/services/payment_providers/gocardless_service_spec.rb
- spec/services/payment_providers/stripe_service_spec.rb
**How to reproduce issue?**
1. Create a payment provider integration (tested with stripe but probably happens with all of them)
2. Assign it to a customer
3. Update the integration code in the settings OR delete the integration
**Expected behaviour**
The payment provider value attached to my customer should wither be updated, if integration's code is updated,  or removed if integration's code have been removed.
This PR fixes all payment provider services that handle the code update.
It also adds soft-deleting of:
- payment providers
- payment provider customers
So there are also 2 new migrations that add `deleted_at` column and drop and re-create indices because of that.
> fix(payment-provider-code): Fix payment provider code change

- app/services/webhooks/send_http_service.rb
This PR makes sure that webhook deliveries failing with an `Errno::EHOSTUNREACH` does not end-up in the dead job queue but are marked as `failed` and automatically reprocessed.
> fix(webhook): Handle Errno::EHOSTUNREACH

- app/jobs/invoices/refresh_draft_job.rb
- spec/jobs/invoices/refresh_draft_job_spec.rb
When lots of RefreshDraftJobs are enqueued, we might not be able to process them all in an hour. This code change tries to make sure that we'd not enqueue further jobs for 6 hours.
> Don't execute RefreshDraft service when the ready_to_be_refreshed is not true

- app/controllers/api/v1/plans_controller.rb
- app/graphql/mutations/invites/create.rb
- app/graphql/mutations/invites/revoke.rb
- app/graphql/mutations/plans/create.rb
- app/graphql/resolvers/customer_portal/customers/usage_resolver.rb
- app/graphql/resolvers/customers/usage_resolver.rb
- app/services/invites/create_service.rb
- app/services/invites/revoke_service.rb
- app/services/invoices/customer_usage_service.rb
- app/services/lifetime_usages/calculate_service.rb
- app/services/plans/create_service.rb
- app/services/wallets/balance/refresh_ongoing_service.rb
- spec/services/invites/create_service_spec.rb
- spec/services/invites/revoke_service_spec.rb
- spec/services/invoices/customer_usage_service_spec.rb
- spec/services/plans/create_service_spec.rb
This PR follows https://github.com/getlago/lago-api/pull/2641 and https://github.com/getlago/lago-api/pull/2645 and keeps refactoring some old service to take advantage of the `call` pattern and to remove the `user` arguments used in `BaseService#initialize`. 
This PR:
- Turn the `Plans::CreateService#create` method into a proper `Plans::CreateService#call` one
- Remove the need for the `current_user` argument in `Invites::CreateService` and move the arguments for the `call` method to the `initializer`
- Refact `Invites::RevokeService` to take the `invite` as an argument instead if the `id` and `current_organization` and move the argument for the `call` method to the `initializer`
- Remove the `current_user` argument for the `Invoices::CustomerUsageService`
> misc: Refactor more pre-call era services

- app/services/integrations/aggregator/invoices/payloads/base_payload.rb
- app/services/integrations/aggregator/invoices/payloads/netsuite.rb
- spec/services/integrations/aggregator/invoices/payloads/base_payload_spec.rb
- spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
Netsuite raises an error when creating an invoice with 0 lines items (fees).
This PR fixes a situation where we're about to sync an invoice with empty line items array.
> fix(intergrations): Fix fees in invoices payload

- app/graphql/mutations/memberships/revoke.rb
- app/services/memberships/revoke_service.rb
- spec/graphql/mutations/memberships/revoke_spec.rb
- spec/services/memberships/revoke_service_spec.rb
Today it is possible the revoke a membership from any organization as long as you know the ID.
The `Mutations::Memberships::Revoke` is delegating the logic to `Memberships::RevokeService`, but this service is not checking that the membership is part of any organization (`Membership.find_by`)
This PR refactors the service to use the common `call` pattern.
It also update the mutation to require an Organization and lookup for the membership with a scope to the current organization.
> fix(membership): Ensure membership is in current organization when revoking

- app/graphql/types/customer_portal/customers/object.rb
- schema.graphql
- schema.json
- spec/graphql/types/customer_portal/customers/object_spec.rb
The goal of this PR is to add applicable timezone to the customer's customer portal graphql type.
> feat(customer-portal): Add applicable timezone to customer portal customer

- app/graphql/mutations/payment_providers/destroy.rb
- app/services/base_service.rb
- app/services/payment_providers/destroy_service.rb
- spec/graphql/mutations/payment_providers/destroy_spec.rb
- spec/services/base_service_spec.rb
- spec/services/payment_providers/destroy_service_spec.rb
The `BaseService#initialize` method is expecting a first argument of type `User` that is then assigned to the created `result`. This argument is not used in any places (last references were removed in previous PRs) 
This PR simply removes this reference, and refactors the `::PaymentProviders::DestroyService` that was the last remaining service relying on it.
> misc: Remove the need for BaseService current user argument

- app/services/credit_notes/create_service.rb
- app/services/credit_notes/generate_service.rb
- app/services/invoices/refresh_draft_and_finalize_service.rb
- spec/services/credit_notes/create_service_spec.rb
- spec/services/credit_notes/generate_service_spec.rb
- spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
For credit notes, Lago does not automatically generate PDF files. The webhook `credit_note.generated` is only sent when an API request is made.
Expected behaviour: the credit note logic should be the same as the invoice logic.
This PR changes logic for generating credit notes and their webhook so that it's the same as invoices.
> fix(pdf): Fix credit note generating pdf and webhook

- app/models/credit_note.rb
- app/models/invoice.rb
- app/services/credit_notes/create_service.rb
- app/services/credit_notes/estimate_service.rb
- app/services/credit_notes/validate_item_service.rb
- app/services/credit_notes/validate_service.rb
- spec/models/credit_note_spec.rb
- spec/scenarios/credit_note_spec.rb
- spec/services/credit_notes/validate_item_service_spec.rb
- spec/support/scenarios_helper.rb
We have this issue that when we issue Invoice, we apply tax on sum of items,
but when we issue a credit note, we apply tax on each item separately.
as result, some values can be rounded in deffirent direction which result in not matching sum.
Example that our client had (all values are amount_cents):
```
Invoice 001
charge01 = 68_33
charge 02 = 68_33
charge03 = 57_50
charge04 = 85_00
```
if we apply 20% taxes on the sum of charges, we get:
```
(68_33 + 68_33 + 57_50 + 85_00) * 1.2 = 334_99,2
```
but because it is in cents, when issuing the invoice, the value is rounded to `334_99`
Next, when we create credit notes for this invoice, and we create a separate CN per each item:
```
CN01 = 68_33 * 1.2 = 8199.6 => 82_00
CN02 = 57_50 * 1.2 = 69_00
CN03 = 85_00 * 1.2 = 102_00
CN04 = 68_33 * 1.2 = …
```
> Fix: adjust tax precise amount when issuing credit notes

- app/models/wallet.rb
- app/services/wallets/balance/increase_service.rb
- db/migrate/20241008080209_add_lock_version_to_wallets.rb
- db/schema.rb
Recently, feature for updating wallet balance upon successful payment was introduced.
If multiple paid credits are issues, there is a chance that after successful payment processing we will receive all events from payment provider in the same request.
Multiple events will schedule multiple jobs for increasing wallet balance and each job is updating the same resource so there is a high chance of race condition.
This PR introduced optimistic locking approach with 1 additional retry if multiple processes are updating the same resource.
> fix (wallet-race-condition): Retry wallet update upon race condition

- app/models/customer.rb
- app/models/integration_customers/base_customer.rb
- app/models/integration_customers/hubspot_customer.rb
- app/serializers/v1/integration_customer_serializer.rb
- spec/factories/integration_customers.rb
- spec/models/customer_spec.rb
- spec/models/integration_customers/base_customer_spec.rb
- spec/models/integration_customers/hubspot_customer_spec.rb
- spec/serializers/v1/integration_customer_serializer_spec.rb
This PR adds models, associations and attributes needed for hubspot customers.
It also adds logic to the custoemr serializer so that it can return correct customer type.
> feat(hubspot): Add associations, attributes to customer models to support hubspot integration

- app/services/credit_notes/create_service.rb
Job for submitting credit note in tax provider should be called once DB transaction ends
> fix(credit-notes): submit credit note to tax provider after transaction ends

- app/graphql/types/customer_portal/customers/object.rb
- app/graphql/types/customer_portal/customers/update_input.rb
- app/graphql/types/customer_portal/wallets/object.rb
- app/services/customer_portal/customer_update_service.rb
- schema.graphql
- schema.json
- spec/graphql/mutations/customer_portal/update_customer_spec.rb
- spec/graphql/types/customer_portal/customers/object_spec.rb
- spec/graphql/types/customer_portal/customers/update_input_spec.rb
- spec/graphql/types/customer_portal/wallets/object_spec.rb
- spec/services/customer_portal/customer_update_service_spec.rb
👉 https://getlago.canny.io/feature-requests/p/add-features-to-the-customer-portal
The current customer portal already exposes some customer information. However, it is missing some important pieces of customer information. Also, we want to allow customer to edit their own billing information.
This change enable customers to update their customer type (individual/company) through the customer portal.
Also, adds `last_balance_sync_at` to CustomerPortal::Wallet:Object in order to render the last time wallet balance was synced in a tooltip.
And expose a `premium` field in `CustomerPortalCustomer` type.
> feat(cp-improve): Customer portal update customer's customer_type

- app/models/concerns/sequenced.rb
- app/models/invoice.rb
- app/services/invoices/add_on_service.rb
- app/services/invoices/advance_charges_service.rb
- app/services/invoices/create_one_off_service.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- app/services/invoices/finalize_open_credit_service.rb
- app/services/invoices/number_generation_service.rb
- app/services/invoices/paid_credit_service.rb
- app/services/invoices/progressive_billing_service.rb
- app/services/invoices/refresh_draft_and_finalize_service.rb
- app/services/invoices/retry_service.rb
- app/services/invoices/subscription_service.rb
- spec/models/invoice_spec.rb
- spec/services/invoices/number_generation_service_spec.rb
- spec/services/invoices/retry_service_spec.rb
Currently invoice numbering requires locking scope on invoices table.
This PR moves invoice numbering logic to the very end of the invoice generation process (outside DB transaction). With this approach, lock duration is decreased and it it less likely to face `SequenceError`
> misc: move invoice numbering outside DB transaction

- app/services/invoices/create_one_off_service.rb
- app/services/invoices/create_pay_in_advance_charge_service.rb
- app/services/invoices/progressive_billing_service.rb
- spec/services/invoices/create_one_off_service_spec.rb
- spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
- spec/services/invoices/progressive_billing_service_spec.rb
- spec/services/invoices/subscription_service_spec.rb
Recently one refactoring around invoice numbering was introduced.
This PR ensures that draft invoice number is attached when status is failed
> fix(invoice-numbering): cover draft invoice number when tax error

- app/models/dunning_campaign.rb
- app/models/dunning_campaign_threshold.rb
- app/models/organization.rb
- db/migrate/20241007083747_create_dunning_campaigns.rb
- db/migrate/20241007092701_create_dunning_campaign_thresholds.rb
- db/schema.rb
- spec/factories/dunning_campaign_thresholds.rb
- spec/factories/dunning_campaigns.rb
- spec/models/dunning_campaign_spec.rb
- spec/models/dunning_campaign_threshold_spec.rb
- spec/models/organization_spec.rb
👉  [https://getlago.canny.io/feature-requests/p/send-reminders-for-overdue-invoices](https://getlago.canny.io/feature-requests/p/send-reminders-for-overdue-invoices)
As a user, as part of the dunning process, I want to send email reminders to my customers when they have overdue invoices.
The goal of this PR is to setup the basic dunning entities:
- `DunningCampaign` 
- `DunningCampaignThreshold`
> feat(dunning): Add DunningCampaign and DunningCampaignThreshold

- app/services/invoices/advance_charges_service.rb
Currently if an invoice with paid in advance charges is terminated, there are edge cases where paid fees are not invoiced because of a time boundaries issues.
This change ensure all not already invoiced paid fees are included in a new invoice when the subscription is terminating ignoring time boundaries.
> fix: Generate invoice for paid instant charges on subscription termination

- app/models/wallet_transaction.rb
- db/migrate/20241010055733_add_reference_to_credit_note_from_wallet_transaction.rb
- db/migrate/20241011123148_add_foreign_key_constraint_to_credit_note_id_at_wallet_transaction.rb
- db/migrate/20241011123621_change_validate_on_foreign_key_from_wallet_transaction_to_credit_note.rb
- db/schema.rb
Now we don't allow creation of credit notes on prepaid credits. We want to implement this possibility. 
When credits will be issued, we'll be creating a voiding outbound wallet_transaction. Currently we're tracking the outbound wallet transactions. To support this behaviour we'll need to add credit_note_id to the wallet transaction
Added credit_note_id to wallet_transaction
> Feat: issue credit note on credit invoice - db change

- app/services/credit_notes/create_service.rb
Some `CreditNotes::GeneratePdfJob` have failed lately with the following error:
```
ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find CreditNote with 'id'=XXX
```
This PR makes sure that all jobs related to credit notes are performed after any database transaction.
> fix(credit_note): Make sure after create jobs are processed outside of DB transactions

- app/services/invoices/subscription_service.rb
This PR is related to `BillSubscriptionJob` dead jobs with the following error:
```
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_invoice_subscriptions_on_charges_from_and_to_datetime" DETAIL: Key (subscription_id, charges_from_datetime, charges_to_datetime)=(XXX, 2024-09-01 00:00:00, 2024-09-30 23:59:59.999999) already exists. 
```
This issue can appears when a lot of invoices are generated at the same time, for example on the first day of a month when a lot of calendar subscription have to be billed.
As the clock job is executed every hour and enqueues a job for all subscriptions that have to be billed on a particular day but filtering the ones that have been billed already, in some cases when the queue is full a billing job can wait for more than one …
> fix(invoice) Skip ActiveRecord::RecordNotUnique for periodic invoices

- app/services/credits/applied_prepaid_credit_service.rb
Some `SendWebhookJob` for wallet transaction creation have failed lately with the following error:
```
ActiveJob::DeserializationError 
Error while trying to deserialize arguments: Couldn't find WalletTransaction with 'id'=XXX
```
This PR makes sure that all jobs related to wallet transaction creation are performed after any database transaction.
> fix(wallet): Send wallet transaction webhooks outside of DB transactions

- app/services/integrations/aggregator/base_service.rb
This PR follows https://github.com/getlago/lago-api/pull/2570
It updates the way we check for the presence of the rate error limit code in the payload to avoid parsing the JSON body and be independent from the format of the response.
> fix(integration): Fix rate limit handling

- app/services/wallet_transactions/create_service.rb
- app/services/wallet_transactions/void_service.rb
- spec/services/wallet_transactions/create_service_spec.rb
- spec/services/wallet_transactions/void_service_spec.rb
This pull request includes several changes to the `wallet_transactions` services to standardize the handling of credit amounts and improve precision by using `BigDecimal` and flooring the values to five decimal places. 
* [`app/services/wallet_transactions/create_service.rb`](diffhunk://#diff-982c298415227695373911c5d4f1807aa1efe9ba65e962ab7f0065ac1edea794L27-R27): Modified `handle_paid_credits`, `handle_granted_credits`, and `handle_voided_credits` to use `BigDecimal` for credit amounts, flooring them to five decimal places. [[1]](diffhunk://#diff-982c298415227695373911c5d4f1807aa1efe9ba65e962ab7f0065ac1edea794L27-R27) [[2]](diffhunk://#diff-982c298415227695373911c5d4f1807aa1efe9ba65e962ab7f0065ac1edea794L36-R36) [[3]](diffhunk://#diff-982c298415227695373911c5d4f1807aa1efe9ba65e962ab7f006 …
> fix(wallet): Save wallet transaction using floor for credits

- app/jobs/wallets/refresh_ongoing_balance_job.rb
This pull request includes a small change to the `app/jobs/wallets/refresh_ongoing_balance_job.rb` file. The change adds a retry mechanism for the `RefreshOngoingBalanceJob` class to handle `ActiveRecord::StaleObjectError` with a polynomial backoff strategy.
* [`app/jobs/wallets/refresh_ongoing_balance_job.rb`](diffhunk://#diff-b9d74143d00aee0ddc9a3ae9d05b87e50bb09e2a1395eaf34ee96740bcc73724R9-R10): Added `retry_on ActiveRecord::StaleObjectError` with a polynomial backoff strategy and 3 attempts.
> misc: Retry RefreshOngoingBalanceJob if stale object

- app/services/events/stores/clickhouse/unique_count_query.rb
This pull request focuses on optimizing timestamp precision in the `unique_count_query.rb` file by adjusting the precision level in various SQL queries. The changes include modifying the `toDateTime64` function to use a precision of 3 instead of 5 across different methods.
Timestamp precision adjustments:
* [`app/services/events/stores/clickhouse/unique_count_query.rb`](diffhunk://#diff-15e04aaa1cc9a958e117e73b27e752ce967e85a43ce0dcb7f4ded58b44b9ff78L209-R209): Changed the precision in the `events_cte_sql` method to use `timestamp` directly instead of `toDateTime64(timestamp, 5, 'UTC')`.
* [`app/services/events/stores/clickhouse/unique_count_query.rb`](diffhunk://#diff-15e04aaa1cc9a958e117e73b27e752ce967e85a43ce0dcb7f4ded58b44b9ff78L229-R229): Updated the `grouped_events_cte_sql` method …
> fix(clickhouse): Fix timestamp precision

- app/models/charge.rb
- app/services/charges/override_service.rb
- db/migrate/20241015132635_add_parent_id_to_charges.rb
- db/schema.rb
- spec/services/charges/override_service_spec.rb
Currently, plan updates are not cascaded to the children plan / charges.
This PR adds basic pre-requirement for cascading charge changes.
Later, we will write migration that would set `parent_id` on all existing charge records
> feat (cascading): add DB changes for charge cascading

- app/config/permissions/definition.yml
- app/config/permissions/role-finance.yml
- app/config/permissions/role-manager.yml
- app/graphql/resolvers/dunning_campaigns_resolver.rb
- app/graphql/types/query_type.rb
- app/models/dunning_campaign.rb
- app/queries/dunning_campaigns_query.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/dunning_campaigns_resolver_spec.rb
- spec/queries/dunning_campaigns_query_spec.rb
This pull request introduces a new feature to manage and query dunning campaigns within an organization. The most important changes include adding new permissions, creating a resolver and query for dunning campaigns, and updating the GraphQL schema to support these queries.
* [`app/graphql/resolvers/dunning_campaigns_resolver.rb`](diffhunk://#diff-d45ebb2f5c75cc98d69a0d641723cff50a2a7034d18de7561d16ff45c71680c3R1-R38): Created a new resolver for querying dunning campaigns with appropriate permissions and arguments.
* [`app/graphql/types/query_type.rb`](diffhunk://#diff-f091357fe3bc9b42153dde4873030274dd9aa16c9cf86f689fee229ca9558b8cR35): Added `dunning_campaigns` field to the `QueryType` to use the new resolver.
* [`app/models/dunning_campaign.rb`](diffhunk://#diff-3b7eb2d6a06a5b47d979ac5e …
> feat(dunning): Add DunningCampaignsResolver

- app/services/credit_notes/refunds/gocardless_service.rb
This PR is a fix for `CreditNotes::Refunds::GocardlessCreateJob` failing with `GoCardlessPro::InvalidApiUsageError, One of your parameters was incorrectly typed`
In the [Gocardless API reference](https://developer.gocardless.com/api-reference#refunds-create-a-refund) the metadata field is defined like this:
> Key-value store of custom data. Up to 3 keys are permitted, with key names up to 50 characters and values up to 500 characters.
Today, we are sending `lago_customer_id`, `lago_credit_note_id`, `lago_invoice_id` and `reason` wich is more than 3...
Since the `lago_customer_id` is not used when receiving related webhooks this PR removes it from the metadatas so that we only send 3 keys.
> fix(gocarless): Refund metadata can contains 3 keys at max

- app/services/customers/create_service.rb
- spec/services/customers/create_service_spec.rb
Creation of customer via the REST API is failing if a nil value is provided for the `finalize_zero_amount_invoice` field (when called via the Ruby client for example)
The raised error is a `ActiveRecord::NotNullViolation`
This PR defaults to the default value (`inherit`) when it's the case
> fix(customer): Fix create/update via API when finalize_zero_amount_invoice is nil

- app/jobs/payment_provider_customers/stripe_checkout_url_job.rb
- app/services/payment_provider_customers/stripe_service.rb
- spec/services/payment_provider_customers/stripe_service_spec.rb
This PR fixes the handling of ` Stripe::AuthenticationError` in `PaymentProviderCustomers::StripeCheckoutUrlJob` 
Today this type of error leads to a dead job without notifications sent to the owner of the Strip account.
Since this type of Stripe error cannot be handled on Lago's side we simply have to send a webhook to the account owner and prevent the job from ending in the dead queue.
This PR reuses the logic that was introduce in the `PaymentProviderCustomers::StripeCreateJob` and inner services to notify the owner and only log the error
> fix(stripe): Handle authentication errors for checkout URL

- app/controllers/api/v1/fees_controller.rb
- app/queries/fees_query.rb
- spec/queries/fees_query_spec.rb
This pull request introduces a new filter for `event_transaction_id` in the fees query functionality.
It allows users to filter fees by `pay_in_advance_event_transaction_id`.
> feat(fee): Allow filtering fees on event transaction id

- app/services/subscriptions/create_service.rb
It's currently possible to create 2 subscriptions with the same external id from graphql. Not from the API.
We want to have the same behaviour and prevent to do this from the frontend application.
> fix(subscription): Prevent creating subscription with same external id

- app/serializers/v1/fee_serializer.rb
- spec/serializers/v1/fee_serializer_spec.rb
This PR exposes a new `lago_charge_id` field for the `Fee` resource in the REST API.
It will help users to find the billed resource.
> feat(fee): Expose charge_id in REST API

- app/services/payment_requests/create_service.rb
This PR is a fix for `PaymentRequests::Payments::StripeCreateJob` failing with a `ActiveJob::DeserializationError`
It fixes the error by making sure that all jobs in `PaymentRequests::CreateService` are enqueued outisde of the database transaction
> fix(payment_request): Create jobs outside of DB transaction

- app/jobs/charges/create_job.rb
- app/services/charges/create_service.rb
- app/services/plans/update_service.rb
- spec/jobs/charges/create_job_spec.rb
- spec/services/charges/create_service_spec.rb
- spec/services/plans/update_service_spec.rb
This PR handles the case for cascading charge creation
> feat(plan-cascade): add logic for cascading charge creation

- app/services/events/post_process_service.rb
- app/services/fees/charge_service.rb
- app/services/invoices/customer_usage_service.rb
- app/services/subscriptions/charge_cache_middleware.rb
- app/services/subscriptions/charge_cache_service.rb
- lib/tasks/cache.rake
- spec/services/fees/charge_service_spec.rb
- spec/services/subscriptions/charge_cache_service_spec.rb
Today caching for usage data is scope to the charge.
When an event is received for a specific billable metric code will invalidate the cache for all charges attached to it for the customer's plan. The cache will leave until the end of the billing period or until a new event is received for the same billable metric code and subscription.
This logic avoid recomputing the complete charge aggregation every time the customer usage is requested.
This logic was fine until the introduction of charge filters.
Aggregation for filters are done one by one for every filter, and stored in cache using the same charge cache key (ie: all filtered aggregations are grouped inside the same charge cached bucket). When an event matching a filter is received it invalidate the cache for all filters, meaning that …
> misc(usage): Scope usage caching to the charge filter level

- app/models/invoice.rb
- app/services/credit_notes/estimate_service.rb
- spec/models/invoice_spec.rb
- spec/scenarios/credit_note_spec.rb
- spec/services/credit_notes/estimate_service_spec.rb
Adding a possibility to estimate credit note on prepaid credit invoice:
- allow credit note for credit invoices
- credited amount for credit invoices is 0
- refund amount for credit invoices is not bigger than available wallet balance
> Feat: credit note on credit invoice - estimate service

- app/jobs/charges/create_job.rb
- app/jobs/charges/destroy_job.rb
- app/services/charges/destroy_service.rb
- app/services/plans/update_service.rb
- spec/jobs/charges/destroy_job_spec.rb
- spec/services/charges/destroy_service_spec.rb
- spec/services/plans/update_service_spec.rb
This PR handles the case for cascading charge removal case
> feat (cascade-plan-updates): add logic for cascading charge removal

- app/services/wallet_transactions/void_service.rb
- spec/services/wallet_transactions/void_service_spec.rb
In order keep consistency of outbound transactions from the wallet, we want to save a credit_note_id into wallet_transaction when woiding credits and when credit_note_id is sent
> Feat: credit note on credit - update void credits service

- app/models/fee.rb
- app/services/credit_notes/create_service.rb
- app/services/credit_notes/estimate_service.rb
- app/services/credit_notes/validate_item_service.rb
- app/services/credit_notes/validate_service.rb
- spec/models/fee_spec.rb
- spec/scenarios/credit_note_spec.rb
- spec/services/credit_notes/create_service_spec.rb
- spec/services/credit_notes/estimate_service_spec.rb
Last part of issuing credit notes on credit invoices - creation of a credit note and voiding credits
- updated service to create credit note
- added validation to create and estimate credit notes to return error if requested amount is higher than available
- added validation to have association with active wallet
- added validation to not allow create credited credit_notes for credit invoices
> Feat: credit note on credit - create service

- app/graphql/types/invoices/object.rb
- schema.graphql
- schema.json
To help FE to show the correct reason of disabling button to create credit note, we need to show them when a credit invoice is not associated with an active wallet
added associated_active_wallet_present field to invoice graphql object
> add a field to invoice graphql object

- app/models/customer.rb
- app/models/daily_usage.rb
- app/models/organization.rb
- app/models/subscription.rb
- db/migrate/20241021095706_create_daily_usages.rb
- db/schema.rb
- spec/factories/daily_usages.rb
- spec/models/customer_spec.rb
- spec/models/daily_usage_spec.rb
- spec/models/organization_spec.rb
- spec/models/subscription_spec.rb
This PR is part of the Usage Revenue and unit.
Today, Lago does not offer a way to retrieve customer usage with a granularity lower than the billing period (via invoices and fees). On the other end, it is possible to get the current usage for a customer/subscription, but this usage is just a “snapshot” of the usage a the current time. 
This PR is the first part of a feature implementing a daily usage monitoring. Is simply introduce a new `DailyUsage` model to store the computed daily usage.
> feat(daily_usage): Add DailyUsage model

- app/queries/past_usage_query.rb
- spec/queries/past_usage_query_spec.rb
- spec/requests/api/v1/customers/usage_controller_spec.rb
Past usage endpoint allows you to retrieve past usage, an external subscription id parameter is required. 
However, we incorrectly send all fees belonging to the found invoice, we should filter these by the subscription id as well.
> bug(PastUsage) - Filter fees by external subscription id

- app/graphql/resolvers/dunning_campaigns_resolver.rb
- app/queries/dunning_campaigns_query.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/dunning_campaigns_resolver_spec.rb
- spec/queries/dunning_campaigns_query_spec.rb
Add filter to dunning campaigns resolver to request campaigns in a give set of currencies. This will allow to display only relevant campaigns matching customer currency.
> feat(dunning): Filter dunning campaigns by threshold currency

- app/graphql/types/customers/object.rb
- app/graphql/types/customers/update_customer_input.rb
- app/models/organization.rb
- app/services/customers/update_service.rb
- app/services/dunning_campaigns/update_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/customers/object_spec.rb
- spec/graphql/types/customers/update_customer_input_spec.rb
- spec/models/organization_spec.rb
- spec/services/customers/update_service_spec.rb
Add auto dunning campaign fields to customers object type.
Update customers auto dunning campaign config through customers update mutation.
`exclude_from_dunning_campaign` has higher priority than the applied campaign and if both config arguments are provided at update, exclusion true overwrites the applied campaign.
> feat(dunning): Update dunning campaign config for customers

- app/services/billable_metrics/aggregation_factory.rb
- app/services/events/common_factory.rb
- app/services/events/create_service.rb
- spec/services/events/common_factory_spec.rb
This PR fixes the handling of events for pay in advance charges with both `Clickhouse` and the ingest service
> fix(clickhouse): pay in advance handling

- config/environments/production.rb
- config/environments/staging.rb
We aim to make the Redis connection pool size for the cache configurable via an environment variable
The default Redis connection pool size is currently set to 5
This PR introduces a new environment variable `LAGO_REDIS_CACHE_POOL_SIZE` to control the Redis connection pool size for caching. If the environment variable is set, the value will be used as the pool size; if not, it will default to 5.
> feat: Add redis pool size

- app/services/payment_providers/adyen/handle_incoming_webhook_service.rb
- app/services/payment_providers/find_service.rb
- spec/services/payment_providers/adyen/handle_incoming_webhook_service_spec.rb
- spec/services/payment_providers/find_service_spec.rb
we convert some errors to webhook errors, the payment provider code missing was not handled like that. This MR changes this, so it's now also a webhook error.
> bug(Adyen) - Also send webhook for missing payment provider code

- app/services/integrations/aggregator/invoices/payloads/netsuite.rb
- spec/services/integrations/aggregator/invoices/create_service_spec.rb
- spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
- spec/services/integrations/aggregator/sales_orders/create_service_spec.rb
NetSuite Sync Invoice format is wrong and failing.
Fix netsuite invoice payload by:
- add missing fields: `taxregoverride` and `taxdetailsoverride`
- remove: `tranid`
> fix(netsuite): Fix invoice payload - add missing fields

- app/jobs/clock/subscriptions_to_be_terminated_job.rb
- spec/jobs/clock/subscriptions_to_be_terminated_job_spec.rb
The `left join` in this query causes the same subscription to be returned multiple times. Adding the `distinct` makes sure we're dealing with a list of unique subscriptions.
The reason we can have multiple already existing webhooks is that organizations can have multiple webhook endpoints.
> bug(Clock::SubscriptionsToBeTerminatedJob) - Make sure we only send the webhook once per subscription

- app/jobs/charges/update_job.rb
- app/models/charge.rb
- app/services/charges/create_service.rb
- app/services/charges/update_service.rb
- app/services/plans/update_service.rb
- spec/jobs/charges/update_job_spec.rb
- spec/models/charge_spec.rb
- spec/services/charges/create_service_spec.rb
- spec/services/charges/update_service_spec.rb
- spec/services/plans/update_service_spec.rb
This PR handles the case for cascading charge update case
> feat(cascade-plan-charges): add logic for cascading charge update

- app/models/integration_resource.rb
- app/models/subscription.rb
- spec/models/integration_resource_spec.rb
- spec/models/subscription_spec.rb
When creating or updating subscriptions in Lago, we must sync them to Hubspot.
This PR adds model attributes, methods for subscriptions to be syncable to Hubspot.
> feat(hubspot): Modify models for syncing subscriptions

- app/services/integrations/aggregator/invoices/payloads/netsuite.rb
- spec/services/integrations/aggregator/invoices/create_service_spec.rb
- spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
- spec/services/integrations/aggregator/sales_orders/create_service_spec.rb
NetSuite Sync Invoice format is wrong and failing.
Fix netsuite invoice payload by:
- re-add: `tranid`
> fix(netsuite): Add tranid to netsuite create invoice payload

- app/services/charge_filters/event_matching_service.rb
This PR is related to https://github.com/getlago/lago-api/pull/2678.
The charge filter lookup that was added in the `Events::PostProcessService` lead to some performance regression. The reason behind this is that the `ChargeFilters::EventMatchingService` is reloading systematically the charge filters and associated values even if they were already pre-loaded in the `Events::PostProcessService`
The PR is checking the cached status of the `filters` association to avoid the reload.
> misc: Avoid reloading charge filter if already loaded

- spec/services/integrations/aggregator/invoices/crm/create_service_spec.rb
- spec/services/integrations/aggregator/invoices/crm/update_service_spec.rb
This PR removes this warning from specs:
```
WARNING: An expectation of `:file_url` was set on `nil`. To allow expectations on `nil` and suppress this message, set `RSpec::Mocks.configuration.allow_message_expectations_on_nil` to `true`. To disallow expectations on `nil`, set `RSpec::Mocks.configuration.allow_message_expectations_on_nil` to `false`
```
> chore(specs): Remove a warning from specs

- app/graphql/resolvers/events_resolver.rb
- app/graphql/types/events/object.rb
- app/models/clickhouse/events_raw.rb
- app/queries/events_query.rb
- db/clickhouse_migrate/20231024084411_create_events_raw.rb
- db/clickhouse_migrate/20231026124912_create_events_raw_queue.rb
- db/clickhouse_migrate/20231030163703_create_events_raw_mv.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/events_resolver_spec.rb
- Support `Clickhouse::EventsRaw` for events listing
> feat(events): Support clickhouse store for events listing

- app/jobs/data_exports/combine_parts_job.rb
- app/jobs/data_exports/export_resources_job.rb
- app/jobs/data_exports/process_part_job.rb
- app/models/data_export.rb
- app/models/data_export_part.rb
- app/services/data_exports/combine_parts_service.rb
- app/services/data_exports/create_part_service.rb
- app/services/data_exports/csv/invoice_fees.rb
- app/services/data_exports/csv/invoices.rb
- app/services/data_exports/export_resources_service.rb
- app/services/data_exports/process_part_service.rb
- config/sidekiq.yml
- db/migrate/20241024082941_create_data_export_parts.rb
- db/schema.rb
- spec/factories/data_export_parts.rb
- spec/jobs/data_exports/combine_parts_job_spec.rb
- spec/jobs/data_exports/export_resources_job_spec.rb
- spec/jobs/data_exports/process_part_job_spec.rb
- spec/models/data_export_part_spec.rb
- spec/models/data_export_spec.rb
- spec/services/data_exports/combine_parts_service_spec.rb
- spec/services/data_exports/create_part_service_spec.rb
- spec/services/data_exports/csv/invoice_fees_spec.rb
- spec/services/data_exports/csv/invoices_spec.rb
- spec/services/data_exports/export_resources_service_spec.rb
- spec/services/data_exports/process_part_service_spec.rb
When exporting lots of invoices, we're bumping into the limits of how fast we can export data.
This PR introduces the concept of `DataExportPart`. It's a way for data exports to be split into many parts. These parts can then be handled by a single Sidekiq job. This allows a trivial way to split up the data export. 
once the parts are done, they will be combined into the final export.
> feat(DataExport) Parallelize data export by splitting it into parts

- Guardfile
- app/jobs/integrations/aggregator/subscriptions/crm/create_customer_association_job.rb
- app/jobs/integrations/aggregator/subscriptions/crm/create_job.rb
- app/jobs/integrations/aggregator/subscriptions/crm/update_job.rb
- spec/jobs/integrations/aggregator/subscriptions/crm/create_customer_association_job_spec.rb
- spec/jobs/integrations/aggregator/subscriptions/crm/create_job_spec.rb
- spec/jobs/integrations/aggregator/subscriptions/crm/update_job_spec.rb
When creating or updating subscriptions in Lago, we must sync them to Hubspot.
This PR implements jobs that handle syncing subscriptions to Hubspot.
> feat(hubspot): Add subscription jobs

- app/controllers/api/v1/events_controller.rb
- app/graphql/resolvers/events_resolver.rb
- app/graphql/types/events/object.rb
- app/models/clickhouse/events_raw.rb
- app/queries/events_query.rb
- add `subscription_id`  and `customer_id` for events on CH
- add a default `lago_id`
> fix(events): Fix clickhouse events id

- app/jobs/clock/compute_all_daily_usages_job.rb
- app/jobs/daily_usages/compute_job.rb
- app/models/daily_usage.rb
- app/models/organization.rb
- app/services/daily_usages/compute_all_service.rb
- app/services/daily_usages/compute_service.rb
- clock.rb
- db/migrate/20241025081408_add_refreshed_at_to_daily_usage.rb
- db/schema.rb
- schema.graphql
- schema.json
- spec/clockwork_spec.rb
- spec/factories/daily_usages.rb
- spec/factories/subscriptions.rb
- spec/jobs/clock/compute_all_daily_usages_job_spec.rb
- spec/jobs/daily_usages/compute_job_spec.rb
- spec/services/daily_usages/compute_all_service_spec.rb
- spec/services/daily_usages/compute_service_spec.rb
This PR is part of the Usage Revenue and unit. It follows https://github.com/getlago/lago-api/pull/2718
Today, Lago does not offer a way to retrieve customer usage with a granularity lower than the billing period (via invoices and fees). On the other end, it is possible to get the current usage for a customer/subscription, but this usage is just a “snapshot” of the usage a the current time. 
This PR adds the base logic to compute the daily usage for every active subscription.
For now the feature is enabled by checking the presence of the `LAGO_ENABLE_REVENUE_ANALYTICS` environment variable.
> feat(daily_usage): Add clock to refresh all daily usage

- app/graphql/types/organizations/current_organization_type.rb
- app/models/organization.rb
- app/services/customers/update_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/organizations/current_organization_type_spec.rb
- spec/models/organization_spec.rb
- spec/services/customers/update_service_spec.rb
Customer update service accepts `applied_dunning_campaign_id` as nil to unset its applied campaign and fallback to organization's default dunning campaign.
> feat(dunning): update customer to fallback to organization dunning

- app/models/organization.rb
- app/services/dunning_campaigns/process_attempt_service.rb
- spec/services/dunning_campaigns/process_attempt_service_spec.rb
This change introduces a new service to process a dunning campaign attempt
> feat(dunning): process dunning campaign attempt

- Gemfile
- Gemfile.lock
Two pull requests opened on the `clickhouse-active` records repository were merged lately.
- https://github.com/PNixx/clickhouse-activerecord/pull/158
- https://github.com/PNixx/clickhouse-activerecord/pull/169
Since now all mandatory pieces that we require to use it in production are here, we can use the official gem rather than the fork.
This PR replaces `gem 'clickhouse-activerecord', git: 'https://github.com/getlago/clickhouse-activerecord.git'` with `gem "clickhouse-activerecord", "~> 1.2.0"`
> misc(clickhouse): Use official clickhouse-activerecord gem

- app/jobs/fees/create_pay_in_advance_job.rb
- app/jobs/invoices/create_pay_in_advance_charge_job.rb
After adding the `PreciseTotalAmountCents` to Clickhouse, we now have discrepancies between event json. The one coming from Kafka always has "0.0" set for precise total amount cents while the ruby one has nil. 
This causes 2 duplicate invoice jobs to be enqueued for the same event. The uniqueness key compared all arguments to the job. 
The fix is to limit what is used as lock_key via the `lock_key_arguments` method.
> bug(PayInAdvance) - Add dedicated lock_key_arguments for pay in advance jobs

- .rubocop.yml
- app/controllers/api/base_controller.rb
- app/graphql/types/organizations/current_organization_type.rb
- app/models/api_key.rb
- app/models/clickhouse/events_enriched.rb
- app/models/clickhouse/events_raw.rb
- app/models/organization.rb
- app/models/webhook.rb
- app/services/organizations/create_service.rb
- app/services/users_service.rb
- db/migrate/20241021140054_create_api_keys.rb
- db/schema.rb
- db/seeds/base.rb
- db/seeds/webhooks.rb
- lib/tasks/signup.rake
- spec/factories/api_keys.rb
- spec/factories/organizations.rb
- spec/graphql/resolvers/organization_resolver_spec.rb
- spec/models/api_key_spec.rb
- spec/models/organization_spec.rb
- spec/models/webhook_spec.rb
- spec/requests/api/base_controller_spec.rb
- spec/scenarios/subscriptions/multiple_upgrade_spec.rb
- spec/services/organizations/create_service_spec.rb
- spec/services/users_service_spec.rb
- spec/support/api_helper.rb
One tiny step towards advanced API key management.
Introduces new model `ApiKey` that will replace `api_key` column on the `Organization` model during next steps.
Migrate existing values for `api_key` to the dedicated model.
Adjust REST API authorization to use lookup for ApiKey model and temporary keep previous lookup for Organization model.
> feat(api key management) Extract api key model

- app/graphql/resolvers/api_key_resolver.rb
- app/graphql/resolvers/api_keys_resolver.rb
- app/graphql/types/api_keys/object.rb
- app/graphql/types/api_keys/sanitized_object.rb
- app/graphql/types/query_type.rb
- schema.graphql
- schema.json
- spec/graphql/resolvers/api_key_resolver_spec.rb
- spec/graphql/resolvers/api_keys_resolver_spec.rb
- spec/graphql/types/api_keys/object_spec.rb
- spec/graphql/types/api_keys/sanitized_object_spec.rb
Adding GraphQl types and queries to the newly added ApiKey model. Those would be used to implement hide and reveal feature on FE side later.
Added new types, queries for ApiKey model.
> feat(api-key-management) Add Graphql types and queries for ApiKey model

- app/services/subscriptions/charge_cache_service.rb
- spec/services/invoices/customer_usage_service_spec.rb
- spec/services/subscriptions/charge_cache_service_spec.rb
If fees were present in the cache they would be duplicated when moving to the new caching scheme.
this PR adds a key that we can bump when making changes to the caching.
> bug(caching) - Add cache key version to Subscriptions::ChargeCacheService

- app/services/integration_customers/hubspot_service.rb
- app/services/integrations/aggregator/invoices/crm/create_customer_association_service.rb
- app/services/integrations/aggregator/subscriptions/crm/create_customer_association_service.rb
- app/services/integrations/hubspot/invoices/deploy_object_service.rb
- app/services/integrations/hubspot/subscriptions/deploy_object_service.rb
- app/services/subscriptions/activate_service.rb
- app/services/subscriptions/billing_service.rb
- app/services/subscriptions/create_service.rb
- app/services/subscriptions/free_trial_billing_service.rb
- app/services/subscriptions/terminate_service.rb
- app/services/subscriptions/update_service.rb
- spec/factories/customers.rb
- spec/services/integration_customers/hubspot_service_spec.rb
- spec/services/integrations/aggregator/invoices/crm/create_customer_association_service_spec.rb
- spec/services/integrations/aggregator/subscriptions/crm/create_customer_association_service_spec.rb
- spec/services/subscriptions/activate_service_spec.rb
- spec/services/subscriptions/billing_service_spec.rb
- spec/services/subscriptions/create_service_spec.rb
- spec/services/subscriptions/free_trial_billing_service_spec.rb
- spec/services/subscriptions/terminate_service_spec.rb
- spec/services/subscriptions/update_service_spec.rb
When creating or updating subscriptions in Lago, we must sync them to Hubspot.
This PR calls the services that handle syncing subscriptions to Hubspot via Nango.
> feat(hubspot): Sync subscriptions

- app/controllers/api/v1/plans_controller.rb
- app/graphql/mutations/plans/update.rb
- app/graphql/types/plans/object.rb
- schema.graphql
- schema.json
- spec/graphql/types/plans/object_spec.rb
This PR adds `cascade_updates` attribute that allows user to skip cascade action.
Also, this PR includes `has_overridden_plans` attribute on GQL plan object.
> feat(cascade-plan-changes): add api and GQL support for cascade feature

- app/jobs/bill_subscription_job.rb
- app/jobs/clock/retry_generating_subscription_invoices_job.rb
- app/models/clickhouse/events_raw.rb
- app/models/invoice_error.rb
- clock.rb
- db/migrate/20241031102231_create_invoice_errors.rb
- db/schema.rb
- spec/clockwork_spec.rb
- spec/jobs/bill_subscription_job_spec.rb
- spec/jobs/clock/retry_generating_subscription_invoices_job_spec.rb
- spec/models/invoice_error_spec.rb
When invoices fails to generate it's hard to understand what's going wrong.
We're now automatically retrying invoices that are stuck in generating state. We will also create InvoiceError objects for invoices that fail to generate and finalize.
> feat(InvoiceError) - Add InvoiceError

- app/jobs/clock/retry_generating_subscription_invoices_job.rb
InvoiceSubscriptions can have `invoicing_reason == nil`, so before picking the reason we have to remove nils from the array of invoicing reasons as inside BillSubscriptionJob we're trying to transform invoicing_reason to_sym, and if nil is sent, it crashes
https://lago.sentry.io/issues/6033978013/?referrer=slack&notification_uuid=0479c7e7-eb80-429f-a0a3-486cac9a9b77&environment=production&alert_rule_id=11137413&alert_type=issue
> fix(bug): invoicing reason nil when calling from RetryGeneratingSubscriptionInvoicesJob

- spec/services/daily_usages/compute_service_spec.rb
This PR fixes a flacky test that was introduced by the recent daily_usage feature 
See https://github.com/getlago/lago-api/pull/2718
> misc(daily_usage): fix flacky test

- app/models/invoice_error.rb
- spec/models/invoice_error_spec.rb
If an invoice already has an invoice error, and still fails to generate. We'd have a duplicate primary key violation. 
we'd rather simply update the existing error object.
> feat(InvoiceError) - Improve create_for handling 

- app/models/billable_metric.rb
- db/migrate/20240314165306_migrate_groups_to_filters.rb
- db/migrate/20240603095841_refresh_cached_aggregations.rb
- db/migrate/20241029141351_add_rounding_options_to_billable_metrics.rb
- db/schema.rb
In addition to the [flexible aggregation](https://github.com/119ef63110d2803db639f0db37a3b135?pvs=25), some customers wants to round the output of the aggregation.
This PR adds two new fields to the `billable_metrics` table:
- `rounding_function` as an enum accepting `round`, `flour` or `ceil` (or null)
- `rounding_precision` as a nullable integer
These fields will be used in following pull requests to handle the rounding of the billable metric aggregation
> feat(rounding): Add rounding fields to billable_metrics

- app/controllers/api/v1/billable_metrics_controller.rb
- app/graphql/types/billable_metrics/create_input.rb
- app/graphql/types/billable_metrics/object.rb
- app/graphql/types/billable_metrics/rounding_function_enum.rb
- app/graphql/types/billable_metrics/update_input.rb
- app/serializers/v1/billable_metric_serializer.rb
- app/services/billable_metrics/create_service.rb
- app/services/billable_metrics/update_service.rb
- schema.graphql
- schema.json
- spec/graphql/types/billable_metrics/create_input_spec.rb
- spec/graphql/types/billable_metrics/object_spec.rb
- spec/graphql/types/billable_metrics/update_input_spec.rb
- spec/requests/api/v1/billable_metrics_controller_spec.rb
- spec/serializers/v1/billable_metric_serializer_spec.rb
- spec/services/billable_metrics/create_service_spec.rb
- spec/services/billable_metrics/update_service_spec.rb
In addition to the [flexible aggregation](https://github.com/119ef63110d2803db639f0db37a3b135?pvs=25), some customers wants to round the output of the aggregation.
This PR exposes `rounding_function` and `rounding_precision` fields to REST and GraphQL APIs. It also update `BillableMetrics#CreateService` and `BillableMetrics#UpdateService`
> feat(rounding): Expose rounding attributes to APIs

- app/services/dunning_campaigns/create_service.rb
- spec/graphql/mutations/dunning_campaigns/create_spec.rb
- spec/services/dunning_campaigns/create_service_spec.rb
This change adds the requirement of premium license and premium addon enabled at organization to create dunning campaigns
> feat(dunning): campaign creation requires organization premium add-on

- app/models/dunning_campaign.rb
- app/services/dunning_campaigns/create_service.rb
- db/migrate/20241031123415_add_applied_to_organization_unique_index_to_dunning_campaigns.rb
- db/schema.rb
- spec/services/dunning_campaigns/create_service_spec.rb
This change ensures only one campaign can be applied to organization on creation (per organization). Adds a database unique index to ensure data consistency.
> feat(dunning): only one dunning campaign applied to organization on creation

- app/services/billable_metrics/aggregations/apply_rounding_service.rb
- app/services/billable_metrics/aggregations/base_service.rb
- spec/services/billable_metrics/aggregations/apply_rounding_service_spec.rb
- spec/services/billable_metrics/aggregations/sum_service_spec.rb
- spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
In addition to the [flexible aggregation](https://github.com/119ef63110d2803db639f0db37a3b135?pvs=25), some customers wants to round the output of the aggregation.
This PR applies the rounding logic to the billable metric aggregation result.
> feat(rounding): Apply rounding to billable metric aggregation results

- app/jobs/data_exports/combine_parts_job.rb
This should fix a race condition when multiple data export parts are finished very close in time resulting into multiple CombinePartsJob queued, hence active storage fails because of duplicated key.
> fix: Ensure DataExports::CombinePartsJob uniqueness

- app/services/dunning_campaigns/create_service.rb
- spec/services/dunning_campaigns/bulk_process_service_spec.rb
- spec/services/dunning_campaigns/create_service_spec.rb
This change introduces validation to ensure dunning campaign at least has one threshold.
> feat(dunning): validate dunning campaign has at least one threshold

- app/services/integrations/aggregator/payments/payloads/base_payload.rb
- spec/services/integrations/aggregator/payments/payloads/base_payload_spec.rb
When syncing netsuite payments we need to ensure that correct `integration_customer` object is used in the payload since there can be attached integration_customers of other kinds as well
> fix: Ensure correct integration customer is used when syncing netsuite payments
