config/routes.rb
=> feat: #231 disable sidekiq web by default

app/services/fees/subscription_service.rb, spec/services/fees/subscription_service_spec.rb
=> fix: #235 subscription fee amount when pay in advance

README.md
Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. You have a descriptive commit message with a short title (first line).
c. You have only one commit (if not, squash them into one commit).
d. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).
3. **After** these steps, you're ready to open a pull request.
a. Give a descriptive title to your PR.
b. Describe your changes.
c. Put `closes #XXXX` in your comment to auto-close the issue that …
=> move local setup to wiki pages

db/seeds.rb
=> feat: Improve reseeding and add event seeds

app/services/webhooks/base_service.rb, spec/services/webhooks/invoices_service_spec.rb
=> fix: #246 bug object type root object is missing on webhook

app/graphql/types/invoices/invoice_type_enum.rb, app/graphql/types/invoices/object.rb, app/models/invoice.rb, app/serializers/v1/invoice_serializer.rb, app/services/invoices/add_on_service.rb, app/services/invoices/create_service.rb, db/migrate/20220613130634_add_invoice_type_to_invoices.rb, db/schema.rb, schema.graphql, schema.json, spec/graphql/resolvers/customer_resolver_spec.rb, spec/services/invoices/add_on_service_spec.rb, spec/services/invoices/create_service_spec.rb
=> feat: Add invoice type to invoice

Gemfile, Gemfile.lock, app/jobs/payment_provider_customers/stripe_create_job.rb, app/services/customers_service.rb, app/services/payment_provider_customers/create_service.rb, app/services/payment_provider_customers/stripe_service.rb, config/sidekiq.yml, spec/factories/payment_provider_customers_factory.rb, spec/jobs/payment_provider_customers/stripe_create_job_spec.rb, spec/services/customers_service_spec.rb, spec/services/payment_provider_customers/create_service_spec.rb, spec/services/payment_provider_customers/stripe_service_spec.rb
=> feat: Create customer on stripe

app/jobs/invoices/payments/stripe_create_job.rb, app/models/invoice.rb, app/models/payment.rb, app/models/payment_provider_customers/base_customer.rb, app/models/payment_providers/base_provider.rb, app/services/invoices/add_on_service.rb, app/services/invoices/create_service.rb, app/services/invoices/payments/stripe_service.rb, app/services/payment_provider_customers/create_service.rb, db/migrate/20220617124108_create_payments.rb, db/schema.rb, spec/factories/payment_factory.rb, spec/jobs/invoices/payments/stripe_create_job_spec.rb, spec/models/payment_spec.rb, spec/services/invoices/add_on_service_spec.rb, spec/services/invoices/create_service_spec.rb, spec/services/invoices/payments/stripe_service_spec.rb
Fixes #270
- Create stripe charge for invoices
- Store stripe charge status in a `Payment` model
=> feat: Create charge on stripe when invoice is created

clock.rb
Fixes https://github.com/getlago/lago-api/issues/278
=> [BUG]: We should log error on clock service

app/graphql/types/invoices/object.rb, app/graphql/types/invoices/status_type_enum.rb, db/schema.rb, schema.graphql, schema.json, spec/graphql/resolvers/customer_resolver_spec.rb
=> feat: #299 expose invoice status to graphql

lib/lago_http_client/lago_http_client/client.rb, spec/lib/lago_http_client/client_spec.rb
- Fix error when webhook response is not a JSON but a simple string
=> fix: Webhook string response

app/views/templates/invoice.slim
=> fix: pdf org legal name

app/graphql/mutations/wallets/create.rb, app/graphql/mutations/wallets/terminate.rb, app/graphql/mutations/wallets/update.rb, app/graphql/types/wallets/object.rb, app/models/wallet.rb, app/services/wallets/create_service.rb, app/services/wallets/terminate_service.rb, app/services/wallets/update_service.rb, db/schema.rb, schema.graphql, schema.json, spec/graphql/mutations/wallets/create_spec.rb, spec/graphql/mutations/wallets/terminate_spec.rb, spec/graphql/mutations/wallets/update_spec.rb, spec/services/wallets/create_service_spec.rb, spec/services/wallets/terminate_service_spec.rb, spec/services/wallets/update_service_spec.rb
- Add Wallets Mutation logic
Need https://github.com/getlago/lago-api/pull/337
=> feat: wallets mutations logic

app/graphql/types/customers/object.rb, app/graphql/types/wallet_transactions/object.rb, schema.graphql, schema.json
- Add the GraphQL `hasActiveWallet` field for customers
=> feat: graphql customer active wallet boolean

db/schema.rb
The schema file is apparently not up-to-date.
[Here](https://github.com/getlago/lago-api/commit/c36ce47a7ddf7c53eecfb9211c38c2bbe0ab6fe8) is an example of a commit with a missing update on the schema.
The goal of this PR is to fetch the latest version of the schema file.
=> misc: Fix not up-to-date schema

config/storage.yml
Heyyyy Guys,
this PR makes S3 endpoints overwriteable.
https://edgeguides.rubyonrails.org/active_storage_overview.html#s3-service-amazon-s3-and-s3-compatible-apis
=> feat: active storage: make non-aws users happy

PULL_REQUEST_TEMPLATE.md
We want to improve the visibility and the quality of our pull requests.
So that everyone can understand and contribute easily to Lago.
This PR is changing the content of our `PULL_REQUEST_TEMPLATE.md`.
By looking at the preview on Github.
=> misc: Update PR template

docker-compose.ci.yml
We need a Redis for the CI env
- Add Redis into the CI compose file
=> misc: Add Redis in CI compose

app/jobs/segment_identify_job.rb, spec/jobs/segment_identify_job_spec.rb
We miss the organization name in the segment identify informations
- Add the organization name in the segment identify traits
=> feat: add Organization Name in Segment Identify

app/services/invoices/generate_service.rb, app/views/templates/invoice.slim, config/environments/development.rb
Invoice's font were loading with an external http css, sometimes the font were not loaded by Gotenberg
- Fonts have been packed into the Gotenberg image
- Add the CSS to declare the font
- Fix the S3 env var for development
=> fix(invoices): invoices font are now packed into the gotenberg image

Dockerfile.arm64
=> misc(docker): Add ARM64 DockerFile

.github/workflows/lint.yml, .github/workflows/pronto.yml
We loves to be linted.
- Add the Linter action
=> misc: Add Linter

.github/workflows/manual-release.yml, .github/workflows/release.yml
Since we added support of ARM64 image, we need to build them during the release process
- Add the ARM64 image build
=> misc(docker): Build ARM64 Image with CI

app/controllers/webhooks_controller.rb, app/jobs/payment_providers/gocardless/handle_event_job.rb, app/serializers/v1/organization_serializer.rb, app/services/payment_providers/gocardless_service.rb, config/routes.rb, spec/fixtures/gocardless/events.json, spec/jobs/payment_providers/gocardless/handle_event_job_spec.rb, spec/requests/webhooks_spec.rb, spec/services/payment_providers/gocardless_service_spec.rb
Handle incoming webhooks
Handle incoming webhooks that notify about payment statuses
=> fect (gocardless): handle incoming webhooks

app/services/persisted_events/create_or_update_service.rb, spec/services/persisted_events/create_or_update_service_spec.rb
When adding > removing > re-adding the same persisted event the same day, price increases
Instead of reading the persisted event, we should set back the `removed_at` field to nil
=> fix(persisted_events): Reactivate event if removed and then re-added on same day

app/graphql/resolvers/invoice_credit_notes_resolver.rb, app/graphql/types/query_type.rb, schema.graphql, schema.json, spec/graphql/resolvers/invoice_credit_notes_resolver_spec.rb
👉 https://github.com/getlago/lago/issues/59
We need to fetch credit notes from an invoice details view
Please note this PR is merged into a feature branch
This PR adds the endpoints for it
=> feat: add invoice_credit_notes resolver

app/models/customer.rb, app/models/organization.rb, db/migrate/20221115100834_add_invoice_grace_period.rb, db/schema.rb
The goal of this PR is to create `invoice_grace_period` on `organizations` and `customers`.
=> feat(grace-period): Add invoice grace period columns

app/views/templates/invoice.slim
The goal of this PR is to fix the invoice when we have recurring fees with an amount equal to 0.
=> misc: Display invoice with 0 amount recurring fees

app/graphql/types/credit_notes/object.rb, db/schema.rb, schema.graphql, schema.json
👉  https://github.com/getlago/lago/issues/{{NUMBER}}
This PR is part of the credit notes work and will be released on the feature branch
This PR adds some graphQL fields needed for UI porpose
=> feat(graph) Add some graphQL fields for UI purpose

spec/graphql/resolvers/add_on_resolver_spec.rb, spec/graphql/resolvers/coupon_resolver_spec.rb, spec/graphql/resolvers/plan_resolver_spec.rb, spec/graphql/resolvers/plans_resolver_spec.rb
[A recent bugfix](https://github.com/getlago/lago-api/pull/620/files) did correct the value returned in some methods
This PR adds tests to assert the value.
=> chore: add tests for customerCount method

app/jobs/credit_notes/refunds/gocardless_create_job.rb, app/services/credit_notes/create_service.rb, app/services/credit_notes/refunds/gocardless_service.rb, app/services/payment_providers/gocardless_service.rb, spec/fixtures/gocardless/events_refund.json, spec/jobs/credit_notes/refunds/gocardless_create_job_spec.rb, spec/services/credit_notes/create_service_spec.rb, spec/services/credit_notes/refunds/gocardless_service_spec.rb, spec/services/payment_providers/gocardless_service_spec.rb
As part of credit notes, refunds have to be handled for gocardless
=> feat (credit_notes): handle refunds for gocardless

.github/workflows/pronto.yml
Remove Pronto job for Dependabot
=> misc(gh): Do not run Pronto for Dependabots PR

app/controllers/api/v1/invoices_controller.rb, app/graphql/resolvers/invoices_resolver.rb, app/graphql/types/query_type.rb, schema.graphql, schema.json, spec/graphql/resolvers/invoices_resolver_spec.rb, spec/requests/api/v1/invoices_spec.rb
Provide possibility to fetch and filter invoices
Add filter by payment status in the GET /invoices endpoint
Add resolver to fetch invoices and filter them by payment status
=> feat (invoices): add possibility to fetch and filter invoices

app/graphql/resolvers/invoices_resolver.rb, schema.graphql, schema.json, spec/graphql/resolvers/invoices_resolver_spec.rb
From the UI we also want to be able to filter invoices by status
Invoices resolver is extended with possibility to filter invoices by status
=> feat (invoices): Filter invoices by status in resolver

app/controllers/api/v1/events_controller.rb, app/services/events/create_service.rb, app/services/events/validate_creation_service.rb, spec/requests/api/v1/events_spec.rb, spec/services/events/create_service_spec.rb
The goal of this PR is to improve the validations of parameters when creating an event.
=> misc: Use Events::ValidateCreationService for validating event params

app/services/billable_metrics/update_service.rb, app/services/groups/create_batch_service.rb, spec/services/billable_metrics/update_service_spec.rb, spec/services/groups/create_batch_service_spec.rb
The goal of this PR is to be able to remove groups from a billable metric.
=> fix: Ability to remove groups from a billable metric

app/services/persisted_events/validate_creation_service.rb
The goal of this PR is to fix an issue when creating a persisted event.
=> fix: Create persisted event

config/environments/production.rb, config/environments/staging.rb
=> fix(license): services urls

app/services/customers/create_service.rb, app/services/customers/update_service.rb, app/services/organizations/update_service.rb, spec/graphql/mutations/customers/create_spec.rb, spec/graphql/mutations/customers/update_spec.rb, spec/graphql/mutations/organizations/update_spec.rb, spec/requests/api/v1/customers_spec.rb, spec/requests/api/v1/organizations_spec.rb, spec/services/customers/create_service_spec.rb, spec/services/customers/update_service_spec.rb, spec/services/organizations/update_service_spec.rb
The license management was recently introduce. Since timezone feature is supposed to be a premium one, it is impacted
This PR adds the premium flag handling to unblock the feature
=> feat(timezones): Add license management

app/services/customers/create_service.rb, app/services/customers/update_service.rb, app/services/organizations/update_service.rb, spec/graphql/mutations/customers/create_spec.rb, spec/graphql/mutations/customers/update_invoice_grace_period_spec.rb, spec/graphql/mutations/customers/update_spec.rb, spec/graphql/mutations/organizations/update_spec.rb, spec/requests/api/v1/customers_spec.rb, spec/requests/api/v1/organizations_spec.rb, spec/services/customers/create_service_spec.rb, spec/services/customers/update_service_spec.rb, spec/services/organizations/update_service_spec.rb
- Put `grace_period` feature under license
=> feat(grace-period): activate grace period under license

app/jobs/send_webhook_job.rb, app/services/subscriptions/terminate_service.rb, app/services/webhooks/subscriptions/terminated_service.rb, spec/jobs/send_webhook_job_spec.rb, spec/services/invoices/calculate_fees_service_spec.rb, spec/services/subscriptions/terminate_service_spec.rb
- Add a subscription terminated webhook
=> feat(subscriptions): Add terminated webhook

app/models/credit_note.rb, db/schema.rb
When a subscription has no fee, a default one is assigned and the currency is also the default one, not the subscription one
Assign the right currency to the default fee
=> fix(credit-note): Subscription fee currency

config/routes.rb
Ensure sidekiq web interface is disabled unless `LAGO_SIDEKIQ_WEB` is explicitly set to `"true"`
=> fix: ensure sidekiq is disabled unless true

app/controllers/api/v1/wallet_transactions_controller.rb, app/graphql/resolvers/wallet_transactions_resolver.rb, app/queries/wallet_transactions_query.rb, config/routes.rb, spec/queries/wallet_transactions_query_spec.rb, spec/requests/api/v1/wallet_transactions_spec.rb
Add API endpoint to fetch wallet transactions with query class
This PR adds endpoint to fetch wallet transactions.
Also, new query class is made and applied to both API controller and graphQL resolver
=> feat (wallets): add API endpoint to fetch wallet transactions with query class

Gemfile.lock
- Update `newrelic` and `sentry` dependencies
=> misc(dependencies): Update some tools versions

app/models/webhook.rb, db/migrate/20230206143214_create_webhooks.rb, db/schema.rb, db/seeds/base.rb, db/seeds/invoices.rb, db/seeds/webhooks.rb, spec/factories/webhooks.rb
We want to add an history of webhooks for users to be able to manage them.
- Add the `webhooks` table and `webhook` model
- Add some seeds
=> feat(webhooks): Add Webhooks Table and Model

app/graphql/resolvers/webhooks_resolver.rb, app/graphql/types/query_type.rb, app/graphql/types/webhooks/object.rb, app/graphql/types/webhooks/status_enum.rb, app/models/organization.rb, schema.graphql, schema.json, spec/graphql/resolvers/webhooks_resolver_spec.rb
- Add the GQL Webhooks Resolver
=> feat(webhooks): Add Webhooks GQL Resolver

app/jobs/clock/webhooks_cleanup_job.rb, clock.rb, spec/jobs/clock/webhooks_cleanup_job_spec.rb
- We need to delete webhooks that are older than 90 days
- Add a Clock job to remove old webhooks
=> feat(webhooks): Add Cleanup Job

db/migrate/20230214100638_change_webhooks_organization_id_to_uuid.rb, db/schema.rb
- use `uuid` for `organization_id` on `webhooks` table
=> fix(webhooks): Change Webhooks organization reference type

app/graphql/resolvers/invites_resolver.rb
Change the order or returned invites
=> misc(invites): set order on created_at

app/graphql/resolvers/webhooks_resolver.rb, app/models/webhook.rb, app/queries/webhooks_query.rb, schema.graphql, schema.json, spec/queries/webhooks_query_spec.rb
We want to be able to search webhooks by `id` or `webhook_type`, and also filter by status
- Add search capability on webhooks
=> feat(webhooks): Add Search capability

config/storage.yml
Closes https://github.com/getlago/lago-api/issues/848
- Add S3 Path Style option
=> feat(storage): Add S3 Path style option

app/models/fee.rb, app/models/invoice.rb, app/services/credit_notes/create_from_termination.rb, app/services/credit_notes/create_service.rb, app/services/credit_notes/validate_item_service.rb, app/services/credit_notes/validate_service.rb, app/services/invoices/compute_amounts_from_fees.rb, app/services/invoices/customer_usage_service.rb, spec/models/fee_spec.rb, spec/models/invoice_spec.rb, spec/scenarios/terminate_pay_in_advance_spec.rb, spec/services/credit_notes/create_from_termination_spec.rb, spec/services/fees/charge_service_spec.rb, spec/services/fees/subscription_service_spec.rb, spec/services/invoices/customer_usage_service_spec.rb
We want to change how rounding is done for having better precision.
The goal of this PR is to convert rounding from `ceil` to `round`.
=> feat(rounding): Change ceil to round

.github/workflows/fern-check.yml, .github/workflows/manual-release.yml, .github/workflows/release.yml, fern/api/definition/addOns.yml, fern/api/definition/api.yml, fern/api/definition/billableMetrics.yml, fern/api/definition/commons.yml, fern/api/definition/coupons.yml, fern/api/definition/creditNotes.yml, fern/api/definition/customers.yml, fern/api/definition/events.yml, fern/api/definition/invoices.yml, fern/api/definition/organizations.yml, fern/api/definition/plans.yml, fern/api/definition/subscriptions.yml, fern/api/definition/wallets.yml, fern/api/generators.yml, fern/fern.config.json
This PR introduces [Fern](https://www.buildwithfern.com/) to this repo. The Fern team is working with @jdenquin to automate client generation, api reference generation and postman collection generation. 
In this PR, we added: 
- Fern definition that lives at the root of the repo in a `fern` folder. The docs/sdks/postman collection will be updated based on the Fern definition. So, whenever the API changes it is important to update the Fern spec accordingly. 
- `fern-check` GitHub action to validate that the fern definition is valid. 
- `fern-generate` GitHub actions. This Github action will release the SDKs and use the version that is provided. 
@jdenquin there are a couple things the Lago team will need to do before the automation will work:
=> 🌿 Introduce Fern

config/application.rb, config/locales/en/invoice.yml, config/locales/nb.yml, config/locales/nb/credit_note.yml, config/locales/nb/invoice.yml
With this PR we are adding support for norwegian locale in documents
=> feat (localization): Add norwegian locale

app/validators/email_validator.rb
This PR aims to find a better approach for email validation, and make sure the FE uses the same.
=> misc: Update email regex to be consistent with the frontend

app/services/fees/create_instant_service.rb, spec/services/fees/create_instant_service_spec.rb
This PR allows the Fees::CreateInstantService to perform the aggregation and compute fees amount without delivering webhook or persisting a fee. We will then use it to compute the expected fees of an event.
=> feat(instant_charge): Allow instant fee creation without persistence

app/controllers/api/v1/customers_controller.rb, config/routes.rb, spec/requests/api/v1/customers_spec.rb
Customer portal allows end user to visit basic informations like subscription and invoices
This PR adds endpoint for fetching customer portal URL
=> feat (customer portal): Add api endpoint for fetching customer portal url

app/graphql/resolvers/customer_portal/customer_resolver.rb, app/graphql/resolvers/customer_portal/organization_resolver.rb, app/graphql/types/query_type.rb, schema.graphql, schema.json, spec/graphql/resolvers/customer_portal/customer_resolver_spec.rb, spec/graphql/resolvers/customer_portal/organization_resolver_spec.rb
Customer portal allows end user to visit basic informations like subscription and invoices
This PR handles:
- adding customer portal user graphQL query
- adding customer portal organization graphQL query
=> feat (customer portal): add customer portal queries

app/services/customer_portal/generate_url_service.rb, spec/graphql/mutations/customer_portal/generate_url_spec.rb, spec/requests/api/v1/customers_spec.rb, spec/services/customer_portal/generate_url_service_spec.rb
Customer portal is feature that should be available only for premium users so this check validate it
=> fix: add licence check in generate customer portal url service

CONTRIBUTING.md
Update the contribution guide to improve the contribution experience:
- Fix links to community slack
- Fix link to feature request tool
- Fix issues and pull request labels
=> misc: Update and fix contribution guide

app/controllers/api/v1/events_controller.rb, app/services/events/create_batch_service.rb, app/services/events/validate_creation_service.rb, spec/requests/api/v1/events_spec.rb, spec/services/events/create_batch_service_spec.rb, spec/services/events/validate_creation_service_spec.rb
Update validations when creating batch events
We should add more detail validation response to the user when creating events in batch. Currently we have set of validations that is performed during the Job processing, but we also want to add the same scope of validations to the user (in API response)
=> misc(events): update validations when creating batch events

app/services/invoices/finalize_service.rb
Async jobs were executed before the end of a DB transaction on finalized invoice.
Run all async stuff after the DB transaction is done.
=> fix(invoices): Race conditions on finalized invoices

app/services/applied_coupons/create_service.rb, spec/services/applied_coupons/create_service_spec.rb
In some cases coupons needs to be applied only on certain charges. In order to support it, billable metric limitations will be added.
Prevent applying coupon if there is plan overlap.
There is plan overlap if either plans or BMs directly overlap. Also, there can be overlap if billable metric limitation is present on one coupon but at the same time there is plan limitation on another coupon where plan's charge contain same BM
=> feat (coupons): prevent applying coupon if there is plan overlap

app/views/templates/credit_note.slim, app/views/templates/invoice.slim, config/application.rb, config/locales/de.yml, config/locales/de/credit_note.yml, config/locales/de/email.yml, config/locales/de/invoice.yml
Add german translations for documents and emails
=> feat (localization): add german translations

config/locales/fr/invoice.yml
Some French copy needed to be updated in the invoice template
=> misc(invoice): update some fr copy

app/controllers/api/v1/plans_controller.rb, app/graphql/types/charges/input.rb, app/graphql/types/charges/object.rb, app/serializers/v1/charge_serializer.rb, app/services/plans/create_service.rb, app/services/plans/update_service.rb, db/migrate/20230522113810_add_invoiceable_to_charges.rb, db/schema.rb, schema.graphql, schema.json, spec/services/plans/create_service_spec.rb, spec/services/plans/update_service_spec.rb
This feature adds possibility to bill charges in advance
In this PR new field called `invoiceable` is added. This field is responsible for selecting if certain charges will be included on invoice or not.
=> feat (charges): add invoiceable field

app/jobs/send_webhook_job.rb, app/services/fees/create_pay_in_advance_service.rb, app/services/invoices/generate_pdf_service.rb, app/views/helpers/money_helper.rb, app/views/templates/invoices/charge.slim, spec/jobs/send_webhook_job_spec.rb, spec/services/fees/create_pay_in_advance_service_spec.rb
This PR adds a new template for invoices that are created with ingesting an event (case `pay_in_advance=true` and `invoiceable=true`)
=> feat (charges): add new template for pay_in_advance charges

config/environments/production.rb
=> misc(license): Fix License env

db/migrate/20221018144521_add_legacy_flag_to_invoices.rb
The migration task `invoices:fill_vat_rate` was failing because it as been accidentally removed with a previous clean-up of the migration process. 
The proper fix pushed with this PR is rewrite of the migration task in pure SQL.
Fixes https://github.com/getlago/lago/issues/244
=> fix: Fix legacy vat migration

.vscode/settings.json, Gemfile.lock, app/controllers/webhooks_controller.rb, app/jobs/invoices/payments/adyen_create_job.rb, app/jobs/payment_provider_customers/adyen_create_job.rb, app/jobs/payment_providers/adyen/handle_event_job.rb, app/models/customer.rb, app/models/payment_provider_customers/adyen_customer.rb, app/serializers/v1/customer_serializer.rb, app/services/customers/create_service.rb, app/services/customers/update_service.rb, app/services/invoices/payments/adyen_service.rb, app/services/invoices/payments/create_service.rb, app/services/payment_provider_customers/adyen_service.rb, app/services/payment_provider_customers/create_service.rb, app/services/payment_providers/adyen_service.rb, config/routes.rb, schema.graphql, schema.json, spec/factories/payment_provider_customers.rb, spec/factories/payment_responses.rb, spec/fixtures/adyen/webhook_authorisation_response.json, spec/jobs/invoices/payments/adyen_create_job_spec.rb, spec/jobs/payment_providers/adyen/handle_event_job_spec.rb, spec/models/payment_provider_customers/adyen_customer_spec.rb, spec/requests/webhooks_spec.rb, spec/services/invoices/payments/adyen_service_spec.rb, spec/services/payment_provider_customers/adyen_service_spec.rb, spec/services/payment_providers/adyen_service_spec.rb
👉  https://getlago.canny.io/feature-requests/p/support-integration-with-adyen
Adyen provides payment apis for card and other payments.
Add Adyen as a payment provider supported natively
=> feat(adyen payments): Add adyen payments

app/services/webhooks/base_service.rb, spec/services/webhooks/base_service_spec.rb
Many webhook delivereies are failing with non-HTTP error. (SocketError, time-out)
These error should be handled by the retry system and not be sent to de dead-job queue.
This PR rescues `Net::ReadTimeout`, `Errno::ECONNRESET`, `SocketError` and apply the retry webhook logic.
=> fix: Handle non-HTTP error case for webhook delivery

app/services/invoices/subscription_service.rb
We want to rollback the creation if the invoice is an error is raised.
=> Prevent creating invoices in case of duplicate

app/services/fees/subscription_service.rb, app/services/subscriptions/dates_service.rb, spec/scenarios/invoices_spec.rb, spec/services/invoices/calculate_fees_service_spec.rb, spec/services/subscriptions/dates/monthly_service_spec.rb, spec/services/subscriptions/dates/weekly_service_spec.rb, spec/services/subscriptions/dates/yearly_service_spec.rb
The goal of this PR is to fix an issue related to timezone and first subscription calculation.
=> fix: first subscription fee with timezone

app/views/templates/credit_note.slim
The goal of this PR is to update the credit note template in order to display:
- true up fees
- dimensions
=> Display true up fees and groups on credit note template

app/controllers/api/v1/coupons_controller.rb, app/graphql/mutations/coupons/create.rb, app/graphql/mutations/coupons/update.rb, app/graphql/types/coupons/create_input.rb, app/graphql/types/coupons/object.rb, app/graphql/types/coupons/update_input.rb, app/serializers/v1/coupon_serializer.rb, app/services/coupons/create_service.rb, app/services/coupons/update_service.rb, db/migrate/20230629100018_add_description_to_coupon.rb, db/schema.rb, schema.graphql, schema.json, spec/graphql/mutations/coupons/create_spec.rb, spec/graphql/mutations/coupons/update_spec.rb, spec/graphql/resolvers/coupon_resolver_spec.rb, spec/serializers/v1/coupon_serializer_spec.rb, spec/services/coupons/create_service_spec.rb
👉  https://getlago.canny.io/feature-requests/p/add-optional-description-for-coupons
We want to add an optional description to coupon model
This PR updates all part of the code needed to perform such action
=> feat: Add coupon description

app/services/organizations/update_service.rb, spec/services/organizations/update_service_spec.rb
Update an orga with this:
```json
{
"organization": {
"country": "fr"
}
}
```
Try to access the UI ****************settings**************** > ************************organization************************
⇒ This fails
=> fix(organization): Country code should be upcased

app/services/billable_metrics/aggregations/base_service.rb, app/services/billable_metrics/aggregations/sum_service.rb, app/services/billable_metrics/aggregations/unique_count_service.rb, app/services/billable_metrics/prorated_aggregations/base_service.rb, app/services/billable_metrics/prorated_aggregations/sum_service.rb, app/services/billable_metrics/prorated_aggregations/unique_count_service.rb, app/services/charges/apply_pay_in_advance_charge_model_service.rb, app/services/charges/charge_models/base_service.rb, app/services/fees/charge_service.rb, app/services/fees/create_pay_in_advance_service.rb, spec/scenarios/pay_in_advance_charges_spec.rb, spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb, spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
This PR adds some refactoring to proration logic. New setup of inheritance is implemented and common methods are used for all prorated classes.
=> feat (billable metrics): Refactoring around common proration code

app/models/charge.rb, app/models/invoice.rb, app/services/billable_metrics/aggregations/sum_service.rb, app/services/billable_metrics/aggregations/unique_count_service.rb, app/services/billable_metrics/prorated_aggregations/base_service.rb, app/services/charges/charge_models/volume_service.rb, app/services/invoices/calculate_fees_service.rb, app/services/quantified_events/create_or_update_service.rb, spec/services/billable_metrics/aggregations/unique_count_service_spec.rb, spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb, spec/services/charges/charge_models/volume_service_spec.rb, spec/services/fees/charge_service_spec.rb, spec/services/plans/create_service_spec.rb
This branch consists of various small fixes related to new aggregation logic (prorated, recurring, in advance)
Here is the list of fixes:
- small update for volume charge model and proration
- disable graduated charge model and proration
- round proration coefficient (number of days) to upper value
- in case of upgrade use external id in queries (in order to use also previous subscription events)
=> feat (aggregation-refactoring): Various small fixes

app/models/billable_metric.rb, db/migrate/20230719100256_migrate_recurring_count_and_unique_count_aggregation.rb
As part of new aggregation logic, we need to migrate old aggregation data.
=> feat (aggregations): migrate old aggregation data

Gemfile, Gemfile.lock, app/controllers/api/v1/customers_controller.rb, app/graphql/types/payment_provider_customers/provider.rb, app/graphql/types/payment_provider_customers/provider_input.rb, app/graphql/types/payment_provider_customers/provider_payment_methods_enum.rb, app/jobs/payment_provider_customers/adyen_checkout_url_job.rb, app/models/payment_provider_customers/stripe_customer.rb, app/serializers/v1/customer_serializer.rb, app/services/customers/create_service.rb, app/services/invoices/payments/stripe_service.rb, app/services/payment_provider_customers/adyen_service.rb, app/services/payment_provider_customers/create_service.rb, app/services/payment_provider_customers/stripe_service.rb, app/services/payment_providers/stripe_service.rb, schema.graphql, schema.json, spec/factories/payment_provider_customers.rb, spec/fixtures/stripe/charge_event.json, spec/fixtures/stripe/customer_retrieve_response.json, spec/fixtures/stripe/customer_updated_event.json, spec/graphql/mutations/customers/create_spec.rb, spec/graphql/mutations/customers/update_spec.rb, spec/models/payment_provider_customers/stripe_customer_spec.rb, spec/requests/api/v1/customers_spec.rb, spec/services/invoices/payments/stripe_service_spec.rb, spec/services/payment_provider_customers/create_service_spec.rb, spec/services/payment_providers/stripe_service_spec.rb
Accept Stripe SDD
Add provider_payment_methods to StripeCustomer model
=> feat(stripe sdd): Stripe sdd model

app/controllers/api/v1/webhook_endpoints_controller.rb, app/services/webhook_endpoints/update_service.rb, config/routes.rb, spec/requests/api/v1/webhook_endpoints_spec.rb, spec/services/webhook_endpoints/update_service_spec.rb
- Add `PUT` endpoint for `webhook_endpoints`
=> feat(webhooks): Webhook endpoints update

app/services/credits/applied_coupon_service.rb, spec/scenarios/taxes_on_invoice_spec.rb
handle `precise_coupon_amount` on fees when its value is greater than fees `amount_cents`
=> fix(fees): handle precise_coupon_amount on fees when its value is greater than fees amount_cents

app/services/invoices/payments/stripe_service.rb, spec/services/invoices/payments/stripe_service_spec.rb
When calling Stripe API to create a payment intent, it could in some situations returns a payment object with a `processing` status. The service is using this returned status to update the `payment_status` of the related invoice. Sadly the current implementation only accepts `pending`, `succeeded` or `failed`.
In the current situation, the service end-up raising a validation error: 
```
BaseService::ValidationFailure: Validation errors: {:payment_status=>["value_is_invalid"]}
```
This PR ensure that the invoice keeps the pending status but is not marked as `ready_for_payment_processing` until we receive the proper webhook to mark it as `failed` or `succeeded`.
NOTE: in the future, we might want to introduce a proper `processing` payment_status on invoice, to simplify the processing of the …
=> fix(stripe): handle processing payment status

app/views/templates/invoices/charge.slim, app/views/templates/invoices/one_off.slim, app/views/templates/invoices/v3.slim, db/migrate/20230808144739_fill_invoice_payment_due_date.rb, db/schema.rb
This PR follows https://github.com/getlago/lago-api/pull/1225 and adds a migration to fill the `invoice#payment_due_date` field
=> Migrate payment due date

app/services/payment_provider_customers/stripe_service.rb
A lot of dead jobs are related to missing Stripe customers when receiving `customer.update` webhooks from Stripe.
One of the reasons for this kind of error is that the same Stripe Secret key could be shared between organizations. As a consequence, we could receive `customner.update` webhooks for customer attached to another organization, leading to `stripe_customer_not_found` error when the customer is found in database.
The fix is to scope the customer lookup in the `handle_missing_customer` guard to the organization receiving the hook.
=> fix(stripe): Add new filter for missing stripe customer in strip webhooks

app/services/subscriptions/dates/quarterly_service.rb, spec/services/subscriptions/dates/quarterly_service_spec.rb
The goal of this feature is to allow quarterly billing period
This PR adds quarterly billing service and depending tests
=> feat (subscriptions): add quarterly dates service

db/migrate/20230811081854_populate_fees_precise_coupons_amount_cents.rb, db/seeds/invoices.rb
Related to https://github.com/getlago/lago-api/pull/1239
=> fix(tax): Last fix for fees#precise_coupons_amount_cents migration

app/graphql/types/invoice_subscription/object.rb, schema.graphql, schema.json
When plan is pay in arrear and charges are pay in advance we need to send to the UI correct charges interval
=> fix (invoice): add charges in advance interval

app/models/plan.rb, app/services/subscriptions/billing_service.rb, app/services/subscriptions/dates_service.rb, config/locales/de/invoice.yml, config/locales/en/invoice.yml, config/locales/fr/invoice.yml, config/locales/nb/invoice.yml, schema.graphql, schema.json, spec/models/plan_spec.rb, spec/scenarios/subscriptions/billing_spec.rb, spec/services/invoices/calculate_fees_service_spec.rb, spec/services/subscriptions/billing_service_spec.rb, spec/services/subscriptions/dates_service_spec.rb
Main point of this feature is to add quarterly billing interval
In this PR there are few main parts:
- updated billing service
- add new interval in plan model
- connect quarterly_billing_service into dates_service
Other parts include tests and configuration
=> feat(subscriptions): integrate quarterly billing period

app/services/charges/charge_models/graduated_percentage_service.rb, spec/services/charges/charge_models/graduated_percentage_service_spec.rb
The objective of this feature is to introduce a new graduated percentage charge model similar to the current graduated charge model but applying a rate to the units rather than an amount.
This PR adds the logic for the new charge model
=> feat(charge): Graduated charge model logic

config/application.rb, config/locales/it.yml, config/locales/it/credit_note.yml, config/locales/it/email.yml, config/locales/it/invoice.yml, config/locales/it/webhook_endpoint.yml
Add document translations for italian language
=> feat (localization): add translations for italian

app/models/payment_provider_customers/base_customer.rb, app/models/payment_providers/base_provider.rb, config/initializers/analytics_ruby.rb
This PR is adding papertrail versioning to `PaymentProvider` and `PaymentProviderCustomer` in order to ease future debugging.
=> misc: Add versioning on PaymentProvider and PaymentProviderCustomer

app/services/billable_metrics/create_service.rb, app/services/billable_metrics/update_service.rb, app/services/groups/create_or_update_batch_service.rb, spec/services/groups/create_or_update_batch_service_spec.rb
👉 https://getlago.canny.io/feature-requests/p/edit-groups-associated-with-billable-metrics
We want to be able to edit billable metric groups.
The goal of this PR is to permit editing groups for a billable metric.
=> feat(group): Ability to edit groups for a billable metric

app/jobs/clock/terminate_ended_subscriptions_job.rb, app/services/subscriptions/activate_service.rb, app/services/utils/timezone_service.rb, spec/jobs/clock/terminate_ended_subscriptions_job_spec.rb, spec/scenarios/subscriptions/terminate_ended_spec.rb
Fix timezone condition in job that terminates ending subscription.
=> fix (subscriptions): terminate ended subscriptions condition regarding timezone

db/migrate/20230911185900_add_unique_index_to_applied_taxes.rb, db/schema.rb
We're facing some issues with duplicated applied taxes.
The goal of this PR is to prevent such issues by creating some unique indexes.
=> misc: Add unique index to applied taxes tables

app/graphql/types/customers/create_customer_input.rb, app/graphql/types/customers/object.rb, app/graphql/types/customers/update_customer_input.rb, schema.graphql, schema.json
=> feat(customer): expose external salesforce id

Gemfile.lock, config/application.rb, config/locales/sv.yml, config/locales/sv/credit_note.yml, config/locales/sv/email.yml, config/locales/sv/invoice.yml, config/locales/sv/webhook_endpoint.yml
=> Add Swedish locale

app/views/templates/credit_note.slim, config/locales/es/invoice.yml, config/locales/sv/invoice.yml, db/schema.rb
Add entries to swedish and spanish locales, fix translations in pdf.
=> Add entries to swedish and spanish locales, fix translations in pdf

spec/graphql/resolvers/customer_resolver_spec.rb
=> misc: add customer test for salesforce id

app/services/invoices/payments/adyen_service.rb, spec/factories/payment_responses.rb
Fix adyen payments
There is a bug in Adyen payments service that uses incorrect response attributes to create a payment record.
=> fix(adyen-payments): Fix adyen payments

Gemfile, Gemfile.lock, app/models/clickhouse/base_record.rb, config/database.yml, db/clickhouse_schema.rb
On the path for high volume improvements, we are introducing the clickhouse database engine.
This PR is the first of the feature. It introduces a basic clickhouse config/model for the development environment.
=> feat(event): Basic clickhouse database config

Gemfile, Gemfile.lock, app/services/events/create_service.rb, karafka.rb, spec/services/events/create_service_spec.rb
=> feat(events): Stream events to kafka

Gemfile, Gemfile.lock
- Update sentry gems to the same version
=> misc(sentry): Update sentry gems

Gemfile.lock, db/clickhouse_migrate/20231024084411_create_events_raw.rb, db/clickhouse_migrate/20231030163703_create_events_raw_mv.rb, db/clickhouse_schema.rb
On the path for high volume improvements, we are introducing the clickhouse database engine.
This PR changes turns `events_raw#properties` field type from `string` to `Map(String, String)` and adds the `events_raw_mv` to fill the `events_raw`
=> feat(clickhouse): Add events_raw_mv to fill events_raw

db/migrate/20231107110809_undiscard_incorrectly_deleted_events.rb, db/schema.rb
This migration undiscards all events that got incorrectly discarded and that affect future invoices
=> fix (events): add migration for incorrectly discarded events

app/services/invoices/payments/adyen_service.rb, spec/services/invoices/payments/adyen_service_spec.rb
Invalid card number is raised and not handled in `Invoice::Payments::AdyenCreateJob`
Handle validation errors in `Invoices::Payments::AdyenService`
=> fix(adyen): Handle invalid card validation error

app/models/customer.rb, app/services/fees/create_pay_in_advance_service.rb, app/services/invoices/create_pay_in_advance_charge_service.rb, db/migrate/20231102141929_add_index_on_event_external_subscription_id.rb, db/schema.rb
Prepare path for https://github.com/getlago/lago-api/pull/1436
=> feat(event): Cleanup to prepare external_id only usage on events

app/controllers/api/v1/analytics/gross_revenues_controller.rb, app/graphql/resolvers/analytics/gross_revenues_resolver.rb, app/graphql/types/analytics/gross_revenues/object.rb, app/graphql/types/query_type.rb, app/models/analytics/base.rb, app/models/analytics/gross_revenue.rb, app/serializers/v1/analytics/gross_revenue_serializer.rb, config/routes.rb, schema.graphql, schema.json, spec/graphql/resolvers/analytics/gross_revenues_resolver_spec.rb, spec/graphql/types/analytics/gross_revenues/object_spec.rb, spec/models/analytics/gross_revenue_spec.rb, spec/requests/api/v1/analytics/gross_revenues_spec.rb, spec/serializers/v1/analytics/gross_revenue_serializer_spec.rb
This PR adds gross revenue model, controller, serializer and graphql resources.
=> Feat dashboard models

app/controllers/api/v1/analytics/outstanding_invoices_controller.rb, app/graphql/resolvers/analytics/outstanding_invoices_resolver.rb, app/graphql/types/analytics/outstanding_invoices/object.rb, app/graphql/types/query_type.rb, app/models/analytics/outstanding_invoice.rb, app/serializers/v1/analytics/outstanding_invoice_serializer.rb, config/routes.rb, db/schema.rb, schema.graphql, schema.json, spec/graphql/resolvers/analytics/outstanding_invoices_resolver_spec.rb, spec/graphql/types/analytics/outstanding_invoices/object_spec.rb, spec/models/analytics/outstanding_invoice_spec.rb, spec/requests/api/v1/analytics/outstanding_invoices_spec.rb, spec/serializers/v1/analytics/outstanding_invoice_serializer_spec.rb
This PR adds outstanding invoices model, controller, serializer and graphql resources.
=> Analytics outstanding invoices

app/controllers/api/v1/analytics/base_controller.rb, app/controllers/api/v1/analytics/gross_revenues_controller.rb, app/controllers/api/v1/analytics/invoiced_usages_controller.rb, app/controllers/api/v1/analytics/mrrs_controller.rb, app/controllers/api/v1/analytics/outstanding_invoices_controller.rb, app/services/analytics/base_service.rb, app/services/analytics/gross_revenues_service.rb, app/services/analytics/invoiced_usages_service.rb, app/services/analytics/outstanding_invoices_service.rb, spec/services/analytics/gross_revenues_service_spec.rb, spec/services/analytics/invoiced_usages_service_spec.rb, spec/services/analytics/outstanding_invoices_service_spec.rb
Analytics controllers are not using services to handle authorization.
This PR adds services to handle authorization for analytics controllers.
=> feat(analytics): Refactor controllers and services

app/services/payment_providers/adyen_service.rb, spec/services/payment_providers/adyen_service_spec.rb
Fix webhook error when payment provider of an organization is not found.
=> fix(adyen): Fix payment provider not found

app/services/billable_metrics/aggregations/max_service.rb, app/services/events/stores/base_store.rb, app/services/events/stores/clickhouse_store.rb, app/services/events/stores/postgres_store.rb, spec/services/events/stores/clickhouse_store_spec.rb, spec/services/events/stores/postgres_store_spec.rb, spec/spec_helper.rb
This PR is part of the  high usage event ingestion epic. It follows https://github.com/getlago/lago-api/pull/1422
The objective of the PR is to implement the `Max` aggregation at clickhouse level
=> feat(event): Clickhouse Max Aggregation

app/models/analytics/mrr.rb
=> fix(analytics): Fix MRR query

app/models/analytics/gross_revenue.rb
This PR fixes the Gross revenue query.
=> fix(analytics): Fix Gross revenue query

app/controllers/api/v1/analytics/gross_revenues_controller.rb, app/controllers/api/v1/analytics/invoice_collections_controller.rb, app/controllers/api/v1/analytics/invoiced_usages_controller.rb, app/controllers/api/v1/analytics/mrrs_controller.rb, app/models/analytics/gross_revenue.rb, spec/graphql/resolvers/analytics/gross_revenues_resolver_spec.rb, spec/requests/api/v1/analytics/gross_revenues_spec.rb
This PR fixes the Gross revenue query.
=> fix(analytics): Refactor gross revenue query

app/services/webhooks/invoices/payment_status_updated_service.rb
- Add `customer` on `invoice.payment_status_updated` webhook payload
=> imp(webhooks): Add customer on webhook invoice payment status updated

app/services/billable_metrics/aggregations/base_service.rb
This PR is part of the high event ingestion epic.
Its purpose is only to cleanup the code in aggregation service that is now obsolete due to the event store refactor.
=> misc: Cleanup base aggregation service

app/jobs/send_webhook_job.rb, app/serializers/v1/customer_serializer.rb, app/services/customers/eu_auto_taxes_service.rb, app/services/webhooks/customers/vies_check_service.rb, spec/jobs/send_webhook_job_spec.rb, spec/services/customers/eu_auto_taxes_service_spec.rb, spec/services/webhooks/customers/vies_check_service_spec.rb
- Add the `customer.vies_check` webhook
=> feat(taxes): Add Vies check webhook

app/services/invoices/create_service.rb
We recently added new service that handles invoice creation.
Adapt creation of one-off invoices with new invoice generation service.
=> feat(one-off-invoices): use new invoice generation service for creating one-off invoices

db/migrate/20231220115621_update_organization_sequential_id_index.rb, db/schema.rb
Existing index was taking into account only month, but we should also take year into account so that index can be really unique.
=> fix: update index for organization_sequential_id

app/views/helpers/money_helper.rb, app/views/templates/invoices/v4/_graduated.slim, app/views/templates/invoices/v4/_package.slim, app/views/templates/invoices/v4/_volume.slim
- Use the right Money rounding for unit prices
=> fix(invoices): Fix money rounding

Gemfile, Gemfile.lock, app/serializers/v1/invoice_serializer.rb, config/environments/development.rb
There were some N+1 queries in `InvoiceSerializer`.
We installed `bullet` gem to help us spot these queries.
This PR also fixes some of them in `InvoiceSerializer`.
=> misc(bullet): Install bullet gem and fix some N+1 queries

scripts/start.sh
Multiple self hosted users reported issues with the database migration.
The issue is related to migration not executed or taking a long time to perform. 
The but was most certainly introduce by the new database setup to allow an event database and the clickhouse setup.
This PR ensures that the API migrations are performed correctly during the startup process of the rails application.
=> fix: Migration should perform when starting the api

app/models/analytics/invoiced_usage.rb
Invoiced usage query for the analytics dashboard was not correct.
This PR fixes the invoiced usage query.
=> fix(analytics): Fix invoiced usage query

app/services/events/create_batch_service.rb, app/services/events/create_service.rb, spec/services/events/create_batch_service_spec.rb, spec/services/events/create_service_spec.rb
- Configure kafka topic
- Produce async
=> feat(high-usage): Configure kafka topic

Gemfile, Gemfile.lock, config/environments/production.rb, config/environments/staging.rb, config/initializers/lograge.rb
=> misc(configuration): configure log level

app/services/events/stores/clickhouse_store.rb
`Events::Stores::Clickhouse#grouped_max` test is flaky.
This PR uses the clickhouse deduplication logic to prevent the flaky test
=> fix(clickhouse): Refact clickhouse grouped_max to prevent flaky tests

db/clickhouse_migrate/20231026124912_create_events_raw_queue.rb, db/clickhouse_schema.rb, lib/tasks/db.rake
- Support custom kafka topic defined with env var for Clickhouse
=> feat(clickhouse): Configure Kafka topic with env var

app/services/customers/create_service.rb
It is impossible to remove sepa_debit payment method from a customer billing configuration via API.
This PR fixes Customer API to be able to update/remove payment methods from customer billing configuration.
=> fix(payment-methods): Fix updating payment provider payment methods

app/services/billable_metrics/aggregations/max_service.rb, spec/services/billable_metrics/aggregations/max_service_spec.rb
This PR applies the grouped_by logic to the max aggregation.
=> feat(grouped-by): Adapt max aggregation to return grouped aggregation

app/services/events/create_batch_service.rb, app/services/events/create_service.rb, config/database.yml, db/clickhouse_migrate/20231024084411_create_events_raw.rb, db/clickhouse_migrate/20231026124912_create_events_raw_queue.rb, db/clickhouse_migrate/20231030163703_create_events_raw_mv.rb, db/clickhouse_schema.rb, lib/tasks/db.rake
- Add Clickhouse migration paths
- Fix timestamp for events
=> feat(clickhouse): Clickhouse migration paths

app/controllers/application_controller.rb
Add database check
Implemented database checking in /health handler for enhanced system monitoring.
=> Add database check

app/controllers/api/v1/organizations_controller.rb, config/routes.rb, spec/requests/api/v1/organizations_spec.rb
- Add `GET /v1/organizations` endpoint
=> feat(organizations): Add Show endpoint

spec/scenarios/invoices/invoices_spec.rb
This PR adds scenario test that check invoice boundaries in leap year
=> misc: add scenario that checks boundaries in February for leap year

.github/workflows/spec.yml, Dockerfile, Dockerfile.dev, Gemfile, Gemfile.lock
=> misc(ruby): update to 3.2.3

app/views/helpers/fee_display_helper.rb, spec/views/helpers/fee_display_helper_spec.rb
Update grouped_by display helper
=> fix: update grouped_by display helper

app/services/invoices/customer_usage_service.rb, db/clickhouse_migrate/20231030163703_create_events_raw_mv.rb, db/clickhouse_schema.rb
- Parse JSON correctly into `Map(String,String)` without extra quote
=> fix(clickhouse): Fix clickhouse strings

app/controllers/admin/invoices_controller.rb, app/controllers/dev_tools/invoices_controller.rb, app/services/invoices/generate_pdf_service.rb, app/services/utils/pdf_generator.rb, config/routes.rb
Add route for rendering invoices as html pages in development environment: 
`GET /admin/invoices/:id`
=> misc(html-invoices): Add route for showing invoices as html

Gemfile, Gemfile.lock
- Upgrade puma to last version, increase performances and stability.
=> misc(puma): Upgrade to 6.x

app/services/payment_provider_customers/adyen_service.rb, app/services/payment_provider_customers/gocardless_service.rb, app/services/payment_provider_customers/stripe_service.rb
Add guard operators to prevent error if email is not defined
=> fix: add guard operators to prevent fail if email is not defined

app/graphql/types/organization_type.rb, app/graphql/types/safe_organization_type.rb, app/graphql/types/user_type.rb, schema.graphql, schema.json, spec/graphql/resolvers/memberships_resolver_spec.rb, spec/requests/graphql_spec.rb
- Do not expose all organization fields for memberships
=> fix(graphql): Fix potential travers on memberships

app/models/concerns/currencies.rb, schema.graphql, schema.json
Adding the JOD (Jordanian dinar) currency as available currency
=> misc(currency) add JOD

app/graphql/types/billable_metric_filters/input.rb, schema.graphql, schema.json, spec/graphql/types/billable_metrics/create_input_spec.rb, spec/graphql/types/billable_metrics/update_input_spec.rb
Make this type's name more explicit.
It is not used on Frontend side yet.
=> mics(graph) change type name

app/services/events/post_validation_service.rb, db/migrate/20240308104003_rollback_post_validation_view.rb, db/schema.rb, spec/services/events/post_validation_service_spec.rb
Fix performance issue with new `last_hour_events_mv` including filters
=> fix: Rollback post validation job with filters

app/services/fees/estimate_pay_in_advance_service.rb
Fix issue:
https://github.com/getlago/lago-api/issues/1812
=> Refactor event transaction in estimate_pay_in_advance_service.rb

spec/services/fees/estimate_pay_in_advance_service_spec.rb
This PR add missing specs for https://github.com/getlago/lago-api/pull/1813
=> misc: Add missing spec for fee estimate

config/initializers/sidekiq.rb
- Improve Sidekiq logger by using `json`
=> misc(sidekiq): use JSON Sidekiq Logger

app/models/concerns/secrets_storable.rb, app/models/concerns/settings_storable.rb, app/models/integrations/base_integration.rb, app/models/integrations/netsuite_integration.rb, app/models/organization.rb, app/models/payment_providers/base_provider.rb, db/migrate/20240403084644_add_integrations_setup.rb, db/schema.rb, spec/factories/integrations.rb, spec/models/integrations/base_integration_spec.rb, spec/models/integrations/netsuite_integration_spec.rb
Lago currently does not support accounting integrations.
This PR adds basic model and DB setup for supporting accounting integrations
=> feat (integrations): add base model and db setup for integrations

app/graphql/types/integrations/netsuite.rb, app/graphql/types/integrations/netsuite/create_input.rb, app/graphql/types/integrations/netsuite/update_input.rb, app/models/integrations/netsuite_integration.rb, app/services/integrations/netsuite/create_service.rb, app/services/integrations/netsuite/update_service.rb, schema.graphql, schema.json, spec/factories/integrations.rb, spec/graphql/mutations/integrations/netsuite/create_spec.rb, spec/graphql/mutations/integrations/netsuite/update_spec.rb, spec/graphql/resolvers/integration_resolver_spec.rb, spec/graphql/types/integrations/netsuite_spec.rb, spec/models/integrations/netsuite_integration_spec.rb, spec/services/integrations/netsuite/create_service_spec.rb, spec/services/integrations/netsuite/update_service_spec.rb
This PR adds `script_endpoint_url` to Netsuite integration.
=> feat(integrations-attributes): Add new attribute to netsuite integration

app/services/integration_collection_mappings/destroy_service.rb, app/services/integration_collection_mappings/netsuite/create_service.rb, app/services/integration_collection_mappings/netsuite/update_service.rb, app/services/integration_mappings/destroy_service.rb, app/services/integration_mappings/netsuite/create_service.rb, app/services/integration_mappings/netsuite/update_service.rb, spec/services/integration_collection_mappings/destroy_service_spec.rb, spec/services/integration_collection_mappings/netsuite/create_service_spec.rb, spec/services/integration_collection_mappings/netsuite/update_service_spec.rb, spec/services/integration_mappings/destroy_service_spec.rb, spec/services/integration_mappings/netsuite/create_service_spec.rb, spec/services/integration_mappings/netsuite/update_service_spec.rb
Currently Lago does not support accounting integrations.
This Pull request adds services for netsuite integration mappings.
=> feat(integrations-mapping): Add integration mapping services

db/migrate/20240314165306_migrate_groups_to_filters.rb
This PR fixes the group migration:
- Migrate the deleted status of a group
- Migrate the charge without group properties when BM is linked to groups
=> fix(filter): Group migration

app/graphql/resolvers/integration_collection_mappings/netsuite_collection_mappings_resolver.rb, app/graphql/resolvers/integration_mappings/netsuite_mappings_resolver.rb, schema.graphql, schema.json
This Pull adds GraphQL enums to resolvers instead of strings.
=> fix(integrations): Fix graphql enums in resolvers

db/migrate/20240423155113_add_organization_timestamp_index_on_events.rb, db/schema.rb
- Add missing index on `organization_id, timestamp` on `events` table
=> fix(events): Add Events Index on organization_id and timestamp

app/graphql/types/integrations/netsuite.rb, schema.graphql, schema.json
Simply add an available attribute to the type definition
=> misc: add netsuite connection ID to object type definition

app/graphql/mutations/auth/okta/accept_invite.rb, app/graphql/mutations/auth/okta/authorize.rb, app/services/auth/okta/authorize_service.rb, schema.graphql, schema.json, spec/graphql/mutations/auth/okta/authorize_spec.rb, spec/services/auth/okta/authorize_service_spec.rb
- We want to get an authorize URL for Okta with an invite
- Provide an authorize url for invite process
=> feat(okta): Authorize URL with invite

Gemfile, Gemfile.lock, config/initializers/karafka.rb, config/routes.rb, karafka.rb
- Add new configuration for Karafka
=> chore(karafka): add new configuration

app/graphql/types/fees/amount_details/graduated_percentage_range.rb, app/graphql/types/fees/amount_details/graduated_range.rb, schema.graphql, schema.json
=> misc(amount_details): fix attributes type definition

app/graphql/concerns/authenticable_customer_portal_user.rb, lib/tasks/permissions.rake, spec/graphql/concerns/authenticable_customer_portal_user_spec.rb, spec/graphql/mutations/customer_portal/download_invoice_spec.rb, spec/graphql/resolvers/customer_portal/customer_resolver_spec.rb, spec/graphql/resolvers/customer_portal/invoices_resolver_spec.rb, spec/graphql/resolvers/customer_portal/organization_resolver_spec.rb, spec/support/shared_examples/graphql_requirements.rb
Following #1952, this PR add tests to `AuthenticableCustomerPortalUser` and ensure that `super` is called in the `ready?` method.
=> chore(gql): Refactor and add tests to `AuthenticableCustomerPortalUser`

app/graphql/mutations/auth/okta/accept_invite.rb, app/graphql/types/auth/okta/accept_invite_input.rb, app/graphql/types/mutation_type.rb, app/services/auth/okta/accept_invite_service.rb, app/services/auth/okta/authorize_service.rb, app/services/auth/okta/base_service.rb, app/services/auth/okta/login_service.rb, lib/lago_http_client/lago_http_client/client.rb, schema.graphql, schema.json, spec/graphql/mutations/auth/okta/accept_invite_spec.rb, spec/graphql/mutations/auth/okta/login_spec.rb, spec/services/auth/okta/accept_invite_service_spec.rb, spec/services/auth/okta/authorize_service_spec.rb, spec/services/auth/okta/login_service_spec.rb
- We want to be able to signup with an invite by using Okta.
- Add logic for Okta and accept invite
=> feat(okta): add accept invite logic

Gemfile, Gemfile.lock
- Upgrade Karafka to last version
- No breaking change on our side since it's actually not used, test in development env is OK
=> chore(karafka): upgrade to 2.4.0

app/controllers/api/v1/customers_controller.rb, app/graphql/types/customers/create_customer_input.rb, app/graphql/types/customers/update_customer_input.rb, app/graphql/types/integration_customers/input.rb, app/graphql/types/integration_customers/netsuite.rb, app/services/integration_customers/create_or_update_service.rb, schema.graphql, schema.json, spec/graphql/types/integration_customers/input_spec.rb, spec/graphql/types/integration_customers/netsuite_spec.rb, spec/services/integration_customers/create_or_update_service_spec.rb
Lago currently does not support accounting integrations
This PR fixes fields related to integration customer
=> fix (accounting-integrations): Fix integrations customer graphql fields

spec/scenarios/billable_metrics/custom_aggregation_spec.rb
This PR improves the custom aggregation spec scenario to ensure that a real-life use case is fully covered by the custom aggregator
=> fix(custom_agg): Improve custom aggregation spec scenario

Gemfile, config/initializers/karafka.rb, config/routes.rb, karafka.rb
This PR updates the Karafka config in order to enable the Web UI monitoring
It follows the Karafka documentation to enable monitoring for multi app: https://karafka.io/docs/Web-UI-Multi-App/
=> misc(kafka): Add config for Web UI monitoring

app/services/events/create_service.rb, app/services/invoices/customer_usage_service.rb
- do not save events on PG when using clickhouse
=> misc(events): Do not save on PG when using clickhouse

config/database.yml
This PR enables the SSL support for clickhouse database connection.
=> misc(clickhouse): Turn on SSL support for clickhouse

app/jobs/integrations/aggregator/invoices/create_job.rb, app/jobs/integrations/aggregator/sales_orders/create_job.rb, app/models/credit_note.rb, app/models/integration_resource.rb, app/models/invoice.rb, app/models/payment.rb, db/migrate/20240514081110_create_integration_resources.rb, db/schema.rb, spec/factories/integration_resources.rb, spec/models/credit_note_spec.rb, spec/models/integration_resource_spec.rb, spec/models/invoice_spec.rb, spec/models/payment_spec.rb
This PR adds integration resource models, factories and specs
=> Integrations invoices models only

app/models/organization.rb, schema.graphql, schema.json
- Update `IntegrationTypeEnum` with `okta`
=> misc(okta): add okta in integration enum

app/services/subscriptions/dates_service.rb, spec/services/subscriptions/dates/monthly_service_spec.rb
I tried to reproduce a bug but couldn't. I believe this test is useful tho.
=> feat(tests): Test dates service with tz change during grace period

config/database.yml
- Define a pool number for Clickhouse adapter
=> misc(clickhouse): Define pool number

app/jobs/integrations/aggregator/payments/create_job.rb, app/services/integrations/aggregator/payments/create_service.rb, spec/jobs/integrations/aggregator/payments/create_job_spec.rb, spec/services/integrations/aggregator/payments/create_service_spec.rb
This PR adds `Integrations::Aggregator::Payments::CreateJob`
=> feat(integrations): Sync payments job

app/services/subscriptions/billing_service.rb
If you need to re-run billing in the past (like if the clock didn't run) or if you want to test on staging envs, it's easier to just pass `billing_at` to the billing service.
It's also more inline with what we do in other similar services.
```ruby
Subscriptions::BillingService.call 3.days.from_now
```
Today, we do it with `timecop`
```ruby
require 'timecop'
Timecop.freeze(DateTime.new(2024, 6, 20, 10)) do
Subscriptions::BillingService.call
end
```
=> feat(billing): Add billing_at arg to BillingService

app/models/integrations/base_integration.rb, app/models/integrations/xero_integration.rb, app/models/organization.rb, spec/factories/integrations.rb, spec/models/integrations/xero_integration_spec.rb, spec/models/organization_spec.rb
This PR adds new models and modifies existing ones to support Xero integration.
=> feat(xero): Add models

app/controllers/api/v1/invoices_controller.rb, app/graphql/mutations/invoices/create.rb, app/services/invoices/create_one_off_service.rb, spec/services/invoices/create_one_off_service_spec.rb
This service is only used to create one_off invoices, not all invoices.
=> chore(invoice): Rename `Invoices::CreateService` to `Invoices:CreateOneOffService`

app/jobs/integrations/aggregator/perform_sync_job.rb, app/services/integrations/netsuite/create_service.rb, app/services/integrations/netsuite/update_service.rb, app/services/integrations/xero/create_service.rb, app/services/integrations/xero/update_service.rb, spec/factories/integrations.rb, spec/jobs/integrations/aggregator/perform_sync_job_spec.rb, spec/services/integrations/aggregator/items_service_spec.rb, spec/services/integrations/xero/create_service_spec.rb, spec/services/integrations/xero/update_service_spec.rb
This PR adds services to create and update Xero integration.
=> feat(xero): Add integration services

app/controllers/application_controller.rb, config/initializers/lograge.rb
- Add `organization_id` to logs
=> misc(logs): Add Organization ID to logs

spec/services/integrations/aggregator/invoices/create_service_spec.rb
This PR fixes a flaky spec in `Integrations::Aggregator::Invoices::CreateService`
=> fix(integrations): Fix flaky spec

app/services/integrations/aggregator/invoices/base_service.rb, spec/services/integrations/aggregator/invoices/create_service_spec.rb
Fix flaky test
We need to be consistent in handling fees while preparing integration payload so that this payload can be tested
=> update aggregator invoice spec

clock.rb
Clock is broken in exception handling
Appropriate naming of variables
=> Fix exception handling

spec/scenarios/coupons_breakdown_spec.rb
This PR adds extensive coupons integration (scenario) test.
This test combines various subscriptions in the same invoice with multiple coupons (some are with limitations and some are regular ones)
=> misc: add extensive coupons integration test

app/services/integration_collection_mappings/factory.rb, app/services/integration_customers/factory.rb, app/services/integration_mappings/factory.rb, app/services/integrations/aggregator/accounts_service.rb, app/services/integrations/aggregator/base_service.rb, app/services/integrations/aggregator/sync_service.rb, spec/fixtures/integration_aggregator/accounts_response.json, spec/services/integrations/aggregator/accounts_service_spec.rb
This PR adds mapping and collection mapping services for Xero integration.
=> Feat xero mappings services

app/services/events/create_batch_service.rb, app/services/events/create_service.rb
- Add a key on the message produced to permit partitioning by key.
=> misc(kafka): Add key on message for partioning

config/initializers/sidekiq.rb
- `sidekiqmon` cause a lot of issues depending on Redis configuration
- Uses a very simple approach to check Sidekiq to Redis networking
=> misc(sidekiq): Add new monitoring system for k8s liveness probe

app/graphql/resolvers/integrations/accounts_resolver.rb, app/graphql/types/integrations/accounts/object.rb, app/graphql/types/integrations/object.rb, app/graphql/types/query_type.rb, app/models/organization.rb, app/services/integrations/xero/create_service.rb, app/services/integrations/xero/update_service.rb, schema.graphql, schema.json, spec/graphql/resolvers/integrations/accounts_resolver_spec.rb, spec/graphql/types/integrations/accounts/object_spec.rb, spec/graphql/types/integrations/subsidiaries/object_spec.rb
This PR adds GraphQL to create and update Xero integration mappings.
=> Feat xero mappings graphql

db/schema.rb
We commit schema.rb because we load CI database with it. We test migrations in a separate step.
```sh
lago exec api bin/rails db:drop db:create db:migrate:primary db:schema:dump RAILS_ENV=test
```
=> chore(schema): Commit fresh schema.rb

app/services/invoices/calculate_fees_service.rb, spec/scenarios/subscriptions/free_trial_billing_spec.rb
When using Trial period, the subscription is only billed at the end of the trial.
If the trial ends on billing day, we should invoice the subscription for the upcoming month. This part works but it didn't handle timezone. It creates issues with billing happens the day before in customer timezone
=> fix(trial): Handle timezone correct to bill subscription on billing day

app/controllers/api/v1/invoices_controller.rb, spec/requests/api/v1/invoices_controller_spec.rb
👉  https://getlago.canny.io/feature-requests/p/ability-to-export-data-from-the-user-interface
In order to effortlessly download export of invoices by non-technical users, it is required to extend the invoices filtering capabilities.
This change adds all filtering and searching available capabilities to GET /api/v1/invoices endpoint matching the GraphQL endpoint resolver.
- search_term
- payment_dispute_lost
- currency
- invoice_type
=> Add all available filters to /api/v1/invoices endpoint

db/migrate/20240701184757_add_deleted_at_to_fees.rb, db/migrate/20240711091155_add_fee_deleted_at_index.rb, db/schema.rb
Add column first, then add index without transaction.
=> fix(migrations): Split add_column and index

db/migrate/20240716153753_add_index_on_fees_pay_in_advance_event_transaction_id.rb, db/schema.rb
- Add missing index on `fees.pay_in_advance_event_transaction_id` with `deleted_at`
=> fix(fees): Add pay_in_advance_event_transaction_id index with deleted_at

app/queries/past_usage_query.rb, app/serializers/v1/invoice_serializer.rb, app/services/charges/override_service.rb, app/services/events/stores/base_store.rb, config/locales/en/charge.yml
Related to https://github.com/getlago/lago-api/pull/2257
This PR removes some remaining legacy group related logic
=> misc: Cleanup remaining group logic

db/migrate/20240722201341_add_index_to_invoices_status.rb, db/schema.rb
- Add a missing index on `invoices.status`
=> fix(invoices): Add index on status

db/migrate/20240718105718_create_integration_error_details.rb, db/schema.rb
https://www.notion.so/getlago/Dive-in-Calculate-taxes-info-for-finalized-invoices-subscription-58481b4c8a5c40b18cf86b8a800cf49d?pvs=4#62871d933e9745abb548f8c03bdb55da
As part of implementation logic to store errors received from Anrok through Nango we need a new model that would be used to store the errors
Added migration to create table for the new model
=> feat(anrok): add migration for IntegrationErrorDetails

app/services/integrations/aggregator/taxes/invoices/payload.rb, app/services/invoices/compute_amounts_from_fees.rb, app/services/invoices/retry_service.rb, spec/services/invoices/retry_service_spec.rb
Currently Lago is implementing tax integrations
This PR adds small improvements to the retry service
=> fix(tax-integrations): add small improvements to the retry service

app/services/invoices/payments/adyen_service.rb, app/services/invoices/payments/deliver_error_webhook_service.rb, app/services/invoices/payments/gocardless_service.rb, app/services/invoices/payments/stripe_service.rb
To be rebased when #2336 is merged
=> feat(webhook): Introduce `wallet_transaction.payment_failure` webhook

app/services/integrations/aggregator/invoices/payloads/netsuite.rb, spec/services/integrations/aggregator/invoices/create_service_spec.rb, spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb, spec/services/integrations/aggregator/sales_orders/create_service_spec.rb
Add `duedate` to netsuite invoice payload body.
=> feat(netsuite): Add due date to netsuite invoice

app/controllers/graphql_controller.rb, app/services/applied_coupons/create_service.rb, app/services/base_service.rb, app/services/events/validate_creation_service.rb, config/environments/development.rb, config/environments/production.rb, config/initializers/open_telemetry.rb
Improve tracing by adding spans to high-level calls. Currently this will add tracing to all `.call` calls on Service and Query objects.
=> misc(tracing) - Add custom spans to Services & GraphQLController

app/graphql/types/invoices/object.rb, app/models/error_detail.rb, app/serializers/v1/invoice_serializer.rb, app/services/invoices/retry_service.rb, spec/services/invoices/retry_service_spec.rb
Added default scope to error_details, that filters kept errors
=> Fix: add kept default scope to error_details

app/services/events/create_batch_service.rb, spec/services/events/create_batch_service_spec.rb
Adds an extra sanity check before any logic is called in the `Events::CreateBatchService`
=> fix(bulk_events) - Add #blank? check to `Events::CreateBatchService`

app/config/permissions/role-finance.yml
We want to allow finance role to create invoices
=> misc: allow finance role to create invoices

app/services/customers/eu_auto_taxes_service.rb, app/services/taxes/auto_generate_service.rb, lib/lago_eu_vat/lago_eu_vat/rate.rb, spec/lib/lago_eu_vat/rate_spec.rb, spec/services/customers/eu_auto_taxes_service_spec.rb, spec/services/taxes/auto_generate_service_spec.rb
Add support for VAT exceptions within Europe
=> feat(vat): Support EU VAT Exceptions

app/models/customer.rb, app/models/invoice.rb, app/models/payable_group.rb, app/models/payment.rb, app/models/payment_request.rb, app/serializers/v1/payment_request_serializer.rb, db/migrate/20240801134832_create_payment_requests.rb, db/migrate/20240801134833_add_index_on_payment_requests_payable_id_and_payable_type.rb, db/schema.rb, spec/factories/payment_requests.rb, spec/models/customer_spec.rb, spec/models/invoice_spec.rb, spec/models/payable_group_spec.rb, spec/models/payment_request_spec.rb, spec/models/payment_spec.rb, spec/serializers/v1/payment_request_serializer_spec.rb
The goal of this PR is to introduce a `PaymentRequest` model and its serializer.
=> feat(dunning): Introduce PaymentRequest entity

spec/services/lifetime_usages/recalculate_and_check_service_spec.rb
Fixes a small discrepancy in the specs.
=> Fix progressive billing spec

spec/scenarios/invoices/invoices_spec.rb
This PR consists of scenario test that covers subscription that is upgraded and terminated in the same month.
=> misc: add scenario test that covers subscription upgrade and termination case

app/models/organization.rb, schema.graphql, schema.json
👉  https://getlago.canny.io/feature-requests/p/progressive-billing
Add progressive_billing to IntegrationTypeEnum
=> feat(progressive-billing): Add progressive_billing to IntegrationTypeEnum

app/models/customer.rb, app/services/integrations/aggregator/contacts/payloads/netsuite.rb, spec/factories/customers.rb, spec/models/customer_spec.rb, spec/services/integrations/aggregator/contacts/create_service_spec.rb, spec/services/integrations/aggregator/contacts/payloads/netsuite_spec.rb
Revert commit that adds address to netsuite create contact payload.
=> Revert "feat(netsuite): Add shipping and billing address to create contact

app/models/customer.rb, app/models/integrations/netsuite_integration.rb, app/services/integrations/aggregator/contacts/payloads/netsuite.rb, spec/factories/customers.rb, spec/factories/integrations.rb, spec/models/customer_spec.rb, spec/models/integrations/netsuite_integration_spec.rb, spec/services/integrations/aggregator/contacts/create_service_spec.rb, spec/services/integrations/aggregator/contacts/payloads/netsuite_spec.rb
Only add address to netsuite create contact payload when it is not empty.
=> Add shipping and billing address to create contact with a fix

app/jobs/bill_subscription_job.rb
In Lago, jobs are not retried by default. We specify in each jobs what exception are suitable for retries or we re-enqueue jobs  manually.
When billing a subscription we re-enqueue the job once if it has a created a `generating` invoice. I'd like to delay the retry a little bit on billing day. The system is typically under heavy load so let's wait a few minutes.
=> feat(billing): Delay job retry on billing day

app/validators/email_validator.rb
Fix email validation logic to correctly handle valid email formats 
added I for case insensitivity
=> feat: fix email validation

app/services/integrations/aggregator/taxes/invoices/create_draft_service.rb, app/services/integrations/aggregator/taxes/invoices/create_service.rb, app/services/integrations/aggregator/taxes/invoices/payload.rb, spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb, spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb
Currently integration with tax provider Anrok is being implemented.
This PR handle case that has been uncovered yet.
If customer exists in Anrok, we should use change flow so that we don't create the same customer in Anrok again
=> fix (tax-integrations): Update flow for syncing Anrok customer

app/graphql/types/invoices/object.rb
Currently Anrok integration is being implemented
This PR fixes tax_provider_voidable in GQL context
=> fix(tax-integrations): condition for displaying sync action

app/services/webhooks/invoices/drafted_service.rb
Added error details to draft invoice serialization when sending webhooks
=> Fix(anrok): include error details when serializing drafted invoice to webhook

app/views/templates/invoices/v4.slim, app/views/templates/invoices/v4/_subscription_details.slim, app/views/templates/invoices/v4/_subscriptions_summary.slim, app/views/templates/invoices/v4/charge.slim, app/views/templates/invoices/v4/one_off.slim
Update remaining invoice templates with applied on whole invoice taxes format
=> update all invoice types with new tax views

spec/services/payment_requests/payments/adyen_service_spec.rb, spec/services/payment_requests/payments/stripe_service_spec.rb
👉
The goal of this change is to extend generate_payment_url tests to ensure the expected payload is sent to the payment providers (for stripe and adyen)
=> feat(dunning): Add payment_request.payment_failure webhook (#2501)

app/models/organization.rb, schema.graphql, schema.json
The goal of this change is to add dunning to premium integrations.
=> feat(dunning): Add dunning to premium integrations

app/models/applied_usage_threshold.rb, app/services/credits/progressive_billing_service.rb, app/services/fees/charge_service.rb, app/services/invoices/progressive_billing_service.rb, app/services/lifetime_usages/recalculate_and_check_service.rb, app/services/lifetime_usages/usage_thresholds/check_service.rb, app/services/subscriptions/progressive_billed_amount.rb, app/views/templates/invoices/v4.slim, app/views/templates/invoices/v4/_progressive_billing_details.slim, spec/factories/invoices.rb, spec/services/credits/progressive_billing_service_spec.rb, spec/services/invoices/calculate_fees_service_spec.rb, spec/services/invoices/progressive_billing_service_spec.rb, spec/services/lifetime_usages/recalculate_and_check_service_spec.rb, spec/services/subscriptions/progressive_billed_amount_spec.rb
Fix all QA remarks related to progressive billing
=> feat(ProgressiveBilling) - Fix QA remarks

app/views/templates/invoices/v4/one_off.slim
Updated one-off invoice with the same text formatting as in subscription invoice
=> Fix(PDF): align text in one-off invoice table the same way as in subscription invoice

app/services/payment_requests/payments/adyen_service.rb, spec/services/payment_requests/payments/adyen_service_spec.rb
The goal of this change is to update the status of adyen payments for payment requests.
=> feat(dunning): Add update_payment_status for adyen payments

app/graphql/types/integrations/premium_integration_type_enum.rb, app/graphql/types/organizations/current_organization_type.rb, app/models/organization.rb, app/services/integrations/anrok/create_service.rb, app/services/integrations/anrok/update_service.rb, schema.graphql, schema.json, spec/models/organization_spec.rb, spec/services/integrations/anrok/create_service_spec.rb, spec/services/integrations/anrok/update_service_spec.rb
Anrok should be under premium license and not under premium add-on license
=> feat(tax-integrations): change anrok license from add-on to premium

app/controllers/api/v1/lifetime_usages_controller.rb, spec/requests/api/v1/lifetime_usages_controller_spec.rb
Small bugfix: due to a typo usage_thresholds were not part of the API output.
=> bug(ProgressiveBilling) - make sure usage_thresholds are present 

spec/models/subscription_spec.rb
This PR adds specs for the `subscription#mark_as_active!` making sure that the lifetime usage object (including the historical usage) is transferred from a previous subscription to a newly activated one
=> misc(ProgressiveBilling): Add missing specs for lifetime usage

app/services/invoices/progressive_billing_service.rb, app/services/lifetime_usages/recalculate_and_check_service.rb, spec/services/invoices/progressive_billing_service_spec.rb, spec/services/lifetime_usages/recalculate_and_check_service_spec.rb
Lago is implementing integration with tax provider ANrok
This PR adapts progressive billing invoice generation logic with necessary changes so that it can work with Anrok.
=> feat(tax-integrations): adapt progressive billing invoice with tax provider changes

app/graphql/lago_api_schema.rb
=> Revert "misc: Disable GraphQL introspection"

app/services/integrations/aggregator/taxes/base_service.rb, app/services/integrations/aggregator/taxes/credit_notes/create_service.rb, app/services/integrations/aggregator/taxes/invoices/base_service.rb
Currently Lago is working on integration with tax provider Anrok
This PR refactors inheritance inside the aggregator scope
=> misc: refactor tax provider inheritance for the aggregator scope

app/graphql/types/customers/usage/charge.rb, app/graphql/types/customers/usage/grouped_usage.rb, schema.graphql, schema.json, spec/graphql/types/customers/usage/charge_spec.rb
Create a random ID on a plain object created “on the flight”, to ease some FE logic
=> misc: create a random id on generated plain object

app/services/payment_provider_customers/gocardless_service.rb, spec/services/payment_provider_customers/gocardless_service_spec.rb
GCL payload needs to be fixed. All attributes need to be wrapped under `payload`
=> fix: change gcl customer payload

config/locales/fr/email.yml
The goal of this change is improve the payment requested email French translation.
=> feat(dunning): update FR email copy

app/services/wallet_transactions/create_service.rb
Add forgoten place where we set metadata to hash on wallet transaction
=> fix default metadata

app/graphql/types/integrations/object.rb, graphql_schemas/api.graphql, graphql_schemas/api.json, schema.graphql, schema.json
Add HubSpot to integration types object
=> feat(hubspot): add hubspot to Integrations types

app/services/auth/okta/base_service.rb
- Remove `default` in okta oauth url
=> fix(okta): Fix okta auth url

app/services/auth/okta/authorize_service.rb
=> fix(okta): fix auth URL

app/jobs/invoices/prepaid_credit_job.rb, app/services/wallets/apply_paid_credits_service.rb, app/services/wallets/balance/increase_service.rb, spec/jobs/invoices/prepaid_credit_job_spec.rb
This PR improves how we handle race condition scenario upon wallet update
=> fix (wallets): improve handling rc upon wallet update

app/services/invoices/create_one_off_service.rb, app/services/invoices/create_pay_in_advance_charge_service.rb, app/services/invoices/progressive_billing_service.rb, spec/services/invoices/create_one_off_service_spec.rb, spec/services/invoices/create_pay_in_advance_charge_service_spec.rb, spec/services/invoices/progressive_billing_service_spec.rb, spec/services/invoices/subscription_service_spec.rb
This PR reverts https://github.com/getlago/lago-api/pull/2671
=> fix (invoice-numbering): revert draft case for new invoice numbering

app/models/organization.rb, app/services/billable_metrics/aggregation_factory.rb, app/services/events/create_service.rb, app/services/events/pay_in_advance_service.rb, app/services/invoices/customer_usage_service.rb, db/migrate/20241016133129_add_clickhouse_events_store_to_organizations.rb, db/schema.rb, spec/services/events/pay_in_advance_service_spec.rb
- add a new field `clickhouse_events_store`  on `organizations`
- `clickhouse_aggregation` will be dropped later
=> feat(clickhouse): new column for clickhouse events store on org

app/services/integrations/aggregator/contacts/payloads/netsuite.rb, spec/services/integrations/aggregator/contacts/payloads/factory_spec.rb, spec/services/integrations/aggregator/contacts/payloads/netsuite_spec.rb, spec/services/integrations/aggregator/contacts/update_service_spec.rb
The format of updating Netsuite customer changed in the restler script.
This PR changes the format of Netsuite customer update payload.
=> fix(netsuite): Fix the customer update payload

app/models/clickhouse/events_enriched.rb
This PR fixes the model annotation for the `EventEnriched` model, as it was recently refactored
=> fix(clickhouse): event_enriched model annotation

app/graphql/types/credit_notes/object.rb, app/jobs/credit_notes/provider_taxes/report_job.rb, app/models/credit_note.rb, app/views/templates/credit_note.slim, config/locales/de/credit_note.yml, config/locales/en/credit_note.yml, config/locales/es/credit_note.yml, config/locales/fr/credit_note.yml, config/locales/it/credit_note.yml, config/locales/nb/credit_note.yml, config/locales/sv/credit_note.yml
- Changed CreditNote PDF for prepaid credits
- Do not send credit note on credit to Anrok
- update tax_provider_syncable field sent to FE
=> Feat credit note fixes

app/models/fee.rb, app/queries/fees_query.rb
This scope boils down to a very expensive query. It's much faster to have PG do 2 queries and UNION them.
=> use UNION to perform faster query for 'from_organization' scope

app/models/concerns/currencies.rb, schema.graphql, schema.json
https://github.com/getlago/lago/issues/422
=> chore(currencies): Add BHD support

app/queries/invoices_query.rb
This PR removes n+1 issues from invoices index action.
=> fix: eager load invoice attachments

config/initializers/cors.rb
- Supports new `LAGO_DOMAIN` env var
=> misc(cors): Support new LAGO_DOMAIN

app/controllers/api/base_controller.rb, app/controllers/api/v1/events_controller.rb, app/graphql/types/api_keys/object.rb, app/jobs/clock/api_keys/track_usage_job.rb, app/models/api_key.rb, app/services/api_keys/track_usage_service.rb, clock.rb, db/migrate/20241101151559_add_last_used_at_to_api_keys.rb, db/schema.rb, schema.graphql, schema.json, spec/graphql/types/api_keys/object_spec.rb, spec/graphql/types/api_keys/sanitized_object_spec.rb, spec/jobs/clock/api_keys/track_usage_job_spec.rb, spec/mailers/api_key_mailer_spec.rb, spec/requests/api/base_controller_spec.rb, spec/services/api_keys/track_usage_service_spec.rb
Add ability to track when API key was last used
=> feat(api-key-management): Track when API key was last used

app/controllers/api/base_controller.rb, app/graphql/mutations/api_keys/rotate.rb, app/graphql/resolvers/api_keys_resolver.rb, app/graphql/types/api_keys/object.rb, app/models/api_key.rb, db/migrate/20241107093418_add_name_to_api_keys.rb, db/schema.rb, schema.graphql, schema.json, spec/graphql/mutations/api_keys/rotate_spec.rb, spec/graphql/types/api_keys/object_spec.rb, spec/graphql/types/api_keys/sanitized_object_spec.rb, spec/mailers/payment_request_mailer_spec.rb, spec/models/api_key_spec.rb, spec/services/api_keys/rotate_service_spec.rb
Add name to the API key model.
Add default scope to the API key.
=> feat(api-key-management): Add name to the API key model

app/services/integrations/aggregator/payments/payloads/base_payload.rb, spec/services/integrations/aggregator/payments/payloads/netsuite_spec.rb
This PR fixes a bug where the integration invoice was not scoped to its integration.
=> Fix specs and payment payload

app/graphql/types/base_argument.rb, app/graphql/types/base_field.rb, app/jobs/concerns/sentry_cron_concern.rb, app/services/billable_metrics/aggregations/latest_service.rb, app/services/billable_metrics/aggregations/max_service.rb, app/services/billable_metrics/aggregations/unique_count_service.rb, app/services/billable_metrics/aggregations/weighted_sum_service.rb, lib/tasks/tests/seed_plans.rake
This PR is the result of running `rubocop -A`.
=> misc: Fix existing rubocop issues

spec/graphql/mutations/dunning_campaigns/update_spec.rb
=> fix: failing specs

app/jobs/fees/create_pay_in_advance_job.rb, app/jobs/integrations/aggregator/credit_notes/create_job.rb, app/jobs/integrations/aggregator/invoices/create_job.rb, app/jobs/integrations/aggregator/invoices/crm/create_customer_association_job.rb, app/jobs/integrations/aggregator/invoices/crm/create_job.rb, app/jobs/integrations/aggregator/invoices/crm/update_job.rb, app/jobs/integrations/aggregator/payments/create_job.rb, app/jobs/integrations/aggregator/subscriptions/crm/create_customer_association_job.rb, app/jobs/integrations/aggregator/subscriptions/crm/create_job.rb, app/jobs/integrations/aggregator/subscriptions/crm/update_job.rb, app/jobs/invoices/create_pay_in_advance_charge_job.rb
=> Revert "Revert "fix(netsuite): Aggregator jobs should be unique (#2818)""

app/serializers/v1/tax_serializer.rb, spec/serializers/v1/tax_serializer_spec.rb
=> Revert "hotfix(taxes): Remove charges count from taxes serializer"

app/services/charge_filters/event_matching_service.rb
=> perf(EventMatchingService) - Do not use #all

app/services/charges/apply_pay_in_advance_charge_model_service.rb, app/services/charges/pay_in_advance/amount_details_calculator.rb, spec/scenarios/pay_in_advance_charges_spec.rb, spec/services/charges/pay_in_advance/amount_details_calculator_spec.rb
In fee payload for graduated_percentage pay in advance fees we want to include amount_details
Extracted a new service - `Charges::PayInAdvance::AmountDetailsCalculator` to calculate amount_details for a single event
=> Feat amount details graduated percentage

app/models/invoice_custom_section.rb, app/services/invoice_custom_sections/create_service.rb, app/services/invoice_custom_sections/select_service.rb, spec/services/invoice_custom_sections/create_service_spec.rb, spec/services/invoice_custom_sections/select_service_spec.rb
Service to create and select for organization invoice custom section
=> Feat: invoice custom section create service

app/jobs/clock/finalize_invoices_job.rb, app/jobs/invoices/finalize_job.rb
This job also belongs on the billing queue if your configuration demands it.
=> feat(BillingWorker) - move FinalizeJob to billing queue

Gemfile, Gemfile.lock, app/services/events/calculate_expression_service.rb, app/services/events/create_batch_service.rb, app/services/events/create_service.rb, spec/services/events/calculate_expression_service_spec.rb, spec/services/events/create_batch_service_spec.rb
* bump Lago-expression gem.
* Create new service Events::CalculateExpressionService.
* Use new service in both Batch and regular event creation.
=> bug(SqlExpression) - Fix batch endpoint

app/models/fee.rb
Fixed a misspelling in fee validation
=> fix misspelling in fee validation

Makefile, config/environments/staging.rb, scripts/start.api.sh, scripts/start.billing.worker.sh, scripts/start.clock.sh, scripts/start.events.worker.sh, scripts/start.pdfs.worker.sh, scripts/start.sh, scripts/start.worker.sh
use `exec` so that signals are correctly propagated to children.
=> feat(deployment) - use exec so that spawned child processes receive the right signals

app/graphql/resolvers/invoice_custom_sections_resolver.rb, app/graphql/types/query_type.rb, app/models/invoice_custom_section.rb, schema.graphql, schema.json, spec/graphql/resolvers/invoice_custom_sections_resolver_spec.rb
Next step in implementing invoice custom sections - allow FE to query invoice_custom_sections. Added InvoiceCustomSectionsResolver
=> Feat: invoice_custom_sections query resolver

app/services/invoice_custom_sections/deselect_service.rb, app/services/invoice_custom_sections/update_service.rb, spec/services/invoice_custom_sections/deselect_service_spec.rb, spec/services/invoice_custom_sections/update_service_spec.rb
We need services to update invoice_custom_sections
- Added service to update invoice_custom_section
- Added service to deselect invoice_custom_section
=> Add InvoiceCustomSections::UpdateService

app/services/integrations/aggregator/invoices/payloads/netsuite.rb, spec/services/integrations/aggregator/invoices/create_service_spec.rb, spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
=> feat(netsuite): add issuing date to NetSuite trandate payload

app/models/data_export.rb, app/services/data_exports/csv/credit_notes.rb, app/services/data_exports/export_resources_service.rb, spec/models/data_export_spec.rb, spec/services/data_exports/csv/credit_notes_spec.rb
Adding services for credit notes export
=> feat(credit-notes-export): Add services for simple credit note export

app/jobs/clock/activate_subscriptions_job.rb, app/jobs/clock/api_keys/track_usage_job.rb, app/jobs/clock/compute_all_daily_usages_job.rb, app/jobs/clock/create_interval_wallet_transactions_job.rb, app/jobs/clock/events_validation_job.rb, app/jobs/clock/finalize_invoices_job.rb, app/jobs/clock/free_trial_subscriptions_biller_job.rb, app/jobs/clock/mark_invoices_as_payment_overdue_job.rb, app/jobs/clock/process_dunning_campaigns_job.rb, app/jobs/clock/refresh_draft_invoices_job.rb, app/jobs/clock/refresh_lifetime_usages_job.rb, app/jobs/clock/refresh_wallets_ongoing_balance_job.rb, app/jobs/clock/retry_failed_invoices_job.rb, app/jobs/clock/retry_generating_subscription_invoices_job.rb, app/jobs/clock/subscriptions_biller_job.rb, app/jobs/clock/subscriptions_to_be_terminated_job.rb, app/jobs/clock/terminate_coupons_job.rb, app/jobs/clock/terminate_ended_subscriptions_job.rb, app/jobs/clock/terminate_wallets_job.rb, app/jobs/clock/webhooks_cleanup_job.rb, config/sidekiq/sidekiq.yml, config/sidekiq/sidekiq_clock.yml, scripts/start.clock.worker.sh
- Clock job should not impact other queues
- Adding a dedicated clock worker
=> chore(scalability): Add dedicated clock worker

app/jobs/send_http_webhook_job.rb, app/jobs/send_webhook_job.rb, config/sidekiq/sidekiq_webhook.yml
=> chore(scalability): Add dedicated webhook worker

app/controllers/api/v1/credit_notes_controller.rb, app/models/credit_note.rb, app/queries/credit_notes_query.rb, spec/queries/credit_notes_query_spec.rb, spec/queries/invoices_query_spec.rb, spec/spec_helper.rb
CreditNoteQuery expanded with new filter options
=> feat(credit-note-export): Add new filter options to credit note query

db/migrate/20241223144027_backfill_failed_payable_payment_status.rb, db/schema.rb
Mark all the failed payments on the new column payable_payment_status
=> feat: mark all failed on the new column

.rspec, Gemfile, Gemfile.lock, spec/models/add_on_spec.rb, spec/models/api_key_spec.rb, spec/models/applied_add_on_spec.rb, spec/models/applied_coupon_spec.rb, spec/models/applied_invoice_custom_section_spec.rb, spec/models/applied_usage_threshold_spec.rb, spec/models/coupon_spec.rb, spec/models/integration_collection_mappings/base_collection_mapping_spec.rb, spec/models/integration_item_spec.rb, spec/models/integration_mappings/base_mapping_spec.rb, spec/models/integration_resource_spec.rb, spec/models/integrations/base_integration_spec.rb, spec/models/payment_providers/base_provider_spec.rb, spec/models/quantified_event_spec.rb, spec/models/usage_threshold_spec.rb, spec/models/wallet_spec.rb, spec/models/webhook_spec.rb, spec/requests/api/v1/invoices_controller_spec.rb
Add Fuubar gem
Change `FactoryBot.create` to `FactoryBot.build` where possible
Add missing tests for PaperTrail
Add tests to some associations and validations
=> misc: Add more tests

app/jobs/integration_customers/create_job.rb, app/jobs/integration_customers/update_job.rb, schema.json
=> feat: add concurrency limit

app/services/invoices/refresh_draft_service.rb
If we have old invoice_subscriptions we can re-use that timestamp
=> perf(DraftService) - shortcut timestamp fetching if there are invoice subscriptions

app/services/integrations/aggregator/taxes/invoices/payload.rb, spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb
Don't order, as there's unneeded checking going on.
=> perf(PullAndApplyTaxes) - remove ordering

app/serializers/v1/payment_serializer.rb, spec/serializers/v1/payment_serializer_spec.rb
👉  https://getlago.canny.io/feature-requests/p/log-partial-payments
This PR adds `PaymentSerializer`
=> feat(manual-payments): Add payment serializer

app/controllers/api/v1/customers_controller.rb, app/jobs/integrations/aggregator/invoices/hubspot/create_job.rb, app/models/invoice.rb, spec/factories/organizations.rb, spec/models/invoice_spec.rb, spec/scenarios/customers/create_partner_and_run_billing_spec.rb, spec/services/invoices/subscription_service_spec.rb, spec/support/scenarios_helper.rb
=> adding tests for invoice-related updates

app/services/payment_providers/stripe/payments/create_service.rb
This PR is a fix related to the recent payment handling refactor.
It makes sure that payment attempt on stripe failing with an `Stripe::IdempotencyError`  keeps a `pending` payable payment status.
It will fix the retry handling of payment failed with an `amount_too_small` error message when a customer payment method is updated
=> fix(stripe): Idem-potency errors should keep the payment pending

spec/services/payment_providers/stripe/payments/create_service_spec.rb
This PR is an attempt to fix some flaky specs in `spec/services/payment_providers/stripe/payments/create_service_spec.rb`
=> misc(stripe): Improve payment create specs

app/queries/invoices_query.rb, spec/queries/invoices_query_spec.rb
Improvements for invoice filtering
Add ability to find invoices where particular metadata key is absent.
=> Add ability to filter invoice by absence of metadata

app/services/integrations/aggregator/base_service.rb, app/services/integrations/aggregator/credit_notes/create_service.rb, app/services/integrations/aggregator/invoices/create_service.rb, app/services/integrations/aggregator/payments/create_service.rb, spec/services/integrations/aggregator/credit_notes/create_service_spec.rb, spec/services/integrations/aggregator/invoices/create_service_spec.rb, spec/services/integrations/aggregator/payments/create_service_spec.rb
Nango is introducing API changes that could result in breaking change on Lago side.
This PR is fixing it
=> fix: adapt nango status code checks

app/models/api_key.rb, app/models/organization.rb, app/services/api_keys/create_service.rb, app/services/api_keys/update_service.rb, app/services/fees/charge_service.rb, app/services/integrations/hubspot/create_service.rb, app/services/integrations/hubspot/update_service.rb, app/services/integrations/netsuite/create_service.rb, app/services/integrations/netsuite/update_service.rb, app/services/integrations/okta/create_service.rb, app/services/integrations/okta/update_service.rb, app/services/integrations/salesforce/create_service.rb, app/services/integrations/salesforce/update_service.rb, app/services/integrations/xero/create_service.rb, app/services/integrations/xero/update_service.rb, app/services/invoices/subscription_service.rb, app/services/plans/create_service.rb, app/services/plans/override_service.rb, app/services/plans/update_service.rb, spec/graphql/mutations/api_keys/update_spec.rb, spec/models/api_key_spec.rb, spec/models/organization_spec.rb, spec/services/api_keys/update_service_spec.rb, spec/services/fees/charge_service_spec.rb, spec/services/integrations/okta/create_service_spec.rb, spec/services/integrations/okta/update_service_spec.rb, spec/services/integrations/salesforce/create_service_spec.rb, spec/services/invoices/subscription_service_spec.rb, spec/support/shared_examples/api_requirements.rb
This pull request refactors the way premium integrations are checked, and updating various service classes to use the new methods for checking premium integrations.
=> feat(data): Add premium integrations enabled methods

app/services/invoices/preview_service.rb, spec/requests/api/v1/invoices_controller_spec.rb, spec/services/invoices/preview_service_spec.rb
Invoice preview should be enabled only for premium users
=> fix(invoice-preview): disable preview feature for freemium users

.github/workflows/migrations-test.yml, .github/workflows/spec.yml
This PR fixes issues in specs and migration specs that were introduce by the recent merge of https://github.com/ClickHouse/ClickHouse/pull/75259 on clickhouse side.
The network access for the `default` user is now disabled when no password is provided.
This PR makes sure that the password is effectively provided
=> fix: clickhouse related specs

app/models/webhook_endpoint.rb
- Increase webhook endpoints limit to 10
=> imp(webhooks): Increase webhook endpoints limit to 10

app/models/invoice.rb, db/migrate/20250205184611_add_index_on_invoices_org_seq_id.rb, db/schema.rb
This index reduces the time to fetch the highest id from around 40ms to 0.4ms.
=> perf(InvoiceGeneration) - add index on invoices to speed up fetching the highest organization_sequential_id

app/graphql/types/invoice_subscriptions/object.rb
Hotfix for https://github.com/getlago/lago-api/pull/3152 and https://github.com/getlago/lago-api/pull/3157
=> hotfix(invoice): Fix graphql object rendering

app/services/integrations/aggregator/invoices/payloads/base_payload.rb, app/services/integrations/aggregator/invoices/payloads/netsuite.rb, spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb, spec/services/integrations/aggregator/invoices/payloads/xero_spec.rb
=> Revert "fix(integrations): Fix invoices with progressive billing"

config/routes.rb, karafka.rb, scripts/start.events.consumer.sh
Related to https://github.com/getlago/lago/pull/468
=> misc: Add kafka event consumer

app/models/charge.rb, db/migrate/20250214091021_add_index_to_in_advance_charges.rb, db/schema.rb
This PR is related to https://github.com/getlago/lago-api/pull/3178
The goal is to speed-up the post processing by improving the in_advance charges lookup
=> misc(charge): Index pay_in_advance charges to speed-up post processing

config/initializers/console.rb
```ruby
enable_premium_integration! "f5f71e0c-7495-4b46-abe2-d82acf54bc19", :okta
enable_all_premium_integrations! "f5f71e0c-7495-4b46-abe2-d82acf54bc19"
```
=> feat(console): Add helper to enable premium integrations

config/initializers/lograge.rb
How did I not notice this before?!
=> chore(dev): colorize logs in dev env

config/initializers/rsa_keys.rb, scripts/generate.rsa.sh, scripts/migrate.sh
- Improve RSA Keys management
- Ease the docker compose deployment
- Support files or env var
=> chore(config): Improve the RSA Keys configuration

app/services/coupons/validate_service.rb, app/services/utils/datetime.rb, app/services/validators/expiration_date_validator.rb, app/services/wallets/update_service.rb, app/services/wallets/validate_service.rb, spec/services/validators/expiration_date_validator_spec.rb, spec/services/wallets/validate_service_spec.rb
Currently, expiration date validation logic is repeated in multiple places across the codebase. This PR introduces a centralized ExpirationDateValidator in the Validators module to ensure consistency
Created Validators::ExpirationDateValidator to validate expiration dates.
Moved logic from various service classes into this reusable module.
Expiration dates being in the future using Utils::Datetime.future_date?.
=> chore(validation): Refactor Expiration Date Validation to Use Centralized Validator

Gemfile, Gemfile.lock, app/jobs/clock/activate_subscriptions_job.rb, app/jobs/clock/api_keys/track_usage_job.rb, app/jobs/clock/compute_all_daily_usages_job.rb, app/jobs/clock/create_interval_wallet_transactions_job.rb, app/jobs/clock/events_validation_job.rb, app/jobs/clock/finalize_invoices_job.rb, app/jobs/clock/free_trial_subscriptions_biller_job.rb, app/jobs/clock/inbound_webhooks_cleanup_job.rb, app/jobs/clock/inbound_webhooks_retry_job.rb, app/jobs/clock/mark_invoices_as_payment_overdue_job.rb, app/jobs/clock/process_dunning_campaigns_job.rb, app/jobs/clock/refresh_draft_invoices_job.rb, app/jobs/clock/refresh_lifetime_usages_job.rb, app/jobs/clock/refresh_wallets_ongoing_balance_job.rb, app/jobs/clock/retry_failed_invoices_job.rb, app/jobs/clock/retry_generating_subscription_invoices_job.rb, app/jobs/clock/subscriptions_biller_job.rb, app/jobs/clock/subscriptions_to_be_terminated_job.rb, app/jobs/clock/terminate_coupons_job.rb, app/jobs/clock/terminate_ended_subscriptions_job.rb, app/jobs/clock/terminate_recurring_transaction_rules_job.rb, app/jobs/clock/terminate_wallets_job.rb, app/jobs/clock/webhooks_cleanup_job.rb, config/initializers/newrelic.rb, config/initializers/sentry.rb
- Add `stackprof` to add profiling on sentry
- Only loads sentry if a key is present
- Only load newrelic if a key is present
=> chore(sentry): Add strackprof profiling with sentry

app/graphql/types/billable_metrics/object.rb
=> fix(bm): Fix counts perf in BM resolver

app/services/integrations/aggregator/credit_notes/payloads/netsuite.rb, app/services/integrations/aggregator/invoices/payloads/netsuite.rb, spec/services/integrations/aggregator/credit_notes/create_service_spec.rb, spec/services/integrations/aggregator/invoices/create_service_spec.rb, spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
This PR adds description to Netsuite invoice and credit note line items.
The value depends on the object.
=> feat(netsuite): Add description to netsuite payloads

spec/graphql/resolvers/customer_portal/customers/usage_resolver_spec.rb, spec/graphql/resolvers/customers/usage_resolver_spec.rb
=> fix: flaky tests

app/controllers/api/v1/analytics/base_controller.rb, app/controllers/api/v1/analytics/gross_revenues_controller.rb, app/controllers/api/v1/analytics/invoice_collections_controller.rb, app/controllers/api/v1/analytics/invoiced_usages_controller.rb, app/controllers/api/v1/analytics/mrrs_controller.rb, app/controllers/api/v1/analytics/overdue_balances_controller.rb, app/graphql/resolvers/analytics/gross_revenues_resolver.rb, app/graphql/resolvers/analytics/invoice_collections_resolver.rb, app/graphql/resolvers/analytics/invoiced_usages_resolver.rb, app/graphql/resolvers/analytics/mrrs_resolver.rb, app/graphql/resolvers/analytics/overdue_balances_resolver.rb, app/models/analytics/gross_revenue.rb, app/models/analytics/invoice_collection.rb, app/models/analytics/invoiced_usage.rb, app/models/analytics/mrr.rb, app/models/analytics/overdue_balance.rb, app/services/analytics/base_service.rb, schema.graphql, schema.json, spec/models/analytics/gross_revenue_spec.rb, spec/models/analytics/invoice_collection_spec.rb, spec/models/analytics/invoiced_usage_spec.rb, spec/models/analytics/mrr_spec.rb, spec/models/analytics/overdue_balance_spec.rb, spec/requests/api/v1/analytics/gross_revenues_controller_spec.rb, spec/requests/api/v1/analytics/invoice_collections_controller_spec.rb, spec/requests/api/v1/analytics/invoiced_usages_controller_spec.rb, spec/requests/api/v1/analytics/mrrs_controller_spec.rb, spec/requests/api/v1/analytics/overdue_balances_controller_spec.rb
We're working on the third step of implementation billing_entities: allowing to accept billing_entity to use in services. This PR includes billing_entity effect on analytics
- added possibility to include billing_entity_id in analytics
- added tests for analytics models
=> Feat(multientities): include billing_entity_id filter in analytics

app/jobs/invoices/create_pay_in_advance_charge_job.rb
Corrected a typo: replaced `:exponentially_longer` with the correct `:polynomially_longer` retry strategy.
=> feat: ops follow ai issue

app/graphql/types/plans/object.rb, schema.graphql, schema.json, spec/graphql/types/plans/object_spec.rb
This attribute is needed for Frontend to build logic on top
=> misc(GraphQL): add deletedAt on plans object

app/services/coupons/update_service.rb
This PR allows the edition of coupon's description when the coupon is already attached to a customer
=> fix(coupon): Allow updating description when already applied

app/controllers/api/v1/billing_entities_controller.rb, app/serializers/v1/billing_entity_serializer.rb, config/routes.rb, spec/requests/api/v1/billing_entities_controller_spec.rb, spec/serializers/v1/billing_entity_serializer_spec.rb
Added billing_entities#index and billing_entities#show endpoints
=> Feat(multientities): add API endpoints for billing_entities

app/services/charges/pay_in_advance/amount_details_calculator.rb
We're currently using `Float` when computing amount details for percentage and graduated percentage charge models.
This can lead to incorrect decimal values on invoices. The goal of this PR is to fix this by using `BigDecimal`.
=> fix: Use BigDecimal instead of Float on amount details

app/graphql/resolvers/integrations_resolver.rb, app/graphql/types/integrations/anrok.rb, app/graphql/types/integrations/avalara.rb, app/graphql/types/integrations/object.rb, app/models/organization.rb, schema.graphql, schema.json, spec/graphql/types/integrations/avalara_spec.rb, spec/models/organization_spec.rb
Currently integration with Avalara tax provider is being implemented
This PR adds base graphql type setup for connection part
=> feat(avalara-integration): add base avalara graphql connection setup

app/services/fees/create_pay_in_advance_service.rb
An issue was reported by a customer, related to pay in advance fees related to a percentage charge model with a per transaction max amount.
The in advance charge always performs two queries for the aggregation, one including the billed event and a second one excluding it. The final amount is then the difference of these two amounts. On top of that the per transaction max/min amount is also querying the DB to fetch the discreet values of each event in order to apply the min/max logic on each of them.
If the billing of an event is started and a new event is ingested in the mean time, it could lead to race condition were the new event is taken into account in some queries and not in other.
This PR enforce the transaction isolation to `repeatable_read` during the aggregation to make sure that …
=> fix(fee): Add repeatable read isolation for in advance fees creation

app/graphql/types/billing_entities/object.rb, app/serializers/v1/billing_entity_serializer.rb, app/services/fees/charge_service.rb, app/services/fees/commitments/minimum/create_service.rb, schema.graphql, schema.json, spec/serializers/v1/billing_entity_serializer_spec.rb, spec/services/fees/charge_service_spec.rb, spec/services/fees/commitments/minimum/create_service_spec.rb
Added is_default to serialized billing_entity
Updated missed services that create fees to also populate billing_entity_id
=> Feat(multientities): Small fixes at the end of step 3 implementation

app/models/billing_entity.rb, schema.graphql, schema.json, spec/graphql/types/billing_entities/email_settings_enum_spec.rb
While we were working on billing entitiy, a new email setting was added on org
added new email setting to organization
=> Feat(multientities): add setting that was added on organization

app/models/payment.rb, spec/models/payment_spec.rb
Payment#payment_method implementation was missing.
Implement the `payment_method`.
=> fix(payment-receipts): Implement missing payment_method

.github/workflows/linters.yml
Run `rails zeitwerk:check` in production rails env to make sure all code can be loaded in production.
=> bug: Add zeitwerk check to the linters

app/services/billing_entities/create_service.rb, app/services/billing_entities/taxes/apply_taxes_service.rb, app/services/billing_entities/taxes/remove_taxes_service.rb, app/services/billing_entities/update_service.rb, spec/services/billing_entities/taxes/apply_taxes_service_spec.rb, spec/services/billing_entities/taxes/remove_taxes_service_spec.rb
Taxes will be created on organization, but applied on billing_entity, so we need to create services to apply and remove taxes
=> Feat(multientities): Services to apply and remove taxes on billing entity

lib/tasks/signup.rake
Found one more place where we create an organization without billing_entity
=> Fix(multientities): one more seed org creation with billing_entity

app/graphql/resolvers/data_api/prepaid_credits_resolver.rb, app/graphql/types/data_api/prepaid_credits/object.rb, app/graphql/types/query_type.rb, app/services/data_api/prepaid_credits_service.rb, schema.graphql, schema.json, spec/fixtures/lago_data_api/prepaid_credits.json, spec/graphql/resolvers/data_api/prepaid_credits_resolver_spec.rb, spec/graphql/types/data_api/prepaid_credits/object_spec.rb, spec/services/data_api/prepaid_credits_service_spec.rb
This PR adds GraphQL for prepaid credits:
- type
- resolver
It also adds service for fetching the data
=> Prepaid credits GQL

app/graphql/types/data_api/prepaid_credits/object.rb, schema.graphql, schema.json, spec/graphql/types/data_api/prepaid_credits/object_spec.rb
This PR fixes the data types for multiple prepaid credits attributes.
=> fix(data-api): Fix prepaid credits data types

spec/organization_id_column_spec.rb
We're adding `organization_id` to all tables.
In order not to forget to add new `organization_id` to new tables, I'm adding this spec which queres the db schema.
After all tables are migrated, the expectation will be updated to `.to be_empty`.
Remove the table name every time you migrate one.
=> chore(spec): Ensure all tables have organization_id column

app/views/templates/payment_receipts/v1.slim, spec/services/payment_receipts/generate_pdf_service_spec.rb
Fixing a misspelling in payment receipt pdf generation
=> Fix(multientities): fix payment receipt pdf generation

.rubocop.yml, app/services/invoices/progressive_billing_service.rb, spec/services/invoices/progressive_billing_service_spec.rb
This PR ensures that progressive billing invoices are always created with the proper `IdempotencyRecord`, even when the tax management is configured at organization level.
=> fix(progressive_billing): Ensure IdempotencyRecord is persisted

app/controllers/api/v1/activity_logs_controller.rb, config/routes.rb, spec/requests/api/v1/activity_logs_controller_spec.rb
Examples:
The goal of this PR is to be able to fetch a specific activity log through the API.
=> feat(audit_logs): Add ActivityLogsController#show

app/support/idempotency.rb, spec/services/idempotency_spec.rb
detect when an early return happens inside the block. If this happens, we need to raise an error!
=> feat(Idempotency): Detect early returns and raise an error

app/jobs/database_migrations/populate_adjusted_fees_with_organization_job.rb, app/models/adjusted_fee.rb, app/services/adjusted_fees/create_service.rb, db/migrate/20250425123733_add_organization_id_to_adjusted_fees.rb, db/migrate/20250425124100_add_organization_id_fk_to_adjusted_fees.rb, db/migrate/20250425124305_validate_adjusted_fees_organizations_foreign_key.rb, db/structure.sql, spec/organization_id_column_spec.rb
- Reference organization on `adjusted_fees`
=> chore(organization): Add Organization Reference on Adjusted Fees

app/services/adjusted_fees/create_service.rb, app/services/adjusted_fees/destroy_service.rb, app/services/admin/organizations/update_service.rb, app/services/applied_coupons/amount_service.rb, app/services/applied_coupons/create_service.rb, app/services/applied_coupons/terminate_service.rb, spec/services/admin/organizations/update_service_spec.rb
Just a small PR to replace more `OpenStruct` results with proper `Result` objects
=> misc: Add more service results

app/jobs/database_migrations/populate_applied_coupons_with_organization_job.rb, app/models/applied_coupon.rb, app/services/applied_coupons/create_service.rb, app/services/invoices/preview_context_service.rb, db/migrate/20250425132247_add_organization_id_to_applied_coupons.rb, db/migrate/20250425134826_add_organization_id_fk_to_applied_coupons.rb, db/migrate/20250425134911_validate_applied_coupons_organizations_foreign_key.rb, db/structure.sql, spec/organization_id_column_spec.rb, spec/services/applied_coupons/create_service_spec.rb
- Add reference to organization on `applied_coupons`
=> chore(organization): Add Organization reference on Applied Coupons

app/jobs/database_migrations/populate_add_ons_taxes_with_organization_job.rb, app/models/add_on/applied_tax.rb, app/services/add_ons/apply_taxes_service.rb, db/migrate/20250425102306_add_organization_to_add_ons_taxes.rb, db/migrate/20250425102447_add_organization_id_fk_to_add_ons_taxes.rb, db/migrate/20250425102555_validates_add_ons_taxes_organizations_foreign_key.rb, db/structure.sql, spec/factories/add_on_applied_taxes.rb, spec/organization_id_column_spec.rb, spec/services/add_ons/apply_taxes_service_spec.rb
- Reference organization on `add_ons_taxes`
=> chore(organizations): Add Organization ref on add_ons_taxes

app/graphql/resolvers/customers/subscriptions_resolver.rb, spec/graphql/resolvers/customers/subscriptions_resolver_spec.rb
Fix the subscriptions resolver to not return the downgraded pending subscriptions.
=> fix: Fix resolver to not include pending downgraded  subscriptions

db/migrate/20250506170753_update_net_payment_term_on_billing_entity.rb, db/structure.sql
When creating billing_entities per organization somehow we missed the net_payment_term 😱 
Added a migration to update billing_entities with the net_payment_term
=> fix(multientities):  fulfil billing entities net_payment_term

app/controllers/api/v1/data_api/base_controller.rb, app/controllers/api/v1/data_api/usages_controller.rb, app/graphql/resolvers/data_api/usages/aggregated_amounts_resolver.rb, app/graphql/resolvers/data_api/usages_resolver.rb, app/graphql/types/data_api/usages/aggregated_amounts/object.rb, app/graphql/types/data_api/usages/object.rb, app/graphql/types/query_type.rb, app/services/data_api/usages/aggregated_amounts_service.rb, app/services/data_api/usages_service.rb, config/routes.rb, schema.graphql, schema.json, spec/fixtures/lago_data_api/usages.json, spec/fixtures/lago_data_api/usages_aggregated_amounts.json, spec/graphql/resolvers/data_api/usages/aggregated_amounts_resolver_spec.rb, spec/graphql/resolvers/data_api/usages_resolver_spec.rb, spec/graphql/types/data_api/usages/aggregated_amounts/object_spec.rb, spec/graphql/types/data_api/usages/object_spec.rb, spec/requests/api/v1/data_api/usages_controller_spec.rb, spec/services/data_api/usages/aggregated_amounts_service_spec.rb, spec/services/data_api/usages_service_spec.rb
We need to display usages graphs in the FE
This PR contains:
- service to fetch usages from Data API 
- GQL: type, resolver
- controller for the API endpoint.
=> Data API - Usages

app/controllers/api/v1/invoices_controller.rb, app/services/invoices/create_one_off_service.rb, spec/requests/api/v1/invoices_controller_spec.rb, spec/services/invoices/create_one_off_service_spec.rb
- add `skip_payment` option on Invoice creation (one off)
=> feat(invoices): Add skip_payment params for One Off Invoice

app/jobs/credit_notes/provider_taxes/report_job.rb, app/services/integrations/aggregator/taxes/credit_notes/create_service.rb, app/services/integrations/aggregator/taxes/credit_notes/payloads/avalara.rb, app/services/integrations/aggregator/taxes/credit_notes/payloads/factory.rb, spec/services/integrations/aggregator/taxes/credit_notes/payloads/avalara_spec.rb
Lago is currently working on integration with tax provider Avalara.
This PR adds Avalara specific payload for reporting credit notes
=> feat(avalara-integration): handle reporting credit notes for avalara

app/graphql/resolvers/webhook_resolver.rb, app/graphql/types/query_type.rb, schema.graphql, schema.json, spec/graphql/resolvers/webhook_resolver_spec.rb
The goal of this PR is to introduce a WebhookResolver.
It's useful for the frontend in order to select a specific webhook.
=> feat: Add webhook resolver

app/graphql/resolvers/event_resolver.rb, app/graphql/types/query_type.rb, schema.graphql, schema.json, spec/graphql/resolvers/event_resolver_spec.rb
The goal of this PR is to introduce a EventResolver.
It's useful for the frontend in order to select a specific event.
=> feat: add event resolver

app/graphql/resolvers/integrations_resolver.rb, schema.graphql, schema.json, spec/graphql/resolvers/integrations_resolver_spec.rb
Currently integration with avalara tax provider is being implemented
This change allows FE team to easier fetch all integrations filtered by certain type
=> feat(avalara-integration): add support for multiple integration types as GQL filter

.cursor/rules/rails-general.mdc
Basic Rails rules for Cursor.
Let's try to make this file as rich as possible
=> feat(dx): Introduce cursor rules

app/models/organization.rb, app/models/pricing_unit.rb, app/services/pricing_units/create_service.rb, app/services/pricing_units/update_service.rb, db/migrate/20250517100023_create_pricing_units.rb, db/structure.sql, spec/factories/pricing_units.rb, spec/models/organization_spec.rb, spec/models/pricing_unit_spec.rb, spec/services/pricing_units/create_service_spec.rb, spec/services/pricing_units/update_service_spec.rb
First step in adding support for pricing units (custom currencies).
Add PricingUnit model with services to create and update them.
=> feat(pricing-units): Add Pricing unit model and service for create and update

app/services/customers/create_service.rb, app/services/customers/destroy_service.rb, app/services/customers/update_service.rb, app/services/customers/upsert_from_api_service.rb, app/services/utils/activity_log.rb, spec/services/customers/create_service_spec.rb, spec/services/customers/destroy_service_spec.rb, spec/services/customers/update_service_spec.rb, spec/services/customers/upsert_from_api_service_spec.rb, spec/services/utils/activity_log_spec.rb
Examples:
The goal of this PR is to add customer activity logs.
=> feat(audit_logs): Activity log for Customer

db/migrate/20250520143628_update_exports_views_with_organization_id.rb, db/structure.sql, db/views/exports_applied_coupons_v02.sql, db/views/exports_charges_v02.sql, db/views/exports_credit_notes_taxes_v02.sql, db/views/exports_credit_notes_v02.sql, db/views/exports_fees_taxes_v02.sql, db/views/exports_invoices_taxes_v02.sql, db/views/exports_subscriptions_v02.sql, db/views/exports_wallet_transactions_v02.sql, db/views/exports_wallets_v02.sql
- Use new `organization_id` and remove useless joins
=> feat(exports): Update exports views with organization_id

app/queries/billable_metrics_query.rb, spec/queries/billable_metrics_query_spec.rb
See https://github.com/getlago/lago-api/pull/3658
=> fix(gql): Add DISTINCT when filtering BM per plan_id

app/services/wallets/create_interval_wallet_transactions_service.rb, spec/services/wallets/create_interval_wallet_transactions_service_spec.rb
Do not create WalletTransaction if the paid_credits is zero or negative.
=> Fix(wallet_transaction): Don't create transaction when the credits are zero or negative.  

app/services/subscriptions/activate_service.rb, app/services/subscriptions/create_service.rb, app/services/subscriptions/plan_upgrade_service.rb, app/services/subscriptions/terminate_service.rb, app/services/subscriptions/update_service.rb, spec/services/subscriptions/activate_service_spec.rb, spec/services/subscriptions/create_service_spec.rb, spec/services/subscriptions/plan_upgrade_service_spec.rb, spec/services/subscriptions/terminate_service_spec.rb, spec/services/subscriptions/update_service_spec.rb
Activity logs for subscriptions.
**It requires the code to produce activity log without a block.**
=> Subscription activity logs

app/services/events/stores/clickhouse_store.rb
Some time, with Clickhouse queries, a `Errno::ECONNRESET Connection reset by peer - SSL_connect` is raised.
This happen when the Clickhouse cluster is under eavy load and is scaled automatically.
Since these error are intermediary, this PR adds a auto-retry system (up to 3 retries) to reduce the number of errors in the following processes (billing, current usage, daily usage...)
NOTE: we should check how to address this at the Clickhouse connector level, but it is not currently possible to pass an option to enable `max_retries` on the underlying Net::HTTP client
=> fix(clickhouse): Add auto-retry logic on SSL reset error

spec/scenarios/delete_plan_spec.rb, spec/support/scenarios_helper.rb
As I'm working on scenario tests, I realize there are some issues with the helpers:
* I always hated that api call helpers didn't return the http call response.
* Also, some helpers didn't empty the queue so the behavior is "incorrect".
=> chore(spec): better scenario helpers

app/graphql/resolvers/analytics/invoice_collections_resolver.rb, app/models/analytics/invoice_collection.rb, schema.graphql, schema.json, spec/models/analytics/invoice_collection_spec.rb
Add possibility to filter by billing entity code in analytical dashboards - in invoices collections as well.
=> feat(data): Add billing entity code to invoice collections resolver

app/graphql/types/integrations/avalara.rb, app/models/integration_customers/base_customer.rb, app/services/fees/create_pay_in_advance_service.rb, app/services/fees/one_off_service.rb, app/services/integrations/aggregator/taxes/base_service.rb, app/services/invoices/calculate_fees_service.rb, app/services/invoices/compute_amounts_from_fees.rb, app/services/invoices/compute_taxes_and_totals_service.rb, app/services/invoices/customer_usage_service.rb, app/services/invoices/preview_context_service.rb, app/services/invoices/preview_service.rb, app/services/invoices/provider_taxes/pull_taxes_and_apply_service.rb, schema.graphql, schema.json, spec/graphql/types/integrations/avalara_spec.rb, spec/models/integration_customers/base_customer_spec.rb
Currently Lgao is working on integration with tax provider avalara.
This PR enables avalara feature and adds small improvements
=> feat(avalara-integration): small avalara improvements and enabling feature

app/models/coupon.rb
This PR adds some missing validations on the `Coupon` model
It includes
- status
- expiration
-  coupon_type
- frequency
=> fix(coupon): Add validation on enums

app/graphql/resolvers/data_api/mrrs_resolver.rb, app/graphql/resolvers/data_api/prepaid_credits_resolver.rb, app/graphql/resolvers/data_api/revenue_streams_resolver.rb, app/graphql/resolvers/data_api/usages/aggregated_amounts_resolver.rb, app/graphql/resolvers/data_api/usages/invoiced_resolver.rb, app/graphql/resolvers/data_api/usages_resolver.rb, schema.graphql, schema.json, spec/graphql/resolvers/data_api/usages_resolver_spec.rb
Add possibility to filter by billing entity code in analytical dashboards.
=> feat(data): Add billing entity code to resolvers

.cursor/rules/ripper_5_mode.mdc
This file will help AI Agents embedded in Cursor, VSCode, RubyMine, etc. to do better interactions in 5 steps: 
1. Research
2. Innovate
3. Plan
4. Execute
5. Review 
This address issues with agents making unasked code changes into the codebase when prompted for any help. 
Thanks Miguel for the suggestion.
=> (Misc) - Add AI Agent ripper mode instructions

app/jobs/wallets/refresh_ongoing_balance_job.rb
See this PR https://github.com/getlago/lago-api/pull/3769
=> fix(jobs): Use polynomially_longer not exponentially_longer

app/services/daily_usages/fill_history_service.rb, spec/scenarios/daily_usages/fill_history_spec.rb, spec/services/daily_usages/fill_history_service_spec.rb
Add scenario spec for backfilling historical usages.
=> misc(usages): Add spec for pre-filling historical usages

app/services/subscriptions/create_service.rb
There was a possible race condition when calling this API endpoint multiple times with the same `plan_code`:
```
POST /api/v1/subscriptions
```
Duplicate subscriptions were created 
Add lock to customer to `Subscriptions::CreateService`
=> fix(subscriptions): Fix subscriptions creation race condition

app/services/api_keys/cache_service.rb, app/services/billable_metric_filters/create_or_update_batch_service.rb, app/services/charge_filters/matching_and_ignored_service.rb, app/services/events/stores/clickhouse/weighted_sum_query.rb, app/services/events/stores/postgres/weighted_sum_query.rb, app/services/subscriptions/charge_cache_service.rb, app/services/validators/range_bounds_validator.rb, lib/tasks/signup.rake, spec/graphql/resolvers/invoices_resolver_spec.rb, spec/graphql/resolvers/memberships_resolver_spec.rb, spec/graphql/resolvers/organization_resolver_spec.rb, spec/scenarios/customers/customer_eu_taxes_spec.rb, spec/scenarios/invoices/advance_charges_taxes_spec.rb, spec/scenarios/plans/create_and_update_filters_spec.rb, spec/serializers/v1/billable_metric_expression_result_serializer_spec.rb, spec/services/customers/eu_auto_taxes_service_spec.rb, spec/services/invoices/payments/moneyhash_service_spec.rb, spec/services/payment_provider_customers/moneyhash_service_spec.rb
With updating rubocop we missed updating few files to new rules. 
Fixes almost all warnings to reducing noise when calling rubocop locally.
=> misc(rubocop): Fix existing warnings

config/initializers/sidekiq.rb
- Improve sidekiq liveness socket to listen to `0.0.0.0` instead of localhost
=> chore(sidekiq): Update liveness socket to listen to 0.0.0.0

app/services/events/stores/clickhouse_store.rb
This PR follows https://github.com/getlago/lago-api/pull/3733 but we are still seeing some
`Errno::ECONNRESET Connection reset by peer - SSL_connect`
It refactors a bit the way we handle retries as it appears that some `events.to_sql` are also hiting the database.
NOTE: this is a quick fix, a future PR will had some logic to rewrite theses queries in pure SQL to reduce this unintended queries that generates some load on the clickhouse instance
=> misc(clickhouse): Add retries on to_sql

app/services/events/stores/clickhouse/unique_count_query.rb, app/services/events/stores/clickhouse/weighted_sum_query.rb
This PR follows https://github.com/getlago/lago-api/pull/3858
It applies the same refactor to Unique Count and Weigtehd Sum aggregations queries that are built in different services
=> misc(clickhouse): Remove more to_sql from aggregation queries

.cursor/rules/dev-env.mdc, .cursor/rules/rails-general.mdc, .cursor/rules/ripper_5_mode.mdc, spec/requests/api/v1/plans_controller_spec.rb, spec/requests/api/v1/subscriptions/alerts_controller_spec.rb, spec/requests/application_controller_spec.rb, spec/support/matchers/be_not_found_error_matcher.rb
As I'm working on Feature and Entitlement, I added a few new rules to cursor. I'm extracting them in this PR.
Notice the new matcher, and the rule so cursor use it
About RIPPER MODE, I'm personally not so convinced. The diff is weird but this is because I changed it from "agent request" to "manual" in the cursor UI.
=> feat(cursor): cursor rules and new matcher!

app/models/organization.rb, app/services/events/create_batch_service.rb, spec/models/organization_spec.rb, spec/services/events/create_batch_service_spec.rb
This PR makes sure that the batch create event endpoint is working as expected when an organization relies on the Clickhouse event store
=> fix(clickhouse): Batch event end-point

config/application.rb, config/locales/pt_BR.yml, config/locales/pt_BR/commitment.yml, config/locales/pt_BR/credit_note.yml, config/locales/pt_BR/email.yml, config/locales/pt_BR/invoice.yml, config/locales/pt_BR/password_reset.yml, config/locales/pt_BR/payment_receipt.yml, config/locales/pt_BR/webhook_endpoint.yml
Adding Brazilian Portuguese (pt_BR) translation.
Related to https://github.com/getlago/lago-front/pull/2283
=> misc: Add pt_BR translation

config/locales/pt_BR/invoice.yml
When updating locale files, you must run `i18n-tasks` to clean up the file.
See community PR https://github.com/getlago/lago-api/pull/3872
=> chore(i18n): Run `i18n-tasks normalize`

app/models/event.rb, db/migrate/20250703133126_update_index_on_events.rb, db/structure.sql
Update index on events table for better performance
=> feat(events): Change index

app/services/payment_requests/payments/stripe_service.rb, spec/services/payment_requests/payments/stripe_service_spec.rb
Currently `PaymentRequests::Payments::StripeService` in certain conditions might return result with non-persisted payment on it. That creates issues in other services because they assume that payment is persisted if returned.
Particularly, this [PaymentProviders::Stripe::Webhooks::PaymentIntentSucceededService](https://github.com/getlago/lago-api/blob/b643cac6e33e0106f40423fb02917107de802d94/app/services/payment_providers/stripe/webhooks/payment_intent_succeeded_service.rb#L6) service tries to enqueue job with not saved record causing `ActiveJob::SerializationError:` exception.
Adjust service to avoid returning non-persisted payments
=> fix(payments): Prevent returning non-persisted payment in stripe service

.cursor/rules/dev-env.mdc, .cursor/rules/rails-general.mdc, spec/factories/subscriptions.rb, spec/models/subscription_spec.rb
`Subscription` model was missing some tests.
This commit adds missing tests for the `Subscription` model and update the Cursor rules to match what we expect from the model tests.
=> chore(specs): Add missing tests for `Subscription` model

app/controllers/api/v1/plans/entitlements_controller.rb, app/services/entitlement/plan_entitlements_partial_update_service.rb, config/routes.rb, spec/graphql/resolvers/payment_providers_resolver_spec.rb, spec/requests/api/v1/plans/entitlements_controller_spec.rb, spec/services/entitlement/plan_entitlements_partial_update_service_spec.rb
I realized that I implemented differently from what I planned in the Dive In.
It makes no sense to pass a feature_code in the URL since you can update multiple features.
=> fix(entitlements): Fix route for partial update of plan entitlements

spec/services/subscriptions/update_service_spec.rb
While working on the `Subscriptions::UpdateService`, I noticed some test cases missing and some tests incomplete. 
This PR adds/updates those tests.
=> test(subscription): Add more tests `Subscriptions::UpdateService`

app/controllers/api/v1/plans_controller.rb
Fix not so nice implementation added here https://github.com/getlago/lago-api/pull/3960
=> fix(plans): better plan reload

app/controllers/api/v1/payment_requests_controller.rb, app/graphql/resolvers/payment_requests_resolver.rb, app/queries/payment_requests_query.rb, schema.graphql, schema.json, spec/graphql/resolvers/payment_requests_resolver_spec.rb, spec/queries/payment_requests_query_spec.rb
This PR adds the parameter `payment_status` to PaymentRequests.
=> Filter PaymentRequests by payment_status

app/models/entitlement/feature.rb, app/services/entitlement/feature_create_service.rb, app/services/entitlement/feature_destroy_service.rb, app/services/entitlement/feature_update_service.rb, app/services/entitlement/plan_entitlement_destroy_service.rb, app/services/entitlement/plan_entitlement_privilege_destroy_service.rb, app/services/entitlement/plan_entitlements_update_service.rb, app/services/entitlement/privilege_destroy_service.rb, app/services/utils/activity_log.rb, spec/graphql/resolvers/customer_portal/customers/usage_resolver_spec.rb, spec/models/entitlement/feature_spec.rb, spec/services/entitlement/feature_create_service_spec.rb, spec/services/entitlement/feature_destroy_service_spec.rb, spec/services/entitlement/feature_update_service_spec.rb, spec/services/entitlement/plan_entitlement_destroy_service_spec.rb, spec/services/entitlement/plan_entitlement_privilege_destroy_service_spec.rb, spec/services/entitlement/plan_entitlements_update_service-full_spec.rb, spec/services/entitlement/plan_entitlements_update_service-partial_spec.rb, spec/services/entitlement/privilege_destroy_service_spec.rb
This PR adds activity logs on Feature, every time it's created, updated or destroyed.
It also create a log on each plan affected by the change
=> feat(entitlements): Add ActivityLogs for feature and entitlements

app/services/credit_notes/create_from_termination.rb, spec/services/credit_notes/create_from_termination_spec.rb
While working on adding refund capabilities to the subscription termination, I refactored some elements of the `CreditNotes::CreateFromTermination`. This refactoring was extracted to make it simpler to review.
One of the main updates is that I added some documentation of the test cases to make it easier to review and understand. It has the following format:
```
```
=> misc(subscriptions): Refactor `CreditNotes::CreateFromTermination` and its tests

db/migrate/20250718140450_create_exports_invoice_subscriptions.rb, db/structure.sql, db/views/exports_invoice_subscriptions_v01.sql
This PR adds a new export view for the `invoice_subscriptions` table
=> misc(export): Add invoice_subscription view

db/migrate/20250718174008_create_exports_payments.rb, db/structure.sql, db/views/exports_payments_v01.sql
=> feat(exports): Add payments export view

db/migrate/20250721091802_create_exports_payment_requests.rb, db/structure.sql, db/views/exports_payment_requests_v01.sql
- Add `exports_payment_requests` view
=> feat(exports): Add Payment Requests view

app/serializers/v1/entitlement/plan_entitlement_serializer.rb, app/serializers/v1/entitlement/subscription_entitlements_collection_serializer.rb, app/services/entitlement/concerns/create_or_update_concern.rb, app/services/entitlement/plan_entitlements_update_service.rb, app/services/entitlement/subscription_entitlements_update_service.rb, app/services/utils/entitlement.rb, spec/requests/api/v1/plans/entitlements_controller_spec.rb, spec/requests/api/v1/subscriptions/entitlements_controller_spec.rb, spec/services/entitlement/plan_entitlements_update_service-full_spec.rb, spec/services/entitlement/plan_entitlements_update_service-partial_spec.rb, spec/services/utils/entitlement_spec.rb, spec/support/shared_examples/api_requirements.rb
All values are stored as string. This ensure that you send the value in the correct type.
As I'm wigint these lines, I realize that it's gonna be a nightmare for graphql.
=> feat(entitlements): Add value validation

lib/templates/active_record/migration/migration.rb.tt
- Add `# frozen_string_literal: true` automatically on each new migration
=> chore(migrations): Add frozen_string_literal auto comment

config/routes.rb
This endpoint is specifically defined with PATCH line 51.
=> fix(entitlements): Remove update resource routes

app/services/events/stores/clickhouse/unique_count_query.rb, app/services/events/stores/postgres/unique_count_query.rb, app/services/events/stores/postgres_store.rb, spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb, spec/services/events/stores/clickhouse_store_spec.rb, spec/services/events/stores/postgres_store_spec.rb
=> Revert "fix(event-aggregation): the query should group prorated units by day"

app/controllers/api/v1/features/privileges_controller.rb, app/controllers/api/v1/plans/entitlements/privileges_controller.rb, app/controllers/api/v1/plans/entitlements_controller.rb, app/controllers/api/v1/subscriptions/entitlements/privileges_controller.rb, app/controllers/api/v1/subscriptions/entitlements_controller.rb, app/serializers/v1/entitlement/subscription_entitlements_collection_serializer.rb, app/services/entitlement/plan_entitlements_update_service.rb, app/services/entitlement/subscription_entitlements_update_service.rb, app/services/usage_monitoring/create_alert_service.rb, app/services/usage_monitoring/update_alert_service.rb, db/migrate/20250724104251_update_entitlement_subscription_entitlements_view.rb, db/seeds/03_entitlements.rb, db/structure.sql, db/views/entitlement_subscription_entitlements_view_v01.sql, db/views/entitlement_subscription_entitlements_view_v02.sql, spec/serializers/v1/entitlement/subscription_entitlements_collection_serializer_spec.rb
=> fix(entitlements): Fix various bugs

spec/integration/stripe/simple_payment_integration_spec.rb, spec/scenarios/plans/create_and_update_filters_spec.rb, spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb
While working on some features, I had two tests failing randomly in the CI.
This fixes those two tests.
=> test: Fix two flaky tests

app/models/fixed_charge.rb, app/models/subscription.rb, spec/models/subscription_fixed_charge_units_override_spec.rb, spec/models/subscription_spec.rb
As part of work on fixed charges, subscription will have many fixed_charges through plan and also many add_ons through fixed charges
- updated subscription model
- updated subscription model spec
=> Feat(fixed_charges-1): update subscription model

app/controllers/api/v1/payment_requests_controller.rb, config/routes.rb, spec/requests/api/v1/payment_requests_controller_spec.rb
Add `GET /api/v1/payment_requests/:id` endpoint
=> feat(api): Add GET payment_request endpoint

spec/graphql/concerns/execution_error_responder_spec.rb
Add specs for ExecutionErrorResponder
=> Add specs for ExecutionErrorResponder

app/models/fee.rb, app/services/integrations/aggregator/invoices/payloads/netsuite.rb, spec/models/fee_spec.rb, spec/services/integrations/aggregator/invoices/create_service_spec.rb, spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
We need to add a new field for NetSuite invoice creation: `item_source`
=> fix(netsuite): Fix invoice payload - add item_source

app/services/fixed_charges/destroy_service.rb, spec/services/fixed_charges/destroy_service_spec.rb
As part of fixed_charges feature, we need a service to discard fixed charges
- Added `fixed_charges/destroy_service` to discard fixed charges
=> feat(fixed_charges-6): add destroy service

app/jobs/daily_usages/fill_history_job.rb, app/models/daily_usage.rb, app/services/billable_metrics/prorated_aggregations/base_service.rb, app/services/daily_usages/fill_history_service.rb, lib/tasks/daily_usages.rake, spec/scenarios/daily_usages/fill_history_spec.rb, spec/services/billable_metrics/breakdown/sum_service_spec.rb, spec/services/billable_metrics/breakdown/unique_count_service_spec.rb, spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb, spec/services/daily_usages/fill_history_service_spec.rb
This pull request refactors the `DailyUsages::FillHistoryService` and related components to replace `datetime`-based parameters with `date`-based ones, improving consistency and simplifying the handling of date ranges.
=> fix(daily-usage): Refactor DailyUsages::FillHistoryService

app/services/plans/update_service.rb, spec/services/plans/update_service_spec.rb
this is a second part of updating plan: updating fixed charges and cascading the changes
this PR handle fixed charges creation / update / deletion and passing these changes to children
=> Feat(fixed charges 6): update plan - cascade fixed charges

app/controllers/api/v1/customers/projected_usage_controller.rb, app/graphql/resolvers/customer_portal/customers/projected_usage_resolver.rb, app/graphql/types/query_type.rb, app/models/organization.rb, schema.graphql, schema.json, spec/graphql/resolvers/customer_portal/customers/projected_usage_resolver_spec.rb, spec/graphql/types/integrations/premium_integration_type_enum_spec.rb, spec/requests/api/v1/customers/projected_usage_controller_spec.rb
This feature will be hidden behind a premium integration to test load on small customers first.
Just added the `projected_usage` string to the premium integration list.
=> feat(projected-usage): Add projected usage as premium integration

app/services/invoices/payments/retry_service.rb, spec/services/invoices/payments/retry_service_spec.rb
For some legacy reasons, we used to send invoice related webhooks and activity logs (e.g. `invoice.created`) on payment retry. This could cause confusion as users would notice multiple `invoice.created` log for the same invoice.
This removes the webhooks and activity logs.
=> fix(payment): Stop sending invoice webhooks and activity log on payment retry

app/services/events/stores/clickhouse_store.rb
This PR is an attempt to fix the `undefined method 'select_all' for nil (NoMethodError)` happening from time to time with clickhouse connection
The PR refactors the way we relies on Clikchouse connections to execute raw SQL queries to make sure that we always have an active connection.
=> fix(clickhouse): Avoid nil connections when performing queries

app/queries/credit_notes_query.rb, app/serializers/v1/credit_note_item_serializer.rb, app/serializers/v1/credit_note_serializer.rb, spec/serializers/v1/credit_note_serializer_spec.rb
=> fix: added more precision

app/services/invoices/regenerate_from_voided_service.rb, spec/services/invoices/regenerate_from_voided_service_spec.rb
Regenerated invoice (after voiding) missed some core actions like processing payment or sync with 3rd party providers
This PR adds missing actions
=> fix(invoice): add missing actions for regenerate voided invoice

Gemfile.lock
=> chore(update): update ransack gem

Gemfile.lock
Reverts getlago/lago-api#4409
Creating Stack Level too deep errors
=> Revert "chore(update): Update gem graphql-pagination"

spec/services/events/stores/clickhouse_store_spec.rb
This PR adds 2 specs to validate the event deduplication logic in order to avoid issues with clickhouse queries
- the first case validates that events with same transaction_id are kept
- the second one validates that events sharing the same transaction_id and timestamp are merged
=> misc(clickhouse): Add specs for deduplication
