getlago/lago-api

lib/lago_http_client/lago_http_client/client.rb
spec/lib/lago_http_client/client_spec.rb

Today, if we successfully deliver a webhook (HTTP 200 response code), if the response body is empty, the job fails with a `JSON::ParserError`.
The webhook has been delivered, so the job should not failed

fix: Delivered webhooks with empty response bodies should not fail

---

config/initializers/cors.rb

Before this change you had to manually edit this file in order to run
the api and front-end on a non-standard port in development. Now
LAGO_FRONT_URL will be preferred if it exists in the environment and it
will allow non-standard ports instead of just using the configured
hostname.

feat: prefer LAGO_FRONT_URL and enable urls with non-standard ports

---

app/controllers/api/v1/customers_controller.rb
app/models/customer.rb
app/models/payment_provider_customers/base_customer.rb
app/models/payment_provider_customers/stripe_customer.rb
app/models/payment_providers/base_provider.rb
app/serializers/v1/customer_serializer.rb
app/services/customers_service.rb
app/services/payment_provider_customers/create_service.rb
db/migrate/20220610134535_create_payment_provider_customers.rb
db/migrate/20220610143942_add_payment_provider_to_customers.rb
db/schema.rb
spec/factories/payment_provider_customers_factory.rb
spec/requests/api/v1/customers_spec.rb
spec/services/customers_service_spec.rb
spec/services/payment_provider_customers/create_service_spec.rb

Related to https://github.com/getlago/lago-api/issues/257
Changes:
- Add a new table `payment_provider_customers` to store customer config for payment providers.
- Update `POST api/v1/customers` API end-point to allow update of payment provider and customer_id on external payment provider (stripe)
- Send back these fields to the customer payload in API

feat: Add hability to assign stripe customer id with API

---

app/jobs/send_webhook_job.rb

This change introduces the `LAGO_WEBHOOK_ATTEMPTS` environment variable,
which will be used instead of the default of 3 when attempting to
deliver webhooks.

feat: enable configuration for webhook attempts

---

app/controllers/api/base_controller.rb
app/controllers/api/v1/events_controller.rb
app/serializers/v1/event_serializer.rb
config/routes.rb
spec/factories/event_factory.rb
spec/requests/api/v1/events_spec.rb

Implements https://github.com/getlago/lago/issues/48
Closes https://github.com/getlago/lago/issues/48

Add Event show action to the API

---

app/services/invoices/payments/stripe_service.rb
app/services/payment_provider_customers/stripe_service.rb

- Do not reprocess failed invoice, only pending
- No stripe receipt for payment

feat: Small cleanup arround stripe

---

app/models/charge.rb
app/services/invoices/customer_usage_service.rb
app/services/plans/update_service.rb
db/schema.rb
spec/services/plans/update_service_spec.rb

Allow addition of new charge to a plan even if subscriptions are using the plan

feat: Enable add charge if subscription

---

config/initializers/rsa_keys.rb

Fixes part two of https://github.com/getlago/lago-api/issues/296 and replaces #297

Use the documented variable LAGO_RSA_PRIVATE_KEY

---

app/services/payment_providers/stripe_service.rb
spec/services/payment_providers/stripe_service_spec.rb

- Fix event parsing coming from the `HandleEventJob`

fix: parse json for stripe webhook event

---

spec/rails_helper.rb

The goal is to enforce `RAILS_ENV` to be equal to `test` when running specs.
So that running `bundle exec rspec` without passing `RAILS_ENV` is loading the correct environment (not `development`).

Force setting RAILS_ENV to test in rails_helper

---

Gemfile
Gemfile.lock
config/initializers/analytics_ruby.rb

This PR is integrating the Ruby library for Segment.
And using the `SEGMENT_WRITE_KEY` based on the environment.

Integrate Ruby library for Segment

---

app/controllers/api/base_controller.rb
app/controllers/concerns/trackable.rb
app/controllers/graphql_controller.rb
config/application.rb
lib/current_context.rb
spec/controllers/concerns/trackable_spec.rb

We decided to track memberships and not users on [Segment.com](http://segment.com/) for now, as they should be authenticated to perform the actions.
Concerning the API, we only have the information about the organization, we’ll put tracking on the first created membership.
Each time a request is made (cloud or self-hosted), the membership id is now added to the current context.
This information is mandatory for sending tracking events to Segment.

Set membership context on each request

---

app/services/subscriptions/terminate_service.rb
spec/services/subscriptions/terminate_service_spec.rb

1. When customer got an active plan A and we decide to downgrade this plan B, a new line appears and the plan B is in `pending` status.
2. If we terminate the active plan A, the plan B is still in pending in the base and will be active on the next billable period
Terminating the active plan A should also cancel the pending plan B
Check for presence of pending next subscription when terminating and canceled it

fix: canceled next subscription when terminating a downgraded one

---

.github/workflows/spec.yml
app/jobs/segment_track_job.rb
app/services/billable_metrics/create_service.rb
app/services/plans/create_service.rb
app/services/users_service.rb
config/initializers/analytics_ruby.rb
spec/jobs/segment_track_job_spec.rb
spec/services/billable_metrics/create_service_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/users_service_spec.rb

The goal of this PR is to send a tracking event to Segment on:
- User registration
- Billable metric creation
- Plan creation

feat(segment): Add some tracking on Segment

---

app/services/add_ons/create_service.rb
app/services/applied_add_ons/create_service.rb
app/services/applied_coupons/create_service.rb
app/services/coupons/create_service.rb
app/services/customers/create_service.rb
app/services/subscriptions/create_service.rb
spec/services/add_ons/create_service_spec.rb
spec/services/applied_add_ons/create_service_spec.rb
spec/services/applied_coupons/create_service_spec.rb
spec/services/coupons/create_service_spec.rb
spec/services/customers/create_service_spec.rb
spec/services/subscriptions/create_service_spec.rb

The goal of this PR is to send a tracking event to Segment on:
- Customer creation
- Subscription creation
- Coupon creation
- Coupon assignment
- Addon creation
- Addon assignment

feat(segment): Add some tracking on Segment (part 2)

---

app/jobs/segment_track_job.rb
app/services/invoices/create_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/invoices/update_service.rb
spec/jobs/segment_track_job_spec.rb
spec/services/invoices/create_service_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/invoices/update_service_spec.rb

The goal of this PR is to send a tracking event to Segment on:
- Invoice creation
- Payment status change on invoice update
- Payment status change on stripe service
And use `membership/unidentifiable` as Segment user id when membership is not found (for instance when doing an action from the rails console).

feat(segment): Add some tracking on Segment (part 3)

---

app/graphql/mutations/wallet_transactions/create.rb
app/graphql/resolvers/wallet_transaction_resolver.rb
app/graphql/resolvers/wallet_transactions_resolver.rb
app/graphql/resolvers/wallets_resolver.rb
app/graphql/types/query_type.rb
app/graphql/types/wallet_transactions/object.rb
app/graphql/types/wallet_transactions/single_object.rb
app/graphql/types/wallet_transactions/status_enum.rb
app/graphql/types/wallet_transactions/transaction_type_enum.rb
app/models/customer.rb
app/models/organization.rb
app/models/wallet.rb
app/models/wallet_transaction.rb
db/migrate/20220721150658_create_wallet_transactions.rb
db/schema.rb
db/seeds.rb
schema.graphql
schema.json
spec/factories/wallet_transaction_factory.rb
spec/graphql/resolvers/wallet_transaction_resolver_spec.rb
spec/graphql/resolvers/wallet_transactions_resolver_spec.rb

**Context**
As we added `wallets` linked to a customer, we now need to prepare the logic behind the prepaid credits feature.
For this we need to add `wallet_transactions` that will represent what happen in the wallet and keep a trace of all credits movements.
**Changes**
- Add `WalletTransactions` migration
- Add GraphQL Resolvers for `walletTransactions`

feat: Add wallet transactions

---

app/jobs/segment_identify_job.rb
app/services/add_ons/create_service.rb
app/services/applied_add_ons/create_service.rb
app/services/applied_coupons/create_service.rb
app/services/billable_metrics/create_service.rb
app/services/coupons/create_service.rb
app/services/customers/create_service.rb
app/services/invoices/add_on_service.rb
app/services/invoices/create_service.rb
app/services/plans/create_service.rb
app/services/subscriptions/create_service.rb
app/services/users_service.rb
spec/graphql/mutations/login_user_spec.rb
spec/jobs/segment_identify_job_spec.rb
spec/services/add_ons/create_service_spec.rb
spec/services/applied_add_ons/create_service_spec.rb
spec/services/applied_coupons/create_service_spec.rb
spec/services/billable_metrics/create_service_spec.rb
spec/services/coupons/create_service_spec.rb
spec/services/customers/create_service_spec.rb
spec/services/invoices/add_on_service_spec.rb
spec/services/invoices/create_service_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/users_service_spec.rb

The goal of this PR is to send an identified event to Segment on:
- when the user signs up
- when the user logs in

feat(segment): Identify user on signup and signin

---

config/storage.yml

Reverts getlago/lago-api#355
@namehorn Sorry but we have to revert it for now since `ActiveStorage` do want a value for `endpoint` if you define it.
We have some work to do to make it optional on our side and not break the AWS S3 support (since with a private S3 Bucket you don't have any endpoint on AWS!)

Revert "feat: active storage: make non-aws users happy"

---

config/initializers/analytics_ruby.rb

Before this change Rails would not boot if `SEGMENT_WRITE_KEY` was not
set in the environment. Now we re-use the `LAGO_DISABLE_SEGMENT`
environment variable that was already being checked in the Segment jobs
to disable this initializer if it's set.

fix: make Segment optional

---

app/services/events/create_service.rb
app/services/invoices/customer_usage_service.rb
spec/services/events/create_service_spec.rb
spec/services/invoices/customer_usage_service_spec.rb

We want to be able to create multiple plans for a specific customer.
The goal of this PR is to fix the name of the cache key to interact with the subscription id instead of the customer id.

fix(multiple_plans): Use subscription for cache key on customer usage

---

app/services/billing_service.rb
spec/services/billing_service_spec.rb

We want to add the ability to choose to bill users at subscription date anniversary and not only on a calendar basis.
The objective of this pull request is to take anniversary subscriptions into account in the `BillingService`
It will:
- Bill weekly subscriptions on their weekly anniversary day
- Bill monthly subscriptions on their monthly anniversary day, taking into account month duration for subscription day > 28
- Bill yearly subscriptions on their yearly anniversary day, taking into account year duration for subscription = February 29th when year is not a leap year
- Bill fees for yearly subscriptions with monthly fee billing on their monthly anniversary taking into account month duration for subscription day > 28
This PR follows:
- https://github.com/getlago/lago-api/pull/352 to …

feat: Bill anniversary subscriptions

---

app/jobs/events/create_job.rb
spec/jobs/events/create_job_spec.rb

**Context**
Event job is raising validation errors linked to the Service Result. We do not want to keep dead jobs about validation errors
**Changes**
Do not raise service result errors

fix: remove result raises error on result not success

---

app/services/subscriptions/create_service.rb
lib/tasks/subscriptions.rake
spec/services/subscriptions/create_service_spec.rb

After releasing the multiple plans feature, we've seen some issues with subscription creation.
Indeed, retrieving the existing subscription was not possible.
We've stored the `customer_id` as the default value of `unique_id`.
Related issue on Slack: https://lago-community.slack.com/archives/C03MCH55EL8/p1659957452490519.

fix(multiple_plans): Set customer_id to unique_id

---

app/controllers/api/v1/customers_controller.rb
app/services/invoices/customer_usage_service.rb
spec/requests/api/v1/customers_spec.rb

With the introduction of the multiple plan feature, a regression has been identified in customer current usage on the customer API.
If the provider `customer_id` is not found or does not belongs to the organization, an error is raised in the `Invoices::CustomerUsageService` when trying to find the subscription.
Details of the error:
```
NoMethodError
undefined method `organization_ids' for nil:NilClass
```
To fix the issue, we should render a not found error as soon as possible instead of going further in the service.
Sentry issue: https://sentry.io/organizations/lago/issues/3487652425/?project=6370067 (external link)

fix(current_usage): Fix customer current usage in API when not found

---

db/migrate/20220727161448_add_customer_to_invoices.rb
db/migrate/20220809083243_fill_customer_id_on_invoices.rb
db/schema.rb

We've seen some issues where `customer_id` is not filled on `invoices`.
This, because we're calling the rake task in the same migration we're adding the column.
The goal of this PR is to call the rake task inside a new migration, so that we ensure `customer_id` is correctly populated.

fix(multiple_plans): Force filling customer id to invoices

---

.github/workflows/manual-release.yml
.github/workflows/release.yml
Dockerfile

We have some errors trying to start api's docker image because `SEGMENT_WRITE_KEY` is not packaged into the image
- Add `SEGMENT_WRITE_KEY` as Docker build arg
- Add support of Build Args for release actions
- Add a manual release action

fix: Add Segment write key into Dockerfile

---

app/services/fees/subscription_service.rb
spec/services/fees/subscription_service_spec.rb

With the new multiple plans feature,  the issuing date of the invoice have been updated to be the previous day of the invoice generation.
Before the change, in the case of a plan payed in advance, the issuing date was the invoice creation date and so the first day of the new invoice period. 
The issuing date field was used to recompute bounds of the invoice in the case of a trial period.
Before:
```ruby
issuing_date = DateTime.parse('2022-03-01')
invoiced_from_date = issuing_date // 2022-03-01
invoiced_to_date = issuing_date.end_of_month // 2022-03-31
```
After:
```ruby
issuing_date = DateTime.parse('2022-28-02')
invoiced_from_date = issuing_date // 2022-02-28
invoiced_to_date = issuing_date.end_of_month // 2022-02-28
```
Also, the code was not taking the plan interval into account, it …

fix: Fix boundaries for full period payed in advance

---

app/jobs/payment_providers/stripe/refresh_webhook_job.rb
app/services/invoices/payments/stripe_service.rb
app/services/payment_provider_customers/stripe_service.rb
app/services/payment_providers/stripe_service.rb
db/migrate/20220811155332_refresh_stripe_webhooks.rb
db/schema.rb
lib/tasks/stripe.rake
spec/fixtures/stripe/payment_method_detached_event.json
spec/jobs/payment_providers/stripe/refresh_webhook_job_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/payment_provider_customers/stripe_service_spec.rb
spec/services/payment_providers/stripe_service_spec.rb

Stripe integration is missing the payment method cleanup webhook and does not checks for the validity of the registered payment   method
If a payment method is removed from a customer on stripe dashboard, or via an API call, Lago application does not know about it and will try to use it for future payment.
This PR includes two fixes:
- handle `payment_method.detached` Stripe webhook to cleanup `PaymentProviderCustomers::StripeCustomer payment_method_id field` when a payment method is removed on Stripe side
- Check if a registered payment method still exists before processing a payment
A Complete QA will be performed both locally and on a staging branch

fix(stripe): ensure payment method is up to date

---

config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb
config/storage.yml

The `aws-s3-sdk` gem that we are using to manage document storage (for invoice) allows the usage of S3 compatible services.
This feature has been requested multiple https://github.com/getlago/lago/issues/90 and we already tried to address it (https://github.com/getlago/lago-api/pull/355) but it ended on some trouble on our cloud environment and the change was reverted.
This PR is a new attempt to address the feature by adding an alternate s3 configuration when `LAGO_AWS_S3_ENDPOINT` the environment variable is present in the configuration.
A full QA will be performed on a staging environment

feat: Allow alternate S3 compatible storages

---

app/services/customers/update_service.rb
app/services/payment_provider_customers/create_service.rb
spec/services/customers/update_service_spec.rb

When a customer has a default_payment_provider & payment_provider_customer_ID filled , if we want to remove it from the edit customer dialog, the payment_provider_customer_id remains
The issue is related to the way we are treating payment provider customers with the "create customers" option checked.
The customer related logic is performed in the `PaymentProviderCustomers::CreateService` called from the `Customers::UpdateService`.
As both services are working with two distinct instance of the same `PaymentProviderCustomers::StripeCustomer`, the response from the update service is returning the wrong value.
The fix is only to reload the provider customer

fix(customer): Fix removal of stripe customer id

---

app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/fees/charge_service.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb

We want to add the ability to:
- Apply a fixed fee per `distinct transaction`
- Apply free units on the `number of distinct transactions` or on `the monetary total amount`
This is the first step of the feature, the goal of this PR is to calculate running total from sum aggregator service.
The running total of the events is the cumulative sum of the event’s `properties.field_name`.
https://github.com/getlago/lago/issues/92
A full QA will be performed when the feature will be 100% implemented.

feat(free-units): Calculate running total on sum aggregation

---

.rubocop.yml

We're using Rubocop as our code analyzer and code formatter.
With the latest version of Rubocop (1.35.0), `IgnoredMethods` has been renamed to `AllowedMethods`.
The goal of this PR is to not have any warning message due to this change.

misc: Bump rubocop config to latest version

---

docker-compose.ci.yml

We want to add some E2E/Integration tests to Lago, we need to run an API with Github action.
The best way to to it is to work with Docker Compose.
- Create a `docker-compose.ci.yml` file for CI purposes

misc: Add Docker Compose file for CI purposes

---

app/services/subscriptions/dates/monthly_service.rb
app/services/subscriptions/dates/weekly_service.rb
app/services/subscriptions/dates/yearly_service.rb
app/services/subscriptions/dates_service.rb
spec/services/subscriptions/dates/monthly_service_spec.rb
spec/services/subscriptions/dates/weekly_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb
spec/services/subscriptions/dates_service_spec.rb

We want to add the ability to choose to bill users at subscription date anniversary and not only on a calendar basis.
Following the previous introduction of a date service (see https://github.com/getlago/lago-api/pull/360) to extract logic to compute fees boundaries, few changes are required in order to use this service in the `Fees::ChargeService` and `Fees::SubscriptionService`:
- `from_date` and `to_date`  should return the boundaries of the coming subscription period when plan is payed in advance. It will kill the need for boundaries rewriting in `Fees::SubscriptionService` (see https://github.com/getlago/lago-api/blob/main/app/services/fees/subscription_service.rb#L152 for example)
- Since `to_date` is also used for charge, a `charges_to_date` is required as charges are always billed …

feat: Add pay in advance logic into date service 

---

docker-compose.ci.yml

We have to support the CORS policy on CI environment
- Add the `LAGO_FRONT_URL` for the CI `docker-compose.ci.yml` file

misc: Add CORS origin env var for CI docker compose

---

app/services/charges/charge_models/base_service.rb
app/services/charges/charge_models/graduated_service.rb
app/services/charges/charge_models/package_service.rb
app/services/charges/charge_models/percentage_service.rb
app/services/charges/charge_models/standard_service.rb
app/services/fees/charge_service.rb
spec/services/charges/charge_models/graduated_service_spec.rb
spec/services/charges/charge_models/package_service_spec.rb
spec/services/charges/charge_models/percentage_service_spec.rb
spec/services/charges/charge_models/standard_service_spec.rb

We want to add the ability to:
- Apply a fixed fee per distinct transaction
- Apply free units on the number of distinct transactions or on the monetary total amount
This is the third step of adding fixed amount and free units to the percentage charge.
- Calculate percentage charge based on fixed amount
- Calculate percentage charge based on free units (per aggregation or per events)
https://github.com/getlago/lago/issues/92
A full QA will be performed when the feature will be 100% implemented.

feat(free-units): Calculate percentage based on fixed amount and free units

---

app/models/fee.rb
app/serializers/v1/fee_serializer.rb
app/services/charges/charge_models/base_service.rb
app/services/charges/charge_models/percentage_service.rb
app/services/fees/charge_service.rb
app/views/templates/invoice.slim
db/migrate/20220818141616_add_events_count_to_fees.rb
db/schema.rb
spec/services/charges/charge_models/percentage_service_spec.rb
spec/services/fees/add_on_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/subscription_service_spec.rb

We want to add the ability to:
- Apply a fixed fee per `distinct transaction`
- Apply free units on the `number of distinct transactions` or on `the monetary total amount`
This is the last step of adding fixed amount and free units to the percentage charge.
The goal of this PR is to update the invoice to display the number of events for a percentage charge.
https://github.com/getlago/lago/issues/92
A full QA will be performed when the feature will be 100% implemented.

feat(free-units): Add events_count on Fee and update invoice

---

app/models/charge.rb
app/services/charges/validators/volume_service.rb
config/locales/en.yml
schema.graphql
schema.json
spec/factories/charge_factory.rb
spec/models/charge_spec.rb
spec/services/charges/validators/volume_service_spec.rb

We want to introduce a new charge model to charge users based on a consumed volume.
The existing graduated pricing does not fit this need because it creates tier, and each tier has its own price.
The volume price works differently, it creates tiers, but the whole number of units is multiplied by the current tier. Then, **the number of units consumed determine the total price for each unit.**
This pull request is the first step of the volume pricing charge model.
It adds the logic to validate a charge with a `volume` charge model.

feat: Add validation logic for the volume charge model

---

app/graphql/types/invoices/object.rb
app/graphql/types/subscriptions/object.rb
app/models/invoice.rb
app/models/invoice_subscription.rb
app/models/subscription.rb
app/services/fees/charge_service.rb
app/services/fees/subscription_service.rb
app/services/invoices/create_service.rb
app/services/invoices/customer_usage_service.rb
app/services/subscriptions/dates/monthly_service.rb
app/services/subscriptions/dates/weekly_service.rb
app/services/subscriptions/dates/yearly_service.rb
app/services/subscriptions/dates_service.rb
app/views/templates/invoice.slim
schema.graphql
schema.json
spec/models/invoice_subscription_spec.rb
spec/models/subscription_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/invoices/create_service_spec.rb
spec/services/invoices/customer_usage_service_spec.rb
spec/services/subscriptions/dates/monthly_service_spec.rb
spec/services/subscriptions/dates/weekly_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb

We want to add the ability to choose to bill users at subscription date anniversary and not only on a calendar basis.
This pull request is the last one for this feature.
It uses the previously introduce `Subscriptions::DatesService` into the invoice and fees creation logic in order to make it easier to understand and to allow the usage of the `anniversary` billing time.
All date management is removed from `Invoices::CreateService`, `Fees::SubscriptionService`, `Fees::ChargeService` and `Invoices::CustomerUsageService` and delegated to the `Subscriptions::DatesService` and its subclasses
It should be merged before https://github.com/getlago/lago-api/pull/365 and https://github.com/getlago/lago-api/pull/364
A huge QA will be performed on a staging branch before merging this branch

feat: Use date service for invoice bounds

---

scripts/start.sh

Update start.sh so that the API will run in both an IPv4 and IPv6 environment. Fly.io is an example of an IPv6 env.
I'm attempting to run Lago using Fly.io, but Fly's private networking is IPv6 only. As such, I'm not able to use Lago till rails listens on both IPv4 and IPv6.
Changed the listening address from `0.0.0.0`, which is IPv4 only, to `::`, which is both IPv4 and IPv6.

Update start.sh for IPv6

---

app/controllers/api/v1/plans_controller.rb
app/graphql/types/charges/input.rb
app/graphql/types/charges/object.rb
app/graphql/types/charges/usage.rb
app/models/charge.rb
app/serializers/v1/charge_serializer.rb
app/serializers/v1/charge_usage_serializer.rb
app/services/fees/charge_service.rb
app/services/plans/create_service.rb
db/migrate/20220818151052_remove_amount_currency_null_constraint_from_charges.rb
db/schema.rb
schema.graphql
schema.json
spec/factories/charge_factory.rb
spec/graphql/mutations/plans/create_spec.rb
spec/graphql/mutations/plans/update_spec.rb
spec/graphql/resolvers/customers/usage_resolver_spec.rb
spec/requests/api/v1/plans_spec.rb
spec/serializers/v1/charge_serializer_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/update_service_spec.rb

**Context**
`amount_currency` on `Charges` is misleading and not used, it should always be the same as the plan's currency.
- Remove the `amount_currency` for `charges` in payload
- Make `amount_currency` nullable on `charges` before removing it later

Remove plan charge currency

---

config/environments/production.rb

Docker Compose default all empty env vars with an empty string.
We have to test if the env var is `true` or empty
Update the `LAGO_USE_AWS_S3` env var

fix: LAGO_USE_AWS_S3 env var usage

---

app/services/charges/charge_models/volume_service.rb
app/services/fees/charge_service.rb
spec/factories/charge_factory.rb
spec/services/charges/charge_models/volume_service_spec.rb

We want to introduce a new charge model to charge users based on a consumed volume.
The existing graduated pricing does not fit this need because it creates tier, and each tier has its own price.
The volume price works differently, it creates tiers, but the whole number of units is multiplied by the current tier. Then, the number of units consumed determine the total price for each unit.
This PR adds the core charge model logic.
This PR follows https://github.com/getlago/lago-api/pull/394

feat: Implement volume pricing charge model logic

---

app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/charges/charge_models/percentage_service.rb
app/services/fees/charge_service.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/charges/charge_models/percentage_service_spec.rb

We've added the ability to:
- Apply a fixed fee per `distinct transaction`
- Apply free units on the `number of distinct transactions` or on `the monetary total amount`
But when a user does not set any free units on events, only for total aggregation, an issue is present when calculating the running total.
The goal of this PR is to includes all the events in running total, even without free units per events.
https://github.com/getlago/lago/issues/92

fix(free-units): Includes all the events in running total

---

app/graphql/concerns/charge_model_attributes_handler.rb
app/graphql/types/charges/input.rb
app/graphql/types/charges/object.rb
app/graphql/types/charges/volume_range.rb
app/graphql/types/charges/volume_range_input.rb
schema.graphql
schema.json
spec/graphql/mutations/plans/create_spec.rb
spec/graphql/mutations/plans/update_spec.rb

We want to introduce a new charge model to charge users based on a consumed volume.
The existing graduated pricing does not fit this need because it creates tier, and each tier has its own price.
The volume price works differently, it creates tiers, but the whole number of units is multiplied by the current tier. Then, the number of units consumed determine the total price for each unit.
This PR updates the GraphQL schema to allow creation, update and query of the Volume charge model.
- A new `VolumeRange` type is added to handle range definition. Attributes are `fromValue`, `toValue`, `perUnitAmount` and `flatAmount` 
- The `Charge` type is updated to add a new `volumeRanges` attribute as an array of `VolumeRange`
- A new `VolumeRangeInput` type is added to handle range creation and …

feat: Update GraphQL schema to create or update charges

---

app/controllers/api/v1/subscriptions_controller.rb

The subscription index is not scoped to the organization.
- Scope the subscription index to the `current_organization`

fix: Hotfix subscription index

---

app/controllers/api/v1/plans_controller.rb
spec/requests/api/v1/plans_spec.rb

The objective of this PR is to ensure that a call to `POST /api/v1/plans` or `PUT /api/v1/plans/:id` without a charges attribute in the plan payload does not result in a server error (`HTTP 500`)

fix(charge): Prevent issue with plan create/update and empty charges

---

app/graphql/types/customers/single_object.rb
schema.graphql
schema.json
spec/graphql/resolvers/customer_resolver_spec.rb

We need to add the customer currency at the customer object level for GraphQL
- Add the customer currency for the graphql Object

feat: add Currency at Customer level for GraphQL

---

app/jobs/segment_identify_job.rb
spec/jobs/segment_identify_job_spec.rb

We need the membership email on Self Hosted for tracking purpose.
NOTE: This is included in our Privacy Policy.
Add the membership's email on Segment tracking for self hosted

misc: Add email for segment identify on self hosted

---

Gemfile
Gemfile.lock
config/initializers/activejob_traceable.rb

We want to keep tracing information on active jobs.
The goal of this PR is to include [activejob-traceable](https://github.com/qonto/activejob-traceable) so that `CurrentContext.membership` is also available in background jobs.

misc: Add activejob-traceable to have context on active jobs

---

app/services/fees/subscription_service.rb
spec/services/fees/subscription_service_spec.rb

- When using a trial period with a pay in advance plan, with an anniversary subscription, the daily price is wrong.
- Use the correct date for daily price calculating.
We QAed it and it's all good now!

fix: Subscription anniversary date with trial amount

---

app/controllers/api/v1/wallets_controller.rb
spec/requests/api/v1/wallets_spec.rb

We want to clarify the difference between lago ids and external ids.
- rename `customer_id` to `external_customer_id` on wallets

misc: Rename customer_id to external_customer_id on wallets

---

app/services/invoices/create_service.rb
spec/services/invoices/create_service_spec.rb

With we introduce the anniversary date subscription billing, we made a change in the way we bill charges. 
Before the feature, the charges were not billed on the terminated subscription, but only at the end of the upgraded subscription period.
We decided to get rid of this behavior because it was a mess for the billing period computation and was kind of a weird behavior, that's why 
Unfortunately, we forgot to remove one condition in the `Invoices::CreateService` to check if charge fees should be generated.
This PR is here to fix this mistake

fix(subscriptions): Apply charge fees on subscription upgrade

---

app/serializers/v1/wallet_serializer.rb
spec/requests/api/v1/wallets_spec.rb

We want to clarify the difference between lago ids and external ids.
- return `external_customer_id` on wallet serializer

misc: Add external_customer_id on wallet serializer

---

app/models/customer.rb
app/models/persisted_metric.rb
db/migrate/20220829094054_create_persisted_metrics.rb
db/schema.rb
spec/factories/persisted_metrics.rb
spec/models/persisted_metric_spec.rb

This pull request is the first for this topic. Its objective is to introduce the new PersistedMetric model that will be used later by the recurring_count aggregation.

feat(persisted-metrics): Add Persisted metric model

---

app/models/billable_metric.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
app/services/fees/charge_service.rb
schema.graphql
schema.json

This pull request adds the new `recurring_count_agg` aggregation type and exposes it for creation, update and display in API and GraphQL.
It does not implment yet the aggregation logic, it will come in a following pull request.
- New `PersistedMetric` model: https://github.com/getlago/lago-api/pull/414

feat(persisted-metrics): Add new type of aggregation

---

app/models/persisted_metric.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
app/services/subscriptions/dates_service.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb
spec/services/subscriptions/dates/monthly_service_spec.rb
spec/services/subscriptions/dates/weekly_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb
spec/services/subscriptions/dates_service_spec.rb

This PR is adding the aggregation logic. It uses the previously introduced `PersistedMetric`.
The logic takes into account:
- persisted metrics added before the period and not terminated or terminated after the period
- persisted metrics added during the period
- persisted metrics removed during the period
- persisted metrics added and removed during the period
- subscription terminated (or upgraded) before the end of the period
- subscription started before the beginning
- PersistedMetric model: https://github.com/getlago/lago-api/pull/414
- New aggregation type: https://github.com/getlago/lago-api/pull/415

feat(persisted-metrics): Aggregation logic implementation

---

app/models/customer.rb
app/models/persisted_event.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
db/migrate/20220905095529_rename_persisted_metrics_into_persisted_events.rb
db/schema.rb
spec/factories/persisted_events.rb
spec/models/persisted_event_spec.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb

This PR rename the previously added `PersistedMetrics` into `PersistedEvents` to make it more obvious it's related to events and not a new kind of metric definition

feat(persisted-metrics): Rename PersistedMetric into PersistedEvent

---

app/models/billable_metric.rb
app/models/persisted_event.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
db/migrate/20220905142834_add_billable_metric_id_to_persisted_events.rb
db/schema.rb
spec/factories/persisted_events.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb

This PR is a fix to add a foreign key on the persisted event table to point to a billable metric. Without this relation, all metrics are taken into account for all billable metrics, leading to an inconsistent billing...

fix(persisted-metrics): Add relation between billable metric and persisted events

---

app/controllers/api/v1/customers_controller.rb
config/routes.rb
spec/requests/api/v1/customers_spec.rb

We do not have any endpoints to list organization's customer or search for a customer on the API.
- Add the `/customers` index endpoint
- Add the `/customers/:customer_id` show endpoint

feat(customers): Add index and show on API

---

app/models/invoice.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
app/services/subscriptions/dates/monthly_service.rb
app/services/subscriptions/dates/weekly_service.rb
app/services/subscriptions/dates/yearly_service.rb
app/services/subscriptions/dates_service.rb
app/views/templates/invoice.slim
db/schema.rb
spec/factories/billable_metric_factory.rb
spec/factories/fee_factory.rb
spec/models/invoice_spec.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb
spec/services/subscriptions/dates/monthly_service_spec.rb
spec/services/subscriptions/dates/weekly_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb
spec/services/subscriptions/dates_service_spec.rb

The objective of this pull request is to update the PDF invoice in order to render the breakdown of the persisted metrics:
- Items billed on the full period
- Items added during the period
- Items remove during the period
- Items added and then remove during the same period
- Event ingestion logic: https://github.com/getlago/lago-api/pull/429
- Aggregation logic for the recurring persisted metrics: https://github.com/getlago/lago-api/pull/421

feat(persisted-metrics): Add persisted metric breakdown on the invoice

---

app/services/events/create_batch_service.rb
app/services/events/create_service.rb
app/services/events/validate_creation_service.rb
app/services/persisted_events/create_or_update_service.rb
app/services/persisted_events/validate_creation_service.rb
spec/services/events/create_batch_service_spec.rb
spec/services/events/create_service_spec.rb
spec/services/events/validate_creation_service_spec.rb
spec/services/persisted_events/create_or_update_service_spec.rb
spec/services/persisted_events/validate_creation_service_spec.rb
spec/services/wallets/validate_service_spec.rb

This PR updates the event creation logic to manage as well the persistent metrics:
- Create a persistent metric when receiving an `add` operation
- Remove an existing persistent metric when receiving a `remove` operation
- Validate the persisted metrics requirements before processing the event
**NOTE: We should wait for the merge of https://github.com/getlago/lago-api/pull/419 since `Subscription#unique_id` will be renamed into `Subscription#external_id`**
Aggregation logic: https://github.com/getlago/lago-api/pull/421

feat(persisted-metrics): Create persisted event from event

---

app/controllers/api/base_controller.rb
app/controllers/api/v1/add_ons_controller.rb
app/controllers/api/v1/billable_metrics_controller.rb
app/controllers/api/v1/coupons_controller.rb
app/controllers/api/v1/customers_controller.rb
app/controllers/api/v1/events_controller.rb
app/controllers/api/v1/invoices_controller.rb
app/controllers/api/v1/plans_controller.rb
app/controllers/api/v1/subscriptions_controller.rb
app/controllers/api/v1/wallets_controller.rb
app/controllers/application_controller.rb
app/controllers/concerns/api_responses.rb
config/routes.rb
spec/requests/application_spec.rb

Current Rails configuration is missing a proper handling of HTTP 500 and 404 errors.
Both where not sending empty responses.
This PR :
- Adds 404 error handling for:
- ActionController::RoutingError
- ActiveRecord::RecordNotFound
- Force request to JSON format, in order for Rails to use built-in 500 response
- Add a "catch all" route to respond 404 when users tries to access

feat(api): Handle 500 and 404 global errors

---

app/graphql/concerns/execution_error_responder.rb
spec/graphql/mutations/customers/create_spec.rb

Details for `unprocessable_entity` error was lost recently with the introduction of the wallet feature.
As a result, it was not possible anymore for the front end to display validation errors.
This PR fixes the regression and adds a test case for this scenario.

fix(errors): Fix error details for GraphQL mutations

---

app/controllers/api/base_controller.rb
app/graphql/concerns/execution_error_responder.rb
app/services/base_service.rb
app/services/billable_metrics/destroy_service.rb
app/services/coupons/destroy_service.rb
app/services/customers/destroy_service.rb
app/services/plans/destroy_service.rb
spec/requests/api/v1/billable_metrics_spec.rb
spec/requests/api/v1/coupons_spec.rb
spec/requests/api/v1/plans_spec.rb
spec/services/billable_metrics/destroy_service_spec.rb
spec/services/coupons/destroy_service_spec.rb
spec/services/customers/destroy_service_spec.rb
spec/services/plans/destroy_service_spec.rb

The objective of this pull request is to normalize the way services return method not allowed errors.
When a service action cannot be performed because the status is invalid or the pre-conditions are not met, the service keeps returning a failed as it was doing before. But instead of a code and a message attached to the result, we now build a `BaseService::MethodNotAllowedFailure` with a code attribute and we attach it as the error field of the result object.
- At API controller level, when a service result has a `BaseService::MethodNotAllowedFailure`, it will format an HTTP 405 response with the error code in the payload
- At GraphQL level, it formats a `GraphQL::ExecutionError`, with …

feat(errors): Handle not allowed error in services API and GraphQL errors

---

app/graphql/concerns/execution_error_responder.rb
app/services/invites/revoke_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/memberships/revoke_service.rb
spec/graphql/mutations/invites/revoke_spec.rb
spec/graphql/mutations/memberships/revoke_spec.rb
spec/services/invites/revoke_service_spec.rb
spec/services/memberships/revoke_service_spec.rb

Following previous PR https://github.com/getlago/lago-api/pull/442 and https://github.com/getlago/lago-api/pull/444, this one aims to turn more simple `fail!` service errors into typed errors

feat(error): Turn more service errors into not found or not allowed

---

app/controllers/concerns/pagination.rb

We want to increase the default pagination on API from `10` to `100`.
For GraphQL, it remains the same value, `25`.

misc: Update default per page from 10 to 100

---

config/routes.rb

Hotfix to avoid catching inner ActiveStorage routes with the "Catch all" route added to render json 404

fix: Avoid catching ActiveStorage routes with catch_all

---

.github/workflows/pronto.yml
app/graphql/types/membership_type.rb
schema.graphql
schema.json

This PR aims to udpate the membership type definition.
--
The membership has 2 `belongs_to` relationships with `user` and `organization`.
In the type definition we were defining the fields to return those relations' ids.
Now it's defining the Objects themself so they can be properly used and query using graphQL (so `memberhip.user` will now work on client side.)

Membership - return object instead of relation id

---

app/serializers/v1/subscription_serializer.rb
spec/requests/api/v1/subscriptions_spec.rb

We want to add the `previous_plan_code` and `next_plan_code` to the subscription object.

feat: Add previous and next plan code to subscription object

---

app/serializers/v1/subscription_serializer.rb
spec/requests/api/v1/subscriptions_spec.rb

We want to add the `previous_external_id` and `next_external_id` to the subscription object.

feat: Add previous and next external id to subscription object

---

app/services/invoices/customer_usage_service.rb

We have received few errors lately with the cache expiration computation for customer usage
These errors are raised by Redis (`Redis::CommandError - ERR invalid expire time in 'set' command`) when trying to write down the usage into the cache with the expiration key.
The goal of this PR is to make sure that the expiration duration is never 0 or negative to prevent Redis from raising the error

fix: Fix cache expiration result for customer current usage

---

app/services/base_service.rb
app/services/base_validator.rb
app/services/invites/validate_service.rb
app/services/subscriptions/create_service.rb
app/services/wallet_transactions/validate_service.rb
app/services/wallets/validate_service.rb
spec/services/invites/create_service_spec.rb
spec/services/invites/validate_service_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/wallet_transactions/create_service_spec.rb
spec/services/wallet_transactions/validate_service_spec.rb
spec/services/wallets/create_service_spec.rb
spec/services/wallets/validate_service_spec.rb

The objective of this pull request is to normalize the way services return data validation errors.
When a service action cannot be performed because the custom pre-conditions are not met, the service keeps returning a failed error as it was doing before. But instead of a list of error codes and custom "unprocessable entity we are now building a `BaseService::ValidationFailure` with a list of error messages for each fields (or base if not for a specific field) and we attach it as the error field of the result object.
This new behavior is now used in the custom service validators
**NOTE:** The result of wallet validators changed a bit, it as an impact on the front end and should be fixed …

feat(errors): Turn manualy raised unprocessable_entity errors into ValidationFailure

---

app/controllers/api/v1/invoices_controller.rb
spec/requests/api/v1/invoices_spec.rb

The goal of this PR is to be able to filter invoices by `external_customer_id` instead of `customer_id`.

fix: Ability to filter invoices by external customer id

---

app/graphql/types/subscriptions/object.rb
app/models/subscription.rb
app/serializers/v1/subscription_serializer.rb
spec/models/subscription_spec.rb
spec/requests/api/v1/subscriptions_spec.rb

When a downgrade is made, `external_id` is copied from the original to the new subscription.
Instead of returning `external_id`, we want to return the downgrade plan date of the subscription in the API.

feat: Return downgrade plan date instead of next and previous external id

---

app/graphql/mutations/customers/create.rb
app/graphql/mutations/customers/update.rb
app/graphql/types/customers/object.rb
app/models/customer.rb
app/services/base_service.rb
app/services/customers/create_service.rb
app/services/customers/update_service.rb
schema.graphql
schema.json
spec/graphql/mutations/customers/create_spec.rb
spec/graphql/mutations/customers/update_spec.rb
spec/services/customers/create_service_spec.rb
spec/services/customers/update_service_spec.rb

Currently, we cannot apply a coupon, an add-on or even prepaid-credits if a customer has no active subscription. This problem happen because customer object does not hold the currency directly, but via the currency of the plan of it’s first active subscription.
It’s a problem when a plan is invoiced in-advance because it can then take up to 1 year to apply the mentioned objects on the first generated invoice.
This PR allows front end to assign customer currency:
- At customer creation time via the `createCustomer` mutation
- At customer edition via the `updateCustomer` mutation
It also exposes this currency in the `Customer` type
In the update scenario, if the customer is attached to an `active subscription`, an `add_on`, a `coupon` or a `wallet`, the action will raise an …

feat(customers): Add or update customer currency via GraphQL

---

app/graphql/mutations/plans/create.rb
app/graphql/types/plans/object.rb
app/models/plan.rb
app/services/plans/create_service.rb
db/migrate/20220916131538_add_parent_id_on_plans.rb
db/schema.rb
schema.graphql
schema.json

There is a new feature that eases the process of plan creation with pre-filling information from selected plan.
While creating a new plan based on selected 'parent' plan we still want to keep this relationship in order to keep possibility to group such a plans in the UI

feat: support new field called parent_id on plan creation

---

app/serializers/error_serializer.rb
app/services/applied_add_ons/create_service.rb
app/services/applied_coupons/create_service.rb
app/services/events/validate_creation_service.rb
app/services/subscriptions/create_service.rb
spec/requests/api/v1/applied_add_ons_spec.rb
spec/requests/api/v1/applied_coupons_spec.rb
spec/requests/api/v1/subscriptions_spec.rb
spec/serializers/error_serializer_spec.rb
spec/services/applied_add_ons/create_service_spec.rb
spec/services/applied_coupons/create_service_spec.rb
spec/services/events/validate_creation_service_spec.rb
spec/services/subscriptions/create_service_spec.rb

**Context**
The objective of this PR is to return `404 not_found` errors for existing `422 missing_argument` failures.
Concerning GraphQL, it impacts `CreateAppliedAddOn` (when customer or add_on not found), `CreateAppliedCoupon` (when customer or coupon not found) and `CreateSubscription` (when customer or plan not found).
It has been validated that this change does not require updating the frontend, as it only triggers a generic error.
**WIP**
Need to update `ErrorSerializer` to render 404 Not Found for webhooks instead of 422.

feat(errors): Convert missing_argument to not_found errors

---

app/models/billable_metric.rb
spec/models/billable_metric_spec.rb
spec/services/billable_metrics/aggregations/count_service_spec.rb

Trying to assign an invalid aggregation type when creating a billable metric leads to an HTTP 500 error when it should returns a 422.
This behavior is related to the Rails `enum` implementation. When assigning an invalid value to an enum, a ruby `ArgumentError` is raised immediately, making it impossible to validate the provided value with the standard model validations.
In order to fix the issue, the idea is:
- to override the default enum setter, to add filter invalid inputs
- add a validation rule to validate inclusion of the value (or nil) in the list of aggregation types

fix(billable_metrics): Wrong aggregation type should raise a validation error

---

app/controllers/api/v1/invoices_controller.rb
app/serializers/v1/invoice_serializer.rb
spec/requests/api/v1/invoices_spec.rb

Calling `GET /api/v1/invoices/:id` does not return the list of credits applied to the invoice
This PR goals is to fix the behavior documented in the API reference documentation and include invoice credits in the response payload

fix(invoices): Show credit list on API invoice results

---

app/graphql/types/subscriptions/object.rb
schema.graphql
schema.json

Add `subscription_end_date` in subscription resolver. This change is needed for _duplicate plans_ feature. We need this information on FE side in order to present valid end date in notification pop-up while downgrading subscription.

feat: add subscription end date in subscription resolver

---

app/controllers/api/v1/customers_controller.rb
app/serializers/v1/customer_serializer.rb
app/services/base_service.rb
app/services/customers/create_service.rb
spec/requests/api/v1/customers_spec.rb
spec/services/customers/create_service_spec.rb

Currently, we cannot apply a coupon, an add-on or even prepaid-credits if a customer has no active subscription. This problem happen because customer object does not hold the currency directly, but via the currency of the plan of it’s first active subscription.
It’s a problem when a plan is invoiced in-advance because it can then take up to 1 year to apply the mentioned objects on the first generated invoice.
This PR allows API users to assign customer currency at customer creation or update time via a `POST` on `/api/v1/customers`
It also exposes this currency in the `response` type
In the update scenario, if the customer is attached to an `active subscription`, an `add_on`, a `coupon` or a `wallet`, the call will render an HTTP 422 error, with the error code `currencies_does_not_match` …

feat(customers): Add or update customer currency via API

---

app/services/users_service.rb
spec/graphql/mutations/login_user_spec.rb

User without an active status were still able to log in the app.
This PR brings a check to prevent them to do so.
I has been agree with product that the returned error should be the same as if the user does not exists

fix: prevent revoked users to log in

---

app/services/invoices/payments/stripe_service.rb
app/services/invoices/update_service.rb
app/services/payment_provider_customers/stripe_service.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/invoices/update_service_spec.rb

The objective of this PR is to attach validation failures to a field when instead of rendering a single validation code.
It has been validated that this change does not require updating the frontend, as it only triggers a generic error.

feat(errors): More handling of single validation errors

---

app/services/users_service.rb
spec/services/invites/accept_service_spec.rb

When building the invite flow, we duplicated the `register` method.
This method does include a check on the user id, that stops the process if a user with the same email were already existing. 
We decided to remove this check in the accept invite flow, in order to allow users to be invited multiple time.
Indeed, as the user is never deleted, this check will make the call fail if a revoked user is invited once again.
We agreed that the situation when the user creates an organization (using the existing `register` method), then is invited to an organization will not work, as in the frontend we'll need to make a organization switcher in order to make them choose between multiple orga. By default we display the first organization fetched

fix(invite): remove check on user.id when accepting an invite

---

app/services/fees/subscription_service.rb
spec/services/fees/subscription_service_spec.rb

During a subscription upgrade, the amount calculated for an in advance and a different interval is wrong.
The boudaries passed to calculate the previous subscription are wrong.
- Use the previous subscription boundaries instead of the new one
- Fix some specs

fix(subscription): Fix Upgrade Old Subscription Boundaries

---

app/controllers/webhooks_controller.rb
app/services/base_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/fees/charge_service.rb
app/services/payment_providers/stripe_service.rb
spec/requests/webhooks_spec.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/payment_providers/stripe_service_spec.rb

The objective of this PR is to handle a new type of error `ServiceFailure`. This type apply when error are not supposed to bubble up to end users, but instead needs to be handled internally

feat(errors): Handle inner service failures

---

.github/ISSUE_TEMPLATE/bug_report.md

We have hard time to understand whereas a bug is reported using the last version of the app or not.
This PR adds a new section in github issue template, asking for the Lago version used

chore(issue-template): ask for lago version in issue template

---

app/controllers/api/v1/coupons_controller.rb
app/graphql/mutations/coupons/create.rb
app/graphql/mutations/coupons/update.rb
app/graphql/types/coupons/object.rb
app/models/coupon.rb
app/serializers/v1/coupon_serializer.rb
app/services/coupons/create_service.rb
app/services/coupons/update_service.rb
db/migrate/20220923092906_add_expiration_date_to_coupons.rb
db/schema.rb
lib/tasks/coupons.rake
schema.graphql
schema.json
spec/graphql/mutations/coupons/create_spec.rb
spec/graphql/mutations/coupons/update_spec.rb
spec/requests/api/v1/coupons_spec.rb
spec/serializers/v1/coupon_serializer_spec.rb
spec/services/coupons/create_service_spec.rb
spec/services/coupons/terminate_service_spec.rb
spec/services/coupons/update_service_spec.rb

This change includes expiration logic around coupons.
We have several changes around expiration:
> We will use expiration_date instead of expiration_duration
> Expiration fields are editable from now on even if coupon is already assigned to customer

feat(coupons): add expiration_date coupon changes

---

lib/lago_http_client/lago_http_client/client.rb
spec/lib/lago_http_client/client_spec.rb

If a webhook url is set to a domain wihtout path, it raises an error when trying to deliver it.
Instead of trying to send the webhook to a blank path, it should be sent to the root path (`/`)

fix: Empty webhook URI path sould not raise an error

---

app/services/webhooks/invoices/generated_service.rb
spec/services/webhooks/invoices/generated_service_spec.rb

On the `invoice.generated` webhook we do not have the customer informations
- Add the `customer` information on the `invoice.generated` webhook

feat(invoices): add customers into generated webhook

---

config/storage.yml

- We do not support bucket name for AWS S3 Compatible systems
- Add the `bucket` configuration option for AWS S3 Compatible systems

fix(s3): Add compatible S3 Bucket config

---

app/models/customer.rb

With the old behaviour, `Customers::UpdateService` is returning error when we try to assign a subscription to customer that have applied percentage coupon. `currencies_does_not_match` error is raised if customer currency does not exist but the customer is not editable. If customer have percentage coupon applied and customer currency is nil, currency should still be editable...

fix (customer): change editable? method in customer model

---

app/models/subscription.rb
app/services/invoices/create_service.rb
spec/models/subscription_spec.rb
spec/services/invoices/create_service_spec.rb

This bug fix prevents charging subscription fees twice in the same day when paying is in advance and when subscription is created on the billing day (just before BillingJob running time)

fix: prevent charging subscription fees twice in the same day

---

app/models/concerns/sequenced.rb
app/models/credit.rb
app/models/credit_note.rb
app/models/credit_note_item.rb
app/models/fee.rb
app/models/organization.rb
db/migrate/20220930123935_create_credit_notes.rb
db/migrate/20220930134327_create_credit_note_items.rb
db/migrate/20220930143002_add_credit_note_id_to_credits.rb
db/schema.rb
spec/factories/credit_factory.rb
spec/factories/credit_note_items.rb
spec/factories/credit_notes.rb
spec/models/credit_note_spec.rb

This pull request is the first one for the feature.
It updates the data structure:
- Add the new `CreditNote` model, to store allowed and remaining credit
- Add the new `CreditNoteItem` model to store the link between a credit note and a targeted fee
- Add a new relation between the `Credit` model and the new `CreditNote` to apply a credit note to an invoice

feat(credit-notes): Add credit note database structure

---

db/migrate/20221007075812_run_customer_currency_task_again.rb
db/schema.rb
lib/tasks/customers.rake

There is an issue with the migration task to populate customer currency
The objective of this PR is to fix the migration task and force it to run again on app upgrade to prevent some user to be blocked with the subscription update of some of their customers

feat(customers): HOTFIX for customer currency migration

---

app/views/templates/invoice.slim

The objective of this PR is to fix a typo in the invoice PDF template

fix(invoices): Fix Typo on persistent BM on Inovoice PDF

---

app/graphql/types/credit_note_items/object.rb
app/graphql/types/credit_notes/object.rb
app/graphql/types/credit_notes/reason_type_enum.rb
app/graphql/types/credit_notes/status_type_enum.rb
app/graphql/types/customers/single_object.rb
app/graphql/types/fees/object.rb
app/graphql/types/invoices/invoice_item.rb
schema.graphql
schema.json
spec/factories/coupon_factory.rb
spec/graphql/resolvers/customer_resolver_spec.rb

This PR exposes the customer `creditNotes` into the GraphQL schema. It is attached to the `customerDetails` type

feat(credit_notes): Expose credit notes into GraphQL

---

app/controllers/api/v1/subscriptions_controller.rb
app/graphql/mutations/subscriptions/create.rb
app/graphql/mutations/subscriptions/update.rb
app/graphql/resolvers/customers/subscriptions_resolver.rb
app/models/subscription.rb
app/services/fees/subscription_service.rb
app/services/subscriptions/create_service.rb
app/services/subscriptions/update_service.rb
app/services/subscriptions/validate_service.rb
config/locales/en.yml
schema.graphql
schema.json
spec/graphql/resolvers/customer_resolver_spec.rb
spec/models/subscription_spec.rb
spec/requests/api/v1/subscriptions_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/subscriptions/update_service_spec.rb
spec/services/subscriptions/validate_service_spec.rb

This change allows creating subscription with preselected subscription_date.
This is the first PR for `subscription on specific date` feature
In this PR only necessary logic for creating subscription on specific date is added.
Upgrade/downgrade; subscription update and converting pending to active subscriptions will be handled in following PRs

feat (subscriptions): add logic to create subscription with given subscription_date

---

app/services/events/create_service.rb
spec/services/events/create_service_spec.rb

The recent changes related to the error management have introduce a regression with the error web-hook for event ingestion.
Before the change, error attached to a service result was a message or a code, and it was sent as the error message in the web-hook.
With the new error management, result error are subclass of `Base::FailedResult`. The issue is that this error cannot be serialized for sidekiq job, leading to an `ActiveJob::SerializationError` when trying to send the webhook.
This fixes changes the behavior to send the error message, and adds a test for this specific case

fix(errors): Event error webhook after error management refactoring

---

app/services/invoices/create_service.rb
db/seeds.rb
spec/services/invoices/create_service_spec.rb

Include charges in the first invoice for subscription created in the past
Usually we do not include charges in the first invoice when plan is pay in advance because for payment in advance first invoice is generated right after subscription creation so there are not charges at that time. However, with this change we still want to bill charges even with first invoice but only for subscription that are created with subscription date in the past.

fix (subscriptions): update logic for including charges in the first invoice

---

app/models/billable_metric.rb
app/models/group.rb
db/migrate/20221004092737_create_groups.rb
db/schema.rb
spec/factories/groups.rb

The goal of this PR is to create the `groups` table.

feat(groups): Create table groups

---

app/graphql/mutations/billable_metrics/create.rb
app/graphql/mutations/billable_metrics/update.rb
app/graphql/types/billable_metrics/object.rb
app/models/billable_metric.rb
app/models/group.rb
app/serializers/v1/billable_metric_serializer.rb
app/services/billable_metrics/create_service.rb
app/services/billable_metrics/update_service.rb
app/services/groups/create_batch_service.rb
db/migrate/20221004092737_create_groups.rb
db/schema.rb
schema.graphql
schema.json
spec/factories/groups.rb
spec/graphql/mutations/billable_metrics/create_spec.rb
spec/graphql/mutations/billable_metrics/update_spec.rb
spec/models/billable_metric_spec.rb
spec/serializers/v1/billable_metric_serializer_spec.rb
spec/services/billable_metrics/create_service_spec.rb
spec/services/groups/create_batch_service_spec.rb

The goal of this PR is to accept groups in GraphQL for a billable metric, on creation and update.

feat(groups): Accept group in GraphQL for billable metric

---

app/models/credit.rb
app/serializers/v1/credit_serializer.rb
db/migrate/20221010083509_rename_credit_credit_note.rb
db/schema.rb
spec/factories/credit_factory.rb
spec/models/credit_spec.rb
spec/serializers/v1/credit_serializer_spec.rb

This PR adds the credit note details in the `credit` serializer used in both invoice webhooks and API response payloads

feat(credit_notes): Add credit note details in invoice webhook and API payload

---

app/controllers/api/v1/billable_metrics_controller.rb
app/services/billable_metrics/create_service.rb
app/services/billable_metrics/update_service.rb
app/services/groups/create_batch_service.rb
spec/graphql/mutations/billable_metrics/create_spec.rb
spec/graphql/mutations/billable_metrics/update_spec.rb
spec/requests/api/v1/billable_metrics_spec.rb
spec/services/billable_metrics/update_service_spec.rb

The goal of this PR is to accept groups in API for a billable metric, on creation and update.

feat(groups): Create or update groups via API

---

Dockerfile
Dockerfile.arm64

ARM64 image is missing dependency on the last version `v0.11.0-alpha`
- Add the missing dependency in the `Dockerfile.arm64` file

fix(docker): arm64 image is missing dependency

---

app/services/billable_metrics/create_service.rb
app/services/billable_metrics/update_service.rb
app/services/groups/create_batch_service.rb
spec/graphql/mutations/billable_metrics/create_spec.rb
spec/graphql/mutations/billable_metrics/update_spec.rb
spec/requests/api/v1/billable_metrics_spec.rb
spec/services/groups/create_batch_service_spec.rb

The goal of this PR is to validate the format of group parameters.

feat(groups): Validate format of groups

---

spec/services/users_service_spec.rb

A user service spec is present in the codebase.
It does have `describe` blocks per methods in the service.
I noticed the `login` block was calling `register` method
This PR fixes this by calling the `login` method instead.
We need to create a membership first too.
Please note the `login` method accept only 2 args
A test for the `register` method is already present in the file

fix(test): method called should be the same as describe

---

app/controllers/api/v1/credit_notes_controller.rb
app/jobs/credit_notes/generate_pdf_job.rb
app/jobs/send_webhook_job.rb
app/models/credit_note.rb
app/serializers/v1/credit_note_serializer.rb
app/services/credit_notes/generate_service.rb
app/services/invoices/generate_service.rb
app/services/utils/pdf_generator.rb
app/services/webhooks/credit_notes/generated_service.rb
config/routes.rb
spec/controllers/api/v1/credit_notes_controller_spec.rb
spec/factories/credit_notes.rb
spec/jobs/credit_notes/generate_pdf_job_spec.rb
spec/jobs/send_webhook_job_spec.rb
spec/services/credit_notes/generate_service_spec.rb
spec/services/events/create_service_spec.rb
spec/services/invoices/generate_service_spec.rb
spec/services/utils/pdf_generator_spec.rb
spec/services/webhooks/credit_notes/generated_service_spec.rb

This PR adds:
- A new route to download a credit note PDF
- A new webhook `credit_note.generated` sent when the credit note PDF is generated
- The credit note PDF generation logic

feat(credit_notes): Download and generate credit note PDF from API

---

app/services/groups/create_batch_service.rb
spec/requests/api/v1/billable_metrics_spec.rb
spec/services/groups/create_batch_service_spec.rb

The goal of this PR is to rename error message on groups from `invalid_format` to `value_is_invalid` to be consistent with other errors.

feat(groups): Change error message to value_is_invalid for groups

---

app/services/subscriptions/terminate_service.rb
spec/services/subscriptions/terminate_service_spec.rb

When terminating _starting in the future_ subscription, we don't want to trigger invoice generation

fix (subscriptions): add new condition for invoicing upon subscription termination

---

app/services/groups/create_batch_service.rb
spec/graphql/mutations/billable_metrics/update_spec.rb
spec/services/billable_metrics/create_service_spec.rb
spec/services/billable_metrics/update_service_spec.rb
spec/services/groups/create_batch_service_spec.rb

The goal of this PR is to fix the validation of `group` format.

fix(groups): Correct validation format of groups

---

app/models/credit_note.rb
schema.graphql
schema.json
spec/factories/credit_notes.rb

This PR updates the credit note model to add the list of accepted credit note reasons

feat(credit_notes): Add list of credit note reasons

---

app/graphql/types/credit_note_items/object.rb
app/models/credit_note.rb
app/models/credit_note_item.rb
app/models/invoice.rb
app/serializers/v1/credit_note_item_serializer.rb
app/services/credit_notes/create_service.rb
app/services/credit_notes/validate_item_service.rb
db/migrate/20221011083520_rename_credit_note_items.rb
db/schema.rb
schema.graphql
schema.json
spec/controllers/api/v1/credit_notes_controller_spec.rb
spec/factories/credit_note_items.rb
spec/graphql/resolvers/customer_resolver_spec.rb
spec/models/invoice_spec.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/credit_notes/validate_item_service_spec.rb

This PR adds the logic to create a credit note from an invoice and a list of fees

feat(credit_notes): Add service to create a credit note

---

app/models/charge.rb
app/models/group.rb
app/models/group_property.rb
db/migrate/20221011133055_create_group_properties.rb
db/schema.rb
spec/factories/charges.rb
spec/factories/group_properties.rb
spec/models/charge_spec.rb

The goal of this PR is to create the table `group_properties`.

feat(groups): Add group properties table

---

app/jobs/send_webhook_job.rb
app/services/webhooks/credit_notes/created_service.rb
spec/jobs/send_webhook_job_spec.rb
spec/services/webhooks/credit_notes/created_service_spec.rb

This PR adds the new `credit_note.created` webhook type

feat(credit_notes): Add credit_note.created webhook

---

app/services/invoices/create_service.rb
app/services/subscriptions/create_service.rb
spec/services/invoices/create_service_spec.rb
spec/services/subscriptions/create_service_spec.rb

When upgraded a subscription pay in advance, we do not create an invoice with fees for the charges on the period between beginning of period and termination date.
It is a regression introduce by the refactoring done with the anniversary date feature as charges for the period were billed on the new subscription and not on the terminated one.
This PR fixes the behavior by enqueuing a `BillSubscriptionJob`. The service is already able to create fees at pro-rata for the charges

fix(subscription): Charge fees on terminated subscription after upgrade

---

app/models/credit_note.rb
app/models/credit_note_item.rb
app/models/subscription.rb
app/views/templates/credit_note.slim
spec/factories/fees.rb
spec/models/credit_note_item_spec.rb
spec/models/credit_note_spec.rb
spec/models/subscription_spec.rb

feat(credit_notes): Credit Note PDF template

---

app/models/credit.rb
app/models/invoice.rb
app/services/invoices/add_on_service.rb
app/services/invoices/create_service.rb
app/services/invoices/paid_credit_service.rb
app/views/templates/credit_note.slim
app/views/templates/invoice.slim
db/migrate/20221018144521_add_legacy_flag_to_invoices.rb
db/schema.rb
lib/tasks/invoices.rake
spec/models/invoice_spec.rb
spec/services/invoices/add_on_service_spec.rb
spec/services/invoices/create_service_spec.rb
spec/services/invoices/paid_credit_service_spec.rb

This PR adds some changes on the invoice to allow application of prepaid credit, coupon and credit notes after the VAT instead of before as it is today

feat(credit_notes): Prepare changes on invoice to apply credit after VAT

---

app/graphql/resolvers/credit_note_resolver.rb
app/graphql/types/query_type.rb
schema.graphql
schema.json
spec/graphql/resolvers/credit_note_resolver_spec.rb

This PR adds a single Credit Note GraphQL resolver to fetch a Credit Note by it's id

feat(credit_notes): Add a single credit note GraphQL resolver

---

app/graphql/resolvers/invoice_resolver.rb
app/graphql/types/fees/object.rb
app/graphql/types/fees/types_enum.rb
app/graphql/types/invoice_subscription/object.rb
app/graphql/types/invoices/object.rb
app/graphql/types/query_type.rb
app/graphql/types/subscriptions/object.rb
schema.graphql
schema.json
spec/graphql/resolvers/invoice_resolver_spec.rb

To ease the work of Credit note, we’ll have an invoice details page to see the details of it and issue a credit note. We don’t have this screen so far so the goal is to build it before credit note.
This PR does 2 things, in 2 commits:
- [Creates a new invoice resolver](https://github.com/getlago/lago-api/pull/547/commits/e3ca9dddb41eed7a6fa2520c0e7a4afbbd050e5b)
- [Expose missing fields to all frontend to build and invoice details page](https://github.com/getlago/lago-api/pull/547/commits/3911ef891f70bc6f1c855cc28573baa0f1b144e6)
- Frontend related task: https://github.com/getlago/lago-front/pull/504

feat(invoices): A GraphQL resolver and types to fetch a single invoice with details

---

db/seeds.rb

This PR adds new seeds to create credit notes

feat(credit_notes): Add credit note seeds

---

app/controllers/api/v1/plans_controller.rb
app/graphql/concerns/charge_model_attributes_handler.rb
app/graphql/types/charges/object.rb
app/models/charge.rb
app/services/charges/charge_models/graduated_service.rb
app/services/charges/charge_models/volume_service.rb
app/services/charges/validators/graduated_service.rb
app/services/charges/validators/volume_service.rb
config/locales/en.yml
db/migrate/20221013140147_update_graduated_properties_to_hash.rb
db/schema.rb
lib/tasks/charges.rake
spec/factories/charges.rb
spec/graphql/resolvers/customers/usage_resolver_spec.rb
spec/models/charge_spec.rb
spec/requests/api/v1/customers_spec.rb
spec/requests/api/v1/plans_spec.rb
spec/services/charges/charge_models/graduated_service_spec.rb
spec/services/charges/charge_models/volume_service_spec.rb
spec/services/charges/validators/graduated_service_spec.rb
spec/services/charges/validators/volume_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/update_service_spec.rb

In order to be consistent between all charge models, we want to store `properties` by using the same type.
The goal of this MR is to:
- update `properties` from `array` to `hash` for graduated charges
- rename `ranges` to `volume_ranges` for the volume properties key

misc: Update graduated ranges from array to hash

---

app/controllers/api/v1/billable_metrics/groups_controller.rb
app/graphql/types/billable_metrics/object.rb
app/models/billable_metric.rb
app/models/charge.rb
app/serializers/v1/billable_metric_serializer.rb
app/serializers/v1/group_serializer.rb
config/locales/en.yml
spec/graphql/mutations/plans/create_spec.rb
spec/graphql/mutations/plans/update_spec.rb
spec/models/billable_metric_spec.rb
spec/models/charge_spec.rb
spec/requests/api/v1/billable_metrics/groups_spec.rb
spec/services/billable_metrics/update_service_spec.rb

- Fix selectable groups when one dimension
- Add a validation when creating/updating a charge with group properties

feat(groups) Ensure that all groups is referenced on group properties

---

app/services/charges/charge_models/percentage_service.rb
app/services/fees/charge_service.rb
spec/services/charges/charge_models/percentage_service_spec.rb

--
When a fixed amount is set on a percentage charge model with some free unit per events, and we’re receiving some events but the limit of free units is not reached, amount can be negative instead of 0.

fix: Return 0 when free unit per events is not reached

---

app/controllers/api/base_controller.rb
app/controllers/graphql_controller.rb
app/services/base_service.rb
app/services/customers/create_service.rb
lib/current_context.rb
spec/requests/api/base_spec.rb
spec/requests/graphql_spec.rb
spec/services/customers/create_service_spec.rb

Track source in order to be able to differentiate api requests from graphql requests

feat (gocardless): add source in current context

---

app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/charges/charge_models/base_service.rb
app/services/persisted_events/create_or_update_service.rb
db/migrate/20221021135428_add_properties_to_persisted_events.rb
db/migrate/20221021135946_fill_properties_on_persisted_events.rb
db/schema.rb
lib/tasks/events.rake
spec/services/billable_metrics/aggregations/count_service_spec.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/persisted_events/create_or_update_service_spec.rb

The goal of this PR is to be able to compute aggregation based on existing groups for a billable metric.

feat(groups): compute aggregation based on existing groups

---

app/services/subscriptions/terminate_service.rb
spec/factories/subscriptions.rb
spec/services/subscriptions/terminate_service_spec.rb

When we reactivate a subscription with the same `external_id`, if we want to terminate it, it does not found the right subscription.
- We should search for subscriptions only into the `active` one

fix(subscription): Terminate from API only with active sub

---

app/services/plans/update_service.rb
spec/services/plans/update_service_spec.rb

The goal of this PR is to be able to update a plan by setting group properties to a charge.

fix(groups): Update charge with group properties

---

app/models/credit_note_item.rb
app/models/fee.rb
app/services/credit_notes/create_service.rb
app/services/credit_notes/validate_item_service.rb
spec/factories/credit_note_items.rb
spec/models/credit_note_item_spec.rb
spec/models/fee_spec.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/credit_notes/validate_item_service_spec.rb

This PR adds the logic to handle refund amount when creating a credit note

feat(credit_notes): Handle refund amount for credit note creation

---

app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/charges/charge_models/base_service.rb
app/services/charges/charge_models/graduated_service.rb
app/services/charges/charge_models/package_service.rb
app/services/charges/charge_models/percentage_service.rb
app/services/charges/charge_models/standard_service.rb
app/services/charges/charge_models/volume_service.rb
app/services/fees/charge_service.rb
app/services/invoices/customer_usage_service.rb
spec/services/billable_metrics/aggregations/count_service_spec.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/charges/charge_models/graduated_service_spec.rb
spec/services/charges/charge_models/package_service_spec.rb
spec/services/charges/charge_models/percentage_service_spec.rb
spec/services/charges/charge_models/standard_service_spec.rb
spec/services/charges/charge_models/volume_service_spec.rb
spec/services/fees/charge_service_spec.rb

The goal of this PR is to be able to aggregate and create fees for each group properties.

feat(groups): Update charge service to support groups

---

app/jobs/invoices/payments/gocardless_create_job.rb
app/services/base_service.rb
app/services/invoices/create_service.rb
app/services/invoices/payments/gocardless_service.rb
app/services/invoices/payments/stripe_service.rb
spec/jobs/invoices/payments/gocardless_create_job_spec.rb
spec/services/invoices/payments/gocardless_service_spec.rb

Implement gocardless payment flow. When invoice is generate trigger gocardless payment if gocardless is selected as customer's payment provider.
Additionally, In this PR, logic for force-creating customer is stripe is removed since it's not used. Force-created customer does not have payment method anyways and such a payment usually fails...

feat (gocardless): implement gocardless payment flow

---

app/jobs/payment_provider_customers/gocardless_checkout_url_job.rb
app/jobs/send_webhook_job.rb
app/models/payment_providers/gocardless_provider.rb
app/serializers/v1/payment_providers/customer_checkout_serializer.rb
app/services/payment_provider_customers/gocardless_service.rb
app/services/webhooks/payment_providers/customer_checkout_service.rb
spec/jobs/payment_provider_customers/gocardless_checkout_url_job_spec.rb
spec/jobs/send_webhook_job_spec.rb
spec/serializers/v1/payment_providers/customer_checkout_serializer_spec.rb
spec/services/payment_provider_customers/gocardless_service_spec.rb
spec/services/webhooks/payment_providers/customer_checkout_service_spec.rb

Generate gocardless checkout url
Gocardless payment request cannot be made unless customer have `mandate_id`. We need to trigger generation of the checkout url (where end-user will fill billing details) and pass the url in the webhook. When end-user fills the form we can expect mandate_id in the incoming webhook...

feat (gocardless): generate checkout url with billing request flow

---

app/services/persisted_events/create_or_update_service.rb
db/schema.rb
spec/services/persisted_events/create_or_update_service_spec.rb

- If a `persisted_event` has already been removed, and if we add the exact same one, the `find_by` will take the already removed one (based on creation date order)
- add the `removed_at` nil into the `find_by`
NOTE : this is a hotfix, we should rework on this to find the best solution

hotfix(events): Remove persisted events

---

app/graphql/types/wallets/object.rb
schema.graphql
schema.json
spec/graphql/mutations/wallets/create_spec.rb

When creating through the API a wallet with no wallet_name, when going on customer.details.wallet on the UI, we have an error
Wallet name is not mandatory on both API and GraphQL, but GraphQL type was expecting this name to be present.
This PR fixes the issue by updating GraphQL schema to make name field as optional on `Wallet` type

fix(wallets): Fix GraphQL wallet type as name is not mandatory

---

app/controllers/api/v1/customers_controller.rb
app/controllers/webhooks_controller.rb
app/graphql/types/payment_provider_customers/provider.rb
app/graphql/types/payment_provider_customers/provider_input.rb
app/graphql/types/payment_providers/gocardless.rb
app/jobs/payment_providers/gocardless/handle_event_job.rb
app/models/payment_providers/base_provider.rb
app/models/payment_providers/stripe_provider.rb
app/serializers/v1/organization_serializer.rb
app/services/invoices/payments/gocardless_service.rb
app/services/payment_provider_customers/create_service.rb
app/services/payment_providers/gocardless_service.rb
config/routes.rb
schema.graphql
schema.json
spec/fixtures/gocardless/events.json
spec/jobs/payment_providers/gocardless/handle_event_job_spec.rb
spec/requests/webhooks_spec.rb
spec/services/customers/create_service_spec.rb
spec/services/invoices/payments/gocardless_service_spec.rb
spec/services/payment_providers/gocardless_service_spec.rb

Add few improvements related to gocardless feature
1. Fetch mandate before each payment
2. On UI, we won't be using mandate_id field anymore, so it should be removed
3. Generate webhook secret key (will be used on UI) while generating gocardless access token

feat (gocardless): fetch mandate before payment

---

lib/lago_http_client/lago_http_client/client.rb
spec/lib/lago_http_client/client_spec.rb

Fixes https://github.com/getlago/lago/issues/123
If a webhook URL contains query parameters, these parameters are stripped out from the URL and are note delivered to the target URL.
This PR fixes the behavior by making sure that query params are sent correctly to the webhook URL

fix(webhooks): Keep query params when sending webhooks

---

app/controllers/api/v1/credit_notes_controller.rb
app/graphql/mutations/credit_notes/create.rb
app/graphql/types/credit_notes/object.rb
app/serializers/v1/credit_note_serializer.rb
app/services/credit_notes/create_service.rb
db/migrate/20221031144907_add_description_to_credit_notes.rb
db/schema.rb
schema.graphql
schema.json
spec/controllers/api/v1/credit_notes_controller_spec.rb
spec/graphql/mutations/credit_notes/create_spec.rb
spec/services/credit_notes/create_service_spec.rb

This PR adds a `description` field to the credit note object and updates the `createCreditNote` mutation and to the `POST /api/v1/credit_notes` API routes

feat(credit_notes): Add description field to credit note

---

app/controllers/api/v1/credit_notes_controller.rb
app/services/credit_notes/update_service.rb
config/routes.rb
spec/controllers/api/v1/credit_notes_controller_spec.rb
spec/requests/api/v1/invoices_spec.rb

This PR adds the a new a new API route to update the refund status of a credit note

feat(credit_notes): Update refund status via API

---

app/jobs/send_webhook_job.rb
app/serializers/v1/credit_notes/payment_provider_refund_error_serializer.rb
app/services/webhooks/credit_notes/payment_provider_refund_failure_service.rb
spec/jobs/send_webhook_job_spec.rb
spec/serializers/v1/credit_notes/payment_provider_refund_error_serializer_spec.rb
spec/services/webhooks/credit_notes/payment_provider_refund_failure_service_spec.rb

This PR adds a new `credit_note.provider_refund_failure` webhook  to notify about failure in refund processing

feat(:credit_notes): Add error webhook for refund on payment providers

---

app/jobs/send_webhook_job.rb
app/models/credit_note.rb
app/models/payment.rb
app/models/payment_provider_customers/base_customer.rb
app/models/payment_providers/base_provider.rb
app/models/refund.rb
app/serializers/v1/credit_notes/payment_provider_refund_error_serializer.rb
app/services/webhooks/credit_notes/payment_provider_refund_failure_service.rb
db/migrate/20221028124549_create_refunds.rb
db/schema.rb
spec/jobs/send_webhook_job_spec.rb
spec/serializers/v1/credit_notes/payment_provider_refund_error_serializer_spec.rb
spec/services/webhooks/credit_notes/payment_provider_refund_failure_service_spec.rb

This PR adds a new `refund` model to handle refunds on stripe

feat(credit_notes): Add refund model to handle stripe refunds

---

app/services/invoices/customer_usage_service.rb
spec/services/invoices/customer_usage_service_spec.rb

The cache of the customer current usage is a bit too long on the last day of a billing period, making it overlapping on the first day
This PR fixes the issue by adding the `charges_to_date` boundary to the cache key

fix(current-usage): Reduce cache duration on last period day

---

app/models/credit_note.rb
app/services/credit_notes/void_service.rb
spec/services/credit_notes/void_service_spec.rb

This PR set the credit_note `balance_amount_cents` to 0 when voiding the credit note

feat(creadit_notes): Set credit balance to 0 when voided

---

app/services/credit_notes/create_service.rb
spec/services/credit_notes/create_service_spec.rb

This PR adds tracking of the credit note creation on Segment

feat(credit_note): Track creation on Segment

---

app/controllers/api/v1/credit_notes_controller.rb
config/routes.rb
spec/controllers/api/v1/credit_notes_controller_spec.rb

This PR adds the `PUT /api/v1/credit_notes/:id/void` route to void a credit note via the API

feat(credit_notes): Void a credit note via API

---

app/models/group.rb
app/models/invoice.rb
app/views/templates/invoice.slim

The goal of this PR is to be able to support groups on the invoice.

feat(groups): Update invoice to support groups

---

app/services/subscriptions/dates_service.rb
spec/services/subscriptions/dates/yearly_service_spec.rb

Today, if a yearly subscription is billed on an anniversary basis with a subscription date on the first day of month (appart for January 1st), any billing job will failed with a `Date::Error invalid date` error.
The issue is related to a wrong handling of day computation in the Yearly and Monthly date service. The service tries to build a date object with 0 as day number, leading to the exception.
The fix is to  handle this 0 case and move to the last day of the previous month.

fix(dates): Fix yearly to_date computation when subscription anniversary is on first day of a month

---

app/graphql/resolvers/invoice_credit_notes_resolver.rb
app/graphql/types/query_type.rb
schema.graphql
schema.json
spec/graphql/resolvers/invoice_credit_notes_resolver_spec.rb

👉 https://github.com/getlago/lago/issues/59
We need 2 ways to fetch credit note list: via an invoice or a customer id
This PR adds the invoice credit notes resolver, as the customer already exists on the feature branch

feat: add invoice_credit_notes_resolver

---

app/graphql/types/customers/object.rb
schema.graphql
schema.json
spec/graphql/resolvers/customer_resolver_spec.rb

👉 https://github.com/getlago/lago/issues/59
This PR is part of the credit note feature.
We need the information if a customer has or not any credit notes already existing, for display purpose (handle a tab display)
We add a boolean to be returned to frontend app in order to handle UI logic

feat: add has_credit_notes boolean on customer type

---

app/graphql/types/customers/object.rb
schema.graphql
schema.json
spec/graphql/resolvers/customer_resolver_spec.rb

👉 https://github.com/getlago/lago/issues/59
This PR is part of the credit note feature.
We need the information about customer credit notes (count and remaining credits)
We add those datas to the customer type, to be returned to frontend app in order to handle UI logic

feat(customer): add credit notes related data for UI purpose

---

app/models/payment_providers/gocardless_provider.rb
app/services/invoices/payments/gocardless_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/payment_providers/gocardless_service.rb
db/migrate/20221114102649_fill_sync_with_provider_field.rb
db/schema.rb
lib/tasks/customers.rake

Private method called `handle_prepaid_credits` is called from method where `invoice` instance variable is present but also from another method where `invoice` instance variable is not present
Also, in this PR few other improvements are added:
1.) gocardless auth site url is handled in model instead using hardcoded string that applies only to sandbox
2.) migration is added that sets sync_with_provider field to true for existing customers (if customer's payment provider is set to stripe)

fix (gocardless): fix calling invoice without its instance var

---

db/migrate/20221115110223_add_unique_index_on_customers_external_id.rb
db/schema.rb

The `external_id` of the `customers` must be unique, within the scope of the `organization`.
In the model, we have the same validation:
`validates :external_id, presence: true, uniqueness: { scope: :organization_id }`
The goal of this PR is to be consistent at the database level.

misc: Fix unique index on customers external_id

---

app/controllers/api/v1/customers_controller.rb
app/controllers/api/v1/organizations_controller.rb
app/serializers/v1/customer_serializer.rb
app/serializers/v1/organization_serializer.rb
app/services/customers/create_service.rb
app/services/customers/update_service.rb
app/services/organizations/update_service.rb
spec/requests/api/v1/customers_spec.rb
spec/requests/api/v1/organizations_spec.rb
spec/serializers/v1/organization_serializer_spec.rb

The goal of this PR is to be able to set `invoice_grace_period` on `organizations` and `customers` via the API.

feat(grace_period): Set invoice grace period on customers and organizations via API

---

app/graphql/types/applied_coupons/object.rb
app/services/applied_coupons/create_service.rb
app/services/credits/applied_coupon_service.rb
app/services/invoices/create_service.rb
db/migrate/20221115135840_add_frequency_duration_remaining_to_applied_coupons.rb
db/schema.rb
schema.graphql
schema.json
spec/services/applied_coupons/create_service_spec.rb
spec/services/credits/applied_coupon_service_spec.rb
spec/services/invoices/create_service_spec.rb

This change handles applying multiple coupons to the customer.
Applying multiple coupons to the customer requires removing validation on the BE side upon apply_coupon creation and updating logic when generating an invoice.
From now on, we will also track `recurring` case with the `frequency_duration_remaining` field so that we don't change originally value that is set on applied coupon object. This field will also be needed in the API endpoint for applied_coupons collection.

feat (coupons): allow applying multiple coupons to the customer

---

app/models/customer.rb
app/models/organization.rb
app/validators/timezone_validator.rb
db/migrate/20221115155550_add_timezone_to_organizations.rb
db/migrate/20221115160325_add_timezone_to_customers.rb
db/schema.rb
spec/models/customer_spec.rb
spec/models/organization_spec.rb

This PR is the first of the feature. It adds two new database columnes:
- `organizations#timezone`
- `customers#timezone`

feat(timezone): Add timezone to organizations and customers

---

app/controllers/api/v1/applied_coupons_controller.rb
app/models/organization.rb
app/serializers/v1/applied_coupon_serializer.rb
config/routes.rb
spec/requests/api/v1/applied_coupons_spec.rb

API endpoint for listing all applied coupons
`GET /api/v1/applied_coupons`
It's also allowed to filter applied coupons by `customer` and `status`

feat (coupons): add API endpoint for fetching all applied coupons

---

db/migrate/20221118093903_fill_frequency_duration_remaining_field.rb
db/schema.rb
lib/tasks/applied_coupons.rake

Set `frequency_duration_remaining` field
Currently we use `frequency_duration` field to count number of cycles in which certain coupon is used. Since we are switching to `frequency_duration_remaining` field, we need to set it for existing applied_coupons objects

feat (coupons): add migration to populate frequency_duration_remaining field

---

app/models/concerns/customer_timezone.rb
app/models/concerns/organization_timezone.rb
app/models/customer.rb
app/models/organization.rb
spec/models/customer_spec.rb

This PR adds:
- `Customer#applicable_timezone` to get the timezone applicable for the customer
- `CustomerTimezone` concern to allow `*_in_customer_timezone` and `*_in_organization_timzone` on models datetime fields

feat(timezone): Add timezone concerns to customer and organization

---

app/controllers/api/v1/customers_controller.rb
app/controllers/api/v1/organizations_controller.rb
app/serializers/v1/customer_serializer.rb
app/serializers/v1/organization_serializer.rb
app/services/customers/create_service.rb
app/services/customers/update_service.rb
app/services/organizations/update_service.rb
spec/requests/api/v1/customers_spec.rb
spec/requests/api/v1/organizations_spec.rb
spec/serializers/v1/organization_serializer_spec.rb
spec/services/customers/create_service_spec.rb
spec/services/customers/update_service_spec.rb
spec/services/organizations/update_service_spec.rb

The goal of this PR is to move fields related to Billing or Invoice into `billing_configuration`.
For customer: `invoice_grace_period`, `vat_rate`.
For organization: `invoice_footer`, `invoice_grace_period`, `vat_rate`.

misc: Move fields related to Billing or Invoice into billing_configuration

---

app/graphql/types/invoices/object.rb
schema.graphql
schema.json

This PR is part of the credit notes feature
Expose the `credit_notes` relationship in invoice model through Invoice type so Frontend can use them

feat: expose credit notes on invoices

---

app/graphql/types/coupons/object.rb
app/graphql/types/plans/object.rb

We display the number of "customer count" on different places in the app.
- Plans list
- Coupons list
- Addons list
This value were wrong at 2 places, as we calculated all active subscription instead
This PR corrects the value returned by those methods

bug: fix customer count wrongly calculated

---

app/graphql/types/invoices/object.rb
app/graphql/types/invoices/status_type_enum.rb
app/models/invoice.rb
app/serializers/v1/invoice_serializer.rb
schema.graphql
schema.json
spec/graphql/resolvers/invoice_resolver_spec.rb
spec/requests/api/v1/invoices_spec.rb

The goal of this PR is to add `invoice#status` for defining draft or finalized invoices.

feat(grace_period): Add status to invoices

---

app/models/customer.rb
app/services/invoices/create_service.rb
app/services/webhooks/invoices/drafted_service.rb
spec/models/customer_spec.rb
spec/services/invoices/create_service_spec.rb
spec/services/webhooks/invoices/drafted_service_spec.rb

The goal of this PR is to create invoice as draft if applicable grace period.

feat(grace_period): Create invoice as draft if applicable grace period

---

app/jobs/bill_add_on_job.rb
app/services/applied_add_ons/create_service.rb
app/services/invoices/add_on_service.rb
app/services/invoices/create_service.rb
app/services/invoices/paid_credit_service.rb
app/services/invoices/payments/create_service.rb
spec/jobs/bill_add_on_job_spec.rb
spec/services/invoices/add_on_service_spec.rb
spec/services/invoices/create_service_spec.rb
spec/services/invoices/paid_credit_service_spec.rb
spec/services/invoices/payments/create_service_spec.rb

This PR updates the logic around invoice `issuing_date` to make sure the date is always in customer timezone.

feat(timezones): Invoice issuing date must be in customer timezone

---

app/graphql/types/credit_notes/object.rb
app/serializers/v1/credit_note_serializer.rb
app/services/credit_notes/create_service.rb
app/views/templates/credit_note.slim
db/migrate/20221125111605_add_issuing_date_to_credit_notes.rb
db/schema.rb
schema.graphql
schema.json
spec/factories/credit_notes.rb
spec/services/credit_notes/create_service_spec.rb

This PR updates the logic around credit notes to add an `issuing_date`. This date will be in the customer timezone.

feat(timezones): Add issuing date in customer timezone on Credit notes

---

app/models/subscription.rb
app/services/billing_service.rb
app/services/subscriptions/activate_service.rb
clock.rb
spec/services/billing_service_spec.rb
spec/services/subscriptions/activate_service_spec.rb

This PR updates `Clock::ActivateSubscriptionsJob` and `Clock::SubscriptionsBillerJob` to takes customer (assigned or inherited from organization) timezone into account

feat(timezone): Use timezone in billing service

---

app/controllers/api/v1/invoices_controller.rb
app/graphql/resolvers/customers/invoices_resolver.rb
app/graphql/types/query_type.rb
schema.graphql
schema.json
spec/graphql/resolvers/customers/invoices_resolver_spec.rb
spec/requests/api/v1/invoices_spec.rb

The goal of this PR is to be able to fetch customer invoices and filter them by `status`.

feat(grace_period): Ability to fetch invoices by status

---

app/graphql/types/subscriptions/object.rb
app/models/subscription.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
app/services/fees/subscription_service.rb
app/services/invoices/create_service.rb
app/services/invoices/customer_usage_service.rb
app/services/subscriptions/dates/yearly_service.rb
app/services/subscriptions/dates_service.rb
spec/services/subscriptions/dates/monthly_service_spec.rb
spec/services/subscriptions/dates/weekly_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb
spec/services/subscriptions/dates_service_spec.rb

This PR updates the Subscriptions::Dates::*Services to take customer timezone into account.
**NOTE**: It changes the behavior of the services by returning `datetime` instead of `date` for boundaries. For now results are converted back into `date` to prevent a too large number of changes in this PR. The handling of `datetime` boundaries will be done in a next pull request.

feat(timezones): Apply customer timezone to date service

---

db/seeds/invoices.rb

Since the merge of https://github.com/getlago/lago-api/pull/628, seeds are not working anymore.
The issue is that issuing_date is now a mandatory field on the credit note but the seed are not setting the value

fix: Fix credit note seeds

---

config/environments/production.rb
config/initializers/sidekiq.rb

Some users want to be able to use a Redis protected server.
- Add the support of `REDIS_PASSWORD` for Sidekiq
- Add the support of `LAGO_REDIS_CACHE_PASSWORD` for Cache Store

misc(redis): Add Redis Password Support

---

app/services/invoices/paid_credit_service.rb
app/views/templates/invoice.slim
db/schema.rb

The PR is related to the credit note feature and especially the changes regarding VAT
Since Prepaid credit will not handle VAT anymore, this PR removes the tax related items from the prepaid credit invoices when they are not legacy.

fix(invoices): Fix prepaid credit invoices to hide tax related items

---

config/environments/production.rb
config/initializers/sidekiq.rb

- Docker Compose is using blank string instead of `nil` values for ENV VAR that are not defined

fix(redis): Password is defaulted to empty string by docker compose

---

app/models/plan.rb
spec/models/plan_spec.rb

When setting a trial period at `0` the first subscription of a paid in advance calendar plan is wrongly billed at 0 when created on the last day of the period
The issue is related to a wrong assumption of the behavior of the rails `present?` method:
```ruby
0.0.present?
```

fix: Trial period set to zero should not be considered as present

---

app/graphql/types/invoice_subscription/object.rb
app/graphql/types/invoices/usage.rb
app/models/invoice.rb
app/models/invoice_subscription.rb
app/serializers/v1/customer_usage_serializer.rb
app/serializers/v1/legacy/customer_usage_serializer.rb
app/services/fees/charge_service.rb
app/services/fees/subscription_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/customer_usage_service.rb
app/views/templates/invoice.slim
db/migrate/20221128132620_change_fees_boundaries.rb
db/schema.rb
lib/tasks/fees.rake
schema.graphql
schema.json
spec/factories/fees.rb
spec/graphql/resolvers/customers/usage_resolver_spec.rb
spec/graphql/resolvers/invoice_resolver_spec.rb
spec/models/invoice_subscription_spec.rb
spec/serializers/v1/customer_usage_serializer_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/create_service_spec.rb
spec/services/invoices/customer_usage_service_spec.rb
spec/support/matchers/datetime_matcher.rb

This PR updates the invoice, fees and subscription_invoice object to manage boundaries as datetime rather than date, it will allow these boundaries to be converted into customer timezones

feat(timezone): Change invoice boundaries from date to datetime

---

app/models/billable_metric.rb

Deleting a BM including 2 levels of dimension was not possible due to `PG::ForeignKeyViolation` on groups.
The goal of this PR is to use `delete_all` when deleting groups, to not hit any callbacks.

fix: Delete all groups without calling callbacks

---

lib/tasks/fees.rake

This PR fixes the fee boundaries migration introduced by a recent PR for the timezone feature

fix(timezone): Fee boundaries migration

---

app/serializers/v1/customer_usage_serializer.rb
app/serializers/v1/legacy/customer_usage_serializer.rb

A recent changes of the billing period boundaries introduced for the timezone features has led to an issue with the cached result of the customer usage.
The cache still contains date boundaries when the serializer expects a datetime.
This fix introduce a temporary fallback to deal with the previous fields until all cached expire.

fix(timezones): Prevent error with cached boundaries

---

app/jobs/clock/finalize_invoices_job.rb
app/services/invoices/finalize_service.rb
app/services/invoices/refresh_draft_service.rb
clock.rb
spec/jobs/clock/finalize_invoices_job_spec.rb
spec/services/invoices/finalize_service_spec.rb
spec/services/invoices/refresh_draft_service_spec.rb

The goal of this PR is to be able to finalize automatically draft invoices.

feat(grace_period): Ability to finalize automatically draft invoices

---

app/services/credit_notes/create_service.rb
spec/services/credit_notes/create_service_spec.rb

This PR updates the Segment tracking payload to match the specs

feat(credit_notes): Update Segment payload

---

lib/tasks/signup.rake
scripts/start.dev.sh
scripts/start.sh

Lago by design is used to push events using one of its clients to the api server. As a developper, often times, the event collection happens on a different app than Lago. In a modern dev environment where apps are deployed at the same time this can lead to a confusing developer experience. Let's take an example where `app_1` is used to collect billable metrics and `lago_api` is used to store it. A developper will boot both app in its cluster (docker-compose, k8s, ...). Since `app_1` is requesting lago client to be able to work the developper has to inject the lago url as well as the token in then ENV variables of `app_1`. But those credentials only exists when the developer logs in to the newly deployed instance of lago, signs up for an account and get his/her api key, then proceed to …

Add autoprovisioning of member & orgs

---

app/controllers/api/v1/wallets_controller.rb
app/graphql/mutations/wallets/create.rb
app/graphql/mutations/wallets/update.rb
app/graphql/types/wallets/object.rb
app/legacy_inputs/base_legacy_input.rb
app/legacy_inputs/wallet_legacy_input.rb
app/models/user.rb
app/models/wallet.rb
app/serializers/v1/legacy/wallet_serializer.rb
app/serializers/v1/wallet_serializer.rb
app/services/wallets/create_service.rb
app/services/wallets/update_service.rb
clock.rb
db/migrate/20221202130126_rename_wallets_expiration_date.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/mutations/wallets/create_spec.rb
spec/graphql/mutations/wallets/update_spec.rb
spec/requests/api/v1/wallets_spec.rb
spec/serializers/v1/wallet_serializer_spec.rb
spec/services/wallets/create_service_spec.rb
spec/services/wallets/terminate_service_spec.rb
spec/services/wallets/update_service_spec.rb

This PR updates the wallet to turn `expiration_date` into `expiration_at`, it is keeping the compatibility with the existing fields.

feat(timezone): Wallet expiration date

---

app/models/event.rb
app/models/invoice.rb
app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/fees/charge_service.rb
app/services/utils/timezone_service.rb
spec/services/billable_metrics/aggregations/count_service_spec.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb

This PR updates the aggregation service to use datetime instead of dates for calculation.
It will allow the usage of the datetime in customer timezone once the changes on the date service will be merged

feat(timezones): Use datetimes in aggregation services

---

app/controllers/api/base_controller.rb
app/services/base_service.rb
app/services/credit_notes/create_from_upgrade.rb
app/services/credit_notes/create_service.rb
spec/controllers/api/v1/credit_notes_controller_spec.rb
spec/graphql/mutations/credit_notes/create_spec.rb
spec/services/credit_notes/create_service_spec.rb

This PR disable the manual credit note creation for API and GraphQL until we release the license management system

feat(credit-notes): Disable credit note creation until license management is ready

---

app/controllers/api/v1/coupons_controller.rb
app/graphql/mutations/coupons/create.rb
app/graphql/mutations/coupons/update.rb
app/graphql/types/coupons/object.rb
app/legacy_inputs/coupon_legacy_input.rb
app/models/coupon.rb
app/serializers/v1/applied_coupon_serializer.rb
app/serializers/v1/coupon_serializer.rb
app/serializers/v1/legacy/applied_coupon_serializer.rb
app/serializers/v1/legacy/coupon_serializer.rb
app/services/coupons/create_service.rb
app/services/coupons/update_service.rb
clock.rb
db/migrate/20221129133433_change_expiration_dates_type.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/mutations/coupons/create_spec.rb
spec/graphql/mutations/coupons/update_spec.rb
spec/requests/api/v1/coupons_spec.rb
spec/serializers/v1/coupon_serializer_spec.rb
spec/services/coupons/create_service_spec.rb
spec/services/coupons/terminate_service_spec.rb
spec/services/coupons/update_service_spec.rb

This PR updates the coupon to turn `expiration_date` into `expiration_at`, it is keeping the compatibility with the existing fields.

feat(timezones): Coupon expiration date

---

app/models/invoice.rb
app/models/invoice_subscription.rb
app/services/invoices/add_on_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/create_service.rb
app/services/invoices/paid_credit_service.rb
app/services/subscriptions/dates_service.rb
db/migrate/20221208140608_add_timezone_to_invoices.rb
db/migrate/20221208142739_add_properties_to_invoice_subscriptions.rb
db/schema.rb
db/seeds/groups.rb
spec/models/invoice_subscription_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/create_service_spec.rb
spec/services/subscriptions/dates/monthly_service_spec.rb
spec/services/subscriptions/dates/weekly_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb

This PR ensure that charges billed on a period does not overlap with a previous invoice or that no holes appears between 2 consecutive invoices in case of a change of time zone at customer or organization level.
Timezone will be stored at invoice level to ensure we are not loosing the timezone information

feat(timezones): Prevent overlaping of timezone when customer timezone changes

---

app/services/base_service.rb

Related to https://github.com/getlago/lago-api/pull/663
The error returned by the service was a `ServiceFailure` when it should be a `ForbiddenFailure`.
Note: this code is not yet covered by tests because it will change soon with the premium/oss separation

fix(credit-notes): Return the right type of error on creation

---

app/graphql/types/subscriptions/object.rb
app/models/subscription.rb
app/serializers/v1/subscription_serializer.rb
app/services/billing_service.rb
app/services/subscriptions/activate_service.rb
app/services/subscriptions/create_service.rb
app/services/subscriptions/dates/monthly_service.rb
app/services/subscriptions/dates/weekly_service.rb
app/services/subscriptions/dates/yearly_service.rb
app/services/subscriptions/dates_service.rb
app/services/subscriptions/update_service.rb
app/services/subscriptions/validate_service.rb
db/migrate/20221206094412_change_subscription_date_type.rb
db/schema.rb
db/seeds/base.rb
db/seeds/groups.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb
spec/services/billing_service_spec.rb
spec/services/credit_notes/create_from_upgrade_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/create_service_spec.rb
spec/services/invoices/customer_usage_service_spec.rb
spec/services/subscriptions/activate_service_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/subscriptions/dates/monthly_service_spec.rb
spec/services/subscriptions/dates/weekly_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb
spec/services/subscriptions/dates_service_spec.rb
spec/services/subscriptions/update_service_spec.rb

This PR turn the `subscription_date` (`date`) field into a `subscription_at` (`datetime`) for subscriptions.
For now, it does not changes the API contract, it will be handled in a new PR

feat(timezones): Turn subscription#subscription_date into subscription_at

---

app/controllers/api/v1/subscriptions_controller.rb
app/graphql/mutations/subscriptions/create.rb
app/graphql/mutations/subscriptions/update.rb
app/graphql/types/subscriptions/object.rb
app/legacy_inputs/subscription_legacy_input.rb
app/models/user.rb
app/serializers/v1/legacy/subscription_serializer.rb
app/serializers/v1/subscription_serializer.rb
app/services/subscriptions/create_service.rb
app/services/subscriptions/update_service.rb
app/services/subscriptions/validate_service.rb
schema.graphql
schema.json
spec/graphql/mutations/subscriptions/create_spec.rb
spec/graphql/mutations/subscriptions/update_spec.rb
spec/requests/api/v1/subscriptions_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/subscriptions/update_service_spec.rb
spec/services/subscriptions/validate_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/655 and allow the creation and update of subscriptions using the `subscription_at` fields instead of the `subscription_date`.
NOTE: it is keeping the compatibility with the existing fields

feat(timezones): Create and update subscription#subscription_at

---

app/services/invoices/create_service.rb

- we had a race condition that was sending the webhook for a invoice before closing the transaction DB for it.
- Call the webhook job after the invoice DB transaction

fix(invoices): race conditions for wbehook

---

app/services/coupons/create_service.rb
app/services/coupons/update_service.rb
app/services/coupons/validate_service.rb
spec/services/coupons/create_service_spec.rb
spec/services/coupons/validate_service_spec.rb

When creating/updating coupon from the API we need to validate expiration_at field. Currently, we don't validate it and coupon can be created even with `expiration_at` field set in the past

fix (coupons): validate expiration_at field on create and update

---

app/jobs/bill_subscription_job.rb
app/models/invoice_subscription.rb
app/models/subscription.rb
app/services/billing_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/subscription_service.rb
clock.rb
db/migrate/20221212153810_add_source_to_invoice_subscriptions.rb
db/schema.rb
db/seeds/invoices.rb
spec/factories/invoice_subscriptions.rb
spec/jobs/bill_subscription_job_spec.rb
spec/services/billing_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/subscription_service_spec.rb

This PR ensure that a subscription cannot is not billed twice on its creation date or the billing date

feat(timezones): Prevent double billing

---

app/jobs/bill_subscription_job.rb
app/models/invoice_subscription.rb
app/services/billing_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/subscription_service.rb
db/migrate/20221219111209_change_invoice_subscription_source.rb
db/schema.rb
db/seeds/invoices.rb
spec/factories/invoice_subscriptions.rb
spec/jobs/bill_subscription_job_spec.rb
spec/services/billing_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/subscription_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/662 but turn `source` into a boolean flag `recurring` on `InvoiceSubscription` model

feat(timezones): Turn source into a reccuring flag

---

app/controllers/api/v1/invoices_controller.rb
app/services/invoices/generate_service.rb
spec/requests/api/v1/invoices_spec.rb
spec/services/invoices/generate_service_spec.rb

The goal of this PR is to prevent downloading a draft invoice.

feat(grace_period): Prevent from downloading a draft invoice

---

app/models/credit_note.rb
app/services/events/create_service.rb
app/services/events/validate_creation_service.rb
app/services/invoices/calculate_fees_service.rb
spec/services/events/create_service_spec.rb
spec/services/events/validate_creation_service_spec.rb

The goal of this PR is to be able to create events on a terminated subscription.

feat(grace_period): Ability to create events on terminated subscription

---

app/graphql/mutations/customers/update_invoice_grace_period.rb
app/jobs/clock/finalize_invoices_job.rb
app/models/invoice.rb
app/services/customers/create_service.rb
app/services/customers/update_invoice_grace_period_service.rb
app/services/customers/update_service.rb
app/services/invoices/finalize_service.rb
app/services/invoices/refresh_draft_service.rb
app/services/invoices/subscription_service.rb
app/services/organizations/update_invoice_grace_period_service.rb
app/services/organizations/update_service.rb
spec/graphql/mutations/invoices/refresh_spec.rb
spec/jobs/clock/finalize_invoices_job_spec.rb
spec/requests/api/v1/invoices_spec.rb
spec/services/customers/create_service_spec.rb
spec/services/customers/update_invoice_grace_period_service_spec.rb
spec/services/invoices/finalize_service_spec.rb
spec/services/invoices/refresh_draft_service_spec.rb
spec/services/invoices/subscription_service_spec.rb
spec/services/organizations/update_invoice_grace_period_service_spec.rb
spec/services/organizations/update_service_spec.rb

The goal of this PR is to be able to finalize invoices when updating grace period on customer or organization.

feat(grace_period): Finalize invoices if grace period is updated

---

app/graphql/types/customers/object.rb
app/models/customer.rb
app/services/events/validate_creation_service.rb
db/migrate/20221226091020_add_nullable_to_invoice_grace_period.rb
db/schema.rb
schema.graphql
schema.json
spec/models/customer_spec.rb
spec/services/customers/update_invoice_grace_period_service_spec.rb
spec/services/events/validate_creation_service_spec.rb

- add nullable to invoice grace period column on customers
- be able to create persisted events in a terminated subscription

feat(grace_period): Add nullable to invoice_grace_period

---

app/services/events/create_service.rb
spec/services/events/create_service_spec.rb

We currently have an issue when trying to create an event without a given timestamp in the payload.
The goal of this PR is to fix this issue by assigning the current timestamp.

fix: Ability to create an event without a given timestamp

---

app/graphql/resolvers/organization_resolver.rb
app/graphql/types/query_type.rb
app/services/customers/create_service.rb
schema.graphql
schema.json
spec/graphql/mutations/customers/create_spec.rb
spec/graphql/resolvers/organization_resolver_spec.rb

- add a resolver for fetching the current organization via graphQL.
_We decided to not put this accessible via the API for now._
- fix an issue for setting invoice_grace_period to `nil` by default on customers
---

feat: Add resolver for fetching the current organization

---

app/services/customers/create_service.rb
spec/services/customers/create_service_spec.rb

Avoiding resetting billing configuration values if values are not provided in API payload

fix(customers): fix customer api update

---

app/services/events/validate_creation_service.rb
spec/factories/billable_metrics.rb
spec/services/events/validate_creation_service_spec.rb

For billable metric that is `sum_agg` or `max_agg` we need to check if event's field_name value is integer/float.
For invalid values, validation message should be raised and event should not be persisted

fix (events): add validation for invalid event field_name value

---

db/migrate/20230102150636_change_invoices_default_status.rb
db/schema.rb
spec/factories/invoices.rb
spec/graphql/mutations/invoices/finalize_spec.rb
spec/graphql/resolvers/customers/invoices_resolver_spec.rb
spec/requests/api/v1/invoices_spec.rb
spec/services/invoices/add_on_service_spec.rb
spec/services/invoices/finalize_service_spec.rb
spec/services/invoices/paid_credit_service_spec.rb

Add on and prepaid credit invoices are created in draft but they should not
This PR changes default invoice status from `draft` to `finalized` to make sure this types of invoice are not impacted by the grace period feature.

fix(invoices): invoice status should be finalized by default

---

app/controllers/api/v1/webhooks_controller.rb
config/routes.rb
spec/requests/api/v1/webhooks_spec.rb

In order to be consistent in API response types, this PR changes response type for endpoint to generate webhook public key
`api/v1/webhooks/public_key` returned text/plain in the past. It's changed now to application/json

fix (webhooks): change webhook public key endpoint reponse type

---

app/services/invoices/payments/gocardless_service.rb

In order to prevent conflicts with retry feature, we should turn off GCL auto retries.
We should prevent double charging the same invoice. It can happen in the edge case when payment first failed and after that manual retry is triggered. In the same time auto-retry started and double charge could happen. GCL also suggested to not have both mechanisms in the same time

feat (invoices): Turn off GCL auto retries

---

app/models/invoice.rb
app/services/credit_notes/create_service.rb
spec/controllers/api/v1/credit_notes_controller_spec.rb
spec/factories/invoices.rb
spec/graphql/mutations/credit_notes/create_spec.rb
spec/rails_helper.rb
spec/services/credit_notes/create_service_spec.rb
spec/support/license_helper.rb

The license management was recently introduce. Since credit note feature is supposed to be a premium one, it is impacted
This PR adds:
- the premium flag handling to unblock the feature
- Prevents the manual creation of credit notes on `draft`, `credit` or `legacy` invoices

feat(credit_notes): Add license management and handle grace period

---

db/migrate/20230106152449_turn_all_amount_cents_to_bigint.rb
db/schema.rb

In current database schema, `applied_add_ons#amount_cents` and `applied_coupons#amount_cents` are stored as integer. 
This is not a good datatype to store amount in cents as max value for an integer is `2147483648` witch could be an issue for some currency.
For example: 2'147'483'648 VND ≃ 86'433 EUR
This PR intent to turn these field into the bigint datatype allowing values up to 9'223'372'036'854'775'807
**NOTE**: a next PR will turn the GraphQL types for amount_cents fields into bigint to fix issues with large amounts

fix: Turn integer amount fields into bigint

---

lib/tasks/subscriptions.rake

The goal of this PR is to provide a way of generating invoices from a simple rake task.
We often need to generate invoices in the future for QA reasons.

misc: Ability to generate invoice from a rake task

---

app/models/invoice.rb
app/models/subscription.rb
app/services/credit_notes/create_service.rb
app/services/fees/subscription_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/finalize_service.rb
app/services/invoices/refresh_draft_service.rb
app/services/subscriptions/dates_service.rb
app/services/subscriptions/terminate_service.rb
db/migrate/20230105094302_add_nullable_to_fee_id_on_credit_note_items.rb
db/schema.rb
spec/models/subscription_spec.rb
spec/requests/api/v1/invoices_spec.rb
spec/scenarios/invoices_spec.rb
spec/services/invoices/refresh_draft_service_spec.rb

The goal of this PR is to be able to pay in advance invoices.

feat(grace_period): Ability to refresh pay in advance invoices

---

spec/requests/api/base_spec.rb

```
1) Api::BaseController sets the context source to api
Failure/Error: expect(CurrentContext.source).to eq 'api'
expected: "api"
got: nil
(compared using ==)
```

fix: Spec failure on CurrentContext.source

---

app/graphql/resolvers/add_ons_resolver.rb
app/queries/add_ons_query.rb
schema.graphql
schema.json
spec/queries/add_ons_query_spec.rb

👉  https://github.com/getlago/lago/issues/156
It’s hard for our user to find a specific objects when there’s more than 10 objects in a list view.
This PR adds the ability to search on a specific search query agains AddOns `name` and `code`

feat(add_ons): add search capability to GraphQl resolver

---

app/graphql/mutations/credit_notes/download.rb
app/jobs/credit_notes/generate_pdf_job.rb
app/services/credit_notes/generate_service.rb
spec/jobs/credit_notes/generate_pdf_job_spec.rb
spec/services/credit_notes/generate_service_spec.rb

The objective of this PR is to enforce the security of the credit note generation in GraphQL API by scopping the lookup to the connected user

fix(credit_notes): Enforce security on PDF generation from GraphQL

---

app/graphql/resolvers/coupons_resolver.rb
app/queries/coupons_query.rb
schema.graphql
schema.json
spec/queries/coupons_query_spec.rb

👉  https://github.com/getlago/lago/issues/156
It’s hard for our user to find a specific objects when there’s more than 10 objects in a list view.
This PR adds the ability to search on a specific search query agains Coupons `name` and `code`

feat(coupons): add search capability to GraphQl resolver

---

Gemfile.lock
app/graphql/resolvers/customer_credit_notes_resolver.rb
app/models/concerns/ransack_uuid_search.rb
app/models/credit_note.rb
app/queries/customer_credit_notes_query.rb
schema.graphql
schema.json
spec/queries/customer_credit_notes_query_spec.rb

👉  https://github.com/getlago/lago/issues/156
It’s hard for our user to find a specific objects when there’s more than 10 objects in a list view.
This PR adds the ability to search on a specific search query agains CreditNotes `number` and `id`
Note that Ransack needs the ID value to be a varchar in order to perform a `_cont` on it.
This PR adds an helper to transform the ID type during ransack search

feat(credit_notes): add search capability to GraphQl resolver

---

app/graphql/resolvers/invoices_resolver.rb

This PR intends to fix invoice ordering in invoices resolver.
Since current order relies only on `issuing_date` the order could be unpredictable if some invoices share the same issuing date.
The `created_at` is now used as a second param for ordering.

feat(invoices): Add second order on created_at on resolver to make order predictable

---

app/services/credit_notes/create_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/finalize_service.rb
app/services/subscriptions/dates_service.rb
lib/tasks/subscriptions.rake
spec/scenarios/invoices_spec.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/invoices/finalize_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb

The goal of this PR is to also finalize credit notes when finalizing invoices.

feat(grace_period): Finalize credit notes

---

app/services/invoices/refresh_draft_service.rb
app/services/subscriptions/create_service.rb
spec/scenarios/invoices_spec.rb

As we're not handling milliseconds, we can have issues where `terminated_at` is set before the timestamp sent to the billing job (on upgrade for instance).
The goal of this PR is to fix this by adding one second to the timestamp. The ideal solution would be to handle correctly milliseconds in the future.

feat(grace_period): Add 1 second to timestamp before billing

---

app/graphql/resolvers/invoices_resolver.rb
app/models/invoice.rb
app/queries/invoices_query.rb
schema.graphql
schema.json
spec/queries/invoices_query_spec.rb

👉  https://github.com/getlago/lago/issues/156
It’s hard for our user to find a specific objects when there’s more than 10 objects in a list view.
This PR adds the ability to search on specific attributes of an invoice
- id
- number
- customer_name
- customer_external_id
- customer_email

feat(invoices): add search capability to GraphQl resolver

---

app/services/credit_notes/create_from_termination.rb
spec/services/credit_notes/create_from_termination_spec.rb

We have an issue with the subscription termination in the following case:
1. I apply a pay in advance plan to a customer (subscription A)
2. Invoice is finalized and I applied a credit note covering the 100% of invoice
3. I decided to terminate the subscription A
4. I’ve this error, the terminate does not lead to an invoice creation
It fails with a validation failure:
```
Validation errors: {:amount_cents=>["higher_than_remaining_fee_amount", "higher_than_remaining_invoice_amount"]}
```
The reason is that when terminating the subscription, we try to emit a credit note for the overpaid amount (at prorata of the period duration) targeting the subscription fee of the last invoice. Since this fee has been already re-credited, the validation fails as there is no remaining creditable amount. …

fix(credit-notes): Fix credit note amount for terminate with previous credit note

---

Gemfile
Gemfile.lock
app/jobs/invoices/payments/gocardless_create_job.rb
app/jobs/invoices/payments/stripe_create_job.rb
config/initializers/active_job_uniqueness.rb
spec/rails_helper.rb

This PR follows https://github.com/getlago/lago-api/pull/709 and in particular the retry logic.
It take advantage of `activejob-uniqueness` gem to ensure that only one payment processing job can be processed for an invoice at a time.
Note: lock is release automatically when the job finish it's execution

feat(invoices): Lock invoice payment jobs for 1 hour

---

config/storage.yml

S3 Endpoints (not AWS) do not use `region` but it's mandatory for the `aws-sdk` gem
- Add the `region` env var support for S3 endpoints

fix(s3): Add compatible S3 Bucket Region

---

Gemfile
Gemfile.lock
app/models/billable_metric.rb
app/models/charge.rb
app/models/event.rb
app/models/group.rb
app/models/group_property.rb
app/models/persisted_event.rb
db/migrate/20230118100324_add_deleted_at_to_billable_metrics.rb
db/schema.rb
spec/requests/api/v1/billable_metrics/groups_spec.rb
spec/requests/api/v1/billable_metrics_spec.rb
spec/requests/api/v1/events_spec.rb
spec/services/billable_metrics/create_service_spec.rb

- Add `deleted_at` to all affected tables
- Setup discard gem with `deleted_at` column and default scope `kept`
- Ensure code uniqueness validation does not take into account deleted billable metrics

feat(delete_bm): Add deleted_at and setup discard for soft-delete

---

app/models/fee.rb
app/views/templates/invoice.slim
spec/factories/charges.rb
spec/factories/utils.rb
spec/services/invoices/generate_service_spec.rb

The goal of this PR is to ensure deleted resource remains visible on PDF invoice

feat(delete_bm): Expose deleted resources in PDF invoice

---

app/models/billable_metric.rb
app/serializers/v1/fee_serializer.rb
spec/factories/utils.rb
spec/models/billable_metric_spec.rb
spec/requests/api/v1/invoices_spec.rb
spec/services/invoices/generate_service_spec.rb

The goal of this PR is to ensure deleted resource attached to a fee remain visible in invoice API endpoint

feat(delete_bm): Ensure deleted resources are exposed in Invoice API endpoint

---

app/graphql/types/charges/object.rb
app/models/billable_metric.rb
spec/graphql/resolvers/invoice_resolver_spec.rb

The goal of this PR is to ensure deleted resource attached to a fee remain visible in invoice GraphQL type

feat(delete_bm): Ensure deleted resources are exposed in Invoice GrahQL type

---

lib/tasks/charges.rake
lib/tasks/events.rake

Resetting the database was not working due to the addition of the default scope on `deleted_at` column.
The goal of this PR is to fix legacy tasks by adding `unscoped`.

fix: Add unscoped to legacy tasks

---

app/graphql/types/billable_metrics/object.rb
app/graphql/types/charges/group_properties.rb
app/graphql/types/charges/object.rb
app/graphql/types/events/object.rb
app/graphql/types/groups/object.rb
schema.graphql
schema.json

The goal of this PR is to expose the `deletedAt` field in the GraphQL schema for:
- BillableMetric
- Charge
- Group
- GroupProperty
- Event

feat(delete_bm): Add deleted_at field in GraphQL schema

---

app/models/applied_coupon.rb
app/models/coupon.rb
app/serializers/v1/applied_coupon_serializer.rb
app/services/credits/applied_coupon_service.rb
schema.graphql
schema.json
spec/services/credits/applied_coupon_service_spec.rb

Add logic for handling forever coupons
Forever coupons are applied indefinitely, no matter if percentage or fixed amount

feat (coupons): add logic for handling forever coupons

---

app/graphql/types/billable_metrics/object.rb
app/serializers/v1/billable_metric_serializer.rb
schema.graphql
schema.json
spec/graphql/resolvers/billable_metric_resolver_spec.rb
spec/serializers/v1/billable_metric_serializer_spec.rb

The goal of this PR is to add on the billable metric object:
- `activeSubscriptionsCount`
- `draftInvoicesCount`
These fields are used to know the impact of deleting billable metric.

feat(delete_bm): Add activeSubscriptionsCount and draftInvoicesCount

---

app/controllers/api/v1/billable_metrics_controller.rb
app/graphql/mutations/billable_metrics/destroy.rb
app/jobs/billable_metrics/delete_events_job.rb
app/services/billable_metrics/destroy_service.rb
spec/graphql/mutations/billable_metrics/destroy_spec.rb
spec/jobs/billable_metrics/delete_events_job_spec.rb
spec/services/billable_metrics/destroy_service_spec.rb

- Refactor bm destroy service
- Discard metric and associations (charges, groups, group properties, events and persisted events)

feat(delete_bm): Discard metric and associations

---

app/graphql/types/billable_metrics/object.rb
app/jobs/billable_metrics/delete_events_job.rb
app/jobs/invoices/refresh_batch_job.rb
app/serializers/v1/billable_metric_serializer.rb
app/services/billable_metrics/destroy_service.rb
spec/graphql/resolvers/billable_metric_resolver_spec.rb
spec/serializers/v1/billable_metric_serializer_spec.rb
spec/services/billable_metrics/destroy_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb

- Track metric deletion on Segment
- Refresh linked draft invoices

feat(delete_bm): Track metric and refresh draft invoices

---

app/controllers/api/v1/plans_controller.rb
app/graphql/mutations/plans/update.rb
app/services/plans/update_service.rb
spec/services/plans/update_service_spec.rb

Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete/edit charges.
The goal of this feature is to be able to destroy a charge linked to an active or terminated subscription.
This PR merges `Plans::UpdateService#update` and `Plans::UpdateService#update_from_api` methods into a single one named `Plans::UpdateService#call`. This will reduce the amount of code to maintain and test and ensure the behavior is the same between API and GraphQL

feat(delete_charge): Refact plan update service to merge api and graphql

---

app/controllers/api/v1/plans_controller.rb
app/graphql/mutations/plans/destroy.rb
app/services/plans/destroy_service.rb
spec/services/plans/destroy_service_spec.rb

Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete/edit plans.
The goal of this feature is to be able to destroy a plans linked to an active or terminated subscription.
This PR merges `Plans::DestroyService#update` and `Plans::DestroyService#update_from_api` methods into a single one named `Plans::DestroyService#call`. This will reduce the amount of code and test  to maintain and ensure the behavior is the same between API and GraphQL

feat(delete_plan): Merge API and GraphQL service method to destroy plan

---

app/models/charge.rb
app/services/plans/update_service.rb
spec/services/billable_metrics/destroy_service_spec.rb
spec/services/plans/update_service_spec.rb

Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete/edit charges.
The goal of this feature is to be able to destroy a charge linked to an active or terminated subscription.
Objective:
- discard charge 
- discard group properties
- refresh related draft invoices

feat(delete_charge): Discard charge, properties and refresh invoices

---

app/models/coupon.rb
app/models/coupon_plan.rb
app/models/plan.rb
db/migrate/20230125104957_create_coupon_plans.rb
db/schema.rb

It’s impossible to assign a coupon only for some dedicated plans. It means that coupons is deducted from total invoice no matter the plans.
This PR adds basic DB changes needed for this feature

feat (coupons): coupons v4 db changes

---

app/models/plan.rb
db/migrate/20230126103454_add_deleted_at_to_plans.rb
db/schema.rb

The goal of this PR is to add `deleted_at` on plans.

feat(delete_plan): Add deleted_at on plans

---

app/jobs/send_webhook_job.rb
app/services/invoices/payments/gocardless_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/webhooks/invoices/payment_status_updated_service.rb
spec/jobs/send_webhook_job_spec.rb
spec/services/invoices/payments/gocardless_service_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/webhooks/invoices/payment_status_updated_service_spec.rb

Customers are not notified when a payment status is updated on an invoice when using payment providers
- Add a `invoice.payment_status_updated` webhook

feat(webhooks): Add invoice payment status updated webhook

---

app/services/payment_provider_customers/stripe_service.rb
spec/services/payment_provider_customers/stripe_service_spec.rb

Fix for the following error:
```
Module::DelegationError
PaymentProviderCustomers::StripeService#customer delegated to stripe_customer.customer, but stripe_customer is nil
```
The issue happen because, `PaymentProviderCustomers::StripeService#update_payment_method` is expecting for a `customer` attribute when trying to refresh the pending invoices.
This attribute is delegated to a `stripe_customer` instance variable, but it was not set in this context.
The fix is simple as we only need to set the `stripe_customer` instance variable.
A proper test coverage was also added

fix(stripe): prevent issue with payment method update

---

app/services/events/create_service.rb
spec/services/events/create_service_spec.rb

The goal of this PR is to not raise an exception is someone is creating an event by using a string for the timestamp.

fix: Accept timestamp as string

---

app/controllers/application_controller.rb

We don't want to wrap the parameters hash into a nested hash by default.
This will allow returning a 400 bad request when clients submit requests without specifying root elements.

misc: Disable wrap parameters by default

---

app/services/invoices/payments/stripe_service.rb
app/services/payment_providers/stripe_service.rb
spec/fixtures/stripe/payment_intent_event.json
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/payment_providers/stripe_service_spec.rb

This fix is related to the following error:
```
BaseService::NotFoundFailure
stripe_payment_not_found
```
We have A LOT of them in sentry and A LOT of related dead jobs.
The issue is that we are receiving stripe webhooks for all payment executed by Stripe, even those not initiated by Lago, leading to a failure because the app is unable to find a matching payment.
Since we are sending the invoice ID in the metadata when initiating the payment, to we should be looking for the presence of this id in the hook object metadata and ignore the hook if the field is not present.

fix(stripe): Ignore not found payment webhook when not created with lago

---

app/graphql/types/plans/object.rb
app/serializers/v1/plan_serializer.rb
schema.graphql
schema.json
spec/graphql/resolvers/plan_resolver_spec.rb
spec/serializers/v1/plan_serializer_spec.rb

The goal of this PR is to add two counters in the `V1::PlanSerializer` and `Plan` GraphQL type:
- `active_subscription_count`
- `draft_invoice_count`

feat(delete_plan): Add subscription and invoice counters to plans

---

app/services/applied_coupons/create_service.rb
spec/services/applied_coupons/create_service_spec.rb

It’s impossible to assign a coupon only for some dedicated plans. It means that coupons is deducted from total invoice no matter the plans.
This PR adds validation that prevent adding plan limitation only if there is plan limitation already added on previous coupon (that is applied on customer)

feat (coupons): coupon overlapping plans validation

---

app/controllers/api/v1/subscriptions_controller.rb
app/graphql/mutations/subscriptions/terminate.rb
app/jobs/subscriptions/terminate_job.rb
app/services/subscriptions/terminate_service.rb
spec/graphql/mutations/subscriptions/terminate_spec.rb
spec/jobs/subscriptions/terminate_job_spec.rb
spec/services/subscriptions/terminate_service_spec.rb

The goal of this PR is to merge `Subscriptions::TerminateService#terminate` and `Subscriptions::TerminateService#terminate_from_api` into a single one named `call`.

feat(delete_plan): Merge subscription terminate methods

---

app/graphql/types/plans/object.rb
app/models/plan.rb
app/services/plans/destroy_service.rb
schema.graphql
schema.json
spec/graphql/resolvers/plans_resolver_spec.rb
spec/requests/api/v1/plans_spec.rb
spec/services/plans/destroy_service_spec.rb

The goal of this PR is to remove `canBeDeleted` from plans.

feat(delete_plan): Remove plan canBeDeleted

---

app/controllers/api/v1/plans_controller.rb
app/graphql/mutations/plans/destroy.rb
app/graphql/types/invoices/object.rb
app/jobs/plans/destroy_job.rb
app/models/plan.rb
app/models/subscription.rb
app/queries/plans_query.rb
app/services/plans/destroy_service.rb
app/services/plans/prepare_destroy_service.rb
app/services/subscriptions/terminate_service.rb
db/migrate/20230127140904_add_pending_deletion_to_plans.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/mutations/plans/destroy_spec.rb
spec/requests/api/v1/plans_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/destroy_service_spec.rb
spec/services/plans/prepare_destroy_service_spec.rb

The goal of this PR is to be able to remove plans even if they are linked to active subscriptions.

feat(delete_plan): Ability to delete a plan linked to subscriptions

---

app/controllers/api/v1/customers_controller.rb
app/graphql/mutations/customers/destroy.rb
app/services/customers/destroy_service.rb
config/routes.rb
spec/requests/api/v1/customers_spec.rb
spec/services/customers/destroy_service_spec.rb

The goal of this PR is to add the missing route `DELETE /api/v1/customers/:external_id` and to improve the `Customers::DestroyService`

feat(delete_customer): Add API delete route and improve services

---

spec/services/invoices/finalize_service_spec.rb

The goal of this PR is to fix the following flaky test:
```
Invoices::FinalizeService#call updates the issuing date
Failure/Error:
expect { finalize_service.call }
.to change { invoice.reload.issuing_date }.to(Time.current.to_date)
expected `invoice.reload.issuing_date` to have changed to Wed, 01 Feb 2023, but did not change
```

fix: Flaky test on finalizing invoices

---

app/models/invoice_subscription.rb

- The order is wrong on the `order_by_charges_to_datetime` since it's `ASC` and we want a `DESC` to use it for the `Subscriptions::DateService#last_invoice_subscription`.
- change the order to `DESC`

fix(subscriptions): Fix invoice subscriptions order

---

app/controllers/api/v1/coupons_controller.rb
app/graphql/mutations/coupons/destroy.rb
app/models/coupon.rb
app/services/coupons/destroy_service.rb
db/migrate/20230131152047_add_deleted_at_to_coupons.rb
db/schema.rb
spec/graphql/mutations/coupons/destroy_spec.rb
spec/services/coupons/create_service_spec.rb
spec/services/coupons/destroy_service_spec.rb

To allow soft deletion of customers, we first need to be able to soft delete add_ons and coupons
The goal of this PR is to add a `deleted_at` field to the `coupons` table and the Discard logic to allow soft deletion.

feat(delete_coupon): Add ability to soft delete a coupon

---

app/models/coupon.rb
app/models/coupon_plan.rb
app/models/plan.rb
db/migrate/20230125104957_create_coupon_plans.rb
db/schema.rb

It’s impossible to assign a coupon only for some dedicated plans. It means that coupons is deducted from total invoice no matter the plans.
This PR adds DB changes that are needed for coupons with plan limitations

feat (coupons): add DB changes for coupons with plan limitations

---

lib/tasks/coupons.rake

Resetting the database was not working due to the addition of the default scope on the deleted_at column.
The goal of this PR is to fix legacy tasks by adding unscoped.

feat(delete_coupon): Add unscoped to legacy coupon's tasks

---

app/services/credit_notes/create_from_termination.rb
spec/scenarios/invoices_spec.rb

By terminating a subscription with usage, we got the previous error. Credit note and invoice are not created.
1. Create a plan **************Premium**************
2. Attach 2 usage based charges
3. Ingest usage
4. Terminate subscription
5. >> Bug
```
BaseService::ValidationFailure
Validation errors: {:base=>["does_not_match_item_amounts"]}
```
The issue is related to the rounding of the credit note amount.
Credit note VAT for `credit_amount_cents` is computed without rounding on the amount but once assigned to the item, the amount rounded down automatically by rails because the field is stored as an integer.
It could leads to an error in validation of the credit_amount_cents against item total_amounts. The fix is to round the amount before computing the `credit_amount_cents` to make sure …

fix(subscription): Fix credit note amount validation when terminating

---

app/graphql/types/billable_metrics/object.rb
app/graphql/types/plans/object.rb
schema.graphql
schema.json
spec/graphql/resolvers/billable_metric_resolver_spec.rb
spec/graphql/resolvers/plan_resolver_spec.rb

We want to restrict the edition of BM and plan if they are attached to subscriptions.
The goal of this PR is to return:
- number of subscriptions linked to a plan
- number of subscriptions linked to a BM

feat(subscriptions): Add subscriptions count to BM and plan

---

app/models/payment_provider_customers/base_customer.rb
db/migrate/20230202110407_add_index_to_payment_provider_customers.rb
db/schema.rb

In production, two users have duplicated Stripe customers. The reason why is still unclear, but it leads to unpredictable behaviors when trying to update the stripe customer id.
To prevent duplication of payment provider customer, this PR adds a validation rule to ensure each customer can have only one PaymentProviderCustomer per type of provider.

fix(payment_provider): Prevent duplicated payment provider customers

---

app/models/customer.rb
db/migrate/20230202150407_add_deleted_at_to_customers.rb
db/schema.rb
lib/tasks/customers.rake
spec/services/customers/create_service_spec.rb

The goal of this PR is to add the `deleted_at` column to the `customers` table, to allow soft deletion of customers

feat(delete_customer): Add attributes to allow soft deletion

---

app/services/add_ons/update_service.rb
spec/services/add_ons/update_service_spec.rb

The goal of this PR is to restrict the update of an add_on if already applied to a subscription.

feat: Restrict add on update if already applied

---

app/graphql/types/add_ons/object.rb
app/graphql/types/coupons/object.rb
app/models/add_on.rb
schema.graphql
schema.json
spec/graphql/resolvers/add_on_resolver_spec.rb
spec/graphql/resolvers/coupon_resolver_spec.rb
spec/graphql/resolvers/coupons_resolver_spec.rb
spec/models/add_on_spec.rb

- Remove `can_be_deleted` on `coupons` and `add_ons`
- Add `appliedCouponsCount` and `appliedAddOnsCount`
In order to know if a specific coupon or add_on can be updated or deleted.

feat: Remove can_be_deleted on coupons and add_ons

---

app/models/fee.rb
app/services/add_ons/destroy_service.rb
spec/factories/fees.rb
spec/graphql/resolvers/invoice_resolver_spec.rb
spec/models/add_on_spec.rb
spec/services/add_ons/destroy_service_spec.rb

To allow soft deletion of customers, we first need to be able to soft delete add_ons and coupons
The goal of this PR add the soft deletion logic for add_ons

feat(delete_add_on): Process soft deletion

---

app/models/coupon.rb
app/models/coupon_plan.rb
app/models/credit.rb
app/services/coupons/destroy_service.rb
app/services/coupons/update_service.rb
db/migrate/20230203132157_add_deleted_at_to_coupon_plans.rb
db/schema.rb
spec/factories/coupon_plans.rb
spec/models/coupon_spec.rb
spec/requests/api/v1/coupons_spec.rb
spec/services/add_ons/destroy_service_spec.rb
spec/services/billable_metrics/destroy_service_spec.rb
spec/services/coupons/destroy_service_spec.rb
spec/services/plans/destroy_service_spec.rb

This PR adds the ability to soft-delete a coupon and coupon plans.

feat(delete_coupon): Soft delete coupon and coupon plans

---

app/graphql/mutations/applied_coupons/terminate.rb
app/services/applied_coupons/terminate_service.rb
app/services/coupons/destroy_service.rb
spec/services/add_ons/destroy_service_spec.rb
spec/services/applied_coupons/terminate_service_spec.rb
spec/services/coupons/destroy_service_spec.rb

This PR adds the ability to terminate active applied coupons on coupon deletion.

feat(delete_coupon): Terminate applied coupons on deletion

---

app/models/credit_note.rb
app/views/templates/credit_note.slim
spec/models/credit_note_spec.rb

We have an issue with the PDF for credit notes on add_on invoice:
To reproduce:
1. I apply a credit note to an add-invoice
2. I’m in the credit note and I download the .pdf of credit note
3. There’s no details line in the invoice
This PR fixes PDF by ensuring add on label is displayed when initial fee was for an add_on

fix(credit_note): Fix item label when related to an add on invoice

---

app/controllers/api/v1/customers/applied_coupons_controller.rb
app/controllers/api/v1/customers_controller.rb
config/routes.rb
spec/requests/api/v1/customers/applied_coupons_spec.rb

This PR adds the ability to terminate an applied coupon from the API.

feat(delete_coupon): Ability to terminate an applied coupon from the API

---

app/controllers/api/v1/wallets_controller.rb
app/graphql/mutations/wallets/terminate.rb
app/jobs/customers/terminate_relations_job.rb
app/models/subscription.rb
app/services/customers/destroy_service.rb
app/services/customers/terminate_relations_service.rb
app/services/wallets/terminate_service.rb
spec/jobs/customers/terminate_relations_job_spec.rb
spec/services/customers/destroy_service_spec.rb
spec/services/customers/terminate_relations_service_spec.rb
spec/services/wallets/terminate_service_spec.rb

This PR add the logic to:
- Terminate the active subscription
- Finalize the draft invoices
- Cancel the pending subscription
- Terminate the active wallets
- Terminate the active applied coupons
when soft deleting a customer

feat(delete_customer): Terminate all customer resources

---

app/services/credits/applied_coupon_service.rb
app/services/invoices/calculate_fees_service.rb
spec/services/credits/applied_coupon_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb

It’s impossible to assign a coupon only for some dedicated plans. It means that coupons is deducted from total invoice no matter the plans.
This PR handles applying coupons with plan limitations on invoice

feat (coupons): apply coupons with plan limitations on invoice

---

spec/scenarios/delete_customer_spec.rb
spec/support/scenarios_helper.rb

This PR adds a spec scenario for deleting a customer.

feat(delete_customer): Add scenario spec

---

app/controllers/api/v1/invoices_controller.rb
app/graphql/types/add_ons/object.rb
app/graphql/types/applied_add_ons/object.rb
app/graphql/types/customers/object.rb
app/jobs/clock/terminate_wallets_job.rb
app/models/credit_note.rb
app/models/customer.rb
app/models/invoice.rb
app/models/organization.rb
app/services/customers/destroy_service.rb
app/services/customers/terminate_relations_service.rb
app/services/wallets/terminate_service.rb
schema.graphql
schema.json
spec/graphql/mutations/credit_notes/update_spec.rb
spec/graphql/mutations/credit_notes/void_spec.rb
spec/graphql/resolvers/credit_note_resolver_spec.rb
spec/jobs/clock/terminate_wallets_job_spec.rb
spec/models/customer_spec.rb
spec/requests/api/v1/invoices_spec.rb
spec/scenarios/delete_customer_spec.rb
spec/services/credit_notes/refunds/gocardless_service_spec.rb
spec/services/credit_notes/refunds/stripe_service_spec.rb
spec/services/customers/destroy_service_spec.rb
spec/services/wallets/terminate_service_spec.rb
spec/services/webhooks/credit_notes/created_service_spec.rb
spec/services/webhooks/credit_notes/generated_service_spec.rb
spec/services/webhooks/credit_notes/payment_provider_refund_failure_service_spec.rb
spec/support/scenarios_helper.rb

This PR adds two changes:
- It removes the not allowed error when trying to delete a plan attached to a subscription
- It removes the `canBeDeleted` attribute from the `Customer` GraphQL type

feat(delete_customer): Remove delete limitation

---

app/controllers/api/v1/organizations_controller.rb
app/serializers/v1/organization_serializer.rb
app/services/organizations/update_service.rb
spec/requests/api/v1/organizations_spec.rb
spec/serializers/v1/organization_serializer_spec.rb

For legal reason, some companies had to generate invoices in their own languages. Unfortunately Lago is supporting only one language that do not fit their need.
This PR handles updating organization document locale from the API

feat (localization): update org document locale from the API

---

app/controllers/api/v1/customers_controller.rb
app/serializers/v1/customer_serializer.rb
app/services/customers/create_service.rb
spec/requests/api/v1/customers_spec.rb
spec/serializers/v1/customer_serializer_spec.rb
spec/services/customers/create_service_spec.rb

For legal reason, some companies had to generate invoices in their own languages. Unfortunately Lago is supporting only one language that do not fit their need.
This PR handles updating customer document locale from the API

feat (localization): support managing customer document locale through the API

---

app/services/credit_notes/create_from_termination.rb
spec/scenarios/terminate_pay_in_advance_spec.rb
spec/services/credit_notes/create_from_termination_spec.rb

As a user with a specific time zone, when terminating a subscription pay in advance, the amount of the credit note is not accurate.
The issue was related to the `optional_from_date` passed to the method used to compute the single day price on a period. In the case of a positive time shift with UTC, the wrong day was used as the beginning of the period, leading to a wrong single day price.

fix(credit_notes): Fix downgrade credit notes when timezone

---

spec/services/billing_service_spec.rb

- Do not use a `now` for this spec

fix(specs): Fix a flaky test on subscriptions date

---

app/services/invoices/calculate_fees_service.rb
app/services/invoices/compute_amounts_from_fees.rb
app/services/invoices/refresh_draft_service.rb
spec/services/invoices/compute_amounts_from_fees_spec.rb

Lago API performs some math on top of monetary values, to calculate VAT, internal fees, etc.
Since these operations are done using integer amounts in cents and are spread around the codebase, there are some rounding issues and inconsistencies, like off-by-one errors.
This PR ensure VAT amount stored at invoice level is computed based on fee amount without using rounded value stored at fee level, to prevent rounding issues

fix(invoices): Round VAT at invoice level

---

app/services/invoices/customer_usage_service.rb
spec/services/invoices/customer_usage_service_spec.rb

Lago API performs some math on top of monetary values, to calculate VAT, internal fees, etc.
Since these operations are done using integer amounts in cents and are spread around the codebase, there are some rounding issues and inconsistencies, like off-by-one errors.
This PR ensure VAT amount computed at invoice level on customer current usage is computed based on fee amount without using rounded value computed at fee level, to prevent rounding issues

fix(usage): Round VAT at invoice level

---

app/models/invoice.rb
spec/models/invoice_spec.rb
spec/services/credit_notes/validate_item_service_spec.rb
spec/services/credit_notes/validate_service_spec.rb

Lago API performs some math on top of monetary values, to calculate VAT, internal fees, etc.
Since these operations are done using integer amounts in cents and are spread around the codebase, there are some rounding issues and inconsistencies, like off-by-one errors.
This PR ensure VAT amount computed to validate credit notes is computed based on fee amount without using rounded value stored on fees, in order to prevent rounding issues

fix(credit_notes): Round VAT at credit note level

---

app/controllers/api/v1/applied_add_ons_controller.rb
app/graphql/mutations/applied_add_ons/create.rb
app/services/applied_add_ons/create_service.rb
spec/services/applied_add_ons/create_service_spec.rb

This PR merges `AppliedAddOns::CreateService#create` and `AppliedAddOns::CreateService#create_from_api` methods into a single one named `AppliedAddOns::CreateService#call`. 

misc: Merge API and GraphQL AppliedAddOn create services

---

app/controllers/api/v1/applied_coupons_controller.rb
app/graphql/mutations/applied_coupons/create.rb
app/services/applied_coupons/create_service.rb
spec/services/applied_coupons/create_service_spec.rb

This PR merges `AppliedCoupons::CreateService#create` and `AppliedCoupons::CreateService#create_from_api` methods into a single one named `AppliedCoupons::CreateService#call`. 

misc: Merge API and GraphQL AppliedCoupon create services

---

app/controllers/api/v1/billable_metrics_controller.rb
app/graphql/mutations/billable_metrics/update.rb
app/services/billable_metrics/update_service.rb
spec/services/billable_metrics/update_service_spec.rb

This PR merges `BillableMetrics::UpdateService#update` and `BillableMetrics::UpdateService#update_from_api` methods into a single one named `BillableMetrics::UpdateService#call`. 

misc: Merge API and GraphQL BillableMetric update services

---

app/controllers/api/v1/customers/applied_coupons_controller.rb
config/routes.rb
spec/requests/api/v1/customers/applied_coupons_spec.rb

Currently we can assign multiple coupons of a same type on a customer. That being said we need to remove applied coupon by unique identifier.

fix (applied coupons): fix delete applied coupon logic by using lago id as identifier

---

app/controllers/api/v1/subscriptions_controller.rb
app/graphql/mutations/subscriptions/create.rb
app/services/subscriptions/create_service.rb
spec/services/subscriptions/create_service_spec.rb

This PR merges `Subscriptions::CreateService#create` and `Subscriptions::CreateService#create_from_api` methods into a single one named `Subscriptions::CreateService#call`. 

misc: Merge API and GraphQL Subscription create services

---

app/services/invoices/payments/stripe_service.rb
spec/services/invoices/payments/stripe_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/773
This fix is related to the following error:
```
BaseService::NotFoundFailure
stripe_payment_not_found
```
We have A LOT of them in sentry and A LOT of related dead jobs.
The issue is that we are receiving stripe webhooks for all payment executed by Stripe, even those not initiated by the receiving lago instance, leading to a failure because the app is unable to find a matching payment.
Since we are sending the invoice ID in the metadata when initiating the payment, to we should be looking for the presence of this invoice in the database and ignore the hook if the invoice is not found.

fix(stripe): Ignore not found payment webhook when no invoice

---

app/services/payment_provider_customers/stripe_service.rb
app/services/payment_providers/stripe_service.rb
spec/services/payment_provider_customers/stripe_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/845
This fix is related to the following error:
```
BaseService::NotFoundFailure
stripe_customer_not_found
```
We have A LOT of them in sentry and A LOT of related dead jobs.
The issue is that we are receiving stripe webhooks for all customer changes executed by Stripe, even those not initiated by the receiving lago instance, leading to a failure because the app is unable to find a matching customer.
Since we are sending the customer ID in the metadata when initiating creating a customer, we should be looking for the presence of this customer in the database and ignore the hook if the customer is not found.

fix(stripe): Ignore not found customer webhook when no customer

---

app/controllers/api/v1/coupons_controller.rb
app/graphql/mutations/coupons/update.rb
app/services/coupons/update_service.rb
spec/services/coupons/update_service_spec.rb

This PR merges `Coupons::UpdateService#update` and `Coupons::UpdateService#update_from_api` methods into a single one named `Coupons::UpdateService#call`. 

misc: Merge API and GraphQL Coupons update services

---

app/services/payment_providers/stripe_service.rb

This PR fixes a typo in the error capture when removing a webhook URL from Stripe API.

fix(stripe): Capture error when removing webhook url

---

app/models/customer.rb
app/models/metadata/customer_metadata.rb
db/migrate/20230221070501_create_customer_metadata.rb
db/schema.rb
spec/factories/customer_metadata.rb
spec/models/metadata/customer_metadata_spec.rb

Creating a customer with Lago’s basic information is not enough to bring context.
This PR adds customer metadata table and model relations/validations

feat (metadata): add basic model setup for customer metadata

---

app/controllers/api/v1/applied_coupons_controller.rb
app/serializers/v1/applied_coupon_serializer.rb
app/serializers/v1/credit_serializer.rb
spec/serializers/v1/applied_coupon_serializer_spec.rb
spec/serializers/v1/credit_serializer_spec.rb

Some clients requested extension for applied coupons serializer. They want to see on which invoices coupon was spent and the amount that is used. This can be achieved by extending credit serializer and returning list of credits with each applied coupon.

feat(applied coupons): extend applied coupon serializer

---

app/services/credit_notes/create_from_termination.rb
app/services/credit_notes/create_service.rb
app/services/credit_notes/validate_service.rb
db/migrate/20230221102035_add_precise_amount_cents_to_credit_note_items.rb
db/schema.rb
spec/factories/credit_note_items.rb
spec/scenarios/terminate_pay_in_advance_spec.rb
spec/services/credit_notes/validate_service_spec.rb

The goal of this PR is to fix rounding issues by using a precise amount cents for credit note items.

feat(rounding): Add precise amount cents to credit note items

---

app/services/plans/update_service.rb
spec/services/plans/update_service_spec.rb

We don't want to sanitize charges if they are not passed at all on update request

bug (plans): fix update plan charges condition

---

app/services/credit_notes/create_from_termination.rb
spec/services/credit_notes/create_from_termination_spec.rb

This PR is a fix for some validation errors when creating credit notes for terminated subscription:
```
Validation errors: {:amount_cents=>["higher_than_remaining_fee_amount", "higher_than_remaining_invoice_amount"]}
```
Order of the query to fetch the last subscription fee as target of the credit note item, was always returning the first fee created on the subscription...

fix(credit-notes): Take max creditable amount when terminating subscription

---

app/services/invoices/payments/retry_service.rb
spec/services/invoices/payments/retry_service_spec.rb

When performing invoice retry action wrong webhook type was passed as parameter

fix(webhooks): [BUG] Change webhook type for invoice retry action

---

app/models/credit.rb
spec/models/credit_spec.rb

When a coupon is deleted it could remain visible on invoice if it has generated a credit line.
Current implementation fails when trying to retrieve the coupon display name for the PDF document.
To fix the issue, we need to rely on the `coupon` relation at credit level rather than on `applied_coupon.coupon` because relation uses `with_discared` scope to include automatically deleted coupons.

fix(coupons): Fix deleted coupon display on invoice

---

app/controllers/api/v1/customers_controller.rb
app/serializers/v1/customer_serializer.rb
app/serializers/v1/customers/metadata_serializer.rb
app/services/customers/create_service.rb
app/services/customers/metadata/update_service.rb
app/services/customers/update_service.rb
spec/requests/api/v1/customers_spec.rb
spec/serializers/v1/customer_serializer_spec.rb
spec/serializers/v1/customers/metadata_serializer_spec.rb
spec/services/customers/create_service_spec.rb
spec/services/customers/metadata/update_service_spec.rb

Currently additional customer data cannot be stored in Lago
This PR handles customer metadata for create and update API requests

feat (customer_metadata): handle customer metadata create and update for API

---

app/graphql/resolvers/events_resolver.rb
spec/graphql/resolvers/events_resolver_spec.rb

The goal of this PR is to not return duplicated events on the debugger for deleted billable metrics.

fix: Do not duplicate events on debugger

---

fern/api/generators.yml

Updating the java client with fern failed because it was pointing to a non-existent repo.

misc(fern): Fix java client repository name

---

fern/api/generators.yml

Adds a new generator to publish the fern generated OpenAPI spec to `getlago/lago-openapi-v2`

generate OpenAPI for `getlago/lago-openapi-v2`

---

app/models/invoice_subscription.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/refresh_draft_service.rb
app/services/invoices/subscription_service.rb
spec/services/invoices/refresh_draft_service_spec.rb

An issue of "double invoice generation" has been raised. After investigation, it is related to the  `recurring` status of an invoice subscription that is lost during the refresh of a draft invoice.
This status is used by the BillingService to identify the subscription that have already been billed on their billing day to prevent them to be re-billed during the same day.
By loosing the `recurring` status, the billing job was unable to identify these subscription and so was re-enqueuing a `BillingJob`
To fix the issue, we need to keep the pre-existing `recurring` flag when refresing a draft invoice.

fix(invoices): Prevent double billing when refreshing draft invoices

---

PULL_REQUEST_TEMPLATE.md

We now use Canny to maintain our public roadmap.
https://getlago.canny.io/feature-requests

chore: Update PULL_REQUEST_TEMPLATE.md

---

app/services/billing_service.rb
spec/services/billing_service_spec.rb

Protection against double billing was not effective for `UTC+X` timezone as it was not checking the timestamp in the customer timezone.
This was leading to double invoice generation...
The fix is to ensure that customer applicable timezone is taken into account when checking if a subscription has already been billed on its billing day.

fix(invoice): Prevent double billing with timezone

---

app/models/charge.rb
config/locales/en.yml
db/migrate/20230227145104_add_instant_to_charges.rb
db/schema.rb
spec/factories/billable_metrics.rb
spec/factories/charges.rb
spec/models/charge_spec.rb

- add `instant` to `Charge`
- add error when trying to create an instant charge for a `recurring_count_agg` or `max_agg` billable metric
- add error when trying to create an instant charge for a `volume` charge model

feat(instant_charge): Ability to have instant charges

---

app/controllers/api/v1/fees_controller.rb
app/models/organization.rb
config/routes.rb
spec/requests/api/v1/fees_spec.rb

This PR adds a new route to retrieve a single fee via the API (`GET /api/v1/fees/:id`)

feat(instant_charge): Add API route to show a fee

---

app/graphql/types/charges/input.rb
app/graphql/types/charges/object.rb
schema.graphql
schema.json

The goal of this PR is to return `instant` to `Charge` via graphql.

feat(instant_charge): Add instant to Charge via GraphQL

---

fern/api/generators.yml

The java client should be published under Lago's GitHub org.

publish java client to `io.github.lago-api:lago`

---

app/models/event.rb
spec/graphql/resolvers/events_resolver_spec.rb

Destroying a customer (actually soft deleting it) does not destroy the customer events. It is the intended behavior but it leads to an error in the event debugger because the customer appears as missing.
To fix this issue, we need to make sure the customer remain visible from an event.

fix(events): Fix debugger with deleted customers

---

app/models/fee.rb
schema.graphql
schema.json
spec/models/fee_spec.rb

This PR allows a fee to be created withou an invoice

feat(instant_charge): Allow fees#invoice_id to be null

---

app/jobs/fees/create_instant_job.rb
app/services/events/create_service.rb
app/services/fees/create_instant_service.rb
spec/jobs/fees/create_instant_job_spec.rb
spec/services/events/create_service_spec.rb

This PR adds a the logic to perform an instant fee creation when an created event matches an instant charge

feat(instant_charge): Enqueue job to process an instant charge for a new event

---

app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
spec/services/billable_metrics/aggregations/count_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb

This PR adds the logic to compute the instant aggregation for each aggregation types impacted by the feature

feat(instant_charge): Compute instant aggregation

---

app/services/charges/apply_instant_charge_model_service.rb
spec/services/charges/apply_instant_charge_model_service_spec.rb

This PR adds the instant aggregation service on charges.

feat(instant_charge): Add instant aggregation service on charges

---

db/migrate/20230307131524_add_instant_event_id_to_fees.rb
db/schema.rb

This PR adds a new `instant_event_id` column to the fees table, in order to keep track of the event leading to the creation of the fee.
The data type is intentionally using `string` over `uuid` because no foreign key will be defined on the relation and we might want to be able to delete old events or to …

feat(instant_charge): Add instant_event_id to fees to track instant fee source

---

app/services/fees/create_instant_service.rb
spec/services/fees/create_instant_service_spec.rb

This PR adds the instant fee creation logic using previously introduced `BillableMetrics::InstantAggregationService` and `Charges::ApplyInstantChargeModelService`

feat(instant_charge): Add instant fee creation service

---

app/jobs/send_webhook_job.rb
app/services/fees/create_instant_service.rb
app/services/webhooks/fees/instant_created_service.rb
spec/jobs/send_webhook_job_spec.rb
spec/services/fees/create_instant_service_spec.rb
spec/services/webhooks/fees/instant_created_service_spec.rb

This PR delivers a new webhook `fee.instant_charge_created` when a fee is created for an instant charge

feat(instant_charge): Deliver webhooks for created fees

---

app/controllers/api/v1/invoices_controller.rb
app/serializers/v1/invoice_serializer.rb
app/serializers/v1/invoices/metadata_serializer.rb
spec/requests/api/v1/invoices_spec.rb
spec/serializers/v1/invoice_serializer_spec.rb
spec/serializers/v1/invoices/metadata_serializer_spec.rb

Currently it is not possible to store additional invoice informations in the Lago
This PR adds support for handling invoice metadata through the API.

feat(invoice_metadata): Handle invoice metadata through the api

---

app/models/organization.rb
spec/requests/api/v1/fees_spec.rb

This PR allows fetching an instant charge via `GET api/v1/fees/:id` endpoint.

feat(instant_charge): Fetch fee from subscriptions instead of invoices

---

app/services/customers/create_service.rb
spec/services/customers/create_service_spec.rb

Save correctly customer billing configuration upon customer creation

fix (customers): save correctly customer billing configuration upon customer creation

---

app/services/charges/apply_instant_charge_model_service.rb
db/schema.rb
spec/scenarios/instant_charges_spec.rb
spec/support/scenarios_helper.rb

This PR adds new test scenarios for instant charge feature

feat(instant_charge): Add scenarios

---

.rubocop.yml

We decided to disable this Rubocop rule

misc(Rubocop): Disable ExtractType rule

---

app/models/coupon.rb
spec/models/coupon_spec.rb
spec/requests/api/v1/applied_coupons_spec.rb
spec/services/credits/applied_coupon_service_spec.rb
spec/services/credits/applied_coupons_service_spec.rb

`amount_cents`, `amount_currency` and `percentage_rate` are required fields but only for certain coupon type. This PR is adding missing validations

feat (coupons): add few more coupon validations

---

app/services/credit_notes/create_from_termination.rb
spec/services/credit_notes/create_from_termination_spec.rb

A new rounding error just poped-up with the credit note termination amount.
The issue is related to the automatic rounding done by rails when setting the "precise_amount" on the credit note item. Since the max precision of the field is 5 digit, rails apply a rounding to the value. In some cases this rounding led to a validation error when comparing the item amount and the credit note amount.
Example:
Computed amount in the terminate service: 499.49999999999994
Rounded for the `credit_amount_cents`: 499
Stored at item level: 499.5 (`= amount.round(5)`)
Rounded for comparison with credit note total_amount: 500 :boom: 
To prevent the issue, we should manually apply a `truncate` with the maximum precision instead of letting rails rounding the value

fix(credit-notes): Truncate item amount on termination

---

Gemfile.lock
app/services/charges/charge_models/percentage_service.rb
spec/scenarios/charge_models/percentage_spec.rb
spec/support/scenarios_helper.rb

The goal of this PR is to fix an issue we currently have when calculating `free_units_count` for the percentage charge model.
I also added some scenarios in order to improve the coverage of our tests.

fix: Correct percentage calculation for fixed amount

---

lib/tasks/invoices.rake

It seens it's not possible to migrate from a version prior to v0.22.0-beta to version higher than v0.24.0-beta.
It's related to the introduction of paper trail, preventing to run a migration task in `AddOrganizationIdToInvoices` migration because the `versions` table used by papertrail does not exist yet.
The solution is to temporary turn off the versioning while running the migration task

fix: Ensure migrations with tasks from prior v0.24.0-beta passes

---

app/controllers/api/v1/plans_controller.rb
app/serializers/v1/charge_serializer.rb
app/serializers/v1/fee_serializer.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/plans/create_service.rb
app/services/plans/update_service.rb
spec/scenarios/instant_charges_spec.rb
spec/serializers/v1/charge_serializer_spec.rb
spec/serializers/v1/fee_serializer_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/update_service_spec.rb
spec/services/webhooks/base_service_spec.rb

This PR allows to have an instant charge.

feat(instant_charge): Ability to have an instant charge

---

app/controllers/api/v1/events_controller.rb
config/routes.rb
spec/requests/api/v1/events_spec.rb

This PR introduces a new `POST api/v1/events/estimate_fees` route to retrieve a list of expected instant fees that would be created after reception of a specific event

feat(instant_charge): Add API route to estimate instant fees amount

---

app/graphql/types/charges/graduated_range.rb
app/graphql/types/charges/graduated_range_input.rb
app/graphql/types/charges/group_properties.rb
app/graphql/types/charges/group_properties_input.rb
app/graphql/types/charges/properties.rb
app/graphql/types/charges/properties_input.rb
app/graphql/types/charges/volume_range.rb
app/graphql/types/charges/volume_range_input.rb
schema.graphql
schema.json
spec/graphql/mutations/plans/create_spec.rb
spec/graphql/mutations/plans/update_spec.rb

A bug was discovered wile trying to create charges with large numbers (`9,999,999,999` for example).
This issue is that GraphQL type definition are using `Integer` type which is limiter to 32 bits.
The fix is to switch the type to `BigInt`

fix(charge_models): Change Integer types to BigInt

---

app/views/templates/credit_note.slim
app/views/templates/invoice.slim

If metadata key and value are too long, table content gets cut and not displayed properly

fix(invoice template): fix invoice template header overflow

---

app/models/refund.rb
db/migrate/20230327134418_remove_payment_provider_null_constraint_on_refunds.rb
db/schema.rb

Removing Stripe api Key raised 500 if there are refunds objects
When we remove PaymentProviders::BaseProvider, dependent objects also need to be nullified:
`has_many :refunds, dependent: :nullify, foreign_key: :payment_provider_id`
However, on `refunds` table, `payment_provider_id` was marked as null: false, so destroy operation raises 500 since we are not able to set null on `payment_provider_id`

fix (payment providers): remove null constraint on refunds for payment_provider_id field

---

app/services/invoices/payments/gocardless_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/invoices/update_service.rb
spec/services/invoices/payments/gocardless_service_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/invoices/update_service_spec.rb

Also related to https://getlago.canny.io/developer-experience/p/receive-a-webhook-for-invoicepaymentstatus-update
This PR refactors the invoice payment status management to pave the way for fee payment status management.
The objective is to …

feat(instant_charge): Add service to update invoice status

---

app/jobs/invoices/update_fees_payment_status_job.rb
app/models/fee.rb
app/services/fees/add_on_service.rb
app/services/fees/charge_service.rb
app/services/fees/create_instant_service.rb
app/services/fees/paid_credit_service.rb
app/services/fees/subscription_service.rb
app/services/invoices/update_service.rb
db/migrate/20230323112252_add_payment_status_to_fees.rb
db/schema.rb
spec/jobs/invoices/update_fees_payment_status_job_spec.rb
spec/services/fees/add_on_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/create_instant_service_spec.rb
spec/services/fees/paid_credit_service_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/invoices/update_service_spec.rb

This PR adds new `payment_status` field to `fees` table and ensures this field is always set

feat(instant_charge): Add and update fees#payment_status

---

app/controllers/api/v1/fees_controller.rb
app/models/fee.rb
app/serializers/v1/fee_serializer.rb
app/services/customers/terminate_relations_service.rb
app/services/fees/update_service.rb
app/services/invoices/update_service.rb
config/routes.rb
spec/requests/api/v1/fees_spec.rb
spec/serializers/v1/fee_serializer_spec.rb
spec/services/fees/update_service_spec.rb

This PR adds a new `PUT /api/v1/fees/:id` route to update the payment status of a fee. It delegates the logic to a `Fees::UpdateService`

feat(instant_charge): add API end-point to update fee payment_status

---

app/views/layouts/mailer.slim

We'll have a new mail templates that won't have certain data we expect to be provided.
This template will use this mailer template.
It was initially done [in the feature PR](https://github.com/getlago/lago-api/pull/942/commits) but can easily be extracted
This PR makes the template hide those sections if the data is not provided

misc(mailer): prevent orga info display when data is not present

---

app/views/templates/invoice.slim

Prevent invoice template from raising error when billable metric is deleted
In invoice template we want to also use discarded billable metrics in order to present data. Currently in one place we query over billable metrics that are NOT deleted

fix(invoice): prevent invoice template from raising error when billable metric is deleted

---

app/controllers/api/v1/fees_controller.rb
app/queries/base_query.rb
app/queries/fees_query.rb
app/services/credit_notes/create_from_termination.rb
config/routes.rb
spec/factories/fees.rb
spec/queries/fees_query_spec.rb
spec/requests/api/v1/fees_spec.rb

This PR adds a new `GET /api/v1/fees` to retrieve fees. It accepts a lot of filter attributes

feat(instant_charge): Add GET /api/v1/fees route

---

app/serializers/v1/fee_serializer.rb
spec/serializers/v1/fee_serializer_spec.rb

We miss the fees boundaries on the invoice payload.
- Add `date_from` and `date_to` to fees when it applies

imp(fees): Add dates boundaries into serializer

---

app/mailers/password_reset_mailer.rb
app/views/password_reset_mailer/requested.slim

There were a misunderstanding in specs regarding the email template
We need to have 2 links
- One for the button, leading to the reset password flow
- One that redirect to forgot password flow, in order to renew your token  
This PR updated the wrong link usage and replace with the expected one

bug(password-reset): fix displayed links in email

---

app/models/billable_metric.rb
app/models/coupon.rb
app/models/coupon_target.rb
app/models/plan.rb
app/services/applied_coupons/create_service.rb
app/services/coupons/create_service.rb
app/services/coupons/destroy_service.rb
app/services/coupons/update_service.rb
app/services/credits/applied_coupons_service.rb
db/migrate/20230403094044_add_billable_metric_limitations_to_coupons.rb
db/schema.rb
spec/factories/coupon_plans.rb
spec/factories/coupon_targets.rb
spec/services/coupons/create_service_spec.rb
spec/services/coupons/update_service_spec.rb

In some cases coupons needs to be applied only on certain charges. In order to support it, billable metric limitations will be added.
Main points of this PR:
- Renaming of the join table `coupon_plans` => `coupon_targets`
- Adding billable metric relation to `coupon_targets`
- Fixing `coupon_plans` occurrences across the project

feat (coupons): Add setup for billable metric limitations

---

app/services/subscriptions/create_service.rb
spec/services/subscriptions/create_service_spec.rb

The goal of this PR is to not bill the subscription if pending.
Here is the following issue we want to fix in that PR:
- when a user is creating a subscription via API
- and plan is pay in advance
- with a subscription date in the future but today
- we don't want to enqueue a `BillSubscriptionJob`

fix: Do not bill subscription if not active

---

app/graphql/types/wallets/object.rb
app/models/wallet.rb
app/serializers/v1/legacy/wallet_serializer.rb
app/serializers/v1/wallet_serializer.rb
app/services/credits/applied_prepaid_credit_service.rb
app/services/wallet_transactions/create_service.rb
app/services/wallets/apply_paid_credits_service.rb
app/services/wallets/balance/decrease_service.rb
app/services/wallets/balance/increase_service.rb
db/migrate/20230403093407_add_balance_cents_to_wallets.rb
db/schema.rb
schema.graphql
schema.json
spec/factories/wallets.rb
spec/jobs/invoices/prepaid_credit_job_spec.rb
spec/models/wallet_spec.rb
spec/serializers/v1/wallet_serializer_spec.rb
spec/services/credits/applied_prepaid_credit_service_spec.rb
spec/services/wallet_transactions/create_service_spec.rb
spec/services/wallets/apply_paid_credits_service_spec.rb
spec/services/wallets/balance/decrease_service_spec.rb
spec/services/wallets/balance/increase_service_spec.rb

In our data model, amounts are usually integers in cents (e.g. `amount_cents` or `vat_amount_cents`).
However, in wallet, amount attributes are defined in float and exposed as string in the two API
This difference makes it difficult for users to use this information for calculation purposes (e.g. cannot easily deduct `amount_cents` from `balance` without converting the attribute into an integer).
This PR changes turned wallet fields into bigint and adds currency columns to match the amount and currency handling from other models.
- `balance_cents` / `balance_currency`
- `consumed_amount_cents` / `consumed_amount_currenty`
For compatibility purpose, all float fields are still exposed in public API but are deprecated.
This changes also requires an update of the front-end to adapt to the new …

feat: Turn balance float amounts into cents

---

db/migrate/20230403093407_add_balance_cents_to_wallets.rb

Validations are failing during wallet migration when customer is deleted. This PR ensures the validations passes even if the customer is soft deleted

hofix: Issue in wallet migration with deleted customers

---

app/models/charge.rb
config/locales/en.yml
db/migrate/20230411083336_add_min_amount_cents_to_charges.rb
db/schema.rb
spec/models/charge_spec.rb

The goal of this PR is to add `min_amount_cents` to `Charge`.

feat(min_charge): Add min_amount_cents to charges

---

app/services/credits/applied_coupons_service.rb
spec/services/credits/applied_coupons_service_spec.rb

In some cases coupons needs to be applied only on certain charges. In order to support it, billable metric limitations will be added.
This PR adds logic that apply coupons with BM limitations on invoice.
There is an order defined for applying coupons on invoice:
1. Coupons with BM limitations
2. Coupons with plan limitations
3. Coupons that apply to all fees

feat (coupons): Add logic that applies coupons with BM limitations on invoice

---

app/graphql/resolvers/billable_metrics_resolver.rb
app/queries/billable_metrics_query.rb
schema.graphql
schema.json
spec/queries/billable_metrics_query_spec.rb

We're refactoring the plan view on FE side.
It does required to have 2 inputs to search for billable metric. One in the "normal" charge section and one in the Instant charges section.
The instant charge section should only retrieve BM according to their `aggregation_type` value.
This PR updates the BM query to allow to filter by an array of `aggregation_type`

feat(billable_metric): allow to filter by aggregation_type

---

app/graphql/types/charges/input.rb
app/graphql/types/charges/object.rb
schema.graphql
schema.json

The goal of this PR is to add `min_amount_cents` into Charge for graphql.

feat(min_charge): Add min_amount_cents to Charge for graphql

---

app/services/fees/charge_service.rb
app/services/fees/create_true_up_service.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/create_true_up_service_spec.rb

The goal of this PR is to add a service for creating the true-up fee.

feat(min_charge): Add service to create the true-up fee

---

app/services/events/validate_creation_service.rb
spec/services/events/validate_creation_service_spec.rb

The event validation is failing if the property field is missing while the billable metric is expecting a property. 
This PR fixes this by handling the missing property field. The event will be ignored by the aggregation process, but will be flagged in the debugger as it will be if the aggregation property is not a valid numeric value.

fix(instant_charge): event properties might be nil

---

app/services/plans/update_service.rb

This PR ensure charge lookup when updating a plan is scoped to the plan, to prevent mixed update of charges.

fix(plan): Scope charge lookup to plan charges

---

app/models/invoice.rb
db/migrate/20230414074225_add_version_to_invoices.rb
db/schema.rb
spec/models/invoice_spec.rb
spec/services/credit_notes/create_service_spec.rb

Since already invoices created with the current implementation will still have to be generated or impacted by credit notes, we need a way to quickly identify which logic was applied when creating the invoice.
This PR turn the current `legacy` field of invoice into a `version_number`. It will default to 2 for now, and will be changed to 3 with the coming changes on coupons.
A next PR will remove the `legacy` and `legacy?` methods to use the versioning logic when applying credit notes and when generating PDFs

feat(coupon): Replace legacy with version_number on invoices

---

app/graphql/types/invoices/object.rb
app/models/invoice.rb
app/serializers/v1/invoice_serializer.rb
app/services/credits/credit_note_service.rb
app/views/templates/invoice.slim
db/migrate/20230417131515_add_credit_notes_amount_cents_to_invoices.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/resolvers/invoice_resolver_spec.rb
spec/models/invoice_spec.rb
spec/serializers/v1/invoice_serializer_spec.rb
spec/services/credits/credit_note_service_spec.rb

In order to make this change easier, we need to improve the way we store amounts and currency on invoice.
This PR adds a new `credit_notes_amount_cents` column to the `invoices` table. It will store the sum of credit notes credit amount.

feat(invoice): Add new credit_notes_amount_cents to invoice

---

app/graphql/types/invoices/object.rb
app/models/invoice.rb
app/serializers/v1/invoice_serializer.rb
app/services/credits/applied_coupons_service.rb
app/services/invoices/calculate_fees_service.rb
db/migrate/20230417122020_add_coupons_amount_cents_to_invoices.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/resolvers/invoice_resolver_spec.rb
spec/models/invoice_spec.rb
spec/serializers/v1/invoice_serializer_spec.rb
spec/services/credits/applied_coupons_service_spec.rb

In order to make this change easier, we need to improve the way we store amounts and currency on invoice.
This PR adds a new `coupons_amount_cents` column to the `invoices` table. It will store the sum of coupon credit amount.

feat(invoice): Add new coupons_amount_cents to invoice

---

app/graphql/types/invoices/object.rb
app/models/invoice.rb
app/serializers/v1/invoice_serializer.rb
app/services/credits/applied_prepaid_credit_service.rb
app/services/invoices/calculate_fees_service.rb
app/views/templates/invoice.slim
db/migrate/20230417140356_add_prepaid_credit_amount_cents_to_invoices.rb
db/schema.rb
lib/tasks/invoices.rake
schema.graphql
schema.json
spec/graphql/resolvers/invoice_resolver_spec.rb
spec/models/invoice_spec.rb
spec/serializers/v1/invoice_serializer_spec.rb
spec/services/credits/applied_prepaid_credit_service_spec.rb

In order to make this change easier, we need to improve the way we store amounts and currency on invoice.
This PR adds a new `prepaid_credit_amount_cents` column to the `invoices` table. It will store the sum of wallet transaction amount.

feat(invoice): Add new prepaid_credit_amount_cents to invoice

---

config/initializers/active_job_uniqueness.rb
db/schema.rb

An issue was raised in the community about a problem with Stripe payment job processing:
The job enqueuing was failing with a Redis Error:
```
Failed enqueuing Invoices::Payments::StripeCreateJob to Sidekiq(providers): Redis::CommandError (NOAUTH Authentication required.)
```
The `REDIS_PASSWORD` variable was correctly set and other jobs were enqueuing just fine.
After some investigation, it appears the issue is related to the `activejob-uniqueness` used in `Invoices::Payments::StripeCreateJob` and Invoices::Payments::GoCardlessCreateJob to prevent double processing of these jobs.
The fix is to ensure that the `REDIS_PASSWORD` is passed in the redis connection string when present.

fix(redis): activejob-uniqueness should take care of redis password

---

app/graphql/types/fees/object.rb
app/models/fee.rb
app/serializers/v1/fee_serializer.rb
db/migrate/20230419123538_add_true_up_fee_id_to_fees.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/resolvers/invoice_resolver_spec.rb
spec/serializers/v1/fee_serializer_spec.rb

The goal of this PR is to add `true_up_fee_id` on `Fee`.

feat(min_charge): add `true_up_fee_id` on `Fee`

---

app/graphql/types/invoices/object.rb
app/models/invoice.rb
app/serializers/v1/invoice_serializer.rb
app/serializers/v1/legacy/invoice_serializer.rb
app/services/credit_notes/create_service.rb
app/services/invoices/generate_pdf_service.rb
app/views/templates/invoices/v1.slim
app/views/templates/invoices/v2.slim
schema.graphql
schema.json
spec/serializers/v1/invoice_serializer_spec.rb
spec/services/invoices/generate_pdf_service_spec.rb
spec/services/invoices/subscription_service_spec.rb
spec/services/utils/pdf_generator_spec.rb

Since already invoices created with the current implementation will still have to be generated or impacted by credit notes, we need a way to quickly identify which logic was applied when creating the invoice.
This PR uses the new `invoice.version_number` field to render the right PDF template and exposes it into API and GraphQL schema

feat(coupon): expose invoice version & split PDF

---

app/models/charge.rb
app/models/fee.rb
app/views/templates/invoices/v2.slim
config/locales/de/invoice.yml
config/locales/en/invoice.yml
config/locales/fr/invoice.yml
config/locales/nb/invoice.yml

The goal of this PR is to update the invoice template to include true up fees.

feat(min_charge): Update invoice template to include true up fees

---

app/views/templates/invoices/v3.slim

This PR adds a new email template for future v3 invoices. The main change compared to `v2` is that coupons appears before the `sub_total_vat_included_amount_cents` item.

feat(coupon): Add invoice v3 template

---

app/serializers/v1/credit_serializer.rb
app/services/credits/applied_coupon_service.rb
app/services/credits/credit_note_service.rb
db/migrate/20230421094757_add_before_vat_to_credits.rb
db/schema.rb

This PR adds a new `before_vat` flag to the credit object. It will allow us to distinguish credit applied before vat (coupons) from the one applied after VAT (credit notes)

feat(coupons): Add before_vat flag to credits

---

app/graphql/types/credit_notes/object.rb
app/models/credit_note.rb
app/serializers/v1/credit_note_serializer.rb
app/serializers/v1/legacy/credit_note_serializer.rb
app/views/templates/credit_note.slim
config/locales/en/credit_note.yml
db/migrate/20230424091446_add_coupons_adjustment_amount_to_credit_notes.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/resolvers/credit_note_resolver_spec.rb
spec/serializers/v1/credit_note_serializer_spec.rb

This PR adds a new `coupons_adjustment_amount_cents` fields to the credit notes object. 
It will allow us to store the adjustment made on credited and refunded amount based on the applied coupons before VAT

feat(coupon): Add coupons adjustment amount to credit notes

---

app/services/billable_metrics/aggregations/recurring_count_service.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb

There is special case when period duration calculation hasn't been working for recurring BM: `calendar` subscription that is `pay_in_advance` and upgraded

fix(recurring-bm): fix period duration calculation

---

app/services/credit_notes/refresh_draft_service.rb
app/services/invoices/refresh_draft_service.rb
spec/services/credit_notes/refresh_draft_service_spec.rb

When finalizing a draft invoice including a credit note, the related credit note needs to be refreshed as well.
For instance, when the vat rate of the customer has changed, we need to recalculate the vat amounts of the credit note.

fix: Refresh draft credit note

---

app/models/credit_note.rb
app/models/invoice.rb
app/services/credit_notes/create_service.rb
app/services/credit_notes/validate_service.rb
db/migrate/20230424150952_drop_internal_credit_notes_vat_amounts.rb
db/migrate/20230424154516_add_precise_amounts_to_credit_notes.rb
db/schema.rb
spec/factories/credit_notes.rb
spec/models/invoice_spec.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/credit_notes/validate_service_spec.rb

This PR adds adapt the credit note creation logic to take credit note applied before VAT into account.

feat(coupon): Take coupons before VAT into account on credit notes

---

app/services/credits/applied_coupons_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/compute_amounts_from_fees.rb
app/views/templates/credit_note.slim
config/locales/de/credit_note.yml
config/locales/en/credit_note.yml
config/locales/fr/credit_note.yml
config/locales/nb/credit_note.yml
db/migrate/20230425130239_change_default_invoice_version.rb
db/schema.rb
spec/graphql/mutations/credit_notes/create_spec.rb
spec/graphql/resolvers/invoice_resolver_spec.rb
spec/models/credit_note_spec.rb
spec/models/invoice_spec.rb
spec/requests/api/v1/credit_notes_spec.rb
spec/serializers/v1/invoice_serializer_spec.rb
spec/services/credit_notes/create_from_termination_spec.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/credits/applied_coupons_service_spec.rb
spec/services/invoices/compute_amounts_from_fees_spec.rb
spec/services/invoices/subscription_service_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/subscriptions/terminate_service_spec.rb

This PR updates the coupon application logic on invoice to include the amount before VAT computation and to make sure the `before_vat` flag is set on the resulting `credit` record.
Invoice is also bumped to version 3

feat(coupons): Apply coupons before VAT and bump invoice to v3

---

app/models/organization.rb
app/models/tax_rate.rb
db/migrate/20230503143229_create_tax_rates.rb
db/schema.rb
spec/factories/tax_rates.rb
spec/models/tax_rate_spec.rb

👉  [https://getlago.canny.io/feature-requests/p/{{FEATURE_SLUG}}](https://getlago.canny.io/feature-requests/p/create-several-tax-rates)
The goal of this PR is to add the `TaxRate` model.

feat(tax_rates): Add TaxRate model

---

app/controllers/api/v1/tax_rates_controller.rb
app/models/organization.rb
app/models/tax_rate.rb
app/serializers/v1/tax_rate_serializer.rb
app/services/tax_rates/create_service.rb
app/services/tax_rates/destroy_service.rb
app/services/tax_rates/update_service.rb
config/routes.rb
db/migrate/20230503143229_create_tax_rates.rb
db/schema.rb
spec/factories/tax_rates.rb
spec/models/tax_rate_spec.rb
spec/requests/api/v1/tax_rates_spec.rb
spec/serializers/v1/tax_rate_serializer_spec.rb
spec/services/tax_rates/create_service_spec.rb
spec/services/tax_rates/destroy_service_spec.rb
spec/services/tax_rates/update_service_spec.rb

- fetch a tax rate
- list tax rates
- create a tax rate
- update a tax rate
- delete a tax rate

feat(tax_rates): Add tax rate resource

---

app/controllers/api/v1/subscriptions_controller.rb
app/queries/subscriptions_query.rb
spec/queries/subscriptions_query_spec.rb
spec/requests/api/v1/subscriptions_spec.rb

Today it is not possible to retrieve easily all subscription attached to a specific plan using the API
This PR add a `plan_code` filter to the `GET /api/v1/subscriptions` route.
It also refactors the query logic into a new `SubscriptionsQuery` service

feat(subscription): Allow plan filters on subscription index

---

app/serializers/v1/fee_serializer.rb
spec/serializers/v1/fee_serializer_spec.rb

`fee.instant_created` webhook is missing some details about customer, subscription and event attributes
This PR is adding  `lago_subscription_id`, `external_subscription_id`, `lago_customer_id`, `external_customer_id` and `event_transaction_id` to the fee serializer when `instant_charge` inclusion is passed

feat(instant_charge): Expose more details in fee.instant_created webhook

---

.rubocop.yml
app/graphql/resolvers/tax_rate_resolver.rb
app/graphql/resolvers/tax_rates_resolver.rb
app/graphql/types/query_type.rb
app/graphql/types/tax_rates/object.rb
app/queries/tax_rates_query.rb
schema.graphql
schema.json
spec/graphql/resolvers/tax_rate_resolver_spec.rb
spec/graphql/resolvers/tax_rates_resolver_spec.rb
spec/queries/tax_rates_query_spec.rb

- add the tax rate graphql resolver
- add the tax rates graphql resolver

feat(tax_rates): Add tax rate graphql resolvers

---

db/migrate/20230505093030_change_credits_id_type.rb
db/schema.rb

`Credits#id` type is currently integer, this is inconsistent considering all id columns have an `uuid` type 
This PR turns the id column into an uuid.
Since no other resource belongs to credits, it relatively safe to update

fix(credits): turn primary key column into uuid

---

app/serializers/v1/tax_rate_serializer.rb
app/services/tax_rates/destroy_service.rb
app/services/tax_rates/update_service.rb
spec/serializers/v1/tax_rate_serializer_spec.rb
spec/services/tax_rates/destroy_service_spec.rb
spec/services/tax_rates/update_service_spec.rb

- add customers_count on tax rate serializer
- refresh draft invoices when tax rate is updated or deleted

feat(tax_rates): Refresh draft invoices when tax rate is updated

---

app/services/credit_notes/compute_amount_service.rb
app/services/credit_notes/create_from_termination.rb
app/services/credit_notes/create_service.rb
spec/services/credit_notes/compute_amount_service_spec.rb
spec/services/credit_notes/create_from_termination_spec.rb

With recent changes regarding coupons, that are now applied before VAT rather than after, credit note creation was impacted at vat level and with the introduction of coupon_adjustment_amount_cents.
When terminating a payed in advance subscription, a credit note is created on the subscription fee, at pro-rata of the remaining days before the expected duration of subscription, but we forgot to take the coupon into account.
This PR introduce a new `CreditNotes::CompouteAmountService` to compute, the coupon adjustment, vat and creditable amount base on the amount to credit at fee level and the applied coupons

fix(subscription): Take coupons into account for credit note creation at subscription termination

---

spec/services/invites/validate_service_spec.rb

This TODO was written first before I wrote any tests here.
There is no reason to keep it.

misc(invites): remove TODO in code

---

app/models/customer.rb
app/models/customers_tax_rate.rb
app/models/organization.rb
app/models/tax_rate.rb
db/migrate/20230510113501_create_customers_tax_rates.rb
db/schema.rb
lib/tasks/tax_rates.rake
spec/factories/customers_tax_rates.rb
spec/factories/tax_rates.rb
spec/models/customers_tax_rate_spec.rb

- add `applied_by_default` boolean to `tax_rates` table
- create `customers_tax_rates` join table
- add task to migrate from `vat_rate` to `tax_rates`

feat(tax_rates): Migration from vat_rate to tax rates

---

app/controllers/api/v1/tax_rates_controller.rb
app/serializers/v1/tax_rate_serializer.rb
app/services/tax_rates/create_service.rb
app/services/tax_rates/update_service.rb
spec/requests/api/v1/tax_rates_spec.rb

The goal of this PR is to expose the `TaxRate#applied_by_default` attribute in API in order to turn it on/off for the organization

feat(tax_rate): Assign a tax rate to an organization via API

---

Gemfile
Gemfile.lock
app/controllers/admin/base_controller.rb
app/controllers/admin/organizations_controller.rb
app/controllers/api/base_controller.rb
app/controllers/concerns/api_errors.rb
app/services/admin/organizations/update_service.rb
config/environments/development.rb
config/initializers/cors.rb
config/routes.rb
lib/current_context.rb
spec/rails_helper.rb
spec/requests/admin/base_spec.rb
spec/requests/admin/organizations_spec.rb
spec/services/admin/organizations/update_service_spec.rb
spec/support/admin_helper.rb

- We want to use an admin tool to be able to do basic operations
- The first one to be covered is to be able to rename an organization
- Add the `/admin` api logic
- It uses the `googleauth` gem and it's based on a Google Oauth2
- Add the `PUT /admin/organizations/:id` endpoint and logic

Add admin organization update

---

app/controllers/api/v1/customers/applied_tax_rates_controller.rb
app/serializers/v1/applied_tax_rate_serializer.rb
app/services/applied_tax_rates/create_service.rb
app/services/applied_tax_rates/destroy_service.rb
config/routes.rb
spec/requests/api/v1/customers/applied_tax_rates_spec.rb
spec/serializers/v1/applied_tax_rate_serializer_spec.rb
spec/services/applied_tax_rates/create_service_spec.rb
spec/services/applied_tax_rates/destroy_service_spec.rb

- assign a tax rate to a customer via API
- unassign a tax rate to a customer via API

feat(tax_rates): Assign and unassign tax rate to a customer

---

app/services/subscriptions/dates/monthly_service.rb
app/services/subscriptions/dates_service.rb
spec/scenarios/billing_scenario_spec.rb
spec/services/subscriptions/dates/monthly_service_spec.rb

An issue have been identified with yearly plan billed in advance with charges billed monthly when the subscription starts on the last day of a month with 31 days.
If  the next month is shorter than the subscription one, the subscription fee is re-billed on the second month...
The fix is to ensure that in this situation when subscription was started on the last day of the month, we take the last day of current month as billing day.

hotfix: Fix monthly charges for yearly plan when subscription starts on last day of the month

---

app/controllers/admin/invoices_controller.rb
app/services/invoices/generate_pdf_service.rb
config/routes.rb
spec/requests/admin/invoices_spec.rb
spec/services/invoices/generate_pdf_service_spec.rb
spec/support/admin_helper.rb

We want to be able to regenerate an invoice PDF with the admin endpoints
- Add the `POST /admin/invoices/:id/regenerate` endpoint and logic

feat(admin): Add invoice regenerate endpoint

---

app/controllers/admin/memberships_controller.rb
app/models/membership.rb
app/serializers/v1/membership_serializer.rb
app/services/memberships/create_service.rb
config/routes.rb
db/migrate/20230522091400_add_unique_index_on_memberships.rb
db/schema.rb
lib/tasks/memberships.rake
spec/factories/memberships.rb
spec/requests/admin/memberships_spec.rb
spec/services/invites/accept_service_spec.rb
spec/services/memberships/create_service_spec.rb

We want to be able to add a membership for a defined organization and user by using our admin tool.
- Add the `POST /admin/memberships` route and logic
- Add a unique index on `memberships` table on `user_id` and `organization_id`

feat(admin): Add membership endpoint

---

app/serializers/v1/charge_usage_serializer.rb
app/serializers/v1/fee_serializer.rb
app/services/events/create_service.rb
app/services/fees/update_service.rb
app/services/invoices/calculate_fees_service.rb
spec/requests/api/v1/fees_spec.rb
spec/scenarios/pay_in_advance_charges_spec.rb
spec/serializers/v1/fee_serializer_spec.rb
spec/services/events/create_service_spec.rb
spec/services/fees/update_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb

This feature adds possibility to bill charges in advance
In this PR several small changes are added, in order to apply charge's invoiceable field on existing logic:
- fee update service can be applied only for `invoiceable = false`
- charge usage and fee serailizer are extended with `invoiceable`
- current 'instant charge' logic is applied only for `pay_in_advance = true` and `invoiceable = false`
- charge fees that are applied on subscription invoice are only caluclated for `pay_in_advance = false` and `invoiceable = true` -> `pay_in_advance = true` and `invoiceable = true` case will be handled later (as well as recurring case)

feat (charges): apply invoiceble field on existing logic

---

app/services/billable_metrics/aggregations/sum_service.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb

Pay in advance aggregation is failing with sum aggregation when the  event property is a floating point value.
The source of the issue is that we are relying on `BigDecimal` to handle the event property, but BigDecimal accepts only strings or integers as input values...
The fix is to convert the event value into a string before initializing the BigDecimal.

fix(aggregation): Fix sum aggregation when event property is a float

---

app/models/fee.rb
app/models/fees_tax.rb
app/models/tax.rb
db/migrate/20230525120005_create_fees_taxes.rb
db/schema.rb
spec/factories/fees_taxes.rb
spec/models/fees_tax_spec.rb

The goal of this PR is to add the `fees_taxes` table.
Column | Type | Attributes
-- | -- | --
id | uuid | not null
fee_id | uuid | not null
tax_id | uuid | not null
tax_code | string | not null
tax_name | string | not null
tax_description | string | null
tax_rate | float | not null
amount_cents | bigint | not null
amount_currency | string | not null
created_at | datetime | not null
updated_at | datetime | not null

feat(tax): Add fees_taxes resource

---

app/models/credit_notes_tax.rb
db/migrate/20230525154612_create_credit_notes_taxes.rb
db/schema.rb
spec/factories/credit_notes_taxes.rb
spec/models/credit_notes_tax_spec.rb

The goal of this PR is to add the `credit_notes_taxes` table.
Column | Type | Attributes
-- | -- | --
id | uuid | not null
credit_note_id | uuid | not null
tax_id | uuid | not null
tax_code | string | not null
tax_name | string | not null
tax_description | string | null
tax_rate | float | not null
amount_cents | bigint | not null
amount_currency | string | not null
created_at | datetime | not null
updated_at | datetime | not null

feat(tax): Add credit_notes_taxes resource

---

app/controllers/api/v1/applied_coupons_controller.rb
app/queries/applied_coupons_query.rb
spec/queries/applied_coupons_query_spec.rb
spec/requests/api/v1/applied_coupons_spec.rb

Fetching applied coupons via the API end-points is failing when the attached customer is deleted.
Applied coupons should not be returned when the customer is deleted.
This PR moved the coupon filtering into a query service and ensure that applied coupons are filtered when the attached customer is deleted.

fix(coupons): Ignore applied coupons for deleted customers

---

db/migrate/20221020093745_add_credit_amount_to_invoices.rb
lib/tasks/invoices.rake

Fixes https://github.com/getlago/lago/issues/238
An old migration task is failing on recent code base because it relies on models that are not aligned anymore with the migration logic.
Since the data migration itself was performed in a Job we have no way to ensure the state of the database schema and the models.
To fix the migration, the `invoices:fill_credit_amount` is removed and turned into a proper SQL migration

fix: Invoice credit amount migration

---

app/controllers/api/v1/credit_notes_controller.rb
app/controllers/api/v1/events_controller.rb
app/controllers/api/v1/fees_controller.rb
app/controllers/api/v1/invoices_controller.rb
app/models/credit_note.rb
app/models/tax.rb
app/serializers/v1/credit_note_serializer.rb
app/serializers/v1/fee_serializer.rb
app/serializers/v1/invoice_serializer.rb
app/services/webhooks/credit_notes/created_service.rb
app/services/webhooks/invoices/created_service.rb
app/services/webhooks/invoices/drafted_service.rb
app/services/webhooks/invoices/one_off_created_service.rb
app/services/webhooks/invoices/paid_credit_added_service.rb
spec/requests/api/v1/credit_notes_spec.rb
spec/requests/api/v1/fees_spec.rb
spec/requests/api/v1/invoices_spec.rb

- Present taxes on Invoice serializer
- Present taxes on Fee serializer
- Present taxes on CreditNote serializer

feat(tax): Present taxes on fees, invoices and credit notes serializers

---

app/models/tax.rb
app/services/fees/apply_taxes_service.rb
lib/tasks/taxes.rake
spec/services/fees/apply_taxes_service_spec.rb

The goal of this PR is to add a new `Fees::ApplyTaxesService` to apply customer or organizations taxes to a fee and creates the related `FeesTaxes` records

feat(tax): Add a service to apply taxes to a fee

---

db/migrate/20230202163249_add_organization_id_to_invoices.rb
lib/tasks/invoices.rake

Fixes https://github.com/getlago/lago/issues/238
An old migration task is failing on recent code base because it relies on models that are not aligned anymore with the migration logic.
To fix the migration, the `invoices:fill_organization` is removed and turned into a proper SQL migration

fix: Invoice organization_id migration

---

app/graphql/types/credit_notes/applied_taxes/object.rb
app/graphql/types/credit_notes/object.rb
app/graphql/types/fees/applied_taxes/object.rb
app/graphql/types/fees/object.rb
app/graphql/types/invoices/applied_taxes/object.rb
app/graphql/types/invoices/object.rb
app/graphql/types/taxes/applied_tax.rb
schema.graphql
schema.json
spec/graphql/resolvers/credit_note_resolver_spec.rb
spec/graphql/resolvers/invoice_resolver_spec.rb

The goal of this PR is to return applied taxes for fees, invoices and credit notes on graphql.

feat(tax): Return applied taxes via graphql

---

app/models/plan.rb
spec/models/plan_spec.rb

If we try to create an plan via the API without sending the `pay_in_advance` value, the request fails with an HTTP 500 error, because the value is not validated while the not null is enforced at database level.
This PR adds a validation rule on the plan model, to ensure that `pay_in_advance` is always set to `true` or `false`. The service will now returns a validation failure instead of a database error.

fix(plan): Validate pay_in_advance

---

app/services/events/create_service.rb

This PR will fix a `NotImplementedError` that is raised by the `SendWebhookJob`

fix(event): fix event webhook error

---

app/jobs/send_webhook_job.rb

When a subscription terminated, a credit note is created at pro-rata of the remaining days.
This credit note is created with the `CreditNotes::CreateFromTermination` service in a database creation.
This service relies itself on the `CreditNotes::CreateService` and is delivering a `credit_note.created` webhook.
As often, sidekiq is to quick to get the job and the webhook delivery failed with a ` ActiveJob::DeserializationError ` because the DB transaction is not yet committed. 
To fix the issue, we should retry the webhook delivery few times before raising the error.

fix(credit-note): retries webhook delivery as it could be sent inside a DB transaction

---

app/serializers/v1/applied_coupon_serializer.rb
spec/serializers/v1/applied_coupon_serializer_spec.rb

The `applied_coupon` object does not include `coupon_name`, so we need to use `coupon_code` and perform `GET /api/v1/coupons/:code` to retrieve the name of the applied coupon, which is not convenient.
This PR adds the `coupon_name` directly to the `applied_coupon_serializer`

feat(applied_coupon): expose coupon name in serializer

---

app/services/plans/create_service.rb

Plan creation via API is failing with an `HTTP 500` when no interval is provided in the input parameters when it should respond with an `HTTP 422`.
This PR uses the safe navigation operator to prevent error when trying to convert the provided value into a `symbol`. The service will automatically fail with a validation_error if no value is provided

fix(plan): Prevent error when creating a plan without interval

---

app/views/templates/credit_note.slim
app/views/templates/invoices/charge.slim
app/views/templates/invoices/one_off.slim
app/views/templates/invoices/v3.slim

👉  https://getlago.canny.io/feature-requests/p/display-legal-number-on-pdf-invoice
We want to display the customer and organization's legal number in PDF documents when relevant.
This PR adds the legal number displayed for both customer and organization in the:
- credit notes PDF
- charge invoice PDF
- subscription PDF
- one-off (addOn) invoice PDF

feat(invoices): display customer and orga legal_number

---

app/services/invoices/calculate_fees_service.rb
spec/services/invoices/calculate_fees_service_spec.rb

This PR ensures that the `Invoices::SubscriptionsService` is unable to create a diplicated invoice.
Duplicated invoice means:
- Recurring (created periodically by the billing service)
- Having the invoice subscription attached to the same subscription
- Having equal period boundaries (`from_datetime`, `to_datetime`)

feat(invoice): Prevent duplicated subscription invoice creation

---

app/jobs/credit_notes/refunds/adyen_create_job.rb
app/services/credit_notes/create_service.rb
app/services/credit_notes/refunds/adyen_service.rb
app/services/payment_providers/adyen_service.rb
spec/factories/refund_responses.rb
spec/fixtures/adyen/webhook_refund_response.json
spec/jobs/credit_notes/refunds/adyen_create_job_spec.rb
spec/services/credit_notes/refunds/adyen_service_spec.rb
spec/services/payment_providers/adyen_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/support-integration-with-adyen
Adyen provides payment apis for card and other payments.
Add Adyen as a payment provider supported natively

feat(adyen refunds): Add adyen refunds

---

app/services/invoices/calculate_fees_service.rb
app/services/invoices/create_pay_in_advance_charge_service.rb
db/migrate/20230602090325_add_boundaries_to_invoice_subscriptions.rb
db/schema.rb
lib/tasks/invoices.rake
spec/services/invoices/calculate_fees_service_spec.rb

- Unify `fees->timestamp` to be a required `timestamp`
- Create and set `timestamp` on `invoice_subscriptions`
- Create and set `from_datetime` on `invoice_subscriptions`
- Create and set `to_datetime` on `invoice_subscriptions`
- Create and set `charges_from_datetime` on `invoice_subscriptions`
- Create and set `charges_to_datetime` on `invoice_subscriptions`

Move boundaries from properties on invoice_subscriptions

---

app/jobs/invoices/payments/stripe_create_job.rb
app/services/invoices/payments/stripe_service.rb
spec/services/invoices/payments/stripe_service_spec.rb

Some payment creation attempt are failing on stripe due to misconfiguration or processing error (expired card, insufficient funds...).
Those errors are already sent to lago users via a specific `'invoice.payment_failure` webhook and the payment is marked as failed but in parallel, has we are still raising the error, they appear in the dead queue of sidekiq.
This PRs improve the Stripe error handling when trying to create a payment:
- `Stripe::CardError`, `Stripe::InvalidRequestError` and `Stripe::PermissionError` are sent back to the user via webhook but does not lead to a failed job.
- `Stripe::RateLimitError` are re-enqueued for new attempt

fix(stripe): Improve Stripe error handling on payment creation

---

app/controllers/api/v1/organizations_controller.rb
app/serializers/v1/legacy/organization_serializer.rb
app/serializers/v1/organization_serializer.rb
app/services/organizations/update_service.rb
spec/requests/api/v1/organizations_spec.rb
spec/serializers/v1/organization_serializer_spec.rb
spec/services/organizations/update_service_spec.rb

The goal of this PR is to ensure the PUT `/api/v1/organizations` route keeps handle legacy `vat_rate` attributes.

feat(tax_rate): Handle legacy vat_rate at organization level

---

app/services/fees/add_on_service.rb
app/services/fees/charge_service.rb
app/services/fees/create_pay_in_advance_service.rb
app/services/fees/create_true_up_service.rb
app/services/fees/one_off_service.rb
app/services/fees/paid_credit_service.rb
app/services/fees/subscription_service.rb
spec/graphql/mutations/invoices/create_spec.rb
spec/graphql/resolvers/customers/usage_resolver_spec.rb
spec/requests/api/v1/customers_spec.rb
spec/requests/api/v1/invoices_spec.rb
spec/scenarios/charge_models/percentage_spec.rb
spec/scenarios/invoices_spec.rb
spec/scenarios/spending_minimum_spec.rb
spec/scenarios/terminate_pay_in_advance_spec.rb
spec/services/fees/add_on_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb
spec/services/fees/create_true_up_service_spec.rb
spec/services/fees/one_off_service_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/invoices/add_on_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/customer_usage_service_spec.rb
spec/services/invoices/one_off_service_spec.rb
spec/services/invoices/subscription_service_spec.rb

The goal of this PR is to creates the `fees_taxes` when creating new fees using the applied customer taxes or the organization default one. It relies on the previously created `Fees::ApplyTaxesService`.
`NOTE:` the service is also temporary using the `applicable_vat_rate` as a fallback, until we switch to the new tax logic

feat(tax): Apply taxes to fees

---

app/serializers/v1/invoice_serializer.rb
app/services/invoices/add_on_service.rb
app/services/invoices/apply_taxes_service.rb
app/services/invoices/compute_amounts_from_fees.rb
app/services/invoices/customer_usage_service.rb
app/services/invoices/one_off_service.rb
app/services/invoices/paid_credit_service.rb
spec/services/invoices/add_on_service_spec.rb
spec/services/invoices/apply_taxes_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/compute_amounts_from_fees_spec.rb
spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
spec/services/invoices/one_off_service_spec.rb
spec/services/invoices/paid_credit_service_spec.rb
spec/services/invoices/refresh_draft_service_spec.rb
spec/services/invoices/subscription_service_spec.rb

The goal of this PR is to creates the `invoices#applied_taxes` when creating new invoice using the applied customer taxes or the organization default one. It relies on the previously created `Invoices::ApplyTaxesService`.

feat(tax): Apply taxes to invoices

---

app/jobs/payment_provider_customers/stripe_checkout_url_job.rb
app/services/payment_provider_customers/stripe_service.rb
spec/jobs/payment_provider_customers/stripe_checkout_url_job_spec.rb
spec/services/payment_provider_customers/stripe_service_spec.rb

This PR adds a new feature.
Once a new customer with Stripe as a payment provider is added to the app, via UI or API, we send a webhook with a checkout session url.
This checkout session will be used to store customer payment information on Stripe in order to ease future payments.
This URL is sent on the `customer.checkout_url_generated` webhook event.

feat(stripe) send webhook when user is created

---

app/services/invoices/calculate_fees_service.rb
spec/services/invoices/calculate_fees_service_spec.rb

A pre-condition was recently added to prevent the creation of duplicated invoices.
See https://github.com/getlago/lago-api/pull/1086
The fix introduced a regression because it was applied to every subscription billing cases (recurring, termination...) and not only to the recurring subscription billing
This PR fixes the precondition to ensure we are in a recurring case.

fix(invoice): Duplication validation should only be checked for recurring billing

---

app/services/payment_provider_customers/stripe_service.rb

Related to https://github.com/getlago/lago-api/pull/1107

fix(stripe): checkout URL should return empty result when no webhook URL

---

app/services/credit_notes/apply_taxes_service.rb
app/services/invoices/apply_taxes_service.rb
spec/services/credit_notes/apply_taxes_service_spec.rb

The goal of this PR is to add a new service `CreditNotes::ApplyTaxesService` to create `applied_taxes` for credit notes based on previously created `fees#applied_taxes` and `invoices#applied_taxes`

feat(tax): Add service to appliy taxes on credit notes

---

app/graphql/types/credit_notes/applied_taxes/object.rb
app/models/credit_note_item.rb
app/serializers/v1/credit_notes/applied_tax_serializer.rb
app/views/templates/credit_note.slim
config/locales/de/credit_note.yml
config/locales/en/credit_note.yml
config/locales/fr/credit_note.yml
config/locales/nb/credit_note.yml
schema.graphql
schema.json

The goal of this PR is to update the credit note PDF template to render the taxes

feat(tax): Display taxes on credit note PDF template

---

app/services/invoices/payments/gocardless_service.rb
spec/services/invoices/payments/gocardless_service_spec.rb

Update payment status didn't work properly if invoice has not been passed to constructor.

fix (gocardless): update invoice payment status for GCL

---

app/graphql/resolvers/billable_metrics_resolver.rb
app/queries/billable_metrics_query.rb
schema.graphql
schema.json
spec/queries/billable_metrics_query_spec.rb

In order to support UI experience for recurring billable metric, it has to be enabled to filter billable metrics by `recurring` field

feat (billable metrics): extend billable metric query service

---

app/models/event.rb
app/models/quantified_event.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/events/create_service.rb
app/services/events/validate_creation_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/quantified_events/create_or_update_service.rb
app/services/quantified_events/validate_creation_service.rb
db/migrate/20230615183805_add_event_refrence_to_quantified_events.rb
db/schema.rb
spec/factories/quantified_events.rb
spec/scenarios/pay_in_advance_charges_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/events/create_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/quantified_events/create_or_update_service_spec.rb
spec/services/quantified_events/validate_creation_service_spec.rb

As part of new charge pay in advance feature, unique count aggregation is refactored and computation of pay in advance event is changed
This PR covers few parts:
- aggregation for unique count BM has changed since currently we support operation types
- computation of pay in advance event has changed since we need to take into account maximum in current period in order to calculate fair price for the user

ftr (billable metrics): unique count aggregation refactoring

---

app/services/customers/applied_taxes/create_service.rb
app/services/customers/applied_taxes/destroy_service.rb
app/services/taxes/update_service.rb
spec/services/customers/applied_taxes/create_service_spec.rb
spec/services/customers/applied_taxes/destroy_service_spec.rb
spec/services/taxes/update_service_spec.rb

The goal of this PR is to correctly refresh draft invoices when a tax is updated or assigned to a customer.

feat(taxes): Refresh draft invoices on taxes update

---

db/migrate/20230626124005_migrate_organization_taxes.rb

We want to avoid displaying `Tax (20.0%) (20%)`, the goal of this PR is to not duplicate tax rate everywhere after the migration.

feat(taxes): Migrate taxes with Tax name

---

app/controllers/api/v1/plans_controller.rb
app/graphql/types/charges/input.rb
app/graphql/types/charges/object.rb
app/models/charge.rb
app/serializers/v1/charge_serializer.rb
app/services/plans/create_service.rb
app/services/plans/update_service.rb
config/locales/en.yml
db/migrate/20230627080605_add_prorated_to_charges.rb
db/schema.rb
schema.graphql
schema.json
spec/models/charge_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/update_service_spec.rb

As part of charges pay in advance feature it will be also possible to choose whether to prorate aggregation or not.
This feature adds support for `prorated` boolean field on charges

feat (charges): add support for prorated field

---

app/services/payment_providers/adyen_service.rb
spec/services/payment_providers/adyen_service_spec.rb

Raise NotFoundFailure when handling adyen webhook with an organization id that doesn't exist.

fix(adyen): Raise error when handling webhook with non-existent org

---

app/services/payment_providers/adyen_service.rb
spec/services/payment_providers/adyen_service_spec.rb

Change error to webhook_error when organization is not found.
The previous implementation raised NotFoundFailure which has different api: `error_code` instead of `code`.

fix(adyen): Change error to webhook_error when organization is not found

---

config/locales/fr/invoice.yml

fix: translations on plan interval for invoice template

---

db/migrate/20230704112230_fix_organizations_taxes.rb
db/schema.rb

An issue as been identified in the organization default tax rate migration.
See https://github.com/getlago/lago-api/blob/main/db/migrate/20230626124005_migrate_organization_taxes.rb#L25
The migration is creating the tax if it does exists with the `applied_to_organization`  set to true. But if it does find it, it does not mark the tax as applied to the organization.
This pull requests ensure the vat rate is applied by default to the organization

fix(tax): Organization default vat_rate migration

---

app/models/charge.rb
app/models/charge/applied_tax.rb
app/models/plan.rb
app/models/plan/applied_tax.rb
app/models/tax.rb
db/migrate/20230704144027_create_plans_taxes.rb
db/migrate/20230704150108_create_charges_taxes.rb
db/schema.rb
spec/factories/charge_applied_taxes.rb
spec/factories/plan_applied_taxes.rb

This PR add two new tables and the related models:
- `plans_taxes`, `Plan::AppliedTax`
- `charges_taxes`, `Charge::AppliedTax`

feat(tax): Add Plan::AppliedTax and Charge::AppliedTax models

---

app/controllers/api/v1/plans_controller.rb
app/serializers/v1/charge_serializer.rb
app/serializers/v1/plan_serializer.rb
spec/serializers/v1/charge_serializer_spec.rb
spec/serializers/v1/plan_serializer_spec.rb

This PR exposes the taxes in the public API for plans and charges objects

feat(tax): Expose plan and charge taxes in the API

---

app/services/events/create_service.rb
app/services/events/validate_creation_service.rb
app/services/fees/estimate_pay_in_advance_service.rb
spec/factories/subscriptions.rb
spec/requests/api/v1/events_spec.rb
spec/scenarios/create_event_spec.rb
spec/services/events/create_service_spec.rb
spec/services/events/validate_creation_service_spec.rb
spec/services/fees/estimate_pay_in_advance_service_spec.rb
spec/support/scenarios_helper.rb

- add the ability to create an event on a terminated subscription by passing `external_customer_id`
- add scenarios for validating event creation

fix: Improve validations when creating an event

---

app/controllers/api/v1/events_controller.rb
app/services/events/create_service.rb
spec/scenarios/create_event_spec.rb

We are using `Time.current.to_i` for the timestamp when creating an event. It does not incllude milliseconds.
When creating a subscription in the same time, sometimes we can have errors on events.
The goal of this PR is to fix this issue.

fix: Ability to start the subscription and create an event in the same time

---

app/controllers/api/v1/plans/applied_taxes_controller.rb
app/controllers/api/v1/plans_controller.rb
app/models/plan.rb
app/serializers/v1/plans/applied_tax_serializer.rb
app/services/plans/applied_taxes/create_service.rb
app/services/plans/applied_taxes/destroy_service.rb
config/routes.rb
spec/requests/api/v1/plans/applied_taxes_spec.rb
spec/services/plans/applied_taxes/create_service_spec.rb
spec/services/plans/applied_taxes/destroy_service_spec.rb

This PR permits to assign and unassign taxes to a specific plan.

feat(taxes): Ability to assign and unassign taxes to a plan

---

app/controllers/api/v1/subscriptions_controller.rb
app/graphql/types/subscriptions/object.rb
app/queries/subscriptions_query.rb
app/services/subscriptions/terminate_service.rb
schema.graphql
schema.json
spec/queries/subscriptions_query_spec.rb
spec/services/subscriptions/terminate_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/retrieve-andor-cancel-pending-subscriptions
We want to allow canceling a pending subscription, either because they are planned in the future alone or due to a downgrade
This PR allows such action
Better review commit-by-commit

feat: cancel pending subscription

---

app/controllers/api/v1/plans_controller.rb
app/services/charges/apply_taxes_service.rb
app/services/plans/create_service.rb
spec/requests/api/v1/plans_spec.rb
spec/services/charges/apply_taxes_service_spec.rb

The goal of this PR is to be able to assign taxes on the creation of a charge.

feat(taxes): Assign tax to a charge

---

app/graphql/types/taxes/object.rb
app/serializers/v1/tax_serializer.rb
schema.graphql
schema.json
spec/graphql/mutations/taxes/create_spec.rb
spec/serializers/v1/tax_serializer_spec.rb

This PR adds `plans_count` and `charges_count` in both API and GraphQL

feat(tax): Expose plans_count and charges_count for taxes in API

---

app/controllers/api/base_controller.rb
app/controllers/concerns/api_errors.rb
spec/requests/api/base_spec.rb

When a request is missing an expected argument, Rails is raising an `ActionController::ParameterMissing`.
Today this error is not captured leads to an HTTP 500 error from the application
This PR makes sure that the error is catched and renders a proper HTTP 400 error.

fix: Handle ActionController::ParameterMissing error

---

app/services/subscriptions/dates_service.rb
spec/services/subscriptions/dates_service_spec.rb

The goal of this PR is to fix an issue on the `to_datetime` boundaries when terminating a subscription created in the past, and then refreshing the corresponding draft invoice.
Previously, the boundaries were calculated for the full period instead of using the terminated_at.

fix: To datetime boundary on invoice refresh

---

app/models/invoice.rb
app/serializers/v1/credit_serializer.rb
app/serializers/v1/legacy/credit_serializer.rb
app/services/credits/applied_coupon_service.rb
app/services/credits/credit_note_service.rb
db/migrate/20230713122526_rename_credit_before_vat.rb
db/schema.rb
spec/serializers/v1/credit_serializer_spec.rb
spec/services/credits/applied_coupon_service_spec.rb
spec/services/credits/credit_note_service_spec.rb

This PR renames `Credit#before_vat` into `Credit#before_taxes` to allign with the lastest changes regarding taxes

feat(tax): Rename credit#before_vat into credit#before_taxes

---

app/models/invoice/applied_tax.rb
db/migrate/20230717090135_add_precise_coupons_amount_cents_to_fees.rb
db/schema.rb

This PR adds two new fields to the database:
- `fees#precise_coupons_amount_cents` to store the pro-rata of coupons applied to a fee
- `invoices_taxes#fees_amount_cents` to store the fees amount related to a specific tax rate at invoice level

feat(tax): Add fields for coupons pro-rata

---

app/services/fees/apply_taxes_service.rb
spec/services/fees/apply_taxes_service_spec.rb

This PR uses Plan and Charge applied taxes in the `Fees::ApplyTaxesService`
NOTE: A proper test scenario should be added as well

feat(tax): Apply taxes to fees with charge or plan taxes

---

app/queries/subscriptions_query.rb
spec/queries/subscriptions_query_spec.rb

We introduced a breaking change in the last release
`GET /subscription` was now returning all subscriptions no matter their `status`. But this endpoint is used to return only `active` ones.
This PR does fix that by 
1. returning only `active` subscription by default
2. keep allowing users to filter subscriptions by `status` and get the list is they want

fix(subscriptions) return active subscriptions by default

---

app/graphql/types/invoices/applied_taxes/object.rb
app/serializers/v1/invoices/applied_tax_serializer.rb
schema.graphql
schema.json
spec/serializers/v1/invoices/applied_tax_serializer_spec.rb

This PR exposes `invoices_taxes#fees_amount_cents` in both GraphQL and public API

feat(tax): Expose invoices_taxes#fees_amount_cents in API

---

app/models/invoice.rb
app/services/billable_metrics/breakdown/sum_service.rb
app/services/billable_metrics/breakdown/unique_count_service.rb
app/services/billable_metrics/prorated_aggregations/sum_service.rb
app/services/billable_metrics/prorated_aggregations/unique_count_service.rb
app/views/templates/invoices/_subscription_details.slim
app/views/templates/invoices/charge.slim
app/views/templates/invoices/v3.slim
config/locales/de/invoice.yml
config/locales/en/invoice.yml
config/locales/fr/invoice.yml
config/locales/nb/invoice.yml
spec/models/invoice_spec.rb
spec/services/billable_metrics/breakdown/sum_service_spec.rb
spec/services/billable_metrics/breakdown/unique_count_service_spec.rb

This PR adds new invoice template changes for recurring billable metrics.
This PR adds new invoice template changes for recurring billable metrics.
Most significant change is around breakdown section for charges that are paid in arrears.
Also for pay in advance invoice that is prorated we display now number of days when the service has been used

feat (invoice): New invoice template changes for recurring case

---

app/models/subscription.rb
app/services/fees/subscription_service.rb
spec/models/subscription_spec.rb
spec/scenarios/invoices_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb

Fix billing boundaries for termination case if there is customer timezone
If customer timezone is set, in case of termination wrong number of days was calculated and therefore proration coefficient was incorrect

fix (subscription): fix billing boundaries for termination case

---

db/migrate/20230720081854_populate_fees_precise_coupons_amount_cents.rb
db/migrate/20230720120622_populate_fees_amount_cents_in_invoice_taxes.rb
db/schema.rb

This PR adds a migration to populate added in a previous PR: https://github.com/getlago/lago-api/pull/1178

feat(tax): Populate missing pro-rated coupon taxes amounts

---

db/migrate/20230721073114_fix_credit_before_taxes.rb
db/schema.rb

---
I create an invoice link to a subscription like this
```
Subscription fee        $100.00
-------------------------------
Coupon                  -$10.00
Substotal (excl. tax)    $90.00  
Tax (10%)                $ 9.00
Subtotal (incl. tax)     $99.00
-------------------------------
Prepaid credits         -$ 5.00
-------------------------------
Total due                $94.00
```
When I’m creating a credit note through the UI, it tells me that the maximum refundable amount is $84.00.
When I’m creating a credit note through the API, it tells me that the maximum refundable amount is $94.00
---
When I’m creating a credit note through the UI, the maximum refundable amount should be $94.00.
The issue is related to a bug with the `credits.before_taxes` flag. It was introduced to quickly …

fix(credit): Migrate v3 credits with wrong before taxes flag

---

app/services/billable_metrics/create_service.rb
app/services/billable_metrics/update_service.rb
spec/services/billable_metrics/create_service_spec.rb
spec/services/billable_metrics/update_service_spec.rb

We don't accept from now on `recurring_count_agg` aggregation type. It is migrated to `count_unique` type with `recurring` = `true` and `prorated` = `true` (on related charge). In the future (after new feature gets released completely) we will remove this type completely from the codebase.
Block `recurring_count_agg` aggregation type on the API side.

fix (billable-metrics): temporary block recurring_count_agg aggregation type

---

app/graphql/types/payment_provider_customers/provider_input.rb
schema.graphql
schema.json

This attributes can be null, so it's type must not be required

bug(customer) makes the provider_payment_methods not required

---

app/models/fee.rb
app/services/credit_notes/apply_taxes_service.rb
app/services/credits/applied_coupon_service.rb
app/services/credits/applied_coupons_service.rb
app/services/fees/apply_taxes_service.rb
app/services/fees/charge_service.rb
app/services/fees/create_pay_in_advance_service.rb
app/services/fees/create_true_up_service.rb
app/services/fees/one_off_service.rb
app/services/fees/subscription_service.rb
app/services/invoices/apply_taxes_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/compute_amounts_from_fees.rb
app/services/invoices/customer_usage_service.rb
app/services/plans/update_service.rb
spec/scenarios/taxes_on_invoice_spec.rb
spec/services/credit_notes/apply_taxes_service_spec.rb
spec/services/credit_notes/create_from_termination_spec.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/credit_notes/refresh_draft_service_spec.rb
spec/services/credits/applied_coupon_service_spec.rb
spec/services/fees/apply_taxes_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb
spec/services/fees/create_true_up_service_spec.rb
spec/services/fees/one_off_service_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/invoices/apply_taxes_service_spec.rb
spec/services/invoices/compute_amounts_from_fees_spec.rb
spec/support/scenarios_helper.rb

This PR adds the logic to compute coupons pro-rata and apply it to fees while computing taxes

feat(tax): coupons pro-rata for fees

---

app/models/add_on.rb
app/models/add_on/applied_tax.rb
db/migrate/20230727163611_create_add_ons_taxes.rb
db/schema.rb
spec/factories/add_on_applied_taxes.rb

This PR adds the `AddOn::AppliedTax` resource.

feat(tax): Add AddOn::AppliedTax

---

app/graphql/types/invoices/object.rb
app/models/customer.rb
app/models/organization.rb
app/serializers/v1/invoice_serializer.rb
app/services/customers/update_invoice_grace_period_service.rb
app/services/invoices/add_on_service.rb
app/services/invoices/create_pay_in_advance_charge_service.rb
app/services/invoices/finalize_service.rb
app/services/invoices/one_off_service.rb
app/services/invoices/paid_credit_service.rb
app/services/invoices/subscription_service.rb
app/services/organizations/update_invoice_grace_period_service.rb
app/views/templates/invoices/charge.slim
app/views/templates/invoices/one_off.slim
app/views/templates/invoices/v3.slim
db/migrate/20230726165711_add_net_payment_term_on_organization_and_customer.rb
db/migrate/20230726171737_add_payment_due_date_to_invoice.rb
db/schema.rb
schema.graphql
schema.json
spec/factories/invoices.rb
spec/serializers/v1/invoice_serializer_spec.rb
spec/services/customers/update_invoice_grace_period_service_spec.rb
spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
spec/services/invoices/finalize_service_spec.rb
spec/services/organizations/update_invoice_grace_period_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/define-invoice-due-date
We want to allow defining a payment due date that is different than the invoice issuing date
This is a non breaking PR. it basically "just" add attributes and logic between them. But the "heart" of the feature (updating the due date) is not done yet
----------
This PR adds a payment_due_date attribute on invoices and display it on templates
It' based on the issuing datre for now
Also, customer and orga has their new net_payment_term attribute added.
Updating this attribute will be possible in following PRs

feat: add payment_due_date and display on invoices

---

app/controllers/api/v1/add_ons_controller.rb
app/serializers/v1/add_on_serializer.rb
app/services/add_ons/apply_taxes_service.rb
app/services/add_ons/create_service.rb
spec/requests/api/v1/add_ons_spec.rb
spec/services/add_ons/apply_taxes_service_spec.rb
spec/services/add_ons/create_service_spec.rb

This PR adds the ability to assign taxes on add on creation.

feat(tax): Assign taxes on add on creation

---

app/services/invoices/calculate_fees_service.rb
db/migrate/20230731095510_remove_index_from_invoice_subscriptions.rb
db/schema.rb
spec/services/invoices/calculate_fees_service_spec.rb

If plan interval is `yearly` and `bill_charges_monthly` is `true` we do not want to raise `duplicated_invoice` error since on multiple invoices we can have the same `from_datetime` and `to_datetime` values but different `charges_from_datetime` and `charges_to_datetime`

fix (subscriptions): do not raise duplicated_invoice error for yearly plan case

---

app/serializers/v1/invoice_serializer.rb
app/services/invoices/add_on_service.rb
app/services/invoices/create_pay_in_advance_charge_service.rb
app/services/invoices/one_off_service.rb
app/services/invoices/paid_credit_service.rb
app/services/invoices/subscription_service.rb
app/views/templates/invoices/charge.slim
app/views/templates/invoices/one_off.slim
app/views/templates/invoices/v3.slim
config/locales/de/invoice.yml
config/locales/en/invoice.yml
config/locales/fr/invoice.yml
config/locales/nb/invoice.yml
db/migrate/20230731135721_add_net_payment_term_to_invoice.rb
db/schema.rb
spec/serializers/v1/invoice_serializer_spec.rb

👉  https://getlago.canny.io/feature-requests/p/define-invoice-due-date
We want to allow defining a payment due date that is different than the invoice issuing date
This PR does
- add the net_payment_term on the invoice
- make the payment_due_date dynamic on prepaid credits invoices (was forgotten in previous PR)

feat(invoice) display net payment term

---

app/services/users_service.rb
db/schema.rb
spec/services/users_service_spec.rb

https://github.com/getlago/lago/issues/220
- Do not permit register (signup) when its disabled with `LAGO_SIGNUP_DISABLED` env var is set to `true`

fix(register): Do not permit signup when disabled

---

app/services/invoices/calculate_fees_service.rb
spec/services/invoices/calculate_fees_service_spec.rb

When billable metric is recurring and charge is pay in advance, we do not want to bill such charges upon subscription termination

fix (charges): do not bill recurring pay in advance charges upon termination

---

app/graphql/types/taxes/object.rb
app/models/tax.rb
app/serializers/v1/tax_serializer.rb
schema.graphql
schema.json
spec/graphql/mutations/taxes/create_spec.rb
spec/serializers/v1/tax_serializer_spec.rb

This PR adds the ability to return the number of add ons impacted by a tax.

feat(tax): Add add_ons_count to tax

---

app/services/credits/applied_coupon_service.rb
app/services/invoices/calculate_fees_service.rb
spec/scenarios/taxes_on_invoice_spec.rb

Invoice `sub_total_excluding_taxes_amount_cents` was not correctly calculated and because of that coupon base amount was wrong (applied coupons amount was higher than invoice fees). Applying coupons with limitations are not affected here since we have validation that prevents applying coupons with same limitations on the given invoice

fix(coupons): fix coupon base amount for multiple subscriptions

---

app/models/charge.rb

Some invoice mailer failed to execute because they were related to deleted plans, leading to a `NoMethodError: undefined method amount_currency for nil:NilClass`
This PR ensures that the plan `amount_currency` is accessible in `monetize :min_amount_cents` at charge level even if the related plan is soft deleted

fix(invoice): Ensure mailer can be sent for deleted charges/plans

---

app/services/webhooks/base_service.rb

Some webhooks are failing to deliver with an `EOFError` error.
This error appears when the webhook clients tries to read in a network socket that has been closed by the server.
Has the only possible way to handle this kind of error is to retry to send the webhook, this PR adds the `EOFError` to the list of rescued and retried errors.

fix(webhook): Handle auto retry with EOFError

---

app/graphql/mutations/add_ons/create.rb
app/graphql/mutations/add_ons/update.rb
app/graphql/types/add_ons/create_input.rb
app/graphql/types/add_ons/object.rb
app/graphql/types/add_ons/update_input.rb
schema.graphql
schema.json
spec/graphql/mutations/add_ons/create_spec.rb
spec/graphql/mutations/add_ons/update_spec.rb

This PR adds the ability to send `taxCodes` as a parameter of add-on resource, and returns `taxes`.

feat(tax): Add taxes to graphql add_ons create/update

---

app/services/fees/apply_taxes_service.rb
spec/requests/api/v1/invoices_spec.rb
spec/services/fees/apply_taxes_service_spec.rb

This PR permits to apply taxes from add-on.

feat(tax): Apply taxes to add on fees

---

app/views/templates/invoices/charge.slim
app/views/templates/invoices/one_off.slim
app/views/templates/invoices/v3.slim

Since the merge of https://github.com/getlago/lago-api/pull/1193, it is not possible to generate the PDF for invoice created before the release.
The reason behind this is that the template now rely on the `payment_due_date` field but this field was not filled for existing invoice
The fix for now is to rollback to the previous state on invoice template using `issuing_date` field

fix(invoice): revert changes for payment_due_date on templates

---

app/services/subscriptions/dates/yearly_service.rb
spec/scenarios/customer_usage_spec.rb

The `to_datetime` boundary for customer current usage is wrong if the plan is yearly payed in advance and calendar and if the customer have a timezone.
The underlying issue is that the `charges_from_datetime` computation in the yearly date service is using the `from_datetime` method which already takes the customer timezone into account, leading to a wrong result when the timezone is before UTC (example: 'Europe/Berlin').
The fix is to rely on `compute_from_date` to get the from date before the timezone shift. The next steps of the service are already handling the shift to the customer timezone and started_at/terminated_at

fix(subscription): Charge to date boundaries for yearly plan

---

app/services/invoices/calculate_fees_service.rb
spec/scenarios/invoices_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb

**Cases when we don’t want to bill the charges (i.e. don’t include them in subscription invoice):**
1. pay_in_advance = true AND recurring = false
2. pay_in_advance = true AND recurring = true AND subscription IS terminated (upgrade / old subscription)
3. pay_in_advance = true AND recurring = true AND subscription IS terminated (regular termination)
4. pay_in_advance = false AND prorated = false AND recurring = true AND subscription IS terminated (upgrade / old subscription)
**IN THIS CASE WE WANT TO BILL → BUG**
1. pay_in_advance = false AND prorated = false AND recurring = true AND subscription IS terminated (regular termination) → BILL THIS ONE ⚠️

fix (charges): fix condition that determines when to bill charges

---

db/migrate/20221021135946_fill_properties_on_persisted_events.rb
lib/tasks/events.rake

`PersistedEvent` model does not exist anymore. In order to perform migration correctly, we increased delay time for background job in order to renaming migration can finish before. Also, we are are using renamed model inside the task - `QuantifiedEvent`

fix (migration): fix failing migration

---

app/models/charge.rb
app/services/charges/validators/graduated_percentage_service.rb
app/services/charges/validators/graduated_service.rb
app/services/charges/validators/volume_service.rb
app/services/validators/decimal_amount_service.rb
app/services/validators/range_bounds_validator.rb
schema.graphql
schema.json
spec/factories/charges.rb
spec/models/charge_spec.rb
spec/services/charges/validators/graduated_percentage_service_spec.rb

The objective of this feature is to introduce a new graduated percentage charge model similar to the current graduated charge model but applying a rate to the units rather than an amount.
This PR adds:
- The `graduated_percentage` value in `Charge#CHARGE_MODELS` enum as well as in the GraphQL `ChargeModelEnum`
- The charge model validation logic

feat(charge): Add graduated percentage charge model validation

---

app/services/invoices/payments/stripe_service.rb
app/services/payment_providers/stripe_service.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/payment_providers/stripe_service_spec.rb

Same as https://github.com/getlago/lago-api/pull/1231 for Stripe payments
A lot of dead jobs are related to missing Stripe payments when receiving `payment_intent.payment_failed`, `payment_intent.succeeded` webhooks from Stripe.
One of the reasons for this kind of error is that the same Stripe Secret key could be shared between organizations. As a consequence, we could receive `customner.update` webhooks for customer attached to another organization, leading to `stripe_payment_not_found` error when the invoice is found in database.
The fix is to scope the invoice lookup in the `handle_missing_invoice` guard to the organization receiving the hook.

fix(stripe): Add new filter for missing stripe payment webhooks

---

app/models/charge.rb
app/services/plans/create_service.rb
app/services/plans/update_service.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/update_service_spec.rb

The objective of this feature is to introduce a new graduated percentage charge model similar to the current graduated charge model but applying a rate to the units rather than an amount.
This PR allow the creation of graduated percentage charge as a premium feature

feat(charge): Allow creation of graduated percentage charges

---

app/services/fees/create_true_up_service.rb
spec/scenarios/spending_minimum_spec.rb
spec/services/fees/create_true_up_service_spec.rb

The goal of this PR is to fix the billing calculation for a true-up fee when customer has a timezone.

fix(timezone): Correct calculation for true-up fee with timezone

---

app/models/subscription.rb
config/locales/en.yml

While fixing an error on FE side, I noticed and error code was containing a typo. We usually send them without `s`
This PR fixes the error code to be as all others similar in the app

bug(error) fix typo in error name

---

app/graphql/types/charges/graduated_percentage_range.rb
app/graphql/types/charges/graduated_percentage_range_input.rb
app/graphql/types/charges/properties.rb
app/graphql/types/charges/properties_input.rb
schema.graphql
schema.json
spec/graphql/mutations/plans/create_spec.rb

The objective of this feature is to introduce a new graduated percentage charge model similar to the current graduated charge model but applying a rate to the units rather than an amount.
This PR adds the GraphQL types definition to create and update graduated percentage charge models.

feat(charge): GrapgQL types for graduated percentage

---

app/services/subscriptions/dates/quarterly_service.rb
spec/services/subscriptions/dates/quarterly_service_spec.rb

Quarterly anniversary with subscription date in the past does not have the right boundaries on current usage
The PR adds a test case on the current month to check that it is a billing month, otherwise, if returns the previous billing month.

fix: Quarterly anniversary current usage should take care of the month

---

db/migrate/20230811081854_populate_fees_precise_coupons_amount_cents.rb

We have an issue with a migration related to coupons on fees objects
The PR fixes the migration

fix: fees coupon amount migration

---

app/models/charge.rb
app/services/charges/build_default_properties_service.rb
app/services/fees/charge_service.rb
app/services/plans/create_service.rb
app/services/plans/update_service.rb
config/locales/en.yml
spec/models/charge_spec.rb
spec/services/charges/build_default_properties_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/update_service_spec.rb

👉 https://getlago.canny.io/feature-requests/p/edit-groups-associated-with-billable-metrics
We want to be able to set a default price on charges with groups.
The goal of this PR is to use the default properties when creating fees for undefined groups.

feat(group): Use default properties when creating fees for groups

---

app/models/group_property.rb
db/migrate/20230821135235_add_unique_constraint_to_group_properties.rb
db/schema.rb

The goal of this PR is to ensure having only one pair `charge_id` / `group_id` on `group_properties`.
I haven't seen any duplications on cloud production, so I decided to not add the logic for cleaning duplicates on the migration for OSS.
`GroupProperty.select(:id, :group_id, :charge_id).group(:group_id, :charge_id).having("count(*) > 1") => 0`

feat(group): Add unique index on group_properties

---

app/graphql/types/charges/properties.rb
app/graphql/types/charges/properties_input.rb
schema.graphql
schema.json
spec/graphql/mutations/plans/create_spec.rb

👉  https://getlago.canny.io/feature-requests/p/apply-price-floorcap-on-transactions
Fintech users want to be able to cap a transaction to a maximum amount or to flour it to a minimum amount.
This feature will apply this logic to the `percentage` charge model.
This PR exposes the `per_transaction_max_amount`/`per_transaction_min_amount` for charge model properties in GraphQL api

feat(charge): Add per transaction min/max amounts to GraphQL percentage charge model fields

---

app/models/invoice.rb
app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/billable_metrics/breakdown/sum_service.rb
app/services/billable_metrics/breakdown/unique_count_service.rb
app/services/billable_metrics/prorated_aggregations/base_service.rb
app/services/billable_metrics/prorated_aggregations/sum_service.rb
app/services/billable_metrics/prorated_aggregations/unique_count_service.rb
app/services/charges/pay_in_advance_aggregation_service.rb
app/services/fees/charge_service.rb
spec/services/billable_metrics/aggregations/count_service_spec.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/billable_metrics/breakdown/sum_service_spec.rb
spec/services/billable_metrics/breakdown/unique_count_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
spec/services/charges/pay_in_advance_aggregation_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/apply-price-floorcap-on-transactions
Fintech users want to be able to cap a transaction to a maximum amount or to flour it to a minimum amount.
This feature will apply this logic to the `percentage` charge model.
In order to ease the logic for the min/max per transaction amount on the `percentage` charge model, this PR is refactoring the billable metric aggregator services. It moves the boundaries from the aggregate method calls to the service initializer, to make it easier to call other method on the service if required.

feat(billable metric): Refact aggregator initializers

---

app/services/charges/validators/percentage_service.rb
spec/services/charges/validators/percentage_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/apply-price-floorcap-on-transactions
Fintech users want to be able to cap a transaction to a maximum amount or to flour it to a minimum amount.
This feature will apply this logic to the `percentage` charge model.
This PR is the first for this feature. It adds the validation rules for the `per_transaction_min_amount` and `per_transaction_max_amount` fields on the `percentage` charge model.
The validation is performed only if the application is premium

feat(charge): Add validation for min/max per transaction amount on percentage charge model

---

app/jobs/send_webhook_job.rb
app/serializers/v1/subscription_serializer.rb
app/services/subscriptions/activate_service.rb
app/services/subscriptions/create_service.rb
app/services/webhooks/subscriptions/started_service.rb
app/services/webhooks/subscriptions/terminated_service.rb
spec/jobs/send_webhook_job_spec.rb
spec/serializers/v1/subscription_serializer_spec.rb
spec/services/subscriptions/activate_service_spec.rb
spec/services/webhooks/subscriptions/started_service_spec.rb
spec/services/webhooks/subscriptions/terminated_service_spec.rb

👉 https://getlago.canny.io/feature-requests/p/receive-a-webhook-when-a-subscription-starts-subscriptionstarted
- Add the `subscription.started` webhook

feat(webhooks): Add subscription.started webhook

---

app/services/invoices/calculate_fees_service.rb
spec/scenarios/invoices_spec.rb

This PR fix condition when to bill charges.
For recurring pay in arrear charges (non-prorated) we want to skip billing charges upon upgrade. However, this should happen only if upgraded plan contains charge with the same billable metric

fix (invoices): update condition when to bill charges

---

app/controllers/api/v1/billable_metrics/groups_controller.rb
app/graphql/types/charges/object.rb
app/models/billable_metric.rb
app/models/charge.rb
app/models/group_property.rb
app/serializers/v1/charge_usage_serializer.rb
app/services/charges/build_default_properties_service.rb
app/services/fees/charge_service.rb
app/services/invoices/customer_usage_service.rb
app/services/plans/create_service.rb
app/services/plans/update_service.rb
config/locales/en.yml
config/locales/en/charge.yml
db/migrate/20230817092555_set_default_properties_to_charges.rb
db/migrate/20230821135235_add_unique_constraint_to_group_properties.rb
db/schema.rb
spec/graphql/resolvers/customers/usage_resolver_spec.rb
spec/models/charge_spec.rb
spec/requests/api/v1/customers_spec.rb
spec/services/charges/build_default_properties_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/update_service_spec.rb

👉 https://getlago.canny.io/feature-requests/p/edit-groups-associated-with-billable-metrics
We want to be able to set a default price on charges with groups.
The goal of this PR is to migrate existing charges by adding default properties on charges with dimensions.
⚠️ This PR can only be merged when the default price feature will be released.

feat(group): Populate default properties on existing charges

---

app/graphql/types/plans/object.rb
app/services/billable_metrics/aggregations/base_service.rb
app/services/charges/apply_pay_in_advance_charge_model_service.rb
app/services/charges/charge_models/percentage_service.rb
spec/scenarios/charge_models/percentage_spec.rb
spec/scenarios/pay_in_advance_charges_spec.rb
spec/services/charges/apply_pay_in_advance_charge_model_service_spec.rb
spec/services/charges/charge_models/percentage_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/apply-price-floorcap-on-transactions
Fintech users want to be able to cap a transaction to a maximum amount or to flour it to a minimum amount.
This feature will apply this logic to the `percentage` charge model.
This PR is the last one for the feature. It uses the previously added `per_event_aggregation` to apply the min/max amount in the percentage charge model service

feat(charge): Apply per transaction min/max in percentage charge model

---

app/models/fee.rb

The goal of this PR is to not have this issue anymore when deleting a fee: `ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR: insert or update on table "credit_note_items" violates foreign key constraint`

misc: Delete credit note items on fee

---

app/models/billable_metric.rb
app/models/group.rb
app/services/billable_metrics/update_service.rb
db/migrate/20230830120517_remove_status_from_groups.rb
db/schema.rb
spec/factories/groups.rb
spec/requests/api/v1/billable_metrics/groups_spec.rb

👉 https://getlago.canny.io/feature-requests/p/edit-groups-associated-with-billable-metrics
We want to be able to edit billable metric groups.
The goal of this PR is to remove useless column `status` from `groups`.

feat(group): Remove status from groups

---

config/initializers/sidekiq.rb

Current dead job limit is 10 000. In some cases it is not enough as we could loose some dead job in case of spike of error.
This PR increase the limit to 100 000 dead job at max

misc: Add sidekiq config to increase max dead job limit

---

app/services/subscriptions/activate_service.rb
clock.rb
spec/scenarios/subscriptions/activation_spec.rb
spec/services/subscriptions/activate_service_spec.rb

Subscription created with a subscription_at set in the future should be started automatically when the date of subscription_at is reached.
In some cases when customer timezone is `UTC-` the job to activate the subscriptions is not fetching al pending subscription correctly, leaving them in a pending state forever.
This PR fixes this situation by:
- Adding the correct timezone shift in the `DATE` query condition
- Ensuring pending subscriptions that should have been started in the past are also taken into account. This will ensure that no subscriptions will remain pending forever.

fix(subscription): Activate should take care of past pending subscription and timezone

---

config/initializers/analytics_ruby.rb

Segment analytics gem generates a lot of logs polluting lago application logs.
Since these logs are mostly useless for us, we can get rid of them
This PR ensures that segment is no longer generating logs.

misc: remove Segment logs

---

app/jobs/clock/terminate_ended_subscriptions_job.rb
app/models/subscription.rb
spec/jobs/clock/terminate_ended_subscriptions_job_spec.rb

Currently it is not possible to terminate subscriptions automatically
In this PR new job that terminates ended subscriptions has been added

feat (subscriptions): add job that terminates ended subscriptions

---

app/models/billable_metric.rb
app/models/charge.rb
app/services/charges/validators/graduated_percentage_service.rb
app/services/charges/validators/percentage_service.rb
app/services/events/validate_creation_service.rb
spec/models/billable_metric_spec.rb
spec/models/charge_spec.rb
spec/services/charges/validators/graduated_percentage_service_spec.rb
spec/services/charges/validators/percentage_service_spec.rb

When user is pre-aggregating number of units on their side, there’s no aggregation type allowing Lago to take in consideration the last unit number received. 
This PR adds validations for new billable metric aggregation type

feat (billable metrics): add validations for latest agg

---

app/graphql/types/billable_metrics/create_input.rb
app/graphql/types/billable_metrics/object.rb
app/graphql/types/billable_metrics/weighted_interval_enum.rb
schema.graphql
schema.json
spec/graphql/mutations/billable_metrics/create_spec.rb

This PR exposes the `weighted_sum_agg` and `weighted_interval` into GraphQL API

feat(weighted-sum): Expose new fields into GraphQL

---

app/controllers/api/v1/billable_metrics_controller.rb
app/serializers/v1/billable_metric_serializer.rb
app/services/billable_metrics/create_service.rb
app/services/billable_metrics/update_service.rb
spec/requests/api/v1/billable_metrics_spec.rb
spec/serializers/v1/billable_metric_serializer_spec.rb

This PR exposes the `billable_metrics#weighted_interval` into the public API

feat(weighted-sum): Expose weighted interval in API

---

app/models/charge.rb
spec/models/charge_spec.rb

This PR adds validation rule to ensure a charge attached to a weighted sum aggregation cannot be payed in advance

feat(weighted-sum): Add charge validation rule preventing pay_in_advance

---

app/models/billable_metric.rb
app/models/charge.rb
app/services/billable_metrics/aggregations/latest_service.rb
app/services/charges/validators/graduated_percentage_service.rb
app/services/charges/validators/percentage_service.rb
app/services/events/validate_creation_service.rb
app/services/fees/charge_service.rb
schema.graphql
schema.json
spec/factories/billable_metrics.rb
spec/models/billable_metric_spec.rb
spec/models/charge_spec.rb
spec/services/billable_metrics/aggregations/latest_service_spec.rb
spec/services/charges/validators/graduated_percentage_service_spec.rb
spec/services/charges/validators/percentage_service_spec.rb

When user is pre-aggregating number of units on their side, there’s no aggregation type allowing Lago to take in consideration the last unit number received. 
This PR adds new billable metric aggregation type and new aggregation service that handles latest aggregation.
In the following PRs missing validations will be added:
- billable metric model validations (that prevents recurring)
- event validation that check if received property is numeric
- charge validations that prevents percentage and graduated percentage model types

feat (billable metrics): Add setup for latest aggregation BM

---

app/serializers/v1/credit_serializer.rb
app/serializers/v1/legacy/credit_serializer.rb
spec/serializers/v1/credit_serializer_spec.rb

A pull request has been opened on the python client to rename for the `invoice_item#lago_item_id` field into `invoice_item#lago_id`.
See https://github.com/getlago/lago-python-client/pull/187
After investigation, it appears that `fees#items` and `credits#items` serializers does not share the same format:
- Fee is using `lago_item_id`
- Credit is using `lago_id`
This PR is:
- Adding `lago_item_id` is the credit serializer
- Moving `lago_id` in the legacy serializer to prevent breaking the existing implementation

fix(invoice): Align fees#item and credits#item seializers

---

.github/workflows/pronto.yml

Pronto actions fail after updating rugged gem to 1.7.1

misc(fix-pronto) Pin rugged gem version to 1.6.3

---

app/models/fee.rb
app/models/group.rb
app/models/quantified_event.rb
app/services/billable_metrics/aggregations/weighted_sum_service.rb
app/services/charges/charge_models/base_service.rb
app/services/fees/charge_service.rb
app/services/fees/create_pay_in_advance_service.rb
app/services/fees/create_true_up_service.rb
db/migrate/20230907153404_add_group_id_to_quantified_events.rb
db/migrate/20230911083923_add_total_aggregated_units_to_fees.rb
db/schema.rb
spec/factories/billable_metrics.rb
spec/factories/fees.rb
spec/models/invoice_spec.rb
spec/models/invoice_subscription_spec.rb
spec/serializers/v1/fee_serializer_spec.rb
spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
spec/services/charges/charge_models/standard_service_spec.rb
spec/services/events/create_service_spec.rb
spec/services/fees/charge_service_spec.rb

This PR adds:
- the aggregation logic for the weighted sum billable metrics.
- it persists the units in `quantified_events` table when the billable metric is recurring
- it stores the units before the application of the `weigthed_interval` to be able to display it on the invoice

feat(weighted-sum): Add aggregation logic

---

app/graphql/types/billable_metrics/update_input.rb
schema.graphql
schema.json
spec/graphql/mutations/billable_metrics/update_spec.rb

This PR add the `weightedInterval` argument in the `Types::BillableMetrics::UpdateInput` GraphQL type

feat(weighted-sum): Add missing weighted interval for BM update in GraphQL

---

app/services/fees/apply_taxes_service.rb
spec/services/fees/apply_taxes_service_spec.rb

In some cases, we are trying to reapply multiple time the same tax to a fee, leading to a database error, because an index was recently added to prevent duplicated taxes.
This PR, adds a guard to the `Fees::ApplyTaxesService` to return immediately if the fee is already attached to taxes

fix(tax): Taxes should not be reapplied to fee if it already has taxes

---

app/views/templates/invoices/_subscription_details.slim
app/views/templates/invoices/fees/_true_up_fee.slim
config/locales/de/invoice.yml
config/locales/en/invoice.yml
config/locales/fr/invoice.yml
config/locales/it/invoice.yml
config/locales/nb/invoice.yml

This PR updates the PDF template to expose the total number of units before applying the weighting interval

feat(weighted-sum): Update invoice PDF template

---

app/models/charge.rb
app/serializers/v1/billable_metric_serializer.rb
app/services/billable_metrics/update_service.rb
spec/models/charge_spec.rb
spec/scenarios/billable_metrics/weighted_sum_spec.rb
spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb

This PR is the last one for the feature, it adds:
- A validation rule ensuring that a charge cannot be prorated if it is attached to a weighted_sum billable metric
- A fix for weighted_interval update on BM
- `weighted_interval` in the billable metric serializer
- A complete scenario for weighted sum billable metric

feat(weighted-sum): Finalize the feature

---

app/controllers/api/v1/plans_controller.rb
app/graphql/mutations/plans/create.rb
app/graphql/mutations/plans/update.rb
app/graphql/types/plans/object.rb
app/models/plan.rb
app/models/subscription.rb
app/serializers/v1/plan_serializer.rb
app/services/plans/create_service.rb
app/services/plans/update_service.rb
app/views/templates/credit_note.slim
app/views/templates/invoices/_subscription_details.slim
app/views/templates/invoices/_subscriptions_summary.slim
app/views/templates/invoices/v1.slim
app/views/templates/invoices/v2.slim
db/migrate/20230907064335_add_invoice_display_name_to_plans.rb
db/schema.rb
schema.graphql
schema.json
spec/factories/plans.rb
spec/graphql/mutations/plans/create_spec.rb
spec/graphql/mutations/plans/update_spec.rb
spec/graphql/types/plans/object_spec.rb
spec/models/plan_spec.rb
spec/models/subscription_spec.rb
spec/requests/api/v1/plans_spec.rb
spec/serializers/v1/plan_serializer_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/update_service_spec.rb

Add the ability to overwrite plan’s and subscription’s names in invoices.
This PR handles only plans and subscriptions invoice display names, charges, fees will be implemented in a follow-up PR.

feat(invoice_display_name_plan): Add invoice display name to plan

---

app/services/payment_provider_customers/stripe_service.rb
spec/services/payment_provider_customers/stripe_service_spec.rb

We are receiving A LOT of `ActiveJob::Uniqueness::JobNotUnique` on ` PaymentProviders::Stripe::HandleEventJob`.
It happens when we tries to reprocess pending invoices for a customer after receiving a Stripe `setup_intent.succeeded`.
This PR is an attempt to reduce the noise in the Sidekiq dead queue by ensuring only finalized and ready for processing invoices are being retried.

fix(stripe): Prevent new payment attempt when invoice is not in the right status

---

app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb

Usecase:
1. Pay in advance event is stored
2. Current usage requested and fails (there is no metadata attached on event and those data are needed for pay in advance current usage)
3. Async job that process pay in advance invoices attaches metadata on event
In order to avoid this race condition, this fix is added. We are ignoring pay in advance events that are not in valid state

fix (charges): refactor paid in advance processing

---

app/services/customers/update_service.rb
spec/services/customers/update_service_spec.rb

Today partially updating a customer (updating taxes, grace period...) is changing Stripe customer’s payment method, leading to failures in invoice payments
This PR ensures that stripe provider customer is updated only if `provider_customer` or `payment_provider` arguments is provider.

fix(customer): prevent updating provider customer on partial update

---

app/serializers/v1/coupon_serializer.rb
spec/serializers/v1/coupon_serializer_spec.rb

Call to `GET /v1/api/coupons/:code` is missing the `terminated_at` value
This PR is adding the missing field in the `V1::CouponSerializer`

fix(coupon): Add missing coupons#terminated_at in serializer

---

db/migrate/20230918090426_add_index_to_events.rb
db/schema.rb

Current usage retrieval could be slow for users with a lot of events.
This PR updates of the `events` table to change the indexes. It ensures the `timestamp` is taken into account in the index along with `code` and `subscription_id`

feat(event): Improve indexes to speed up current usage computation

---

app/models/plan.rb
app/services/charges/override_service.rb
app/services/plans/override_service.rb
db/migrate/20230915073205_update_code_index_on_plans.rb
db/schema.rb
spec/services/charges/override_service_spec.rb
spec/services/plans/override_service_spec.rb

- change validation on plan's code to be unique if `parent_id` is `nil`
- add service to override a charge
- add service to override a plan

feat(override-plan): Services for overriding a plan

---

db/migrate/20230920083133_add_gin_index_to_events.rb
db/schema.rb

Current usage is slow for organization with a lot of events.
One of the issue is related to the queries looking into the jsonb properties field.
This PR is adding a GIN index to the events#properties field to speed up queries into this field.
See https://www.postgresql.org/docs/current/datatype-json.html#JSON-INDEXING

misc: Add GIN index to events properties

---

app/controllers/api/v1/subscriptions_controller.rb
app/graphql/resolvers/subscription_resolver.rb
app/graphql/types/query_type.rb
config/routes.rb
schema.graphql
schema.json
spec/graphql/resolvers/subscription_resolver_spec.rb
spec/requests/api/v1/subscriptions_spec.rb

- add the endpoint `GET /api/v1/subscriptions/:external_id`
- add the GraphQL resolver for fetching a single subscription

feat(override-plan): Add GET single subscription endpoint

---

db/migrate/20230920083133_add_gin_index_to_events.rb

Before:
```
Migrating to AddGinIndexToEvents (20230920083133)
== 20230920083133 AddGinIndexToEvents: migrating ==============================
-- add_index(:events, :properties, {:using=>"gin", :opclass=>:jsonb_path_ops, :algorithm=>:concurrently})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:
PG::ActiveSqlTransaction: ERROR:  CREATE INDEX CONCURRENTLY cannot run inside a transaction block
/app/db/migrate/20230920083133_add_gin_index_to_events.rb:5:in `change'
Caused by:
ActiveRecord::StatementInvalid: PG::ActiveSqlTransaction: ERROR:  CREATE INDEX CONCURRENTLY cannot run inside a transaction block
/app/db/migrate/20230920083133_add_gin_index_to_events.rb:5:in `change'
Caused by:
PG::ActiveSqlTransaction: ERROR:  CREATE INDEX CONCURRENTLY …
```

fix: Run migration without a transaction

---

app/controllers/api/v1/subscriptions_controller.rb
app/graphql/types/subscriptions/charge_overrides_input.rb
app/graphql/types/subscriptions/create_subscription_input.rb
app/graphql/types/subscriptions/plan_overrides_input.rb
app/serializers/v1/plan_serializer.rb
app/services/subscriptions/create_service.rb
schema.graphql
schema.json
spec/graphql/mutations/subscriptions/create_spec.rb
spec/requests/api/v1/subscriptions_spec.rb
spec/serializers/v1/plan_serializer_spec.rb

- Return parent_id on Plan serializer
- Add plan overrides to subscriptions controller
- Add plan overrides to create subscription graphql input

feat(override-plan): Ability to override plan on API subscription creation

---

clock.rb
spec/clock_spec.rb

Pending subscription with a subscription_at in the future are started automatically by a clock job that is executed every one hour at *:30
All events sent between the subscription_at and the started_at (activation time) are not passing validation as the subscription is not active from a database perspective.
A short term fix to reduce this window is to perform the activation job every 5 minutes.
On the long run, with the plans for high event volume feature, a proper change will remove the upfront validation of events. It will fix the current issue.

misc: Speedup subscription activation

---

app/services/fees/subscription_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/subscriptions/billing_service.rb
clock.rb
spec/scenarios/subscriptions/terminate_ended_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/subscriptions/billing_service_spec.rb

If termination happens on billing day before actual billing job has been processed, we will bill only one day instead of previous period for pay in arrears case.
This is especially important for subscription ending feature since termination can be automatically performed with such a feature.
NOTE: This PR also serves as QA branch so `clock.rb` is also updated. Once this case is QA validated this branch will be merged and subscription ending date feature completed
The solution here is to check if we are on the beginning of period and also to check if there is any `InvoiceSubscription` object for previous period

fix (invoice): bill correctly termination on billing day case

---

app/jobs/clock/subscriptions_to_be_terminated_job.rb
spec/jobs/clock/subscriptions_to_be_terminated_job_spec.rb

The goal of this PR is to extend logic for termination alert webhook. We want to trigger this webhook not only 15 days before subscription ending but also 45 days before.

feat (subscriptions): update termination alert webhook

---

app/graphql/mutations/plans/create.rb
app/services/plans/create_service.rb
db/migrate/20230922064617_remove_parent_id_from_plans.rb
db/schema.rb
schema.graphql
schema.json

We want to prevent duplicating a plan by linking it to another plan, thanks to the property `parent_id`.
Overriding a plan will be done thanks to the `POST /api/v1/subscriptions` endpoint.
⚠️ Do not merge until the release of the feature.

feat(override-plan): Remove parent_id from graphql

---

app/graphql/types/plans/object.rb
app/models/plan.rb
app/serializers/v1/plan_serializer.rb
spec/models/plan_spec.rb
spec/serializers/v1/plan_serializer_spec.rb

the goal of this PR is to include customers using overridden plans on `customers_count` of the parent plan.

feat(override-plan): Take into consideration children for customers_count

---

app/controllers/api/v1/plans_controller.rb
app/controllers/api/v1/subscriptions_controller.rb
app/graphql/mutations/subscriptions/update.rb
app/graphql/types/subscriptions/plan_overrides_input.rb
app/graphql/types/subscriptions/update_subscription_input.rb
app/models/plan.rb
app/queries/plans_query.rb
app/serializers/v1/plan_serializer.rb
app/services/plans/override_service.rb
app/services/subscriptions/update_service.rb
schema.graphql
schema.json
spec/requests/api/v1/subscriptions_spec.rb
spec/services/plans/override_service_spec.rb
spec/services/subscriptions/update_service_spec.rb

- be able to update plan overrides on `PUT /subscriptions/:external_id`
- be able to override name and description of plans

feat(override-plan): Ability to update plan overrides

---

app/jobs/plans/destroy_job.rb
app/services/plans/create_service.rb
app/services/plans/override_service.rb
app/services/plans/prepare_destroy_service.rb
app/services/subscriptions/create_service.rb
spec/requests/api/v1/plans_spec.rb
spec/scenarios/delete_plan_spec.rb
spec/services/plans/create_service_spec.rb
spec/services/plans/override_service_spec.rb

- track overridden plans on Segment 
- be able to discard a plan and children

feat(override-plan): Discard plan and children

---

app/graphql/types/plans/object.rb
app/models/plan.rb
app/serializers/v1/plan_serializer.rb
spec/models/plan_spec.rb
spec/serializers/v1/plan_serializer_spec.rb

The goal of this PR is to include overridden plans to plan's counters.

feat(override-plan): Include overridden plans to plan's counters

---

app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/latest_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/billable_metrics/aggregations/weighted_sum_service.rb
app/services/billable_metrics/prorated_aggregations/sum_service.rb

Aggregation are slow on large events volume and we need to improve that
This PR changes field presence check on all aggregation to move from a `IS NOT NULL` to the proper json operator so that the GIN index could be used by PG

misc: Refact aggregation query to speedup field presence check

---

app/controllers/api/v1/events_controller.rb
app/jobs/events/create_job.rb
app/services/events/create_service.rb
app/services/invoices/customer_usage_service.rb
app/services/subscriptions/charge_cache_service.rb
spec/jobs/events/create_job_spec.rb
spec/services/events/create_service_spec.rb
spec/services/invoices/customer_usage_service_spec.rb

Current usage caching is not optimal as it is implemented today.
it keeps the cache for 4 days maximum and expires as soon as a new event is received for a subscription.
This PR changes the approach by: 
- caching the results at charge level
- keeping it until the end of the billing period
- cleaning automatically the charge cache when a new event matching this charge is received

misc: Add granular caching for current usage

---

app/services/events/create_service.rb

A regression was introduce by a previous refactoring for the current usage cashing.
In case of event validation error, a webhook is delivered to the emitter to inform him. But the call to this method was not correctly adapted to the refactor, leading to an `ArgumentError`.
This PR fixes the call to the `deliver_error_webhook` method by removing the organization argument.

fix(event): Error webhook delivery

---

Gemfile
Gemfile.lock
app/graphql/resolvers/events_resolver.rb
app/graphql/types/events/object.rb
app/jobs/billable_metrics/delete_events_job.rb
app/models/event.rb
app/models/events_record.rb
app/services/billable_metrics/aggregations/base_service.rb
config/database.yml
spec/factories/events.rb
spec/graphql/resolvers/events_resolver_spec.rb
spec/jobs/billable_metrics/delete_events_job_spec.rb
spec/models/invoice_spec.rb
spec/rails_helper.rb
spec/scenarios/billable_metrics/weighted_sum_spec.rb
spec/scenarios/invoices_spec.rb
spec/scenarios/pay_in_advance_charges_spec.rb
spec/serializers/v1/fee_serializer_spec.rb
spec/services/billable_metrics/aggregations/count_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
spec/services/billable_metrics/breakdown/sum_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
spec/services/charges/pay_in_advance_aggregation_service_spec.rb
spec/services/events/validate_creation_service_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb
spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
spec/spec_helper.rb

This PR:
- Adds the configuration for a proper events database
- Sends all Event.read queries to the event database
- Clean event related queries to rely on IDs and not Active Record models

feat(event): Add logical separation between application and events databases

---

app/serializers/v1/fee_serializer.rb
app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/billable_metrics/aggregations/weighted_sum_service.rb
app/services/events/create_batch_service.rb
app/services/events/create_service.rb
app/services/events/validate_creation_service.rb
app/services/fees/estimate_pay_in_advance_service.rb
spec/graphql/resolvers/events_resolver_spec.rb
spec/scenarios/create_event_spec.rb
spec/services/events/create_batch_service_spec.rb
spec/services/events/create_service_spec.rb

This PR changes all event related queries to rely only on the event table without joins on other relation

feat(event): Refact event queries

---

app/models/events_record.rb
app/services/events/create_batch_service.rb
app/services/events/create_service.rb
config/database.yml
db/migrate/20220704145333_fill_event_timestamps.rb
db/migrate/20220722123417_add_subscription_id_to_events.rb
db/migrate/20230926132500_add_external_ids_to_events.rb
db/schema.rb
db/seeds/base.rb
spec/factories/events.rb
spec/services/events/create_service_spec.rb

This PR adds `events#external_customer_id` and `events#external_subscription_id fields`. Event creations services are also updated in order to fill these fields with the appropriate value.
Note: A DB migration will come right after to populate theses fields for existing events

feat(event): Add external customer_id and external_subscription_id

---

app/queries/past_usage_query.rb
spec/queries/past_usage_query_spec.rb

Some of our users want to retrieve usage in the past. The main problem they are facing is that at the beginning of a new period, they cannot compute usage in third party systems, or see if everything went well as usage for the past period has been removed.
This PR adds a `PastUsageQuery` to fetch pas usage for a customer/subscription, based on the previous invoices/fees

feat(past_usage): Add base query to fetch past usage

---

app/services/customers/update_invoice_payment_due_date_service.rb
spec/services/customers/update_service_spec.rb

We have an issue when a customer updates it's `net_payment_term` value while having draft invoices.
Those invoices hold their own value of `net_payment_term` but this on was not updated when the customer one was updated.
This update should only concern draft invoices
This PR removes a check that was systematically false.
The reason is that before calling this service, the customer `net_payment_term` was already updated with the new values from the params, leading to the condition always being false.
So I removed it. Having to parse all draft invoices each time won't be that costly in terms of performance.

fix: update draft invoice net_payment_term on customer update

---

app/models/charge.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/prorated_aggregations/base_service.rb
app/services/billable_metrics/prorated_aggregations/sum_service.rb
app/services/charges/charge_models/prorated_graduated_service.rb
app/services/fees/charge_service.rb
spec/scenarios/charge_models/prorated_graduated_spec.rb
spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
spec/services/charges/charge_models/prorated_graduated_service_spec.rb

Currently it is not possible to process graduated and prorated case
This improvement handles recurring amount so that we don't need to load it in memory and calculate it each time while processing current usage or subscription invoice

feat(graduated-prorated): Add improvement for graduated prorated case

---

db/migrate/20230926144126_fill_event_external_ids.rb
db/schema.rb

This PR adds a migration to populate new `events#external_customer_id` and `events#external_subscription_id`

feat(event): Add migration to fill external ids

---

app/graphql/types/plans/object.rb
schema.graphql
schema.json
spec/graphql/types/plans/object_spec.rb

We need access to all the plan's parent information for future development.
Currently, the `plan.parent_id` is not used in the front-end application.
This PR updated the plan Object to reflect this change and expose the new schema updated

refactor(plan): expose parent object instead of only it's ID

---

app/services/subscriptions/create_service.rb
app/services/utils/transactional_jobs.rb
spec/scenarios/subscriptions/upgrade_spec.rb

Some issues were recently reported with subscription upgrade with subscriptions attached to a plan payed in advance,
After investigation it appears that the issue is related to some jobs enqueued during the database transaction dealing with the upgrade process. As the jobs might be performed by sidekiq before the commit of the transaction, the result is unpredictable (subscription status in particular might not be the expected one) and the issue hard to reproduce.
The fix is to add all jobs in a queue and perform them only when the DB transaction lock is released.
For that purpose a new reusable utility concern was created named `Utils::TransactionalJobs`. It exposes two methods: `perform_later` to push the job into a queue and `perform_pending_jobs` to run all jobs when the transaction …

hotfix: Subscription upgrade

---

app/services/invoices/calculate_fees_service.rb

We have few error on the API: `undefined method `days' for nil:NilClass (NoMethodError)`
It is related to the boundaries on the terminated subscription that is missing the `charges_duration` attribute.
This PR fixes the issue by adding the missing attribute

fix: Fix charge boundaries for terminated subscription

---

app/services/invoices/payments/stripe_service.rb
spec/services/plans/update_service_spec.rb

This PR is a fix for `undefined method `invoice_settings' for #<Stripe::Customer` error.
The error occurs when we try to emit a payment on a customer that was deleted on Stripe side. Before sending the payment, we try to refresh the payment method. When the stripe customer is deleted, Stripe still returns it in the response but with a `deleted` flag and no `invoice_settings`.
When it occurs, we can safely return and let the payment generation failed. It will set the invoice payment status to `failed` and will notify the organization via a webhook.
In the future, we should reflect this status in Lago database to stop emitting payments for this customer.
*NOTE: this PR also contains a fix for some flaky tests*

fix(stripe): Prevent issue when refreshing payment method on deleted stripe customer

---

app/services/webhooks/base_service.rb

`Net::OpenTimeout` should be handled by the auto retry / error management system of the webhooks

fix(webhook): Handle Net::OpenTimeout in auto-retry

---

app/jobs/payment_providers/stripe/handle_event_job.rb

Stripe webhook for payment intent creation might sometimes be received before the persistence of the corresponding payment in Lago database, leading to a `BaseService::NotFoundFailure`
This PR adds retry logic for the `PaymentProviders::Stripe::HandleEventJob`

fix(stripe): Retry not found payment intent update

---

app/services/payment_provider_customers/stripe_service.rb

A lot of noise is generated by dead job with `ActiveJob::Uniqueness::JobNotUnique` when we try to reprocess pending invoices at reception of a Stripe webhook.
This happen because multiple stripe webhooks can be received during the processing of a payment and the application only allows one processing job per invoice to prevent duplicated payments.
Since nothing can be done for those jobs, this PR simply prevent the job handing from failing and logs a message.
In a future a proper `processing` payment status should be introduced to reduce this window of `duplication risk`.

fix(stripe): Turn off duplicated payement errors when retries from webhooks

---

app/queries/past_usage_query.rb

Past usage is sometime failing when invoiceable payed in advnaces chages were previously invoiced. The reason behind this is that those invoice does not have boundaries, leading to an error during the serialization.
This PR ensures that only invoices with proper boundaries are taken into account for the past usage

fix(past-usage): Fix for invoiceable payd in advance charges

---

app/queries/past_usage_query.rb
spec/requests/api/v1/customers/usage_spec.rb

An issue has been identified with the past usage API end-point when the `periods_count` parameter is passed in the query.
The issue is received as a string when the pagination logic expects for an integer.
This PR fixes the issue by converting the parameter into an integer.

fix(past_usage): periods count must be converted into integer

---

.github/workflows/spec.yml
.gitignore
config/database.yml

In some context, due to the newly released multi-db approach for the event storage, it was impossible to perform reset migration task on the development database.
This PR fixes this problem by enabling the `primary` suffix on migration tasks.
With this fix, to reset the dabatase, just run `bundle exec rails db:reset:primary`

fix: Migration tasks for primary database

---

app/graphql/types/subscriptions/charge_overrides_input.rb
app/models/coupon.rb
app/services/credits/applied_coupon_service.rb
schema.graphql
schema.json
spec/graphql/mutations/subscriptions/create_spec.rb

The goal of this PR is to be able to override invoice display name on a specific charge via graphql.

feat(override-plan): Ability to override invoice display name of a charge

---

app/graphql/resolvers/subscriptions_resolver.rb
app/graphql/types/query_type.rb
schema.graphql
schema.json
spec/graphql/resolvers/subscriptions_resolver_spec.rb

The goal of this PR is to be able to fetch subscriptions via graphql in order to create the plan's page.

feat(override-plan): Add subscriptions graphql resolver

---

app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/latest_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/weighted_sum_service.rb
app/services/billable_metrics/prorated_aggregations/sum_service.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb

This PR add filters on event aggregation queries to ignore events that does not match the prerequisite (numeric values)

feat(event): Filter events with invalid properties in aggregation

---

app/models/subscription.rb
app/services/events/post_process_service.rb
app/services/fees/estimate_pay_in_advance_service.rb
spec/services/events/post_process_service_spec.rb

This PR add a check on the number of active subscriptions when post-processing an event. If multiple subscriptions are identified, the event is not attached to any subscription.

feat(event): Ensure only one active subscription is active in post-processing

---

app/services/subscriptions/create_service.rb
app/services/subscriptions/terminate_service.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/subscriptions/terminate_service_spec.rb

The goal of this PR is to send `subscription.started` and `subscription.terminated` on upgrade and downgrade.

feat: Send started and terminated subscription webhooks

---

config/initializers/aasm.rb

AASM gem displays warnings like:
```
W, [2023-10-17T08:44:50.999036 #326]  WARN -- : Invoice: overriding method 'draft?'!
W, [2023-10-17T08:44:50.999271 #326]  WARN -- : Invoice: overriding method 'finalized?'!
W, [2023-10-17T08:44:50.999487 #326]  WARN -- : Invoice: overriding method 'voided?'!
```
Lets hide these warnings:
https://github.com/aasm/aasm/issues/361#issuecomment-1157454157

misc(hide-aasm-warnings): Hide aasm warnings

---

app/services/payment_provider_customers/adyen_service.rb
spec/services/payment_provider_customers/adyen_service_spec.rb

There is a bug that occurs when payment provider is no longer present.
Generating of a checkout url fails with NoMethodError.

fix(adyen-checkout-url): Fix generating adyen checkout url when psp is not present

---

app/models/invoice.rb
spec/models/invoice_spec.rb

- Invoice URL is not working when using `LAGO_API_URL` with port or subpath

fix(invoice): Fix URL when API URL is not a domain

---

app/services/credit_notes/refunds/adyen_service.rb
app/services/invoices/payments/adyen_service.rb
app/services/payment_provider_customers/adyen_service.rb
lib/lago/adyen/params.rb
spec/lib/lago/adyen/params_spec.rb

Add Adyen's partners info.
Add Adyen’s partner info to identify Lago as a partner.
https://docs.adyen.com/development-resources/application-information/

feat(adyen-partner-info) Add Adyen partner info to all requests

---

app/models/charge.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/prorated_aggregations/base_service.rb
app/services/billable_metrics/prorated_aggregations/sum_service.rb
app/services/billable_metrics/prorated_aggregations/unique_count_service.rb
app/services/charges/charge_models/prorated_graduated_service.rb
app/services/fees/charge_service.rb
spec/scenarios/charge_models/prorated_graduated_spec.rb
spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
spec/services/charges/charge_models/prorated_graduated_service_spec.rb

Currently graduated charge model cannot be used with `prorated` = `true`
This PR covers new charge model service, made especially for this purpose.
Later, the service will be improved with the logic where recurring amount fetched from the DB and computation is done only for current period.

feat (graduated-prorated): add logic for graduated prorated charge model

---

app/controllers/concerns/api_errors.rb
app/services/base_service.rb
app/services/customers/create_service.rb
app/services/payment_provider_customers/create_service.rb
app/services/payment_provider_customers/stripe_service.rb
spec/services/payment_provider_customers/stripe_service_spec.rb

When Stripe hasn’t been set up in the settings, or the Stripe API key is invalid, and the user tries to create a customer account through integration, the API returns a 500.
Return a 401 error with a message that Stripe authentication failed.

misc(stripe-unauthorized): Rescue Stripe::AuthenticationError error

---

app/services/customers/create_service.rb
spec/services/customers/create_service_spec.rb

If `sync_with_provider` is true, there is no payment provider for customer but payload is missing payment_provider attribute the error is raised.
We need to add guard clause for that case

fix (customers): fix customer create flow when sync_with_provider is true

---

app/services/fees/subscription_service.rb
db/migrate/20231020091031_convert_unit_amount_cents_to_decimal.rb
db/schema.rb
spec/services/fees/subscription_service_spec.rb

👉  [https://getlago.canny.io/feature-requests/p/{{FEATURE_SLUG}}](https://getlago.canny.io/feature-requests/p/display-unit-price-fee-breakdown)
- convert unit amount cents to decimal
- compute unit amount cents to subscription's fee

feat(unit-price): Add unit amount cents to subscription fee

---

app/services/payment_provider_customers/adyen_service.rb
spec/factories/payment_responses.rb
spec/services/payment_provider_customers/adyen_service_spec.rb

When receiving an error from Adyen (422 Error), we do not log it and we do not return a webhook with the error. We should send a webhook with the error, so the user know about it.

fix(adyen-no-payment-methods): Send an error webhook when no payment methods are active

---

app/services/fees/one_off_service.rb
app/services/fees/subscription_service.rb
db/migrate/20231027144605_add_precise_unit_amount_to_fees.rb
db/schema.rb
spec/services/fees/one_off_service_spec.rb
spec/services/fees/subscription_service_spec.rb

- revert unit amount cents to bigint
- create new decimal column `unit_amount` to store precise fee's unit amount
We'll deprecate `unit_amount_cents` in the future.

feat(unit-price): Add unit_amount to fees

---

app/services/billable_metrics/aggregation_factory.rb
app/services/charges/pay_in_advance_aggregation_service.rb
app/services/fees/charge_service.rb
spec/factories/billable_metrics.rb
spec/services/billable_metrics/aggregation_factory_spec.rb
spec/services/charges/pay_in_advance_aggregation_service_spec.rb

With the coming high usage event ingestion, aggregator classes will have to be adapted to target the right event store (PG or Clickhouse) depending on the context.
To make it easier, and since current Aggregator initialization is quite complex, a small cleanup has to be performed in order to simplify the logic.
This PR takes advantage of the factory pattern to initialize the right aggregator for a charge.
It will also soon be responsible for passing the right Event store

feat(billable-metric): Use Factory pattern to initialize aggregators

---

app/controllers/api/v1/credit_notes_controller.rb
app/graphql/resolvers/credit_notes/estimate_resolver.rb
app/graphql/types/credit_note_items/estimate.rb
app/graphql/types/credit_notes/estimate.rb
app/graphql/types/query_type.rb
app/serializers/v1/credit_notes/applied_tax_serializer.rb
app/serializers/v1/credit_notes/estimate_serializer.rb
app/services/credit_notes/estimate_service.rb
config/routes.rb
db/clickhouse_schema.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/resolvers/credit_notes/estimate_resolver_spec.rb
spec/graphql/types/credit_note_items/estimate_spec.rb
spec/graphql/types/credit_notes/estimate_spec.rb
spec/requests/api/v1/credit_notes_spec.rb
spec/scenarios/credit_note_spec.rb
spec/serializers/v1/credit_notes/estimate_serializer_spec.rb
spec/services/credit_notes/estimate_service_spec.rb
spec/support/scenarios_helper.rb

Today it's hard to compute amounts for credit note creation when coupons or multiple tax rates are applied.
The front end and API users have to compute the tax and coupon pro-rata, credit and refund amounts by themselves hopping that the result will match the amounts computed on the backend when validating the validation.
In order to make it easier to create a credit note, this PR adds a new API end point and GraphQL resolver to retrieve creditable/refundable amounts based on items amount.
It exposes:
- A new `GET /api/v1/credit_notes` route
- A new `creditNoteEstimate` resolver

feat(credit_note): Add estimate service and API end points

---

Dockerfile
Dockerfile.dev

- `alpine` for ruby is not recommended in term of performances, a classic `slim` image based on debian is better.

misc(docker): Use now ruby-slim instead of alpine

---

spec/requests/api/v1/invoices_spec.rb

Create invoice request spec was failing sometimes.
Addon fees were rarely created in an opposite order, we're now finding the fee by code to be sure to get the correct one.

fix(invoice): Fix create invoice request spec

---

app/services/charges/charge_models/base_service.rb
app/services/charges/charge_models/standard_service.rb
app/services/fees/charge_service.rb
app/services/fees/create_true_up_service.rb
db/migrate/20231102154537_change_precision_to_precise_unit_amount.rb
db/schema.rb
spec/services/charges/charge_models/standard_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/create_true_up_service_spec.rb

The goal of this PR is to compute `precise_unit_amount` for standard charge models.

feat(unit-price): Set precise unit amount to standard charge model

---

app/models/invoice.rb
app/services/billable_metrics/aggregation_factory.rb
app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/events/stores/base_store.rb
app/services/events/stores/clickhouse_store.rb
app/services/events/stores/postgres_store.rb
spec/services/billable_metrics/aggregations/count_service_spec.rb
spec/services/billable_metrics/aggregations/latest_service_spec.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
spec/services/billable_metrics/breakdown/sum_service_spec.rb
spec/services/billable_metrics/breakdown/unique_count_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
spec/services/charges/apply_pay_in_advance_charge_model_service_spec.rb
spec/services/charges/charge_models/percentage_service_spec.rb
spec/services/charges/charge_models/prorated_graduated_service_spec.rb
spec/services/charges/pay_in_advance_aggregation_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/1404, https://github.com/getlago/lago-api/pull/1419 and https://github.com/getlago/lago-api/pull/1422 and uses dependency injection to pass the event data store to the aggregator services.
The PR adds to event store:
- `Events::Stores::PostrgresStore`
- `Events::Stores::ClickhouseStore`
These store all extends `Events::Stores::BaseStore` and could be passed to the aggregation initializers
NOTE: Only count aggregation is implemented using this logic, more will come later

feat(event): Inject event store in aggregators

---

app/controllers/api/v1/organizations_controller.rb
app/graphql/types/organization_type.rb
app/graphql/types/organizations/update_organization_input.rb
app/models/organization.rb
app/serializers/v1/organization_serializer.rb
app/services/organizations/update_service.rb
db/migrate/20231101080314_add_default_currency_to_organizations.rb
db/schema.rb
schema.graphql
schema.json
spec/factories/organizations.rb
spec/graphql/mutations/organizations/update_spec.rb
spec/graphql/types/organization_type_spec.rb
spec/graphql/types/organizations/update_organization_input_spec.rb
spec/models/organization_spec.rb
spec/requests/api/v1/organizations_spec.rb
spec/serializers/v1/organization_serializer_spec.rb
spec/services/organizations/update_service_spec.rb

To display revenue graphs, we need to know what is the default currency of an organization. This default currency will be used as a filter when landing on this dashboard section.
This PR adds `default_currency` column to `organizations` table.
It also adds the field to organization graphql type and update input, serializer and the organization update service.

feat(default-currency): Add organization default currency

---

app/services/plans/override_service.rb
app/services/subscriptions/create_service.rb
app/services/subscriptions/update_service.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/subscriptions/update_service_spec.rb

When license is not valid and user wants to perform plan override, we should render forbidden error and not unprocessable entity error (validation failure)

fix(plan-override): render forbidden error for plan override without premium license

---

app/services/plans/override_service.rb

The goal of this PR is to avoid having N+1 queries when overriding a plan with group properties.

misc: Include group properties when overriding a plan

---

app/controllers/api/v1/invoices_controller.rb

This PR fixes `undefined local variable or method `resource' for #<Api::V1::InvoicesController` when trying to retry a payment for an invoice, when the invoice is not found.

fix: API Invoice payment retry when not found

---

app/models/recurring_transaction_rule.rb
app/models/wallet.rb
app/models/wallet_transaction.rb
db/migrate/20231103144201_create_recurring_transaction_rules.rb
db/schema.rb
spec/factories/recurring_transaction_rules.rb

Currently Lago supports only manual wallet transactions. With Recurring transactions feature it will be possible to top-up wallet automatically with threshold or intervals rules.
This PR adds needed DB changes

feat (recurring-wallet-transactions): add db changes for recurring wallet transactions

---

app/controllers/api/v1/subscriptions_controller.rb
app/services/subscriptions/update_service.rb
spec/requests/api/v1/subscriptions_spec.rb
spec/services/subscriptions/update_service_spec.rb

- Ensure to not override a children plan
- Update the plan when updating a subscription with plan overrides

fix(plan-override): Ensure to override parent plans

---

Gemfile
Gemfile.lock
app/jobs/clock/events_validation_job.rb
app/models/events/last_hour_mv.rb
db/clickhouse_migrate/20231030163703_create_events_raw_mv.rb
db/migrate/20231109141829_create_last_hour_events_mv.rb
db/migrate/20231109154934_add_events_validation_index.rb
db/schema.rb
db/views/last_hour_events_mv_v01.sql
spec/jobs/clock/events_validation_job_spec.rb

Since we no longer validate event ingestion, users are flying blind to understand which events have been ingested but not used for billing.
Ideally, our users should receive warnings when issues are detected during event ingestion.
This PR is the first step of the feature.
It adds a new Clock job (not activated yet) that will be executed every hour to:
- Refresh a materialized view with the events from the last terminated hour
- (later) enqueue a validation job for each organization that have received at least one event

feat(events): Add Materialized view for post validation

---

app/graphql/types/credit_notes/estimate.rb
app/models/credit_note.rb
app/serializers/v1/credit_notes/estimate_serializer.rb
app/services/credit_notes/apply_taxes_service.rb
app/services/credits/applied_coupon_service.rb
db/schema.rb
schema.graphql
schema.json
spec/models/credit_note_spec.rb
spec/scenarios/credit_note_spec.rb
spec/services/credit_notes/validate_service_spec.rb

Since it's a complicated task to create a credit note with coupons, multiple tax rates and other complex computation, we recently introduce a `CreditNotes::EstimateService` and the corresponding API/GraphQL endpoint to interact with it.
However, it appears that the computation is not always correct when different taxes are applied to an invoice.
This PR tries the fix this situation by fixing the computed tax rate on the credit note and by exposing the `precise_taxes_amount_cents` into the GraphQL query.

fix(credit-note): Fix credit note estimate taxe rate

---

app/graphql/types/subscriptions/charge_overrides_input.rb
schema.graphql
schema.json
spec/graphql/mutations/subscriptions/create_spec.rb

Currently, updating a charge from a subscription is not working because `billable_metric_id` is missing.
The goal of this PR is to fix it by accepting `billableMetricId`.

fix: Ability to update charge from subscription

---

app/services/customers/update_invoice_grace_period_service.rb
app/services/customers/update_service.rb
app/services/invoices/finalize_service.rb
app/services/organizations/update_invoice_grace_period_service.rb
spec/scenarios/customers/update_invoice_grace_period_spec.rb

We have some issues with not sent emails after updating the grace period to 0.
The goal of this is to fix them by removing a transaction.

fix: Ensure email is sent after finalizing an invoice

---

app/services/credit_notes/create_from_termination.rb
spec/services/credit_notes/create_from_termination_spec.rb

Lago should not try to automatically generate credit notes for void invoices.
This PR fixes `CreditNotes::CreateFromTermination` service.

fix(void-invoices-credit-notes): Do not create credit notes for voided invoice

---

app/models/cached_aggregation.rb
db/migrate/20231016115055_create_cached_aggregations.rb
db/schema.rb
spec/factories/cached_aggregations.rb

This PR is the first step for https://github.com/getlago/lago-api/pull/1400
It creates the `CachedAggregation` model that will be used to move events cached metadata outside of the event table.

feat(event): Add cached aggregation model

---

app/jobs/clock/create_interval_wallet_transactions_job.rb
app/jobs/wallet_transactions/create_job.rb
app/services/wallet_transactions/create_service.rb
app/services/wallets/create_interval_wallet_transactions_service.rb
app/services/wallets/create_service.rb
spec/jobs/clock/create_interval_wallet_transactions_job_spec.rb
spec/jobs/wallet_transactions/create_job_spec.rb
spec/services/wallet_transactions/create_service_spec.rb
spec/services/wallets/create_interval_wallet_transactions_service_spec.rb

Currently, wallet transactions (top-up) can be added in a manual way. With this feature we will enable automatic top-up based on interval or threshold rules
This PR adds support for automatic top-up based on wallet interval recurring rules

feat(recurring-transactions-wallet-rules): handle interval transaction rule

---

app/jobs/clock/events_validation_job.rb
app/jobs/events/post_validation_job.rb
app/jobs/send_webhook_job.rb
app/serializers/v1/events_validation_errors_serializer.rb
app/services/events/post_validation_service.rb
app/services/webhooks/events/validation_errors_service.rb
clock.rb
spec/clock_spec.rb
spec/jobs/clock/events_validation_job_spec.rb
spec/jobs/send_webhook_job_spec.rb
spec/serializers/v1/events_validation_errors_serializer_spec.rb
spec/services/events/post_validation_service_spec.rb
spec/services/webhooks/events/validation_errors_service_spec.rb

Since we no longer validate event ingestion, users are flying blind to understand which events have been ingested but not used for billing.
Ideally, our users should receive warnings when issues are detected during event ingestion.
This PR is the last step of the feature.
- It plugs the clock job. It is performed every hour.
- It adds the new `V1::EventsValidationErrorsSerializer`
- It adds the new `Webhooks::Events::ValidationErrorsService`
- It implements the validation logic into a new `Events::PostValidationService.call(organization:)`

feat(event): Add post validation service

---

app/services/invoices/calculate_fees_service.rb
spec/scenarios/subscriptions/terminate_ended_spec.rb

When anniversery period and when `terminated_at` is the same as `started_at`, termination boundaries haven't been calculated correctly.
This PR fixes this issue and adds scenario test for this case.

fix(subscriptions): fix termination boundaries

---

app/models/organization.rb
app/models/quantified_event.rb
app/services/billable_metrics/aggregations/recurring_count_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/billable_metrics/aggregations/weighted_sum_service.rb
app/services/billable_metrics/prorated_aggregations/unique_count_service.rb
app/services/fees/charge_service.rb
app/services/quantified_events/create_or_update_service.rb
app/services/quantified_events/validate_creation_service.rb
db/migrate/20221021135946_fill_properties_on_persisted_events.rb
db/migrate/20231117123744_add_organization_id_to_quantified_events.rb
db/schema.rb
lib/tasks/events.rake
spec/factories/quantified_events.rb
spec/scenarios/billable_metrics/weighted_sum_spec.rb
spec/services/billable_metrics/aggregations/recurring_count_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
spec/services/billable_metrics/breakdown/unique_count_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/quantified_events/create_or_update_service_spec.rb
spec/services/quantified_events/validate_creation_service_spec.rb

Related to https://github.com/getlago/lago-api/pull/1436
On the path for high volume improvements, we need to remove the need for event post-processing and align aggregation logic between Clickhouse and Postgres event stores.
In order to use `subscriptions#external_id` only for events aggregation, we have to fix the relation on the `quantified_events` table as we cannot rely to `customer_id` anymore.
To fix the logic, this PR:
- Adds `quantified_events#organization_id` relation
- Drops `quantified_events#customer_id` relation
- Adapt the logic to stop relying on customer

feat(event): Link quantified events to organization

---

app/models/event.rb
app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/billable_metrics/aggregations/weighted_sum_service.rb
app/services/events/post_process_service.rb
app/services/events/stores/postgres_store.rb
app/services/fees/estimate_pay_in_advance_service.rb
app/services/subscriptions/dates_service.rb
db/seeds/base.rb
db/seeds/groups.rb
spec/factories/events.rb
spec/graphql/resolvers/events_resolver_spec.rb
spec/models/event_spec.rb
spec/scenarios/create_event_spec.rb
spec/scenarios/customer_usage_spec.rb
spec/scenarios/invoices_spec.rb
spec/scenarios/subscriptions/upgrade_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/charges/pay_in_advance_aggregation_service_spec.rb
spec/services/events/post_process_service_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb
spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
spec/services/quantified_events/create_or_update_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb

On the path for high volume improvements, we need to remove the need for event post-processing and align aggregation logic between Clickhouse and Postgres event stores.
Clickhouse aggregation is (will be) built around on `events#external_subscription_id`, this PRs ensures that all events related logic does not use `events#customer_id` and `events#subscription_id` anymore

feat(event): Use only event external_ids in aggregations

---

app/serializers/v1/fee_serializer.rb
app/services/charges/charge_models/base_service.rb
app/services/charges/charge_models/percentage_service.rb
app/services/fees/charge_service.rb
db/migrate/20231114092154_add_amount_details_to_fees.rb
db/schema.rb
spec/requests/api/v1/fees_spec.rb
spec/serializers/v1/fee_serializer_spec.rb
spec/services/charges/charge_models/percentage_service_spec.rb
spec/services/fees/charge_service_spec.rb

The goal of this PR is to compute amount details for the percentage charge model.
Here is how it will be presented on the invoice:

feat(unit-price): Compute amount details for percentage charge model

---

app/services/fees/subscription_service.rb
spec/scenarios/subscriptions/downgrade_spec.rb

For the first `pay in advance` invoice for `downgraded` subscription we bill full value instead of prorated value. This is not noticed if plan is switched from monthly to monthly or weekly, but if we switch from monthly to yearly; invoice end_date would be equal to next year subscription_at and the number of days is less than one year, so we should not bill full period amount

fix(fees): handle subscription fee for downgrade case with anniversary interval

---

app/services/invoices/calculate_fees_service.rb
db/migrate/20231123095209_add_unique_index_on_invoice_subscriptions.rb
db/schema.rb
spec/services/invoices/calculate_fees_service_spec.rb

We recently end-up with the following bug:
```
The invoice subscription is duplicated, so the same information appears twice on the draft invoice, but the total amount is correct.
If we refresh the invoice, the duplicate invoice subscription disappears (tried with another invoice that had the same issue).
```
To prevent such a situation, we have to enforce:
- The database to make sure a subscription can only be attached once to an invoice (unity at invoice subscription level)
- That the `Invoices::CalculateFeesService` makes sure that each subscription is taken into account only one time

fix(invoice): Prevent duplication of invoice subscriptions

---

app/services/charges/amount_details/range_graduated_service.rb
app/services/charges/charge_models/percentage_service.rb
app/services/charges/charge_models/volume_service.rb
spec/services/charges/amount_details/range_graduated_service_spec.rb
spec/services/charges/charge_models/graduated_service_spec.rb
spec/services/charges/charge_models/percentage_service_spec.rb
spec/services/charges/charge_models/volume_service_spec.rb
spec/services/fees/charge_service_spec.rb

The goal of this PR is to compute amount details for the volume charge model.
Here is how it will be presented on the invoice:

feat(unit-price): Compute amount details for volume charge model

---

app/services/charges/amount_details/range_graduated_percentage_service.rb
app/services/charges/amount_details/range_graduated_service.rb
app/services/charges/charge_models/graduated_percentage_service.rb
app/services/charges/charge_models/percentage_service.rb
spec/services/charges/amount_details/range_graduated_percentage_service_spec.rb
spec/services/charges/charge_models/graduated_percentage_service_spec.rb
spec/services/charges/charge_models/graduated_service_spec.rb
spec/services/charges/charge_models/percentage_service_spec.rb
spec/services/fees/charge_service_spec.rb

The goal of this PR is to compute amount details for the graduated percentage charge model.
Here is how it will be presented on the invoice:

feat(unit-price): Compute amount details for graduated percentage charge model

---

app/services/invoices/payments/adyen_service.rb
spec/services/invoices/payments/adyen_service_spec.rb

Creating adyen payment fails as a result of changing payment method to a card with invalid number.
This PR takes care of not raising an error when that happens.

fix(adyen): Fix adyen service when card is invalid

---

db/migrate/20231123105540_add_fields_for_new_document_numbering.rb
db/schema.rb

Currently Lago does not provide solution for updating document numbers. Also, `per_customer` is the only approach in creating incremental numbers. With this feature, it will be allowed to update one part of document number. Also, it will be possible to choose between `per_customer` and `per_organization` numbering 
This PR adds needed DB fields and migration.

feat(invoice-numbering): Invoice numbering db changes

---

config/environments/test.rb

This PR uses a small trick to speed-up a bit the test suite. It redirects the logs to nowhere rather than to `logs/test.log` reducing the I/O, and keeps only the `fatal` logs

misc: Disable logs in test env

---

app/services/payment_provider_customers/adyen_service.rb
app/services/payment_provider_customers/create_service.rb
spec/services/payment_provider_customers/create_service_spec.rb

Cannot link customers to existing Adyen shoppers
This PR fixes a bug when the checkout url is generated and the customer is linked to a payment provider customer.

fix(checkout-url): Fix when the checkout url should be generated

---

app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/billable_metrics/prorated_aggregations/base_service.rb
app/services/fees/create_pay_in_advance_service.rb
db/migrate/20231017082921_fill_cached_aggregations.rb
spec/scenarios/pay_in_advance_charges_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb

This PR moves events#metadata used for in advance aggregation into a new table named `cached_aggregations` to stop writing into events table as it will become impossible in high usage scenarios

feat(event): Move cached in advance aggregation into a proper model

---

app/services/invoices/payments/adyen_service.rb
spec/services/invoices/payments/adyen_service_spec.rb

Cannot link customers to existing Adyen shoppers
This PR fixes a bug when the shopper reference was incorrectly set to an external id.

fix(adyen): Fix shopper reference

---

app/services/wallets/balance/decrease_service.rb
app/services/wallets/create_interval_wallet_transactions_service.rb
spec/services/wallets/balance/decrease_service_spec.rb
spec/services/wallets/create_interval_wallet_transactions_service_spec.rb

Currently Lago supports only manual wallet transactions. With Recurring transactions feature it will be possible to top-up wallet automatically with threshold or intervals rules.
This PR adds feature for automatic top-up based on threshold rule

feat(recurring-transaction-rules): handle auto top up for threshold rule

---

clock.rb

Currently it is not possible to have automatic wallet top-up in lago
This PR enables cron job definition for interval top-up

fest (wallet-recurring-transactions): add cron job definition for wallet recurring interval top-up

---

app/serializers/v1/fee_serializer.rb
spec/serializers/v1/fee_serializer_spec.rb

The `V1::FeeSerializer` exposes `from_date` and `to_date` attributes.
Today this attribute uses the `from|to_datetime` property store in the `fee#properties` field.
This behavior is okay if the fee is a subscription fee as these attributes are the subscription boundaries, but does not always work for charge fees if the charge and subscription period are not in sync.
This PR fixes the behavior by exposing the `charges_from|to_datetime` when the fee is a charge fee

fix(fee): expose charges boundaries in serializer when charge fee

---

config/application.rb
lib/lago_eu_vat/lago_eu_vat.rb
lib/lago_eu_vat/lago_eu_vat/eu_vat_rates.json
lib/lago_eu_vat/lago_eu_vat/rate.rb
spec/lib/lago_eu_vat/rate_spec.rb

- We have to maintain a list of VAT rates for each EU country.
- Create an internal lib `lago-eu-vat` that defines each rates for EU countries based on an applicable date.
- This list comes from https://github.com/ibericode/vat-rates

feat(taxes): Add EU vat rates lib

---

Gemfile.lock
app/services/billable_metrics/aggregations/latest_service.rb
app/services/events/stores/clickhouse_store.rb
app/services/events/stores/postgres_store.rb
spec/services/events/stores/clickhouse_store_spec.rb
spec/services/events/stores/postgres_store_spec.rb

This PR is part of the high usage event ingestion epic. It follows https://github.com/getlago/lago-api/pull/1476
The objective of the PR is to add specs to clickhouse aggregation and do some cleanup to prepare sum and weighted sum aggregation

feat(event): clean-up event stores and add specs for clickhouse

---

app/controllers/api/v1/subscriptions_controller.rb
spec/requests/api/v1/subscriptions_spec.rb

Subscription update via API is not always targeting the right subscription if multiple subscriptions share the same `external_id` (`active`, `terminated,` `pending`).
The root cause of this issue is that the query to find the subscription to update is taking the first `subscription`, no mater the status.
The current fix, changes the behavior:
- It takes the subscription if only one exists with the `external_id`
- Takes the active one by default is multiple exists
- Takes the pending one if the pending `params` is passed in argument.

fix(subscription): Target active subscription when updating

---

app/services/payment_provider_customers/stripe_service.rb
spec/services/payment_provider_customers/stripe_service_spec.rb

Fix a bug when no PSP is connected to a customer.
Return a successful result when no PSP is connected to a stripe customer, so the worker does not fail.

fix(stripe): Return result when no PSP is connected

---

app/services/billable_metrics/prorated_aggregations/base_service.rb
app/services/billable_metrics/prorated_aggregations/sum_service.rb
app/services/billable_metrics/prorated_aggregations/unique_count_service.rb
spec/scenarios/charge_models/prorated_graduated_spec.rb
spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb

Usually, for graduated prorated charge model, in order to fetch recurring value for each billing period, we take it from the last invoice's fee that belongs to certain charge. Mentioned logic also ignores all events contained in recurring value that are ingested after generation of previous invoice.
If there are not generated invoices yet, we still want to include past events, even if they got ingested after subscription creation with the past timestamp. This PR fixes this case.

fix(graduated-prorated-charge-model): Fix graduated prorated initial state

---

app/services/webhooks/base_service.rb
spec/services/webhooks/base_service_spec.rb

👉 https://getlago.canny.io/developer-experience/p/add-unique-id-of-webhook-message-to-header
For diagnostic reasons, it useful to have the unique key of the webhook be included in the request as a header.
Added the header to the request.

Add unique key of webhook message to header

---

app/services/customers/create_service.rb
app/services/customers/update_service.rb
app/services/payment_provider_customers/adyen_service.rb
app/services/payment_provider_customers/gocardless_service.rb
app/services/payment_provider_customers/stripe_service.rb
app/services/payment_provider_customers/update_service.rb
spec/graphql/mutations/customers/update_spec.rb
spec/services/customers/create_service_spec.rb
spec/services/customers/update_service_spec.rb
spec/services/payment_provider_customers/adyen_service_spec.rb
spec/services/payment_provider_customers/gocardless_service_spec.rb
spec/services/payment_provider_customers/stripe_service_spec.rb
spec/services/payment_provider_customers/update_service_spec.rb

When a customer is updated in Lago, we should update the information sent to Stripe.
This PR updates Stripe customers after their details are updated in Lago.

feat(stripe): Update stripe customer billing address

---

app/services/billable_metrics/aggregation_factory.rb
db/migrate/20231207095229_add_clickhouse_flag_to_organizations.rb
db/schema.rb
spec/services/events/stores/clickhouse_store_spec.rb

This PR is part of the high usage ingestion epic. It follows the refactoring of the aggregation classes to allow clickhouse usage.
This PR add logic to turn on clickhouse usage when:
- Clickhouse is globaly enabled on the application
- Organization has `clickhouse_aggregation` flag turn to `true`
- The aggregation allows clickhouse
- The charge is not payed in advance

feat(event): Enable clickhouse per organization

---

app/graphql/types/fees/object.rb
schema.graphql
schema.json

We're refactoring invoices display in the UI.
Description attribute is not exposed on the fee type.
This PR exposed the fee description in the schema

misc(fee) expose description in type

---

app/services/payment_provider_customers/stripe_service.rb
spec/services/payment_provider_customers/stripe_service_spec.rb

Fix a bug when no PSP is connected to a customer.
Return a successful result when no PSP is connected to a stripe customer, so the stripe API call does not fail with nil api_key.

fix(stripe): Fix stripe update without payment provider

---

app/jobs/clock/finalize_invoices_job.rb
app/jobs/invoices/finalize_job.rb
spec/jobs/clock/finalize_invoices_job_spec.rb
spec/jobs/invoices/finalize_job_spec.rb

Some `Clock::FinalizeInvoicesJob` are failling with a `BaseService::ValidationFailure: Validation errors: {:amount_cents=>["value_is_out_of_range"]}` error.
Since all invoices are processed in a single jobs, it's preventing all invoices from being finalized automatically.
This PR does not fix the root cause of the failed job (we first have to identify with invoice is impacted) but it processing each invoice in its own job, to make sure that a failure on an invoice does not impact the other invoices

fix(invoice): Finalize each invoice in a single job

---

app/services/invoices/update_service.rb
spec/services/invoices/update_service_spec.rb

It should not be possible to update the payment status of a draft invoice
This PR fixes the issue by adding a check to the invoice update service.

fix(invoice): Do not update payment status of draft invoices

---

app/services/fees/create_pay_in_advance_service.rb
spec/scenarios/pay_in_advance_charges_spec.rb

An issue has recently been identified with the pay in advance aggregation and group:
```
Steps to reproduce:
1. Create a billable metric with groups;
2. Create a plan with a charge paid in advance linked to the billable metric;
3. Create a subscription;
4. Send events that don’t include the expected group properties → Lago generates a fee even if the group value is invalid or the expected group key is missing.
```
It is a side effect of the default properties at charge level recently introduced.
This PR changes the check for group on billable metrics by checking the selectable groups rather than the group properties at charge level.

fix(event): Pay in advance with missing or invalid group

---

app/services/invoices/create_pay_in_advance_charge_service.rb
spec/scenarios/pay_in_advance_charges_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/1536
It improves the preivous PR by ensuring that no in advance invoice is created when no fees is created after reception of an event with invalid groups.

Fix in advance group events

---

db/migrate/20231214103653_add_unique_index_on_invoice_sequential_id.rb
db/schema.rb

Invoice table is missing the two indexes to ensure that `sequential_id` and `organization_sequential_id` are unique in their scope (`customer_id` or `organization_id`)
This PR is adding those indexes

fix(invoice): Add missing unique index on invoice sequential ids

---

config/storage.yml

Lago by default looks at a file on disk to load Google Cloud credentials, which is not a convenient option for us right now since our platform only allows putting secret files at a certain path, and Lago hardcodes it as located in the Rails root.
This PR adds a env var to allow overriding this configuration.
Uses the value of the env var `GCS_KEYFILE_JSON_PATH` or falls back if the env var isn't set, falls back to pre-existing behavior.

Add ability to set Google Cloud Storage credentials file path by environment variable

---

app/serializers/v1/fee_serializer.rb
app/views/templates/invoices/v4/_subscription_details.slim
spec/serializers/v1/fee_serializer_spec.rb

In invoice template pay in advance charge fees haven't been grouped correctly and they were also incorrectly calculated in fee serializer
This PR fix both cases

fix: date intervals in invoice template and fee payload

---

app/models/invoice.rb
db/migrate/20231214133638_add_unique_index_on_invoice_organization_sequential_id.rb
db/schema.rb
spec/factories/invoices.rb
spec/models/invoice_spec.rb

Invoice table is missing the index to ensure that `organization_sequential_id` is unique in the scope of the `organization_id`
This PR is adding the index

fix(invoice): Add missing unique index on invoice organization_sequential ids

---

app/controllers/api/v1/credit_notes_controller.rb
app/controllers/api/v1/invoices_controller.rb
app/graphql/mutations/credit_notes/create.rb
app/graphql/mutations/customer_portal/download_invoice.rb
app/graphql/mutations/invoices/download.rb
app/graphql/mutations/invoices/refresh.rb
app/graphql/mutations/invoices/retry_payment.rb
app/graphql/mutations/invoices/update.rb
app/graphql/mutations/invoices/void.rb
app/graphql/resolvers/credit_notes/estimate_resolver.rb
app/graphql/resolvers/invoice_resolver.rb
app/graphql/types/customers/object.rb
app/graphql/types/invoices/status_type_enum.rb
app/models/invoice.rb
app/queries/invoices_query.rb

With the increasing number of invoice generated by the cloud instance of lago, a scalability issue have been identified in the process assigning the `sequential_id` and `organization_sequential_id` to new invoices.
The process uses an database `advisory lock` ensuring that the sequential id is unique and contiguous within the system.
Today, this lock is used in the invoice creation transaction and since this transaction could take time, the lock could be kept for a long time, leading to a lot of `SequenceError`.
The new process will first create the invoice to "reserve" the sequential ID in a short db transaction, to reduce the window of locking and will perform the rest of the computation logic in an other process.
This PR is the first step of this new process, it adds the new invoice …

feat(invoice): Add new generating status to invoices

---

app/models/invoice.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/create_generating_service.rb
spec/services/invoices/create_generating_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/1544
This PR adds a new `Invoices::CreateGeneratingService` service responsible for creating a new invoice no matter its type,in a short transaction to reserve the `sequential_id` and `organization_sequential_id` without impacting the billing process.

feat(invoice): Add invoice create generating service

---

app/models/invoice.rb
spec/models/invoice_spec.rb
spec/scenarios/invoices/invoice_numbering_spec.rb

Currently with each invoice we generate both `sequential_id` and `organization_sequential_id`. With this change we will generate `organization_sequential_id` only when `per_organization` numbering type is defined on the organization level.
This PR generates `organization_sequential_id` only when `per_organization` numbering type is selected.

misc: generate organization sequential id only when this numbering type is selected

---

app/models/invoice.rb
spec/models/invoice_spec.rb
spec/scenarios/invoices/invoice_numbering_spec.rb

We will generate `organization_sequential_id` only when needed. Also, we should make sure that unique `organization_sequential_id` is selected, with providing that we don't end up in infinite loop.

fix: change logic for generating organization sequential id

---

app/services/plans/destroy_service.rb
spec/services/plans/destroy_service_spec.rb

The following issue was reported for the post event validation process:
```
Pending subscriptions not automatically cancelled when deleting plans
Steps to reproduce:
1. Create plan;
2. Assign the plan to a customer to create an active subscription;
3. Assign the same plan to the customer to create a pending subscription (i.e. start date in the future);
4. Delete the plan → only the active subscription is automatically terminated.
Expected behaviour: pending subscriptions should be cancelled when the associated plan is deleted.
```
This PR ensures that all pending subscriptions attached to a deleting plan are being canceled

fix(plan): cancel pending subscription on destroy

---

app/jobs/invoices/create_pay_in_advance_charge_job.rb
app/services/fees/create_pay_in_advance_service.rb
app/services/invoices/create_generating_service.rb
app/services/invoices/create_pay_in_advance_charge_service.rb
spec/jobs/invoices/create_pay_in_advance_charge_job_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb
spec/services/invoices/create_pay_in_advance_charge_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/1546
It makes use of the new `Invoices::CreateGeneratingService` service in the `Invoices::CreatePayInAdvanceChargeService`, to reduce the risk of database locking when generating the `organization_sequential_id`
A logic to prevent duplication of `generating` invoice was also added to the `Invoices::CreatePayInAdvanceChargeJob`

feat(event): Plug invoice create generating invoice for in advance aggregation

---

app/jobs/bill_paid_credit_job.rb
app/services/invoices/paid_credit_service.rb
spec/jobs/bill_paid_credit_job_spec.rb
spec/services/invoices/paid_credit_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/1546
It makes use of the new `Invoices::CreateGeneratingService` service in the `Invoices::PaidCreditService`, to reduce the risk of database locking when generating the `organization_sequential_id`
A logic to prevent duplication of `generating` invoice was also added to the `BillPaidCreditJob`

feat(event): Use generating invoice service for prepaid credit invoices

---

db/migrate/20231219121735_update_last_hour_events_mv_to_version2.rb
db/schema.rb
db/views/last_hour_events_mv_v02.sql
spec/services/events/post_validation_service_spec.rb

The following issue was reported for the post event validation process:
```
events.errors webhook includes valid events
Steps to reproduce:
1. Create a billable metric based on `sum_agg` with groups;
2. Create a plan with a charge for this metric (standard pricing);
3. Start a subscription;
4. Send events with the correct aggregation properties, but negative values;
5. Wait for the `events.errors` webhook → events with negative values are included in the payload (`missing_aggregation_property`).
```
This PR fix the behavior by making sure that events with negative values are not flagged as invalid

fix(events): Negative event values should not be flagged as invalid

---

app/models/adjusted_fee.rb
db/migrate/20231220140936_create_adjusted_fees.rb
db/schema.rb
spec/factories/adjusted_fees.rb

Currently it is not possible to edit units and amounts on draft invoice fees.
This feature adds DB changes need for edit draft invoice feature

feat (invoices): add db changes for edit draft invoice feature

---

app/services/webhooks/base_service.rb

This PR adds the `Errno::ECONNREFUSED` error to the list of webhook delivery errors that should be reprocessed automatically or marked as failed after 6 attempts

fix(webhooks): Handle Errno::ECONNREFUSED error class for retry

---

app/services/webhooks/base_service.rb

This PR adds the `OpenSSL::SSL::SSLError` error to the list of webhook delivery errors that should be reprocessed automatically or marked as failed after 6 attempts

fix(webhooks): Handle OpenSSL::SSL::SSLError error class for retry

---

app/services/subscriptions/dates/monthly_service.rb
spec/scenarios/subscriptions/billing_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/subscriptions/dates/monthly_service_spec.rb

An issue have been reported by a user on anniversary billing of monthly subscription. If the anniversary day of the subscription is on a 31, billing on month having less than 31 days result in wrong boundaries computation and possibly on invoice not generated due to the DB index preventing invoice duplication.
This PR fixes the issue by ensuring the boundaries are correct, matches the subscription identified by the billing job, does not overlap each other and covers every days.
For example, if the anniversary is on 31, when billing on 28 of February 2023, the period must go from 2023-01-31 to 2023-02-27, and the next period will cover 2023-02-28 to 2023-03-30
NOTE: the same issue might exists for quarterly subscriptions and for yearly with anniversary day on the 29 of February. Proper …

fix(invoice): Monthly boundaries with aniversary on the 31st

---

lib/lago_eu_vat/lago_eu_vat/eu_vat_rates.json
spec/lib/lago_eu_vat/rate_spec.rb
spec/services/taxes/auto_generate_service_spec.rb

- GB is no more in the EU taxes area

fix(taxes): Remove GB from EU taxes

---

app/services/invoices/payments/stripe_service.rb
spec/services/invoices/payments/stripe_service_spec.rb

- Do not mark the invoice as failed when the amount is too small for Stripe

feat(stripe): do not mark invoice as failed when amount is too small

---

app/services/credits/applied_coupon_service.rb
spec/services/credits/applied_coupon_service_spec.rb

Recently, an issue has been identified where finalizing an invoice wasn't possible due to a `FloatDomainError`.
That's because `precise_coupons_amount_cents` is trying to be created with a `NaN` value on `Fee` object.

fix: Prevent from having NaN precise_coupons_amount_cents

---

app/serializers/v1/customers/charge_usage_serializer.rb
spec/serializers/v1/customers/charge_usage_serializer_spec.rb

Sorting fee by group name raises an error when fee belongs to no group.
This PR fixes the sorting in `ChargeUsageSerializer`

fix(charge-usage): Fix sorting by group name

---

app/models/adjusted_fee.rb
app/services/adjusted_fees/create_service.rb
db/migrate/20240103125624_add_group_id_to_adjusted_fees.rb
db/schema.rb

Currently it is not possible to manually edit draft invoice.
This id DB-only change where group_id is added to the adjusted fees table, collection needed to persist manual adjustments.

feat(edit-draft-invoice): add group_id to adjusted fees table

---

app/services/subscriptions/dates/monthly_service.rb
app/services/subscriptions/dates/quarterly_service.rb
spec/scenarios/subscriptions/billing_spec.rb
spec/services/subscriptions/dates/quarterly_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/1567 
It applies the same logic to the quarterly billing

fix(invoice): Quarterly boundaries with anniversary on the 31st

---

app/jobs/clock/subscriptions_to_be_terminated_job.rb
spec/jobs/clock/subscriptions_to_be_terminated_job_spec.rb

It's nice to make this configurable. e.g. in my case I want it sent 1 day before ending as well.
By setting env var `LAGO_SUBSCRIPTION_TERMINATION_ALERT_SENT_AT_DAYS` it can be overridden from the defaults.
E.g. `LAGO_SUBSCRIPTION_TERMINATION_ALERT_SENT_AT_DAYS` to `1,30` will cause it be sent 1 and 30 days in advance.

Make it possible to configure when subscription termination alert is sent by setting env var

---

app/services/utils/money_with_precision.rb
app/views/helpers/money_helper.rb

Currently Money gem does not allow setting `default_infinite_precision` property per class instance. 
This PR cleans existing logic with the new class that extends Money. New class should be used only when `default_infinite_precision` is needed to be true. This approach is more safe and does not require setting and resetting property on each usage.

misc: refactor money with precision helper method

---

app/models/subscription.rb
spec/services/subscriptions/create_service_spec.rb

A validation rule is missing for the `billing_time` field on the `Subscription` model, leading to an HTTP `500` error rather than to a `422` when a blank string is provided.
This PR adds the missing presence validation

fix(subscription): Add missing validation rule for billing time

---

app/graphql/types/fees/amount_details/graduated_percentage_range.rb
app/graphql/types/fees/amount_details/graduated_range.rb
app/graphql/types/fees/amount_details/object.rb
app/graphql/types/fees/object.rb
schema.graphql
schema.json

We're adding more context to the invoices. PDF have already been updated using the new `amount_details` attribute's values
This PR maps the new attributes and expose them to GraphQL to have them available for FE

feat(unit-price) add amount_details attribute to Fee object

---

lib/tasks/db.rake

This PR makes sure that every migration task calls the `db:clickhouse:filter` task to filters the password in the clickhouse db schema file when the task is defined.

misc: Improve clickhouse migration filter task

---

app/services/credit_notes/create_service.rb

There are some failed mail deliveries when creating credit note upon subscription termination.
When terminating `pay_in_advance = true` subscription, credit note is created automatically and the email should be delivered to the customer. However, if Mailer job is scheduled before parent transaction has ended, credit note cannot be fetched within the mailer job.

fix(credit-note-email): adapt mail delivery for credit note created

---

app/jobs/clock/refresh_wallets_credits_job.rb
app/jobs/wallets/refresh_credits_job.rb
app/models/organization.rb
app/services/wallets/refresh_credits_service.rb
clock.rb
db/migrate/20240115130517_add_credits_auto_refreshed_to_organizations.rb
db/schema.rb
spec/jobs/clock/refresh_wallets_credits_job_spec.rb
spec/jobs/wallets/refresh_credits_job_spec.rb

https://getlago.canny.io/feature-requests/p/real-time-prepaid-credit-consumption
The objective is to be able to consume credits in “real-time”, credit balance should be directly updated instead of waiting for the invoice creation (at the end of the period, or in some cases, when usage is marked as paid in advance).
- Add `credits_auto_refreshed` to organizations
- Add `Clock::RefreshWalletsCreditsJob` job
- Add `Wallets::RefreshCreditsJob` job
- Add `Wallets::RefreshCreditsService` service

feat(prepaid-credits): Add clock for refreshing wallets credits

---

app/models/billable_metric.rb
app/models/billable_metric_filter.rb
app/models/charge.rb
app/models/charge_filter.rb
app/models/charge_filter_value.rb
app/models/fee.rb
db/migrate/20240111140424_create_billable_metric_filters.rb
db/migrate/20240111151140_create_charge_filters.rb
db/migrate/20240111155133_create_charge_filter_values.rb
db/migrate/20240112091706_add_charge_filter_id_to_fees.rb
db/schema.rb
spec/factories/billable_metric_filters.rb
spec/factories/charge_filter_values.rb
spec/factories/charge_filters.rb
spec/factories/fees.rb
spec/models/billable_metric_filter_spec.rb
spec/models/billable_metric_spec.rb
spec/models/charge_filter_spec.rb
spec/models/charge_filter_value_spec.rb
spec/models/charge_spec.rb

This PR is the first one of the epic. It adds the new `BillableMetricFilter`, `ChargeFilter`, `ChargeFilterValue` models as well as the relations with the `BillableMetric`, `Charge` and `Fee` models

feat(filter): Add new models and relations

---

app/controllers/api/v1/events_controller.rb
app/services/events/create_batch_service.rb
app/services/events/validate_creation_service.rb
db/schema.rb
spec/requests/api/v1/events_spec.rb
spec/services/events/create_batch_service_spec.rb
spec/services/events/validate_creation_service_spec.rb

- We want to support multiple events ingestion with one API call.
- Update the `/events/batch` endpoint that was deprecated
- Add the support of 100 event at a time
- Add a simple validation
- It follows the same process as the single event ingestion

feat(events): Batch Event endpoint

---

app/models/commitment.rb
app/models/commitment/applied_tax.rb
app/models/fee.rb
app/models/plan.rb
db/migrate/20240115094827_create_commitments.rb
db/migrate/20240115102012_create_commitment_applied_taxes.rb
db/schema.rb
schema.graphql
schema.json
spec/factories/commitment_applied_taxes.rb
spec/factories/commitments.rb
spec/models/commitment/applied_tax_spec.rb
spec/models/commitment_spec.rb
spec/models/plan_spec.rb

In this PR we're adding migrations and models.

feat(minimum-spending): Add models

---

app/services/payment_provider_customers/stripe_service.rb
app/services/payment_providers/adyen_service.rb
app/services/payment_providers/gocardless_service.rb
app/services/payment_providers/stripe_service.rb

Webhook handling was broken due to a missing argument for `PaymentProviders::FindService`.
Fix payment provider webhook.
Add missing `payment_provider_type` argument to `PaymentProviders::FindService`

fix(webhook): Fix payment provider webhook.

---

app/views/templates/invoices/v4/_subscription_details.slim

With this Fix several issues are fixed in PDF template:
1. No matter if subscription fee is pay in advance or pay in arrear, we always display first pay in arrear interval and then pay in advance interval. However, subscription fee is always on the top of the group where it depends.
2. Fees are sorted by fee invoice name, but uppercase or downcase should not make difference

fix(invoice-pdf): Refactor invoice PDF template

---

db/migrate/20221114102649_fill_sync_with_provider_field.rb

The initial migration process is failing because of a removed task
This PR fixes the process by removing the task invocation

fix: Initial migration is broken with missing task

---

app/models/plan.rb
app/models/tax.rb
app/serializers/v1/commitment_serializer.rb
app/serializers/v1/plan_serializer.rb
app/serializers/v1/tax_serializer.rb
spec/serializers/v1/commitment_serializer_spec.rb
spec/serializers/v1/plan_serializer_spec.rb

In this PR we're adding serializers.

feat(minimum-spending): Add serializers

---

app/models/billable_metric_filter.rb
app/services/billable_metrics/destroy_service.rb
spec/models/billable_metric_filter_spec.rb
spec/services/billable_metrics/destroy_service_spec.rb

This PR adds the logic to discard all billable metric filters, charge filters and charge filter values when discarding a billable metric

feat(filter): Discard filters with billable metrics
