getlago/lago-api

lib/tasks/signup.rake
scripts/migrate.dev.sh
scripts/migrate.sh
scripts/start.api.sh
scripts/start.migrate.dev.sh
scripts/start.migrate.sh

- Improve migrate script
- Improve signup rake task
- Simplify migrations usage

misc(docker): Improve migrate script

---

app/services/data_exports/csv/invoice_fees.rb
app/services/data_exports/csv/invoices.rb
app/services/data_exports/export_resources_service.rb
app/services/data_exports/process_part_service.rb
spec/services/data_exports/csv/invoice_fees_spec.rb
spec/services/data_exports/csv/invoices_spec.rb

when running sidekiq with high amount of concurrency, the default batch size could result in large amounts of longer running jobs. These could make a worker consume too much memory. 
This PR aims to fine-tune the batch size by reducing it by a factor 5 (so jobs will be faster and consume less memory individually). It will also not keep the entire CSV in memory, but rather use a tempfile.

bug(DataExport) - Decrease batch size for data export & use tempfile

---

app/jobs/data_exports/export_resources_job.rb
spec/jobs/data_exports/export_resources_job_spec.rb

We have multiple batch size constants and I had forgotten this one.

Bug(DataExport) - update DEFAULT_BATCH_SIZE of ExportResourcesJob

---

app/models/integrations/base_integration.rb
app/models/integrations/salesforce_integration.rb
app/models/organization.rb
schema.graphql
schema.json
spec/factories/integrations.rb
spec/models/integrations/base_integration_spec.rb
spec/models/integrations/salesforce_integration_spec.rb
spec/models/organization_spec.rb

👉  https://getlago.canny.io/feature-requests/p/sync-lago-customers-with-salesforce
We need to be able to create a Salesforce integration in Lago and sync Lago customers to Salesforce using this integration details.
This PR adds Salesforce integration model and specs.

feat(salesforce): Add integration models

---

app/services/data_exports/csv/invoice_fees.rb
spec/services/data_exports/csv/invoice_fees_spec.rb

The subscription serializer has quite a bit of overhead if we execute it for every fee. This change removes the reliance on it and duplicates the code into the InvoiceFees class.

feat(DataExport) - don't rely on SubscriptionSerializer for plan code and external id

---

app/services/charges/filter_charge_model_properties_service.rb
spec/services/charges/filter_charge_model_properties_service_spec.rb

In some cases `charge#properties[:custom_properties] `are persisted as a string when the logic expects a `Hash`
This PR makes sure that the properties are always saved as a Hash

fix(custom_aggregation): Ensure custom properties are stored as Hash

---

app/models/integration_customers/base_customer.rb
app/models/integration_customers/salesforce_customer.rb
spec/factories/integration_customers.rb
spec/models/integration_customers/base_customer_spec.rb

This PR enables Salesforce integration by allowing synchronization of external_customer_id from Salesforce to our system.
Example JSON
```
{
"customer": {
"external_id": "external_id",
"name": "name_test",
"firstname": "first name",
"lastname": "last name",
"customer_type": "individual",
"metadata": [],
"taxes": [],
"integration_customers": [
{
"integration_type": "salesforce",
"integration_code": "salesforce",
"external_customer_id": 333333
}
]
}
}
```

feat(Salesforce): Add ability to create salesforce customer 

---

app/config/permissions/role-manager.yml
app/mailers/payment_request_mailer.rb
app/models/payment_request.rb
db/migrate/20241106104515_remove_not_null_constraint_from_email_in_payment_requests.rb
db/schema.rb
spec/mailers/payment_request_mailer_spec.rb
spec/models/payment_request_spec.rb

This change removes the not null constraint on `PaymentRequest#email`.

feat(dunning): Permit creation of payment request without email

---

app/services/integrations/salesforce/create_service.rb
app/services/integrations/salesforce/update_service.rb
spec/services/integrations/salesforce/create_service_spec.rb
spec/services/integrations/salesforce/update_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/sync-lago-customers-with-salesforce
We need to be able to create a Salesforce integration in Lago and sync Lago customers to Salesforce using this integration details.
This PR adds `create` and `update` services to store the integration. They will be used by the GraphQL mutations.

Feat salesforce services

---

app/models/clickhouse/events_raw.rb
app/services/daily_usages/compute_service.rb
app/services/invoices/customer_usage_service.rb
lib/tasks/daily_usages.rake

This PR is part of the Usage Revenue and unit.
Today, Lago does not offer a way to retrieve customer usage with a granularity lower than the billing period (via invoices and fees). On the other end, it is possible to get the current usage for a customer/subscription, but this usage is just a “snapshot” of the usage a the current time. 
This PR adds a rake task to fill the daily usage history for a specific organization

feat(DailyUsage): Add daily_usages:fill_history task

---

app/services/dunning_campaigns/bulk_process_service.rb
app/services/dunning_campaigns/create_service.rb
app/services/dunning_campaigns/update_service.rb
spec/services/dunning_campaigns/create_service_spec.rb
spec/services/dunning_campaigns/update_service_spec.rb

This change resets counter at customer level when set as default a new campaign.

feat(dunning): Stop and reset counters for customers

---

clock.rb
spec/clockwork_spec.rb

This change adds the scheduler to run the ProcessDunningCampaigns job every hour at 45 minute.

feat(dunning): schedule process dunning campaigns jobs every hour at 45'

---

app/queries/subscriptions_query.rb
spec/queries/subscriptions_query_spec.rb

This PR addresses the following issue that was reported by a customer:
```
Problem with the order of results when retrieving subscriptions
When fetching subscriptions via the Lago API (GET /subscriptions) results may be duplicated (i.e. subscription listed on page 1 may also be listed on page 2).
```
The issue appears because subscription are ordered by `started_at asc`, but this value might not be present, leading to an inconsistent ordering.
The subscription order is now changed to `started_at asc nulls last, created_at asc`

fix(subscription): Ensure consistent ordering on the index end-point

---

app/models/customer.rb
spec/models/customer_spec.rb
spec/services/customer_portal/customer_update_service_spec.rb

Validation for valid country code was missing which allows to set invalid value via API
Added missing validation and tests

fix(customer): Add missing validation for shipping country

---

app/services/events/stores/clickhouse/unique_count_query.rb
app/services/events/stores/postgres/unique_count_query.rb

It's sometimes not possible to generate the pdf template of a legacy invoice when it's related to unique count aggregation but without `charges_duration` in the boundaries.
The goal of this PR is to avoid having a deadjob and instead use `1`as the default charges duration.

fix: Ability to generate legacy invoice pdfs without charges duration

---

app/jobs/billable_metrics/delete_events_job.rb
spec/jobs/billable_metrics/delete_events_job_spec.rb

when switching events over to use `external_subscription_id` we forgot to adapt this job to also remove those events.
I decided to also keep the old query in there as it might be that a very old billable metric is removed at some point in the future.

bug(BillableMetric) - BillableMetrics::DeleteEventsJob remove new-style events as well

---

app/jobs/charges/update_job.rb
app/models/charge_filter.rb
app/services/charge_filters/create_or_update_batch_service.rb
app/services/charges/update_service.rb
app/services/plans/update_service.rb
spec/jobs/charges/update_job_spec.rb
spec/models/charge_filter_spec.rb
spec/services/charge_filters/create_or_update_batch_service_spec.rb
spec/services/charges/update_service_spec.rb

This PR supports cascading of charge filters. There are several rules:
- If main attribute that supports cascading is not true -> cascading is disabled
- Charge filter properties are cascaded only if the same properties are not already overridden in the child filter
- We need to ensure that all filters that are specific to the child are not changed in any way (extra filters that don't exist on parent)
- When performing cascading, we are basically at the same time updating parent filters and children filters. However, we need to ensure that logic which handles cascading on children filter uses parent filter attributes **before** update for comparison. That's why we pass parent filter attributes before …

feat(plan-charges-cascading): Support charge filters cascading

---

db/migrate/20241022144437_add_parent_to_charges_from_plan_parent.rb
lib/tasks/tests/seed_plans.rake

We want to populate parent_ids for charges. To define a parent for a charge, we're looking into plan's parent plan and trying to find a charge with matching charge_model and properties. If parent plan has more than one matching charge, we claim that we're not able to define a parent charge
added a migration that:
- goes through children plans and loads their charges and parents with their charges
- for each charge of children plan it tries to select charge from parent plan with matching charge model and charge properties
- if only one matching charge is found, update child charge with parent charge (without callbacks)
added a rake task to seed test data, so we can deploy it onto staging, create any number of plans with children, select to not save parent_ids for their charges, run the …

add migration to set parent_ids to charges

---

db/migrate/20241022144437_add_parent_to_charges_from_plan_parent.rb

at the migration when redefining plan, forgot to specify children on the plan

fix missing children on plan

---

app/jobs/plans/update_amount_job.rb
app/services/plans/update_amount_service.rb
app/services/plans/update_service.rb
spec/jobs/plans/update_amount_job_spec.rb
spec/services/plans/update_amount_service_spec.rb

Plans might receive updates between the cascade being enqueued and the job starting. Although an unlikely edge case, idempotency is important should we enable retries for this job in the future.

improvement(Cascade) - Improve cascade jobs by passing in the expected amount_cents

---

app/jobs/invoices/payments/stripe_create_job.rb
app/jobs/payment_provider_customers/stripe_checkout_url_job.rb
app/jobs/payment_provider_customers/stripe_create_job.rb
app/jobs/payment_requests/payments/stripe_create_job.rb
app/models/payment_provider_customers/base_customer.rb
app/services/credit_notes/refunds/stripe_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/payment_provider_customers/stripe/update_payment_method_service.rb
app/services/payment_provider_customers/stripe_service.rb
app/services/payment_providers/stripe_service.rb
app/services/payment_providers/webhooks/base_service.rb
app/services/payment_providers/webhooks/stripe/charge_dispute_closed_service.rb
app/services/payment_providers/webhooks/stripe/customer_updated_service.rb
app/services/payment_providers/webhooks/stripe/setup_intent_succeeded_service.rb
app/services/payment_requests/payments/stripe_service.rb
spec/fixtures/stripe/customer_updated_event_with_metadata.json
spec/fixtures/stripe/setup_intent_event_with_metadata.json
spec/fixtures/stripe/setup_intent_event_without_customer.json
spec/requests/api/v1/customers_controller_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/credit_notes/refunds/stripe_service_spec.rb
spec/services/invoices/payments/generate_payment_url_service_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/payment_provider_customers/stripe/update_payment_method_service_spec.rb
spec/services/payment_provider_customers/stripe_service_spec.rb
spec/services/payment_providers/stripe_service_spec.rb
spec/services/payment_providers/webhooks/stripe/customer_updated_service_spec.rb
spec/services/payment_providers/webhooks/stripe/setup_intent_succeeded_service_spec.rb
spec/services/payment_requests/payments/generate_payment_url_service_spec.rb
spec/services/payment_requests/payments/stripe_service_spec.rb

This PR is related to the remaining ` PaymentProviders::Stripe::HandleEventJob` dead jobs with `BaseService::NotFoundFailure: stripe_customer_not_found`  error
The main goal of the PR is to refactor the handling of the `setup_intent.succeeded` and `customer.updated` to move the logic in a dedicated webhook service (in the objective of killing the unmaintainable `PaymentProviderCustomers::StripeService`).
It also fixes a case in `setup_intent.succeeded` when the webhook has a `customer` with null value and no Lago ids in the metadata. Since in this specif case the webhook does not target a lago resource, the handling should not raise an error but should be ignored.

misc(stripe): Refact payment method update webhooks

---

app/services/payment_requests/create_service.rb

The goal of this PR is to avoid `ActiveJob::DeserializationError` with `PaymentRequests::Payments::*CreateJob` (and in related webhooks and mailers) when the payment request is enqueued from the `DunningCampaigns::ProcessAttemptService`

fix(payment_request): Avoid deserialization issues

---

app/services/customers/create_service.rb
spec/services/customers/create_service_spec.rb

The goal of this PR is to be able to delete assigned taxes to a customer from the API.

fix: Ability to delete assigned customer taxes from the API

---

app/jobs/invoices/payments/adyen_create_job.rb
app/jobs/invoices/payments/gocardless_create_job.rb
app/jobs/invoices/payments/stripe_create_job.rb
app/services/invoices/payments/adyen_service.rb
app/services/invoices/payments/gocardless_service.rb
app/services/invoices/payments/stripe_service.rb
spec/jobs/invoices/payments/adyen_create_job_spec.rb
spec/jobs/invoices/payments/gocardless_create_job_spec.rb
spec/jobs/invoices/payments/stripe_create_job_spec.rb
spec/services/invoices/payments/adyen_service_spec.rb
spec/services/invoices/payments/gocardless_service_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb

This Pull Request adds the handling of `GoCardlessPro::ValidationError` in the `Invoices::Payments::GocardlessService`. It will update the invoice with the `payment_status = failed` and deliver an error webhook to the account owner.
It also adds the `call` pattern to `Invoices::Payments::AdyenService`, `Invoices::Payments::GocardlessService` and `Invoices::Payments::StripeService`

fix(gocardless): Handle GoCardlessPro::ValidationError when creating payment

---

app/services/payment_provider_customers/adyen_service.rb
spec/services/payment_provider_customers/adyen_service_spec.rb

This Pull Request adds the handling of `Adyen::AuthenticationError` in the `PaymentProviderCustomers::AdyenService#create` method.
It will keep delivering an error webhook, but will not raise the authentication error anymore as nothing can be handled at Lago's level.
NOTE: In a future, the related `PaymentProvider` should marked as failed/disconnected/invalid and the error logged to make it visible in the web application and in the API

fix(adyen): Handle Adyen::AuthenticationError when creating the customer

---

app/jobs/integrations/aggregator/credit_notes/create_job.rb
app/jobs/integrations/aggregator/invoices/create_job.rb
app/jobs/integrations/aggregator/invoices/crm/create_customer_association_job.rb
app/jobs/integrations/aggregator/invoices/crm/create_job.rb
app/jobs/integrations/aggregator/invoices/crm/update_job.rb
app/jobs/integrations/aggregator/payments/create_job.rb
app/jobs/integrations/aggregator/subscriptions/crm/create_customer_association_job.rb
app/jobs/integrations/aggregator/subscriptions/crm/create_job.rb
app/jobs/integrations/aggregator/subscriptions/crm/update_job.rb

While syncing invoices to Netsuite, some invoices were sent twice
Add `unique :until_executed` to aggregator jobs so that the resources are only sync'd once.

fix(netsuite): Aggregator jobs should be unique

---

app/services/plans/update_service.rb
app/services/subscriptions/create_service.rb
app/services/subscriptions/plan_upgrade_service.rb
spec/services/plans/update_service_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/subscriptions/plan_upgrade_service_spec.rb

Currently, when a user updates the subscription fee amount for a plan associated with a pending downgrade (scheduled to activate at the end of the billing period), the system does not treat the pending subscription as an upgrade. As a result, the new subscription is not activated, and the previous one is not terminated.
This change extracts the subscription upgrade logic into a dedicated service, ensuring it can be consistently applied across flows that trigger subscription upgrades. Currently, this includes plan updates and initial subscription creation.
An additional edge case, involving plan subscription overrides, is not addressed in this PR. Handling this scenario introduces extra technical and product complexities that require further consideration.

fix(subscription upgrade): Upgrade subscriptions previously considered downgrade on amount increase

---

app/models/fee.rb
app/services/fees/create_pay_in_advance_service.rb
spec/models/fee_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb

grouped_by can be stored on charge filters. This PR caches the properties so we're using the correct ones in the service.

Bug(PayInAdvanceFee) - fix grouped_by logic for Fees::CreatePayInAdvanceService

---

app/services/data_exports/combine_parts_service.rb

Current key generation does not allow to re-run service if there's any failure after file being attached because of unique constraint on active storage blobs table
Add salt to key generation to satisfy uniqueness during repeated runs

fix(data-export): File key uniqueness

---

app/services/integrations/aggregator/credit_notes/create_service.rb
app/services/integrations/aggregator/credit_notes/payloads/base_payload.rb
app/services/integrations/aggregator/invoices/create_service.rb
app/services/integrations/aggregator/invoices/crm/create_service.rb
app/services/integrations/aggregator/payments/create_service.rb
app/services/integrations/aggregator/payments/payloads/base_payload.rb
spec/services/integrations/aggregator/credit_notes/create_service_spec.rb
spec/services/integrations/aggregator/invoices/create_service_spec.rb
spec/services/integrations/aggregator/payments/create_service_spec.rb

When the Netsuite jobs that create invoices, credit note and paymetns were enqueued at the same time, they sometimes created duplicate integration resources.
This PR fixes this issue by checking if the resource already exists in our DB.

fix(netsuite): Fix possible duplicate integration resources creation

---

app/models/payment_providers/stripe_provider.rb
app/services/invoices/payments/stripe_service.rb
app/services/payment_providers/stripe/handle_event_service.rb
app/services/payment_requests/payments/stripe_service.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/payment_providers/stripe/handle_event_service_spec.rb
spec/services/payment_requests/payments/stripe_service_spec.rb

Some `PaymentProviders::Stripe::HandleEventJob` with 'payment_intent.payment_failed' or 'payment_intent.succeeded' event type are failing with `BaseService::NotFoundFailure - stripe_payment_not_found`.
The webhook contains metadata of lago's invoices but the related `Payment` cannot be found in the database. It is probably because the job creating the stripe payment was killed allong with the worker running it under heavy load.
This PR changes the logic to re-create the `Payment` record when missing using the data from the webhook object. It will allow to update the `invoice.payment_status` accordingly

fix(stripe): Handle missing payment

---

app/models/dunning_campaign_threshold.rb
db/migrate/20241118165935_add_deleted_at_to_dunning_campaign_thresholds.rb
db/migrate/20241119110219_update_unique_index_on_dunning_campaign_thresholds.rb
db/schema.rb
spec/models/dunning_campaign_threshold_spec.rb

This change adds capabilities to soft delete dunning campaign thresholds

feat(dunning): Add deleted_at to dunning campaign threshold

---

app/models/dunning_campaign.rb
db/migrate/20241120085057_add_deleted_at_to_dunning_campaigns.rb
db/migrate/20241120090305_update_unique_index_on_dunning_campaigns.rb
db/schema.rb
spec/models/dunning_campaign_spec.rb

This change adds capabilities to soft delete dunning campaigns

feat(dunning): Allow soft deletion on dunning campaign

---

app/models/customer.rb
db/migrate/20241119114948_add_dunning_campaign_completed_to_customers.rb
db/schema.rb

This change adds `completed_dunning_campaign` boolean flag to customers. The goal of this flag is to identify when a customer has exhausted all dunning campaign attemps and exclude it from further dunning campaign executions until one of its payment requests is being paid, the customer get a custom campaign assigned, or other edge cases...

feat(dunning): Add flag to customers when completed a dunning campaign

---

app/graphql/types/adjusted_fees/create_input.rb
app/models/adjusted_fee.rb
app/services/adjusted_fees/create_service.rb
app/services/fees/init_from_adjusted_charge_fee_service.rb
app/services/fees/subscription_service.rb
db/migrate/20241113181629_add_precise_amount_cents_to_adjusted_fee.rb
db/migrate/20241118103032_fulfill_adjusted_fee_unit_precise_amount_cents.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/mutations/adjusted_fees/create_spec.rb
spec/scenarios/invoices/adjusted_charge_fees_spec.rb
spec/scenarios/invoices/adjusted_subscription_fees_spec.rb
spec/scenarios/invoices/invoices_spec.rb
spec/services/adjusted_fees/create_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/init_from_adjusted_charge_fee_service_spec.rb
spec/services/fees/subscription_service_spec.rb

currently when an organization is editing fee, they can enter only 2 digits after the comma for new unit_amount. Instead, they want to be able to enter as many digits as they want as it already works for unit amount in plans.
Added unit_precise_amount_cents to adjusted fee;
Added this new field into consideration when creating fees;
Added a migration to populate unit_precise_amount_cents for currently existing adjusted fees

Fix: allow to edit fees with more than 2 decimal price

---

app/models/daily_usage.rb
app/serializers/v1/customers/charge_usage_serializer.rb
app/services/base_service.rb
app/services/daily_usages/compute_diff_service.rb
app/services/daily_usages/compute_service.rb
db/migrate/20241108103702_add_usage_diff_to_daily_usages.rb
db/schema.rb
lib/tasks/daily_usages.rake
spec/requests/api/v1/customers/usage_controller_spec.rb
spec/scenarios/charge_models/dynamic_spec.rb
spec/serializers/v1/customers/charge_usage_serializer_spec.rb
spec/serializers/v1/customers/usage_serializer_spec.rb
spec/services/daily_usages/compute_diff_service_spec.rb
spec/services/daily_usages/compute_service_spec.rb

This PR is part of the Usage Revenue and unit.
Today, Lago does not offer a way to retrieve customer usage with a granularity lower than the billing period (via invoices and fees). On the other end, it is possible to get the current usage for a customer/subscription, but this usage is just a “snapshot” of the usage a the current time. 
This PR adds a new `usage_diff` field to the `DailyUsage`. The logic to compute the daily usage is also updated to fill this new field.

feat(daily_usage): Compute and store usage_diff

---

Gemfile.lock
app/services/applied_coupons/lock_service.rb
app/services/credits/applied_coupon_service.rb
app/services/credits/applied_coupons_service.rb
spec/services/applied_coupons/lock_service_spec.rb
spec/services/credits/applied_coupon_service_spec.rb

Coupon deduction was not resistant to concurrency issues. This PR introduces safe-guards so coupons are applied correctly.

bug(Coupon) - Use advisory lock to make sure coupon application is correct

---

Gemfile
app/services/daily_usages/fill_history_service.rb
lib/tasks/daily_usages.rake

Related to https://github.com/getlago/lago-api/pull/2843
We missed to move the `require "timecop"` :facepalm: ...

misc: Add missing require in DailyUsages::FillHistoryService

---

app/controllers/api/v1/billable_metrics_controller.rb
app/serializers/v1/billable_metric_serializer.rb
spec/serializers/v1/billable_metric_serializer_spec.rb

Related to https://github.com/getlago/lago-openapi/pull/303
This PR updates the `V1::BillableMetricSerializer` to makes `active_subscriptions_count`, `draft_invoices_count`, and `plans_count` optional by using `includes: %[counters]`

misc: Deprecate counters at billable metric index level

---

app/services/fees/create_pay_in_advance_service.rb
app/services/fees/one_off_service.rb
app/services/integrations/aggregator/taxes/base_service.rb
app/services/integrations/aggregator/taxes/invoices/payload.rb
app/services/invoices/compute_amounts_from_fees.rb
app/services/invoices/customer_usage_service.rb
spec/graphql/mutations/invoices/retry_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb
spec/services/fees/one_off_service_spec.rb
spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb
spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/compute_amounts_from_fees_spec.rb
spec/services/invoices/create_one_off_service_spec.rb
spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
spec/services/invoices/customer_usage_service_spec.rb
spec/services/invoices/progressive_billing_service_spec.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
spec/services/invoices/refresh_draft_service_spec.rb
spec/services/invoices/retry_service_spec.rb
spec/services/invoices/subscription_service_spec.rb

We faced a bug when an invoice has more than one fee related to the same item_id, as in anrok payload we're using the item_id to identify line_item.
as result, we might have more than one line_item with the same item_id - one of them with 0 tax, as fee amount_cents is 0, one with more than 0, as fee amount_cents is not 0, and we can't correctly assign the returned line_item with taxes to the right fee.
when sending a payload to Anrok, send fee.id instead of item_id, as fee_id is uniquely identifies the line_item

Fix(anrok): Taxes not fully applied

---

spec/spec_helper.rb

RSpec::Core provides metadata integration for aggregating failures by default on RSpec.
Why not activating it, instead of putting everywhere `:aggregate_failures` :) 
The legacy calls could be removed later.

misc: Activate aggregate_failures by default on specs

---

app/models/customer.rb
app/queries/customers_query.rb
spec/queries/customers_query_spec.rb

We're allowing searching on name, firstname, lastname.
we've forgotten legal_name. This PR fixes that.

bug(CustomerQuery) - Allow searching on legal_name

---

app/services/dunning_campaigns/update_service.rb
spec/services/dunning_campaigns/update_service_spec.rb

This change enables UpdateService to update dunning campaign data and its thresholds.

feat(dunning): extend DunningCampaigns::UpdateService update all fields

---

app/services/plans/update_amount_service.rb
spec/services/plans/update_amount_service_spec.rb

in `cascade_subscription_fee_update` we call `Plans::UpdateAmountJob`. This job should deal with pending subscriptions similar to how the `Plans::UpdateService` does it. (see `process_downgrade`|`pending_subscriptions`)
This changes handles subscription upgrades when plan amount_cents changes because of cascading from parent plan and there are pending subscriptions.

fix: Plans::UpdateAmountService handle pending subscription upgrades

---

app/models/customer.rb
app/models/dunning_campaign.rb
app/models/organization.rb
app/services/dunning_campaigns/create_service.rb
app/services/dunning_campaigns/destroy_service.rb
app/services/dunning_campaigns/update_service.rb
spec/models/dunning_campaign_spec.rb
spec/models/organization_spec.rb
spec/services/dunning_campaigns/destroy_service_spec.rb

This change adds the ability to reset last attempt on customers when deleting a dunning campaign.

feat(dunning): Reset customers last attempt on dunning campaign deletion

---

app/jobs/fees/create_pay_in_advance_job.rb
app/jobs/integrations/aggregator/credit_notes/create_job.rb
app/jobs/integrations/aggregator/invoices/create_job.rb
app/jobs/integrations/aggregator/invoices/crm/create_customer_association_job.rb
app/jobs/integrations/aggregator/invoices/crm/create_job.rb
app/jobs/integrations/aggregator/invoices/crm/update_job.rb
app/jobs/integrations/aggregator/payments/create_job.rb
app/jobs/integrations/aggregator/subscriptions/crm/create_customer_association_job.rb
app/jobs/integrations/aggregator/subscriptions/crm/create_job.rb
app/jobs/integrations/aggregator/subscriptions/crm/update_job.rb
app/jobs/invoices/create_pay_in_advance_charge_job.rb

This reverts commit 0d43376467dad3ef2035599bae6d69011b4a71d2.
There is a activejob-uniqueness bug that does not enqueue integration jobs.
when using named arguments

Revert "fix(netsuite): Aggregator jobs should be unique (#2818)"

---

app/models/dunning_campaign_threshold.rb
app/services/dunning_campaigns/update_service.rb
spec/models/dunning_campaign_threshold_spec.rb
spec/services/dunning_campaigns/update_service_spec.rb

When a dunning campaign threshold changes, it resets customers last_dunning_campaign_attempt fields with the updated campaign applicable (through direct association or falling back to it through the organization default) when the thresholds does not match anymore (currency and/or amount_cents changed or deletion of the threshold).

feat(dunning): reset customer dunning campaign last attempt data on threshold changes

---

app/models/fee.rb
app/services/fees/add_on_service.rb
app/services/fees/charge_service.rb
app/services/fees/commitments/minimum/create_service.rb
app/services/fees/create_pay_in_advance_service.rb
app/services/fees/init_from_adjusted_charge_fee_service.rb
app/services/fees/one_off_service.rb
app/services/fees/paid_credit_service.rb
app/services/fees/subscription_service.rb
db/migrate/20241122104537_add_organization_id_to_fees.rb
db/migrate/20241122105133_add_organization_id_fk_to_fees.rb
db/migrate/20241122105327_validate_fees_organizations_foreign_key.rb
db/schema.rb
spec/factories/fees.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb

The `from_organization` scope on Fee is rather slow and produces queries that can't be optimized further. To simplify accessing these we're adding `organization_id` column to Fee.
This is the first PR, in which we add the migration and adapt the code to start filling in the organization_id.
Next up: 
- backfilling
- marking the column `not_null`

Add organization_id to Fee

---

app/jobs/billable_metrics/delete_events_job.rb
spec/factories/clickhouse/events_enriched.rb
spec/jobs/billable_metrics/delete_events_job_spec.rb

We recently fixed the case where events were not correctly removed for new-style subscriptions (using `external_subscription_id`). We forgot about clickhouse events, this PR fixes that and will also remove those.

Bug(Events) - make sure to cleanup clickhouse events after billable metric removal

---

app/models/api_key.rb
app/models/organization.rb
config/locales/en.yml
db/migrate/20241120094557_add_permissions_to_api_keys.rb
db/schema.rb
schema.graphql
schema.json
spec/models/api_key_spec.rb

Preparation step for implementing endpoint permissions for api keys.
Define permissions on each api key, fill with default access rights.

feat(api-key-management): Add permissions to the ApiKey

---

app/services/dunning_campaigns/bulk_process_service.rb
spec/services/dunning_campaigns/bulk_process_service_spec.rb

On dunning campaign execution skip customers with dunning campaign completed flag set to true.

feat(dunning): Dunning Campaign processing skip customers completed

---

app/services/customers/update_service.rb
spec/services/customers/update_service_spec.rb

When customer excluded_from_dunning_campaign or
applied_dunning_campaign_id changes reset dunning_campaign_completed to false along with the dunning campaign last attempt counter and timestamp.

feat(dunning): flag customers as dunning campaign completed

---

app/models/charge.rb
db/migrate/20241126141853_update_index_charges_on_billable_metric_id.rb
db/schema.rb

For performance reason, we want to change the existing index `index_charges_on_billable_metric_id` to take into consideration `where deleted_at is null`.
Indeed, when fetching a single subscription, the request is now using this index.

misc: Add deleted_at to index_charges_on_billable_metric_id

---

app/models/dunning_campaign.rb
app/models/payment_request.rb
app/services/dunning_campaigns/process_attempt_service.rb
app/services/payment_requests/create_service.rb
db/migrate/20241126103448_add_dunning_campaign_id_to_payment_requests.rb
db/schema.rb
spec/models/dunning_campaign_spec.rb
spec/models/payment_request_spec.rb
spec/services/dunning_campaigns/process_attempt_service_spec.rb
spec/services/payment_requests/create_service_spec.rb

The goal of this PR is to assign the dunning campaign when creating a payment request via the auto dunning flow.

feat(dunning): Assign dunning campaign when creating a payment request

---

app/services/invoices/update_service.rb
spec/services/invoices/update_service_spec.rb

When an invoice included in a payment request that belongs to a dunning campaign is payment succeeded, this change resets the customer dunning campaign status counters (completed, last attempt number and last attempt timestamp).

feat(dunning): reset customer dunning counters on invoice updates

---

app/services/payment_requests/payments/adyen_service.rb
app/services/payment_requests/payments/gocardless_service.rb
app/services/payment_requests/payments/stripe_service.rb
spec/services/payment_requests/payments/adyen_service_spec.rb
spec/services/payment_requests/payments/gocardless_service_spec.rb
spec/services/payment_requests/payments/stripe_service_spec.rb

Reset customer dunning campaign status (last attempt count, last attempt timestamp and completed status) on payment request succeeded payment status response.

feat(dunning): reset customer dunning campaign status on payment request succeeded payment status

---

db/migrate/20241126102447_set_dunning_campaign_completed_to_customers.rb

The goal of this PR is to set `dunning_campaign_completed: true` to customers when existing dunning campaigns are considered as completed.

feat(dunning): Populate dunning_campaign_completed on existing customers

---

app/serializers/v1/tax_serializer.rb
spec/serializers/v1/tax_serializer_spec.rb

- `count` on API serializer is causing a major performance issue

hotfix(taxes): Remove charges count from taxes serializer

---

app/services/fees/one_off_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/progressive_billing_service.rb
app/services/invoices/retry_service.rb
spec/fixtures/integration_aggregator/taxes/invoices/api_limit_response.json
spec/services/fees/one_off_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/progressive_billing_service_spec.rb
spec/services/invoices/retry_service_spec.rb

In case of Anrok validation error, Lago does not store more details
This PR adds more details to the error_details collection so that issues can be reproduced more easily

misc: extend tax error details for validationError

---

app/models/customer.rb
app/services/customers/update_service.rb
app/services/dunning_campaigns/process_attempt_service.rb
app/services/invoices/update_service.rb
app/services/payment_requests/payments/adyen_service.rb
app/services/payment_requests/payments/gocardless_service.rb
spec/models/customer_spec.rb
spec/services/dunning_campaigns/process_attempt_service_spec.rb

Flag customers as dunning campaign completed on last attempt execution, also check the completed flag instead of the campaign max attempts as execution exit condition.
Also, extracts code to reset customer dunning campaign status fields to be reused.

feat(dunning): flag customer as dunning campaign completed on last attempt execution

---

app/services/integration_customers/factory.rb
app/services/integration_customers/salesforce_service.rb
spec/services/integration_customers/factory_spec.rb
spec/services/integration_customers/salesforce_service_spec.rb

Add the ability to create a new salesforce customer without passing the external customer id so it can be filled later by the salesforce integration

feat(salesforce): Add create customer without external id

---

app/models/customer.rb
app/models/dunning_campaign.rb
app/models/organization.rb
app/services/dunning_campaigns/bulk_process_service.rb
app/services/dunning_campaigns/process_attempt_service.rb
app/services/dunning_campaigns/update_service.rb
app/services/payment_requests/payments/stripe_service.rb
db/migrate/20241128091634_remove_dunning_campaign_completed_from_customers.rb
db/schema.rb
spec/models/customer_spec.rb
spec/models/dunning_campaign_spec.rb
spec/models/organization_spec.rb
spec/services/customers/update_service_spec.rb
spec/services/dunning_campaigns/bulk_process_service_spec.rb
spec/services/dunning_campaigns/process_attempt_service_spec.rb
spec/services/dunning_campaigns/update_service_spec.rb
spec/services/invoices/update_service_spec.rb
spec/services/payment_requests/payments/adyen_service_spec.rb
spec/services/payment_requests/payments/gocardless_service_spec.rb
spec/services/payment_requests/payments/stripe_service_spec.rb

The goal of this PR is to remove the flag `dunning_campaign_completed` on customers.
We don't need this complexity and prefer retrying the dunning process when number of attempts is changed.

feat(dunning): Remove dunning_campaign_completed flag

---

app/services/integrations/aggregator/invoices/payloads/netsuite.rb
spec/services/integrations/aggregator/invoices/create_service_spec.rb
spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb

When we calculate the line item price with big decimals, Netsuite rounds it to 8 decimal places.
And in that case the Netsuite prices are different to what is saved in Lago.
Add `amount` attribute to Netsuite payload with precalculated price.

fix(netsuite): Add amount to invoice line items

---

app/jobs/clock/retry_failed_invoices_job.rb
app/services/integrations/aggregator/taxes/base_service.rb
clock.rb
spec/jobs/clock/retry_failed_invoices_job_spec.rb

Failed invoices due to api limit should be auto retried
This PR uses error detail extension (https://github.com/getlago/lago-api/pull/2878) to catch all failed invoices due to API limit error and auto-retry them.
This is first phase for covering api limit errors. Later, we will turn tax integration to be async and implement throttling mechanism for it.

feat (tax-integrations): auto retry failed invoice due to api limit

---

app/services/plans/update_service.rb

We started having errors in sidekiq that charge cannot be saved because parent_id charge does not exist in the database
Wrap cascade_charge_creation in after_commit block

Fix: missing parent charge in the database

---

app/services/integrations/aggregator/invoices/payloads/netsuite.rb

Netsuite cannot accept more than 15 decimal places in invoice line item quantity
Round the line item quantity in netsuite invoice payload.

fix(netsuite): Fix quantity sent to netsuite

---

app/queries/events_query.rb

We've got an index on (organization_id, timestamp). I don't think there's much downside to ordering by timestamp rather than created_at.

perf(EventsApi) - order events by timestamp rather than created_at

---

app/graphql/types/credit_notes/object.rb

The GraphqlController#execute method was throwing a NameError due to an uninitialized constant Types::Integrations::BaseIntegration. This issue affected the production environment 
The root cause was an incorrect namespace resolution for Integrations::BaseIntegration::INTEGRATION_ACCOUNTING_TYPES in the integration_syncable method for credit notes.

feat: rubocop

---

lib/tasks/organizations.rake

Sometimes it is needed to "clear" organization's data. This task will allow support engineer to delete all invoices, events and credit notes of the provided organization

Feat: clear invoice data rake task

---

app/services/customers/create_service.rb
spec/graphql/mutations/integrations/salesforce/create_spec.rb
spec/graphql/mutations/integrations/salesforce/update_spec.rb

This PR makes sure that `ActiveRecord::RecordNotUnique` are catched correctly when calling `POST /api/v1/customers` API endpoint and respond with a proper `HTTP 422` rather than with today's `HTTP 500`
Sidenote: It also removes `pp` from some spec files

fix(customer): Catch ActiveRecord::RecordNotUnique when creating with API

---

Gemfile.lock
app/services/customers/create_service.rb
spec/services/customers/create_service_spec.rb

`customer.created` webhook was called when updating a customer via API instead of `customer.updated`.
This PR fixes the issue and calls the correct `customer.updated` webhook.

fix(customer): Fix update customer webhook

---

app/jobs/clock/finalize_invoices_job.rb
app/jobs/invoices/finalize_job.rb
app/services/credits/applied_prepaid_credit_service.rb
spec/services/credits/applied_prepaid_credit_service_spec.rb

Prepaid credits should be applied on invoice only once. This condition should be basic check in the depending service.
Currently we are just returning result instead of proper error for the described case, which leads to errors that are hard to track

fix: update applied prepaid credits service exit case

---

app/models/customer.rb
db/migrate/20241122111534_create_invoice_custom_sections.rb
db/migrate/20241122134430_create_invoice_custom_section_selections.rb
db/migrate/20241122140603_create_applied_invoice_custom_sections.rb
db/migrate/20241122141158_add_skip_invoice_custom_sections_to_customers.rb
db/schema.rb

In order to save invoice custom sections, we need to make some changes in the DB
Added
- invoice_custom_sections
- invoice_custom_section_selections
- applied_invoice_custom_sections
Updated
- Customer

Feat invoice custom section migrations

---

app/serializers/v1/billable_metric_serializer.rb
app/serializers/v1/plan_serializer.rb
app/serializers/v1/tax_serializer.rb
spec/serializers/v1/billable_metric_serializer_spec.rb
spec/serializers/v1/commitment_serializer_spec.rb
spec/serializers/v1/plan_serializer_spec.rb

These count queries are hard to optimize and executed way too often. We're going to start returning zero so we don't break API clients, but these fields will be removed.

perf(API) - Set all _count values in API to zero

---

app/models/applied_invoice_custom_section.rb
app/models/customer.rb
app/models/invoice.rb
app/models/invoice_custom_section.rb
app/models/invoice_custom_section_selection.rb
app/models/organization.rb
spec/factories/applied_invoice_custom_sections.rb
spec/factories/customers.rb
spec/factories/invoice_custom_sections.rb
spec/factories/organizations.rb
spec/models/applied_invoice_custom_section_spec.rb
spec/models/customer_spec.rb
spec/models/invoice_custom_section_spec.rb
spec/models/organization_spec.rb

In order to save invoice custom sections, we need to make create new models related to the new tables
Added 
- InvoiceCustomSection
- AppliedInvoiceCustomSection
- InvoiceCustomSectionSelection
Updated
- Organization
- Customer

Feat invoice custom sections -  models updates

---

spec/requests/api/v1/add_ons_controller_spec.rb
spec/requests/api/v1/analytics/gross_revenues_controller_spec.rb
spec/requests/api/v1/analytics/invoice_collections_controller_spec.rb
spec/requests/api/v1/analytics/invoiced_usages_controller_spec.rb
spec/requests/api/v1/analytics/mrrs_controller_spec.rb
spec/requests/api/v1/analytics/overdue_balances_controller_spec.rb
spec/requests/api/v1/applied_coupons_controller_spec.rb
spec/requests/api/v1/billable_metrics_controller_spec.rb
spec/requests/api/v1/coupons_controller_spec.rb
spec/requests/api/v1/credit_notes_controller_spec.rb
spec/requests/api/v1/customers/applied_coupons_controller_spec.rb
spec/requests/api/v1/customers/usage_controller_spec.rb
spec/requests/api/v1/customers_controller_spec.rb
spec/requests/api/v1/events_controller_spec.rb
spec/requests/api/v1/fees_controller_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/requests/api/v1/lifetime_usages_controller_spec.rb
spec/requests/api/v1/organizations_controller_spec.rb
spec/requests/api/v1/payment_requests_controller_spec.rb
spec/requests/api/v1/plans_controller_spec.rb
spec/requests/api/v1/subscriptions_controller_spec.rb
spec/requests/api/v1/taxes_controller_spec.rb
spec/requests/api/v1/wallet_transactions_controller_spec.rb
spec/requests/api/v1/wallets_controller_spec.rb
spec/requests/api/v1/webhook_endpoints_controller_spec.rb
spec/requests/api/v1/webhooks_controller_spec.rb

Extracting request tests refactoring into dedicated PR for easier review.
Use `subject` in request tests.
Add few missing tests.
Use `let!` where possible.
Reduce amount of `entity1` like variable names.

misc(api-key-management): Refactor request tests

---

app/serializers/v1/fee_serializer.rb
spec/serializers/v1/fee_serializer_spec.rb

In some scenarios, there was no `event_transaction_id` attached in fee serializer
This PR simplifies method in serializer and ensure presence of `event_transaction_id` value

fix: adjust fee serializer for pay in advance fees

---

app/graphql/mutations/api_keys/update.rb
spec/graphql/mutations/api_keys/update_spec.rb

Fix editing API key when 'api_permissions' add-on is not enabled.
Avoid setting permissions to `nil` if it's no passed to prevent nullifying of the value.

fix(api-key-management): API key editing

---

app/models/applied_coupon.rb
app/services/credit_notes/validate_item_service.rb

Credit Note Item model allows amount_cents to be 0; Because of roundings, applied_coupon.amount_cents can also be 0

Fix: greater_than usage

---

app/services/daily_usages/fill_history_service.rb

This PR is a fix for the daily usage escape condition, making sure that we are not duplicating values when running the task to fill usage history

fix(daily_usage): Fix escape condition for daily_usage history

---

app/services/integrations/aggregator/taxes/base_service.rb

When Anrok's requests limit is reached, they might send us another form of the error message.
As a temporary fix, we'll save this another message as first API limit message

Fix(tax-integrations): another error received from Anrok

---

app/models/customer.rb
app/models/wallet.rb
app/services/events/post_process_service.rb
app/services/invoices/refresh_draft_service.rb
app/services/invoices/subscription_service.rb
app/services/wallets/balance/update_ongoing_service.rb
spec/models/customer_spec.rb
spec/services/invoices/subscription_service_spec.rb
spec/services/wallets/balance/update_ongoing_service_spec.rb

The goal of this PR is to include **draft invoices** in the **ongoing** balance.

fix(wallet): Include draft invoices inside wallet's ongoing balance

---

app/models/webhook_endpoint.rb
spec/models/webhook_endpoint_spec.rb

The goal of this PR is to improve performance when deleting a webhook endpoint associated to several webhooks.

misc: Delete webhooks directly from the database when deleting webhook endpoint

---

app/models/integration_resource.rb
app/services/integrations/aggregator/invoices/create_service.rb

We miss some information in the logs when debugging the extrnal integrations.
This PR add logs to integration invoice create service.

misc(logs): Add logs to integration invoice create service

---

app/models/charge.rb
app/models/fee.rb
app/views/templates/invoices/v4/charge.slim
spec/models/charge_spec.rb
spec/models/fee_spec.rb

When charge has filters, fee details are not displayed for percentage charge model in the invoice PDF
This PR ensures that fee details are properly displayed in the invoice PDF

fix: update regrouped invoice pdf with percentage details on fees

---

app/services/invoices/subscription_service.rb
spec/services/invoices/subscription_service_spec.rb

This PR makes sure that the job to compute the daily usage from a periodic or a termination invoice is enqueued using the `subscriptions` rather than the `invoice_subscriptions` records

fix(daily_usage): Compute usage from periodic or terminating invoices

---

app/services/invoices/refresh_draft_service.rb
spec/services/invoices/refresh_draft_service_spec.rb

When we're refreshing the invoice, we should reset the progressive_billing_amount as well

Fix: progressive billing amount cents reset when refresh inovice

---

app/services/daily_usages/fill_from_invoice_service.rb

This PR is a fix for `undefined method charge_model for nil` raised in `DailyUsages::FillFromInvoiceJob`.
The issue is raised because the job was not excluding subscription fees when serializing the usage data for the `DailyUsage` computation.

fix(daily_usage): targets only charge fees

---

app/services/integrations/aggregator/invoices/create_service.rb

This PR reverts changes in https://github.com/getlago/lago-api/pull/2940
It leaves just the logger info.

misc(logging): Refactor logging of integration invoice.

---

app/models/metadata/customer_metadata.rb
app/services/validators/metadata_validator.rb
spec/models/metadata/customer_metadata_spec.rb

increased customer and  wallet transactions metadata value size limit to 100

feat: Increase metadata max value length

---

app/services/integrations/aggregator/invoices/payloads/netsuite.rb
spec/services/integrations/aggregator/invoices/create_service_spec.rb
spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb

Add `custcol_service_period_date_from` and `custcol_service_period_date_to` attributes to the invoice payload for fee lines items.
Coupons, credits and credit notes will not contain these fields.

feat(netsuite): Add fees period dates to invoice payload

---

app/views/templates/invoices/v4/charge.slim

Add `succeeded_at` on PDF where pay in advance properties are displayed
Add `succeeded_at` so that PDF matched UI in regrouped fee invoice

fix (pdf): add succeeded at on percentage charge details in pdf

---

app/models/invoice.rb
app/services/customers/update_invoice_grace_period_service.rb
app/services/organizations/update_invoice_grace_period_service.rb
spec/jobs/clock/finalize_invoices_job_spec.rb
spec/models/invoice_spec.rb
spec/services/customers/update_invoice_grace_period_service_spec.rb
spec/services/organizations/update_invoice_grace_period_service_spec.rb
spec/services/organizations/update_service_spec.rb

When billing job is triggered in the past, `issuing_date` is not set correctly.
`issuing_date` is set based on the billing job timestamp and grace period.
However, when we check if it is correct time to finalize invoice or in services that set grace period we calculate issuing date again based on `invoice.created_at`. If `invoice.created_at` is different than billing day timestamp, we could end-up with invalid issuing date. This especially affects when the draft invoice is finalized.
@vincent-pochet @rsempe Can you see any downside of this approach?

fix (grace_period): refactor how issuing date is set

---

Gemfile
Gemfile.lock
app/mailers/data_export_mailer.rb
app/models/data_export.rb
app/services/data_exports/csv/base_csv_service.rb
app/services/data_exports/csv/invoice_fees.rb
app/services/data_exports/csv/invoices.rb
spec/factories/data_exports.rb
spec/mailers/data_export_mailer_spec.rb
spec/models/data_export_spec.rb
spec/rails_helper.rb

Refactor and preparations to expand existing data export solution with new export types.
Extract common logic into a new `BaseCsvService`.
Refactor tests.

misc(export-credit-notes): Refactor services and tests

---

app/services/fees/charge_service.rb
spec/services/fees/charge_service_spec.rb

We still have some invoices stuck in generating status, when units or amount are negative.
The goal of this PR is to permit the creation of the fee by converting the value to 0 when it's negative for `units` and `amount` fields.
But we keep the calculation details on `amount_details`.
Example:

fix: Ability to create fee with negative units or amount

---

app/services/billable_metrics/aggregation_factory.rb
app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/aggregations/count_service.rb
app/services/billable_metrics/aggregations/custom_service.rb
app/services/billable_metrics/aggregations/latest_service.rb
app/services/billable_metrics/aggregations/max_service.rb
app/services/billable_metrics/aggregations/sum_service.rb
app/services/billable_metrics/aggregations/unique_count_service.rb
app/services/billable_metrics/aggregations/weighted_sum_service.rb
app/services/events/stores/base_store.rb
app/services/events/stores/clickhouse_store.rb
app/services/events/stores/postgres_store.rb
app/services/events/stores/store_factory.rb
app/services/fees/charge_service.rb
app/services/invoices/calculate_fees_service.rb
spec/services/billable_metrics/aggregations/count_service_spec.rb
spec/services/billable_metrics/aggregations/custom_service_spec.rb
spec/services/billable_metrics/aggregations/latest_service_spec.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/billable_metrics/aggregations/weighted_sum_service_spec.rb
spec/services/events/stores/clickhouse_store_spec.rb
spec/services/events/stores/postgres_store_spec.rb

The current approach for generating a subscription invoice with charge fees is to perform one aggregation request per charge (and possibly per charge filter when defined) no matter the number of events received during the billing period.
For plans counting a lot of charges this could be very slow when many invoices are generated in parallel (on a 1st day of a month for example).
After some research, it appears that in many cases, most of the aggregation result for both charges or filters results in a zero fee as no event were received.
The goal of this PR is to add a pre-check on events before performing the charge billing. It will detect the distinct event code received for a specific subscription during the billing period, and use this list to perform the aggregation only on charge …

misc(invoice): Bypass aggregation queries when no event in period

---

app/models/invoice.rb
db/migrate/20241216140931_add_tax_status_to_invoices.rb
db/schema.rb
schema.graphql
schema.json
spec/factories/invoices.rb
spec/models/invoice_spec.rb

Currently Anrok calls are sync and performed during invoice generation
The goal of this improvement is to make calls to Anrok in dedicated job so that we can implement throttling for rate limit issues.
This PR adds necessary DB changes

feat(anrok): add new tax related statuses on invoice

---

app/services/base_service.rb
app/services/invoices/payments/adyen_service.rb
app/services/invoices/payments/create_service.rb
app/services/invoices/payments/gocardless_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/payment_providers/adyen/payments/create_service.rb
app/services/payment_providers/create_payment_factory.rb
app/services/payment_providers/gocardless/payments/create_service.rb
app/services/payment_providers/stripe/payments/create_service.rb
spec/scenarios/wallets/topup_with_open_invoices_spec.rb
spec/services/invoices/payments/adyen_service_spec.rb
spec/services/invoices/payments/create_service_spec.rb
spec/services/invoices/payments/gocardless_service_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/payment_providers/adyen/payments/create_service_spec.rb
spec/services/payment_providers/create_payment_factory_spec.rb
spec/services/payment_providers/gocardless/payments/create_service_spec.rb
spec/services/payment_providers/stripe/payments/create_service_spec.rb

This PR follow https://github.com/getlago/lago-api/pull/2930 and https://github.com/getlago/lago-api/pull/2935 in the refactor of the payment processing.
The main goal of this refactor will be to:
- Avoid double payment at all cost
- Avoid code duplication between payment processor integration to make maintenance easier
This PR:
- Extract the payment creation logic from `Invoices::Payments::*Service#call` into dedicated services in `PaymentProviders::*::Payments::CreateService#call`. These services are only responsible for the payment creation itself and the related error handling
- Extract webhook deliveries, invoice payment status handling and integration notification in from each provider services in the main `Invoices::Payments::CreateService`
In the next step this last service will …

misc(payment): Refactor payment creation on provider

---

app/services/base_service.rb

Currently Anrok calls are sync and performed during invoice generation
The goal of this improvement is to make calls to Anrok in dedicated job so that we can implement throttling for rate limit issues.
This PR adds new error definition that will represent the state where tax is not pulled yet from external provider

feat (anrok): add error that indicates that tax is unknown

---

spec/spec_helper.rb

Recently we're added by default `aggregate_failures: true` to all test's metadata.
Unfortunately, `aggregate_failures` changes some information on the test example metadata and limits our opportunity to debug randomly failing test more efficiently.
Particularly this overrides `example.exception`. It's needed when we have test that fails from time to time depending on some tricky data combination.
The quickest and easiest known way to me to debug it is to use `after { |example| binding.pry if example.exception }`. That callback will trigger breakpoint only if test failed.
quick debug setup will look like
```ruby
describe "something" do
after { |example| binding.pry if example.exception }
1000.times do
fit "randomly failing test", aggregate_failures: false do
end
end
end
```
That will run …

misc: Prevent overriding set by test example aggregate_failures flag

---

app/services/integration_customers/create_service.rb
spec/services/integration_customers/create_service_spec.rb

This PR updates the link_customer! method to ensure that the sync_with_provider attribute is always set to true when the integration type is SalesforceIntegration. Previously, the value for sync_with_provider was hardcoded as false, regardless of the integration type.

feat(salesforce): Sync with provider always true

---

app/services/invoices/payments/create_service.rb
app/services/payment_providers/adyen/payments/create_service.rb
app/services/payment_providers/gocardless/payments/create_service.rb
app/services/payment_providers/stripe/payments/create_service.rb
spec/services/payment_providers/stripe/payments/create_service_spec.rb

This PR is related to https://github.com/getlago/lago-api/pull/2962
An issue was raised with the payment status on payment provider in the mapping with invoice payment status

fix(payment): Fix handling of processing payment

---

app/services/invoices/payments/create_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/payment_provider_customers/stripe/update_payment_method_service.rb
app/services/payment_providers/stripe/payments/create_service.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/payments/create_service_spec.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
spec/services/invoices/retry_service_spec.rb
spec/services/invoices/subscription_service_spec.rb
spec/services/payment_provider_customers/stripe/update_payment_method_service_spec.rb
spec/services/payment_providers/stripe/payments/create_service_spec.rb

This pull requests fixes two issues related to the recent refactoring of the payment handling on payment providers:
- It makes sure that `amount_too_small` raised by stripe are correctly handled, by failing the `Payment` record and by setting the `invoice.payment_status` back to `pending`
- I fixes some issues related to missing payment found/created on the fly when receiving Stripe webhooks for payment_intend

fix(payment): Handling of amount_too_small - stripe webhooks

---

app/services/invoices/payments/stripe_service.rb

In some situation, multiple `PaymentProviders::Stripe::HandleEventJob` are handled for the same `one-time` stripe, payment_intent, leading to a duplicated payment record in the database.
This PR makes sure that the payment is retrieved correctly from the database if it already exists

fix(payment): Avoid creating duplicated Payment record for one time invoices

---

app/controllers/api/v1/events_controller.rb
app/services/events/create_batch_service.rb
app/services/events/create_service.rb
app/services/events/validate_creation_service.rb
spec/requests/api/v1/events_controller_spec.rb
spec/services/events/create_batch_service_spec.rb
spec/services/events/create_service_spec.rb
spec/services/events/validate_creation_service_spec.rb

A check for event timestamp as it should be sent in seconds

Misc(events): add timestamp validation for create event

---

app/jobs/clock/compute_all_daily_usages_job.rb
app/jobs/daily_usages/compute_job.rb
app/models/daily_usage.rb
app/services/daily_usages/compute_service.rb
app/services/daily_usages/fill_from_invoice_service.rb
app/services/daily_usages/fill_history_service.rb
db/migrate/20241219145642_add_usage_date_to_daily_usages.rb
db/migrate/20241219152909_add_index_on_usage_date_to_daily_usages.rb
db/schema.rb
spec/jobs/clock/compute_all_daily_usages_job_spec.rb
spec/services/daily_usages/compute_service_spec.rb
spec/services/daily_usages/fill_from_invoice_service_spec.rb

The goal of this PR is to add `usage_date` column to the `daily_usages` table.
It will help fetching the correct usage for a specific date, without computing the `refreshed_at` values.
Next PR will remove use of `refreshed_at` in favor of `usage_date`.

feat(data): Add usage_date to daily_usages

---

app/controllers/api/v1/credit_notes_controller.rb
app/queries/credit_notes_query.rb
spec/queries/credit_notes_query_spec.rb
spec/requests/api/v1/credit_notes_controller_spec.rb

Added more filter options to credit notes list endpoint

feat(credit-note-export): Add new filters options to credit notes list endpoint

---

app/services/invoices/payments/create_service.rb
spec/services/invoices/payments/create_service_spec.rb

This PR is part of the recent payment handling refactoring.
It makes sure that failed payment attempts with an `amount_too_small` error does not lead to an error webhook but only keeps the payment with a `failed` `status` and `pending` `payable_payment_status`. allowing reprocessing of the payment or grouping in  a payment request, without spamming the organization owner

misc(payment): Avoid error webhooks on small amount failure

---

app/services/charge_filters/create_or_update_batch_service.rb
db/migrate/20241220084758_fix_charge_properties_with_double_values.rb
spec/factories/charges.rb
spec/services/charge_filters/create_or_update_batch_service_spec.rb

Added check on charge_filters creation
added migration to fix existing charges and charge_filters

Chore(charge_filters): add check on filter properties to be compliant with charge.charge_model

---

db/migrate/20241220095049_backfill_payable_payment_status.rb

Changed the migration to clean duplicate data first and then run the migration

Fix clean duplicate payments

---

app/models/wallet.rb
app/services/wallets/create_service.rb
spec/services/wallets/create_service_spec.rb

This PR is related to 
```
ActiveRecord::NotNullViolation
PG::NotNullViolation: ERROR:  null value in column "balance_currency" of relation "wallets" violates not-null constraint (ActiveRecord::NotNullViolation)
```
The error is raised when creating a wallet with a null currency if the related customer does not have a currency.
The PR
- Add a validation on `wallet#currency` making sure it is included in the accepted currency list.
- Avoid updating the customer currency with a nil value

fix(wallet): Validate currency

---

app/models/daily_usage.rb
app/services/daily_usages/compute_all_service.rb
app/services/daily_usages/compute_diff_service.rb
app/services/daily_usages/compute_service.rb
app/services/daily_usages/fill_from_invoice_service.rb
app/services/daily_usages/fill_history_service.rb
spec/factories/daily_usages.rb
spec/models/daily_usage_spec.rb
spec/services/daily_usages/compute_all_service_spec.rb
spec/services/daily_usages/compute_diff_service_spec.rb
spec/services/daily_usages/compute_service_spec.rb

The goal of this PR is to use `usage_date` column instead of `refreshed_at` from the `daily_usages` table.
It will help fetching the correct usage for a specific date, without computing the `refreshed_at` values.
Next PR will remove the `refreshed_at` column.

feat(data): Use usage_date instead of refreshed_at for daily usage

---

app/services/daily_usages/fill_history_service.rb

When checking for existing daily usages, we don't want to convert the date into the customer timezone, because it can change the current date.

fix(data): Populate daily usages

---

app/jobs/plans/destroy_job.rb
spec/jobs/plans/destroy_job_spec.rb

This change is meant to avoid issues when a user tries to delete a plan more than once. This happens because the plan deletion is performed as a background job and could take some time as all child plans must be deleted, subscriptions terminated, invoices generated and discarded, etc...
The goal of this change is to avoid failed jobs because of race conditions between multiple runs for the same plan producing unique DB index constraints errors or discard! errors as those only produce noise and waste of support time.

fix: Ensure Plans::DestroyJob are queued only once

---

app/graphql/types/invoices/object.rb
app/graphql/types/invoices/tax_status_type_enum.rb
app/jobs/bill_subscription_job.rb
app/jobs/fees/create_pay_in_advance_job.rb
app/jobs/invoices/create_pay_in_advance_charge_job.rb
app/jobs/invoices/provider_taxes/pull_taxes_and_apply_job.rb
app/services/integrations/aggregator/taxes/invoices/create_draft_service.rb
app/services/integrations/aggregator/taxes/invoices/create_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/compute_taxes_and_totals_service.rb
app/services/invoices/progressive_billing_service.rb
app/services/invoices/provider_taxes/pull_taxes_and_apply_service.rb
app/services/invoices/refresh_draft_and_finalize_service.rb
app/services/invoices/refresh_draft_service.rb
app/services/invoices/retry_service.rb
app/services/invoices/subscription_service.rb
app/services/lifetime_usages/recalculate_and_check_service.rb
schema.graphql
schema.json
spec/graphql/mutations/invoices/finalize_spec.rb
spec/graphql/mutations/invoices/retry_spec.rb
spec/jobs/bill_subscription_job_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/compute_taxes_and_totals_service_spec.rb
spec/services/invoices/progressive_billing_service_spec.rb
spec/services/invoices/provider_taxes/pull_taxes_and_apply_service_spec.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
spec/services/invoices/refresh_draft_service_spec.rb
spec/services/invoices/subscription_service_spec.rb
spec/services/lifetime_usages/recalculate_and_check_service_spec.rb

Currently Anrok calls are sync and performed during invoice generation
The goal of this improvement is to make calls to Anrok in dedicated job so that we can implement throttling for rate limit issues.
This PR changes all places where Anrok in used in sync way. This is the last PR that is extension of:
- https://github.com/getlago/lago-api/pull/2984
- https://github.com/getlago/lago-api/pull/2968
- https://github.com/getlago/lago-api/pull/2964

feat(anrok): make api calls async in dedicated service

---

app/jobs/invoices/provider_taxes/pull_taxes_and_apply_job.rb

Currently Anrok calls are sync and performed during invoice generation
The goal of this improvement is to make calls to Anrok in dedicated job so that we can implement throttling for rate limit issues.
This PR changes queue for described job. Previous 'integrations' queue was intended mostly for syncs when invoice is already finalized.
Queue for this job needs to have higher priority so that invoice can be moved from `pending` as soon as possible.

fix (tax-integrations): change queue for the job that apply taxes on pending invoice

---

spec/services/daily_usages/compute_service_spec.rb

when subscription is terminated after the timestamp test had issues with year change.

fix(broken-test): DailyUsages::ComputeService test

---

app/serializers/v1/invoice_serializer.rb
app/services/webhooks/invoices/resynced_service.rb
spec/services/webhooks/invoices/resynced_service_spec.rb

The ResyncedService requires the inclusion of integration_customers in the serialized Customer object as part of the webhook payload. However, this inclusion should only happen in specific cases, like in the ResyncedService, and not affect other serializers or services. 
we use this webhook to do the salesforce integration that why we need the customer integration

feat: Add Conditional Integration Customers to use on resync webhook

---

app/controllers/webhooks_controller.rb
app/jobs/clock/inbound_webhooks_cleanup_job.rb
app/jobs/clock/inbound_webhooks_retry_job.rb
app/jobs/inbound_webhooks/process_job.rb
app/models/inbound_webhook.rb
app/services/inbound_webhooks/create_service.rb
app/services/inbound_webhooks/process_service.rb
app/services/inbound_webhooks/validate_payload_service.rb
app/services/payment_providers/stripe/handle_incoming_webhook_service.rb
app/services/payment_providers/stripe/validate_incoming_webhook_service.rb
clock.rb
db/migrate/20241213182343_create_inbound_webhooks.rb
db/migrate/20241219122151_add_processing_at_to_inbound_webhooks.rb
db/migrate/20241223154437_add_indices_to_inbound_webhooks.rb
db/schema.rb
spec/clockwork_spec.rb
spec/factories/inbound_webhooks.rb
spec/jobs/clock/inbound_webhooks_cleanup_job_spec.rb
spec/jobs/clock/inbound_webhooks_retry_job_spec.rb
spec/jobs/inbound_webhooks/process_job_spec.rb
spec/models/inbound_webhook_spec.rb
spec/requests/webhooks_controller_spec.rb
spec/services/inbound_webhooks/create_service_spec.rb
spec/services/inbound_webhooks/process_service_spec.rb
spec/services/inbound_webhooks/validate_payload_service_spec.rb
spec/services/payment_providers/stripe/handle_incoming_webhook_service_spec.rb
spec/services/payment_providers/stripe/validate_incoming_webhook_service_spec.rb

Currently, when our application receives webhooks from third-party services (e.g., Stripe, GoCardless, Adyen), their payloads are immediately queued in Sidekiq for background processing. While this approach works in most cases, it introduces a critical reliability issue, especially in self-hosted environments where Sidekiq may lose jobs if workers are abruptly terminated or overloaded.
This unreliability has led to issues like pending transactions that are never resolved despite receiving valid webhooks. For example, a reported issue involved a wallet credit purchase where the payment settled on Stripe, the webhook was received, but the transaction remained pending indefinitely until manually resolved.
To address this, we aim to ensure that no webhook payload is lost and processing …

fix: Persist inbound stripe webhooks

---

app/services/subscriptions/dates_service.rb

At present, it is possible to obtain fees with errors within boundaries.
In fact, when the fee is of the charge type, paid in advance and the charge non-invoiceable, on the last day of the billing period there is a boundary shift.
`from_date` and `to_date` correspond to the next billing period.

fix(fee): Charge pay in advance interval without any day-shift

---

app/services/invoices/advance_charges_service.rb
spec/services/invoices/advance_charges_service_spec.rb

The goal of this PR is to ensure the fee is created for the correct billing period.
By checking invoice subscription boundaries and comparing them to the fee timestamp.

fix(fee): Prevent creating fee for an incorrect billing period

---

app/jobs/invoices/create_pay_in_advance_charge_job.rb

Sometimes, we could have issues related to stale wallet updates, when creating pay in advance event.
The goal of this PR is to retry the `Invoices::CreatePayInAdvanceChargeJob` if we had this exception.

fix: Retry when getting stale wallet error for pay in advance events

---

app/services/customers/update_invoice_grace_period_service.rb
app/services/organizations/update_invoice_grace_period_service.rb
spec/services/customers/update_invoice_grace_period_service_spec.rb
spec/services/organizations/update_invoice_grace_period_service_spec.rb
spec/services/organizations/update_service_spec.rb

We incorrectly converted nil to zero in the invoice grace period update service. This means we cannot clear the value.

Fix invoice grace period saving with null values

---

app/services/charges/charge_models/percentage_service.rb

Some invoices failed to generate because some values stored in the fee#amount_details were failing to render as amount. The reason was that they were computed as `float` and converted to string. 
Since float is not a reliable data type, we should use `BigDecimal` to handle the amount detail values

fix(invoice): Use BigDecimal rather than float for amount details

---

app/models/analytics/overdue_balance.rb
app/models/payment.rb
app/services/manual_payments/create_service.rb
config/locales/en.yml
spec/models/payment_spec.rb
spec/services/manual_payments/create_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/log-partial-payments
This PR adds `ManualPayments::CreateService`

feat(manual-payments): Add service to create manual payments

---

.github/workflows/migrations-test.yml
.github/workflows/spec.yml

To support external contributions, we can't use secrets in GitHub workflows that need to run. This PR addresses that by hardcoding the values for specs and migration tests.

misc(Github) - Do not use secrets when hardcoded values suffice

---

app/controllers/api/v1/events_controller.rb
spec/requests/api/v1/events_controller_spec.rb

This PR fixes `ActiveRecord::ActiveRecordError` raised when calling `GET /api/v1/events/:transaction_id`.
It happen when the `clickhouse_events_store` flag is turned on at organization level.
The fix is to use `organization_id` rather than `organization` when fetching the event as `Clickhouse::RawEvent` does not define a relation with the organization model

fix(event): retrieve clickhouse events

---

app/jobs/bill_non_invoiceable_fees_job.rb
app/services/invoices/advance_charges_service.rb
app/services/subscriptions/terminate_service.rb
spec/graphql/lago_api_schema_spec.rb
spec/scenarios/invoices/recurring_fees_spec.rb
spec/services/invoices/advance_charges_service_spec.rb
spec/services/subscriptions/terminate_service_spec.rb
spec/support/scenarios_helper.rb

Steps to reproduce the issue:
1. Create a recurring metric;
2. Create a plan with a charge linked to the recurring metric - the charge should be:
* prorated = true;
* pay_in_advance = true;
* invoiceable = false;
* regroup_paid_fees = invoice;
3. Create a subscription with a start date in the past and send an event in the past (e.g. 1 December) -> you receive a fee.created webhook;
4. Duplicate the original plan and only modify the price of the charge (higher price);
5. Trigger an upgrade of the existing subscription by assigning the new plan;
6. Mark the fee in step 3 as succeeded via POST api/v1/fees/:lago_id
7. Terminate the subscription -> the fee is not included in the end-of-period invoice.
Expected behaviour: the fee should be included in the end-of-period invoice, even if the …

fix: Recurring fee not displayed on invoices after upgrade

---

app/services/invoices/advance_charges_service.rb
spec/scenarios/invoices/advance_charges_spec.rb
spec/services/invoices/advance_charges_service_spec.rb

This pull request includes changes to improve the handling of succeeded fees based on a new `succeeded_at` timestamp. These changes ensure that fees are correctly associated with invoices based on their success timestamp.

fix: Use succeeded_at to select fees for regrouping

---

app/jobs/invoices/prepaid_credit_job.rb
app/jobs/wallet_transactions/create_job.rb
app/jobs/wallets/refresh_ongoing_balance_job.rb
config/sidekiq/sidekiq.yml
spec/services/invoices/advance_charges_service_spec.rb

Queuing of wallet transaction related jobs is ideal as jobs as a low priority, meaning that under heavy load, they are a huge delay might happen between enqueue and  processing. Since it is user facing, we need to improve it.
This PR:
- Adds a new `high_priority` queue that should be used for all jobs requiring an "immediate" processing
- Moves the `Invoices::PrepaidCreditJob` from the `wallet` to the new `high_priority` queue
- Moves the `WalletTransactions::CreateJob` from the `wallet` to the new `high_priority` queue
- Moves `Wallets::RefreshOngoingBalanceJob` into the low priority queue
Note no more jobs will relies on the `wallet` queue, but this queue is kept fro now in the config to avoid issue with existing enqueued jobs.

misc(wallet): Refactor wallet transaction related jobs queuing

---

app/models/payment_providers/stripe_provider.rb
app/services/payment_providers/stripe/payments/create_service.rb

Some recent refactors were made on the payment processing implementation with stripe.
When a payment intent creation was failing with the `requires_payment_method` status, the lago payment is kept `processing` preventing it from being retried because of the idem-potency key (the new attempt will have a different payload if the payment method is updated).
This PR changes the behavior for `requires_payment_method` ensuring that the payment is marked as failed, allowing a retry after fixing the cause of the failure (missing or expired payment method)

fix(stripe): Payment failing with requires_payment_method should be marked as failed

---

app/jobs/invoices/refresh_draft_job.rb

As the RefreshDraftJob can be enqueued for lots of invoices, this should be handled by the billing worker as well, avoiding large backlogs on other queues.

misc(BillingWorker) - Move Invoices::RefreshDraftJob to billing queue

---

app/services/charge_filters/event_matching_service.rb
spec/services/charge_filters/event_matching_service_spec.rb

When creating an event, it was ignored because the type has been sent as an integer and should be sent as a string.
The goal of this PR is to convert it to string so that it can be taken into consideration in the current usage.

fix: Cast filters to string on ingestion

---

app/services/invoices/create_pay_in_advance_charge_service.rb
spec/services/invoices/create_pay_in_advance_charge_service_spec.rb

Pay in advance jobs do not reliably retry when a StaleObjectError is raised.
This PR builds on top of [this PR](https://github.com/getlago/lago-api/pull/3027) which will retry the pay in advance job when a StaleObjectError is raised. This error is currently handled by the generic `rescue` block, and instead should be re-raised similarly to how the SequenceError is.
I have tested this in a local docker setup, by sending a large volume of events to Lago over a very short period. Before this fix, some fees fail to generate, after the fix all the fees are successfully generated.

Propagate StaleObjectErrors so PayInAdvance jobs retry

---

app/controllers/api/v1/invoices_controller.rb
spec/requests/api/v1/invoices_controller_spec.rb

We were not sending `integration_customers` in the invoice payload in the following endpoints:
```
GET /api/v1/invoices/
GET /api/v1/invoices/:id
```
This PR adds `integration_customers` to the payload in `InvoicesController#show` and `InvoicesController#index` actions.

misc(invoice): Add integration_customers to the invoice payload

---

app/services/invoices/create_one_off_service.rb
spec/services/invoices/create_one_off_service_spec.rb

We were getting this error in `Invoices::CreateOneOffService#tax_error?`:
```
NoMethodError undefined method `code' for an instance of BaseService::ValidationFailure (NoMethodError)
```
The reason for that is that some errors (e.g.: `BaseService::ValidationFailure`) don't have `code`.
This PR fixes `Invoices::CreateOneOffService#tax_error?` by checking if the actual error result responds to `code`.

fix(one-off-invoice): Fix create one off invoice service

---

app/controllers/api/v1/invoices_controller.rb
app/graphql/resolvers/invoices_resolver.rb
app/graphql/types/data_exports/invoices/filters_input.rb
app/queries/invoices_query.rb
schema.graphql
schema.json
spec/factories/invoice_metadata.rb
spec/graphql/mutations/data_exports/invoices/create_spec.rb
spec/graphql/resolvers/invoices_resolver_spec.rb
spec/graphql/types/data_exports/invoices/filters_input_spec.rb
spec/queries/invoices_query_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb

Adding new filters for Invoices
Add invoice amount filters to the graphql, export and API
Add invoice metadata filters to API only

feat(invoices): Add new filters

---

app/services/subscriptions/validate_service.rb
spec/services/subscriptions/validate_service_spec.rb

When updating the subscription with `subscription_at` or `ending_at` fields, they should accepts milliseconds e.g.: `2025-01-10T00:00:00.000Z`
This PR updates `Subscriptions::ValidateService#subscription_at` and `Subscriptions::ValidateService#ending_at` so that they can parse datetimes containing milliseconds.

fix(validations): Fix subscriptions validate service

---

app/services/fees/charge_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/customer_usage_service.rb
app/services/invoices/progressive_billing_service.rb
spec/scenarios/invoices/adjusted_charge_fees_spec.rb
spec/scenarios/invoices/invoices_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
spec/services/invoices/refresh_draft_service_spec.rb
spec/services/invoices/subscription_service_spec.rb

This PR follow https://github.com/getlago/lago-api/pull/3020 the goal is to stop generating empty fees (0 units, amount and events without adjustments or true up fees).
The reason behind this change is scalability as for now, depending on the plan setups, it appears that 98% of generated fees does not have an amount...
**NOTE:** a new feature will improve the edit fees feature since this PR will prevent creation of adjustment fees from the UI if no event have been received for a specific billable metric on a period.

feat(invoice): Avoid generating 0 amount charge fees

---

app/controllers/api/v1/invoices_controller.rb
app/queries/invoices_query.rb
spec/queries/invoices_query_spec.rb

👉  https://getlago.canny.io/feature-requests/p/log-partial-payments
This feature introduces the ability to filter invoices for partially paid invoices. It provides additional flexibility for users who need to identify partially paid or unpaid invoices. This enhancement aligns with the requirements outlined in the linked roadmap task.
The changes include:
- Implementation of the with_partially_paid method to filter invoices based on partially_paid values (true, false, or nil).
- Updated the InvoicesQuery class to apply the filter when the partially_paid parameter is provided.

Add support for filtering invoices by partially paid

---

app/contracts/queries/payments_query_filters_contract.rb
app/controllers/api/v1/invoices_controller.rb
app/controllers/api/v1/payments_controller.rb
app/models/api_key.rb
app/models/payment.rb
app/queries/invoices_query.rb
app/queries/payments_query.rb
app/serializers/v1/payment_serializer.rb
app/services/manual_payments/create_service.rb
config/routes.rb
spec/contracts/queries/payments_query_filters_contract_spec.rb
spec/models/payment_spec.rb
spec/queries/invoices_query_spec.rb
spec/queries/payments_query_spec.rb
spec/requests/api/v1/payments_controller_spec.rb
spec/serializers/v1/payment_serializer_spec.rb
spec/services/manual_payments/create_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/log-partial-payments
This PR introduces a new endpoint to list all payments. Additionally, it adds the ability to filter payments by a specific invoice_id, allowing users to narrow down the results to payments associated with a particular invoice. This enhancement improves the flexibility and usability of the payments listing functionality.
It also adds `create` and `show` actions in the PaymentsController.
**Added Endpoint:**
- Created an endpoint to list, show and create payments.
- Filter by invoice_id:
- Added functionality to filter payments based on the provided invoice_id.
- Included a validation step to ensure the invoice_id is in the correct UUID format before executing the query.
**Query Updates:**
- Refactored PaymentsQuery to …

Feat manual payments controller

---

app/services/fees/charge_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/customer_usage_service.rb
app/services/invoices/progressive_billing_service.rb
spec/scenarios/invoices/adjusted_charge_fees_spec.rb
spec/scenarios/invoices/invoices_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
spec/services/invoices/refresh_draft_service_spec.rb
spec/services/invoices/subscription_service_spec.rb

This reverts commit 36315a97b88f2e3313aa0e0c7b1d8c90aa02cf8b.

Revert "feat(invoice): Avoid generating 0 amount charge fees (#3032)"

---

app/services/customers/terminate_relations_service.rb
spec/services/customers/terminate_relations_service_spec.rb

When deleting a customer that has draft invoices in `Customers::TerminateRelationsService`
This job is called twice `PullTaxesAndApplyJob` as a result of calling `TerminateService` and then `Invoices::RefreshDraftAndFinalizeService.call`.
Then the first enqueued `PullTaxesAndApplyJob` raises:
```
ActiveRecord::InvalidForeignKey
PG::ForeignKeyViolation: ERROR:  insert or update on table "fees_taxes" violates foreign key constraint "fk_rails_..." (ActiveRecord::InvalidForeignKey)
DETAIL:  Key (fee_id)=(...) is not present in table "fees".
```
Because the concurrently running second job deleted those fees from the DB in the meantime.
This PR mitigates the issue by delaying `Invoices::FinalizeJob` by 5 minutes.

fix(terminate-relations): Fix terminate relations service

---

app/models/customer.rb
app/models/invoice.rb
db/migrate/20250114163522_add_account_type_to_customers.rb
db/migrate/20250114172823_add_self_billed_to_invoices.rb
db/schema.rb

Add `account_type` enum to customers.
Add `self_billed` flag to invoices

feat(revshare): Add db columns for partners and self_billed invoices

---

app/models/analytics/gross_revenue.rb
app/models/analytics/invoice_collection.rb
app/models/analytics/invoiced_usage.rb
app/models/analytics/mrr.rb
app/models/analytics/overdue_balance.rb

Ignore self billed invoices in analytics

feat(revshare): Skip self billed invoices in analytics

---

app/controllers/api/v1/customers_controller.rb
app/graphql/types/customers/account_type_enum.rb
app/graphql/types/customers/create_customer_input.rb
app/graphql/types/customers/object.rb
app/models/customer.rb
app/models/organization.rb
app/serializers/v1/customer_serializer.rb
app/services/customers/create_service.rb
schema.graphql
schema.json
spec/graphql/types/customers/account_type_enum_spec.rb
spec/graphql/types/customers/create_customer_input_spec.rb
spec/graphql/types/customers/object_spec.rb
spec/models/customer_spec.rb
spec/models/organization_spec.rb
spec/requests/api/v1/customers_controller_spec.rb
spec/serializers/v1/customer_serializer_spec.rb
spec/services/customers/create_service_spec.rb
spec/support/shared_examples/organization_feature_spec.rb

define `revenue_share` premium integration for organizations
Create customers with account_type partner when revenue share premium integration is enabled.
GraphQL and API v1 accepts and returns customer account_type.

feat(revshare): Create customers with partner as account_type

---

app/services/fees/subscription_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/preview_service.rb
spec/services/fees/subscription_service_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature enables fetching first Lago invoice. This invoice is not persisted aand is calculated on the fly.
This PR adds preview service which will be the base for the feature.
It can work for existing subscription and customer, but also for objects that are just created in-memory.
Following PRs will attach credits to the preview invoice and tax provider integration will also be supported.

feat(invoice-preview): add base preview service

---

app/services/fees/charge_service.rb
app/services/invoices/calculate_fees_service.rb
spec/services/fees/charge_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb

Currently we had an issue that pay in advance, non-invoiceable and recurring fees are missing taxes when recreated at next billing period for subscription. This PR partially fixes it by applying defined in Lago taxes.
There will be another part addressing taxes via Anrok provider.
Optionally add Lago-defined taxes for charge fees.

Add taxes to recreated recurring pay in advance fees

---

app/serializers/v1/invoice_serializer.rb
app/services/invoices/create_generating_service.rb
app/services/invoices/payments/create_service.rb
spec/factories/invoices.rb
spec/serializers/v1/invoice_serializer_spec.rb
spec/services/invoices/create_generating_service_spec.rb
spec/services/invoices/payments/create_service_spec.rb

expose self_billed attribute in v1 invoices serializer
create invoice as self_billed when customer is a partner
skip payment creation for self_billed invoices.

feat(revshare): self billed invoice creation and skip payments

---

app/graphql/types/customers/update_customer_input.rb
app/services/customers/update_service.rb
schema.graphql
schema.json
spec/graphql/types/customers/update_customer_input_spec.rb
spec/services/customers/update_service_spec.rb

applies customer account_type updates when customer is editable and feature is enabled.
as side effect excludes customer from dunning campaigns (not applicable to partners)

feat(revshare): update customer account_type

---

app/models/invoice.rb
spec/models/invoice_spec.rb
spec/services/invoices/payments/create_service_spec.rb
spec/services/invoices/subscription_service_spec.rb

Self-billed invoices should not be reported to Hubspot and Salesforce 
in definition of methods that return if invoice should be synced, added condition to skip self-billed invoices

Feat(revshare): self billed invoices - do not trigger integrations

---

app/models/adjusted_fee.rb
app/models/applied_coupon.rb
app/models/billable_metric.rb
app/models/charge.rb
app/models/commitment.rb
app/models/coupon.rb
app/models/credit_note.rb
app/models/customer.rb
app/models/error_detail.rb
app/models/fee.rb
app/models/integration_collection_mappings/base_collection_mapping.rb
app/models/integration_item.rb
app/models/integration_resource.rb
app/models/invite.rb
app/models/invoice.rb
app/models/invoice_subscription.rb
app/models/membership.rb
app/models/organization.rb
app/models/payment.rb
app/models/payment_request.rb
app/models/plan.rb
app/models/recurring_transaction_rule.rb
app/models/subscription.rb
app/models/wallet.rb
app/models/wallet_transaction.rb
app/models/webhook.rb
app/models/webhook_endpoint.rb

Let's get ready for Rails 7.2
I was looking at [Ancor's PR](https://github.com/getlago/lago-api/pull/2894) to upgrade to Rails 7.2 and I thought we could extracted the enum changes to a separate PR since the syntax is already available.
Rails 7.2 will show a warning if we keep using the previous syntax (with a hash) and 8.0 will remove it entirely.
https://blog.saeloun.com/2021/02/26/rails-introduces-new-syntax-for-enum/

chore: Use enum with positional arguments

---

app/models/applied_coupon.rb
app/models/fee.rb
app/services/applied_coupons/amount_service.rb
app/services/coupons/preview_service.rb
app/services/credits/applied_coupon_service.rb
app/services/invoices/preview_service.rb
spec/models/applied_coupon_spec.rb
spec/models/fee_spec.rb
spec/services/applied_coupons/amount_service_spec.rb
spec/services/coupons/preview_service_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature enables fetching first Lago invoice. This invoice is not persisted and is calculated on the fly.
This PR adds service for applying coupons on preview invoice. The goal was not to affect heavily main service for applying coupons on invoices.
In order not to repeat the code, some common logic is extracted  s that it can be used on both places

feat(invoice-preview): add logic for applying coupons on preview invoice

---

.github/workflows/migrations-test.yml
app/models/fee.rb
db/migrate/20250120151959_add_unique_event_index_on_fees.rb
db/schema.rb

- To prevent duplicate invoicing for in advance charges, we add a unique index based on the `transaction_id` from the event

chore(fees): Add unique index on event transaction id

---

app/services/validators/metadata_validator.rb
app/services/wallets/recurring_transaction_rules/validate_service.rb
spec/requests/api/v1/wallets_controller_spec.rb
spec/services/validators/metadata_validator_spec.rb
spec/services/wallets/recurring_transaction_rules/update_service_spec.rb
spec/services/wallets/recurring_transaction_rules/validate_service_spec.rb
spec/services/wallets/update_service_spec.rb

We expect transaction_metadata for recurring_transaction_rules to be an array, but we do not validate that what we received via API as an array and not an empty hash
Added validation of type for metadata - both, wallet and recurring_transaction_rule to be of type Array

Fix: add validation on transaction_metadata type for recurring transaction rules

---

app/models/invoice.rb
app/services/invoices/generate_pdf_service.rb
app/views/templates/invoices/v4/self_billed.slim
config/locales/de/invoice.yml
config/locales/en/invoice.yml
config/locales/es/invoice.yml
config/locales/fr/invoice.yml
config/locales/it/invoice.yml
config/locales/nb/invoice.yml
config/locales/sv/invoice.yml
spec/models/invoice_spec.rb
spec/services/invoices/generate_pdf_service_spec.rb

add self_billed invoice template
generate self_billed invoices with the right template
custom sections feature is the only one excluded from v4 normal invoices template, all other features like progressive billing, coupons, etc should be available.

feat(revshare): self billed invoice pdf/html template

---

app/services/credits/credit_note_service.rb
app/services/invoices/preview_service.rb
spec/services/credits/credit_note_service_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature enables fetching first Lago invoice. This invoice is not persisted and is calculated on the fly.
This PR adds logic for applying wallet and credit note credits on preview invoice.

feat(invoice-preview): add preview support for wallet and credit note credits

---

app/services/credit_notes/create_service.rb
app/services/credit_notes/estimate_service.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/credit_notes/estimate_service_spec.rb

When receiving a request to estimate/create a credit note with missing items, now we simply fail with server error, instead we want to return a validation error
Added validation to credit_notes/create_service and credit_notes/estimate_service to check if the received items is an array

Chore: add validation on credit note creation and estimate to have items as an array

---

app/services/invoices/refresh_draft_and_finalize_service.rb
db/migrate/20250122112050_delete_sequence_generation_invoice_error_for_generated_invoices.rb
db/schema.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb

We have invoices that are generated, so they have invoice_number, but the invoice_error storing details of not generated number still exists
Added migration to delete invoice_errors that are not needed anymore;
Added methods to delete invoice_errors when invoice is successfully generated

Chore: delete invoice errors for sequential number generation when finishing invoice generation

---

app/queries/invoices_query.rb
spec/queries/invoices_query_spec.rb

Recently added invoice filtering by metadata incorrectly counts `total_count` in pagination metadata.
Fix pagination `total_count` when filter invoices by metadata.

fix(invoice-filtering): Wrong total count when filter invoices by metadata

---

spec/rails_helper.rb
spec/services/integrations/aggregator/companies/create_service_spec.rb
spec/services/integrations/aggregator/contacts/create_service_spec.rb
spec/services/invoices/payments/create_service_spec.rb
spec/services/lifetime_usages/recalculate_and_check_service_spec.rb
spec/services/payment_provider_customers/adyen_service_spec.rb
spec/services/payment_provider_customers/stripe_service_spec.rb
spec/services/payment_requests/payments/create_service_spec.rb
spec/support/queues_helper.rb

This PR makes sure that specs involving the `on_queue` matcher keeps passing when the webhook worker is configured

fix(webhook): Fix specs when webhook worker is enabled

---

app/services/invoices/payments/adyen_service.rb
app/services/invoices/payments/cashfree_service.rb
app/services/invoices/payments/gocardless_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/payment_requests/payments/adyen_service.rb
app/services/payment_requests/payments/cashfree_service.rb
app/services/payment_requests/payments/gocardless_service.rb
app/services/payment_requests/payments/stripe_service.rb
spec/factories/payments.rb
spec/services/payment_requests/payments/cashfree_service_spec.rb

This PR is related to the recent changes introduced by https://github.com/getlago/lago-api/pull/2962 and https://github.com/getlago/lago-api/pull/2986 to rely on payment provider idem-potency logic
A new `payable_payment_status` was added to the Payment model, but this status is not updated when a webhook is received from a payment provider
This PR makes sure that the payment, payment request or all other payment related statuses are updated accordingly

fix(payment): Handle payment and invoice status update

---

app/models/fee.rb
app/services/fees/add_on_service.rb
app/services/fees/charge_service.rb
app/services/fees/commitments/minimum/create_service.rb
app/services/fees/create_pay_in_advance_service.rb
app/services/fees/init_from_adjusted_charge_fee_service.rb
app/services/fees/one_off_service.rb
app/services/fees/paid_credit_service.rb
app/services/fees/subscription_service.rb
spec/services/fees/add_on_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/commitments/minimum/create_service_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb
spec/services/fees/init_from_adjusted_charge_fee_service_spec.rb
spec/services/fees/one_off_service_spec.rb
spec/services/fees/paid_credit_service_spec.rb
spec/services/fees/subscription_service_spec.rb

When adding the column back in https://github.com/getlago/lago-api/pull/2858 I did not add specs for the saving of the organization_id. Because of Rails and how relationships were setup, this was not caught and did not result in errors. (just in not-filled-in column, which is not a big deal as the backfill is still to happen).

fix(Fee) - make sure organization_id is stored

---

db/migrate/20241220084758_fix_charge_properties_with_double_values.rb

When an organization have charges or charge filters with wrong properties, the migration fails and it's hard to indicate what exactly went wrong
Added rescue to migration that fixes double properties for charges and charges filters

add rescue when failing to update charge filters and charges

---

app/models/invoice.rb
app/services/customers/create_service.rb
spec/scenarios/invoices/invoice_numbering_spec.rb
spec/services/customers/create_service_spec.rb

There were small issues found during the QA
Fixed invoice numbering switching from customer-based to per-organization
Do not allow edit customers via API if they are not editable

Fix(rev-share): fix bugs found during QA

---

app/models/payment.rb
app/services/invoices/payments/adyen_service.rb
app/services/invoices/payments/cashfree_service.rb
app/services/invoices/payments/gocardless_service.rb
app/services/invoices/payments/stripe_service.rb
app/services/payment_requests/payments/adyen_service.rb
app/services/payment_requests/payments/cashfree_service.rb
app/services/payment_requests/payments/gocardless_service.rb
app/services/payment_requests/payments/stripe_service.rb
spec/services/invoices/payments/adyen_service_spec.rb
spec/services/invoices/payments/cashfree_service_spec.rb
spec/services/invoices/payments/gocardless_service_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb
spec/services/payment_requests/payments/adyen_service_spec.rb
spec/services/payment_requests/payments/cashfree_service_spec.rb
spec/services/payment_requests/payments/gocardless_service_spec.rb
spec/services/payment_requests/payments/stripe_service_spec.rb

This PR is related to https://github.com/getlago/lago-api/pull/3088 it ensure that none of the payment `status`, `payable_payment_status` and related payables's `payment_status` are updated if an unknown status is received from a payment provider

fix(payment): Ensure payment status is checkd as a string

---

app/controllers/webhooks_controller.rb
app/services/invoices/payments/cashfree_service.rb

Updated the Cashfree webhook integration to handle both sets of headers. Additionally, added `payment_type: "one-time"` to the link parameters to ensure the payment is created upon receiving the webhook.
I tested the flow with these changes in the actual Cashfree Test Environment, and everything is now functioning as expected.
fixes #3105

fix(cashfree): Fix webhook and payment flow

---

app/controllers/api/v1/invoices_controller.rb
app/serializers/v1/invoice_serializer.rb
app/serializers/v1/invoices/applied_tax_serializer.rb
app/services/coupons/preview_service.rb
app/services/invoices/preview_context_service.rb
app/services/invoices/preview_service.rb
config/routes.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature enables fetching first Lago invoice. This invoice is not persisted and is calculated on the fly.
This PR is the last one for the feature. It adds route, controller action and includes few fixes based on QA returns

feat(preview-invoice): add route and controller action

---

app/models/organization.rb
app/services/fees/charge_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/customer_usage_service.rb
app/services/invoices/progressive_billing_service.rb
schema.graphql
schema.json
spec/scenarios/invoices/adjusted_charge_fees_spec.rb
spec/scenarios/invoices/invoices_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
spec/services/invoices/refresh_draft_service_spec.rb
spec/services/invoices/subscription_service_spec.rb

This PR follow https://github.com/getlago/lago-api/pull/3020 the goal is to stop generating empty fees (0 units, amount and events without adjustments or true up fees).
The reason behind this change is scalability as for now, depending on the plan setups, it appears that 98% of generated fees does not have an amount...
**NOTE:** a new feature will improve the edit fees feature since this PR will prevent creation of adjustment fees from the UI if no event have been received for a specific billable metric on a period.

Reapply "feat(invoice): Avoid generating 0 amount charge fees (#3032)" (#3059)

---

db/migrate/20250103124802_drop_zero_amount_fees.rb

This PR removes the charge fees attached to finalized or voided invoices and having `amount = 0`.
In a close future, these fees will not be generated anymore, and the logic built around it will be refactored (adjusted fees, daily_usage computation...)

misc(fee): Delete zero amount finalized fees

---

app/services/invoices/payments/stripe_service.rb
spec/services/invoices/payments/stripe_service_spec.rb

Recently we added the possibility to pay an invoice with a stripe checkout url. The payment method used wasn't saved in stripe. This change will allow the customer to reuse this method next time.
When using the `/customers/:external_customer_id/checkout_url` you setup a payment method so the payment method is associated with the customer in Stripe.
When using `/invoices/:lago_id/payment_url` the payment method is used but not associated. This PR makes sure the payment method used is savec with the customer.
Related docs: https://docs.stripe.com/api/checkout/sessions/create#create_checkout_session-payment_intent_data-setup_future_usage
For now, we don't support offsession paiement in India so we don't et this parameter in case the customer is in India.
Note that **it's different** from …

feat(stripe): Save Payment Method in Customer when paying invoice with checkout url

---

app/controllers/api/v1/events_controller.rb
app/services/charges/estimate_instant/percentage_service.rb
app/services/events/calculate_expression_service.rb
app/services/events/validate_creation_service.rb
app/services/fees/batch_estimate_instant_pay_in_advance_service.rb
app/services/fees/estimate_instant_pay_in_advance_service.rb
app/services/fees/estimate_pay_in_advance_service.rb
config/routes.rb
db/schema.rb
spec/requests/api/v1/events_controller_spec.rb
spec/services/charges/estimate_instant/percentage_service_spec.rb
spec/services/events/validate_creation_service_spec.rb
spec/services/fees/batch_estimate_instant_pay_in_advance_service_spec.rb
spec/services/fees/estimate_instant_pay_in_advance_service_spec.rb
spec/services/fees/estimate_pay_in_advance_service_spec.rb

For some charge models, it's possible to speed up fee estimates. We're adding a new endpoint to support this use-case.

Feat(InstantEstimate) - estimate instant fees

---

app/services/integrations/aggregator/taxes/invoices/payload.rb
app/services/invoices/customer_usage_service.rb
spec/services/invoices/customer_usage_service_spec.rb

Initially, when fetching taxes from Anrok we used `fee.item_id` (`add_on_id`, `billable_metric_id`, `subscription_id`) as main identifier that helps us map received taxes with certain fee on Lago side.
First version worked well for real invoices, but also for current usage where we don't have ID persisted on fee.
However, there was a case where multiple charges are related to the same billable_metric (especially when one fee amount is zero and another is positive) and we were not able to perform mapping correctly: https://github.com/getlago/lago-api/pull/2842
However, one regression bug was produced with latest changes. Since `fee.id` is nil for current usage, taxes are not applied correctly in some scenarios.
This PR fixes described case

fix(current usage): fix current usage taxes

---

app/graphql/mutations/adjusted_fees/create.rb
app/graphql/types/adjusted_fees/create_input.rb
app/graphql/types/invoices/object.rb
app/models/invoice.rb
app/services/adjusted_fees/create_service.rb
app/services/billable_metrics/aggregations/base_service.rb
app/services/fees/init_from_adjusted_charge_fee_service.rb
schema.graphql
schema.json
spec/factories/invoices.rb
spec/graphql/mutations/adjusted_fees/create_spec.rb
spec/graphql/types/adjusted_fees/create_input_spec.rb
spec/graphql/types/invoices/object_spec.rb
spec/models/invoice_spec.rb
spec/scenarios/invoices/adjusted_charge_fees_spec.rb
spec/scenarios/invoices/adjusted_subscription_fees_spec.rb
spec/scenarios/invoices/invoices_spec.rb
spec/services/adjusted_fees/create_service_spec.rb

As a consequence of the removal of the 0 units fees removal from both DB and invoicing logic, we lost the ability to adjust fees without amount / units as the feature was expecting a fee to be present. This feature is a new approach to bring this functionality back.
This features refactors the `AdjustedFees::CreateService` and the `Mutations::AdjustedFees::Create` mutation to allow the creation of adjusted fees without pre-existing fees via the GraphQL API

misc(adjusted_fee): Allow fee adjustement without pre-existing fee

---

app/models/payment_provider_customers/stripe_customer.rb
schema.graphql
schema.json
spec/graphql/types/customers/customer_type_enum_spec.rb
spec/graphql/types/payment_provider_customers/provider_payment_methods_enum_spec.rb
spec/services/payment_providers/stripe/payments/create_service_spec.rb

We're adding support for Boleto payment method through Stripe 🇧🇷
Boleto requires 2 step. First the payment is initiated on Stripe and the customer receive a barcode to go pay IRL.
This PR has very little change because most of it already works and is already tested 😅 but it requires a fair amount of manual QA.
To test the integration, you can use [different email address as described in Stripe docs](https://docs.stripe.com/payments/boleto/accept-a-payment#test-integration). By default, boleto payment are completed after 3 minutes.

feat(boleto): Introduce Boleto as a valid Stripe Payment Method

---

app/services/add_ons/apply_taxes_service.rb
app/services/add_ons/create_service.rb
app/services/add_ons/destroy_service.rb
app/services/add_ons/update_service.rb
app/services/base_result.rb
app/services/base_service.rb
spec/services/base_result_spec.rb

As a requirement to enable YJIT compiler for Ruby, we need to get rid of OpenStruct as it leads to a huge memory consumption.
At the same time, we are lacking visibility on what properties are attached to result objects returned by services.
This PR introduces a new `BaseResult` result object, that should be used a a base in every services to define the attributes of a Result:
```ruby
module SomeModule
class SomeService < BaseService
Result = BaseResult[:attr_name1, :attr_name2]
```
To keep compatibility until all services are migrated to this approach, the `BaseService` is still relying on a `LegacyResult` using OpenStruct as a parent class.

misc: Introduce BaseResult to get rid of OpenStruct

---

Gemfile.lock
config/initializers/active_job_uniqueness.rb

We're sometimes getting errors related to Redis connections. based on https://github.com/redis-rb/redis-client/issues/116#issuecomment-1534406659 we shoud configure reconnection attempts to prevent these.

chore(versions): Bump redis related gems and configure reconnection in redlock

---

app/models/invoice.rb
spec/models/invoice_spec.rb

In certain countries, tax regulations require invoices to be labeled as **"Tax Invoice"** instead of just **"Invoice"** when taxes are applied.
This PR introduces a constant `TAX_INVOICE_LABEL_COUNTRIES` to centralize the list of countries that require this label. 
- Added `TAX_INVOICE_LABEL_COUNTRIES` (`%w[AU AE NZ ID SG]`) as a constant.
- Included **Singapore (SG)** as a country requiring the "Tax Invoice" label.

feat: add Singapore to tax invoices label countries

---

app/views/templates/credit_notes/self_billed.slim

removed Logo from self-billed credit note PDF

Fix(rev-share): do not display logo in credit note PDF

---

app/services/invoices/preview_context_service.rb
app/services/invoices/preview_service.rb
spec/services/invoices/preview_context_service_spec.rb

During invoice preview it's possible to override customer attributes only for preview invoice. Customer integrations appears to be saved to DB when it shouldn't.
Change the way to build customer integrations in preview to avoid persisting.
Improve test to cover this case.

fix(invoice-preview): Prevent customer updates during invoice preview

---

app/jobs/bill_paid_credit_job.rb

During the start of a new billing period, the system generates a large number of invoices, which in turn delays wallet top-up jobs. While other critical jobs like `Invoices::PrepaidCreditJob` and `WalletTransactions::CreateJob` have already been moved to the high-priority queue, `BillPaidCreditJob` remains in the default queue. 
This PR moves the `BillPaidCreditJob` to the high-priority queue.

feat: change BillPaidCreditJob to high_priority

---

app/controllers/api/v1/customers/usage_controller.rb
app/models/fee.rb
app/services/integrations/aggregator/taxes/base_service.rb
app/services/integrations/aggregator/taxes/invoices/payload.rb
app/services/invoices/customer_usage_service.rb
spec/requests/api/v1/customers/usage_controller_spec.rb
spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb
spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb
spec/services/invoices/customer_usage_service_spec.rb

When calling `GET /customers/:cust_id/current_usage?external_subscription_id=:sub_id` Lago computes the current usage
The taxes are computed by a thrid party (Anrok through Nango). We originally implemented a cache to avoir http calls to third party but it comes with drawbacks. We recently [tried to improve this](https://github.com/getlago/lago-api/pull/3115).
After investigation we believe it's best to remove the cache.
- If you get an error due to third party, you can call again without taxes
- In case you only need pre-tax amounts (like for b2b), passing `apply_taxes: false` will be more performant
- https://github.com/getlago/lago-openapi/pull/332

fix(anrok): Remove cache for Current Usage

---

app/services/invoices/advance_charges_service.rb
spec/scenarios/invoices/advance_charges_spec.rb
spec/services/invoices/advance_charges_service_spec.rb

Today, for `in_advance_charge_periodic` invoices, an `invoice_subscription` is generated for all `active` and `terminated` matching the provided `subscription#external_id` no matter the real presence of in advance fees not yet attached to an invoice.
It leads to issues with the invoice related Webhooks/API responses as every invoice_subscription will be exposed in the `billing_periods` attribute
See https://github.com/getlago/lago-api/pull/3012
This PR ensures that only subscriptions really having at least one fee is attached to the invoice 
🎁 This also ensure the job early returns if no invoice is going to be generated.

fix(fees): Avoid empty invoice subscription on regroup fees

---

spec/graphql/mutations/customer_portal/download_invoice_spec.rb
spec/graphql/mutations/invoices/download_spec.rb
spec/scenarios/coupons_breakdown_spec.rb
spec/scenarios/customers/update_invoice_grace_period_spec.rb
spec/scenarios/taxes_on_invoice_spec.rb
spec/services/credit_notes/generate_service_spec.rb
spec/services/invoices/generate_pdf_service_spec.rb

There is a helper to stub PDF generation and many tests didn't use it. Instead of mocking multiple services, it mocks the HTTP requests to the gotemberg service.

chore(spec): Use `stub_pdf_generation` helper

---

spec/services/invoices/payments/create_service_spec.rb
spec/services/payment_requests/payments/create_service_spec.rb
spec/services/webhook_endpoints/update_service_spec.rb

Some test uses OpenStruct where I think it should be a double.
Piece by piece we'll get rid of every OpenStruct usage 😝

chore(spec): Use instance_double instead of OpenStruct

---

app/graphql/types/data_exports/credit_notes/filters_input.rb
app/graphql/types/data_exports/invoices/filters_input.rb
app/services/data_exports/csv/credit_notes.rb
app/services/data_exports/csv/invoices.rb
schema.graphql
schema.json
spec/services/data_exports/csv/credit_notes_spec.rb
spec/services/data_exports/csv/invoices_spec.rb
spec/services/data_exports/process_part_service_spec.rb

When invoices are self-billed, we want to indicate them in data-exports
Added self_billed to filter inputs for invoices and credit notes data exports
Modified data export csv to include info if the invoice is self-billed

Fix(revenue-share): add self-billed field to data exports

---

app/services/payment_requests/payments/create_service.rb
spec/services/payment_requests/payments/create_service_spec.rb

In some cases, payment failure emails were not being sent when the BaseService::ServiceFailure was raised during payment processing. This was causing missed notifications for failed payment attempts
Ensured that PaymentRequestMailer.with(payment_request: payable).requested.deliver_later is called both when a payment fails and when a ServiceFailure is raised

feat: added PaymentRequestMailer on rescue

---

app/graphql/types/invoice_subscriptions/object.rb
schema.graphql
schema.json
spec/graphql/types/invoice_subscriptions/object_spec.rb

We recently added a new attribute on GraphQL that combines a new field with a new associated definition.
The two were named differently tho.
This PR makes sure we have the same name on the field and it's associated method.
c.f. https://github.com/getlago/lago-api/pull/3152

chore(GraphQL): rename invoice subscription attribute

---

app/jobs/invoices/update_all_invoice_grace_period_from_organization_job.rb
app/jobs/invoices/update_grace_period_from_organization_job.rb
app/models/invoice.rb
app/services/invoices/update_all_invoice_grace_period_from_organization_service.rb
app/services/invoices/update_grace_period_from_organization_service.rb
app/services/organizations/update_invoice_grace_period_service.rb
db/migrate/20250207094842_add_applied_grace_period_to_invoices.rb
db/migrate/20250207142402_backfill_applied_grace_period_on_draft_invoices.rb
db/schema.rb
spec/jobs/invoices/update_all_invoice_grace_period_from_organization_job_spec.rb
spec/jobs/invoices/update_grace_period_from_organization_job_spec.rb
spec/services/invoices/update_all_invoice_grace_period_from_organization_service_spec.rb
spec/services/invoices/update_grace_period_from_organization_service_spec.rb
spec/services/organizations/update_invoice_grace_period_service_spec.rb
spec/services/organizations/update_service_spec.rb

The grace period update service was not built to deal with many (>100k) draft invoices. This means that some issuing_dates could be set incorrectly if the request timed out. This PR moves the update to an asynchronous job.
For idempotency reasons it's important to store the applied_grace_period on the invoice, this way we can be certain that we're not running the job twice.

bug(GracePeriod) - Make grace period update async for increased reliability

---

app/services/base_service.rb
app/services/events/create_service.rb
spec/requests/api/v1/events_controller_spec.rb
spec/services/events/create_service_spec.rb

Currently /api/v1/events fails with a 500 error due to incomplete error propagation.
This PR addresses this by propagating the error as a validation error.

bug(Event): Propagate expression evaluation failure 

---

app/services/invoices/preview_service.rb
spec/services/invoices/preview_service_spec.rb

Some clients want to override address in preview feature. Address is one of the parameters that determine tax and we decided to always fetch fresh taxes in preview feature

fix: Remove tax cache from invoice preview

---

app/services/customer_portal/customer_update_service.rb
app/services/customers/create_service.rb
app/services/customers/eu_auto_taxes_service.rb
app/services/customers/update_service.rb
spec/services/customer_portal/customer_update_service_spec.rb
spec/services/customers/create_service_spec.rb
spec/services/customers/eu_auto_taxes_service_spec.rb
spec/services/customers/update_service_spec.rb

This PR tries to reduce calling EU tax service in certain conditions.
The goal is NOT to call the service if customer is updated, there are existing EU taxes and tax relevant customer attributes haven't changed

fix: prevent calling eu tax service when not needed

---

app/controllers/api/base_controller.rb
app/controllers/api/v1/events_controller.rb
app/models/api_key.rb
app/services/api_keys/cache_service.rb
app/services/api_keys/destroy_service.rb
app/services/api_keys/rotate_service.rb
app/services/api_keys/update_service.rb
app/services/organizations/update_service.rb
spec/models/api_key_spec.rb
spec/services/api_keys/cache_service_spec.rb

This PR is part of a global initiative to improve the performance of the LAGO Rest API.
Today every request made received by the API leads to at least two database queries to authenticate the organization. A first one is fetching the `api_key` using the provided bearer token from the HTTP header, the second one loads the related `organization`.
As by nature, api_keys and organizations are not update really often, adding a caching strategy could reduce drastically the time consumed authenticating the organization.
This PR changes the authentication mechanism by:
- Adding a dedicated cache service for API key. It default to no cache unless cache is explicitly turned on.
- If cache is on:
- Checking for cached api_key and organization
- Fetching the values from the DB is no cache is present …

feat(api_key): cache api key and organization

---

app/controllers/dev_tools/invoices_controller.rb
app/mailers/application_mailer.rb
app/mailers/credit_note_mailer.rb
app/mailers/invoice_mailer.rb
app/mailers/payment_request_mailer.rb
app/models/organization.rb
app/views/layouts/mailer.slim
app/views/templates/credit_notes/_powered_by_logo.slim
app/views/templates/credit_notes/credit_note.slim
app/views/templates/credit_notes/self_billed.slim
app/views/templates/invoices/v4.slim
app/views/templates/invoices/v4/_powered_by_logo.slim
app/views/templates/invoices/v4/charge.slim
app/views/templates/invoices/v4/one_off.slim
app/views/templates/invoices/v4/self_billed.slim
schema.graphql
schema.json

Lago adds a logo at the bottom of invoices and emails.
This premium addon allows Lago users to remove the Lago branding from customer facing invoice and emails.

New `remove_branding_watermark` Premium addons

---

.git-blame-ignore-revs

See https://github.com/getlago/lago-api/pull/3167

chore(git): Add #3167 to .git-blame-ignore-revs

---

app/services/integrations/aggregator/invoices/payloads/base_payload.rb
app/services/integrations/aggregator/invoices/payloads/netsuite.rb
spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
spec/services/integrations/aggregator/invoices/payloads/xero_spec.rb

Invoices synced to Netsuite don't contain line item for already billed usage (progressive billing).
Add already billed usage as credit to Netsuite and Xero invoices.

fix(integrations): Fix invoices with progressive billing

---

app/services/daily_usages/compute_service.rb
app/services/daily_usages/fill_from_invoice_service.rb
app/services/daily_usages/fill_history_service.rb
spec/jobs/daily_usages/compute_job_spec.rb
spec/services/daily_usages/compute_service_spec.rb
spec/services/daily_usages/fill_from_invoice_service_spec.rb

The daily usage is needed for the data part of Lago. Currently it contains a lot of useless information due to 0 unit fees.
The goal of this PR is to not populate those fees inside the daily usages.

feat(data): Compute daily usages for positive fees only

---

app/jobs/send_webhook_job.rb
app/jobs/wallet_transactions/create_job.rb
app/services/invoices/payments/deliver_error_webhook_service.rb
app/services/wallet_transactions/create_service.rb
app/services/wallet_transactions/validate_service.rb
app/services/wallets/balance/decrease_service.rb
app/services/wallets/balance/increase_service.rb
app/services/wallets/create_service.rb
app/services/wallets/terminate_service.rb
app/services/wallets/update_service.rb
app/services/webhooks/wallets/created_service.rb
app/services/webhooks/wallets/terminated_service.rb
app/services/webhooks/wallets/updated_service.rb
spec/graphql/mutations/wallets/create_spec.rb
spec/graphql/mutations/wallets/terminate_spec.rb
spec/graphql/mutations/wallets/update_spec.rb
spec/jobs/wallet_transactions/create_job_spec.rb
spec/requests/api/v1/wallets_controller_spec.rb
spec/serializers/v1/wallet_serializer_spec.rb
spec/services/invoices/payments/deliver_error_webhook_service_spec.rb
spec/services/wallet_transactions/create_service_spec.rb
spec/services/wallets/balance/decrease_service_spec.rb
spec/services/wallets/balance/increase_service_spec.rb
spec/services/wallets/create_service_spec.rb
spec/services/wallets/terminate_service_spec.rb
spec/services/wallets/update_service_spec.rb
spec/services/webhooks/wallets/created_service_spec.rb
spec/services/webhooks/wallets/terminated_service_spec.rb
spec/support/queues_helper.rb
spec/support/scenarios_helper.rb

Wallet operations trigger 3 webhooks today: 
* `wallet.depleted_ongoing_balance`
* `wallet_transaction.updated`
* `wallet_transaction.payment_failure`.
We want to add the following: 
* `wallet.created`
* `wallet.updated`
* `wallet.terminated`
https://docs.getlago.com/api-reference/webhooks/messages#wallets-and-prepaid-credits
~Notice that the webhook job is dispatched by `WalletTransactions::CreateJob` so the wallet sent in the webhook has the initial balance instead of 0. Unlike the API which returns 0.~
~The `WalletTransactions::CreateJob` is always dispatch even if the `WalletTransactions::CreateService` might do nothing.~
Notice that the webhook job is dispatched as soon as the wallet is created so the initial balance can be 0. The API always returns balance = 0 when creating a …

feat(wallet): New `wallet.(created|updated|terminated)` webhooks

---

app/controllers/api/v1/invoices_controller.rb
app/services/invoices/preview_context_service.rb
app/services/invoices/preview_service.rb
spec/services/invoices/preview_context_service_spec.rb
spec/services/invoices/preview_service_spec.rb

With invoice preview feature, customers will have possibility to check how next invoice will look like
This is the first PR in second part that covers persisted subscriptions. Here is the setup for multiple subscription and there is added validation that ensures that multiple subscriptions has the same currency.
Since part 1 is already released, second part PRs will be created from part 2 feature branch: `ftr-invoice-preview-two`

feat(invoice-preview): add base multiple subscription setup

---

app/services/charges/amount_details/range_graduated_percentage_service.rb
app/services/charges/charge_models/percentage_service.rb
app/services/charges/estimate_instant/percentage_service.rb
spec/services/charges/amount_details/range_graduated_percentage_service_spec.rb
spec/services/charges/charge_models/percentage_service_spec.rb
spec/services/charges/estimate_instant/percentage_service_spec.rb

Percentage charges have rounding issues with smaller units and decimal rates.
E.g this code
```ruby
amount = units * rate.fdiv(100)
```
produces rounding issues.
```ruby
rate = BigDecimal("2.9") # service always converts it to BigDecimal
units = 4
units * rate.fdiv(100) # => 0.11599999999999999
units * rate.fdiv(100).class # => Float
units * rate / 100 # => 0.116
(units * rate / 100).class # => BigDecimal
```
The issue that `.fdiv(100)` returns result as Float, in our case downgrading from BigDecimal to Float.
In changes cases we always have BigDecimal, so it's safe to use `/` instead of `fdiv`.
Btw, another way to address this issue by using `.fdiv(BigDecimal("100"))` which for me looks horrible.
Adjusted percentage calculation to return expected results with smaller amount.s
Adjusted …

fix(fee-estimation): fix rounding when small amounts provided

---

.rubocop.yml
app/services/dunning_campaigns/update_service.rb
db/migrate/20221010142031_update_credit_notes.rb
db/migrate/20230216145442_change_webhooks_object_nullable.rb
db/migrate/20231117123744_add_organization_id_to_quantified_events.rb
db/migrate/20240314163426_add_multiple_values_to_charge_filter_values.rb
db/migrate/20240425131701_update_cached_aggregations.rb
db/migrate/20240808080611_remove_amount_currency_from_usage_tresholds.rb
dev/cops/service_call_cop.rb
lib/tasks/tests/seed_plans.rake

As I'm fixing the quotes for string literals, there are other errors showing up so let's fix those. I'm going to merge this one first before updating the quote PRs.
Many of them are about old migrations that I don't think we should change. I simply disabled the rule for them.
`Cops/ServiceCallCop` was renamed `Lago/ServiceCall` and I excluded the services failing. It's not so easy to fix in this kind of cosmetic PR but it should be done one day.
> 3234 files inspected, no offenses detected

chore(rubocop): Disable or fix last errors

---

app/services/integrations/aggregator/base_service.rb
spec/services/integrations/aggregator/base_service_spec.rb

We never raise `RequestLimitError` because `request_limit_error?` never returns true
This PR fixes `request_limit_error?` method so that we can process rate limit errors properly.

fix(rate-limit): Fix rate limit errors

---

app/services/invoices/payments/retry_service.rb
spec/services/invoices/payments/retry_service_spec.rb

We we retry payment for invoice we send webhook but `progressive_billing` invoices were missing their webhook.
Add missing webhook.

fix(invoice-webhooks): Fix progressive billing invoice not having webhook on payment retry

---

app/services/integrations/aggregator/invoices/payloads/base_payload.rb
app/services/integrations/aggregator/invoices/payloads/netsuite.rb
spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb
spec/services/integrations/aggregator/invoices/payloads/xero_spec.rb

Invoices synced to Netsuite don't contain line item for already billed usage (progressive billing).
Add already billed usage as credit to Netsuite and Xero invoices.

fix(invoices): Fix progressive billing

---

app/jobs/send_webhook_job.rb
app/services/subscriptions/create_service.rb
app/services/subscriptions/update_service.rb
app/services/webhooks/subscriptions/updated_service.rb
spec/jobs/send_webhook_job_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/subscriptions/update_service_spec.rb
spec/services/webhooks/subscriptions/updated_service_spec.rb

When downgrading a plan customers won't receive a webhook right away.
We're adding a new webhook  `subscription.updated` that called in case of downgrade or update of subscription.

feat(webhooks): Add subscription updated webhook

---

app/controllers/api/v1/invoices_controller.rb
app/services/invoices/preview_context_service.rb
app/services/invoices/preview_service.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/invoices/preview_context_service_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature allows to see first invoice preview. It works for both non-existing subscriptions but also for active subscriptions.
This PR adds missing logic in order to properly handle persisted subscriptions

feat(invoice-preview): update logic for multiple peristed subscriptions

---

app/services/fees/create_pay_in_advance_service.rb
app/services/invoices/advance_charges_service.rb
app/services/invoices/aggregate_amounts_and_taxes_from_fees.rb
spec/scenarios/invoices/advance_charges_spec.rb
spec/scenarios/invoices/advance_charges_taxes_spec.rb
spec/services/invoices/advance_charges_service_spec.rb
spec/services/invoices/aggregate_amounts_and_taxes_from_fees_spec.rb

Using Fees with the following attributes, you will get an invoice at the end of the period that regroups all PAID fees.
* pay_in_advance: true
* invoiceable: false
* regroup_paid_fees: 'invoice'
The taxes on these fees are computed for each fee. The final invoice should show the amount of taxes actually paid, not the amount of taxes that would have been paid if the fees were paid at once in a single invoice invoice.
**Example**
Fee 1:
* amount_cents: 12
* taxes: 20%
* taxes_amount_cents: 2.4 rounded to 2
Fee 2:
* amount_cents: 12
* taxes: 20%
* taxes_amount_cents: 2.4 rounded to 2
Final invoice:
* 2 fees 
* fees_amount_cents: 24 (12 * 2)
* taxes_amount_cents: **4 if you sum the existing fees, but 20% of 24 is 4.8, rounded to 5**
* total_amount_cents: 28 with this PR (actually paid taxes) …

feat(regroup_fee): Sum fees to get invoice totals instead of recomputing taxes

---

app/models/organization.rb
app/services/invoices/preview_service.rb
schema.graphql
schema.json
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature allows to see first invoice preview. It works for both non-existing subscriptions but also for active subscriptions.
This PR adds premium add-on validation for part 2 and part 3, where preview invoice is generated on existing subscriptions. Only lightweight preview invoice with subscription fee is enabled without premium add-on (only basic license is needed).

feat(invoice-preview): add premium addon validation and apply small refactoring

---

app/jobs/daily_usages/fill_history_job.rb
config/sidekiq/sidekiq.yml

The goal of this PR is to introduce a new Sidekiq queue `long_running` and extract `DailyUsages::FillHistoryJob` to that queue.
Indeed, we've seen in the past that running such a one-time job can be long and delay the execution of other tasks inside the `low_priority` queue.

misc: Extract DailyUsages::FillHistoryJob to a new long_running queue

---

app/jobs/invoices/payments/create_job.rb

Currently, creating a payment is done in the `low_priority` sidekiq queue.
It seems that we want to increase the priority of this job, by moving it to the `default` queue.

misc: Change queue from low_priority to default when creating a payment

---

app/services/payment_providers/stripe/webhooks/customer_updated_service.rb
spec/services/payment_providers/stripe/webhooks/customer_updated_service_spec.rb

Some `customer.updated` Stripe webhooks are failing with a `stripe_customer_not_found` error.
The metadata of the webhook payload includes a `lago_customer_id`, meaning that it was initially created from Lago and should be found in the database.
After some investigation it appears that a deleted `StripeCustomer` is present in the database meaning the the webhook should not raise an error but should instead be ignored.
This PR checks for the presence of a deleted `stripe_customer` to return an empty success result when a deleted one is found in the database.

fix(stripe): Avoid raising not_found for deleted stripe customers

---

app/models/add_on.rb
spec/models/add_on_spec.rb

This PR adds a presence validation on the `code` property of `add_on`, to make sure `an HTTP 422` is returned from the REST API instead of a `500`

fix(add_on): Validate presence of code

---

app/services/invoices/provider_taxes/pull_taxes_and_apply_service.rb
spec/services/invoices/provider_taxes/pull_taxes_and_apply_service_spec.rb

Whenever we refresh the taxes of an invoice with an invalid status (not `pending`), we return an error and there's a deadjob.
The purpose of this PR is to prevent having deadjobs and return a successful result in that case without processing anything.

fix: Don't raise error when invoice's status is invalid

---

app/services/payment_provider_customers/stripe/check_payment_method_service.rb
app/services/payment_provider_customers/stripe_service.rb
app/services/payment_providers/stripe/payments/create_service.rb
spec/services/payment_provider_customers/stripe/check_payment_method_service_spec.rb
spec/services/payment_provider_customers/stripe_service_spec.rb
spec/services/payment_providers/stripe/payments/create_service_spec.rb

When we delete a customer, all related subscriptions are terminated and a termination invoice is generated. If the customer is linked to a payment provider, the system will try to collect it.
Some error will be raised as the application will not be able to find the discarded record in the database 
This PR extract the `PaymentProviderCustomers::StripeService#check_payment_method` into a dedicated `PaymentProviderCustomers::CheckPaymentMethodService` and makes sure it relies only on the `stripe_customer` to fetch the payment method.

fix(payment): Handle deleted customers

---

app/services/integration_customers/create_service.rb

This PR makes sure that we the `IntegrationCustomers::CreateService` does not raise an `ActiveRecord::RecordNotUnique` when two creation attempts are executed at the time but instead returns the unique `integration_customer`

fix(integration): Avoid raising RecordNotUnique on race condition

---

app/services/daily_usages/compute_service.rb
app/services/daily_usages/fill_from_invoice_service.rb
app/services/daily_usages/fill_history_service.rb
spec/services/daily_usages/compute_service_spec.rb
spec/services/daily_usages/fill_from_invoice_service_spec.rb

This PR includes improvements to the `DailyUsages::ComputeService` class to ensure better handling of daily usage records and their associated fees. The changes include adding conditions to **filter out zero-unit fees**.
In an effort of improving performances of daily usages, we decided to not create daily usage records when there is no subscription usage (`total_amount_cents: 0`).

feat(data): Do not create daily usage when no usage

---

app/services/credit_notes/refunds/stripe_service.rb
app/services/payment_providers/gocardless/handle_event_service.rb
app/services/payment_providers/stripe/webhooks/charge_dispute_closed_service.rb
spec/services/credit_notes/refunds/stripe_service_spec.rb

This PR improve the handling of some payment provider's webhooks:
- `payment_not_found` for Stripe `charge.dispute.closed` webhook
- `payment_not_found` for GoCardless refund `failed` webhook
The PR also improve the handling of the `Stripe::InvalidRequestError` when refunding a payment, by preventing the re-raise of the error when the failure is `Refunds are not supported on this payment method.`

fix(webhook): Handle errors with payment and refunds

---

app/mailers/credit_note_mailer.rb
app/mailers/invoice_mailer.rb
spec/mailers/credit_note_mailer_spec.rb
spec/mailers/invoice_mailer_spec.rb

Currently, invoices and credit notes attached to emails are named generically (e.g., invoice.pdf, credit_note.pdf). This makes it difficult for customers to organize and retrieve specific documents especially when dealing with multiple invoices or credit notes.
This PR improves the naming by including the number in the attachments file names:
- For invoices: `invoice-NUMBER.pdf`
- For credit notes: `credit_notes-NUMBER.pdf`

misc(mailer): Improve attachements names

---

app/services/credit_notes/refunds/stripe_service.rb
spec/services/credit_notes/refunds/stripe_service_spec.rb

This PR improves https://github.com/getlago/lago-api/pull/3200 by relying on the error code rather than on the error message

misc(stripe): Improve error code handling

---

app/models/customer.rb
spec/models/customer_spec.rb
spec/services/customers/create_service_spec.rb

Some errors are raised on api when sending and invalid `customer_type` to `POST /api/v1/customers`
The server raises the following error: `ArgumentError 'xxx' is not a valid customer_type (ArgumentError)` and returns an HTTP 500
This PR adds a validation rule on the `customer_type` enum, making sure that teh API will return an `HTTP 422`

fix(customer): Add validation om customer type

---

app/jobs/integrations/aggregator/invoices/create_job.rb

This PR adds an auto retry logic for `Net::ReadTimeout` error on `Integrations::Aggregator::Invoices::CreateJob`

misc(integration): Add retry for invoice creation on Net::ReadTimeout

---

spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb

There is a flacky test (main branch is failing). I believe this is because the mock is relying on the order of the fees, maybe `array_including` will fix it.
Ideally, we should rely on webmock instead of mocking the class.

fix(spec): tentative fix for flacky test

---

app/services/fees/charge_service.rb
app/services/invoices/preview_service.rb
spec/services/fees/charge_service_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature allows to see first invoice preview. It works for both non-existing subscriptions but also for active subscriptions.
This PR adds support for charges for subscriptions that are persisted in the DB.

feat(invoice-preview): add charges support

---

app/models/billing_entity.rb
db/migrate/20250219124948_create_billing_entities.rb
db/schema.rb
spec/factories/billing_entities.rb
spec/models/billing_entity_spec.rb

👉  https://getlago.canny.io/feature-requests/p/support-billing-from-multiple-entities
Add billing entity model as a starting point to kick off this feature development.

feat(multi-entities): Add billing entity model

---

app/models/payment_provider_customers/stripe_customer.rb
app/services/invoices/payments/stripe_service.rb
app/services/payment_provider_customers/stripe_service.rb
schema.graphql
schema.json
spec/graphql/types/payment_provider_customers/provider_payment_methods_enum_spec.rb

* Add `crypto` to the list of available payment methods
* When generating customer checkout url, we remove crypto from the list because it cannot be used in setup mode
* When paying an invoice with crypto, the same `payment_intent.succeeded` stripe webhook is sent so we correctly update the invoice payment status

feat(stripe): Add Stripe `crypto` payment method

---

config/initializers/console.rb

This PR adds some helpers that I like to use locally. I use Hooli and Gavin's user account when developing to 2 methods let's you retrieve the org and the user easily.
The third one let's you delete all the webhooks for the hooli work so when testing, you can get rid of all previous webhooks for some clarity.

feat(dev): Add console helpers for local development

---

app/models/payment.rb
db/migrate/20250220085848_add_unique_index_to_provider_payment_id.rb
db/schema.rb

We have seen some duplicate payments due to a race condition when receiving two stripe webhooks at the same time.
The objective of this PR is to add a unique constraint for the table `payments`, on the columns `provider_payment_id` and `payment_provider_id`.
We took the opportunity to fix invalid `total_paid_amount_cents` on the impacted invoices.

fix: Add unique index on payment provider id

---

app/views/helpers/money_helper.rb
config/locales/de.yml
config/locales/en.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/it.yml
config/locales/nb.yml
config/locales/sv.yml
spec/views/helpers/money_helper_spec.rb

This PR fixes https://github.com/getlago/lago-api/issues/3129
This PR will keep using symbols on invoice for currencies using "well known" symbols (`$`, `€`, `£` and `¥`) but will fallback on ISO codes for others:
- `100 USD`, or `100 CAD` will still be rendered as `$100.00`
- `100 BHD` will be rendred as `BHD 100.000`
The local is also taken into account, for example with french locale:
- `100 USD`, or `100 CAD` will still be rendered as `100.00 $`
- `100 BHD` will be rendred as `100.000 BHD`

fix(currency): Use some ISO codes instead of symbols

---

db/migrate/20250219205535_fix_invoices_with_incorrect_total_paid_amount.rb

During a backfill migration, we updated all invoices with payment_status: succeeded by setting:
``` ruby
Invoice.where(payment_status: Invoice::PAYMENT_STATUS[:succeeded])
.update_all("total_paid_amount_cents = total_amount_cents")
```
However, some invoices were marked as fully paid without ever receiving payments or payment requests. This led to incorrect total_paid_amount_cents, affecting refund calculations.
we need to revert this value back to zero on this cases so we don't have wrong values on the refundable_amount_cents
SQL Used for Validation
``` sql
SELECT *
FROM invoices
LEFT JOIN payments ON invoices.id = payments.payable_id
LEFT JOIN invoices_payment_requests ON invoices.id = invoices_payment_requests.invoice_id
WHERE payments.id IS NULL 
AND invoices_payment_requests.id IS …
```

fix(manual_payments): Fix Incorrect total_paid_amount_cents for Invoices Without Payments

---

app/graphql/types/integrations/anrok.rb
app/graphql/types/integrations/netsuite.rb
app/graphql/types/integrations/okta.rb
app/graphql/types/obfuscated_string_type.rb
app/graphql/types/payment_providers/adyen.rb
app/graphql/types/payment_providers/stripe.rb
schema.graphql
schema.json
spec/graphql/types/integrations/anrok_spec.rb
spec/graphql/types/integrations/netsuite_spec.rb
spec/graphql/types/payment_providers/adyen_spec.rb
spec/graphql/types/payment_providers/stripe_spec.rb

For api keys or token, the graphql exposes a string with dots and only shows the last 3 characters.
This PR introduces a custom `ObfuscatedStringType` to our graphql schema so you don't have to redeclare it every time you need to hide a sensitive information.

feat(gql): Introduce ObfuscatedStringType

---

spec/rails_helper.rb
spec/spec_helper.rb
spec/support/pdf_helper.rb

Currently, we have both `spec_helper.rb` and `rails_helper.rb`.
My main goal was to merge them so we have only one place defining all the before/after actions. I realized that we could get rid of the rails_helper file entirely, so we don't have to require it manually anymore.
Any reason you'd like to keep it?

chore(spec): Merging rails_helper into spec_helper

---

app/controllers/api/v1/invoices_controller.rb
app/models/organization.rb
app/services/fees/charge_service.rb
app/services/invoices/preview_context_service.rb
app/services/invoices/preview_service.rb
schema.graphql
schema.json
spec/graphql/types/integrations/premium_integration_type_enum_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/invoices/preview_context_service_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature allows to see first invoice preview. It works for both non-existing subscriptions but also for active subscriptions.
This PR includes feature branch.
Following PRs were already reviewed and and this feature branch does not contain any change outside of these PRS:
-https://github.com/getlago/lago-api/pull/3222
-https://github.com/getlago/lago-api/pull/3206
-https://github.com/getlago/lago-api/pull/3190
-https://github.com/getlago/lago-api/pull/3185
-https://github.com/getlago/lago-api/pull/3173

feat(invoice-preview): generating invoice review for existing subscriptions

---

app/services/invoices/payments/stripe_service.rb
app/services/payment_requests/payments/stripe_service.rb

This PR is related to https://github.com/getlago/lago-api/pull/3223
Since the introduction of the index on `payments(payment_provider_id, provider_payment_id)` an `ActiveRecord::RecordNotUnique` is raised if two concurrent stripe webhooks are handled by the system. This PR makes sure that it does not end in a dead jobs.
NOTE: https://github.com/getlago/lago-api/pull/3228 will drastically reduce the risk of concurrent status update

fix(stripe): Avoid raising for concurent status update

---

app/services/integrations/aggregator/contacts/payloads/netsuite.rb

We currently receive deadjobs when trying to sync customers on Netsuite.
This is because `state` sent contains more characters than the maximum size allowed by Netsuite (`30`).
Deadjob:
> action_script_runtime_error: The field state contained more than the maximum number ( 30 ) of characters allowed.
The goal of this PR is to only select the first 30 characters for the state when creating a customer on Netsuite.

fix(netsuite): Prevent trying to create customer with max netsuite state reached

---

app/jobs/invoices/provider_taxes/pull_taxes_and_apply_job.rb
app/services/integrations/aggregator/base_service.rb
app/services/integrations/aggregator/taxes/invoices/create_draft_service.rb
app/services/integrations/aggregator/taxes/invoices/create_service.rb
lib/lago_http_client/lago_http_client/client.rb
spec/fixtures/integration_aggregator/bad_gateway_error.html
spec/services/integrations/aggregator/taxes/invoices/create_draft_service_spec.rb
spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb

Sometime jobs to fetch taxes from Anrock are failing with a `JSON::ParseError`. It happens because the server is responding with an `HTTP 200` even if the message contains the HTML markup for an `HTTP 502 Bad Gateway`...   
This PR adds some logic to detect the presence of the error in the response body and re-reraise the right error for a correct handling, in this case an auto-retry of job

fix(integration): Fix error handling for Bad Gateway errors received as HTTP 200

---

app/jobs/bill_non_invoiceable_fees_job.rb

During monthly billing we can spend a lot of time enqueueing jobs (which we do every hour). In order to avoid duplication of billing jobs, we should mark them as unique. (Similar to what we did for the BillSubscriptionJob).
I've opted for a 4 hour lock window instead of 12 hours.

feat(Uniqueness) - Mark BillNonInvoiceableFeesJob as unique

---

app/models/billing_entity.rb
app/models/billing_entity/applied_tax.rb
app/models/tax.rb
db/migrate/20250219164502_create_billing_entities_taxes.rb
db/schema.rb
spec/factories/billing_entity_applied_taxes.rb
spec/models/billing_entity/applied_tax_spec.rb
spec/models/billing_entity_spec.rb
spec/models/tax_spec.rb

Add billing entities applied taxes

feat(multi-entities): Add billing entities applied taxes relationship

---

app/models/billing_entity.rb
app/models/customer.rb
app/models/fee.rb
app/models/invoice.rb
app/models/invoice_custom_section_selection.rb
app/models/organization.rb
app/models/subscription.rb
db/migrate/20250219152213_add_references_to_billing_entities.rb
db/schema.rb
spec/factories/billing_entities.rb
spec/factories/customers.rb
spec/factories/fees.rb
spec/factories/invoices.rb
spec/factories/organizations.rb
spec/models/billing_entity_spec.rb
spec/models/customer_spec.rb
spec/models/invoice_spec.rb
spec/models/organization_spec.rb

After we created the billing_entity model itself, we want to add references to it from different model that should be separated by billing entities
Added references to billing_entities
Added creation of default billing_entity when creating an organization
Updated tests

Feat(multi-entities): add references to and from billing_entity

---

app/services/integrations/aggregator/contacts/payloads/netsuite.rb

We currently receive deadjobs when trying to sync customers on Netsuite.
This is because `state` sent contains more characters than the maximum size allowed by Netsuite (`30`).
Deadjob:
> action_script_runtime_error: The field addr1 contained more than the maximum number ( 150 ) of characters allowed.
The goal of this PR is to only select the first 30 characters for the state when creating a customer on Netsuite.

fix(netsuite): Use max length when creating netsuite customer

---

app/models/payment_provider_customers/stripe_customer.rb
app/services/integration_customers/create_or_update_service.rb
app/services/payment_providers/stripe/payments/create_service.rb
schema.graphql
schema.json
spec/graphql/types/payment_provider_customers/provider_payment_methods_enum_spec.rb
spec/models/payment_provider_customers/stripe_customer_spec.rb
spec/services/payment_providers/stripe/payments/create_service_spec.rb

Lago does not currently support Bank Transfer payments for users receiving payouts through Stripe’s customer balance. This PR adds support for this payment method to accommodate use cases where Bank Transfers are required.
Added support for Bank Transfer payments when using Stripe’s customer balance.
Updated relevant service logic to handle this payment method.

Feat stripe bank transfers

---

app/config/permissions/definition.yml
app/config/permissions/role-finance.yml
app/config/permissions/role-manager.yml
app/graphql/resolvers/data_api/revenue_streams_resolver.rb
app/graphql/types/data_api/revenue_streams/object.rb
app/graphql/types/data_api/time_granularity_enum.rb
app/graphql/types/query_type.rb
schema.graphql
schema.json
spec/graphql/resolvers/data_api/revenue_streams_resolver_spec.rb
spec/graphql/types/data_api/revenue_streams/object_spec.rb
spec/graphql/types/data_api/time_granularity_enum_spec.rb

**Context**
This pull request extracts revenue streams resolver to `data_api` namespace.

feat(data): Extract revenue streams resolver to data_api namespace

---

app/graphql/resolvers/data_api/revenue_streams_resolver.rb
schema.graphql
schema.json
spec/graphql/resolvers/data_api/revenue_streams_resolver_spec.rb

**Context**
This pull request renames `customerCurrency` parameter to `currency` for revenue streams.

feat(data): Rename customerCurrency to currency for revenue streams

---

app/controllers/api/v1/invoices_controller.rb
app/services/invoices/preview/subscriptions_service.rb
app/services/invoices/preview_context_service.rb
spec/services/invoices/preview/subscriptions_service_spec.rb
spec/services/invoices/preview_context_service_spec.rb

Allow to simulate subscription termination for invoice preview. This part only accepts new param and prepare correct subscription object for `PreviewService` which responsible for all invoice generation.
Add support for `terminated_at` timestamp.
Add validation that only 1 subscription could be terminated.
Add validation for provided timestamp (valid + not in past).
Extract subscription building logic into dedicated class for better separation of concerns.

feat(invoice-preview): Add invoice preview with simulated termination date on subscription

---

app/models/subscription.rb
app/services/invoices/preview_service.rb
spec/models/subscription_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature enables to see invoice breakdown on the fly, without storing any object in the DB
This PR covers support for terminated invoices. For this specific case, correct boundaries are fetched and certain fees skipped if not applicable.

feat(invoice-preview): support terminated preview invoices

---

config/initializers/console.rb

Previously, the hard_delete_invoice method could fail because of the new feature invoice_custom_sections.
This PR modifies the hard_delete_invoice method to delete the applied_invoice_custom_sections too and then delete the invoice

Feat: update hard_delete_invoice Method

---

app/services/events/common_factory.rb
spec/services/events/common_factory_spec.rb

This small changes ensure that we find subscriptions that start on the same *second* as the event timestamp. previously the conversion to an integer would drop the milliseconds from the float, resulting in a timestamp that starts that the start of the second. 
Due to this we could no longer find subscriptions starting in the same second. (as the event now suddenly falls before the start date of the subscription).
This change fixes that and converts the timestamp to a float.

bug(PayInAdvance) - Don't loose precision when converting timestamp

---

app/models/payment_provider_customers/stripe_customer.rb
app/services/payment_provider_customers/stripe_service.rb
spec/models/payment_provider_customers/stripe_customer_spec.rb
spec/services/payment_provider_customers/stripe_service_spec.rb

Some stripe errors were not returned by the API when creating a customer checkout url.
This PR also split the payment methods into 2 categories. You cannot create a cutomer checkout url if all their available payment methods are not able to be setup. (this will be very useful for https://github.com/getlago/lago-api/pull/3236)

fix(stripe): Better errors on Stripe customer checkout url

---

app/graphql/resolvers/data_api/revenue_streams/plans_resolver.rb
app/graphql/resolvers/data_api/revenue_streams_resolver.rb
app/graphql/types/data_api/revenue_streams/object.rb
app/graphql/types/data_api/revenue_streams/order_by_enum.rb
app/graphql/types/data_api/revenue_streams/plans/object.rb
app/graphql/types/query_type.rb
app/services/data_api/revenue_streams/plans_service.rb
schema.graphql
schema.json
spec/fixtures/lago_data_api/revenue_streams_plans.json
spec/graphql/resolvers/data_api/revenue_streams/plans_resolver_spec.rb
spec/graphql/resolvers/data_api/revenue_streams_resolver_spec.rb
spec/graphql/types/data_api/revenue_streams/object_spec.rb
spec/graphql/types/data_api/revenue_streams/order_by_enum_spec.rb
spec/graphql/types/data_api/revenue_streams/plans/object_spec.rb
spec/services/data_api/revenue_streams/plans_service_spec.rb

**Context**
This pull request introduces a new feature to query revenue streams plans of an organization using GraphQL.
It requests the `lago-data` api service and returns revenue streams per plans for an organization.

feat(data): Add graphql endpoint for revenue streams plans

---

app/graphql/resolvers/data_api/revenue_streams/customers_resolver.rb
app/graphql/types/data_api/revenue_streams/customers/object.rb
app/graphql/types/query_type.rb
app/services/data_api/revenue_streams/customers_service.rb
schema.graphql
schema.json
spec/fixtures/lago_data_api/revenue_streams_customers.json
spec/graphql/resolvers/data_api/revenue_streams/customers_resolver_spec.rb
spec/graphql/types/data_api/revenue_streams/customers/object_spec.rb
spec/services/data_api/revenue_streams/customers_service_spec.rb

**Context**
This pull request introduces a new feature to query revenue streams customers of an organization using GraphQL.
It requests the `lago-data` api service and returns revenue streams per customers for an organization.

feat(data): Add graphql endpoint for revenue streams customers

---

app/services/invoices/payments/adyen_service.rb
app/services/invoices/payments/cashfree_service.rb
app/services/invoices/payments/stripe_service.rb
spec/services/invoices/payments/adyen_service_spec.rb
spec/services/invoices/payments/cashfree_service_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb

Amount sent to create a checkout link is not accurate when manual payment is recorded on invoice
This PR fixes the amout that is sent to total due amount.

fix(checkout-link): Fix the total due amount

---

app/services/payment_providers/stripe/webhooks/payment_intent_succeeded_service.rb
spec/services/payment_providers/stripe/webhooks/payment_intent_succeeded_service_spec.rb

Newer version of stripe api don't have the charges array bit instead, just the id of te last charge. I need to confirm how we lock API version.
Reverting for now

revert: save payment method

---

app/jobs/invoices/provider_taxes/pull_taxes_and_apply_job.rb

Integration aggregator often returns Net::ReadTimeout
This PR auto retries mentioned error

fix: retry Net::ReadTimeout for pulling taxes

---

app/services/invoices/advance_charges_service.rb
spec/services/invoices/advance_charges_service_spec.rb

when fee has `organization_id = nil`

bug(advance_charges): invoice paid in advance succeeded fees

---

app/services/credit_notes/create_from_termination.rb
app/services/credit_notes/create_service.rb
app/services/invoices/preview/credits_service.rb
app/services/invoices/preview_service.rb
spec/services/credit_notes/create_from_termination_spec.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/invoices/preview/credits_service_spec.rb

For generating proper invoice preview for terminated subscription with plan paid in advance we need to generate credit note and later credit which will be accounted in the termination invoice.
Adjust credit note creation during subscription terminated to allow get non-persisted records.
Extract credits related logic from the `PreviewService` to the `Preview::CreditsService`.

feat(invoice-preview): Add support for generating credit note during invoice preview

---

app/services/invoices/refresh_draft_service.rb
spec/scenarios/invoices/progressive_billing_spec.rb
spec/support/scenarios_helper.rb

Resetting the `progressive_billing_credits` was missed when refreshing draft invoices.

bug(ProgressiveBilling) - Reset progressive billing credits when refreshing draft

---

app/models/billing_entity.rb
app/models/organization.rb
spec/factories/billing_entities.rb
spec/factories/customers.rb
spec/factories/invoices.rb
spec/factories/organizations.rb
spec/models/billing_entity_spec.rb
spec/models/organization_spec.rb

We decided to proceed without default billing entity. Instead we'll be treating the first active billing entity of organization as default if an organization has only one billing entity, otherwise we act as if organization has no default billing entity and forcing client to send the billing_entity_id

Feat(multientities):remove usage of is_default flag on billing_entities

---

app/models/billing_entity.rb
db/migrate/20250227091909_remove_is_default_from_billing_entity.rb
db/schema.rb

Column drop should be happening in a separate commit

Feat(multi-entities): migration to remove is_default from billing_entities

---

app/models/billing_entity.rb

we decided to proceed with billing_entities without adding :default flag, so we needed to add ignored column before running the migration. Now it's time to clean up the ignored column

Feat(multientities): remove default migration cleanup

---

app/services/events/create_service.rb

Following https://github.com/getlago/lago-api/pull/3274, this PR ensures that events received via the REST API are pushed to Kafka with a timestamp sent as float

fix(kafka): Ensure timestamp is pushed as float

---

app/config/permissions/definition.yml
app/config/permissions/role-finance.yml
app/config/permissions/role-manager.yml
app/graphql/resolvers/data_api/mrrs_resolver.rb
app/graphql/resolvers/data_api/revenue_streams/customers_resolver.rb
app/graphql/resolvers/data_api/revenue_streams/plans_resolver.rb
app/graphql/types/data_api/mrrs/object.rb
app/graphql/types/data_api/revenue_streams/customers/object.rb
app/graphql/types/data_api/revenue_streams/object.rb
app/graphql/types/query_type.rb
app/services/data_api/mrrs_service.rb
schema.graphql
schema.json
spec/fixtures/lago_data_api/mrrs.json
spec/graphql/resolvers/data_api/mrrs_resolver_spec.rb
spec/graphql/resolvers/data_api/revenue_streams/customers_resolver_spec.rb
spec/graphql/resolvers/data_api/revenue_streams/plans_resolver_spec.rb
spec/graphql/resolvers/data_api/revenue_streams_resolver_spec.rb
spec/graphql/types/data_api/mrrs/object_spec.rb
spec/graphql/types/data_api/revenue_streams/customers/object_spec.rb
spec/graphql/types/data_api/revenue_streams/object_spec.rb
spec/services/data_api/mrrs_service_spec.rb

**Context**
This pull request introduces a new feature to query mrrs of an organization using GraphQL.
It requests the `lago-data` api service and returns mrrs for an organization.

feat(data): Add graphql endpoint for mrrs

---

app/models/billing_entity.rb
db/migrate/20250303104151_add_code_uniqueness_index_to_billing_entities.rb
db/schema.rb
spec/models/billing_entity_spec.rb

When creating or updating a billing entities, the code should be unique within the organization for not deleted and not archived records
added uniqueness index and validation for code with organization_id

Feat(multientities): add billing_entity code uniqueness validation

---

app/controllers/api/v1/subscriptions_controller.rb
app/controllers/concerns/api_errors.rb
app/jobs/payment_providers/cancel_payment_authorization_job.rb
app/models/organization.rb
app/services/base_result.rb
app/services/base_service.rb
app/services/payment_providers/create_payment_factory.rb
app/services/payment_providers/stripe/payments/authorize_service.rb
app/services/subscriptions/plan_upgrade_service.rb
schema.graphql
schema.json
spec/fixtures/stripe/payment_intent_authorization_failed.json
spec/graphql/types/integrations/premium_integration_type_enum_spec.rb
spec/jobs/payment_providers/cancel_payment_authorization_job_spec.rb
spec/requests/api/v1/subscriptions_controller_spec.rb

When creating a subscription, the invoice and the payment are done asynchronously. We're introducing a way to make a pre-authorization on the credit card to mitigate payment failure.
**The feature should be released in BETA** until we're satisfied with the request/response shape and we added support for other payment provider. Only Stripe is supported now.
When creating a subscription, we'll handle the creation, termination of current subscription and update of future subscriptions if needed.
Then in async, we create the invoice, which in async, will collect the payment. The payment can fail but the subscription is already returned and active.
Before creating a subscription, we can create a pre-authorization on the customer cards. This will make a payment, lock the amount on the customer …

feat(stripe): Pre-authorize payment before creating subscription

---

config/application.rb
config/environments/production.rb
config/environments/staging.rb
config/initializers/sidekiq.rb
lib/active_job/json_log_subscriber.rb
lib/active_job/logging.rb

New Active Job logging format 
```
{:event=>"perform", :status=>"error", :job=>"Invoices::GeneratePdfAndNotifyJob", :duration=>528.95, :job_id=>"11c160df-7edb-45fe-9ab5-31c7db66e97e", :queue=>"invoices", :exception=>{:class=>"Socket::ResolutionError", :message=>"Failed to open TCP connection to pdf:3000 (getaddrinfo: Name or service not known)"}}
```

chore(logs): Improve logging to json

---

app/graphql/resolvers/data_api/mrrs/plans_resolver.rb
app/graphql/types/data_api/mrrs/plans/object.rb
app/graphql/types/query_type.rb
app/services/data_api/mrrs/plans_service.rb
schema.graphql
schema.json
spec/fixtures/lago_data_api/mrrs_plans.json
spec/graphql/resolvers/data_api/mrrs/plans_resolver_spec.rb
spec/graphql/types/data_api/mrrs/plans/object_spec.rb
spec/services/data_api/mrrs/plans_service_spec.rb
spec/services/data_api/revenue_streams/customers_service_spec.rb

**Context**
This pull request introduces a new feature to query mrrs plans of an organization using GraphQL.
It requests the `lago-data` api service and returns mrrs per plan for an organization.

feat(data): Add mrrs plans resolver

---

app/services/payment_providers/stripe/payments/authorize_service.rb

More recent version of stripe require some parameter to be set differently for SetupIntent and PaymentIntent.
https://docs.stripe.com/upgrades#2023-08-16
Keep in mind this feature is beta and enabled for only one customer (no breaking change by forcing the version here).

feat(preauth): Prepare Stripe Authorization for recent versions

---

app/services/integrations/aggregator/contacts/payloads/netsuite.rb
spec/services/integrations/aggregator/contacts/create_service_spec.rb
spec/services/integrations/aggregator/contacts/payloads/factory_spec.rb
spec/services/integrations/aggregator/contacts/payloads/netsuite_spec.rb
spec/services/integrations/aggregator/contacts/update_service_spec.rb

Some customers need Lago customer.external_id to be used at NetSuite entityId:
1. Pass `customer.external_id` to Netsuite `entityId`
2. Enforce this id by passing `autoname` to false

feat(netsuite): enforce customer external id to be NetSuite EntityId

---

lib/lago_http_client/lago_http_client/http_error.rb

When parsing json and converting to ruby hash, we want to be more resilient to parsing errors
This PR returns empty hash, for invalid json

fix: make json parsing more resilient

---

app/services/invoices/preview_service.rb
spec/services/invoices/preview_service_spec.rb

Invoice preview generation logic was missing charge duration property in boundaries which lead to invalid calculations on charge fees.
Add `charges_duration` to boundaries and adjust tests.

fix(invoice-preview): Add charge duration to boundaries during preview generation

---

app/models/charge.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/preview_service.rb
spec/models/charge_spec.rb
spec/services/invoices/preview_service_spec.rb

Preview feature enables to see invoice breakdown on the fly, without storing any object in the DB
This PR covers support for upgraded invoices. For this specific case, correct boundaries are fetched and certain fees skipped if not applicable.

feat(invoice-preview): add upgrade logic

---

app/services/credit_notes/refunds/stripe_service.rb
spec/services/credit_notes/refunds/stripe_service_spec.rb

Refund logic does not work with dunning campaign
Currently credit note refund logic works only if payment intent is created with the initial invoice and if it is successful.
However, with dunning campaign, initial payment can be failed, but there can be separate payment request which covers invoice.
This case was not supported and with refund we were linking invalid failed payment.
This PR fixes described case.

fix(dunning): adapt refund logic with dunning

---

app/jobs/invoices/update_all_invoice_grace_period_from_billing_entity_job.rb
app/jobs/invoices/update_grace_period_from_billing_entity_job.rb
app/models/billing_entity.rb
app/services/billing_entities/update_invoice_grace_period_service.rb
app/services/billing_entities/update_invoice_payment_due_date_service.rb
app/services/billing_entities/update_service.rb
app/services/invoices/update_all_invoice_grace_period_from_billing_entity_service.rb
app/services/invoices/update_grace_period_from_billing_entity_service.rb
app/services/organizations/update_invoice_payment_due_date_service.rb
app/services/organizations/update_service.rb
spec/factories/billing_entities.rb
spec/factories/invoices.rb
spec/jobs/invoices/update_all_invoice_grace_period_from_billing_entity_job_spec.rb
spec/jobs/invoices/update_grace_period_from_billing_entity_job_spec.rb
spec/models/billing_entity_spec.rb
spec/services/billing_entities/update_invoice_grace_period_service_spec.rb
spec/services/billing_entities/update_invoice_payment_due_date_service_spec.rb
spec/services/billing_entities/update_service_spec.rb
spec/services/invoices/update_all_invoice_grace_period_from_billing_entity_service_spec.rb
spec/services/invoices/update_grace_period_from_billing_entity_service_spec.rb

We need a service to update billing_entity data that is doing exactly everything that is currently done when updating an organization.
Since in the future we'll be storing grace period, net_payment term only on billing_entity, we also need services that will be updating these values on invoices, but we shouldn't trigger invoices updates now
Added services:
- `billing_entities/update`
- `billing_entities/update_invoice_grace_period`
- `billing_entities/update_invoice_payment_due_date`
- `invoices/update_all_invoice_grace_period_from_billing_entity`
- `invoices/update_grace_period_from_billing_entity`
Also added jobs:
- `app/jobs/invoices/update_all_invoice_grace_period_from_billing_entity_job.rb`
- `app/jobs/invoices/update_grace_period_from_billing_entity_job.rb`
For now the jobs are not …

Feat(multi-entities): add services to update billing_entity

---

app/services/dunning_campaigns/process_attempt_service.rb
spec/services/dunning_campaigns/process_attempt_service_spec.rb

Together AI have an error when triggering `DunningCampaigns::ProcessAttemptJob`: `BaseService::MethodNotAllowedFailure: invoices_not_ready_for_payment_processing`
this happens because when selecting overdue invoices, we do not filter invoices that are ready for payment processing.
- Added filter invoices to be ready_to_be_processed when filtering invoices for dunning_campaign process_attempt

Fix: overdue invoices should not include invoices not ready to be paid

---

app/controllers/api/v1/customers_controller.rb
app/graphql/mutations/customers/create.rb
app/services/customers/create_from_api_service.rb
app/services/customers/create_service.rb
spec/services/customers/create_from_api_service_spec.rb
spec/services/customers/create_service_spec.rb

We are going to need to change services signature in order to include billing entity information on customer creation, then we are taking the opportunity to refactor this old service following the new style and breaking it into two separate services prior to multi entities development.
Refactor `Customers::CreateService` breaking it in two services with the standard interface (`.call`)...
* `Customers::CreateService` remains for graphQL flow
* `Customers::CreateFromApiService` with the code required for the credate/update Api flow.

misc(refactor): Refactor Customers::CreateService

---

app/controllers/api/v1/invoices_controller.rb
app/services/invoices/preview_service.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/invoices/preview_service_spec.rb

Add support for grace period for invoice preview.
Handle invalid params type for gracefully.

fix(invoice-preview): Params parsing and grace period being ignored

---

app/models/invoice.rb
spec/models/invoice_spec.rb

Fix wrong calculation on max refund amount when an invoice got credits and prepaid credits on it.
Fix `Invoice#refundable_amount_cents` method to not include credits and prepaid credits.

fix(invoice): Fix refundable amount

---

app/services/invoices/preview/subscription_plan_change_service.rb
app/services/invoices/preview/subscription_termination_service.rb
app/services/invoices/preview_service.rb
spec/services/invoices/preview/subscription_plan_change_service_spec.rb
spec/services/invoices/preview/subscription_termination_service_spec.rb
spec/services/invoices/preview_service_spec.rb

Prevent charge fees generation for non-persisted subscriptions.
Adjust subscription termination to always happen in the end of day.
Ensure that upgraded/downgraded subscription always has reference to new subscription.

fix(invoice-preview): Fix bugs

---

app/services/payment_provider_customers/stripe/retrieve_latest_payment_method_service.rb
app/services/payment_providers/stripe/payments/authorize_service.rb
spec/fixtures/stripe/customer_list_no_payment_methods.json
spec/fixtures/stripe/customer_list_payment_methods.json
spec/fixtures/stripe/customer_no_default_payment_method.json
spec/fixtures/stripe/customer_with_default_payment_method.json
spec/graphql/resolvers/memberships_resolver_spec.rb
spec/requests/api/v1/subscriptions_controller_spec.rb
spec/services/payment_provider_customers/stripe/retrieve_latest_payment_method_service_spec.rb

Payments in Lago rely on Stripe to figure out the payment method, we don't pass it explicitly. For payment authorization, we must pass the payment method explicitly.
When a payment method is added to a stripe user, we receive a `setup_intent.succeeded` and save this payment method in Lago. 
It's possible that when creating a new subscription and making a pre-auth call, the webhook wasn't process yet. In this case, we'll try to find a payment method directly on Stripe.
First, we try the default payment.
Then, the most recent card.
Otherwise, fail.

feat(preauth): Get latest payment method from Stripe if not found locally

---

Gemfile
Gemfile.lock

1. Add `binding.pry` somewhere
1. Attach docker `docker attach lago_api_dev` 
(see https://github.com/getlago/lago/pull/473)
1. In another window, run your rspec test and enjoy 🌟

chore(gems): require `pry` for development and test env

---

app/services/invoices/advance_charges_service.rb
app/services/invoices/create_advance_charges_invoice_subscription_service.rb
app/services/invoices/create_invoice_subscription_service.rb
spec/scenarios/invoices/advance_charges_dates_spec.rb
spec/scenarios/invoices/recurring_fees_spec.rb
spec/support/scenarios_helper.rb

`advance_charges` invoices will regroup all **non invoiceable fees paid within the last period**. 
Invoice billing periods are normally related to the fee periods but in this case, you can have a fee created in June paid only in November so we want to recompute the periods.
The second issue is that the `DateService` is designed to work active or "recently terminated" subscription. In this case we try to compute dates for a fees long after the subscription is terminated which results in wrong dates (`to` date being before `from` date for instance). This bug is NOT fixed. Even if it was, the Date service would still compute date related to the subscription when the fee is created which is **not what we want in this specific case**. 
This fixed is inspired by this first attempt by …

feat(regroup_fee): Use current month boundaries for AdvanceCharges invoices

---

app/jobs/invoices/create_pay_in_advance_charge_job.rb

We had a batch of 600 failed jobs trying to update 3 wallets which lead to jobs failing with `ActiveRecord::StaleObjectError: Attempted to update a stale object: Wallet.` exception.
We're trying to increase `jitter` for job retries to order to increase spread between jobs retries and see if that it's enough to mitigate the issue.
This value should increase spread by 10 times on 3rd attempt.
Increase job jitter

misc(retry-jobs): Adjust jitter to increase spread between repeating jobs

---

lib/lago_http_client/lago_http_client/client.rb
lib/lago_http_client/lago_http_client/http_error.rb

This PR adds response headers to `LagoHttpClient::HttpError` which will help us to debug requests made to external integrations services.

misc(http-client): Add response headers to http error

---

app/jobs/wallets/refresh_ongoing_balance_job.rb
app/services/wallets/balance/refresh_ongoing_service.rb
spec/jobs/wallets/refresh_ongoing_balance_job_spec.rb
spec/services/wallets/balance/refresh_ongoing_service_spec.rb

This PR fixes a bug:
- when updating wallet balance
- we fail to fetch taxes
- result of `Invoices::CustomerUsageService` is not checked if it's success
- we update wallet without correctly calculated current usage invoice (total_amount_cents in this case is 0)
After the fix:
- when updating wallet balance
- we fail to fetch taxes
- we return a failed result from the service `Wallets::Balance::RefreshOngoingService`
- Job `Wallets::RefreshOngoingBalance` raises an exception

Fix(wallet-balance): Fail if failed to fetch full current usage while updating wallet

---

app/controllers/api/v1/invoices_controller.rb
app/models/charge.rb
app/models/subscription.rb
app/services/credit_notes/create_from_termination.rb
app/services/credit_notes/create_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/preview/build_subscription_service.rb
app/services/invoices/preview/credits_service.rb
app/services/invoices/preview/subscription_plan_change_service.rb
app/services/invoices/preview/subscription_termination_service.rb
app/services/invoices/preview/subscriptions_service.rb
app/services/invoices/preview_context_service.rb
app/services/invoices/preview_service.rb
app/services/subscriptions/create_service.rb
spec/factories/subscriptions.rb
spec/models/charge_spec.rb
spec/models/subscription_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/credit_notes/create_from_termination_spec.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/invoices/preview/build_subscription_service_spec.rb
spec/services/invoices/preview/credits_service_spec.rb
spec/services/invoices/preview/subscription_plan_change_service_spec.rb
spec/services/invoices/preview/subscription_termination_service_spec.rb
spec/services/invoices/preview/subscriptions_service_spec.rb
spec/services/invoices/preview_context_service_spec.rb
spec/services/invoices/preview_service_spec.rb

Add support for generating invoice preview simulating termination, upgrade and downgrade of existing subscriptions.
Following PRs were already reviewed and this feature branch does not
contain any change outside of these PRS:
-https://github.com/getlago/lago-api/pull/3257
-https://github.com/getlago/lago-api/pull/3265
-https://github.com/getlago/lago-api/pull/3277
-https://github.com/getlago/lago-api/pull/3275
-https://github.com/getlago/lago-api/pull/3296
-https://github.com/getlago/lago-api/pull/3297
-https://github.com/getlago/lago-api/pull/3318
-https://github.com/getlago/lago-api/pull/3328
-https://github.com/getlago/lago-api/pull/3335

feat(invoice-preview): Support previews for simulated termination, upgrade or downgrade of subscription

---

app/jobs/invoices/provider_taxes/pull_taxes_and_apply_job.rb
app/models/invoice.rb
app/services/invoices/compute_amounts_from_fees.rb
app/services/invoices/compute_taxes_and_totals_service.rb
app/services/invoices/transition_to_final_status_service.rb
spec/graphql/mutations/invoices/finalize_spec.rb
spec/models/invoice_spec.rb
spec/services/invoices/compute_taxes_and_totals_service_spec.rb

When invoice does not have any fee attached we don't want to make a request to the tax provider. In addition, if invoice `fees_amount_cents` is zero but customer property for finalizing zero amount invoices is set to `skip`, we also don't want to sync such invoice to Anrok.
In described scenario, expected flow should include using Lago defined taxes, which will anyway result in zero amounts even if Lago taxes are defined.
However, tax provider users usually does not define Lago taxes.

fix(tax-provider): do not call tax provider when invoice is zero amount or without fees

---

app/graphql/resolvers/integrations_resolver.rb
spec/graphql/resolvers/integrations_resolver_spec.rb

Account manager role not see the Anrok connection on a customer under "information" tab.
This PR adds `customers:view` permission to GQL `IntegrationsResolver` so users with the manager role can see all the integrations not just payment providers.

fix(permissions): Fix permissions in integrations resolver

---

app/services/integrations/aggregator/items_service.rb
spec/graphql/mutations/integration_items/fetch_items_spec.rb
spec/services/integrations/aggregator/items_service_spec.rb

`cursor` param sent to xero can't be blank anymore.
This PR fixes the API call with blank `cursor` so that we're not sending it in that case.

fix(aggregator-items): Fix empty cursor in aggregator items service

---

app/graphql/resolvers/wallet_transaction_resolver.rb
app/graphql/types/invoices/object.rb
app/graphql/types/query_type.rb
app/graphql/types/wallet_transactions/object.rb
app/jobs/invoices/prepaid_credit_job.rb
app/models/wallet_transaction.rb
app/serializers/v1/wallet_transaction_serializer.rb
app/services/invoices/update_service.rb
app/services/wallet_transactions/mark_as_failed_service.rb
db/migrate/20250318093216_add_failed_at_to_wallet_transactions.rb
db/migrate/20250318175216_mark_pending_wallet_transactions_as_failed.rb
db/schema.rb
schema.graphql
schema.json
spec/graphql/resolvers/wallet_transaction_resolver_spec.rb
spec/graphql/types/invoices/object_spec.rb
spec/graphql/types/wallet_transactions/object_spec.rb
spec/jobs/invoices/prepaid_credit_job_spec.rb
spec/models/wallet_transaction_spec.rb
spec/scenarios/wallets/topup_with_open_invoices_spec.rb
spec/serializers/v1/wallet_transaction_serializer_spec.rb
spec/services/invoices/update_service_spec.rb
spec/services/wallet_transactions/mark_as_failed_service_spec.rb

This PR enhances the handling of WalletTransactions by introducing support for failed transactions and improving GraphQL access to transaction data. The changes provide better visibility into payment failures and their impact on invoices.
GraphQL Changes
- Added WalletTransactionResolver to allow retrieving a single wallet transaction.
- Linked payments to an invoice 
- Added failed_at and linked invoice to WalletTransaction for better tracking of failed transactions.
Backend Changes
- Introduced a new failed status for WalletTransaction to reflect payment failures.
- Added failed_at timestamp to store when a transaction fails.
- Updated logic to handle payment failures:
- When a payment fails, the corresponding WalletTransaction is now marked as failed with the failed_at timestamp.| …

feat: add wallet transaction details

---

lib/lago_eu_vat/lago_eu_vat/eu_vat_rates.json
spec/lib/lago_eu_vat/rate_spec.rb

This file was copy-pasted from the original repo: https://github.com/ibericode/vat-rates
~This might be communicated to users and clients (via changelog).~
This file will create the taxes in DB when it's "EU Tax Management" integration is installed but the rate are not updated automatically.
> [!IMPORTANT]  
> Notice that compared to the [original file](https://github.com/ibericode/vat-rates/blob/master/vat-rates.json), we manually remove `GB`. I'm not sure why but it was done last time: https://github.com/getlago/lago-api/pull/1570

chore(eu-vat): Update eu_vat_rates.json

---

app/queries/add_ons_query.rb
app/queries/applied_coupons_query.rb
app/queries/billable_metrics_query.rb
app/queries/coupons_query.rb
app/queries/credit_notes_query.rb
app/queries/customers_query.rb
app/queries/dunning_campaigns_query.rb
app/queries/events_query.rb
app/queries/fees_query.rb
app/queries/integration_collection_mappings_query.rb
app/queries/integration_items_query.rb
app/queries/integration_mappings_query.rb
app/queries/invoices_query.rb
app/queries/past_usage_query.rb
app/queries/payment_receipts_query.rb
app/queries/payment_requests_query.rb
app/queries/payments_query.rb
app/queries/plans_query.rb
app/queries/subscriptions_query.rb
app/queries/taxes_query.rb
app/queries/wallet_transactions_query.rb
app/queries/wallets_query.rb
app/queries/webhook_endpoints_query.rb
app/queries/webhooks_query.rb

We're migrating away from `OpenStruct`.
This adds a custom `Result` class for all Query classes in `app/queries`. By design, it's kinda expected that there is only one thing returned in the result. 
Although, I'm surprised to see the pagination returned only in `PastUsageQuery`. 🤔

chore(results): Introduce Result classes for app/queries folder

---

db/seeds/base.rb

Because in the seeds we create an Organization directly with ActiveRecord, not through the service, we have to manually create a BillingEntity for it

Fix(multientities): ensure seeded organization is created with billing_entity

---

app/services/events/create_service.rb

This PR adds a new `source_metadata` collection attribute to the events payload sent to Kafka.
For now, this it will contains a new `api_post_processed` boolean flag to allow the events-processor to identify if the events should be sent-back to API for in advance billing

feat(event): Add metadata in kafka payload

---

Guardfile
app/mailers/application_mailer.rb
app/mailers/credit_note_mailer.rb
app/mailers/invoice_mailer.rb
app/mailers/payment_receipt_mailer.rb
app/services/credit_notes/generate_service.rb
app/services/invoices/generate_pdf_service.rb
app/services/payment_receipts/generate_pdf_service.rb
app/views/credit_note_mailer/created.slim
app/views/invoice_mailer/finalized.slim
app/views/payment_receipt_mailer/created.slim
app/views/payment_request_mailer/requested.slim
spec/mailers/credit_note_mailer_spec.rb
spec/mailers/invoice_mailer_spec.rb
spec/mailers/payment_receipt_mailer_spec.rb

Some clients don't need pdfs of invoices, credit notes and payment receipts.
This PR adds and ENV var to disable generation pdfs: `LAGO_DISABLE_PDF_GENERATION`

feat(pdf): Add env var to disable generating pdfs

---

app/services/events/stores/clickhouse/unique_count_query.rb

When the following event is older than the start of the period, we use the start date of the period as the reference instead of the end date of the period, as previously set.

fix(clickhouse): Use from_datetime for prorated unique count

---

app/models/payment.rb
app/services/payment_providers/stripe/webhooks/payment_intent_succeeded_service.rb
app/services/payments/update_payment_method_data_service.rb
db/migrate/20250324125056_add_provider_payment_method_id_to_payments.rb
db/schema.rb
spec/fixtures/stripe/retrieve_payment_method.json
spec/fixtures/stripe/webhooks/payment_intent_succeeded-2020-08-27.json
spec/fixtures/stripe/webhooks/payment_intent_succeeded-2022-11-15.json
spec/fixtures/stripe/webhooks/payment_intent_succeeded-2024-09-30.acacia.json
spec/services/payment_providers/stripe/webhooks/payment_intent_succeeded_service_spec.rb
spec/services/payments/update_payment_method_data_service_spec.rb

This PR reintroduce the work reverted in #3282 
I originally wanted to freeze the stripe version before re-introducing this feature but:
* I want to upgrade Stripe before we freeze the version
* you can't [update webhook endpoint](https://docs.stripe.com/webhooks/versioning), you need to handle both at some point, so let's handle both now.
We want to save some payment method details for a successful payment. This info will be reused in the Payment Receipt feature.
It's done with the webhook only because it needs to be done with the webhook for all payment happening outside Lago (like invoice payment url or "customer balance"). Instead of doing it multple times, we always rely on webhooks.
The card details are not part of all webhooks depending on the version so we call the Stripe API to …

feat(payments): Save payment method on successful payment (stripe only)

---

app/jobs/lifetime_usages/flag_refresh_from_plan_update_job.rb
app/models/subscription.rb
app/services/invoices/progressive_billing_service.rb
app/services/lifetime_usages/calculate_service.rb
app/services/lifetime_usages/flag_refresh_from_plan_update_service.rb
app/services/lifetime_usages/recalculate_and_check_service.rb
app/services/lifetime_usages/usage_thresholds/check_service.rb
app/services/plans/update_service.rb
app/services/plans/update_usage_thresholds_service.rb
config/environments/development.rb
spec/jobs/lifetime_usages/flag_refresh_from_plan_update_job_spec.rb
spec/scenarios/invoices/progressive_billing_spec.rb
spec/scenarios/subscriptions/progressive_billing_enablement_spec.rb
spec/services/lifetime_usages/flag_refresh_from_plan_update_service_spec.rb
spec/services/plans/update_usage_thresholds_service_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/support/license_helper.rb
spec/support/scenarios_helper.rb

When setting up progressive billing on a plan we need to make sure to recalculate lifetime usage as well.
*  moves threshold update logic to a dedicated service.
* adds a job to flag lifetime usage refresh when plan is updated
* recalculate lifetime usage when subscription is marked as active. (deals with new subscription / upgrade / downgrade behavior)

bug(LifetimeUsage) - refresh lifetime usage when creating subscriptions / updating plans

---

app/services/billing_entities/create_service.rb
app/services/organizations/create_service.rb
db/migrate/20250325145324_assign_customers_to_billing_entities.rb
db/schema.rb
spec/services/billing_entities/create_service_spec.rb
spec/services/organizations/create_service_spec.rb

in order to facilitate the migration to multi entities, the first billing entity id for each organization will match the organization id. This will allow us migrate data in a performant way and reduces the risks of migration issues.
Also, a migration is included to:
1. update all billing entity record ids not matching …

feat(multi-entities): Organizations' first billing entity matches its id with the organization_id

---

app/services/invoices/add_on_service.rb
app/services/invoices/create_generating_service.rb
app/services/invoices/customer_usage_service.rb
app/services/invoices/preview_service.rb
db/migrate/20250325162648_assign_invoices_to_billing_entities.rb
db/schema.rb
spec/services/billing_entities/resolve_service_spec.rb
spec/services/invoices/add_on_service_spec.rb
spec/services/invoices/create_generating_service_spec.rb
spec/services/invoices/customer_usage_service_spec.rb
spec/services/invoices/preview_service_spec.rb

This PR depends on https://github.com/getlago/lago-api/pull/3377 that needs to be merged first.
👉  https://getlago.canny.io/feature-requests/p/support-billing-from-multiple-entities
On invoice generation assign customer's billing entity reference.
Also assign all existing Invoices to the organization default billing entity (matching the organization_id). This is needed to later implement and populate …

feat(multi-entities) Invoices services with billing entities

---

app/models/billing_entity.rb
app/models/organization.rb
app/services/customers/eu_auto_taxes_service.rb
app/services/taxes/auto_generate_service.rb
config/initializers/console.rb
lib/lago_eu_vat/lago_eu_vat/rate.rb
spec/lib/lago_eu_vat/rate_spec.rb
spec/services/taxes/auto_generate_service_spec.rb

As I was updating the rates (see #3352) I noticed we could improve the `LagoEuVat::Rate` class.
Instead of reading the json file every time we initialize the class, we now load it once when Rails is eager loading at boot.
The 2 methods are now class methods too.

refactor(eu_vat): store json in class const (so it's only read once at boot)

---

.rubocop.yml
app/services/payment_providers/stripe/payments/create_service.rb
spec/fixtures/stripe/payment_intent_failed_card_declined.json
spec/scenarios/credit_note_spec.rb
spec/scenarios/customers/create_partner_and_run_billing_spec.rb
spec/scenarios/dunning/campaign_v1_spec.rb
spec/scenarios/dunning/dunning_campaign_v1_spec.rb
spec/support/jobs/mock_stripe_webhook_event_job.rb
spec/support/scenarios_helper.rb

This PR adds a new scenario test for dunning campaign.
The interesting part are:
* mocking stripe at the HTTP level 
* simulating the reception of the Stripe webhooks
* testing emails sent
* testing Lago webhook sent by "logging" them rathen than mocking job
The new jobs in `spec/support/jobs/` extend `ActiveJob::Base` instead of `ApplicationJob` because they are NOT jobs from the applications but fake jobs only meant to be run in spec to help mock behavior.

spec(dunning): Add scenario tests for dunning

---

app/jobs/payments/update_payment_method_data_job.rb
app/services/payment_providers/stripe/webhooks/payment_intent_succeeded_service.rb
app/services/payments/update_payment_method_data_service.rb
spec/jobs/payments/update_payment_method_data_job_spec.rb
spec/services/payment_providers/stripe/webhooks/payment_intent_succeeded_service_spec.rb
spec/services/payments/update_payment_method_data_service_spec.rb

I was hesitant to make it async but it's better for retries.
Note that `update_payment_status` might raise a not found error if the webhook arrived before the `payment._provider_payment_id` is updated in the DB, which will retry the HandleEventJob. 
So when `UpdatePaymentMethodDataJob` is dispatched, we're guaranteed that payment is updated... until the implementation of `update_payment_status` changes 😄

feat(stripe): Update payment method in a job

---

.github/workflows/spec.yml
Gemfile
Gemfile.lock
spec/spec_helper.rb

This PR enables knapsack-pro. It splits up our CI pipeline into 8 nodes and runs now in 3 minutes instead of 15.

chore(CI) - Enable knapsack-pro

---

app/graphql/types/plans/object.rb
schema.graphql
schema.json
spec/graphql/resolvers/plan_resolver_spec.rb
spec/graphql/types/plans/object_spec.rb

These methods will replace `*_count` methods as this ones are DB expensive and we don't need them anymore. It is enough to know if plan or its children plans has related objects nor the count of them, also, this is performant.
`*_count` attributes are deprecated and will be deleted after frontend does not require them anymore.

misc(GraphQL): add `has_*` attributes to plan object as replacement of `*_count` attributes

---

app/jobs/payments/update_payment_method_data_job.rb

```
RuntimeError: Couldn't determine a delay based on :exponentially_longer
```

fix(job): Wrong retry strategy name

---

app/services/charges/update_service.rb
app/services/plans/update_service.rb
spec/graphql/resolvers/customer_portal/customers/usage_resolver_spec.rb

While executing the Charges::UpdateJob, we noticed that some data — specifically the properties key inside params — was being lost. This happened because payload_charge was passed to perform_later with symbol keys (:key), and ActiveJob/Sidekiq serializes job arguments using JSON, which does not handle deeply nested symbol keys properly. As a result, some nested data like properties was silently dropped during serialization.
This PR ensures that payload_charge is passed to the job using .deep_stringify_keys, making the entire structure JSON-safe before enqueueing the job. Additionally, inside the Charges::UpdateService, params are converted back to symbolized keys using .to_h.deep_symbolize_keys

Fix charge update service params

---

app/graphql/types/subscriptions/object.rb
app/jobs/clock/refresh_lifetime_usages_job.rb
app/models/organization.rb
app/services/lifetime_usages/flag_refresh_from_invoice_service.rb
app/services/lifetime_usages/flag_refresh_from_subscription_service.rb
app/services/lifetime_usages/recalculate_and_check_service.rb
schema.graphql
schema.json
spec/graphql/types/integrations/premium_integration_type_enum_spec.rb
spec/scenarios/lifetime_usages/without_progressive_billing_spec.rb
spec/services/lifetime_usages/flag_refresh_from_invoice_service_spec.rb
spec/services/lifetime_usages/flag_refresh_from_subscription_service_spec.rb
spec/spec_helper.rb
spec/support/shared_context/time_travel.rb

Some customers want the lifetime usage of a subscription to always be refreshed for all subscriptions. (Even if the plan does not include progressive billing thresholds). This new premium integration enables that.

feat(LifetimeUsage): Add lifetime_usage premium integration 

---

app/jobs/invoices/create_pay_in_advance_charge_job.rb
app/services/credits/applied_prepaid_credit_service.rb

This PR addresses a PostgreSQL lock_timeout issue when applying prepaid credits to invoices. Under certain conditions, concurrent updates to the same wallet record caused lock contention and job failures.

Feat add timeout

---

app/services/integrations/aggregator/invoices/payloads/xero.rb
spec/services/integrations/aggregator/invoices/payloads/xero_spec.rb

Some billing systems, such as Xero, do not support precise_unit_amount values with more than two decimal places. Currently, we send the raw value, which can cause errors on the values presented on xero
This PR addresses that issue by adjusting the payload format specifically for the Xero integration.
Moves the item(fee) serialization logic into the Xero class, preserving the generic behavior in BasePayload.
When a precise_unit_amount has more than 2 decimal places:
- Sets "units" to 1
- Removes the "precise_unit_amount" field
- Adds "amount_cents" with the fee value excluding discounts and taxes
This logic is only applied to the Xero integration payload.

fix: handle xero decimal cases

---

app/jobs/taxes/update_all_eu_taxes_job.rb
app/jobs/taxes/update_organization_eu_taxes_job.rb
spec/jobs/taxes/update_all_eu_taxes_job_spec.rb
spec/jobs/taxes/update_organization_eu_taxes_job_spec.rb
spec/services/taxes/auto_generate_service_spec.rb

The EU Tax Management integration generate taxes [from a json file](https://github.com/getlago/lago-api/blob/main/lib/lago_eu_vat/lago_eu_vat/eu_vat_rates.json). These taxes should be updated with we update the file.
Related recent changes: https://github.com/getlago/lago-api/pull/3356
The existing service already takes care of updating the existing taxes (see new spec added). This PR only adds jobs to run the update.
When the file is updated, we should add a job to the migration or enqueue it from the console, or even make a rake console.
What's your preference?

feat(taxes): Add jobs to update EU Taxes

---

app/graphql/types/billable_metrics/object.rb
schema.graphql
schema.json
spec/graphql/resolvers/billable_metric_resolver_spec.rb
spec/graphql/types/billable_metrics/object_spec.rb

We have 4 type of count attributes on the BM model.
* activeSubscriptionsCount
* draftInvoicesCount
* plansCount
* subscriptionsCount
Computation for these fields is quite DB expensive and impacts overall performance.
We have replaced the usage of these attributes with new "has_*" attributes. These new attributes return true when there are at least one record matching... these are performant queries for the usage intended and will reduce DB load and improve graphQL response times. 
This change remove the _count attributes from Billable Metric object type as it is not needed anymore.

misc: Remove count attributes from BillableMetric graphQL type object

---

app/serializers/v1/billing_entity_serializer.rb
app/serializers/v1/credit_note_serializer.rb
app/serializers/v1/customer_serializer.rb
app/serializers/v1/invoice_serializer.rb
app/services/invoices/preview_context_service.rb
spec/serializers/v1/billing_entity_serializer_spec.rb
spec/serializers/v1/credit_note_serializer_spec.rb
spec/serializers/v1/customer_serializer_spec.rb
spec/serializers/v1/invoice_serializer_spec.rb
spec/services/invoices/preview_context_service_spec.rb

Include billing_entity code in:
- invoice serialized object
- customer serialized object
- credit_note serialized object
needed to update also `Invoices::PreviewContextService` as customer should always be build with billing entity (the `null: false` on billing_entity_id will be added later)

Feat(multientities): serialize billing_entity_code in API

---

app/services/invoices/aggregate_amounts_and_taxes_from_fees.rb
spec/scenarios/invoices/advance_charges_spec.rb
spec/services/invoices/aggregate_amounts_and_taxes_from_fees_spec.rb

This pull request includes changes to fix the calculation of taxable base amounts in the regroup_fees invoice.
The aim is to compute the value based on the fees having the specified taxes.

fix(regroup_fees): Compute taxable_base_amount_cents on applied taxes

---

config/initializers/active_job_uniqueness.rb

Lago's RedisClient is currently configured to `reconnect_attempts` just 2 times, and redlock's `retry_count` is set to 0.
if Lago tries to connect to Redis and the connection is not stable at the time of the connection, this will result in an error such as:
```
{"level":"error","event":"enqueue","status":"error","job":"Invoices::Payments::CreateJob","queue":"default","exception":{"class":"Redlock::LockAcquisitionError","message":"failed to acquire lock on 'Too many Redis errors prevented lock acquisition:\nRedisClient::ConnectionError: Broken pipe (rediss://redis-host:6379)'"}}
{"level":"error","event":"perform","status":"error","job":"BillSubscriptionJob","duration":557.02,"job_id":"ce1323cb-64e3-4a08-a81e-420fd6e3d345","queue":"billing","exception":{"class":"Redlock::LockAcquisitionError …
```

fix(redis): increase timeouts and retry counts, and reconnect counts, add retry_jitter to avoid lock contention

---

app/jobs/invoices/prepaid_credit_job.rb
app/services/invoices/update_service.rb
spec/services/invoices/update_service_spec.rb

Invoices::PrepaidCreditJob must but unique to avoid incorrect wallet balances... a bug was introduced where payment_status is a string value while by default it is a symbol. This mess up the uniqueness of the job
and caused duplicated processing, hence incorrect wallet balances.

Fix Invoices::PrepaidCreditJob queueing to ensure uniqueness

---

app/services/fees/add_on_service.rb
app/services/fees/create_pay_in_advance_service.rb
app/services/fees/init_from_adjusted_charge_fee_service.rb
app/services/fees/one_off_service.rb
app/services/fees/paid_credit_service.rb
app/services/fees/subscription_service.rb
spec/services/fees/add_on_service_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb
spec/services/fees/init_from_adjusted_charge_fee_service_spec.rb
spec/services/fees/one_off_service_spec.rb
spec/services/fees/paid_credit_service_spec.rb
spec/services/fees/subscription_service_spec.rb

Third part of multientities implementation includes passing billing_entity_id to fees
- updated services that create fees to populate billing_entity_id for fee
- removed calls to organization while creating fees

Feat(multientities): assign billing_entity_id when creating fees

---

app/services/payment_providers/stripe/payments/create_service.rb
spec/services/payment_providers/stripe/payments/create_service_spec.rb

when payload includes payment_method_data, it is not allowed to include payment_method as well.

fix(bug): Stripe payment intent creation payload

---

app/controllers/api/v1/invoices_controller.rb
app/graphql/resolvers/invoices_resolver.rb
app/queries/invoices_query.rb
schema.graphql
schema.json
spec/graphql/resolvers/invoices_resolver_spec.rb
spec/queries/invoices_query_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb

We need a possibility to filter invoices by billing_entity in Graphql resolver and in api endpoint
Added billing_entity param to invoice_resolver and invoice#index action
Added billing_entity_id filter in Invoices query

Feat(multientities): Add support of billing_entity filter in invoices query

---

app/services/payment_requests/payments/stripe_service.rb
spec/services/payment_requests/payments/stripe_service_spec.rb

There was a bug when a payment for payment request was initiated via clicking a payment link in an email.
In that case we were creating a new payment instead of finding an existing one by payment provider id.
That new payment was not created due to a unique index on `provider_payment_id` and `payment_provider_id`.
This PR fixes the described issue by fixing `Invoices::Payments::StripeService#update_payment_status` method implementation.

fix(payments): Fix payment of a one time payment request

---

app/controllers/api/v1/invoices_controller.rb
app/services/invoices/preview_context_service.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/invoices/preview_context_service_spec.rb

When querying `invoices#preview` endpoint, a billing_entity_code might be provided - in this case we should create a preview for customer from this billing_entity. Otherwise a default billing_entity should be used.
Since customer.external_id stays uniq within org, if customer.external_id is provided, we're ignoring billing_entity when looking for a customer

Feat(multientities): add billing_entity to invoices#preview

---

app/models/analytics/gross_revenue.rb
app/models/analytics/invoice_collection.rb
app/models/analytics/invoiced_usage.rb
app/models/analytics/mrr.rb
app/models/analytics/overdue_balance.rb
spec/models/analytics/gross_revenue_spec.rb
spec/models/analytics/invoice_collection_spec.rb
spec/models/analytics/invoiced_usage_spec.rb
spec/models/analytics/mrr_spec.rb
spec/models/analytics/overdue_balance_spec.rb

When caching analytics, billing_entity_id should be taken into account

Fix(multientities): add billing_entity_id to cache key for analytics

---

app/services/payment_providers/stripe/webhooks/payment_intent_succeeded_service.rb

This PR fixes the payment receipts enabled check in PaymentIntentSucceededService when payment is nil.

fix(payment): Fix PaymentIntentSucceededService

---

app/contracts/queries/customers_query_filters_contract.rb
app/controllers/api/v1/customers_controller.rb
app/controllers/api/v1/invoices_controller.rb
app/graphql/resolvers/customers_resolver.rb
app/graphql/resolvers/invoices_resolver.rb
app/queries/customers_query.rb
app/queries/invoices_query.rb
schema.graphql
schema.json
spec/contracts/queries/customers_query_filters_contract_spec.rb
spec/graphql/resolvers/customers_resolver_spec.rb
spec/graphql/resolvers/invoices_resolver_spec.rb
spec/queries/customers_query_spec.rb
spec/queries/invoices_query_spec.rb
spec/requests/api/v1/customers_controller_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb

We need a possibility to filter customers by billing_entity in Graphql resolver and in api endpoint
Added billing_entity param to customers_resolver and customers#index action
Added billing_entity_id filter in Custoemers query
EDIT:
When adding contract, noticed on the design that we should accept array of billing_entities, changed the code
- to accept billing_entity_codes and billing_entity_ids for customers
- to accept billing_entity_codes and billing_entity_ids for invoices

Feat(multientities): Add support of billing_entity filter in customers query 

---

app/services/invoices/aggregate_amounts_and_taxes_from_fees.rb
spec/services/invoices/aggregate_amounts_and_taxes_from_fees_spec.rb

For in advance invoice applied tax objects had invalid data
This PR fixes creation of applied tax for in advance invoice

fix: fix credit note applied taxes

---

app/contracts/queries/customers_query_filters_contract.rb
app/controllers/api/v1/credit_notes_controller.rb
app/controllers/api/v1/customers_controller.rb
app/controllers/api/v1/invoices_controller.rb
app/graphql/resolvers/credit_notes_resolver.rb
app/graphql/resolvers/customers_resolver.rb
app/graphql/resolvers/invoices_resolver.rb
app/queries/credit_notes_query.rb
app/queries/customers_query.rb
app/queries/invoices_query.rb
schema.graphql
schema.json
spec/contracts/queries/customers_query_filters_contract_spec.rb
spec/graphql/resolvers/credit_notes_resolver_spec.rb
spec/graphql/resolvers/customers_resolver_spec.rb
spec/graphql/resolvers/invoices_resolver_spec.rb
spec/queries/credit_notes_query_spec.rb
spec/queries/customers_query_spec.rb
spec/queries/invoices_query_spec.rb
spec/requests/api/v1/credit_notes_controller_spec.rb
spec/requests/api/v1/customers_controller_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb

We need a possibility to filter credit_notes by billing_entity in Graphql resolver and in api endpoint
Added billing_entity param to credit_notes_resolver and credit_notes#index action
Added billing_entity_id filter in CreditNotes query

Feat(multientities): Add support of billing_entity filter in credit_notes query

---

app/controllers/api/v1/customers_controller.rb
app/graphql/types/customers/create_customer_input.rb
app/graphql/types/customers/update_customer_input.rb
schema.graphql
schema.json
spec/graphql/mutations/customers/create_spec.rb
spec/graphql/mutations/customers/update_spec.rb
spec/graphql/types/customers/create_customer_input_spec.rb
spec/graphql/types/customers/update_customer_input_spec.rb
spec/requests/api/v1/customers_controller_spec.rb

Update customer accepts billing_entity_id
Updated graphql inputs for create_customer and update_customer to receive billing_entity_id and send it to the services

Feat(multientities): graphql create and update user with billing entity

---

app/jobs/clock/consume_subscription_refreshed_queue_job.rb
app/jobs/subscriptions/flag_refreshed_job.rb
app/services/subscriptions/consume_subscription_refreshed_queue_service.rb
app/services/subscriptions/flag_refreshed_service.rb
clock.rb
spec/clockwork_spec.rb
spec/jobs/clock/consume_subscription_refreshed_queue_job_spec.rb
spec/jobs/subscriptions/flag_refreshed_job_spec.rb
spec/services/subscriptions/consume_subscription_refreshed_queue_service_spec.rb
spec/services/subscriptions/flag_refreshed_service_spec.rb

Related to https://github.com/getlago/lago/pull/500
This PR adds a new Redis consumer to flag subscription's lifetime usage records and customer's wallet for refresh.
The messages are pushed from the events-processor for every uniq subscriptions.

feat(processor): Add flag subscription refresh logic

---

app/models/integration_collection_mappings/avalara_collection_mapping.rb
app/models/integration_mappings/avalara_mapping.rb
app/services/integration_collection_mappings/factory.rb
app/services/integration_mappings/factory.rb

Currently Lago adds integration with tax provider Avalara.
This PR adds models and base support for mapping. In Lago, _single-table-inheritance_ is used for storing mapping data, so this PR only handles new models and factory classes

feat(avalara-integration): add support for avalara mapping

---

db/migrate/20250402135038_assign_discarded_customers_to_billing_entities.rb
db/structure.sql

When data-exports are created, they include invoices that might  belong to descarded customers. When these customers are serialized, these customers should have billing_entity_id
Also Adding null: false for  customers table will require consistent data
Note: this job is done as a migration, because the original Customers migration was done as a migration. Also the amount of discarded customers is really low - ~5k on US, and they already were updated manually

Feat(multientities): update discarded customers to be assigned to a billing entity

---

app/services/payment_providers/create_payment_factory.rb

Typo in the module name but it has been [this way since the feature was added](https://github.com/getlago/lago-api/pull/2767/files#diff-5fdcae1d090ff3f90fb788278788fe3e73e3b46c1bf899379ee97c88c7848ccfR15-R16). This payment provider is "community maintained".

fix(cashfree): wrong module name

---

clock.rb

This PR changes the variable used to check if the refresh from events processor is enable on wallet and lifetime usage from `LAGO_KAFKA_BOOTSTRAP_SERVERS` to `LAGO_REDIS_STORE_URL`.
This reason behind this is that the Kafka config is not defined on clock service

misc(processor): Change config for refresh

---

app/jobs/database_migrations/fix_invoices_organization_sequential_id_job.rb
app/models/invoice.rb
app/services/organizations/update_invoice_numbering_service.rb
app/services/organizations/update_service.rb
db/migrate/20250403093628_ensure_organization_last_invoice_got_organization_sequential_id.rb
db/structure.sql
spec/jobs/database_migrations/fix_invoices_organization_sequential_id_job_spec.rb
spec/scenarios/invoices/invoice_numbering_spec.rb
spec/services/organizations/update_invoice_numbering_service_spec.rb
spec/support/scenarios_helper.rb

- The way we were assigning organization sequential id was not efficient and doing a lot of queries
- We removed the `switched_from_customer_numbering?`
- This should be done when the user update the organization to `per_organization` numbering
```ruby
organization
.invoices
.non_self_billed
.where.not(organization_sequential_id: 0)
.order(organization_sequential_id: :desc)
.limit(1)
.pick(:organization_sequential_id) || 0
organization
.invoices
.non_self_billed
.maximum(:organization_sequential_id) || 0
``` 
- Change the organization update logic when we change the document numbering
```ruby
if params.key?(:document_numbering)
Organizations::UpdateInvoiceNumberingService.call(
organization:,
document_numbering: params[:document_numbering]
)
end
```
- Create a new service …

fix(invoices): improve organization numbering performances

---

app/graphql/resolvers/invoice_custom_sections_resolver.rb
app/graphql/types/customers/object.rb
app/graphql/types/customers/update_customer_input.rb
app/models/customer.rb
app/models/invoice_custom_section.rb
app/models/organization.rb
app/services/customers/manage_invoice_custom_sections_service.rb
app/services/customers/update_service.rb
db/migrate/20250403110833_add_section_type_to_invoice_custom_sections.rb
db/migrate/20250407202459_add_section_type_index_to_invoice_custom_sections.rb
db/structure.sql
schema.graphql
schema.json
spec/graphql/mutations/customers/update_spec.rb
spec/graphql/resolvers/customer_resolver_spec.rb
spec/graphql/resolvers/invoice_custom_sections_resolver_spec.rb
spec/graphql/types/customers/object_spec.rb
spec/graphql/types/customers/update_customer_input_spec.rb
spec/models/customer_spec.rb
spec/models/invoice_custom_section_spec.rb
spec/models/organization_spec.rb
spec/services/customers/manage_invoice_custom_sections_service_spec.rb
spec/services/customers/update_service_spec.rb

Currently, users have no way to include bank transfer instructions or other automatic content directly on invoices.
To support this in a clean and scalable way, we’re introducing a section_type enum to distinguish between different types of invoice custom sections `manual` and `system_generated`.
This PR focuses only on introducing the structure needed to support that functionality in future changes.
This PR introduces the following changes:
- Added a new section_type enum column to invoice_custom_sections:
- manual: user-defined sections (default)
- system_generated: will be used for auto-generated content (e.g., Stripe funding instructions)
- Updated InvoiceCustomSection model with enum declaration and default value.
- Added two scoped associations in Organization:
- …

feat: Add section_type to InvoiceCustomSections to support different section types

---

app/controllers/api/v1/wallet_transactions_controller.rb
app/serializers/v1/payment_providers/wallet_transaction_payment_serializer.rb
app/services/wallet_transactions/payments/generate_payment_url_service.rb
config/routes.rb
spec/factories/customers.rb
spec/factories/wallet_transactions.rb
spec/requests/api/v1/wallet_transactions_controller_spec.rb
spec/serializers/v1/payment_providers/wallet_transaction_payment_serializer_spec.rb
spec/services/wallet_transactions/payments/generate_payment_url_service_spec.rb

Allow to generate payment url for failed or pending wallet transactions.
Add `payment_url` endpoint for wallet transactions.

feat(wallet-transactions): Add generate payment url endpoint

---

app/jobs/payment_provider_customers/stripe_sync_funding_instructions_job.rb
app/services/invoice_custom_sections/funding_instructions_formatter_service.rb
app/services/payment_provider_customers/stripe/sync_funding_instructions_service.rb
app/services/payment_provider_customers/stripe_service.rb
config/locales/de/invoice.yml
config/locales/en/invoice.yml
config/locales/es/invoice.yml
config/locales/fr/invoice.yml
config/locales/it/invoice.yml
config/locales/nb/invoice.yml
config/locales/sv/invoice.yml
spec/jobs/payment_provider_customers/stripe_sync_funding_instructions_job_spec.rb
spec/services/invoice_custom_sections/funding_instructions_formatter_service_spec.rb
spec/services/payment_provider_customers/stripe/sync_funding_instructions_service_spec.rb
spec/services/payment_provider_customers/stripe_service_spec.rb

This PR builds on the groundwork introduced in the previous [PR](https://github.com/getlago/lago-api/pull/3456), where we added the section_type enum to distinguish between manual and system-generated invoice custom sections.
Now, we’re introducing the logic that automatically fetches bank transfer instructions from Stripe and injects them into invoices via a system_generated section — enabling customers to see accurate payment details directly on the invoice when bank transfer is selected.
This PR introduces the following:
- New background service that:
- Retrieves bank transfer instructions from Stripe for a given customer.
- Generates a system_generated InvoiceCustomSection with the Stripe funding details.
- Ensures the section is associated with the correct invoice and doesn’t …

feat: Add Stripe funding instructions as system-generated invoice custom sections

---

app/services/subscriptions/consume_subscription_refreshed_queue_service.rb
spec/services/subscriptions/consume_subscription_refreshed_queue_service_spec.rb

The `Subscriptions::ConsumeSubscriptionRefreshedQueueService` what recently introduced to handle usage refresh comming from the events-processor.
The service is returning nil instead of an emtpy result when the `LAGO_REDIS_STORE_URL` is not set, leading to dead jobs...
This PR ensures that the service returns a result instead

fix(processor): Avoid dead jobs with subscription consumer

---

app/services/billable_metrics/breakdown/item.rb
app/services/billable_metrics/breakdown/sum_service.rb
app/services/billable_metrics/breakdown/unique_count_service.rb
lib/lago_utils/lago_utils/version.rb

This PR is  part of a larger initiative to remove all remaining `OpenStruc` references from the code base and replace them by pre-defined result or specific classes.
This PR replaces 
- the returns from `LagoUtils::Version#call` by a propert `Result`  defined as `Data.define(:number, :github_url)`
- the result items from `BillableMetrics::Breakdown::SumService` and `BillableMetrics::Breakdown::UniqueCountService` with an array of a new `BillableMetrics::Breakdown::Item` objects defined as `Data.define(:date, :action, :amount, :duration, :total_duration)`

misc: Removes some references to OpenStruct

---

app/graphql/mutations/plans/create.rb
app/graphql/mutations/plans/update.rb
app/graphql/types/plans/create_input.rb
app/graphql/types/plans/update_input.rb
schema.graphql
schema.json
spec/graphql/types/plans/create_input_spec.rb
spec/graphql/types/plans/update_input_spec.rb

This PR extracts the arguments from the `CreatePlan` and `UpdatePlan` mutation into proper types, respectively `CreatePlanInput` and `UpdatePlanInput`
These types will be later extended with the coming alerting feature

misc(plans): Extract plan GraphQL arguments in types

---

config/application.rb

removed here: https://github.com/getlago/lago-api/pull/3470/files#diff-63ba8710e689ec851c82f0151a9e100381f4638f1991dd693d171b8d389ac5e8L3

fix(deps): Require ostruct when initializing

---

app/graphql/types/integrations/avalara.rb
app/graphql/types/integrations/avalara/create_input.rb
app/graphql/types/integrations/avalara/update_input.rb
app/models/integrations/avalara_integration.rb
app/services/integrations/avalara/create_service.rb
app/services/integrations/avalara/update_service.rb
schema.graphql
schema.json
spec/factories/integrations.rb
spec/graphql/mutations/integrations/avalara/create_spec.rb
spec/graphql/mutations/integrations/avalara/update_spec.rb
spec/graphql/types/integrations/avalara/create_input_spec.rb
spec/graphql/types/integrations/avalara/update_input_spec.rb
spec/graphql/types/integrations/avalara_spec.rb
spec/models/integrations/avalara_integration_spec.rb
spec/services/integrations/avalara/create_service_spec.rb
spec/services/integrations/avalara/update_service_spec.rb

Currently Lago is working on integration with tax provider Avalara
This PR adds `company_code` support that was initially skipped during connection part.
Company code would be needed for fetching company ID, that is expected parameter in several Avalara requests.

feat(avalara-integration): add support for company code

---

app/serializers/v1/billing_entity_serializer.rb
spec/factories/fees.rb
spec/serializers/v1/billing_entity_serializer_spec.rb

While writing clients I realized we missed some fields in billing_entity_serializer - added all of them

Feat(multientities): add missing fields to serializer

---

app/jobs/clock/activate_subscriptions_job.rb
app/jobs/clock/compute_all_daily_usages_job.rb
app/jobs/clock/consume_subscription_refreshed_queue_job.rb
app/jobs/clock/create_interval_wallet_transactions_job.rb
app/jobs/clock/events_validation_job.rb
app/jobs/clock/finalize_invoices_job.rb
app/jobs/clock/free_trial_subscriptions_biller_job.rb
app/jobs/clock/inbound_webhooks_cleanup_job.rb
app/jobs/clock/inbound_webhooks_retry_job.rb
app/jobs/clock/mark_invoices_as_payment_overdue_job.rb
app/jobs/clock/process_dunning_campaigns_job.rb
app/jobs/clock/refresh_draft_invoices_job.rb
app/jobs/clock/refresh_lifetime_usages_job.rb
app/jobs/clock/refresh_wallets_ongoing_balance_job.rb
app/jobs/clock/retry_failed_invoices_job.rb
app/jobs/clock/retry_generating_subscription_invoices_job.rb
app/jobs/clock/subscriptions_biller_job.rb
app/jobs/clock/subscriptions_to_be_terminated_job.rb
app/jobs/clock/terminate_coupons_job.rb
app/jobs/clock/terminate_ended_subscriptions_job.rb
app/jobs/clock/terminate_recurring_transaction_rules_job.rb
app/jobs/clock/terminate_wallets_job.rb
app/jobs/clock/webhooks_cleanup_job.rb
app/jobs/clock_job.rb

The following code is repeated over and over in all jobs defined in `/app/jobs/clock`:
```ruby
if ENV["SENTRY_DSN"].present? && ENV["SENTRY_ENABLE_CRONS"].present?
include SentryCronConcern
end
queue_as do
if ActiveModel::Type::Boolean.new.cast(ENV["SIDEKIQ_CLOCK"])
:clock_worker
else
:clock
end
end
```
This PR just moves this logic in a new `ClockJob` base job class, updates the parent class of all related job and removes the duplicated logic

misc(job): Add a new ClockJob base job class

---

app/graphql/types/customers/object.rb
app/graphql/types/integration_customers/avalara.rb
app/models/customer.rb
app/models/integration_customers/avalara_customer.rb
app/models/integration_customers/base_customer.rb
app/services/integration_customers/avalara_service.rb
app/services/integration_customers/factory.rb
app/services/integrations/aggregator/contacts/payloads/avalara.rb
app/services/integrations/aggregator/contacts/payloads/factory.rb
schema.graphql
schema.json
spec/factories/integration_customers.rb
spec/graphql/types/customers/object_spec.rb
spec/graphql/types/integration_customers/avalara_spec.rb
spec/services/integration_customers/avalara_service_spec.rb
spec/services/integrations/aggregator/contacts/payloads/avalara_spec.rb

Currently Lago is implementing integration with Avalara tax provider
This PR adds basic support for creating and updating avalara customers in Lago. It provides graphql support and updates all related places in the code.

feat(avalara-integration): add support for avalara integration customer

---

app/services/taxes/create_service.rb
app/services/taxes/destroy_service.rb
app/services/taxes/update_service.rb
spec/services/taxes/create_service_spec.rb
spec/services/taxes/destroy_service_spec.rb
spec/services/taxes/update_service_spec.rb

The taxes services we had before, should create or delete applied taxes on default_billing_entity
Updated
- `Taxes::CreateService`
- `Taxes::UpdateService`
- `Taxes::DestroyService`

Feat(multientities): update old taxes services

---

Gemfile
Gemfile.lock
app/serializers/v1/customer_serializer.rb
app/services/customers/eu_auto_taxes_service.rb
spec/scenarios/customers/customer_eu_taxes_spec.rb
spec/scenarios/dunning/dunning_campaign_v1_spec.rb
spec/serializers/v1/customer_serializer_spec.rb
spec/services/customers/eu_auto_taxes_service_spec.rb
spec/support/scenarios_helper.rb
spec/support/shared_context/webhook_tracking.rb

Adds scenario tests about customer taxes and EU tax management. Ensure a webhook is sent in case of success or failure.
This ensure the webhook is sent in case of error
When using Valvat, the gem will perform format check via Regex before calling the API. If the format is invalid, the API isn't called.
In the webhook pay load the `customer.vies_check` hash has multple form.
**Notice that valvat is now autloaded with Bundler. I don't know why it was done manually (since the gem was added).**
The response from the VIES API is returned, like before
```json
{
"valid": false,
"valid_format": false,
}
```
```json
{
"valid": false,
"valid_format": true
}
```
```json
{
"valid": false,
"valid_format": true,
"error": "The  web service returned the error: <ERROR FROM VIES>"
}
```
The error message …

chore(spec): Send `customer.vies_check` webhook if error

---

db/structure.sql
db/views/exports_applied_coupons_v01.sql
db/views/exports_billable_metrics_v01.sql
db/views/exports_charges_v01.sql
db/views/exports_coupons_v01.sql
db/views/exports_credit_notes_v01.sql
db/views/exports_customers_v01.sql
db/views/exports_plans_v01.sql
db/views/exports_subscriptions_v01.sql

This PR fixes the exposed data type and format for the export introduced by https://github.com/getlago/lago-api/pull/3491
NOTE: views have been manually updated in production.
The following commands will have to be executed locally to fix the `db/structure.sql` file:
```
lago exec api rails db:migrate:down:primary VERSION=20250407000001
```

fix(exports): Force type for exports

---

app/controllers/api/v1/billing_entities_controller.rb
app/serializers/v1/billing_entity_serializer.rb
spec/requests/api/v1/billing_entities_controller_spec.rb
spec/serializers/v1/billing_entity_serializer_spec.rb

Billing Entity serializer accepts `includes: [:taxes]` to include billing entity's applied taxes serialized.
Also, GET /api/v1/billing_entity/:code (#show) returns the serialized taxes within the billing entity object

feat(multientities): Add taxes (applied) to billing entity serializer

---

app/services/payment_providers/stripe/payments/create_service.rb
spec/fixtures/stripe/payment_intent_card_declined_response.json
spec/services/payment_providers/stripe/payments/create_service_spec.rb

Each time we're failing to process a payment intent, stripe returns us an error. If it was a card_error, the response will contain a payment_intent.id
Updated service that creates stripe payments to dig payment_intent id in the received error message

Fix: save provider_payment_id on payment even if it failed

---

db/seeds/01_base.rb
lib/tasks/db.rake

As I'm working on alerting I found a few little things that I found annoying
This introduce `bin/rails db:truncate` command to remove all data without dropping the database.
When developing, I had to rerun my migration many times using `db:migrate:redo:primary`. Unfortunately, the seeded data might clash (I'm developing the seeder at the same time).
Dropping the database and re-preparing it is annoying because:
1. you might get `PG::ObjectInUse: ERROR:  database "lago" is being accessed by other users (PG::ObjectInUse)`
2. if you load the schema, the latest change to your migration you're building aren't applied.
3. if you migrate from scratch, it takes ~2 years.
```bash
bin/rails db:truncate db:migrate:redo:primary db:seed
```

feat(dx): improve seeders and truncate db

---

spec/spec_helper.rb

~This was changed when we switched to sql structure dump.
I believe this can be reverted so just load the schema if the test DB isn't up to date (instead of failing).~
If there are pending migrations and we migrate the primary db. We can't rely on `maintain_test_schema!` because it will also try to load the schema in clickhouse but it's not committed, so it fails on CI.
https://github.com/getlago/lago-api/pull/3349/files#diff-89eebfcbc0f14b6d989517837ca1e94fce4e2ce9a03233641cd936f2b8d2ed94L54-R53

chore(spec): maintain_test_schema! before test

---

app/views/templates/invoices/v1.slim
app/views/templates/invoices/v2.slim
app/views/templates/invoices/v3.slim
app/views/templates/invoices/v3/charge.slim
app/views/templates/invoices/v3/one_off.slim
app/views/templates/invoices/v4.slim
app/views/templates/invoices/v4/_eu_tax_management.slim
app/views/templates/invoices/v4/charge.slim
app/views/templates/invoices/v4/one_off.slim
app/views/templates/invoices/v4/self_billed.slim

Invoice templates uses billing entity as data source of truth

feat(multientities) BillingEntity as source of truth for Invoices

---

app/controllers/api/v1/customers_controller.rb
app/queries/applied_coupons_query.rb
app/queries/base_filters.rb
app/queries/base_query.rb
app/queries/billable_metrics_query.rb
app/queries/coupons_query.rb
app/queries/credit_notes_query.rb
app/queries/customers_query.rb
app/queries/dunning_campaigns_query.rb
app/queries/events_query.rb
app/queries/fees_query.rb
app/queries/integration_collection_mappings_query.rb
app/queries/integration_items_query.rb
app/queries/integration_mappings_query.rb
app/queries/invoices_query.rb
app/queries/past_usage_query.rb
app/queries/payment_receipts_query.rb
app/queries/payment_requests_query.rb
app/queries/payments_query.rb
app/queries/plans_query.rb
app/queries/subscriptions_query.rb
app/queries/taxes_query.rb
app/queries/wallet_transactions_query.rb
app/queries/wallets_query.rb
app/queries/webhooks_query.rb
spec/factories/data_exports.rb
spec/queries/base_filters_spec.rb

This PR is part of the global initiative to remove `OpenStruct` from the codebase
This PR replaces the definition of  `BaseQuery::Filters` defined as an `OpenStruct` with a new `BaseFilter` class.
In a similar way of the `BaseResult` this new class enforces the whitelisting of accepted filters, by defining the full list of accepted arguments.
NOTE: A future pull request will rework this to integrate with `Queries::*QueryFiltersContract` definitions

misc(filter): Remove OpenStruct for Query::Filters definition

---

app/services/billing_entities/change_eu_tax_management_service.rb
app/services/billing_entities/create_service.rb
app/services/billing_entities/update_service.rb
app/services/organizations/update_service.rb
spec/services/billing_entities/change_eu_tax_management_service_spec.rb
spec/services/billing_entities/update_service_spec.rb
spec/services/organizations/update_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/support-billing-from-multiple-entities
Introduce a new service to standardize the management of EU taxes from billing entity creates and updates.
Organization update still changes its attribute but not handles the tax creation anymore. This attribute will be removed at some point.

feat(multientities): Handle eu tax management at billing entity level

---

app/services/invites/create_service.rb
config/initializers/console.rb

This process usually involves calling the Organizations::CreateService and then manually creating an admin invite.
To streamline this, we’re adding a new helper method to Rails::ConsoleMethods.
This PR adds a create_organization(org_name:, email:) method to the Rails::ConsoleMethods module. It:
Creates an organization using Organizations::CreateService
Creates an admin invite for the specified email via Invites::CreateService
Prints the invitation URL in the console
Also returns the organization and invite_url in a hash for further use.

feat: Add create_org helper to Rails console

---

app/models/customer.rb
app/services/invoices/add_on_service.rb
app/services/invoices/create_one_off_service.rb
app/services/invoices/create_pay_in_advance_charge_service.rb
app/services/invoices/finalize_open_credit_service.rb
app/services/invoices/paid_credit_service.rb
app/services/invoices/progressive_billing_service.rb
app/services/invoices/provider_taxes/pull_taxes_and_apply_service.rb
app/services/invoices/refresh_draft_and_finalize_service.rb
app/services/invoices/subscription_service.rb
app/services/invoices/transition_to_final_status_service.rb
spec/graphql/resolvers/customer_resolver_spec.rb
spec/models/customer_spec.rb
spec/scenarios/dunning/dunning_campaign_v1_spec.rb
spec/scenarios/fees/recurring_fees_spec.rb
spec/scenarios/invoices/progressive_billing_spec.rb
spec/scenarios/wallets/balance_spec.rb
spec/services/customers/update_invoice_payment_due_date_service_spec.rb
spec/services/daily_usages/compute_service_spec.rb
spec/services/invoices/add_on_service_spec.rb
spec/services/invoices/create_one_off_service_spec.rb
spec/services/invoices/create_pay_in_advance_charge_service_spec.rb
spec/services/invoices/paid_credit_service_spec.rb
spec/services/invoices/preview_service_spec.rb
spec/services/invoices/progressive_billing_service_spec.rb
spec/services/invoices/provider_taxes/pull_taxes_and_apply_service_spec.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb
spec/services/invoices/subscription_service_spec.rb
spec/services/invoices/transition_to_final_status_service_spec.rb
spec/services/subscriptions/dates/monthly_service_spec.rb

use billing entity data instead of organization data as source of truth for invoices data.
customer fallbacks to billing entities instead of organization for default values.

feat(multi entities): Billing entities as source of truth for invoices

---

app/services/credit_notes/create_service.rb
app/views/templates/credit_notes/_eu_tax_management.slim
app/views/templates/credit_notes/credit_note.slim
app/views/templates/credit_notes/self_billed.slim
spec/services/credit_notes/create_service_spec.rb

When generating a credit note, the data should be taken from the billing entity
- use billing_entity instead of org when generating PDF
- check email settings on billing_entity when sending an email

Feat(multientities): use billing_entity when generating a credit note

---

app/models/payment_request.rb
app/views/templates/payment_receipts/v1.slim

when generating payment receipt PDFs we should use the billing_entity, associated to the payable of this receipt. Payable can be invoice or payment_request. Invoice belongs to a billing_entity, but payment_request did not, so we added a relation on payment_request to the billing_entity through customer
- updated payment receipt pdfs
- added relation to billing_entity from payment_request through customer

Feat(multientities): payment receipt pdf use billing_entity_info

---

.github/workflows/internal-build.yml
.github/workflows/linters.yml
.github/workflows/migrations-test.yml
.github/workflows/release.yml
.github/workflows/spec.yml

> If a GitHub Actions job or workflow has no explicit permissions set, then the repository permissions are used. Repositories created under organizations inherit the organization permissions. The organizations or repositories created before February 2023 have the default permissions set to read-write. Often these permissions do not adhere to the principle of least privilege and can be reduced to read-only, leaving the write permission only to a specific types as issues: write or pull-requests: write.
See: https://github.com/getlago/lago-api/security/code-scanning/16
I think we don't need any "GitHub Actions permissions" so I disabled it, let's see.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflo …

chore(ci): Set permissions to none

---

app/jobs/lifetime_usages/recalculate_and_check_job.rb
app/services/lifetime_usages/calculate_service.rb
app/services/lifetime_usages/check_thresholds_service.rb
spec/jobs/lifetime_usages/recalculate_and_check_job_spec.rb
spec/services/lifetime_usages/check_thresholds_service_spec.rb

[Alerting](https://github.com/getlago/lago-api/pull/3510) is coming and we need to calculate CurrentUsage only once  per subscription for all services.
This PR breaks down `RecalculateAndCheckService` into 2 services:
* `CalculateService`: was already there but current_usage can be injected (not used yet)
* `CheckThresholdsService`: The same as RecalculateAndCheckService except I removed the inner call to `CalculateService`.

refactor(billing): Breakdown RecalculateAndCheckService to inject current_usage

---

app/services/invoices/progressive_billing_service.rb
app/services/lifetime_usages/check_thresholds_service.rb
app/support/idempotency.rb
spec/scenarios/invoices/progressive_billing_spec.rb
spec/scenarios/subscriptions/progressive_billing_enablement_spec.rb
spec/scenarios/wallets/balance_spec.rb
spec/services/invoices/progressive_billing_service_spec.rb
spec/services/lifetime_usages/check_thresholds_service_spec.rb

Uses the newly introduced Idempotency transaction to ensure no duplicate progressive billing invoices can be created.

feat(ProgressiveBilling) - Add Idempotency.transaction to progressive billing service

---

app/services/invoices/preview_service.rb
spec/services/invoices/preview_service_spec.rb

Currently we're generating credit note for case when we simulate subscription downgrade. That was creating issues since for downgrade case existing subscription always billed for full billing period and there's nothing to refund.
Adjust logic in `Invoices::PreviewService` to skip credit note generation for terminated subscription if it's downgrade case.

fix(invoice-preview): Handle downgraded subscriptions in invoice previews

---

app/jobs/database_migrations/populate_charges_with_organization_job.rb
app/models/charge.rb
app/services/charges/create_service.rb
app/services/plans/create_service.rb
db/migrate/20250424135624_add_organization_id_to_charges.rb
db/migrate/20250424140359_add_organization_id_fk_to_charges.rb
db/migrate/20250424140537_validate_charges_organizations_foreign_key.rb
db/structure.sql
spec/models/charge_spec.rb
spec/services/charges/create_service_spec.rb
spec/services/plans/create_service_spec.rb

The current one is adding the field to the `charges` table. For now the field allows null values. It will be back-filled in a later pull request and then updated to ensure the presence of a value (not null)

misc: Add organization_id field on charges

---

app/services/users_service.rb
spec/services/users_service_spec.rb

Currently during login we can add any of user's memberships to segment, even revoked ones.
This PR ensures that membership we'll mention in segment will be always active. 
Ensure only active membership submitted to segment.
Add tests.

misc(segment): Track only active memberships during login

---

app/jobs/database_migrations/populate_subscriptions_with_organization_job.rb
app/models/subscription.rb
app/services/invoices/preview/build_subscription_service.rb
app/services/invoices/preview/subscription_plan_change_service.rb
app/services/subscriptions/create_service.rb
app/services/subscriptions/plan_upgrade_service.rb
db/migrate/20250425122510_add_organization_id_to_subscriptions.rb
db/migrate/20250425122641_add_organization_id_fk_to_subscription.rb
db/migrate/20250425122705_validate_subscriptions_organizations_foreign_key.rb
db/structure.sql

The current one is adding the field to the `subscriptions` table.

chore(organization): Add organization_id to subscriptions table

---

app/services/payment_providers/stripe/webhooks/charge_dispute_closed_service.rb
spec/services/payment_providers/stripe/webhooks/charge_dispute_closed_service_spec.rb

We're processing payment dispute won or lost events even for payments that belong to payment requests not just invoices.
In that case the service fails because payment requests don't have the method defined:
```
undefined method `mark_as_dispute_lost!' for an instance of PaymentRequest (NoMethodError)
```
This PR fixes that by calling the method only for invoices.

fix(dispute-lost): Do do call lose dispute service for payment requests

---

app/jobs/database_migrations/populate_wallets_with_organization_job.rb
app/models/wallet.rb
app/services/wallets/create_service.rb
db/migrate/20250425124804_add_organization_id_to_wallets.rb
db/migrate/20250425124826_add_organization_id_fk_to_wallets.rb
db/migrate/20250425124942_validate_wallets_organizations_foreign_key.rb
db/seeds/01_base.rb
db/structure.sql

The current one is adding the field to the `wallets` table.

chore(organization): Add organization_id to wallets table

---

app/jobs/database_migrations/populate_wallet_transactions_with_organization_job.rb
app/models/wallet_transaction.rb
app/services/wallet_transactions/create_service.rb
db/migrate/20250425130332_add_organization_id_to_wallet_transactions.rb
db/migrate/20250425130345_add_organization_id_fk_to_wallet_transactions.rb
db/migrate/20250425130412_validate_wallets_transactions_organization_foreign_key.rb
db/seeds/01_base.rb
db/structure.sql

The current one is adding the field to the `wallet_transactions` table.

chore(organization): Add organization_id to wallet_transactions table

---

db/migrate/20250428111042_ensure_organization_last_invoice_got_organization_sequential_id_retry.rb
db/structure.sql

Queue again the database migration job as it failed in the previous attempt due to code loading once the job was queued.
This change queues again the job to ensure no organization is missing the organization sequential id on its last invoice if it changed from numbering per customer to per organization... very unlikely at this point.

Fix(invoices): Ensure invoices got organization sequential id

---

app/jobs/database_migrations/populate_payments_with_organization_from_invoice_job.rb
app/jobs/database_migrations/populate_payments_with_organization_from_payment_request_job.rb
app/models/payment.rb
app/services/invoices/payments/adyen_service.rb
app/services/invoices/payments/cashfree_service.rb
app/services/invoices/payments/create_service.rb
app/services/invoices/payments/moneyhash_service.rb
app/services/payment_requests/payments/adyen_service.rb
app/services/payment_requests/payments/cashfree_service.rb
app/services/payment_requests/payments/create_service.rb
app/services/payment_requests/payments/moneyhash_service.rb
app/services/payment_requests/payments/stripe_service.rb
app/services/payments/manual_create_service.rb
db/migrate/20250425132724_add_organization_id_to_payments.rb
db/migrate/20250425132757_add_organization_id_fk_to_paymants.rb
db/migrate/20250425132821_validate_payments_organizations_foreign_key.rb
db/structure.sql

The current one is adding the field to the `payments` table.

chore(organization): Add organization_id to payments table

---

app/jobs/database_migrations/populate_webhooks_with_organization_job.rb
app/models/webhook.rb
app/services/webhooks/base_service.rb
db/migrate/20250428130107_add_organization_id_to_webhooks.rb
db/migrate/20250428130129_add_organization_id_fk_to_webhooks.rb
db/migrate/20250428130148_validate_webhooks_organizations_foreign_key.rb
db/structure.sql

The current one is adding the field to the `webhooks` table.

chore(organization): Add organization_id to webhooks table

---

app/models/webhook.rb

Hotfix for
```
undefined method `updated?' for an instance of ActiveRecord::Associations::HasOneThroughAssociation (NoMethodError) if association.updated? 
```

hotfix(webhooks): Avoid errors with webhooks delivery

---

app/services/integrations/aggregator/base_service.rb

Currently Lago is working on integration with tax provider Avalara
This PR fixes code for error webhook dispatched in case of contact sync failure

fix: send correct contact error webhook for avalara

---

app/controllers/api/v1/activity_logs_controller.rb
app/models/api_key.rb
app/queries/activity_logs_query.rb
app/serializers/v1/activity_log_serializer.rb
config/routes.rb
spec/factories/clickhouse/activity_logs.rb
spec/queries/activity_logs_query_spec.rb
spec/requests/api/v1/activity_logs_controller_spec.rb
spec/serializers/v1/activity_log_serializer_spec.rb

Examples:
The goal of this PR is to be able to fetch activity logs thru the API.

feat(audit_logs): Ability to fetch activity logs thru the API

---

app/jobs/database_migrations/populate_invoice_subscriptions_with_organization_job.rb
app/models/invoice_subscription.rb
app/services/invoices/create_advance_charges_invoice_subscription_service.rb
app/services/invoices/create_invoice_subscription_service.rb
db/migrate/20250429100149_add_organization_id_to_invoice_subscriptions.rb
db/migrate/20250429100150_add_organization_id_fk_to_invoice_subscriptions.rb
db/migrate/20250429100151_validate_invoice_subscriptions_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `invoice_subscriptions` table.

chore(organization): Add organization_id to invoice_subscriptions table

---

app/jobs/database_migrations/populate_plans_taxes_with_organization_job.rb
app/models/plan/applied_tax.rb
app/services/plans/apply_taxes_service.rb
db/migrate/20250428154444_add_organization_id_to_plans_taxes.rb
db/migrate/20250428154500_add_organization_id_fk_to_plans_taxes.rb
db/migrate/20250428154519_validate_plans_taxes_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `plans_taxes` table.

chore(organization): Add organization_id to plans_taxes table

---

app/models/customer.rb
spec/models/customer_spec.rb

Currently Lago is working on integration with Avalara tax tool
This PR adds small `tax_customer` method on customer model

feat(avalara-integration): add new tax_customer method

---

app/jobs/database_migrations/populate_payment_provider_customers_with_organization_job.rb
app/models/payment_provider_customers/adyen_customer.rb
app/models/payment_provider_customers/base_customer.rb
app/models/payment_provider_customers/cashfree_customer.rb
app/models/payment_provider_customers/gocardless_customer.rb
app/models/payment_provider_customers/moneyhash_customer.rb
app/models/payment_provider_customers/stripe_customer.rb
app/services/payment_providers/adyen/customers/create_service.rb
app/services/payment_providers/cashfree/customers/create_service.rb
app/services/payment_providers/gocardless/customers/create_service.rb
app/services/payment_providers/moneyhash/customers/create_service.rb
app/services/payment_providers/stripe/customers/create_service.rb
db/migrate/20250429100152_add_organization_id_to_payment_provider_customers.rb
db/migrate/20250429100153_add_organization_id_fk_to_payment_provider_customers.rb
db/migrate/20250429100154_validate_payment_provider_customers_organizations_foreign_key.rb
db/structure.sql
spec/factories/payment_provider_customers.rb
spec/organization_id_column_spec.rb

The current one is adding the field to the `payment_provider_customers` table.

chore(organization): Add organization_id to payment_provider_customers table

---

app/jobs/database_migrations/populate_invoices_taxes_with_organization_job.rb
app/models/invoice/applied_tax.rb
app/services/invoices/aggregate_amounts_and_taxes_from_fees.rb
app/services/invoices/apply_provider_taxes_service.rb
app/services/invoices/apply_taxes_service.rb
db/migrate/20250429150114_add_organization_id_to_invoices_taxes.rb
db/migrate/20250429150128_add_organization_id_fk_to_invoices_taxes.rb
db/migrate/20250429150146_validate_invoices_taxes_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `invoices_taxes` table.

chore(organization): Add organization_id to invoices_taxes table

---

config/initializers/zeitwerk.rb
lib/generators/organization_id_generator/organization_id_generator_generator.rb
lib/generators/organization_id_generator/templates/add_organization_id_fk_migration.rb.erb
lib/generators/organization_id_generator/templates/add_organization_id_migration.rb.erb
lib/generators/organization_id_generator/templates/job_template.rb.erb
lib/generators/organization_id_generator/templates/validate_organization_foreign_key_migration.rb.erb

This PR adds a temporary rails generator to creates the migrations and job to add the organization_id column to specific database table.
```bash
bin/rails generate organization_id_generator table_name
```
This will create:
- A migration to add the organization_id: `db/migrate/TIMESTAMP_add_organization_id_to_table_name.rb`
- A migration to add the foreign key, without validating it: `db/migrate/TIMESTAMP_add_organization_id_fk_to_table_name.rb`
- A migration to validate the foreign key after creation, `db/migrate/TIMESTAMP_validate_table_name_organization.rb`
- A job to fill the organization_id column in the table: `job/database_migrations/populate_table_name_from_organization_job.rb`

misc: Add temporary rails generator to fill the organization_id on every table

---

app/jobs/database_migrations/populate_charge_filters_with_organization_job.rb
app/models/charge_filter.rb
app/services/charge_filters/create_or_update_batch_service.rb
db/migrate/20250505135819_add_organization_id_to_charge_filters.rb
db/migrate/20250505135820_add_organization_id_fk_to_charge_filters.rb
db/migrate/20250505135821_validate_charge_filters_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `charge_filters` table.

chore(organization): Add organization_id to charge_filters table

---

app/jobs/database_migrations/populate_charges_taxes_with_organization_job.rb
app/models/charge/applied_tax.rb
app/services/charges/apply_taxes_service.rb
db/migrate/20250505140926_add_organization_id_to_charges_taxes.rb
db/migrate/20250505140927_add_organization_id_fk_to_charges_taxes.rb
db/migrate/20250505140928_validate_charges_taxes_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `charges_taxes` table.

chore(organization): Add organization_id to charge_taxes table

---

app/jobs/database_migrations/populate_credits_with_organization_job.rb
app/models/credit.rb
app/services/credits/applied_coupon_service.rb
app/services/credits/credit_note_service.rb
app/services/credits/progressive_billing_service.rb
db/migrate/20250505142219_add_organization_id_to_credits.rb
db/migrate/20250505142220_add_organization_id_fk_to_credits.rb
db/migrate/20250505142221_validate_credits_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `charges_taxes` table.

chore(organization): Add organization_id to credits table

---

app/controllers/admin/base_controller.rb
app/controllers/api/base_controller.rb
app/controllers/graphql_controller.rb
app/services/utils/activity_log.rb
lib/current_context.rb
spec/requests/api/base_controller_spec.rb
spec/requests/graphql_controller_spec.rb
spec/services/utils/activity_log_spec.rb

Examples:
The goal of this PR is to introduce the utils class to push activity logs into kafka.

feat(audit_logs): Utils to push activity logs to kafka

---

app/jobs/database_migrations/populate_adjusted_fees_with_organization_job.rb
app/jobs/database_migrations/populate_applied_coupons_with_organization_job.rb

Fix related to https://github.com/getlago/lago-api/pull/3540 and https://github.com/getlago/lago-api/pull/3543
Some jobs to fill `organization_id` on some tables are looping for ever because no output condition were set in the job

fix: Output condition for populate organization_id jobs

---

app/services/subscriptions/charge_cache_middleware.rb

Some `UsageMonitoring::ProcessSubscriptionActivityJob` are failing with the following error:
```
ArgumentError: Cache expiration time is invalid, cannot be negative: -42 
```
it happens because a job to refresh subscription activity was enqueued just before the end of a billing period, or because it was retried few times and the comparison between the period to_datetime and the execution time leads to a negative value. 
This PR makes sure that the cache expiration is floor to 0 seconds meaning nothing will be cached.

fix: avoid failure with negative cache expiration

---

app/graphql/resolvers/data_api/usages_resolver.rb
app/services/data_api/usages_service.rb
schema.graphql
schema.json
spec/services/data_api/usages_service_spec.rb

billable_metric_code was missing in the usages filters
This PR adds `billable_metric_code` to:
- usages controller
- usages service
- and GQL resolver

fix(usages): Add billable_metric_code to usages resolver

---

app/services/billing_entities/create_service.rb
db/migrate/20250507154910_update_nil_eu_tax_management_on_billing_entities.rb
db/structure.sql
spec/services/billing_entities/create_service_spec.rb
spec/services/organizations/create_service_spec.rb

when params do not include eu_tax_management, this field should be set to default => false, but because we were always calling the service that sets eu_tax_management to value from params, if value is missing, it becomes nil instead of false
Only set eu_tax_management if the value is sent in params

Fix(multientities):do not set eu_tax_management if not provided

---

app/jobs/database_migrations/populate_credit_notes_with_organization_job.rb
app/models/credit_note.rb
app/services/credit_notes/create_service.rb
app/services/credit_notes/estimate_service.rb
db/migrate/20250505161357_add_organization_id_to_credit_notes.rb
db/migrate/20250505161358_add_organization_id_fk_to_credit_notes.rb
db/migrate/20250505161359_validate_credit_notes_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `credit_notes` table.

chore(organization): Add organization_id to credit_notes table

---

app/jobs/database_migrations/populate_customer_metadata_with_organization_job.rb
app/models/metadata/customer_metadata.rb
app/services/customers/create_service.rb
app/services/customers/metadata/update_service.rb
app/services/customers/upsert_from_api_service.rb
db/migrate/20250506085758_add_organization_id_to_customer_metadata.rb
db/migrate/20250506085759_add_organization_id_fk_to_customer_metadata.rb
db/migrate/20250506085760_validate_customer_metadata_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `customer_metadata` table.

chore(organization): Add organization_id to customer_metadata table

---

app/jobs/database_migrations/populate_applied_invoice_custom_sections_with_organization_job.rb
app/models/applied_invoice_custom_section.rb
app/services/invoices/apply_invoice_custom_sections_service.rb
db/migrate/20250506084020_add_organization_id_to_applied_invoice_custom_sections.rb
db/migrate/20250506084021_add_organization_id_fk_to_applied_invoice_custom_sections.rb
db/migrate/20250506084022_validate_applied_invoice_custom_sections_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `applied_invoice_custom_sections` table.

chore(organization): Add organization_id to applied_invoice_custom_sections table

---

app/jobs/database_migrations/populate_applied_usage_thresholds_with_organization_job.rb
app/models/applied_usage_threshold.rb
app/services/invoices/progressive_billing_service.rb
db/migrate/20250506084827_add_organization_id_to_applied_usage_thresholds.rb
db/migrate/20250506084828_add_organization_id_fk_to_applied_usage_thresholds.rb
db/migrate/20250506084829_validate_applied_usage_thresholds_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `applied_usage_thresholds` table.

chore(organization): Add organization_id to applied_usage_thresholds table

---

app/jobs/database_migrations/populate_billable_metric_filters_with_organization_job.rb
app/models/billable_metric_filter.rb
app/services/billable_metric_filters/create_or_update_batch_service.rb
db/migrate/20250506115437_add_organization_id_to_billable_metric_filters.rb
db/migrate/20250506115438_add_organization_id_fk_to_billable_metric_filters.rb
db/migrate/20250506115439_validate_billable_metric_filters_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `billable_metric_filters` table.

chore(organization): Add organization_id to billable_metric_filters table

---

app/jobs/database_migrations/populate_fees_taxes_with_organization_job.rb
app/models/fee/applied_tax.rb
app/services/fees/apply_taxes_service.rb
db/migrate/20250506121530_add_organization_id_to_fees_taxes.rb
db/migrate/20250506121531_add_organization_id_fk_to_fees_taxes.rb
db/migrate/20250506121532_validate_fees_taxes_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `fees_taxes` table.

chore(organization): Add organization_id to fees_taxes table

---

app/jobs/database_migrations/populate_invoices_payment_requests_with_organization_job.rb
app/models/payment_request/applied_invoice.rb
app/services/payment_requests/create_service.rb
db/migrate/20250506144000_add_organization_id_to_invoices_payment_requests.rb
db/migrate/20250506144001_add_organization_id_fk_to_invoices_payment_requests.rb
db/migrate/20250506144002_validate_invoices_payment_requests_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `fees_taxes` table.

chore(organization): Add organization_id to invoices_payment_requests table

---

app/jobs/database_migrations/populate_invoice_metadata_with_organization_job.rb
app/models/metadata/invoice_metadata.rb
app/services/invoices/metadata/update_service.rb
db/migrate/20250506145849_add_organization_id_to_invoice_metadata.rb
db/migrate/20250506145850_add_organization_id_fk_to_invoice_metadata.rb
db/migrate/20250506145851_validate_invoice_metadata_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `invoice_metadata` table.

chore(organization): Add organization_id to invoice_metadata table

---

app/models/wallet_transaction.rb
db/migrate/20250512081332_add_lock_version_to_wallet_transactions.rb
db/structure.sql

We identified race conditions when applying paid credits to wallets, resulting in duplicate wallet increments. Some wallet transactions were settled twice, with status changed from pending to settled twice within milliseconds of each other.
Adding a lock version to wallet transactions prevents these race conditions by ensuring atomic updates and maintaining data integrity during concurrent operations.

fix(wallets): add lock version to wallet transactions

---

app/services/invoices/payments/create_service.rb
app/services/payment_providers/stripe/payments/create_service.rb
app/services/payment_receipts/create_service.rb
app/services/payment_requests/payments/create_service.rb
app/services/payment_requests/payments/stripe_service.rb
spec/services/invoices/payments/create_service_spec.rb
spec/services/payment_providers/stripe/payments/create_service_spec.rb
spec/services/payment_receipts/create_service_spec.rb
spec/services/payment_requests/payments/create_service_spec.rb
spec/services/payment_requests/payments/stripe_service_spec.rb

When creating payments, the info should be taken from the billing_entity
- added billing_entity into payment description and metadata

Feat(multientities): payment generation switch to entity

---

app/jobs/database_migrations/populate_fees_taxes_with_organization_job.rb

`DatabaseMigrations::PopulateFeesTaxesWithOrganizationJob` for fees_taxes table is not using the right model. `FeesTax` should instead be `Fee::AppliedTax`

fix: Fix organization_id migration job for fees_taxes table

---

app/jobs/database_migrations/populate_billing_entities_taxes_with_organization_job.rb
app/models/billing_entity/applied_tax.rb
app/services/billing_entities/taxes/apply_taxes_service.rb
db/migrate/20250512122606_add_organization_id_to_billing_entities_taxes.rb
db/migrate/20250512122607_add_organization_id_fk_to_billing_entities_taxes.rb
db/migrate/20250512122608_validate_billing_entities_taxes_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `billing_entities_taxes` table.

chore(organization): Add organization_id to billing_entities_taxes table

---

app/graphql/types/subscriptions/next_subscription_type_enum.rb
app/graphql/types/subscriptions/object.rb
schema.graphql
schema.json
spec/graphql/resolvers/subscription_resolver_spec.rb
spec/graphql/types/subscriptions/object_spec.rb

We recently started showing terminated subscription in the frontend. This caused some dislay bug where terminated subscription would be considered "soon to be downgraded" subscription.
These attributes give some more context to the frontend.

feat(gql): add next_subscription attributes

---

app/jobs/database_migrations/populate_customers_taxes_with_organization_job.rb
app/models/customer/applied_tax.rb
app/services/customers/apply_taxes_service.rb
db/migrate/20250512130614_add_organization_id_to_customers_taxes.rb
db/migrate/20250512130615_add_organization_id_fk_to_customers_taxes.rb
db/migrate/20250512130616_validate_customers_taxes_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `credit_notes_taxes` table.

chore(organization): Add organization_id to customers_taxes table

---

app/jobs/database_migrations/populate_data_export_parts_with_organization_job.rb
app/models/data_export_part.rb
app/services/data_exports/create_part_service.rb
db/migrate/20250512142912_add_organization_id_to_data_export_parts.rb
db/migrate/20250512142913_add_organization_id_fk_to_data_export_parts.rb
db/migrate/20250512142914_validate_data_export_parts_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `data_export_parts` table.

chore(organization): Add organization_id to data_export_parts table

---

app/jobs/database_migrations/populate_dunning_campaign_thresholds_with_organization_job.rb
app/models/dunning_campaign_threshold.rb
app/services/dunning_campaigns/create_service.rb
app/services/dunning_campaigns/update_service.rb
db/migrate/20250512144218_add_organization_id_to_dunning_campaign_thresholds.rb
db/migrate/20250512144219_add_organization_id_fk_to_dunning_campaign_thresholds.rb
db/migrate/20250512144220_validate_dunning_campaign_thresholds_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `dunning_campaign_thresholds` table.

chore(organization): Add organization_id to dunning_campaign_thresholds table

---

app/jobs/database_migrations/populate_coupon_targets_with_organization_job.rb
app/models/coupon_target.rb
app/services/coupons/create_service.rb
app/services/coupons/update_service.rb
db/migrate/20250512151246_add_organization_id_to_coupon_targets.rb
db/migrate/20250512151247_add_organization_id_fk_to_coupon_targets.rb
db/migrate/20250512151248_validate_coupon_targets_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `coupon_targets` table.

chore(organization): Add organization_id to coupon_targets table

---

app/serializers/v1/payments/requires_action_serializer.rb
spec/serializers/v1/payments/requires_action_serializer_spec.rb

`lago_id` was missing and it is required to identify the payment for later request to endpoint `GET /api/v1/payments/{lago_id}` to collect more payment information.

misc(webhooks): Add lago_id to payment.requires_action webhook payload

---

app/services/billing_entities/taxes/apply_taxes_service.rb
app/services/billing_entities/taxes/base_service.rb
app/services/billing_entities/taxes/manage_taxes_service.rb
app/services/billing_entities/taxes/remove_taxes_service.rb
spec/services/billing_entities/taxes/apply_taxes_service_spec.rb
spec/services/billing_entities/taxes/manage_taxes_service_spec.rb
spec/services/billing_entities/taxes/remove_taxes_service_spec.rb

Since we're deprecating `applied_to_organization` field on organization, the draft invoices should be refreshed when:
- tax is updated on organization
- tax is applied or removed on applied to billing_entity
- added refresh_draft_invoices method to all manage taxes on billing_entity services

Feat(multientities): refresh draft invoices when manage taxes on billing entity

---

app/support/idempotency.rb
spec/services/idempotency_spec.rb

IdempotencyRecords were recently added to ensure uniqueness across the app.
The goal is to add an entry to the logs so we can start ignoring this exception when needed. For example, an inbound webhook coming from payment provider can be ignored if they are processed twice. Yet, I think we want to add something to the logs.

chore(logs): Log when idempotency record is not unique

---

app/jobs/invoices/provider_taxes/void_job.rb
app/services/integrations/aggregator/taxes/credit_notes/payloads/avalara.rb
app/services/integrations/aggregator/taxes/invoices/create_service.rb
app/services/integrations/aggregator/taxes/invoices/payloads/avalara.rb
app/services/integrations/aggregator/taxes/invoices/void_service.rb
app/services/invoices/provider_taxes/void_service.rb
spec/fixtures/integration_aggregator/taxes/invoices/failure_response_locked_void.json
spec/jobs/invoices/provider_taxes/void_job_spec.rb
spec/services/integrations/aggregator/taxes/credit_notes/payloads/avalara_spec.rb
spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb
spec/services/integrations/aggregator/taxes/invoices/payloads/avalara_spec.rb
spec/services/integrations/aggregator/taxes/invoices/void_service_spec.rb
spec/services/invoices/provider_taxes/void_service_spec.rb

Lago is currently adding integration with tax provider Avalara.
This PR handles void invoice flow.
When invoice is voided in Lago it needs to be reported in the tax provider.
The only exception is when Avalara transaction is in the locked state. In that case, it is not possible to change transaction in any way, so we need to create negative transaction which will act as the refund.
This one is opened instead of https://github.com/getlago/lago-api/pull/3604

feat (avalara-integration): Cover void invoice flow

---

app/graphql/types/data_exports/credit_notes/filters_input.rb
app/graphql/types/data_exports/invoices/filters_input.rb
app/services/data_exports/csv/credit_notes.rb
app/services/data_exports/csv/invoices.rb
schema.graphql
schema.json
spec/graphql/types/data_exports/credit_notes/filters_input_spec.rb
spec/graphql/types/data_exports/invoices/filters_input_spec.rb
spec/services/data_exports/csv/credit_notes_spec.rb
spec/services/data_exports/csv/invoices_spec.rb

When creating a data export, if an organization has multiple entities, we want to show the billing_entity_code in the csv export
- Added billing_entity_code into filters input for invoices and credit notes
- Added an optional column to the data export csv, if an organization has multiple billing_entities

Feat(multientiites): add billing entities to data exports

---

app/services/customers/eu_auto_taxes_service.rb
spec/jobs/customers/retry_vies_check_job_spec.rb
spec/services/customers/eu_auto_taxes_service_spec.rb

When applying eu_tax_management from billing_entity, the default country should be taken from the billing_entity

Fix(multientities): fix eu_tax country source

---

app/mailers/invoice_mailer.rb
app/models/billing_entity.rb
app/views/invoice_mailer/finalized.slim
config/locales/de/email.yml
config/locales/en/email.yml
config/locales/es/email.yml
config/locales/fr/email.yml
config/locales/it/email.yml
config/locales/nb/email.yml
config/locales/sv/email.yml
spec/mailers/invoice_mailer_spec.rb
spec/models/billing_entity_spec.rb

👉  https://getlago.canny.io/feature-requests/p/support-billing-from-multiple-entities
Invoice mailer uses billing entity (instead of organization) as data source for name, email from, etc. Also, update the email template and locale accordingly.

feat(multi entities): Invoice mailer uses billing entity as data source

---

app/controllers/api/v1/billing_entities_controller.rb
app/graphql/mutations/billing_entities/update.rb
app/graphql/types/billing_entities/object.rb
app/graphql/types/billing_entities/update_input.rb
app/models/api_key.rb
app/services/billing_entities/update_service.rb
config/environments/test.rb
config/routes.rb
schema.graphql
schema.json
spec/graphql/mutations/billing_entities/update_spec.rb
spec/requests/api/v1/billing_entities_controller_spec.rb
spec/services/billing_entities/update_service_spec.rb

Add PUT /api/v1/billing_entity/:billing_entity_code REST endpoint and Billing Entity Update GraphQL mutation to update a billing entity.
Also fixes the billing entities update service to also allow updating the billing entity name as it was missing.

feat(multi entities): Add REST endpoint and GraphQL mutation to update a billing entity

---

app/controllers/api/v1/billing_entities_controller.rb
app/graphql/mutations/billing_entities/create.rb
app/graphql/types/billing_entities/create_input.rb
config/routes.rb
spec/graphql/mutations/billing_entities/create_spec.rb
spec/requests/api/v1/billing_entities_controller_spec.rb

Add POST /api/v1/billing_entity REST endpoint
and Billing Entity create GraphQL mutation to create a billing entity.

feat(multi entities): Add REST endpoint and GraphQL mutation to create a billing entity

---

config/initializers/console.rb

Rails 8.0 [removed deprecated Rails::ConsoleMethods](https://guides.rubyonrails.org/8_0_release_notes.html#railties), which broke our console helpers. 
This PR uses the new way of defining console helper, which I should have used from the beginning 😬
As I'm on support, I really miss the `find` helper!
https://github.com/getlago/lago-api/blob/009a8bbc03603bcda524061e2f493292ad943cb3/config/initializers/console.rb#L20-L28

fix(console): Fix console helpers

---

app/services/payment_providers/stripe/register_webhook_service.rb

When setting up Stripe in Lago, you must use the private key, not the publishable one.
When registering webhook an error is raised by stripe but it wasn't forwarded to the users and created a dead job.
```
Stripe::PermissionError: This API call cannot be made with a publishable API key. Please use a secret API key. You can find a list of your API keys at https://dashboard.stripe.com/account/apikeys.
```

fix(stripe): Deliver error webhook when wrong key for registering webhooks

---

app/mailers/credit_note_mailer.rb
app/mailers/invoice_mailer.rb
app/mailers/payment_receipt_mailer.rb
app/mailers/payment_request_mailer.rb
app/models/billing_entity.rb
app/models/payment_receipt.rb
app/services/payment_receipts/create_service.rb
app/views/credit_note_mailer/created.slim
app/views/payment_receipt_mailer/created.slim
app/views/payment_request_mailer/requested.slim
config/locales/de/email.yml
config/locales/en/email.yml
config/locales/es/email.yml
config/locales/fr/email.yml
config/locales/it/email.yml
config/locales/nb/email.yml
config/locales/sv/email.yml
db/migrate/20250515083649_add_billing_entity_id_to_payment_receipts.rb
db/migrate/20250515083802_populate_payment_receipts_billing_entity_id.rb
db/migrate/20250515083935_set_payment_receipts_not_null_constraint_on_billing_entity_id.rb
db/migrate/20250515085230_validate_set_payment_receipts_not_null_constraint_on_billing_entity_id.rb
db/structure.sql
spec/factories/payment_receipts.rb
spec/mailers/credit_note_mailer_spec.rb
spec/mailers/payment_receipt_mailer_spec.rb
spec/mailers/payment_request_mailer_spec.rb
spec/models/billing_entity_spec.rb
spec/models/payment_receipt_spec.rb
spec/scenarios/dunning/dunning_campaign_v1_spec.rb

- Add `billing_entity_id` to `payment_receipts` to identify the billing entity from which the payment receipt was issued.
- Migrate all existing payment receipts to have a `billing_entity_id`.
- Migrate payment receipts, payment requests, and credit notes mailers and templates to use the `billing_entity` as source of …

feat(multientities): add billing_entity_id to payment_receipts and mailers

---

config/initializers/console.rb

Going through your dead queue can be painful if one jobs failed a lot. You might miss more important jobs.
```
lago-api(dev)> deadjobs_summary
=>
{"Clock::ConsumeSubscriptionRefreshedQueueJob" => 7044,
"Clock::ProcessAllSubscriptionActivitiesJob" => 14,
"Clock::FreeTrialSubscriptionsBillerJob" => 1,
"Clock::RefreshDraftInvoicesJob" => 1,
"Clock::ActivateSubscriptionsJob" => 17,
"SendHttpWebhookJob" => 9,
"SendWebhookJob" => 29,
"PaymentProviderCustomers::StripeCheckoutUrlJob" => 1,
"Clock::SubscriptionsToBeTerminatedJob" => 2,
"Clock::ComputeAllDailyUsagesJob" => 1,
"Clock::TerminateEndedSubscriptionsJob" => 1,
"Subscriptions::OrganizationBillingJob" => 1}
```

feat(console): Add `deadjobs_summary` helper

---

app/models/application_record.rb
db/migrate/20230403093407_add_balance_cents_to_wallets.rb
db/migrate/20230626124005_migrate_organization_taxes.rb
db/migrate/20250325145324_assign_customers_to_billing_entities.rb
db/migrate/20250402135038_assign_discarded_customers_to_billing_entities.rb

In some context, when a migration is adding a new column to a table, Postgres might return a `cached plan must not change result type` in a transaction because the cached query plan is not more valid. This error is then raised as a `ActiveRecord::PreparedStatementCacheExpired` by Rails
See https://flexport.engineering/avoiding-activerecord-preparedstatementcacheexpired-errors-4499a4f961cf
This fix is forcing rails to query explicitly every columns in select instead of using `SELECT *`, so that the cached plan remains valid in the transaction. The only drawback will be with column removal, but it should never happen on a used field and would be prevented by `strong_migrations`

misc: avoid ActiveRecord::PreparedStatementCacheExpired errors

---

app/jobs/database_migrations/populate_commitments_with_organization_job.rb
app/models/commitment.rb
app/services/plans/create_service.rb
app/services/plans/override_service.rb
app/services/plans/update_service.rb
db/migrate/20250513132423_add_organization_id_to_commitments.rb
db/migrate/20250513132424_add_organization_id_fk_to_commitments.rb
db/migrate/20250513132425_validate_commitments_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `commitments` table.

chore(organization): Add organization_id to commitments table

---

app/jobs/database_migrations/populate_commitments_taxes_with_organization_job.rb
app/models/commitment/applied_tax.rb
app/services/commitments/apply_taxes_service.rb
db/migrate/20250513144352_add_organization_id_to_commitments_taxes.rb
db/migrate/20250513144353_add_organization_id_fk_to_commitments_taxes.rb
db/migrate/20250513144354_validate_commitments_taxes_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `commitments_taxes` table.

chore(organization): Add organization_id to commitments_taxes table

---

app/jobs/database_migrations/populate_credit_note_items_with_organization_job.rb
app/models/credit_note_item.rb
app/services/credit_notes/create_service.rb
app/services/credit_notes/estimate_service.rb
db/migrate/20250513151258_add_organization_id_to_credit_note_items.rb
db/migrate/20250513151259_add_organization_id_fk_to_credit_note_items.rb
db/migrate/20250513151260_validate_credit_note_items_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `credit_note_items` table.

chore(organization): Add organization_id to credit_note_items table

---

app/jobs/database_migrations/populate_integration_resources_with_organization_job.rb
app/models/integration_resource.rb
app/services/integrations/aggregator/credit_notes/create_service.rb
app/services/integrations/aggregator/invoices/create_service.rb
app/services/integrations/aggregator/invoices/hubspot/create_service.rb
app/services/integrations/aggregator/payments/create_service.rb
app/services/integrations/aggregator/subscriptions/hubspot/create_service.rb
app/services/integrations/aggregator/taxes/credit_notes/create_service.rb
db/migrate/20250513152805_add_organization_id_to_integration_resources.rb
db/migrate/20250513152806_add_organization_id_fk_to_integration_resources.rb
db/migrate/20250513152807_validate_integration_resources_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `integration_resources` table.

chore(organization): Add organization_id to integration_resources table

---

app/jobs/database_migrations/populate_integration_customers_with_organization_job.rb
app/models/integration_customers/anrok_customer.rb
app/models/integration_customers/avalara_customer.rb
app/models/integration_customers/base_customer.rb
app/models/integration_customers/hubspot_customer.rb
app/models/integration_customers/netsuite_customer.rb
app/models/integration_customers/salesforce_customer.rb
app/models/integration_customers/xero_customer.rb
app/services/integration_customers/anrok_service.rb
app/services/integration_customers/avalara_service.rb
app/services/integration_customers/create_service.rb
app/services/integration_customers/hubspot_service.rb
app/services/integration_customers/netsuite_service.rb
app/services/integration_customers/salesforce_service.rb
app/services/integration_customers/xero_service.rb
db/migrate/20250513153628_add_organization_id_to_integration_customers.rb
db/migrate/20250513153629_add_organization_id_fk_to_integration_customers.rb
db/migrate/20250513153630_validate_integration_customers_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `integration_customers` table.

chore(organization): Add organization_id to integration_customers table

---

db/migrate/20250516084025_rebuild_invoice_index_on_billing_entity_sequential_id.rb
db/structure.sql

PGHero indicates that invoices indes on billing_entity_id and billing_entity_sequential_id is broken and suggests us to recreate it
- drop existing index
- create it again

Fix: rebuild invoices index

---

app/jobs/database_migrations/populate_integration_items_with_organization_job.rb
app/models/integration_item.rb
app/services/integrations/aggregator/accounts_service.rb
app/services/integrations/aggregator/items_service.rb
db/migrate/20250516095313_add_organization_id_to_integration_items.rb
db/migrate/20250516095314_add_organization_id_fk_to_integration_items.rb
db/migrate/20250516095315_validate_integration_items_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `integration_items` table.

chore(organization): Add organization_id to integration_items table

---

app/models/clickhouse/activity_log.rb
schema.graphql
schema.json
spec/graphql/types/activity_logs/activity_type_enum_spec.rb

This PR adds the `invoice.one_off_created` type for Activity Log.

fix(activity-log):add invoice.one_off_created to ActivityTypeEnum

---

app/graphql/types/credit_notes/object.rb
app/graphql/types/invoices/object.rb
app/services/integrations/aggregator/taxes/invoices/create_service.rb
schema.graphql
schema.json
spec/fixtures/integration_aggregator/taxes/invoices/success_response.json
spec/graphql/types/invoices/object_spec.rb
spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb

Currently Lago is implementing integration with Avalara tax tool
This PR stores external transaction ID and expose it in GQL. This information is used in the UI for constructing avalara transaction URL

feat(avalara-integration): store avalara external transaction id

---

app/services/fees/init_from_adjusted_charge_fee_service.rb
spec/services/fees/init_from_adjusted_charge_fee_service_spec.rb

Adjusting the amount on a fee with 0 units leads to `NaN` value set on `fees.precise_unit_amount`
This PR makes sure that fees.precise_unit_amount fallback to 0 when the number of units is 0

fix(adjusted_fees): Avoid NaN precise amount cents on fees when 0 units

---

app/services/integrations/aggregator/taxes/invoices/payloads/avalara.rb
spec/services/integrations/aggregator/taxes/invoices/create_service_spec.rb
spec/services/integrations/aggregator/taxes/invoices/payloads/avalara_spec.rb

Lago is currently adding integration with tax provider Avalara.
This PR fixes payload for reporting invoices in avalara. Amount needs to be string and subunit to unit conversion need to take  into account one-off form where taxes are fetched for non-existing fees

fix(avalara-integration): add small avalara payload fix

---

app/jobs/database_migrations/populate_recurring_transaction_rules_with_organization_job.rb
app/models/pricing_unit.rb
app/models/recurring_transaction_rule.rb
app/services/wallets/recurring_transaction_rules/create_service.rb
app/services/wallets/recurring_transaction_rules/update_service.rb
db/migrate/20250519084647_add_organization_id_to_recurring_transaction_rules.rb
db/migrate/20250519084648_add_organization_id_fk_to_recurring_transaction_rules.rb
db/migrate/20250519084649_validate_recurring_transaction_rules_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `recurring_transaction_rules` table.

chore(organization): Add organization_id to recurring_transaction_rules

---

app/jobs/database_migrations/populate_integration_collection_mappings_with_organization_job.rb
app/models/integration_collection_mappings/anrok_collection_mapping.rb
app/models/integration_collection_mappings/avalara_collection_mapping.rb
app/models/integration_collection_mappings/base_collection_mapping.rb
app/models/integration_collection_mappings/netsuite_collection_mapping.rb
app/models/integration_collection_mappings/xero_collection_mapping.rb
app/services/integration_collection_mappings/create_service.rb
db/migrate/20250519085909_add_organization_id_to_integration_collection_mappings.rb
db/migrate/20250519085910_add_organization_id_fk_to_integration_collection_mappings.rb
db/migrate/20250519085911_validate_integration_collection_mappings_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `integration_collection_mappings` table.

chore(organization): Add organization_id to integration_collection_mappings table

---

app/jobs/database_migrations/populate_refunds_with_organization_job.rb
app/models/refund.rb
app/services/credit_notes/refunds/adyen_service.rb
app/services/credit_notes/refunds/gocardless_service.rb
app/services/credit_notes/refunds/stripe_service.rb
db/migrate/20250519092051_add_organization_id_to_refunds.rb
db/migrate/20250519092052_add_organization_id_fk_to_refunds.rb
db/migrate/20250519092053_validate_refunds_organizations_foreign_key.rb
db/structure.sql
spec/organization_id_column_spec.rb

The current one is adding the field to the `refunds` table.

chore(organization): Add organization_id to refunds table

---

app/services/credit_notes/refunds/adyen_service.rb
app/services/credit_notes/refunds/gocardless_service.rb
app/services/credit_notes/refunds/stripe_service.rb

Fix related to https://github.com/getlago/lago-api/pull/3674
The PR introduced a bug by trying to assign `organization_id` to the `organizaton` attribute

fix(refund): Assign organization_id

---

app/jobs/daily_usages/compute_job.rb

Clickhouse raises an error instead of autoscaling when `DailyUsages::ComputeJob` is running on the old pod during the rollout.
Retry the job when this happens.

fix(daily-usages): Retry job on ActiveRecordError

---

app/jobs/clock/mark_invoices_as_payment_overdue_job.rb
app/services/invoices/payments/mark_overdue_service.rb
spec/services/invoices/payments/mark_overdue_service_spec.rb

This PR extract the action to mark an invoice as payment overdue to a service.

feat(audit-logs):extract mark invoice payment overdue service

---

app/graphql/types/subscriptions/object.rb
schema.graphql
schema.json
spec/graphql/types/subscriptions/object_spec.rb

Replaced by `next_subscription*` attributes in #3627

chore(gql): remove deprecated field (see #3627)

---

app/models/payment_providers/stripe_provider.rb
app/services/payment_provider_customers/stripe/sync_funding_instructions_service.rb
app/services/payment_providers/stripe/payments/create_service.rb
spec/services/payment_provider_customers/stripe/sync_funding_instructions_service_spec.rb
spec/services/payment_providers/stripe/payments/create_service_spec.rb

Stripe only supports a limited list of countries when creating `eu_bank_transfer` funding instructions. If a customer's country is not in that list, the request fails with a 400 error.
This feature request aims to allow accepting bank transfers from any European country by defaulting to the organization if that country is supported.
- A fallback mechanism was added when creating Stripe funding instructions for the type `eu_bank_transfer`.
- If the customer's country is unsupported, the system checks whether the organization's country is supported.

feat: Fallback to organization country for EU bank transfers

---

app/graphql/types/activity_logs/object.rb
app/graphql/types/activity_logs/resource_object.rb
schema.graphql
schema.json
spec/graphql/types/activity_logs/object_spec.rb
spec/graphql/types/activity_logs/resource_object_spec.rb

Examples:
The goal of this PR is to return activity log resource as an object.

feat(audit-logs): Return resource as an object for graphql

---

app/services/fees/estimate_instant/base_service.rb
app/services/lifetime_usages/check_thresholds_service.rb
spec/services/fees/estimate_instant/batch_pay_in_advance_service_spec.rb
spec/services/fees/estimate_instant/pay_in_advance_service_spec.rb

when estimating instant fees, we're using a new service, and there we're assuming that amount of units is sent in the event, but some aggregation types do not contain units in properties, because we consider the whole event as unit
- If charge billable_metric does not support field name, we should consider the whole event as one unit
- small additional fix: when generating progressive billing invoice, this process can fail because of idempotency, if it was triggered multiple times, so  we don't want to send the webhook if the invoice generation failed

fix(estimate fees): return 1 unit for estimate count_aggr

---

app/models/organization.rb
app/models/usage_monitoring/alert.rb
app/models/usage_monitoring/billable_metric_usage_units_alert.rb
app/models/usage_monitoring/lifetime_usage_amount_alert.rb
app/services/usage_monitoring/create_alert_service.rb
app/services/usage_monitoring/process_subscription_activity_service.rb
app/services/usage_monitoring/update_alert_service.rb
db/migrate/20250520155108_add_billable_metric_usage_units_alert_type_to_enum.rb
db/migrate/20250520170402_add_lifetime_usage_amount_alert_type_to_enum.rb
db/structure.sql
schema.graphql
schema.json
spec/factories/usage_monitoring/alerts.rb
spec/models/organization_spec.rb
spec/models/usage_monitoring/billable_metric_usage_amount_alert_spec.rb
spec/models/usage_monitoring/billable_metric_usage_units_alert_spec.rb
spec/models/usage_monitoring/lifetime_usage_amount_alert_spec.rb
spec/scenarios/usage_monitoring/subscription_alerts_spec.rb
spec/services/usage_monitoring/create_alert_service_spec.rb
spec/services/usage_monitoring/process_subscription_activity_service_spec.rb
spec/services/usage_monitoring/update_alert_service_spec.rb
spec/support/scenarios_helper.rb

We're adding Alerting feature, see #3528, #3535, #3554, #3600
We introducing 2 new types of alerts:
* LifetimeUsageAmount: to define alert based on lifetime total usage
* BillableMetricUsageUnits: same as BillableMetricUsageAmount but with a number "used units" instead of currency amount.
Creating a new alert is essentially creating a new child class of `UsageMonitoring::Alert` and implementing `find_value`. 🙌

feat(alerting): Add LifetimeUsageAmount and BillableMetricUsageUnits alerts

---

app/services/utils/activity_log.rb
spec/services/utils/activity_log_spec.rb

Examples:
The goal of this PR is to return deleted activity object for activity logs.

feat(audit-logs): Return activity_object for deleted log

---

app/graphql/resolvers/activity_logs_resolver.rb
app/graphql/types/activity_logs/resource_type_enum.rb
app/models/clickhouse/activity_log.rb
schema.graphql
schema.json
spec/graphql/types/activity_logs/resource_type_enum_spec.rb

Examples:
The goal of this PR is to set resource_type as an enum for activity logs resolver.

feat(audit_logs): Add resource_type as an enum

---

app/models/charge.rb
app/models/charge_filter.rb
app/models/concerns/charge_properties_validation.rb
app/services/charges/validators/base_service.rb
app/services/charges/validators/standard_service.rb
spec/services/charges/validators/graduated_percentage_service_spec.rb
spec/services/charges/validators/graduated_service_spec.rb
spec/services/charges/validators/package_service_spec.rb
spec/services/charges/validators/percentage_service_spec.rb
spec/services/charges/validators/standard_service_spec.rb
spec/services/charges/validators/volume_service_spec.rb
spec/support/shared_examples/charges/pricing_group_keys_validation.rb

This PR is part of an epic to add grouped_by feature on all charge models and not only on the standard one like today. 
This PR is the first step:
- It refactors the validation logic for `Charge` and `ChargeFilter` to share the logic
- It moves the grouped_by validation logic from the `Charges::Validators::StandardService` to the `Charges::Validators::BaseService` so that it can be applied to all charge models
- It adds the ability to send grouping keys via `pricing_group_keys` or `grouped_by` to ensure a smooth transition between the two keys.
For now `grouped_by` properties remains whitelisted only on the standard charge model. This will remain like this until the grouped_by logic is applied to all charge model

feat(pricing_group_keys): Add validation logic for all charge models

---

app/graphql/resolvers/activity_logs_resolver.rb
app/queries/activity_logs_query.rb
schema.graphql
schema.json
spec/graphql/resolvers/activity_logs_resolver_spec.rb
spec/queries/activity_logs_query_spec.rb

Examples:
The goal of this PR is to add `activityIds` to the activity logs resolver.

feat(audit-logs): Add activity ids filter

---

app/serializers/v1/customers/charge_usage_serializer.rb
app/services/daily_usages/fill_from_invoice_service.rb
spec/serializers/v1/customers/charge_usage_serializer_spec.rb

This PR fixes a bug that calculates usages and pre-fills `daily_usages` table:
- dates from to were not charges dates
- the serializer that is used was not grouping charge filters

fix(daily-usage): Fix from and to dates in daily usages service

---

app/models/wallet.rb
db/migrate/20250526111147_add_allowed_fee_types_to_wallets.rb
db/structure.sql
spec/models/wallet_spec.rb

Currently, wallet credits are applied to all type of fees in the invoice. With this feature, users will be able to limit spending on specific fee type.
This PR adds basic model and DB changes

ftr(wallets-with-fee-limitations): add model and db changes for wallets with fee limitations

---

app/services/credits/applied_prepaid_credit_service.rb

This PR is a new attempt to approach the issue of parallel wallet refresh refresh in the case of in payed in advance events.
The PR moves fro pessimistic locking (`FOR UPDATE NOWAIT`) to an optimistic one using the `lock_version` already present on the wallets table.
An automatic retry logic is added around the wallet decrease logic with a random wait time between each attempt. It reduce the effect of the error to the decrease logic only instead of the all event processing like it is today.
Finally in case of error, the error is re-raised and the entire logic will be retried by Sidekiq

fix(wallet): Optimistic locking for in advance events

---

app/models/invoice.rb
app/models/payment.rb
app/models/payment_request.rb
app/services/payment_providers/adyen/webhooks/chargeback_service.rb
app/services/payment_providers/stripe/webhooks/charge_dispute_closed_service.rb
app/services/payments/lose_dispute_service.rb
spec/factories/payment_requests.rb
spec/models/payment_spec.rb
spec/services/payment_providers/adyen/webhooks/chargeback_service_spec.rb
spec/services/payment_providers/stripe/webhooks/charge_dispute_closed_service_spec.rb
spec/services/payments/lose_dispute_service_spec.rb

A payment has `payable` which can be an Invoice or a `PaymentRequest`.
When a dispute is lost, Stripe sends a `charge.dispute.closed` webhook with the payment details included. When attached to an invoice, the invoice is flagged as disputed but it it was a PaymentRequest, it wasn't handled.
This PR loops over each invoices of the PaymentRequest and mark them as disputed.
The Adyen service was also updated and since the test don't mock the service call, but check the result, they don't need to be updated.
Note that the original `Invoices::LoseDisputeService` is still [used by GraphQL](https://github.com/getlago/lago-api/blob/b99e8a592fa2d736ce772ff0abff5257fc879543/app/graphql/mutations/invoices/lose_dispute.rb#L19) when marking an invoice as last.

feat(stripe): Mark invoice as disputed for PaymentRequest

---

app/jobs/usage_monitoring/process_organization_subscription_activities_job.rb
app/services/usage_monitoring/process_all_subscription_activities_service.rb
spec/jobs/usage_monitoring/process_organization_subscription_activities_job_spec.rb
spec/services/usage_monitoring/process_all_subscription_activities_service_spec.rb

Alerting is not a premium integration, any premium organization can use it.
Instead of enqueueing a job for all organizations, we use the db to get a list of organization and a count of jobs.
The previous log is moved the clock jobs and more importantly: it's formatted.

fix(alerting): Better All SubscriptionActivity job

---

app/controllers/api/v1/credit_notes_controller.rb
app/graphql/mutations/credit_notes/create.rb
app/graphql/mutations/credit_notes/download.rb
app/jobs/credit_notes/generate_pdf_job.rb
app/mailers/credit_note_mailer.rb
app/models/wallet_transaction.rb
app/services/credit_notes/create_from_progressive_billing_invoice.rb
app/services/credit_notes/create_service.rb
app/services/credit_notes/generate_service.rb
app/services/credit_notes/refunds/adyen_service.rb
app/services/credit_notes/refunds/gocardless_service.rb
app/services/credit_notes/refunds/stripe_service.rb
app/services/invoices/refresh_draft_and_finalize_service.rb
app/services/utils/activity_log.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/credit_notes/generate_service_spec.rb
spec/services/credit_notes/refunds/adyen_service_spec.rb
spec/services/credit_notes/refunds/gocardless_service_spec.rb
spec/services/credit_notes/refunds/stripe_service_spec.rb
spec/services/invoices/refresh_draft_and_finalize_service_spec.rb

Examples:
The goal of this PR is to create activity logs for credit notes.

feat(audit_logs): Activity log for credit notes

---

app/services/invoices/void_service.rb
app/services/wallet_transactions/mark_as_failed_service.rb
spec/services/invoices/void_service_spec.rb
spec/services/wallet_transactions/mark_as_failed_service_spec.rb

we got a bug where:
1. a credit was purchased (1$)
2. invoice marked as succeeded -> wallet transaction marked as settled,
3. wallet balance is updated to 1$
4. invoice payment status updated to failed -> wallet transaction marked as failed
5. wallet balance WAS NOT updated (still 1$) - FIRST ISSUE
6. invoice is voided -> recredit wallet_transaction is created - SECOND ISSUE
7. wallet balance increases to 2$
- when fail a wallet transaction, if a transaction was settled before, it will stay settled, the credits should be voided manually
- when recredit wallet_transactions when voiding an invoice, only recredit outbound wallet transaction (exactly "applied" credits from the wallet)

Fix(wallet balance): failed transaction and voided invoice

---

app/jobs/clock/terminate_ended_subscriptions_job.rb
app/models/daily_usage.rb
app/services/base_service.rb
app/services/daily_usages/compute_all_service.rb
app/services/subscriptions/activate_service.rb
app/services/subscriptions/free_trial_billing_service.rb
app/services/subscriptions/organization_billing_service.rb
app/services/utils/timezone.rb
app/services/wallets/create_interval_wallet_transactions_service.rb
spec/services/daily_usages/compute_all_service_spec.rb

Since we're removing timezone from organization, when performing billing or other jobs, the customer's timezone should be taken from the billing entity, not from the organization
- Updated `at_time_zone` helper to use billing_entity
- updated includes where this helper is used to not load organization where not needed

Feat(multientities): use billing entity timezone

---

app/models/usage_monitoring/alert.rb
app/services/usage_monitoring/create_alert_service.rb
spec/models/usage_monitoring/alert_spec.rb
spec/services/usage_monitoring/create_alert_service_spec.rb

* Use error code `value_already_exist` instead of `value_already_exists`
* fix problem where recurring threshold has the same value as non-recurring threshold

fix(alerting): small QA return

---

app/graphql/types/data_api/usages/object.rb
app/services/data_api/usages_service.rb
schema.graphql
schema.json
spec/factories/billable_metrics.rb
spec/graphql/types/data_api/usages/object_spec.rb
spec/services/data_api/usages_service_spec.rb

We need to add `is_billable_metric_deleted` attribute for usages so that users can filter on that in the UI.
Add `is_billable_metric_deleted` to `DataApiUsages` resolver.

feat(data-api): Add is_billable_metric_deleted argument

---

app/models/organization.rb

This PR follows https://github.com/getlago/lago-api/pull/3722.
The `clickhouse_aggregation` was recently removed from the organization table.
Because the deploy of this change lead to a lot of issues as we are relying on `ApplicationRecord#ignored_columns` to avoid `ActiveRecord::PreparedStatementCacheExpired`, this PR mark the removed column as ignored_columns to reduce the risk of error.
For future columns removal, this approach will be done before pushing the migration.

misc(organization): Exclude remove clickhouse_aggregation column

---

app/services/wallets/create_service.rb
app/services/wallets/update_service.rb
app/services/wallets/validate_limitations_service.rb
app/services/wallets/validate_service.rb
spec/services/wallets/create_service_spec.rb
spec/services/wallets/update_service_spec.rb
spec/services/wallets/validate_limitations_service_spec.rb
spec/services/wallets/validate_service_spec.rb

Currently wallet credits are applied on all fee types. This feature adds possibility to limit wallet consumption on specific fee type.
This PR adds support for new `applies_to` attribute which is the main object for various limitations. The first limitation will be the one related to fee type, but in the future `applies_to` will be extended with more limitations

ftr(wallet-limitations): add support for limitations in wallet services

---

app/config/permissions/role-manager.yml

Account Manager should be able to view billing_entities in order to create customers associated to a billing_entity

Fix: modify managers role permission

---

app/controllers/api/v1/invoices_controller.rb
app/graphql/mutations/invoices/create.rb
app/graphql/types/activity_logs/object.rb
app/jobs/invoices/prepaid_credit_job.rb
app/models/payment_receipt.rb
app/services/credit_notes/refunds/adyen_service.rb
app/services/credit_notes/refunds/gocardless_service.rb
app/services/credit_notes/refunds/stripe_service.rb
app/services/subscriptions/terminate_service.rb
app/services/utils/activity_log.rb
spec/services/credit_notes/refunds/adyen_service_spec.rb
spec/services/credit_notes/refunds/gocardless_service_spec.rb
spec/services/credit_notes/refunds/stripe_service_spec.rb

Some fixes for the Activity Logs.
```
"billable_metric.created" => OK
"billable_metric.updated" => OK
"billable_metric.deleted" => OK
"plan.created" => OK
"plan.updated" => OK
"plan.deleted" => OK
"customer.created" => OK
"customer.updated" => OK
"customer.deleted" => OK
"invoice.drafted"
"invoice.failed"
"invoice.created"
"invoice.one_off_created" => FIXED OK
"invoice.paid_credit_added"
"invoice.generated" => OK
"invoice.payment_status_updated" => OK
"invoice.payment_overdue"
"invoice.voided" => OK
"invoice.payment_failure"
"payment_receipt.created" => FIXED OK / *** PaymentReceipt does not have a customer associated
"payment_receipt.generated" => FIXED OK / *** same as "payment_receipt.created"
"credit_note.created" => OK
"credit_note.generated" => OK
"credit_note.refund_failure" => …
```

Activity log fixes

---

app/services/fees/apply_provider_taxes_service.rb
app/services/fees/apply_taxes_service.rb
app/services/integrations/aggregator/taxes/invoices/create_service.rb
app/services/invoices/sync_salesforce_id_service.rb

This PR ensures that the newly added `organization_id` field is correctly set on all models

misc(organization): Ensure organization_id is set everywhere

---

app/services/daily_usages/fill_from_invoice_service.rb
app/services/daily_usages/fill_history_service.rb

The service calculating historical daily usages used to jump to the next period in case of calculating usages for the last day of current period.
- Fix the incorrect day of usages in `FillHistoryService`
- Fix incorrect boundaries in `FillFromInvoiceService`

feat(usage): Fix history usages

---

app/jobs/wallets/refresh_ongoing_balance_job.rb

For Current usage, taxes are fetched in the sync way. Recently throttling error was rescued there in order to display a bit more user friendly message in the API side.
However, wallet refresh job, that is consuming current usage service, does not auto retry new error, that is actually just a wrapper around Throttling Error.
This PR auto retry wallet refresh job for described case

fix: auto retry throttling errors for wallet refresh job

---

app/graphql/resolvers/usage_monitoring/subscription_alerts_resolver.rb
spec/graphql/resolvers/usage_monitoring/subscription_alerts_resolver_spec.rb

We see unexpected memory consumption. We disable lookahead to see if it's the origin of the issue.
See #3695 for original work

revert(gql): disable lookahead to confirm memory bloat origin

---

app/serializers/v1/usage_monitoring/triggered_alert_serializer.rb
db/seeds/alerting.rb
spec/serializers/v1/usage_monitoring/triggered_alert_serializer_spec.rb

As I'm documenting this `alert.triggered` webhook I realize there was some field that could be better.
* `subscription_external_id` is how you can retrieve subscription via the API (instead of lago_id)
* `organization_id` in case you receive webhooks from multiple organizations? It should be everywhere.
I also edited the seeder to seed some TriggeredAlert.

feat(alerting): new field for alert.triggered webhook payload

---

app/graphql/types/charges/properties.rb
app/graphql/types/charges/properties_input.rb
app/models/charge.rb
app/models/charge_filter.rb
app/serializers/v1/charge_filter_serializer.rb
app/serializers/v1/charge_serializer.rb
app/services/billable_metrics/aggregations/base_service.rb
app/services/charges/charge_model_factory.rb
app/services/charges/filter_charge_model_properties_service.rb
app/services/charges/pay_in_advance_aggregation_service.rb
app/services/fees/charge_service.rb
schema.graphql
schema.json
spec/graphql/types/charges/properties_input_spec.rb
spec/graphql/types/charges/properties_spec.rb
spec/models/charge_filter_spec.rb
spec/models/charge_spec.rb
spec/serializers/v1/charge_filter_serializer_spec.rb
spec/serializers/v1/charge_serializer_spec.rb
spec/services/charges/filter_charge_model_properties_service_spec.rb
spec/services/charges/pay_in_advance_aggregation_service_spec.rb
spec/services/fees/charge_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/3666 and is part of an epic to add grouped_by feature on all charge models and not only on the standard one like today. 
This PR is the second step:
- It updates the GraphQL and the Rest APIs to accept and return the new `pricing_group_keys` attribute
- It makes sure that the deprecated `grouped_by` attribute is still accepted and returned
- It adapt the aggregation logic to use the `pricing_group_keys` or the `grouped_by` attributes
For now the grouped aggregation remains remains whitelisted only on the standard and dynamic charge model. This will remain like this until the logic is applied to all charge model

feat(pricing_group_keys): Add new `pricing_group_keys` API attribute

---

app/controllers/api/v1/billing_entities_controller.rb
app/serializers/v1/billing_entity_serializer.rb
app/services/billing_entities/update_service.rb
spec/requests/api/v1/billing_entities_controller_spec.rb
spec/serializers/v1/billing_entity_serializer_spec.rb
spec/services/billing_entities/update_service_spec.rb

PUT /api/v1/billing_entities/:code endpoint now accepts invoice_custom_section_codes param to update the billing entity selected custom sections.

feat(multientities): Update billing entity Invoice custom sections REST

---

app/services/payment_receipts/create_service.rb
app/services/payment_receipts/generate_pdf_service.rb
spec/services/payment_receipts/generate_pdf_service_spec.rb

The goal of this PR is to prevent creating duplicate activity logs when:
- creating a payment receipt (we can receive multiple stripe events)
- generating the pdf of a payment receipt (only create the activity log when the pdf were not present)

fix(audit-logs): Prevent payment receipt duplicate logs

---

app/models/billing_entity.rb
app/models/dunning_campaign.rb
app/models/organization.rb
app/services/dunning_campaigns/create_service.rb
app/services/dunning_campaigns/update_service.rb
db/migrate/20250526130953_populate_billing_entity_applied_dunning_campaign.rb
spec/graphql/mutations/dunning_campaigns/update_spec.rb
spec/models/billing_entity_spec.rb
spec/models/dunning_campaign_spec.rb
spec/models/organization_spec.rb
spec/services/dunning_campaigns/update_service_spec.rb

Since source of applied dunning campaign is billing entity, when resetting dunning campaign, we should reset customers through billing_entity

Feat(multientities): dunning campaing - reset associated customers

---

app/services/dunning_campaigns/bulk_process_service.rb
app/services/dunning_campaigns/process_attempt_service.rb
app/services/dunning_campaigns/update_service.rb
db/migrate/20250526130953_populate_billing_entity_applied_dunning_campaign.rb
spec/scenarios/dunning/dunning_campaign_v1_spec.rb
spec/services/dunning_campaigns/bulk_process_service_spec.rb
spec/services/dunning_campaigns/process_attempt_service_spec.rb

As default billing_entity follows organization's applied dunning campaign, we want to use billing_entity.applied_dunning_campaign to process dunning campaign

Feat(multientities): billing_entity source of dunning campaign

---

app/services/billable_metrics/aggregations/base_service.rb
app/services/billable_metrics/prorated_aggregations/base_service.rb
app/services/billable_metrics/prorated_aggregations/sum_service.rb
app/services/billable_metrics/prorated_aggregations/unique_count_service.rb
app/services/charges/charge_models/base_service.rb
app/services/charges/charge_models/percentage_service.rb
app/services/charges/charge_models/prorated_graduated_service.rb
app/services/events/stores/base_store.rb
app/services/events/stores/clickhouse_store.rb
app/services/events/stores/postgres_store.rb
spec/services/billable_metrics/aggregations/count_service_spec.rb
spec/services/billable_metrics/aggregations/max_service_spec.rb
spec/services/billable_metrics/aggregations/sum_service_spec.rb
spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/sum_service_spec.rb
spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
spec/services/events/stores/clickhouse_store_spec.rb
spec/services/events/stores/postgres_store_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/3666 and https://github.com/getlago/lago-api/pull/3681 as part of the epic to add grouped_by feature on all charge models and not only on the standard one like today. 
This PR is the second step:
- Adds the ability to inject a set of  grouped_by values when fetching events in an event store implementation (with_grouped_by_values)
- Takes advantage of this ability to change the implementation of all "per event" aggregation logic making sure it always targets the right pricing_group.
For now the grouped aggregation remains remains whitelisted only on the standard and dynamic charge model. This will change in the next step of this feature.

feat(pricing_group_keys): Add grouped_by logic for per event aggregations

---

app/services/invoices/preview/find_subscriptions_service.rb
app/services/invoices/preview/subscription_plan_change_service.rb
app/services/invoices/preview/subscriptions_service.rb
spec/services/invoices/preview/find_subscriptions_service_spec.rb
spec/services/invoices/preview/subscriptions_service_spec.rb

Current logic for invoice preview does not take into account if existing subscription is in the process of downgrade or upgrade. To generate proper invoice preview we need to slightly adjust data so that subscription state matches one of a new bill run.
Add validation for customer persistence. It improves UX by providing more precise error message for some invalid params.
Add support for proper preview of subscription in a process of being downgraded.

fix(invoice-preview): Support preview for subscription during upgrade or downgrade

---

app/services/integration_customers/netsuite_service.rb
spec/services/integration_customers/netsuite_service_spec.rb

An edge case might occur when there's already a contact created in Netsuite but there's also another job that is trying to create the same contact. In that case another contact in netsuite was created (with new external_id) but then the job failed when trying to save the duplicate in the DB
This PR fixes creating duplicate contacts in `IntegrationCustomers::NetsuiteService` by first checking if the record exists in `integration_customers`table in which case it doesn't even call the nango endpoint and returns the existing integration customer.

fix(netsuite): Do not create duplicate contacts in netsuite

---

app/controllers/api/v1/wallets_controller.rb
app/serializers/v1/wallet_serializer.rb
spec/requests/api/v1/wallets_controller_spec.rb
spec/serializers/v1/wallet_serializer_spec.rb

Currently wallet credits are applied on all fee types. This feature adds possibility to limit wallet consumption on specific fee type.
This PR adds API support for creating and updating wallet with fee type limitation.

feat(wallet-limitations): add api support for wallet limitations

---

db/migrate/20250602145535_create_flat_filters.rb
db/structure.sql
db/views/flat_filters_v01.sql

Today, we are not able to use the cache system for organization using Clickhouse event store, because we are not able to easily identify if an event matches filters. 
As a result all action requiring to compute the usage (current usage, daily_usage...) have to recompute the full usage from 0 every time for all billable metric having received at least 1 event during the period. This is highly inefficient especially for charges with filters, has one filter will lead to one DB query.
With Postgres event store, we are able to use a system with charge filter granularity, we would like to use the same logic for the Clickhouse one.
This PR is a first step to add caching at Clickouse level, it adds a new `flat_filters` database view. This view will be used on event_processor side to check filters …

chore(filter): Add the flat_filters database view

---

app/models/clickhouse/base_record.rb
app/services/invoices/customer_usage_service.rb
app/services/invoices/preview_service.rb

Following the work done in https://github.com/getlago/lago/pull/542, this PR enable the caching logic for organization relying on the Clickhouse event store.
The cache expiration will be handled in the events-processor service.

chore(clickhouse): Enable charge caching

---

app/graphql/types/activity_logs/resource_object.rb
app/models/clickhouse/activity_log.rb
app/services/payment_requests/create_service.rb
schema.graphql
schema.json
spec/graphql/types/activity_logs/activity_type_enum_spec.rb
spec/graphql/types/activity_logs/resource_object_spec.rb
spec/graphql/types/activity_logs/resource_type_enum_spec.rb

Examples:
The goal of this PR is to
- add payment request resource type
- add `payment_request.created` activity log

fix(audit-logs): Add payment request resource type

---

app/serializers/v1/usage_monitoring/triggered_alert_serializer.rb
spec/serializers/v1/usage_monitoring/triggered_alert_serializer_spec.rb

A TriggeredAlert is saved to DB when the current usage of the subscription crosses an alerting thresholds.
It's sent over webhooks (serialized once and saved to `webhooks.payload` column). There is no API or graphql resolver to access triggered alerts.
This adds 2 queries to the serialization. Nowhere in the code we serialize multiple triggered alert, so no "eager load" to edit.
This is done to help customer easily retrieve the customer to warn.

feat(alerting): Serialize `customer_external_id` to TriggeredAlerts

---

app/models/fee.rb
app/models/pricing_unit.rb
app/models/pricing_unit_usage.rb
app/services/fees/charge_service.rb
db/migrate/20250610063400_create_pricing_unit_usages.rb
db/structure.sql
spec/factories/pricing_unit_usages.rb
spec/models/fee_spec.rb
spec/models/pricing_unit_usage_spec.rb
spec/services/fees/charge_service_spec.rb

Another step towards PricingUnit feature, this time adding new model PricingUnitUsage. It will store usage in pricing units for a Fee, leaving Fee model itself not changed.
Add PricingUnitUsage model.
Adjustments to the Fees::ChargeService.

Add PricingUnitUsage model

---

app/graphql/types/dunning_campaigns/object.rb
app/models/dunning_campaign.rb
app/queries/dunning_campaigns_query.rb
app/services/dunning_campaigns/create_service.rb
app/services/dunning_campaigns/update_service.rb
spec/factories/dunning_campaigns.rb
spec/graphql/resolvers/dunning_campaign_resolver_spec.rb
spec/queries/dunning_campaigns_query_spec.rb
spec/services/dunning_campaigns/bulk_process_service_spec.rb
spec/services/dunning_campaigns/create_service_spec.rb
spec/services/dunning_campaigns/process_attempt_service_spec.rb
spec/services/dunning_campaigns/update_service_spec.rb

We're planning to clean up a lot of data in the database for the columns that are not in use anymore. To do so we'll start introducing ignored columns on the models
This PR adds ignored_column on dunning campaign's applied_to_organization

Feat(multientities-cleanup): ignore applied_to_organization at dunning campaign

---

app/controllers/concerns/common.rb
spec/controllers/concerns/common_spec.rb

It was possible to call `GET /api/v1/invoices` API endpoint with impossible `issuing_date_from`, `issuing_date_to` params e.g.: `2025-02-30`
Fix the validation method: `Common#valid_date?`

fix(dates): Fix validation of impossible dates

---

app/services/billing_entities/taxes/manage_taxes_service.rb
app/services/integration_collection_mappings/create_service.rb
app/services/invoices/payments/stripe_service.rb
spec/factories/billing_entity_applied_taxes.rb
spec/factories/charge_applied_taxes.rb
spec/factories/invoices.rb
spec/factories/payment_requests.rb
spec/factories/usage_monitoring/alerts.rb
spec/services/billing_entities/taxes/manage_taxes_service_spec.rb
spec/services/integration_collection_mappings/create_service_spec.rb
spec/services/invoices/payments/stripe_service_spec.rb

The current one is refactoring some factories and ensures that all created records received the correct organization_id. The next step of this epic will be to mark the `organization_id` as required

misc(organization): Ensure organization_id is added everywhere

---

Gemfile

I'm moving to dependencies to both dev and test because it breaks the `rails generate` task.

chore(gems): Fix `rails generate` task

---

app/controllers/api/v1/subscriptions_controller.rb
app/graphql/resolvers/customer_resolver.rb
app/graphql/resolvers/subscription_resolver.rb
schema.graphql
schema.json
spec/graphql/resolvers/customer_resolver_spec.rb
spec/graphql/resolvers/subscription_resolver_spec.rb
spec/requests/api/v1/subscriptions_controller_spec.rb

- Resolve a customer by `external_id`
- Resolve a subscription by `external_id`
It will be used for audit logs for instance, to display a link to the related customer and subscription.

feat: Ability to resolve customer and subscription by external id

---

app/services/credits/applied_coupon_service.rb
app/services/credits/applied_prepaid_credit_service.rb
app/services/credits/progressive_billing_service.rb
spec/services/credits/applied_coupon_service_spec.rb
spec/services/credits/applied_prepaid_credit_service_spec.rb
spec/services/credits/progressive_billing_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb

Currently wallet credits are applied on all fee types. This feature adds possibility to limit wallet consumption on specific fee type.
This PR adds logic that applies wallet credits with fee limitations on certain invoice. Other pieces and pre-requirements are already implemented.

ftr(wallet-limitations): apply wallet with limitations on the invoice

---

app/services/invoices/void_service.rb
spec/graphql/mutations/invoices/void_spec.rb
spec/services/invoices/void_service_spec.rb

Voiding an invoice with the [generate_credit_note]
flag should be exclusive to organizations on a Premium license.  
Prior to this change, non-premium tenants could still try to generate credit notes through the void-invoice path, bypassing licensing rules this would lead to a 500 error on the server 
Added a guard clause in `Invoices::VoidService#call`:
```ruby
def generate_credit_note_allowed?
return true unless generate_credit_note   # nothing requested
License.premium?                          # licence check
end
```

feat: Generate credit note validate License

---

app/controllers/admin/base_controller.rb
app/controllers/admin/organizations_controller.rb
config/routes.rb
spec/requests/admin/organizations_controller_spec.rb
spec/support/admin_helper.rb

This pr adds the create Organization endpoint for admin 
It adds a lightweight admin endpoint to create organizations via API, which is useful for self-hosted users and on-duty ops. POST /admin/organizations takes name and email, spins up the org with an admin invite, and returns both in the response.
Authentication in Admin::BaseController now accepts either the existing Google ID token (Authorization: Bearer …) or a static admin key passed as X-Admin-API-Key, read from ADMIN_API_KEY

feat: Admin add organization 

---

app/jobs/application_job.rb
app/services/invoices/update_service.rb
app/services/utils/activity_log.rb
spec/jobs/application_job_spec.rb
spec/services/invoices/update_service_spec.rb
spec/services/utils/activity_log_spec.rb
spec/support/matchers/job_matcher.rb

When doing a manual payment, it will update the invoice payment status. When doing so, we're supposed to do a few things asynchronously like sending a webhook.
Unfortunately, the way it is working right now, our server will sometimes process those asynchronous jobs before the database transaction ends, and therefore before we actually update the invoice. We end up with not up-to-date data within those different actions.
For instance, the webhook might be triggered with `payment_status: 'pending'` in the payload instead of `payment_status: 'succeeded'`.
This commit fixes this issue by ensuring the jobs run after the transaction is committed. This is done by using `AfterCommitEverywhere.after_commit` callbacks.
To reduce the risk of mistakes, two new class methods were added:
- …

fix(invoice): Fix race-condition in invoice update jobs

---

app/models/payment_providers/adyen_provider.rb
app/services/payment_provider_customers/stripe/update_payment_method_service.rb
app/services/payment_providers/adyen/handle_event_service.rb
app/views/templates/payment_receipts/v1.slim
spec/factories/invoices.rb
spec/fixtures/adyen/webhook_report_available_response.json
spec/services/payment_provider_customers/stripe/update_payment_method_service_spec.rb
spec/services/payment_providers/adyen/handle_event_service_spec.rb
spec/services/payment_receipts/generate_pdf_service_spec.rb

During investigation of dead jobs, we found small issues that can be easily fixed
- Ignore `REPORT_AVAILABLE` Adyen event
- Ignore deleted customer on stripe webhook `customer.updated`
- Fix PDF for payment receipt for progressive billing invoice

Chore: dead jobs small fixes

---

app/models/payment_providers/stripe_provider.rb
app/services/payment_providers/stripe/handle_event_service.rb

This PR ensures that cancelled Stripe payments (e.g. due to uncompleted 3DS authentication) correctly update the corresponding Lago payment status.
Previously, Lago only updated statuses on "failed" payments. As a result, "cancelled" Stripe payments remained stuck in a "pending" state on our side, making it impossible for users to retry them without manual intervention.
Stripe webhook handling now includes logic for payment_intent.canceled events.
Cancelled payments are treated as "failed" in Lago (same as other unrecoverable errors).
This allows users to retry cancelled payments

feat: handle canceled stripe payments

---

app/models/applied_usage_threshold.rb
db/migrate/20250627084430_organization_id_check_constaint_on_applied_usage_thresholds.rb
db/migrate/20250627084852_not_null_organization_id_on_applied_usage_thresholds.rb
db/structure.sql
lib/generators/not_null_organization_id/not_null_organization_id_generator.rb
lib/generators/not_null_organization_id/templates/not_null_organization_id.rb.erb
lib/generators/not_null_organization_id/templates/organization_id_check_constaint.rb.erb

Now that we are done with https://github.com/getlago/lago-api/pull/3687 to add a presence validation on the organization_id field), let's add a proper NOT NULL constraint at the DB level!
This PR adds:
- The not null constraint on  `theapplied_usage_thresholds` table
- Add new `not_null_organization_id` rails generator to make it easier to create the migration files
A lot of new migrations are coming :)

misc(organization): Not null constraint on applied_usage_thresholds

---

db/migrate/20250626175249_refresh_stripe_webhooks.rb

this should not use unscoped since we are trying to update deleted webhooks

Add fix migration

---

app/models/data_export.rb
app/models/data_export_part.rb
app/models/dunning_campaign_threshold.rb
db/migrate/20250627134915_organization_id_check_constaint_on_data_export_parts.rb
db/migrate/20250627134916_not_null_organization_id_on_data_export_parts.rb
db/migrate/20250627134925_organization_id_check_constaint_on_data_exports.rb
db/migrate/20250627134926_not_null_organization_id_on_data_exports.rb
db/migrate/20250627134932_organization_id_check_constaint_on_dunning_campaign_thresholds.rb
db/migrate/20250627134933_not_null_organization_id_on_dunning_campaign_thresholds.rb
db/structure.sql

- `data_export_parts`
- `data_exports`
- `dunning_campaign_thresholds`

misc(organization): Not null constraint on d* models

---

app/services/lifetime_usages/check_thresholds_service.rb
spec/services/lifetime_usages/check_thresholds_service_spec.rb

We are receiving ` Idempotency::IdempotencyError` for progressive billing invoices generation on terminated subscriptions.
We should not generate progressive billing invoices for terminated subscriptions as the usage will be billed anyway with the termination invoice.
This PR simply adds a check on the subscription status before proceeding with the invoice generation.

fix(progressive_billing): Avoid checking threshold on terminated subscriptions

---

app/models/invoice.rb
app/serializers/v1/invoice_serializer.rb
app/services/invoices/void_service.rb
spec/models/invoice_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/invoices/void_service_spec.rb

This PR addresses a limitation in the logic for voiding invoices that was causing confusion and blocking expected behaviour with some customers. Previously, certain invoice states were not allowed to be voided depending on specific internal validations, even if the user explicitly triggered a void action.
This inconsistency was particularly evident when using generate_credit_note: false, where the system applied legacy rules that no longer make sense from a user perspective.
We removed the conditional logic that prevented invoices from being voided under specific internal states.
The behaviour is now simplified:
➡️ If the user calls void, the system will proceed with the voiding process without rejecting it due to previous state-based restrictions.
Potential Downside
This is a silent …

feat: all invoices can be voided now

---

spec/services/invoices/update_service_spec.rb
spec/services/wallet_transactions/create_from_params_service_spec.rb
spec/support/matchers/job_matcher.rb

This is a small refactor to make the matcher closer to the `have_enqueued_job` matcher and improve the error messages.
This also update the `WalletTransactions::CreateFromParamsService` to rely on this matcher after the changes introduced in 4a5e510.

chore(matcher): Rename `enqueue_after_commit` matcher to `have_enqueued_job_after_commit`

---

app/services/payment_requests/payments/create_service.rb
spec/services/payment_requests/payments/create_service_spec.rb

When retrying a failed `PaymentRequests::Payments::CreateJob` (manually or automatically), we are not checking if the attached invoices are still ready for payment processing. This lead to a risk of duplicated payments.
This pull request adds a new guard to the `PaymentRequests::Payments::CreateService` to early return when one of the invoice of the `PaymentRequest` is not flagged as `ready_for_payment_processing`

fix(payment_request): Prevent payment creation when invoices are payment succeeded

---

app/controllers/api/v1/plans/entitlements/privileges_controller.rb
app/controllers/api/v1/plans/entitlements_controller.rb
app/models/entitlement/feature.rb
app/models/entitlement/privilege.rb
app/models/plan.rb
app/services/entitlement/feature_destroy_service.rb
app/services/entitlement/feature_update_service.rb
app/services/entitlement/plan_entitlement_destroy_service.rb
app/services/entitlement/plan_entitlement_privilege_destroy_service.rb
app/services/entitlement/plan_entitlements_create_service.rb
app/services/entitlement/plan_entitlements_update_service.rb
app/services/entitlement/privilege_destroy_service.rb
app/services/plans/destroy_service.rb
spec/models/entitlement/feature_spec.rb
spec/models/entitlement/privilege_spec.rb
spec/models/plan_spec.rb
spec/requests/api/v1/plans/entitlements/privileges_controller_spec.rb
spec/requests/api/v1/plans/entitlements_controller_spec.rb
spec/services/entitlement/feature_destroy_service_spec.rb
spec/services/entitlement/feature_update_service_spec.rb
spec/services/entitlement/plan_entitlement_destroy_service_spec.rb
spec/services/entitlement/plan_entitlement_privilege_destroy_service_spec.rb
spec/services/entitlement/plan_entitlements_create_service_spec.rb
spec/services/entitlement/plan_entitlements_update_service_spec.rb
spec/services/entitlement/privilege_destroy_service_spec.rb
spec/services/plans/destroy_service_spec.rb

When a feature is modified, we send a `plan.updated` webhook for all plan using this feature.
When a feature privilege is modified, we send a `plan.updated` webhook for all plan having a value for this privilege.

feat(entitlement): Send `plan.updated` webhooks

---

.github/workflows/spec.yml
Gemfile
Gemfile.lock

Currently, if a community PR is opened, the`KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC` secret will not be set. This will cause the specs to fail with an error as we are not able to run Knapsack Pro in this case.
This is not an ideal situation as it will complexify the contribution process.
The specs will now run using `parallel_tests` (with the `parallel_rspec` CLI) in the CI workflow as a fallback if the `KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC` secret is not set.
Note that we don't use `parallel_rspec` to actually run the tests in parallel. By combining `--only-group` with `-n`, we tell `parallel_rspec` to:
1. Split the tests into `KNAPSACK_PRO_CI_NODE_INDEX` (8) groups
2. Run only the `KNAPSACK_PRO_CI_NODE_INDEX` group
So we have the same behavior as Knapsack but without a proper distribution …

fix(specs): Run specs using `parallel_tests` in CI if PR is from a community member

---

app/serializers/v1/webhook_endpoint_serializer.rb
spec/serializers/v1/webhook_endpoint_serializer_spec.rb

This PR fixes https://github.com/getlago/lago-python-client/issues/322
The [OpenAPI documentation](https://github.com/getlago/lago-openapi/blob/main/src/schemas/WebhookEndpointObject.yaml#L29) as well as the API SDKs are exposing a `webhook_enpoint.created_at` field, but the `WebhookEndpointSerializer` is not...
This PR adds the missing field

fix(webhook-endpoint): Add missing created_at

---

app/jobs/charges/create_children_job.rb
app/jobs/charges/update_children_job.rb

We have monitored cascade feature on production and it can be really slow to create/update charge with huge number of filters.
We should investigate in detail performance in used services, but the first step could be to reduce batch size

fix: adjust batch size for cascade feature

---

app/models/payment.rb
app/models/recurring_transaction_rule.rb
app/models/refund.rb
db/migrate/20250707082435_organization_id_check_constaint_on_payments.rb
db/migrate/20250707082436_not_null_organization_id_on_payments.rb
db/migrate/20250707082509_organization_id_check_constaint_on_recurring_transaction_rules.rb
db/migrate/20250707082510_not_null_organization_id_on_recurring_transaction_rules.rb
db/migrate/20250707082520_organization_id_check_constaint_on_refunds.rb
db/migrate/20250707082521_not_null_organization_id_on_refunds.rb
db/structure.sql

- `payments`
- `recurring_transaction_rules`
- `refunds`

misc(organization): Not null constraint on p|r* models

---

app/models/wallet.rb
app/models/wallet_transaction.rb
app/models/webhook.rb
db/migrate/20250707083159_organization_id_check_constaint_on_wallets.rb
db/migrate/20250707083160_not_null_organization_id_on_wallets.rb
db/migrate/20250707083210_organization_id_check_constaint_on_wallet_transactions.rb
db/migrate/20250707083211_not_null_organization_id_on_wallet_transactions.rb
db/migrate/20250707083221_organization_id_check_constaint_on_webhooks.rb
db/migrate/20250707083222_not_null_organization_id_on_webhooks.rb
db/structure.sql

- `wallets`
- `wallet_transactions`
- `webhooks`

misc(organization): Not null constraint on w* models

---

app/models/add_on/applied_tax.rb
app/models/fee/applied_tax.rb
app/models/invoice/applied_tax.rb
app/models/plan/applied_tax.rb
db/migrate/20250707085614_organization_id_check_constaint_on_fees_taxes.rb
db/migrate/20250707085615_not_null_organization_id_on_fees_taxes.rb
db/migrate/20250707085633_organization_id_check_constaint_on_plans_taxes.rb
db/migrate/20250707085634_not_null_organization_id_on_plans_taxes.rb
db/migrate/20250707085650_organization_id_check_constaint_on_add_ons_taxes.rb
db/migrate/20250707085651_not_null_organization_id_on_add_ons_taxes.rb
db/migrate/20250707085724_organization_id_check_constaint_on_invoices_taxes.rb
db/migrate/20250707085725_not_null_organization_id_on_invoices_taxes.rb
db/structure.sql

- `add_ons_taxes`
- `fees_taxes`
- `invoices_taxes`
- `plans_taxes`

misc(organization): Not null constraint on *_taxes models

---

app/models/plan.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/preview_service.rb
app/services/subscriptions/dates/monthly_service.rb
app/services/subscriptions/dates/quarterly_service.rb
app/services/subscriptions/dates/weekly_service.rb
app/services/subscriptions/dates/yearly_service.rb
app/services/subscriptions/dates_service.rb
spec/factories/plans.rb
spec/models/plan_spec.rb

While working on a feature, Cursor generated code with the `pay_in_arrears` naming and failed to match the rest of the codebase which uses the incorrect `pay_in_arrear` naming.
This commit fixes the naming in the whole codebase and adds a test for `Plan#pay_in_arrears?`.

chore(naming): Rename `pay_in_arrear` to `pay_in_arrears`

---

app/models/metadata/invoice_metadata.rb
app/models/payment_request/applied_invoice.rb
app/models/usage_threshold.rb
db/migrate/20250707094900_organization_id_check_constaint_on_invoice_metadata.rb
db/migrate/20250707094901_not_null_organization_id_on_invoice_metadata.rb
db/migrate/20250707094931_organization_id_check_constaint_on_invoices_payment_requests.rb
db/migrate/20250707094932_not_null_organization_id_on_invoices_payment_requests.rb
db/migrate/20250707095223_organization_id_check_constaint_on_usage_thresholds.rb
db/migrate/20250707095224_not_null_organization_id_on_usage_thresholds.rb
db/structure.sql

- `invoice_metadata`
- `invoices_payment_requests`
- `usage_threshold`

misc(organization): Not null constraint on i|u_* models

---

app/graphql/resolvers/analytics/invoice_collections_resolver.rb
app/graphql/resolvers/analytics/overdue_balances_resolver.rb
app/graphql/resolvers/data_api/mrrs_resolver.rb
app/graphql/resolvers/data_api/prepaid_credits_resolver.rb
app/graphql/resolvers/data_api/revenue_streams_resolver.rb
app/graphql/resolvers/data_api/usages/aggregated_amounts_resolver.rb
app/graphql/resolvers/data_api/usages/invoiced_resolver.rb
app/graphql/resolvers/data_api/usages_resolver.rb
schema.graphql
schema.json

Add `is_customer_tin_empty` argument to GraphQL resolvers so that is can be passed to Data API.

feat(usages): Add is_customer_tin_empty argument to resolvers

---

app/models/adjusted_fee.rb
app/models/applied_coupon.rb
app/models/applied_invoice_custom_section.rb
app/models/payment_provider_customers/adyen_customer.rb
app/models/payment_provider_customers/base_customer.rb
app/models/payment_provider_customers/cashfree_customer.rb
app/models/payment_provider_customers/gocardless_customer.rb
app/models/payment_provider_customers/moneyhash_customer.rb
app/models/payment_provider_customers/stripe_customer.rb
app/models/subscription.rb
db/migrate/20250707095955_organization_id_check_constaint_on_subscriptions.rb
db/migrate/20250707095956_not_null_organization_id_on_subscriptions.rb
db/migrate/20250707100012_organization_id_check_constaint_on_adjusted_fees.rb
db/migrate/20250707100013_not_null_organization_id_on_adjusted_fees.rb
db/migrate/20250707100025_organization_id_check_constaint_on_applied_coupons.rb
db/migrate/20250707100026_not_null_organization_id_on_applied_coupons.rb
db/migrate/20250707100101_organization_id_check_constaint_on_payment_provider_customers.rb
db/migrate/20250707100102_not_null_organization_id_on_payment_provider_customers.rb
db/migrate/20250707113717_organization_id_check_constaint_on_applied_invoice_custom_sections.rb
db/migrate/20250707113718_not_null_organization_id_on_applied_invoice_custom_sections.rb
db/structure.sql

- `adjusted_fees`
- `applied_coupons`
- `payment_provider_customers`
- `applied_invoice_custom_sections`

misc(organization): Not null constraint on remaining models

---

config/initializers/cors.rb

Necessary for [ISSUE-978](https://linear.app/getlago/issue/ISSUE-978/use-renewed-token-on-new-calls)
To make the response header available on front, we need to expose him on CORS configuration.
https://github.com/getlago/lago-api/blob/51d309a81861aa93fba9288ce97aa43ea8105c0d/config/initializers/cors.rb#L5-L28
This should not expose the header to any other page besides the ones listed on `origins` calls. 
```
ENV["LAGO_FRONT_URL"],
ENV["LAGO_DOMAIN"],
"app.lago.dev",
"api",
"lago.ngrok.dev"
```

allow frontend to read x-lago-token header

---

app/models/charge.rb
db/migrate/20250708094414_add_in_advance_index_to_charge.rb
db/structure.sql

A slow query was identified on the charge table:
```
SELECT count(*) FROM "charges" WHERE (plan_id = $1 AND billable_metric_id = $2) AND pay_in_advance = true AND "charges"."deleted_at" IS NULL
```
This query is made by the events processor to identify if an event needs to be billed in advance. The problem was identified because a big burst of event was post-processed, leading to a pike in CPU usage on the database.
This PR only adds a new index to speed up the processing.

misc(events-processor): Add new index to speed up in advance charge processing

---

app/jobs/charges/create_children_job.rb
app/jobs/charges/update_children_job.rb
app/services/charges/destroy_children_service.rb
spec/jobs/charges/create_children_job_spec.rb
spec/jobs/charges/update_children_job_spec.rb
spec/services/charges/destroy_children_service_spec.rb

Currently cascade feature targets all overridden plans even if linked subscription is terminated
Described scenario can lead to performing unnecessary cascading and this PR fixes it

fix: prevent cascading when overridden plan is not linked to active sub

---

app/models/analytics/invoice_collection.rb
spec/models/analytics/invoice_collection_spec.rb

Filtering by `is_customer_tin_empty` which filters by existent or non-existent customer `tax_identification_number` was missing.
This PR adds the missing filter to invoice collection.

fix(invoice-collection): Add is_customer_tin_empty filter

---

spec/factories/subscriptions.rb
spec/services/subscriptions/update_service_spec.rb

While working on the `Subscriptions::UpdateService`, I noticed some test cases missing so I decided to add them. Adding the following spec failed:
```ruby
context "when specifying only name" do
let(:subscription) { create(:subscription, customer:) }
let(:params) { {name: "new name"} }
it "updates the subscription" do
result = update_service.call
expect(result).to be_success
expect(result.subscription.name).to eq("new name")
expect(result.subscription.subscription_at.to_s).not_to include("2022-07-07")
end
end
```
This is due to the fact that `subscription_at` is `nil` in the factory but:
1. It is expected to be set in the `Subscriptions::UpdateService`
2. It is always set when creating a subscription https://github.com/getlago/lago-api/blob/9eebd429260041b822b1bf46abf51a2b200a54b9/app/servi …

test(factory): Add `subscription_at` to `subscription` factory

---

app/graphql/types/customers/usage/charge.rb
app/services/subscriptions/charge_cache_middleware.rb
schema.graphql
schema.json
spec/graphql/resolvers/customers/usage_resolver_spec.rb
spec/graphql/types/customers/usage/charge_spec.rb

Add displaying amounts in pricing units for current usage.
Adjust GQL type.
Make changes in `ChargeCacheMiddleware` to support caching of `pricing_unit_usage` association for Fee.

feat(pricing-units): Support pricing units in current usage

---

app/services/subscriptions/update_service.rb
spec/services/subscriptions/update_service_spec.rb

`Subscriptions::UpdateService` currently do not ensure that jobs are scheduled after commit. This has no impact right now as the service is not called in a transaction anywhere but it will be the case soon.
This PR ensures the jobs are scheduled after commit.

misc(subscription): Ensure `Subscriptions::UpdateService` uses `perform_after_commit`

---

app/services/billing_entities/update_service.rb
spec/services/billing_entities/update_service_spec.rb

We want to allow users to remove a billing entity logo.
This PR removed the billing entity (blob) if the logo param passed is `nil`

misc: allow to remove a logo when passing nil

---

app/serializers/v1/plan_serializer.rb
app/services/plans/prepare_destroy_service.rb
spec/serializers/v1/plan_serializer_spec.rb

When you delete a plan via the API, you get it in the response but nothing shows that it is deleted or about to be deleted.
Because deletion is async, getting this plan from the API will work as if nothing happened until the job is processed.
Need openapi and clients update.
A plan can have maaany children and since we're not calling a service or relying on any model callbacks, I believe it's best to flag them all at once.
Introduced here: https://github.com/getlago/lago-api/commit/69a84700632f760507eee028ede987184d332971

chore(plans): Use update_all to flag plan children for deletion

---

spec/services/credit_notes/create_service_spec.rb
spec/support/matchers/job_matcher.rb

https://github.com/getlago/lago-api/pull/3965 ensured that `Subscriptions::TerminateService` wraps its logic in a transaction. Since `Subscriptions::TerminateService` implicitly calls `CreditNotes::CreateService`, the tests for `CreditNotes::CreateService` were also updated to confirm that jobs are properly enqueued after the transaction is committed.
Note that I needed to update the `have_enqueued_job_after_commit` matcher so that the `with` chain accepts a block. This is because the job expect to receive the newly created credit note as argument. If we try to pass arguments to `with`, it will be evaluated before the credit note is actually created. So using a block is the only way to verify those arguments.

test(credit-note): Update job assertions for `CreditNotes::CreateService` tests

---

app/jobs/database_migrations/populate_payments_with_customer_id.rb

Earlier we introduced a job that updates payments with customer_id, pulling them from payable object. Apparently we have some Payments for Invoices and PaymentRequests (all of them are for "developer" organizations), where related Invoices or PaymentRequests do not exist in the database. 
Modified requests:
- Only search for payments that, when joined with invoices or payment_requests have invoices.customer_id or payment_request.customer_id

Fix(payments with customer_id): update query that populates payments with customer id

---

app/services/charge_filters/create_or_update_batch_service.rb

The proper way of disabling PaperTrail for a class is calling `PaperTrail.request.disable_model(class)`, without a block
https://github.com/paper-trail-gem/paper_trail?tab=readme-ov-file#per-class

proper way to disable paper trail for classes

---

app/services/base_service.rb
app/services/subscriptions/update_service.rb
app/services/utils/activity_log.rb
spec/services/base_service_spec.rb
spec/services/subscriptions/update_service_spec.rb

The `BaseService` activity logging system did not support controlling when activity logs are produced relative to database transactions. This could cause race conditions when activity logs were created before transactions committed. This is problematic if the transaction later failed as we would log an activity for changes that were rolled back.
This adds an `after_commit` parameter to the `BaseService.activity_loggable` method. Services can now control whether activity logs are produced immediately or after the current transaction commits.
Note that the parameter defaults to `false` for backward compatibility. Even though I believe we should log activities by default after commit, this default allows for incremental changes and tests.
The `Subscriptions::UpdateService` now uses …

misc(activity-log): Add `after_commit` parameter to `BaseService.activity_loggable`

---

.cursor/rules/rails-general.mdc

The AI agents did not behave consistently with certains Rails patterns (enum, migration, etc.) and accurate commit message generation.
This PR adds Conventional Commits specification with guidelines for accurate change descriptions, PostgreSQL enum handling patterns, migration best practices, and model testing rules for enums.

misc(cursor): Add commit message and coding rules

---

db/seeds/04_coupons.rb

Current seeds do not couponts which makes it cumbersome to test certain cases with freshly seeded DBs.

misc(seeds): Update seeds to include coupons

---

app/jobs/daily_usages/fill_from_invoice_job.rb
app/services/invoices/subscription_service.rb

This job was sometimes executed before the actual invoice existed.
Use `after_commit` to ensure the invoice was created before enqueuing a job

Fix(daily-usages): Retry job fix (#3987) - use after_commit instead

---

app/services/charges/calculate_price_service.rb
spec/services/charges/calculate_price_service_spec.rb

This is part of the feature that calculates and saves prices for number of units predicted by ML model.
This PR only contains a service that uses charge model services to calculate price based on multiple input params.

Feat forecast calculate price

---

spec/spec_helper.rb
spec/support/monkey_patches/database_cleaner.rb

This is a follow-up to https://github.com/getlago/lago-api/pull/3914.
Clickhouse database currently doesn't get cleaned up by `DatabaseCleaner`. This can result in tests failing because it expects a clean state. For example, the following test fails:
```ruby
require "rails_helper"
RSpec.describe DatabaseCleaner do
context "with clickhouse: true", clickhouse: true do
it "has zero events" do
expect(Clickhouse::EventsRaw.count).to eq(0)
create(:clickhouse_events_raw)
expect(Clickhouse::EventsRaw.count).to eq(1)
end
it "also has zero events" do
expect(Clickhouse::EventsRaw.count).to eq(0)
end
end
end
```
We get the following error:
```shell
⋊> lago exec api bundle exec rspec --color --format documentation spec/database_cleaner_spec.rb
Run options: include {locations: …
```

chore(specs): Fix `DatabaseCleaner` for `clickhouse` database

---

app/queries/subscriptions_query.rb

This pull request includes a minor fix in the `with_plan_code` method of the `SubscriptionsQuery` class. The change corrects a typo in the table name used in the query.
* [`app/queries/subscriptions_query.rb`](diffhunk://#diff-ee305bb9151bb4336edd6b087887276e3ef0fef59030c9a774a295f8190ade16L64-R64): Fixed a typo in the `with_plan_code` method by changing `plans` to `plan` in the `.where` clause to ensure the query functions correctly.

fix: Abilitiy to filter subscriptions by plan code

---

config/initializers/console.rb

We have some payments that are related to not existing invoices. Since when organizations are setting up, sometimes we have to delete their existing invoices, this should be done together with their payments
Added a step of deleting payments when deleting invocies

Fix(invoice-deletion): when destroying invoices, also destroy it's payments

---

app/graphql/types/entitlement/feature_object.rb
app/models/entitlement/feature.rb
schema.graphql
schema.json
spec/graphql/types/entitlement/feature_object_spec.rb
spec/models/entitlement/feature_spec.rb

Used to display the number of subscription in the frontend. Not returned in the API.
Notice that this is a very nice N+1 😬 but it's acceptable since it's only used in the Frontend, on the Freature list page (this is the same for plans list for instance).
Notice that this return only the active and pending subscription, unlike the plans list that shows also terminated subscriptions.
```sql
SELECT
COUNT(*)
FROM
"subscriptions"
INNER JOIN "plans" "plan" ON "plan"."id" = "subscriptions"."plan_id"
WHERE
"subscriptions"."status" IN (1, 0)
AND (
"subscriptions"."plan_id" IN (
SELECT
"plans"."id"
FROM
"plans"
INNER JOIN "entitlement_entitlements" ON "plans"."id" = "entitlement_entitlements"."plan_id"
WHERE
"plans"."deleted_at" IS NULL
AND "entitlement_entitlements"."deleted_at" IS NULL
AND …
```

feat(entitlement): Add `Feature.subscriptions_count`

---

app/models/entitlement/privilege.rb
db/migrate/20250630180000_create_entitlement_features_and_privileges.rb
db/migrate/20250704800001_create_plan_entitlement.rb
db/migrate/20250717092012_fix_privilege_index.rb
db/structure.sql
spec/models/entitlement/privilege_spec.rb

As I'm adding Feature entitlements, I created 4 tables so far. 
One table had the wrong index because it didn't have the `where deleted_at is null` condition on the unique index 😭 😭 😭 
I'm deleting the index and creating the new one (in that order) because **the feature is NOT released**.

fix(db): Add `where deleted_at is null` condition on privileges

---

app/models/plan.rb
db/migrate/20250716123425_add_bill_fixed_charges_monthly_to_plan.rb
db/structure.sql

in order to support yearly plan with monthly fixed charges, we need to add a new column that will be responsible for storing this data
Added a migration to add `bill_fixed_charges_monthly` field on plan

Feat(fixed_charges): add bill_fixed_charges_monthly to plan

---

app/graphql/types/data_api/mrrs/plans/object.rb
schema.graphql
schema.json
spec/graphql/types/data_api/mrrs/plans/object_spec.rb

`mrr_share` contains `NULL` values but was defined as nullable.
Change `null: false` to `null: true` of `mrr_share` field in `DataApiMrrPlan` GraphQL type

fix(mrrs-plan): Fix GraphQL DataApiMrrPlan mrr_share nullable

---

app/models/fixed_charge.rb
app/models/plan.rb
db/migrate/20250716150049_create_fixed_charges.rb
db/structure.sql
spec/factories/fixed_charges.rb
spec/models/fixed_charge_spec.rb
spec/models/plan_spec.rb

We want to add fixed_charge model that would represent the fixed charges included in the subscription that do not depend on the received usage. This PR adds the migration and model of fixed_charges
- add migration for fixed_charges
- add model and basic tests for fixed_charges

Feat(fixed charges): fixed charge model

---

app/controllers/api/v1/subscriptions_controller.rb
app/models/subscription.rb
app/serializers/v1/subscription_serializer.rb
app/services/subscriptions/terminate_service.rb
app/services/subscriptions/update_service.rb
app/services/subscriptions/validate_service.rb
db/migrate/20250709171329_add_on_termination_credit_note_to_subscriptions.rb
db/structure.sql
spec/models/subscription_spec.rb
spec/requests/api/v1/subscriptions_controller_spec.rb
spec/serializers/v1/subscription_serializer_spec.rb
spec/services/subscriptions/terminate_service_spec.rb
spec/services/subscriptions/update_service_spec.rb
spec/services/subscriptions/validate_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/flexible-credit-note-management
When subscriptions are terminated before their billing period ends, the system previously always created credit notes for unused time on pay-in-advance plans. This inflexible behavior didn't accommodate different business needs where organizations might want to skip credit note generation for certain termination scenarios.
This introduces an `on_termination_credit_note` enum field to subscriptions that controls whether credit notes are created when pay-in-advance subscriptions are terminated early. The field supports "credit" (default) and "skip" values, allowing organizations to choose their preferred termination behavior.
The termination service now respects this setting and only creates credit notes when …

feat(subscriptions): Allow to skip credit note on subscription termination

---

app/graphql/mutations/subscriptions/terminate.rb
app/graphql/types/subscriptions/object.rb
app/graphql/types/subscriptions/on_termination_credit_note_enum.rb
schema.graphql
schema.json
spec/graphql/mutations/subscriptions/terminate_spec.rb
spec/graphql/types/subscriptions/object_spec.rb
spec/graphql/types/subscriptions/on_termination_credit_note_enum_spec.rb

👉  https://getlago.canny.io/feature-requests/p/flexible-credit-note-management
When subscriptions are terminated before their billing period ends, the system previously always created credit notes for unused time on pay-in-advance plans. This inflexible behavior didn't accommodate different business needs where organizations might want to skip credit note generation for certain termination scenarios.
The API already accepts the termination behavior as a parameter during subscription termination but the GraphQL API did not.
This update the `terminateSubscription` mutation to handle the `on_termination_credit_note` behavior.

feat(subscription): Allow to skip credit note creation on subscription termination via GraphQL

---

app/models/wallet.rb
app/services/wallets/balance/refresh_ongoing_service.rb
spec/models/wallet_spec.rb
spec/services/wallets/balance/refresh_ongoing_service_spec.rb

Currently it is not possible to scope wallet consumption to target only specific BM fees
With this PR, ongoing balance calculation will take into account wallet limitations to specific billable metric
Fees: `charge_fee1` (bm1_code), `charge_fee2` (bm2_code)
BM limitation: [`bm1_code`]
=> Wallet credits will only target `charge_fee1`

feat (wallet-limitations): Apply billable metric limitation to ongoing balance

---

clock.rb
spec/clockwork_spec.rb

I considered updating `LAGO_SUBSCRIPTION_ACTIVITY_PROCESSING_INTERVAL_SECONDS` on our infra but I think it makes more sense to change the default.

feat(infra): Process SubscriptionActivity every minute

---

app/models/organization.rb
spec/models/organization_spec.rb

This PR fixes the method `Organization#admins` that is returning all admins, regardless their statuses on Membership class.
```
(ruby) organization.memberships.admin.revoked.map(&:user).map(&:email)
> ["sandy@hills.example", "francesco.simonis@moen.test"]
(ruby) organization.memberships.admin.active.map(&:user).map(&:email)
> ["antoinette.pacocha@barton.example"]
(ruby) organization.admins.pluck(:email)
> ["antoinette.pacocha@barton.example", "sandy@hills.example", "francesco.simonis@moen.test"]
```
```
(ruby) organization.memberships.admin.revoked.map(&:user).map(&:email)
> ["ellis@larkin-denesik.example", "simon.blick@okeefe.test"]
(ruby) organization.memberships.admin.active.map(&:user).map(&:email)
> ["gus.nikolaus@jacobs.test"]
(ruby) organization.admins.pluck(:email)
> …
```

fix(organization#admins): Return the correct set of admins

---

app/controllers/graphql_controller.rb
db/structure.sql
spec/requests/graphql_controller_spec.rb

- Add `MAX_QUERY_LENGTH` on GraphQL queries
- If we hit the max length, it will returns an error with 413 status

chore(sec): Add GraphQL max query length validation

---

spec/support/matchers/job_matcher.rb

The current `have_enqueued_job_after_commit` matcher doesn't allow to expect multiple time the same job.
This PR adds this capability. It was tested using the following spec:
```ruby
require "rails_helper"
describe "Job matcher" do
let(:customer) { create(:customer) }
describe "#twice" do
it "enqueues the job twice" do
expect do
SendWebhookJob.perform_after_commit("customer.created", customer)
SendWebhookJob.perform_after_commit("customer.created", customer)
end.to have_enqueued_job_after_commit(SendWebhookJob).twice
end
end
describe "#thrice" do
it "enqueues the job thrice" do
expect do
SendWebhookJob.perform_after_commit("customer.created", customer)
SendWebhookJob.perform_after_commit("customer.created", customer)
SendWebhookJob.perform_after_commit("customer.created", customer)
end.to …
```

test(matcher): Improve `have_enqueued_job_after_commit` matcher

---

config/routes.rb
spec/requests/api/v1/subscriptions/entitlements_controller_spec.rb

In the code review @groyoh proposed to rename `unremove` controller method by `restore`.
I think it's much nicer to have POST on /restore than a DELETE on /remove. Deleting a removed thing is weird, it's implementation details.
```http
POST /api/v1/subscriptions/:external_id/entitlements/:feature_code/restore
🆚
DELETE /api/v1/subscriptions/:external_id/entitlements/:feature_code/remove
```

feat(entitlement): Change DELETE /remove to POST /restore

---

spec/requests/graphql_controller_spec.rb

Use the `Auth::TokenService` to encode the token.

(fix): Use new TokenService

---

app/models/entitlement/privilege.rb
app/services/entitlement/feature_update_service.rb
db/migrate/20250630180000_create_entitlement_features_and_privileges.rb
db/migrate/20250722094047_change_privilege_config_to_not_null.rb
db/structure.sql
spec/services/entitlement/feature_update_service_spec.rb

Allow `config.select_options` to be updated for `select` privilege.
I don't know why the config column is nullable in the DB, this is a mistake.
Notice that I can simply change the column with "safety_assured" because **the feature is not released and there was no tagged version [since I added this model](https://github.com/getlago/lago-api/pull/3873).**

feat(entitlement): append new select_options + not null db column

---

app/controllers/api/v1/wallets_controller.rb
app/serializers/v1/wallet_serializer.rb
spec/requests/api/v1/wallets_controller_spec.rb
spec/serializers/v1/wallet_serializer_spec.rb

With this feature it will be possible to limit wallet consumption on specific billable metric fees
This PR adds api support for billable metrics that should be targeted by wallet credits

feat(wallet-limitations): add api support for billable metric limitation

---

app/controllers/admin/invoices_controller.rb
app/models/charge.rb
app/views/helpers/charge_display_helper.rb
app/views/helpers/fee_display_helper.rb
app/views/helpers/money_helper.rb
app/views/templates/invoices/v2.slim
app/views/templates/invoices/v3/_true_up_fee.slim
app/views/templates/invoices/v4.slim
app/views/templates/invoices/v4/_charge.slim
app/views/templates/invoices/v4/_charge_percentage.slim
app/views/templates/invoices/v4/_default_fee.slim
app/views/templates/invoices/v4/_default_fee_with_filters.slim
app/views/templates/invoices/v4/_fee_with_filters.slim
app/views/templates/invoices/v4/_fees_without_filters.slim
app/views/templates/invoices/v4/_graduated.slim
app/views/templates/invoices/v4/_graduated_percentage.slim
app/views/templates/invoices/v4/_one_off.slim
app/views/templates/invoices/v4/_package.slim
app/views/templates/invoices/v4/_percentage.slim
app/views/templates/invoices/v4/_subscription_details.slim
app/views/templates/invoices/v4/_true_up_fee.slim
app/views/templates/invoices/v4/_volume.slim
app/views/templates/invoices/v4/charge.slim
spec/views/helpers/charge_display_helper_spec.rb
spec/views/helpers/fee_display_helper_spec.rb

It's refactoring changes needed for adjusting PDF for pricing units extracted into separate PR for ease of testing and reviewing. You can check next step changes in [this PR](https://github.com/getlago/lago-api/pull/3867).
Border and paddings between fees re-worked in order to better adapt to varying amounts of table rows (tr) representing one fee. With pricing units changes there will be one more optional row for conversion from pricing units to fiat currency. So 1 fee could be represented in 1, 3, 5 rows.
Another changes is expanding FeeDisplayHelper with more format method, for now they are just redirecting the all to MoneyHelper but in next step it will have a logic to display either values in fiat currency or in pricing units.
CSS refactoring
Expanding FeeDisplayHelper with more …

feat(pricing-units): Refactor invoice PDF

---

app/controllers/api/v1/features_controller.rb
app/graphql/mutations/entitlement/create_feature.rb
app/graphql/mutations/entitlement/update_feature.rb
app/serializers/v1/entitlement/feature_serializer.rb
app/serializers/v1/entitlement/plan_entitlement_serializer.rb
app/serializers/v1/entitlement/subscription_entitlements_collection_serializer.rb
app/services/entitlement/feature_create_service.rb
app/services/entitlement/feature_update_service.rb
app/services/utils/entitlement.rb
spec/requests/api/v1/features/privileges_controller_spec.rb
spec/requests/api/v1/features_controller_spec.rb
spec/requests/api/v1/plans/entitlements/privileges_controller_spec.rb
spec/requests/api/v1/plans/entitlements_controller_spec.rb
spec/requests/api/v1/subscriptions/entitlements_controller_spec.rb
spec/serializers/v1/entitlement/feature_serializer_spec.rb
spec/serializers/v1/entitlement/plan_entitlement_serializer_spec.rb
spec/serializers/v1/entitlement/subscription_entitlements_collection_serializer_spec.rb
spec/serializers/v1/plan_serializer_spec.rb
spec/services/entitlement/feature_create_service_spec.rb
spec/services/entitlement/feature_update_service_spec.rb
spec/services/webhooks/features/created_service_spec.rb
spec/services/webhooks/features/deleted_service_spec.rb
spec/services/webhooks/features/updated_service_spec.rb

This PR modifies the serializer for features and privileges, as well as the payload to manage features.
The payload to manage entitlements (attaching features to plans *with values* is still a hash.
The first thing that made me want to change this was GQL, which was not so easy to use with hash.
Then, I wrote the open API spec and it was even worse.
```diff
{
feature: {
code: "new_feature",
name: "New Feature",
description: "A new feature",
-          privileges: {
-            "priv1" => {value_type: "boolean"},
-            "priv2" => {name: "Maximum", value_type: "boolean"}
-          }
+          privileges: [
+            {code: "priv1", value_type: "boolean"},
+            {code: "priv2", name: "Maximum", value_type: "boolean"}
+          ]
}
}
```
```rb
{
"entitlements" => { …
```

fix(entitlements): Use Array of privileges instead of hash indexed by code

---

app/controllers/api/v1/subscriptions_controller.rb
app/models/subscription.rb
app/serializers/v1/subscription_serializer.rb
app/services/subscriptions/terminate_service.rb
app/services/subscriptions/update_service.rb
app/services/subscriptions/validate_service.rb
db/migrate/20250721192051_add_on_termination_invoice_to_subscriptions.rb
db/structure.sql
spec/models/subscription_spec.rb
spec/requests/api/v1/subscriptions_controller_spec.rb
spec/serializers/v1/subscription_serializer_spec.rb
spec/services/subscriptions/create_service_spec.rb
spec/services/subscriptions/plan_upgrade_service_spec.rb
spec/services/subscriptions/terminate_service_spec.rb
spec/services/subscriptions/update_service_spec.rb
spec/services/subscriptions/validate_service_spec.rb

When a subscription is terminated,whether due to an error or otherwise,Lago automatically generates a closing invoice for pay-in-arrears fees. This inflexible behavior didn't accommodate different business needs where organizations might want to skip the invoice generation.
This introduces an `on_termination_invoice` enum field to subscriptions that controls whether an invoice is generated for pay-in-arrears fees. The field supports "generate" (default) and "skip" values, allowing organizations to choose their preferred termination behavior.
The termination service now respects this setting and only generates an invoice when explicitly configured to do so. The API accepts the termination behavior as a parameter during subscription termination.
The implementation includes database schema …

feat(subscription): Allow to skip invoice generation on subscription termination

---

app/graphql/mutations/entitlement/update_plan_entitlements.rb
app/graphql/types/entitlement/entitlement_input.rb
app/graphql/types/entitlement/entitlement_privilege_input.rb
app/graphql/types/entitlement/subscription_entitlement_object.rb
app/graphql/types/entitlement/subscription_entitlement_privilege_object.rb
app/graphql/types/subscriptions/object.rb
schema.graphql
schema.json
spec/graphql/mutations/entitlement/update_plan_entitlements_spec.rb
spec/graphql/resolvers/subscription_resolver_spec.rb
spec/graphql/types/entitlement/entitlement_input_spec.rb
spec/graphql/types/entitlement/entitlement_privilege_input_spec.rb
spec/graphql/types/entitlement/subscription_entitlement_object_spec.rb
spec/graphql/types/entitlement/subscription_entitlement_privilege_object_spec.rb

Simplified version of #4024
Entitlements are a new field on subscriptions
```json
[
{
"code": "seats",
"name": "Feature Name",
"description": "Feature Description",
"privileges":
[
{
"code": "max",
"name": null,
"valueType": "string",
"value": "100",
"planValue": "100",
"overrideValue": null
},
{
"code": "max_admins",
"name": null,
"valueType": "string",
"value": "12",
"planValue": "5",
"overrideValue": "12"
}
]
},
{
"code": "api",
"name": "Feature Name",
"description": "Feature Description",
"privileges": []
},
{
"code": "storage",
"name": "Feature Name",
"description": "Feature Description",
"privileges": []
}
]
```

feat(entitlements): Add `entitlements` to Subscription Graphql object

---

app/serializers/v1/entitlement/feature_serializer.rb
spec/requests/api/v1/features/privileges_controller_spec.rb
spec/requests/api/v1/features_controller_spec.rb
spec/serializers/v1/entitlement/feature_serializer_spec.rb

Realized during QA yesterday that config wasn't returned here

fix(entitlements): missing config attribute

---

app/models/fixed_charge.rb
app/models/subscription.rb
app/models/subscription_fixed_charge_units_override.rb
db/migrate/20250717071548_create_subscription_fixed_charge_units_overrides.rb
db/structure.sql
spec/factories/subscription_fixed_charge_units_overrides.rb
spec/models/fixed_charge_spec.rb
spec/models/subscription_fixed_charge_units_override_spec.rb
spec/models/subscription_spec.rb

For fixed charges on subscription level we can override number of units, but this should not create a plan override, so we need a new model that would only keep the overridden units
- added migration and model of subscrition_fixed_charges_units_override

Feat(Fixed_charges): add subscription_fixed_charge_units_override

---

app/services/invoices/calculate_fees_service.rb

The goal is to be able to not prevent the creation of a subscription fee when a voided invoice has the same values.

Do not check voided invoice for subscription fee creation

---

app/jobs/send_webhook_job.rb
app/serializers/v1/dunning_campaign_finished_serializer.rb
app/services/dunning_campaigns/bulk_process_service.rb
app/services/webhooks/dunning_campaigns/finished_service.rb
spec/jobs/send_webhook_job_spec.rb
spec/serializers/v1/dunning_campaign_finished_serializer_spec.rb
spec/services/dunning_campaigns/bulk_process_service_spec.rb
spec/services/webhooks/dunning_campaigns/finished_service_spec.rb

Request from users:
> We need webhook message when a dunning campaign ends and isn't paid so we can auto-block users who don't pay at the end of their dunning campaign. 
> 
> If possible - it would be great to include the customer's overdue balance in the message
This PR adds `dunning_campaign.finished` webhook to match described use-case

fix(dunning-campaign): send webhook when dunning campaign ends and is not paid

---

app/services/charge_models/amount_details/range_graduated_percentage_service.rb
app/services/charge_models/amount_details/range_graduated_service.rb
app/services/charge_models/graduated_percentage_service.rb
app/services/charge_models/graduated_service.rb
spec/services/charge_models/amount_details/range_graduated_percentage_service_spec.rb
spec/services/charge_models/amount_details/range_graduated_service_spec.rb

👉 https://getlago.canny.io/feature-requests/p/define-quantities-for-plan-charges
What is the current situation?
**Option 1:** User has to create a one off invoice alongside the subscription, it will create 2 different invoices.
**Option 2:** User can add a recurring billable metric and use event to have this fee invoice on subscription renewal, but it won’t appear on the first billing subscription.
What problem are we trying to solve?
At subscription creation or afterward, there is no clear way to invoice a fixed fee that is not tied to events, aside from the subscription fee itself. This fee could be either a one-time charge or a recurring one.
- Move `AmountDetails` services from `Charges` …

Feat(fixed_charges): Move `AmountDetails` to `ChargeModels` namespace

---

app/models/invoice.rb
spec/factories/invoices.rb
spec/models/invoice_spec.rb
spec/requests/api/v1/invoices_controller_spec.rb
spec/services/invoices/lose_dispute_service_spec.rb
spec/services/payments/lose_dispute_service_spec.rb

Voided invoice should be disputable as well.
Change `Invoice#payment_dispute_losable?` method to return true even if invoice is voided.

fix(invoice): Voided invoice is disputable as well

---

app/services/plans/chargeables_validation_service.rb
app/services/plans/create_service.rb
spec/services/plans/chargeables_validation_service_spec.rb
spec/services/plans/create_service_spec.rb

👉 https://getlago.canny.io/feature-requests/p/define-quantities-for-plan-charges
What is the current situation?
**Option 1:** User has to create a one off invoice alongside the
subscription, it will create 2 different invoices.
**Option 2:** User can add a recurring billable metric and use event to
have this fee invoice on subscription renewal, but it won’t appear on
the first billing subscription.
What problem are we trying to solve?
At subscription creation or afterward, there is no clear way to invoice
a fixed fee that is not tied to events, aside from the subscription fee
itself. This fee could be either a one-time charge or a recurring one.
Add `Plans::ChargeablesValidationService` to …

Feat(fixed_charges): Extract chargeable validation service 

---

app/models/billing_period_boundaries.rb
app/models/invoice_subscription.rb
app/models/subscription.rb
app/services/charges/pay_in_advance_aggregation_service.rb
app/services/fees/charge_service.rb
app/services/fees/create_pay_in_advance_service.rb
app/services/fees/create_true_up_service.rb
app/services/fees/subscription_service.rb
app/services/invoices/calculate_fees_service.rb
app/services/invoices/create_invoice_subscription_service.rb
app/services/invoices/customer_usage_service.rb
app/services/invoices/preview_service.rb
app/services/invoices/progressive_billing_service.rb
app/services/subscriptions/terminate_service.rb
spec/models/billing_period_boundaries_spec.rb
spec/models/subscription_spec.rb
spec/services/charges/pay_in_advance_aggregation_service_spec.rb
spec/services/fees/charge_service_spec.rb
spec/services/fees/create_pay_in_advance_service_spec.rb
spec/services/fees/subscription_service_spec.rb
spec/services/invoices/create_pay_in_advance_charge_service_spec.rb

In many places of the application, we are defining a `boundaries` object, sometimes as an instance of a `Hash`, sometimes as an `OpenStruct`. The fields are not always the same and since the boundaries are injected in a lot of services, this causes some uncertainty when accessing the properties.
In an attempt to improve the readability and the reliability of this key part of the application, the goal of this PR is to introduce a new `BillingPeriodBoundaries` class and to use it everywhere in replacement of `Hash` and `OpenStruct`.
It should also improve the memory consumption as OpenStructs are known to cause memory issues in Ruby when YJIT is enabled

misc: Add BillingPerdiodBoundaries

---

app/services/events/stores/clickhouse/weighted_sum_query.rb

Error: Different expressions with the same alias difference:\ntoDecimal128(25., 26) AS difference\nand\ntoDecimal128(15., 26) AS difference\n: While processing toDecimal128(25., 26) AS difference.

fix(weighted-sum): Clickhouse query

---

app/services/fixed_charges/update_service.rb
spec/services/fixed_charges/update_service_spec.rb

We need a service to update fixed charge and cascade-update. When updating a fixed charge, we can't change `pay_in_advance` and `prorated`
`display_name` can only be changed in parent fixed_charge (not updated while cascade)
`charge_model` can only be updated if plan is not attached to any subscription
`properties` can be updated while cascading only if before update current fixed_charge and the child had matching properties
`taxes` can be changed only for parent fixed_charge without attached subscription
- added `FixedCharges::UpdateService`

Feat(fixed charges 6): update services

---

.cursor/rules/rails-general.mdc
app/models/subscription.rb
app/services/credit_notes/create_from_termination.rb
app/services/subscriptions/terminate_service.rb
db/migrate/20250712000000_add_refund_to_subscription_on_termination_credit_note.rb
db/structure.sql
schema.graphql
schema.json
spec/graphql/types/subscriptions/on_termination_credit_note_enum_spec.rb
spec/models/subscription_spec.rb
spec/requests/api/v1/subscriptions_controller_spec.rb
spec/services/credit_notes/create_from_termination_spec.rb
spec/services/subscriptions/terminate_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/flexible-credit-note-management
When subscriptions are terminated before their billing period ends, the system previously allowed to create credit notes for unused time on pay-in-advance plans. It was also possible to skip the creation of credit note. In cases where the customer already paid, it was not possible to issue a refund as part of the credit note.
This adds support for refunding customers via the `on_termination_credit_note` when terminating pay-in-advance subscriptions early.
This implementation extends the subscription termination process with a new `refund` option alongside the existing `credit` and `omit` behaviors. When a pay-in-advance subscription is terminated early, the system now calculates the unused subscription amount …

feat(subscriptions): Add refund option for subscription termination

---

db/migrate/20250812082721_update_flat_filters_to_version_3.rb
db/structure.sql
db/views/flat_filters_v03.sql

This PR is part of the Pre-aggregation epic.
The main goal of this feature is to setup a complete aggregation pipeline that will be leveraged to compute the customer usage without re-querying the full set of events.
This pull request is exposing the `pay_in_advance` field in the flat_filters view, to allow the events_processor use them when enriching the events.

feat(pre-aggregation): Expose charge pay_in_advance in flat filters

---

app/graphql/resolvers/invoices_resolver.rb
app/queries/invoices_query.rb
schema.graphql
schema.json
spec/graphql/resolvers/invoices_resolver_spec.rb
spec/queries/invoices_query_spec.rb

Currently, it is not possible for the front to retrieve a list of invoices related to a subscription.
This adds a new filter on the `invoices` GraphQL query.

feat(invoice): Allow to filter invoices by `subscription_id` via GraphQL

---

app/services/integrations/aggregator/taxes/invoices/payloads/anrok.rb
spec/services/integrations/aggregator/taxes/invoices/payloads/anrok_spec.rb

Anrok will return a `taxDateTooFarInFuture` error if the issuing date is more than 30 days in the future, which can happen with Quarterly and Yearly subscription.

fix(anrok): issuing_date should be 30 days in the future at most

---

app/graphql/resolvers/events_resolver.rb
spec/graphql/resolvers/events_resolver_spec.rb

Idem-potency logic is different between Postgres and Clickhouse. This creates some confusion on the customer side.
The main problem is that to render the list of event in the front-end, when an organization is configured to use Clickhouse we relies on `EventRaw` which does not do any deduplication. It means that if a customer send two events with the same transaction_id, external_subsciption_id, code and timestamp, all events will appears in the event view, while only one will be considered when doing the aggregation (which relies on `EventEnriched` and that already has a deduplication logic)
This PR makes sure that the events rendered in the GraphQL API are not showing duplicated events, by applying the same deduplication rule than the `EventEnriched` table

fix(events): Deduplicate clickhouse events in the Graphql resolver

---

app/models/charge.rb
spec/services/plans/create_service_spec.rb

Some error were raised by the API:
```
'custom_properties' is not a valid charge_model (ArgumentError)
raise ArgumentError, "'#{value}' is not a valid #{name}"
```
This happen in the `Plans::CreateService` when the provided `charge_model` of a charge is invalid. It renders an HTTP 500 to the end-user when it should return a 422 with a clear message of what is happening.
This PR adds the `validate: true` on the `Charge#charge_model` enum to make sure it returns a validation error instead of raising when an invalid value is provided

fix(charge): Handle invalid charge model values

---

config/initializers/half_year.rb
lib/date_and_time/half_year_calculations.rb
spec/lib/date_and_time/half_year_calculations_spec.rb

A prerequisite to semiannual plans: We need to calculate start and end of half-year for some further calculations.
Prepend `DateAndTime::HalfYearCalculations` to `DateAndTime::Calculations`

feat(semiannual): Prepend DateAndTime::HalfYearCalculations to DateAndTime::Calculations

---

app/services/wallet_transactions/create_from_params_service.rb
app/services/wallet_transactions/create_service.rb
app/services/wallet_transactions/void_service.rb
spec/services/wallet_transactions/create_service_spec.rb

Small preparation step for wallet calculation feature.
Currently this service accept each attribute as separate keyword argument creating a very long list of attributes in the `.initialize`, also we're duplicating default values set in the database.
Receive almost all params in `**transaction_params` simplifying `.initialize`.
Rely on DB defaults for non-provided attributes instead of duplicating the default values.
Rewrite specs to actually cover default DB values being assigned when not provided.

misc(wallet-transaction): Refactor create service

---

app/services/payment_requests/payments/stripe_service.rb
spec/services/payment_requests/payments/stripe_service_spec.rb

add a line item for each overdue invoice included in the payment request.
also, when payment request include one single invoice, include its number in the description...

misc(dunning): Include invoice numbers in stripe payments

---

app/graphql/types/timezone_enum.rb
app/support/timezones.rb
app/validators/timezone_validator.rb
db/migrate/20250821094638_update_timezones.rb
db/structure.sql
schema.graphql
schema.json

Following the update of Ruby to version 3.4.5, some issues where spotted in the timezone especially when exporting the Timezone enum for the GraphQL API.
It appears that some zone were renamed in ruby but that the support for rails has not yet been changed accordingly.
This PR:
- Fixes the Timezone mapping by adding a new `Timezones` module that will be used for both validations and GraphQL export.
- Add the correct handling for the impacted timezones:
- Asia/Rangoon => Asia/Yangon
- Europe/Kiev => Europe/Kyiv
- America/Godthab => America/Nuuk
- Migrates the customers, organizations, invoices and billing entities impacted by these changes

fix(timezones): Fix timezone names

---

app/services/dunning_campaigns/bulk_process_service.rb

`dunning_campaign.finished` webhook should be trigger whenever dunning campaign is done for certain customer, not just when overdue balance is greater than zero

fix: update trigger for dunning_campaign finished webhook

---

app/graphql/resolvers/events_resolver.rb
spec/graphql/resolvers/events_resolver_spec.rb

This PR is a fix for the following rails exception:
```
ActiveRecord::ActiveRecordError
Response code: 500: (ActiveRecord::ActiveRecordError)
["Code: 215. DB::Exception: Column `transaction_id` is not under aggregate function and not in GROUP BY. Have columns: ['count()']: While processing transaction_id, timestamp, external_subscription_id, code. (NOT_AN_AGGREGATE)"]
```
It's a regression introduced by a previous pull-request (https://github.com/getlago/lago-api/pull/4163) that was made to de-duplicates Clickhouse events in the GraphQL events resolver. The issue is happening when querying an empty event page.

fix(events): Fix resolver with Clickhouse

---

app/services/subscriptions/validate_service.rb
spec/services/subscriptions/validate_service_spec.rb

This PR fixes the following error:
```
Date::Error
invalid date (Date::Error) DateTime.strptime(args[:ending_at], "%Y-%m-%dT%H:%M:%S.%LZ""
```
It raising when trying to update a subscription with an `ending_at` value using an invalid date format

fix(subscription): Handle invalid ending at time format

---

app/serializers/v1/fixed_charge_serializer.rb
app/serializers/v1/plan_serializer.rb
spec/factories/fixed_charges.rb
spec/requests/api/v1/plans_controller_spec.rb
spec/serializers/v1/fixed_charge_serializer_spec.rb
spec/services/plans/update_service_spec.rb

After we added managing fixed_charges on plan level, we should also be able to receive updated fixed_charges information.
Goal of this PR is to add fixed_charge serializer and include fixed_charges in plans_serializer

Feat(fixed_charges-8): add fixed_charge_serializer

---

app/graphql/resolvers/api_log_resolver.rb
app/graphql/resolvers/api_logs_resolver.rb
spec/graphql/resolvers/api_log_resolver_spec.rb
spec/graphql/resolvers/api_logs_resolver_spec.rb

Whenever we don't have API logs available, we should not logout the user, we should return that the action is forbidden, which does not logout the user.

fix(api_logs): Do not logout the user when api logs is not available

---

app/models/entitlement/subscription_entitlement.rb
app/models/entitlement/subscription_entitlement_privilege.rb
app/models/entitlement/subscription_feature_removal.rb
app/queries/entitlement/subscription_entitlement_query.rb
db/migrate/20250822100111_add_privilege_removal.rb
db/structure.sql
spec/factories/entitlement/subscription_feature_removals.rb
spec/models/entitlement/subscription_entitlement_privilege_spec.rb
spec/models/entitlement/subscription_entitlement_spec.rb
spec/models/entitlement/subscription_feature_removal_spec.rb
spec/queries/entitlement/subscription_entitlement_query_spec.rb
spec/requests/api/v1/subscriptions/entitlements_controller_spec.rb

- Add new db column so `Entitlement::SubscriptionFeatureRemoval` can belong to a privilege.
- modify the query so we ignore privileges listed in the subscription feature removals.
- Add beautiful hand-crafted test suite to the SubscriptionEntitlementQuery object.
- Add `to_h` to active model to make them much easier to work with
Next PR, will create the removals in services when needed

feat(entitlement): Allow privilege from plan to be removed from subscription

---

app/controllers/api/v1/plans_controller.rb
app/serializers/v1/fixed_charge_serializer.rb
app/serializers/v1/plan_serializer.rb
spec/factories/fixed_charges.rb
spec/requests/api/v1/plans_controller_spec.rb
spec/serializers/v1/fixed_charge_serializer_spec.rb
spec/serializers/v1/plan_serializer_spec.rb
spec/services/plans/update_service_spec.rb

With this PR we're allowing users to send us fixed_charges params when creating and updating plan, so we'll also create, update, delete fixed charges for the plan
- updated plans controller to receive fixed_charges specific params and pass them to plans services

feat(fixed_charges-8): process fixed_charges from plans controller

---

app/graphql/mutations/plans/update.rb
app/graphql/types/fixed_charges/input.rb
app/graphql/types/fixed_charges/object.rb
app/graphql/types/plans/object.rb
app/graphql/types/plans/update_input.rb
schema.graphql
schema.json
spec/graphql/mutations/plans/update_spec.rb
spec/graphql/types/fixed_charges/input_spec.rb
spec/graphql/types/fixed_charges/object_spec.rb
spec/graphql/types/plans/update_input_spec.rb

👉 https://getlago.canny.io/feature-requests/p/define-quantities-for-plan-charges
What is the current situation?
**Option 1:** User has to create a one off invoice alongside the
subscription, it will create 2 different invoices.
**Option 2:** User can add a recurring billable metric and use event to
have this fee invoice on subscription renewal, but it won’t appear on      the first billing subscription.
What problem are we trying to solve?
At subscription creation or afterward, there is no clear way to invoice
a fixed fee that is not tied to events, aside from the subscription fee
itself. This fee could be either a one-time charge or a recurring one.
Update graphQL type Plans::UpdateInput...
- …

Feat(fixed_charges): update graphql for updating plan fixed charges

---

app/services/payment_providers/stripe/webhooks/base_service.rb
spec/services/payment_providers/stripe/webhooks/customer_updated_service_spec.rb
spec/services/payment_providers/stripe/webhooks/setup_intent_succeeded_service_spec.rb

When a customer is updated on Stripe, we receive a `customer.updated` webhook from Stripe. If we cannot match the payload with a `PaymentProviderCustomers::StripeCustomer`, we do the following:
- If the payload does not include the `metadata.lago_customer_id` value, it means the customer was created outside Lago and we can ignore the webhook.
- If the payload include the `metadata.lago_customer_id` but we cannot find it in the database, it means the customer was deleted or belong to another organization and we can ignore the webhook.
- Otherwise, we'll return a `stripe_customer_not_found` error.
There is an edge-case that wasn't handled here though. If someone manually updated the Stripe customer information when updating a Lago customer, the previous Stripe customer will no longer be …

fix(stripe): Fix `customer.updated` Stripe webhook when stripe customer not found in DB

---

app/graphql/types/entitlement/plan_entitlement_privilege_object.rb

With ActiveRecord if you do `EntitlementValue.update value: true`, it will convert the value to `"t"` because the db column is string.
This is intentional and the serializer will use `ActiveModel::Type::Boolean.new.cast("t")` to convert it to `true.
In GQL, we rely on `"true"` and `"false"` string to display the select box. So we need to convert on read.
On write it's fine because the value will always be casted when returned via the API.

fix(entitlements): Convert boolean string for frontend

---

Gemfile.lock
config/initializers/countries.rb
schema.graphql
schema.json

Lago relies on the https://github.com/countries/countries gem to get the list of available country. It is using the list of ISO 3166 country codes.
Some customers recently ask for the inclusion of the Kosovo in the list of countries. The issue is that for now, no ISO 3166 country code is assigne to the Kosovo. 
An issue is opened on the countries repository about it: https://github.com/countries/countries/issues/793
I appears that it will not be fixed until the Kosovo officially received an ISO 3166 country code.
To address the request from customers, this PR is using the proposed workaround from the source repository issue.
The PR also updates the `countries` gem

misc: Add kosovo country code

---

app/models/credit_note.rb
app/services/credit_notes/create_service.rb
spec/services/credit_notes/create_service_spec.rb

The `CreditNote::Create` service was catching all `ArgumentError` exceptions and converting them to `reason` validation errors, which could mask legitimate errors from other parts of the code. This made debugging difficult and could hide real bugs.
This fixes the issue by adding an explicit validation.

fix(credit-notes): Prevent `ArgumentError` masking with proper `reason` validation

---

app/services/credits/progressive_billing_service.rb
spec/services/credits/progressive_billing_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb
spec/services/invoices/progressive_billing_service_spec.rb

Progressive billing credits were being distributed across all invoice fees, regardless of whether a fee belonged to the same charge as the progressive billing invoice. 
This PR updates Credits::ProgressiveBillingService so that credits from a progressive billing invoice are only applied to matching fees on the target invoice (same charge_id/context), instead of being spread across all fees.
This change was needed so that when we apply the credits from the wallet, we need to know the remaining fee, removing the progressive billing part 
This issue would be more evident if we had multiple wallets, and some of them only applied to specific fees, the amount we need to take would not be correct (because the calculations would be affected by the progressive billing )

feat: change the calculations

---

app/services/integrations/aggregator/accounts_service.rb
spec/graphql/mutations/integration_items/fetch_accounts_spec.rb
spec/services/integrations/aggregator/accounts_service_spec.rb

Xero integration started raising an error when fetching accounts, there must have been a change in the API endpoint.
Don't send empty `cursor` parameter in `Integrations::Aggregator::AccountsService`

fix(integrations): Fix aggregator accounts service

---

app/controllers/api/v1/billing_entities_controller.rb

Billing_entities_controller was missing resource name, so when checking api keys permissions,  we were not able to get the resource_name
- added resource_name method to billing_entities_controller

Fix(billing_entity): api key doesn't work for billing entities endpoint

---

app/queries/invoices_query.rb
spec/queries/invoices_query_spec.rb

Sending `amount_from` or `amount_to` as decimal on the `GET /api/v1/invoices` would result in a 500 error due to Postgres cast failure:
```sql
invalid input syntax for type bigint: "0.5"
```
This fixes it by casting the input as `numeric` in the query.

fix(invoice): Fix `InvoicesQuery` when passing `amount_*` as decimal

---

app/services/fees/create_pay_in_advance_service.rb
spec/services/fees/create_pay_in_advance_service_spec.rb

The pay-in-advance charge invoicing process was failing when Anrok tax integration was enabled. For pay-in-advance charge invoicing, the `Fees::CreatePayInAdvanceService` is called with `estimate: true`. This will not persist the fees and the fees won't have an `id`. When sending those fees to Anrok, we'll default to the fee `item_id`, which is the billable metric ID:
https://github.com/getlago/lago-api/blob/d476c33e3abb41bc88701cd13d562d20111e10a7/app/services/integrations/aggregator/taxes/invoices/payloads/anrok.rb#L52
But when we try to look up the tax result for a specific fee, we were relying on the fee `id` which is `nil`:
https://github.com/getlago/lago-api/blob/e142bf11cf449cde27d379dbad9115d54bdc70a7/app/services/fees/create_pay_in_advance_service.rb#L200
This change corrects the …

fix(invoice): Fix pay-in-advance charge invoicing when Anrok is enabled

---

app/models/invoice.rb
app/services/charges/pay_in_advance_aggregation_service.rb
app/services/events/stores/base_store.rb
app/services/fees/charge_service.rb
app/services/fees/projection_service.rb
spec/services/charges/pay_in_advance_aggregation_service_spec.rb
spec/services/fees/projection_service_spec.rb

This PR is part of the Pre-aggregation epic.
The main goal of this feature is to setup a complete aggregation pipeline that will be leveraged to compute the customer usage without re-querying the full set of events.
This pull request pass the `charge_id` and `charge_filter_id` to the event stores. They will be used later to filter events and pre-aggregated events

feat(pre-aggregation): Pass charge_id and charge_filter_id to the event stores

---

scripts/migrate.dev.sh
scripts/start.dev.sh

It seems that https://github.com/getlago/lago/commit/3a94e3d86b2823e9c76a0f0bc3d08ad6fc338aeb introduced an issue with the seed.
Before that commit, `api` container would not depend on `migrate` and would run `rake db:prepare` which would create the database, run migrations AND seed the database.
Since `migrate` now runs before `api`, we will run `db:migrate` which will create the database and run migrations. Then, when `api` will start, the `rake db:prepare` will see that the database is already created and will only run migrations.
This ensures we run `bundle exec rails db:prepare` in `migrate` container.

fix(seeds): Fix automatic seeding in dev environment

---

spec/graphql/resolvers/customer_portal/customers/projected_usage_resolver_spec.rb

Since our primary keys are uuid v4, they are not ordered so we should avoid using `first` or `last` when inspecting API response.

chore(tests): Fix flacky tests in customerportals

---

app/services/credit_notes/validate_service.rb
spec/graphql/mutations/credit_notes/create_spec.rb
spec/requests/api/v1/credit_notes_controller_spec.rb
spec/services/credit_notes/create_service_spec.rb
spec/services/credit_notes/validate_service_spec.rb
spec/support/graphql_helper.rb

This PR addresses an issue which allows users to generate credit notes with a total amount of 0 cents. This behavior is incorrect and should be prevented.
This change introduces a new validation to prevent the creation of credit notes with a total amount of 0.

fix(credit-note): Prevent 0 cent credit note issuance

---

app/graphql/resolvers/events_resolver.rb
spec/graphql/resolvers/events_resolver_spec.rb

This PR rollbacks the change that was introduced by https://github.com/getlago/lago-api/pull/4163 as it is causes issues in prodution

fix(clickhouse): Rollback deduplications for events resolver

---

Gemfile
Gemfile.lock
spec/views/app/views/templates/invoices/__snapshots__/invoices_v4__credit.slim/when_invoice_type_is_credit/when_wallet_has_a_name/renders_correctly.html.snap
spec/views/app/views/templates/invoices/__snapshots__/invoices_v4__credit.slim/when_invoice_type_is_credit/when_wallet_has_no_name/renders_correctly.html.snap
spec/views/app/views/templates/invoices/v4.slim_spec.rb

I am currently working on a task that modifies the behavior of the invoice rendering for `credit` invoices. I noticed there were no spec for the rendering of those invoices. So I decided to add some tests and ended up extracting the logic into this PR.
In order to test the invoice rendering, I relied on the same code used by the `Utils::PdfGenerator`: `Slim::Template.new(template).render(invoice)`. The test is also using `build_stubbed` factory with constant data to have fast and consistent test setup. 
In order to make assertions on the view, I used the [`rspec-snapshots`](https://github.com/levinmr/rspec-snapshot) which serialize the HTML content into a snapshot on the first run and compares with the snapshot on the next runs. This allows us to easily diff the HTML changes and ensure …

test(invoice): Introduce invoice rendering tests

---

app/serializers/v1/wallet_transaction_serializer.rb
app/services/webhooks/wallet_transactions/created_service.rb
app/services/webhooks/wallet_transactions/updated_service.rb
spec/serializers/v1/wallet_transaction_serializer_spec.rb
spec/services/webhooks/wallet_transactions/created_service_spec.rb
spec/services/webhooks/wallet_transactions/updated_service_spec.rb

`wallet_transaction.created` and `wallet_transaction.updated` webhooks did not contain wallet object only the wallet id.
That required an extra request to be made to fetch the wallet.
This PR adds the whole `wallet` object to `wallet_transaction.created` and `wallet_transaction.updated` webhooks.

feat(wallet-transactions): Add wallet to wallet transaction webhooks

---

app/services/events/stores/aggregated_clickhouse_store.rb
app/services/events/stores/base_store.rb
spec/services/events/stores/aggregated_clickhouse_store_spec.rb

This PR is part of the Pre-aggregation epic, it follows https://github.com/getlago/lago-api/pull/4236.
The main goal of this feature is to setup a complete aggregation pipeline that will be leveraged to compute the customer usage without re-querying the full set of events.
This PR implements:
- the base "events" method, relying on the Clickhouse events_enriched_expanded allowing use to filter events using `charge_id`, `charge_filter_id` and `grouped_by`
- the `events_values` and `prorated_events_values` logic
- a new `distinct_charge_filter_ids` that will later allow a pre-filtering the aggregation queries to speedup the computation

feat(pre-aggregation): Implement events_values

---

app/services/wallet_transactions/create_from_params_service.rb
spec/graphql/mutations/wallet_transactions/create_spec.rb

Granted credit never triggers payment not generates invoices. So their `invoice_requires_successful_payment` attribute should always be set to `false`.
This ensures that it is the case.

fix(wallet-transaction): Set `invoice_requires_successful_payment` to `false` for granted credits

---

app/services/events/stores/aggregated_clickhouse_store.rb
app/services/events/stores/base_store.rb
spec/services/events/stores/aggregated_clickhouse_store_spec.rb

This PR is part of the Pre-aggregation epic, it follows https://github.com/getlago/lago-api/pull/4236.
The main goal of this feature is to setup a complete aggregation pipeline that will be leveraged to compute the customer usage without re-querying the full set of events.
This PR implements:
- The base "events_sql" method, relying on the Clickhouse events_enriched_expanded, used to build queries that cannot use the `events_aggregated` table.
- The `prorated_sum`
- The `grouped_prorated_sum`
- The `sum_date_breakdown`

feat(pre-aggregation): Implement prorated_sum

---

app/controllers/api/v1/wallet_transactions_controller.rb
app/models/wallet_transaction.rb
app/serializers/v1/wallet_transaction_serializer.rb
app/services/wallet_transactions/create_from_params_service.rb
app/services/wallet_transactions/create_service.rb
app/services/wallet_transactions/validate_service.rb
app/services/wallet_transactions/void_service.rb
db/migrate/20250903165724_add_name_to_wallet_transactions.rb
db/structure.sql
spec/factories/wallet_transactions.rb
spec/models/wallet_transaction_spec.rb
spec/requests/api/v1/wallet_transactions_controller_spec.rb
spec/serializers/v1/wallet_transaction_serializer_spec.rb
spec/services/wallet_transactions/create_from_params_service_spec.rb
spec/services/wallet_transactions/create_service_spec.rb
spec/services/wallet_transactions/validate_service_spec.rb
spec/services/wallet_transactions/void_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
When creating a wallet transaction, the name displayed on the invoice defaults to the wallet name. However, for organizations managing multiple types of top-ups, it would be beneficial to display specific naming on invoices that corresponds to the particular transaction being made.
This change adds a `name` attribute to the wallet transaction models, params and serializers.

feat(wallet-transaction): Add a `name` to wallet transactions

---

app/graphql/mutations/wallet_transactions/create.rb
app/graphql/types/fees/object.rb
app/graphql/types/wallet_transactions/object.rb
schema.graphql
schema.json
spec/factories/fees.rb
spec/graphql/mutations/wallet_transactions/create_spec.rb
spec/graphql/resolvers/invoice_resolver_spec.rb
spec/graphql/types/fees/object_spec.rb
spec/graphql/types/wallet_transactions/object_spec.rb
spec/spec_helper.rb

👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
Follow up of https://github.com/getlago/lago-api/pull/4256.
This change introduces a `name` field to wallet transactions in the GraphQL API. The implementation adds a new name argument to the wallet transaction creation mutation, allowing clients to specify a custom name when creating transactions. The `WalletTransaction` GraphQL object type now exposes this field.
Additionally, the GraphQL `Fee` and `WalletTransaction` objects respectively gain a `walletTransaction` and `walletName` fields in order for the frontend to easily compute the label to display on invoices based on the following rules:
> - If `walletTransaction.name` is defined
>     
>     ```handlebars
> …
```

feat(wallet-transaction): Add `name` field to wallet transactions in GraphQL

---

app/models/credit_note.rb
app/models/error_detail.rb
app/models/organization.rb
app/services/billing_entities/update_service.rb
app/services/credit_notes/refunds/adyen_service.rb
app/services/credit_notes/refunds/gocardless_service.rb
app/services/credit_notes/refunds/stripe_service.rb
app/services/credit_notes/update_service.rb
app/services/error_details/create_service.rb
app/services/organizations/update_service.rb
spec/services/error_details/create_service_spec.rb
spec/services/organizations/update_service_spec.rb

When handling some enum error, we sometimes returned the wrong format (string instead of array of string).
Ideally, we should use `validate: true` for ALL enum.

chore(errors): Fix non-standard errors because of `enum validate: false`

---

app/graphql/types/coupons/object.rb
app/serializers/v1/coupon_serializer.rb
spec/graphql/types/coupons/object_spec.rb
spec/serializers/v1/coupon_serializer_spec.rb

We should not display coupons that are applicable to child plans, only parent plans. 
UI only allow attach coupons to parent plans. 
API allows attach a coupon using the code, which can attach to child plans as well. 
This coupon can be applied to 3 plans, but 2 are child plans of `testando_taxes`. 
```
lago-api(dev)> Coupon.last.plans.count
=> 3
```
```
{lago_id: "f861c0e9-5001-4efd-949f-ad63ba8a4a22",
name: "Startup Deal",
code: "startup_deal",
description: "I am a coupon description",
coupon_type: "fixed_amount",
amount_cents: 5000,
amount_currency: "USD",
percentage_rate: 0.4e1,
frequency: "recurring",
frequency_duration: 6,
reusable: false,
limited_plans: true,
limited_billable_metrics: false,
plan_codes: ["testando_taxes"],
billable_metric_codes: [],
created_at: …
```

fix(coupons): Do not display child plans on UI and JSON api

---

app/services/credits/applied_prepaid_credit_service.rb
spec/services/credits/applied_prepaid_credit_service_spec.rb
spec/services/invoices/calculate_fees_service_spec.rb

We use this to calculate the amount if prepaid credits in an Invoice. 
Sometime the rounding numbers are ceiling and reduce more than the total invoice costs; producing a negative`total_amounts_cents` and failing the validation, preventing it from finalize.

fix(prepaid_credits): Use precise amounts

---

app/controllers/api/v1/wallet_transactions_controller.rb
app/graphql/mutations/wallet_transactions/create.rb
app/graphql/types/wallet_transactions/create_input.rb
app/services/validators/wallet_transaction_amount_limits_validator.rb
app/services/wallet_transactions/create_from_params_service.rb
app/services/wallets/create_service.rb
schema.graphql
schema.json
spec/graphql/mutations/customer_portal/wallet_transactions/create_spec.rb
spec/graphql/mutations/wallet_transactions/create_spec.rb
spec/graphql/types/wallet_transactions/create_input_spec.rb
spec/requests/api/v1/wallet_transactions_controller_spec.rb
spec/services/validators/wallet_transaction_amount_limits_validator_spec.rb
spec/services/wallet_transactions/create_from_params_service_spec.rb

New wallet transaction are validated against the wallet min/max limits

feat(wallets): Validate top up min/max limit for new transactions

---

app/models/recurring_transaction_rule.rb
app/models/wallet_transaction.rb

`RecurringTransactionRule` and `WalletTransaction` got updated with wrong table annotations.
This fixes the annotations.

chore(annotation): Fix model annotation

---

spec/services/billable_metric_filters/create_or_update_batch_service_spec.rb

This PR follows https://github.com/getlago/lago-api/pull/4328 and adds the missing specs

misc: Add missing specs for discarded billable metric filters

---

app/models/plan.rb
spec/models/plan_spec.rb
spec/requests/api/v1/plans_controller_spec.rb
spec/services/plans/create_service_spec.rb

This PR adds a new validation on the `interval` enum of the `Plan` model
The goal is to avoid an `ArgumentError` when an invalid value is provided via the API as it results in an `HTTP 500` instead of a `422`

fix(plan): Add validation on interval enum

---

app/services/wallets/create_service.rb
app/services/wallets/recurring_transaction_rules/create_service.rb
spec/services/wallets/create_service_spec.rb
spec/services/wallets/recurring_transaction_rules/create_service_spec.rb

Make sure that recurring rules `paid_credits` are aligned with limitations on min/max set on wallet in case of `fixed` rule.
`target` rules does not need this validation as it's amounts calculated dynamically depending on `ongoing` and `target` balance.

feat(recurring-transaction-rules): Apply wallet's min and max limits on create

---

app/models/billing_period_boundaries.rb
spec/factories/fees.rb
spec/models/billing_period_boundaries_spec.rb
spec/scenarios/invoices/advance_charges_dates_spec.rb

Include into `BillingPeriodBoundaries`:
- `fixed_charges_from_datetime`
- `fixed_charges_to_datetime`
- `fixed_charges_duration`

feat(fixed_charges): Add fixed charges boundaries to billing period

---

app/services/subscriptions/dates/monthly_service.rb
app/services/subscriptions/dates/quarterly_service.rb
app/services/subscriptions/dates/weekly_service.rb
app/services/subscriptions/dates/yearly_service.rb
app/services/subscriptions/dates_service.rb
spec/services/subscriptions/dates/monthly_service_spec.rb
spec/services/subscriptions/dates/quarterly_service_spec.rb
spec/services/subscriptions/dates/weekly_service_spec.rb
spec/services/subscriptions/dates/yearly_service_spec.rb
spec/services/subscriptions/dates_service_spec.rb

👉 https://getlago.canny.io/feature-requests/p/define-quantities-for-plan-charges
**Option 1:** User has to create a one off invoice alongside the
subscription, it will create 2 different invoices.
**Option 2:** User can add a recurring billable metric and use event to  have this fee invoice on subscription renewal, but it won’t appear on  the first billing subscription.
At subscription creation or afterward, there is no clear way to invoice  a fixed fee that is not tied to events, aside from the subscription fee  itself. This fee could be either a one-time charge or a recurring one.
Define fixed charge from/to datetime, and duration in days in subscriptions date service.
Fixed Charge …

feat(fixed_charges): Compute date boundaries for Fixed Charges

---

app/models/analytics/mrr.rb
app/models/invoice_subscription.rb
app/models/plan.rb
app/models/recurring_transaction_rule.rb
schema.graphql
schema.json
spec/models/invoice_subscription_spec.rb
spec/models/plan_spec.rb
spec/models/recurring_transaction_rule_spec.rb

When creating a plan, a new interval option should be available: `semiannual`.
In order to enable that, we’ll need to add it to the model, services and GQL.
This PR adds the new interval `semiannual` to all the models and it also updates the GraphQL schema.

feat(semiannual): Add semiannual interval to models

---

app/controllers/api/v1/plans/entitlements/privileges_controller.rb
app/controllers/api/v1/plans/entitlements_controller.rb
spec/requests/api/v1/plans/entitlements/privileges_controller_spec.rb
spec/requests/api/v1/plans/entitlements_controller_spec.rb

It's not possible to set entitlements on override plans, they should only work on parent plans.
The entitlements retrieved in `/v1/plans/:code` are correct because the main controller only allow you modify parent plans. 
It's possible right now to retrieve different entitlements from `/v1/plan/:code/entitlements` if the plan has children, since our primary keys are not ordered.
I will ensure in a following PR that the services cannot be called with a child plan (and double check gql).

fix(entitlements): Retrive only parents plan

---

.dockerignore
Dockerfile

Ensured apt update and package installations are performed before setting the working directory and copying application files to avoid invalidating layer caches

chore: update Dockerfile for better layer caching

---

config/environments/test.rb

5e8cc0acb72e9992569698688a3f6f5b49ff06d9 disabled the logs in test to speed up the test suite. This make sense in a CI context but make it harder to debug in dev environment.
This update the Rails configuration to only disable test logging on CI.

test(log): Enable test log in dev environment

---

app/graphql/types/wallets/recurring_transaction_rules/create_input.rb
app/graphql/types/wallets/recurring_transaction_rules/object.rb
app/graphql/types/wallets/recurring_transaction_rules/update_input.rb
schema.graphql
schema.json
spec/factories/wallets.rb
spec/graphql/mutations/wallets/create_spec.rb
spec/graphql/mutations/wallets/update_spec.rb
spec/graphql/resolvers/wallet_resolver_spec.rb
spec/services/wallets/threshold_top_up_service_spec.rb

👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
Follow up of https://github.com/getlago/lago-api/pull/4282.
This adds a `transaction_name` to the wallet transaction recurring rule GraphQL types that are then used to populate the name of the triggered wallet transactions.

feat(wallet-transaction): Add `transaction_name` to wallet transaction rules GraphQL types

---

spec/requests/api/v1/subscriptions_controller_spec.rb

I got the following flaky test on one of my CI run:
```sh
1) Api::V1::SubscriptionsController PUT /api/v1/subscriptions/:external_id when the plan has already been overriden when progressive billing premium integration is present updates a subscription
Got 2 failures:
1.1) Failure/Error:
expect(first_charge).to match(
{
lago_id: Regex::UUID,
lago_billable_metric_id: overriden_package_charge.billable_metric.id,
invoice_display_name: "Setup",
billable_metric_code: overriden_package_charge.billable_metric.code,
created_at: Regex::ISO8601_DATETIME,
charge_model: "package",
invoiceable: true,
regroup_paid_fees: nil,
expected {:applied_pricing_unit => {:code => "ETH", :conversion_rate => "40.0"}, :billable_metric_code => "ufq...go_id => "f8f752f8-a464-4a24-aa96-9d5e52acd51f", :name => "VAT", …
```

test(subscription): Fix flaky subscription test

---

app/controllers/api/v1/subscriptions_controller.rb
app/controllers/concerns/api_errors.rb
spec/requests/api/v1/add_ons_controller_spec.rb
spec/requests/api/v1/billable_metrics_controller_spec.rb
spec/requests/api/v1/billing_entities_controller_spec.rb
spec/requests/api/v1/coupons_controller_spec.rb
spec/requests/api/v1/credit_notes_controller_spec.rb
spec/requests/api/v1/customers/usage_controller_spec.rb
spec/requests/api/v1/customers_controller_spec.rb
spec/requests/api/v1/events_controller_spec.rb
spec/requests/api/v1/features_controller_spec.rb
spec/requests/api/v1/fees_controller_spec.rb
spec/requests/api/v1/plans/entitlements_controller_spec.rb
spec/requests/api/v1/plans_controller_spec.rb
spec/requests/api/v1/subscriptions_controller_spec.rb
spec/requests/api/v1/taxes_controller_spec.rb
spec/requests/api/v1/wallet_transactions_controller_spec.rb
spec/requests/api/v1/wallets_controller_spec.rb
spec/scenarios/credit_note_spec.rb
spec/scenarios/subscriptions/terminate_manually_spec.rb

`:unprocessable_entity` has been deprecated:
```sh
/usr/local/bundle/gems/actionpack-8.0.2.1/lib/action_controller/metal/rendering.rb:235: warning: Status code :unprocessable_entity is deprecated and will be removed in a future version of Rack. Please use :unprocessable_content instead.
/usr/local/bundle/gems/rspec-rails-6.1.5/lib/rspec/rails/matchers/have_http_status.rb:219: warning: Status code :unprocessable_entity is deprecated and will be removed in a future version of Rack. Please use :unprocessable_content instead.
```
We should now use `:unprocessable_content`.
This updates all occurrences of `:unprocessable_entity` in the controllers and request tests. Note that the GraphQL still uses the `"unprocessable_entity"` code.

fix(deprecation): Use `:unprocessable_content` over `:unprocessable_entity`

---

app/services/charges/create_service.rb
app/services/plans/chargeables_validation_service.rb
spec/services/charges/create_service_spec.rb

Updating a subscription payload is not aligned with creating one.
Creating one only requires an `id` for charge override. However, the update one requires both the `id` **AND** the `billable_metric_id`.
The goal of this PR is to be able to update an existing subscription by passing a charge without its `billable_metric_id`.

fix: Ability to update a subscription without passing bm_id

---

app/services/integrations/aggregator/invoices/payloads/netsuite.rb
spec/services/integrations/aggregator/invoices/payloads/netsuite_spec.rb

Netsuite invoice param `trandate` was only added unless tax nexus was configured.
This PR fixes the Netsuite invoice payload - `trandate` is now present in all cases.

fix(netsuite): Add trandate param to invoice payload

---

app/jobs/lifetime_usages/recalculate_and_check_job.rb
app/services/lifetime_usages/check_thresholds_service.rb
app/services/usage_monitoring/process_subscription_activity_service.rb
spec/jobs/lifetime_usages/recalculate_and_check_job_spec.rb
spec/services/usage_monitoring/process_subscription_activity_service_spec.rb

Sometimes `UsageMonitoring::ProcessSubscriptionActivityService` and `LifetimeUsages::RecalculateAndCheckJob` are performed at the same time.
This leads to a lot of `Idempotency::IdempotencyError` as a logic to avoid duplicating invoices is in place to prevent the same usage threshold from being billed twice.
In some rare situtation (when we are out of luck) it could lead to a double invoicing of the same thresold, with the amount of the first invoice immediately re-credited on the second one. This situation is related to a race condition appearing when the `LifetimeUsages::CalculateService` start to process just before the commit of the Idempotent transaction.
It appears that the `Idempotent.transaction` is not enough to mitigate this situation as it does not cover the full computation …

fix(progressive_billing): Avoid parallel processing

---

app/models/wallet.rb
app/models/wallet_transaction.rb
app/services/wallet_transactions/create_from_params_service.rb
app/services/wallets/create_service.rb
spec/factories/wallet_transactions.rb
spec/factories/wallets.rb
spec/models/wallet_spec.rb
spec/models/wallet_transaction_spec.rb
spec/services/wallet_transactions/create_from_params_service_spec.rb
spec/services/wallets/create_service_spec.rb

Because `ActiveModel::Type::Boolean.new.cast(nil)` returns `nil` and the `invoice_requires_successful_payment` has a `NOT NULL` db constraint, we fail to create a wallet or wallet transaction when `invoice_requires_successful_payment` is set to `nil`.
This fixes this behavior by defaulting to `false` when creating a wallet and defaulting to the wallet's value when creating a transaction. Validations were also added on the model to ensure saving such value will fail.

fix(wallet): Fix behavior when `invoice_requires_successful_payment` is nil

---

app/controllers/api/v1/subscriptions_controller.rb
app/models/organization.rb
schema.graphql
schema.json
spec/graphql/types/integrations/premium_integration_type_enum_spec.rb
spec/models/organization_spec.rb
spec/requests/api/v1/subscriptions_controller_spec.rb

This feature was introduced in March in #3262 as a _beta_ feature.
The _beta_ aspect was handled by a premium integration. I'm removing the premium integration to release the feature in _GA_.
Note that "removing" integration isn't something too common, all apps with this integration would be considered invalid. 
I propose to introduce a list of previous integrations. 
Another way is a db migration to remove the data but it creates "down time" where the feature is removed from DB but the code still rely on this flag. I think this can be done later, if the list grows.

chore(stripe): Remove "beta" for Stripe pre-auth feature

---

app/contracts/queries/customers_query_filters_contract.rb
app/controllers/api/v1/customers_controller.rb
app/queries/base_filters.rb
app/queries/customers_query.rb
spec/contracts/queries/customers_query_filters_contract_spec.rb
spec/queries/base_filters_spec.rb
spec/queries/customers_query_spec.rb
spec/requests/api/v1/customers_controller_spec.rb

The filtering on the `GET /api/v1/customers` endpoint is too limited.
This adds a `has_tax_identification_number` filter to this endpoint.

feat(customer): Add `has_tax_identification_number` filter to `GET /api/v1/customers`

---

spec/scenarios/wallets/__snapshots__/Wallet_Transaction_with_rounding/rounds_the_amount_field_when_handling_paid_credits.html.snap
spec/scenarios/wallets/topup_with_rounding_spec.rb
spec/support/pdf_helper.rb

We currently have some scenario tests related to wallet top-up but they don't actually test the impact on the generated PDF.
This adds an assertion on the wallet top-up scenario test to render and test the invoice via snapshot testing.
In order to do that, I had to modify the `stub_pdf_generation` to use the rendered HTML instead of a blank PDF in the mocked response. This way, the invoice file will contain the rendered HTML which we can test using `expect(invoice.file.download).to match_html_snapshot`. Note that the mocked response is currently not used and has no impact the test suite.

test(wallet): Test invoice rendering in wallet top-up scenarios tests

---

app/contracts/queries/customers_query_filters_contract.rb
app/controllers/api/v1/customers_controller.rb
app/queries/customers_query.rb
spec/contracts/queries/customers_query_filters_contract_spec.rb
spec/queries/customers_query_spec.rb
spec/requests/api/v1/customers_controller_spec.rb

The filtering on the `GET /api/v1/customers` endpoint is too limited.
This adds a `metadata[key]` filter to this endpoint.

feat(customer): Add `metadata[key]` filter to `GET /api/v1/customers`

---

app/services/events/stores/clickhouse/unique_count_query.rb
app/services/events/stores/postgres/unique_count_query.rb
app/services/events/stores/postgres_store.rb
spec/services/billable_metrics/prorated_aggregations/unique_count_service_spec.rb
spec/services/events/stores/clickhouse_store_spec.rb
spec/services/events/stores/postgres_store_spec.rb

when for uniq count we post several events per day like:
27th June - 10:00 - property - Add
27th June - 11:00 - property - Remove
27th June - 12:00 - property - Add
27th June - 13:00 - property - Remove
current logic will count it as two events with minimal length of
proration 1 day, so the customer will be charged for 2 prorated days of
usage.
Instead, we want to group events by day, because we prorate them through
day, and for one day record only one event
another scenario:
27th June - 10:00 - property - Add
28th June - 10:00 - property - Remove
28th June - 11:00 - property - Add
if we "end" usage on 28th, the first Add event will "cover" usage on
28th. The event received on 28th will not do the double charge on 28th,
and will "start" on 29th, but: as result anyway we'll charge for the …

fix(event-aggregation): the query should group prorated units by day

---

app/graphql/resolvers/customers_resolver.rb
app/graphql/types/customers/metadata/filter.rb
schema.graphql
schema.json
spec/graphql/resolvers/customers_resolver_spec.rb
spec/graphql/types/customers/metadata/filter_spec.rb

The filtering on the `GET /api/v1/customers` endpoint was too limited so we added a few filters:
- https://github.com/getlago/lago-api/pull/4377
- https://github.com/getlago/lago-api/pull/4378
- https://github.com/getlago/lago-api/pull/4383
- https://github.com/getlago/lago-api/pull/4386
- https://github.com/getlago/lago-api/pull/4392
- https://github.com/getlago/lago-api/pull/4393
This adds those filters to the `customers` GraphQL query as well.
Note that GraphQL doesn't allow arbitrary map/hash as type so I had to create a specific type for the `metadata` filter.

feat(customer): Add more filters to `customers` GraphQL query

---

app/graphql/types/integration_mappings/update_input.rb
app/services/integration_mappings/update_service.rb
spec/graphql/mutations/integration_mappings/update_spec.rb
spec/graphql/types/integration_mappings/update_input_spec.rb
spec/services/integration_mappings/update_service_spec.rb

When updating a integration mapping, it doesn't really make sense to update the `mappable_id`, `mappable_type` and `integration_id` as this mapping is intrinsically bound to the `integration` and `mappable`. For instance, one would never "move" a mapping from one integration to the other.
Also when updating an integration mapping, [the frontend is currently resending the same data as it received](https://github.com/getlago/lago-front/blob/2c4967927a0c7bb34af7c48784f1f32fd457113d/src/components/settings/integrations/NetsuiteIntegrationMapItemDialog.tsx#L304-L306). 
Therefore the `integration_id`, `mappable_id`, `mappable_type` arguments of the `update_integration_mapping` GraphQL query are currently unnecessary. 
This PR removes the code related these field update for the sake of …

chore(integration): Remove unused code related to integration mapping update

---

app/views/templates/invoices/v4/_progressive_billing_details.slim

We enter this template only with invoices having type `progressive_billing`. Progressive invoice can never be subscription type leading to never showing prepaid credits line in the pdf.

fix(invoice-pdf): Display prepaid credits for progressive billing invoices

---

app/graphql/resolvers/integration_collection_mappings_resolver.rb
app/queries/integration_collection_mappings_query.rb
schema.graphql
schema.json
spec/graphql/resolvers/integration_collection_mappings_resolver_spec.rb
spec/queries/integration_collection_mappings_query_spec.rb

The frontend is currently not using the `mappingType`, `page` and `limit` attributes of the `integrationCollectionMappings` query:
```sh
⋊> rg -B 1 'integrationCollectionMappings\('
src/generated/graphql.tsx
24722-    query getAnrokIntegrationCollectionMappings($integrationId: ID!) {
24723:  integrationCollectionMappings(integrationId: $integrationId) {
--
25155-    query getAvalaraIntegrationCollectionMappings($integrationId: ID!) {
25156:  integrationCollectionMappings(integrationId: $integrationId) {
--
25852-    query getNetsuiteIntegrationCollectionMappings($integrationId: ID!) {
25853:  integrationCollectionMappings(integrationId: $integrationId) {
--
26251-    query getXeroIntegrationCollectionMappings($integrationId: ID!) {
26252:  integrationCollectionMappings(integrationId: …
```

chore(integration): Remove unused `integration_collection_mappings` code

---

config/environments/development.rb

The default cache store in development is currently the `ActiveSupport::Cache::NullStore` instead of Redis. I believe this might be due to an unwanted change during a Rails upgrade.
This updates the cache store to use Redis.

chore(cache): Use Redis as development cache store

---

app/services/fees/apply_taxes_service.rb
app/services/fees/fixed_charge_service.rb
app/services/fixed_charge_events/aggregations/base_service.rb
app/services/fixed_charge_events/aggregations/prorated_aggregation_service.rb
spec/services/fees/apply_taxes_service_spec.rb
spec/services/fees/fixed_charge_service_spec.rb

Add a service that generates fees for a fixed_charge. It uses calls aggregation to see how much units should be billed, and then applies charge model on the aggregation result, and then creates fee. By default it does not apply taxes, but a flag can be passed to apply taxes
- added `Fees::FixedChargeService`

Feat(fixed_charges-16): generate fees
